### ISSUE TITLE
Cleanup uses of prihdr and header in the FITS docs

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#6643] opened 2017-10-02 12:58 UTC
@MSeifert04 fixed an instance of variable names changing half way through the io.fits docs in one place - however there are other places where this happens, e.g. in the headers.rst file:

https://github.com/astropy/astropy/blame/master/docs/io/fits/usage/headers.rst#L138

Fundamentally the issue is that we are skipping the doctests in all these files, which is bad! We really should fix the examples so they actually run (and with data we can put on data.astropy.org, no excuse really)

I also think ``header`` makes more sense than ``prihdr`` as a variable name. It would be great to fix this soon since there have been some complaints/confusion.

**Comment by MSeifert04** [comment] 2017-10-02 13:00
@astrofrog You're right. I actually opened https://github.com/astropy/pytest-remotedata/issues/5 because that would allow to conditionally run the doctests when remote data is given.

**Comment by bsipocz** [comment] 2017-10-02 13:02
This seems to be the duplicate of https://github.com/astropy/astropy/issues/6010

**Comment by saimn** [comment] 2017-10-02 13:05
> This seems to be the duplicate of #6010

Yep (I was looking for the issue number).

**Comment by astrofrog** [comment] 2017-10-02 13:05
@bsipocz - ah yes, though not quite a duplicate, here I mean specifically we need to improve consistency of the variable names, i.e. we could enable doctests and keep inconsistent variable names between pages. This issue is first and foremost about fixing the current names, which we could do before the pytest plugin has what @MSeifert04 needs.

**Comment by saimn** [comment] 2017-10-02 13:08
> I also think header makes more sense than prihdr as a variable name.

For the specific case addressed by  #6628, I'm not sure: sometimes `header` is too generic, difficult to search for in a page. `prihdr` is easier to spot, and there is less chance that it is already defined for another unrelated example. So just to say that using `header` everywhere is maybe not the solution.

**Comment by astrofrog** [comment] 2017-10-02 13:10
@saimn - right, I see your point. Maybe ``hdr`` is a solution too (just because it might not be clear what the ``pri`` stands for)

**Comment by bsipocz** [comment] 2017-10-02 13:14
(also, to be honest I feel that @embray had a valid point, and while stuff is still needed to be cleaned up, should complaints like that always trigger the highest priority?)

**Comment by pllim** [comment] 2017-10-02 14:26
@drdavella was working on making those FITS tests run.

**Comment by MSeifert04** [comment] 2017-10-02 14:30
@pllim Thanks for the info, I was just about to start working on this. 😄

**Comment by pllim** [comment] 2017-10-02 14:34
Not sure if he's still working on it, given ASDF and `pytest` work. But if he's not, at least grab what he has already done first before duplicating work. FYI.

**Comment by astrofrog** [comment] 2017-10-02 14:49
> (also, to be honest I feel that @embray had a valid point, and while stuff is still needed to be cleaned up, should complaints like that always trigger the highest priority?)

The priority high label is a bit too much I agree, but to me cleaning up the docs should actually take precedence on internal code cleanup. I just wanted to make sure this didn't get ignored (it worked!).

**Comment by drdavella** [comment] 2017-10-02 15:37
@pllim, @MSeifert04, unfortunately this is near the bottom of my to-do list at the moment. I pushed some work to https://github.com/drdavella/astropy/tree/enable-fits-doctest. I didn't get too far with it, but maybe it's a good starting point.

**Comment by MSeifert04** [comment] 2017-10-02 15:43
thanks for the fast reply @drdavella , I'll have a look at your PR and see how far I can get 😄

**Comment by saimn** [comment] 2017-10-07 22:05
Closing since #6664 addressed this (using `hdr` instead of `prihdr`).

**Closed by saimn** 2017-10-07 22:05 UTC
Labels: Docs, io.fits
