### ISSUE TITLE
Quantity causing memory leak

### ISSUE THREAD

**Issue by kyleaoman** [astropy/astropy#8507] opened 2019-03-19 10:59 UTC
Ran into a memory leak that seems to be related to applying a boolean mask to a astropy.units.Quantity array. Here's a minimal example:

```python
import astropy.units as U
import numpy as np

# no memory leak
arr = np.ones(100)
mask = np.ones(arr.shape, dtype=np.bool)
while True:
    arr[mask]

# memory leak
arr = np.ones(100) * U.pix
mask = np.ones(arr.shape, dtype=np.bool)
while True:
    arr[mask]
```

Note that running this directly won't leak because it will stay in the first infinite loop, which doesn't leak.

```
koman@pleiades> python
Python 3.7.0 (default, Jun 28 2018, 13:15:42) 
[GCC 7.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import astropy
>>> astropy.__version__
'3.1.2'
>>>
```
Also tried using the current dev branch, the leak persists there as well.

**Comment by mhvk** [comment] 2019-03-19 15:31
Hmm, I cannot reproduce this on my Debian machine (with astropy 3.1.1 and something close to current master).

What numpy version are you using? (mine is 1.16.1, python 3.7.2; GCC 8.2.0)

**Comment by pllim** [comment] 2019-03-19 15:54
Can you please try profiling the memory and see?

https://pypi.org/project/memory-profiler/

**Comment by kyleaoman** [comment] 2019-03-19 16:01
> Hmm, I cannot reproduce this on my Debian machine (with astropy 3.1.1 and something close to current master).
> 
> What numpy version are you using? (mine is 1.16.1, python 3.7.2; GCC 8.2.0)

Bug occurs on numpy 1.15.1. It goes away if I upgrade to 1.16.2.



> Can you please try profiling the memory and see?
> 
> https://pypi.org/project/memory-profiler/

Back on numpy 1.15.1, I tried profiling two variations, changing the number of loop iterations by a factor of 100. Here are the two outputs:
```
Line #    Mem usage    Increment   Line Contents
================================================
     5   44.547 MiB   44.547 MiB   @profile
     6                             def f():
     7   44.547 MiB    0.000 MiB       arr = np.ones(100) * U.pix
     8   44.547 MiB    0.000 MiB       mask = np.ones(arr.shape, dtype=np.bool)
     9   45.117 MiB    0.000 MiB       for i in range(1000):
    10   45.117 MiB    0.258 MiB           arr[mask]
```

```
Line #    Mem usage    Increment   Line Contents
================================================
     5   44.605 MiB   44.605 MiB   @profile
     6                             def f():
     7   44.605 MiB    0.000 MiB       arr = np.ones(100) * U.pix
     8   44.605 MiB    0.000 MiB       mask = np.ones(arr.shape, dtype=np.bool)
     9  133.035 MiB    0.004 MiB       for i in range(100000):
    10  133.035 MiB    0.258 MiB           arr[mask]
```

**Comment by pllim** [comment] 2019-03-19 16:05
Hmm if it no longer leaks in newer Numpy, then it is probably some Numpy bug upstream?

**Comment by kyleaoman** [comment] 2019-03-19 16:06
Seems likely, yes.

**Comment by mhvk** [comment] 2019-03-19 16:13
OK, found it: https://github.com/numpy/numpy/issues/12037 and fix in https://github.com/numpy/numpy/pull/12127. Tricky because it turned up in derived classes only (which of course includes `Quantity`).

So, I'll close this. 

Thanks for reporting!!

**Closed by mhvk** 2019-03-19 16:13 UTC
Labels: Bug, Needs-clarification, units
