### ISSUE TITLE
TST: apply_space_motion no longer emits ErfaWarning in remote data/dev job

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#10648] opened 2020-08-13 15:40 UTC
Example log: https://travis-ci.org/github/astropy/astropy/jobs/717518434 (first 2 failures)

```
____________________________ test_regression_10092 _____________________________
    def test_regression_10092():
        """
        Check that we still get a proper motion even for SkyCoords without distance
        """
        c = SkyCoord(l=10*u.degree, b=45*u.degree,
                     pm_l_cosb=34*u.mas/u.yr, pm_b=-117*u.mas/u.yr,
                     frame='galactic',
                     obstime=Time('1988-12-18 05:11:23.5'))
    
        with pytest.warns(ErfaWarning, match='ERFA function "pmsafe" yielded .*'):
            # expect ErfaWarning here
>           newc = c.apply_space_motion(dt=10*u.year)
E           Failed: DID NOT WARN. No warnings of type (<class 'erfa.core.ErfaWarning'>,) matching ('ERFA function "pmsafe" yielded .*') was emitted. The list of emitted warnings is: [ErfaWarning('ERFA function \'pmsafe\' yielded 1 of "distance overridden (Note 6)"')].
../../.tox/py37-test-devdeps/lib/python3.7/site-packages/astropy/coordinates/tests/test_regression.py:641: Failed
___________________________ test_apply_space_motion ____________________________
    def test_apply_space_motion():
        # use this 12 year period because it's a multiple of 4 to avoid the quirks
        # of leap years while having 2 leap seconds in it
        t1 = Time('2000-01-01T00:00')
        t2 = Time('2012-01-01T00:00')
    
        # Check a very simple case first:
        frame = ICRS(ra=10.*u.deg, dec=0*u.deg,
                     distance=10.*u.pc,
                     pm_ra_cosdec=0.1*u.deg/u.yr,
                     pm_dec=0*u.mas/u.yr,
                     radial_velocity=0*u.km/u.s)
    
        # Cases that should work (just testing input for now):
        c1 = SkyCoord(frame, obstime=t1, pressure=101*u.kPa)
        with pytest.warns(ErfaWarning, match='ERFA function "pmsafe" yielded .*'):
            # warning raised due to high PM chosen above
            applied1 = c1.apply_space_motion(new_obstime=t2)
>           applied2 = c1.apply_space_motion(dt=12*u.year)
E           Failed: DID NOT WARN. No warnings of type (<class 'erfa.core.ErfaWarning'>,) matching ('ERFA function "pmsafe" yielded .*') was emitted. The list of emitted warnings is: [ErfaWarning('ERFA function \'pmsafe\' yielded 1 of "distance overridden (Note 6)"'), ErfaWarning('ERFA function \'pmsafe\' yielded 1 of "distance overridden (Note 6)"')].
../../.tox/py37-test-devdeps/lib/python3.7/site-packages/astropy/coordinates/tests/test_sky_coord.py:1613: Failed
```

If the warning is no longer emitted on purpose, `pytest.warns` needs to be removed. Otherwise, if a warning is expected, this is a symptom of a bug.

**Comment by StuartLittlefair** [comment] 2020-08-13 16:01
I **think** this is caused by moving to an external ```pyerfa``` package. The code does emit *an* ```ErfaWarning``` but it's the one from ```pyerfa``` and not from ```astropy.utils.exceptions```.

[This line](https://github.com/astropy/astropy/blob/master/astropy/coordinates/tests/test_regression.py#L25) needs changing to 

```python
from erfa import ErfaWarning
```

**Comment by pllim** [comment] 2020-08-13 16:10
Weird, pyerfa PR was merged some weeks ago, so why does this only crop up now?

**Comment by StuartLittlefair** [comment] 2020-08-13 16:13
Don't know - that's only a hunch; I'm unable to get my tests to run locally to check.

**Closed** 2020-08-14 15:18 UTC
Labels: coordinates, testing
