### ISSUE TITLE
Save Units of columns into files with ascii.write()

### ISSUE THREAD

**Issue by Emberck** [astropy/astropy#4743] opened 2016-03-28 15:43 UTC
I've noticed that there's no straightforward way to write out the units of a column in a generic way using astropy.table or astropy.io.ascii.

When you print the table on the terminal the Units appear correctly under the col-name but there's no way to save them into a file.

Similar to  #4112

**Comment by pllim** [comment] 2016-03-28 15:53
What if you use `my_table.write(my_filename, format='ipac')`? You should get something like this:

```|wavelength|                  flux|
|    double|                double|
|    micron|erg / (Angstrom cm2 s)|
|      null|                  null|
     0.0805      2.91125425657e-17 
     0.0815      3.05136210514e-17 
     0.0825      3.22549746131e-17 
     0.0835      2.78810781295e-17 
            ...                                    ...
```

**Comment by Emberck** [comment] 2016-03-28 16:03
Yes but that only work if you need an IPAC table, not with any of the other formats available and for example the 'fixed_width' (in any of it's 3 forms) won't work...
So you are unable to get something like this:

             Name | Morphology  |        ra_u |       dec_u  | ...
                  | InNS+B+MOI  | HH:MM:SS.SSS| ±DD:MM:SS:SSS| ...
     =============| ==========  | =========== | ============ | ...
     1_Cam_A      |    I        |04:32:01.845 | +53:54:39.03 | ...

and sadly the IPAC format isn't always the best format, that's why I want to make this Feature Request.

**Comment by taldcroft** [comment] 2016-03-28 16:06
The `ecsv` format is the recommended generic way to write out to an ASCII file with units and all other metadata encapsulated.  That format will round-trip and is readable by most generic CSV readers.

**Comment by pllim** [comment] 2016-03-28 16:13
@Emberck , does `ecsv` as suggested by @taldcroft work for you? IMHO writing out units in fixed width format is not always desirable as some unit names can be a lot longer than your data.

**Comment by Emberck** [comment] 2016-03-28 16:27
I will try to play a little with `ecsv` and tell you how it went
And @pllim I'm basically are with you but it's a request from the Boss... 
Thanks

**Comment by taldcroft** [comment] 2016-03-28 16:37
See also #2869.

@Emberck - note that the example you show is not including "units", but rather some other metadata which is more like "description".  In astropy, "unit" has a specific meaning as a physical unit.

**Comment by Emberck** [comment] 2016-03-28 16:44
@taldcroft well in my example you can see that I have a mix of metadata and physical units (such as Hours for the coordinates) and in the other cols (in this case it's a very long table) I have `mags` , `seconds` and `deg` which are included in `astropy.units` and have actual physical meaning.

**Comment by taldcroft** [comment] 2016-03-28 17:15
Anyway, here is a workaround that is reasonably close to your desired output:
```
In [5]: t
Out[5]: 
<Table length=3>
  a      b     c  
int64 float64 str1
----- ------- ----
    1     1.0    c
    2     2.0    d
    3     3.0    e

In [6]: t['a'].unit = 'whatever'

In [7]: t['b'].unit = 'seconds'

In [8]: t['c'].unit = 'HH:MM:DDD'

In [9]: lines = t.pformat(max_width=-1, max_lines=-1, show_dtype=False)

In [11]: with open('myfile.dat', 'w') as fh:
   ....:     fh.write('\n'.join(lines))

In [12]: cat myfile.dat
   a        b        c    
whatever seconds HH:MM:DDD
-------- ------- ---------
       1     1.0         c
       2     2.0         d
       3     3.0         e
```

**Comment by Emberck** [comment] 2016-03-28 17:37
Thanks @taldcroft 
Yep that should work, now I'm doing something similar and there's also an option with an `ipac` table after saving the table you remove the `null` and `Data Types` rows...

In any case I think that would be nice to have the option of adding the 'Units row' within the `ascii.write ` the same way that you can add the 'Names row'  without workarounds...

That's why I send this Feature Request, and since `write ` already save the row if the `ipac` format is used I guess it should't be much trouble...

Again thanks

P.D.: I'm been playing around with the `ecsv` output but so far I don't think it would work for me... still I will keep trying for a while

**Comment by taldcroft** [comment] 2016-03-28 17:43
Do you have a requirement to be able to read such files back?

**Comment by Emberck** [comment] 2016-03-28 17:48
Yes, I need to be able to read the files in Python, IDL and by a human that's why I'm having such troubles finding just the right format

**Comment by keflavich** [comment] 2019-11-24 20:05
This is a duplicate of https://github.com/astropy/astropy/issues/756.  afaict, it's exactly the same.  So I suppose we're now at the timescale of looking at this issue approximately once every three years.

**Comment by taldcroft** [comment] 2019-11-25 11:49
Closing this as a duplicate of #756.

**Closed by taldcroft** 2019-11-25 11:49 UTC
Labels: Duplicate, Feature Request, io.ascii
