### ISSUE TITLE
astropy.io.fits: writeto() error with Binary HDU

### ISSUE THREAD

**Issue by seclark** [astropy/astropy#4253] opened 2015-10-20 17:57 UTC
I'm using python 2.7.9, but this error was reported to me by a user with python 2.7.10. The following example works for astropy 1.0.1, but fails with astropy 1.0.5 (numpy 1.10.1). The error is very similar to [Issue #2748](https://github.com/astropy/astropy/issues/2748), but is occurring for a binary HDU, or an HDU list that includes a binary HDU. 

```javascript
from astropy.io import fits
import numpy as np

# Data
test_data = np.zeros((200,200), np.float_)
hi = np.zeros(100, np.float_)
hj = np.zeros(100, np.float_)
hthets = np.zeros((1, 200), np.float_)

Hi = fits.Column(name='hi', format='1I', array=hi)
Hj = fits.Column(name='hj', format='1I', array=hj)
ntheta = hthets.shape[1]
Hthets = fits.Column(name='hthets', format=str(int(ntheta))+'E', array=hthets)
cols = fits.ColDefs([Hi, Hj, Hthets])
tbhdu = fits.BinTableHDU.from_columns(cols)

# Header Values 
prihdr = fits.Header()
prihdr['WLEN'] = 9.0

# Whole FITS File
prihdu = fits.PrimaryHDU(data=test_data, header=prihdr)
thdulist = fits.HDUList([prihdu, tbhdu])
thdulist.writeto("test.fits", output_verify='silentfix', clobber=True, checksum=True)
```

This fails with output:

```javascript
WARNING: AstropyDeprecationWarning: Config parameter 'enabled_record_valued_keyword_cards' in section [io.fits] of the file '/Users/susanclark/.astropy/config/astropy.cfg' is deprecated. Use 'enable_record_valued_keyword_cards' in section [io.fits] instead. [astropy.config.configuration]
ERROR: TypeError: object of type 'NoneType' has no len() [astropy.io.fits.fitsrec]
Traceback (most recent call last):
  File "mwe.py", line 23, in <module>
    thdulist.writeto("test.fits", output_verify='silentfix', clobber=True, checksum=True)
  File "/usr/local/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 680, in writeto
    hdu._prewriteto(checksum=checksum)
  File "/usr/local/lib/python2.7/site-packages/astropy/io/fits/hdu/table.py", line 527, in _prewriteto
    return super(_TableBaseHDU, self)._prewriteto(checksum, inplace)
  File "/usr/local/lib/python2.7/site-packages/astropy/io/fits/hdu/base.py", line 568, in _prewriteto
    self._update_checksum(checksum)
  File "/usr/local/lib/python2.7/site-packages/astropy/io/fits/hdu/base.py", line 625, in _update_checksum
    datasum_keyword=datasum_keyword)
  File "/usr/local/lib/python2.7/site-packages/astropy/io/fits/hdu/base.py", line 1403, in add_checksum
    datasum_keyword=datasum_keyword)
  File "/usr/local/lib/python2.7/site-packages/astropy/io/fits/hdu/base.py", line 1353, in add_datasum
    cs = self._calculate_datasum(blocking)
  File "/usr/local/lib/python2.7/site-packages/astropy/io/fits/hdu/table.py", line 834, in _calculate_datasum
    return self._calculate_datasum_with_heap(blocking)
  File "/usr/local/lib/python2.7/site-packages/astropy/io/fits/hdu/table.py", line 804, in _calculate_datasum_with_heap
    csum = self._compute_checksum(dout, blocking=blocking)
  File "/usr/local/lib/python2.7/site-packages/astropy/io/fits/hdu/base.py", line 1609, in _compute_checksum
    sum32 = self._compute_hdu_checksum(data[i:i + length], sum32)
  File "/usr/local/lib/python2.7/site-packages/astropy/io/fits/fitsrec.py", line 547, in __getslice__
    return self[slice(start, end)]
  File "/usr/local/lib/python2.7/site-packages/astropy/io/fits/fitsrec.py", line 486, in __getitem__
    out = self.view(np.recarray).__getitem__(key).view(subtype)
  File "/usr/local/lib/python2.7/site-packages/astropy/io/fits/fitsrec.py", line 249, in __array_finalize__
    self._nfields = len(obj.dtype.names)
TypeError: object of type 'NoneType' has no len()
```

Note that this traces back to fitsrec.py as in the linked issue.

**Comment by embray** [comment] 2015-10-20 18:18
Just as a quick aside, I personally find that it's much easier to create a table directly from a Numpy structured array, rather than going through the steps of setting up FITS columns individually, etc., as the docs demonstrate (incidentally, I'm also in the process of updating the docs to demonstrate simpler examples first).

For example, I *think*, if I understand correctly, you can create a table with the same format as you demonstrated above like so:

```python
>>> table = np.zeros(200, dtype=[('hi', np.int16), ('hj', np.int16), ('hthets', (np.float32, (200,)))])
>>> table_hdu = fits.BinTableHDU(data=table)
>>> table_hdu.header['WLEN'] = 9.0
>>> table_hdu.writeto('test.fits')
>>> hdul = fits.open('test.fits')
>>> hdul[1].header
XTENSION= 'BINTABLE'           / binary table extension                         
BITPIX  =                    8 / array data type                                
NAXIS   =                    2 / number of array dimensions                     
NAXIS1  =                  804 / length of dimension 1                          
NAXIS2  =                  200 / length of dimension 2                          
PCOUNT  =                    0 / number of group parameters                     
GCOUNT  =                    1 / number of groups                               
TFIELDS =                    3 / number of table fields                         
TTYPE1  = 'hi      '                                                            
TFORM1  = 'I       '                                                            
TTYPE2  = 'hj      '                                                            
TFORM2  = 'I       '                                                            
TTYPE3  = 'hthets  '                                                            
TFORM3  = '200E    '                                                            
WLEN    =                  9.0                                                  
>>> hdul[1].data.dtype
dtype([('hi', '>i2'), ('hj', '>i2'), ('hthets', '>f4', (200,))])
```

Not sure why your example is ending up with a traceback. Definitely looks like a bug.

Oh, also I notice you mentioned Numpy 1.10.1 which isn't fully supported yet--see #3854, #4247, etc.  Now that I look that's probably why.

**Comment by embray** [comment] 2015-10-20 18:26
Okay, confirmed this is fixed by #4228, so this is really just due to Numpy 1.10.  Hoping to have the new version out with the Numpy 1.10 fixes before the end of this week.

Meanwhile, however, my above advice still applies about skipping all FITS-centric interfaces and go directly from a Numpy structured array into a FITS HDU.  But if you prefer the FITS-ish interface that's fine too--it *should* work :)

**Closed by embray** 2015-10-20 18:26 UTC
Labels: io.fits

**Comment by seclark** [comment] 2015-10-20 18:42
Thanks! Good to know about Numpy structured array support -- just hoping to keep my old FITS-centric code alive :). Can confirm that the above code works with astropy 1.0.5 + numpy 1.9.1.

**Comment by embray** [comment] 2015-10-20 19:09
Ah okay, right, I forgot that this was code that used to work and then didn't.  Sorry about that.  Should work with Astropy v1.0.6 + Numpy 1.10.
