### ISSUE TITLE
Rust extensions for astropy ?

### ISSUE THREAD

**Issue by bmatthieu3** [astropy/astropy#7679] opened 2018-07-24 15:03 UTC
Rust is a system language comparable to C/C++ and it is therefore possible to compile it to generate so/dll libraries. Considering this, one can call rust from python exactly as we do it with libraries compiled from C code (cf https://bheisler.github.io/post/calling-rust-in-python/ : the python side code is written considering the external library functions as C ones.)

Does astropy can eventually support the pipeline of compiling Rust code ?

**Comment by MSeifert04** [comment] 2018-07-24 15:38
The issue is probably better suited for astropy helpers i think.

 It would make building from source more complicated because one would need a rust compiler and the appropriate python crate. I don't think the Python infrastructure is ready for rust Extensions. However i think there is some effort in conda forge to make that easier for conda users. At least i have seen that they bundle rust. 

May i ask what prompted the question? Do you want to write extensions for astropy? Or an affiliated package? Or something else entirely?

**Comment by bmatthieu3** [comment] 2018-07-30 09:04
@MSeifert04 thank you for your very accurate answer, we see more clearer and understand why this is more complicated for users wanting to build astropy from source.
This is also very interesting to see that there is some effort made in PyPI (e.g. setuptools-rust) for compiling rust code into multiple binary wheels (for the different existing platforms) and also that there exists a conda-forge recipe that directly bundles the rustc compiler.

We actually are a few in the CDS (Centre de Données de Strasbourg) having discovered rust not too long ago and are really excited about this new system programming language (prevents segfault, thread safety, no abstraction cost, ...).

For the moment we have no particular plan for developing in rust considering that this is quite new for us but would like to maybe in the future. We know some affiliated packages (maybe astropy core packages too ?) like astropy-healpix make use of C extensions bound with cython wrapper to perform optimized and fast computations. Therefore we wanted to know if something comparable considering rust was/will be planned for astropy i.e. use rust for developing optimized extensions callable from Python. (Actually, it was more a question coming from our curiousity too :) ). @fxpineau

**Comment by astrofrog** [comment] 2018-07-30 18:49
I guess one question is whether there is anything in Astropy at the moment that **prevents** you from writing e.g. rust extensions? We just use setuptools to compile extensions using the ``Extension`` class - here is an example for astropy-healpix:

https://github.com/astropy/astropy-healpix/blob/master/astropy_healpix/setup_package.py

So if you wanted, you could choose to use RustExtension from [setuptools-rust](https://github.com/PyO3/setuptools-rust) in a ``setup_package.py`` file in an Astropy package and I think it might just work?

I think the only question is on policy of whether to use this or not. I doubt we'll want to use this in the core package anytime soon since we can't easily guarantee that users would have a rust compiler as @MSeifert04 pointed out, and we'd want to wait for this to be more mainstream. However, we don't impose any restrictions on affiliated packages.

Does this make sense?

**Comment by eteq** [comment] 2018-11-15 16:19
Revisiting this in light of some discussions at the ADASS conference...

@bmatthieu3 - I think @astrofrog covered most of the key elements in https://github.com/astropy/astropy/issues/7679#issuecomment-408970465, but one other point that I think is important:  there needs to be sufficient mindshare available to the Astropy community to be able to support a particular technology/extension.  And since we are only just now managing to get the astronomical community together behind Python, it's a long hill to climb to get a lot of support for something like Rust that has a relatively small ecosystem and knowledgeable developer community currently behind it.

So to summarize this and the above discussion, I *think* the current state is:

* We in *principle* have no objections to using Rust if there is a fairly stable way to hook it into the existing Python build machinery a la how C/Cython/Fortran/whatever extensions usually work.
* There needs to be something concrete that justifies using it - i.e.  faster than a Python-based implementation and somehow demonstrably better than something we currently do in C or the like.
* Actually accepting something that uses this would depend on its complexity and how likely it is that we can support it in the long-term.

So with that in mind, I think this issue is essentially answered: "Yes, we could support this", but also "We don't plan to do so unless someone comes along who wants to put in the effort to make it work for a specific use case"- but of course the latter could well be you, @bmatthieu3 :wink:

Given that, I'm going to close this issue because the initial question is answered.  But if you wanted to actually work on this now and want to use an issue to track it, feel free to re-open, @bmatthieu3!

**Closed by eteq** 2018-11-15 16:19 UTC
Labels: Feature Request, external, question

**Comment by pllim** [comment] 2018-11-15 16:35
IMHO if needed, rather than re-open, this should be an APE proposal -- https://github.com/astropy/astropy-APEs 😄

**Comment by eteq** [comment] 2018-11-15 16:56
Oh and one other thing I should have mentioned above: I think all of that stuff might be easier if there was a clear use case that could live in an *affiliated package*, at least for a time.  That would make it a lot easier to build knowledge about how reliable the build machinery is without having to risk breaking the astropy core itself.  (Although again it's all about the risk-reward tradeoff...)

**Comment by bmatthieu3** [comment] 2019-01-29 10:04
@eteq - I worked on a healpix package that uses rust extensions. Please see https://github.com/cds-astro/cds-healpix-python and its readme for more details.
The idea was to see how the deployment pipeline could work with these extensions. As @astrofrog pointed out, there is a [setuptools_rust](https://github.com/PyO3/setuptools-rust) pip package that offers a way to build the rust wrapping code and its dependency crates (in my example, the [cdshealpix rust crate](https://crates.io/crates/cdshealpix)) into a dynamic library and pack it in a wheel. Having installed [rustup](https://www.rust-lang.org/learn/get-started) and setuptools_rust, you can compile the library on your machine and install it by typing ```python setup.py install```.

For users that do not have the rust compiler installed on their machine I deployed **cdshealpix** on PyPI for different architectures (See https://pypi.org/project/cdshealpix/0.1.3/#files) :
- Windows 32/64 bits with python 2.7/3.4->3.7
- Linux x86_64 and i638 with python 2.7/3.4->3.7
- MacOS with python 2.7/3.4->3.7

I am using [cibuildwheel](https://github.com/joerick/cibuildwheel) with travis-ci (resp. appveyor) for generating the wheels for Linux/Mac (resp. Windows).
You can found the current version of my travis yml file [here](https://github.com/cds-astro/cds-healpix-python/blob/master/.travis.yml).
cibuildwheel can run some bash commands before building the wheels. In my case I install the rust compiler and the setuptools rust pip package. I also add the directory where the rust compiler is installed in the $PATH env variable.
The wheel is then generated and some tests are executed. If the tests pass, the wheel is deployed to PyPI. Wheels generation on travis are split into 3 jobs. One job builds the wheels for linux x86_64, the second for linux i638 and the third for MacOS.

One thing to add: I use [cffi](https://cffi.readthedocs.io/en/latest/overview.html) for loading the dynamic library from python. It relies on declaring some C-style function prototypes so that python "sees" Rust code as it would see C code. Other binding strategies such as [pyo3](https://github.com/PyO3/pyo3) (from the same dev as setuptools rust) exist and prevent us from writing C code.

**Comment by bmatthieu3** [comment] 2019-02-11 09:32
I deleted the version 0.1.2 -> 0.1.4 on PyPI because I realized some files were missing in the wheel (especially the .h file where I define the C function prototypes that does the wrapping between python CFFI code and the Rust code). Therefore there was a problem when importing cdshealpix in a python interpreter because this file could not be found.

Since v0.1.5 (the current version is v0.1.6) this problem is resolved: I refer to the non-python files to be included in the package by specifying them in the **package_data** keyword in the [setup.py](https://github.com/cds-astro/cds-healpix-python/blob/master/setup.py). 

@eteq @astrofrog @MSeifert04 - Now you can test it if you want by installing it via pip: 
```pip install cdshealpix``` or updating it if you have an old version ```pip install -U cdshealpix```
and run the example code snippets of the [README](https://github.com/cds-astro/cds-healpix-python).
