### ISSUE TITLE
Slicing FITS_rec objects produces unexpected dtypes.

### ISSUE THREAD

**Issue by weaverba137** [astropy/astropy#5490] opened 2016-11-22 01:20 UTC
Consider the following snippet:

```python
import numpy as np
from astropy.io import fits

def create_data():
    tbhdu = fits.BinTableHDU.from_columns([
        fits.Column(name='a', format='I', array=np.arange(2**16, dtype=np.int16)),
        fits.Column(name='b', format='I', bscale=1, bzero=2**15, array=np.arange(2**16, dtype=np.uint16))])
    tbhdu.writeto('test_scaled_slicing.fits')

def load_data(nonnegative=False):
    with fits.open('test_scaled_slicing.fits') as hdulist:
        data = hdulist[1].data
    if nonnegative:
        return data[data['a'] >= 0]
    else:
        return data

create_data()
t1 = load_data()
t2 = load_data(True)
assert t1['b'].dtype is np.dtype(np.uint16)
# assert t2['b'].dtype is np.dtype(np.float64)
assert t2['b'].dtype is np.dtype(np.uint16)
```

The second `assert` fails because the slicing the FITS_rec object does not trigger the mechanism that handles the scaling of the column 'b'.  In other words, some data access methods on FITS_rec trigger the scaling but some don't.

If however, I use a method that forces the scaling, then this problem goes away.  Here's an example:

```python
def load_data(nonnegative=False):
    with fits.open('test_scaled_slicing.fits') as hdulist:
        data = hdulist[1].data
    #
    # WORKAROUND
    #
    if any([c.bzero is not None for c in data.columns]):
        foo = [data[k].dtype for k in data.dtype.names]
    if nonnegative:
        return data[data['a'] >= 0]
    else:
        return data
```

That is, merely accessing the dtype of each column triggers the scaling.  Looking into the code itself, it looks like the `._converted` attribute needs to be filled in for slicing to work properly.

**Comment by peppedilillo** [comment] 2024-09-08 18:59
This issue was closed but I can still get the same bug with astropy 6.1.3.

**Comment by neutrinoceros** [comment] 2024-09-09 07:49
@peppedilillo This is surprising given that the resolving PR contained a regression test.
I also couldn't reproduce the problem with either astropy 6.1.3 or 7.0.0dev.
Can you please open a new issue ?

**Comment by peppedilillo** [comment] 2024-09-09 09:13
Yes sure i will. Have you tried removing the comment to the second assert before trying it? I get:

```
    assert t2['b'].dtype is np.dtype(np.float64)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by neutrinoceros** [comment] 2024-09-09 09:30
Oh, I didn't get that *this* was the problematic assert. Indeed I can reproduce it then, and I would recommend re-opening this issue instead of creating a new one.

**Comment by peppedilillo** [comment] 2024-09-09 10:07
@neutrinoceros I cannot re-open the issue. Likely no permissions.

**Comment by neutrinoceros** [comment] 2024-09-09 11:40
I know, this was meant for @weaverba137 or @saimn :)

**Comment by weaverba137** [comment] 2024-09-09 17:25
I also do not see an obvious way to reopen the issue. I also note that #6837 is still open. Is that still genuinely open?

**Comment by pllim** [comment] 2024-09-09 21:38
I re-opened this issue as requested but I will defer to @astrofrog and @saimn for #6837

**Comment by pllim** [comment] 2024-09-09 21:40
Though I wonder if https://github.com/astropy/astropy/issues/5490#issuecomment-2337571266 is from numpy 2.0 🤔 and also why didn't our regression test suite catch it?

**Comment by pllim** [comment] 2024-09-09 21:41
@peppedilillo , can you please give us a minimally reproducible code snippet that *you* encountered? What numpy version? Python version, OS, distro, etc?

**Comment by neutrinoceros** [comment] 2024-09-10 09:27
> Though I wonder if https://github.com/astropy/astropy/issues/5490#issuecomment-2337571266 is from numpy 2.0 🤔 

It's not, the same exception is raised with numpy 1.26

> and also why didn't our regression test suite catch it?

This is indeed confusing. Simon's test from #8982 makes sense to me. I keep wondering if Benjamin meant to refer to the commented `assert` statement in
> The second assert fails 

Because it doesn't make much sense to me to *expect* `float64` where only `16` bits data types were used originally.
@weaverba137 Can you please clarify ?

**Comment by peppedilillo** [comment] 2024-09-10 09:48
> @peppedilillo , can you please give us a minimally reproducible code snippet that _you_ encountered? What numpy version? Python version, OS, distro, etc?

```python
from astropy.io import fits


if __name__ == "__main__":
    hdul = fits.open("mre.fits")
    fields = ["CHANNEL", "PHA", "CID", "SDDID"]
    for field in fields:
        print(f"slice, then access {field} field: ", hdul[2].data[:1][field])
    for field in fields:
        print(f"access field, then access {field} slice: ", hdul[2].data[field][:1])
    hdul.close()
```

This outputs:

```python
slice, then access CHANNEL field:  [array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   2,   2,
          0,   0,   3, 228,   0,   0,   0,   0,   0,  76, 106, 162,  65,
        140,  52,  98,  12,   1, 165,  55,   0,  64, 215,  77,  89, 166,
        110,   0,   0,   0,   2,   0,   0,   0,   0,   0,   0,   0,   2,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   2,   0,   0,   0,   0,   0,  12,  61, 246,   0,   0,
          0,   0,   0,   0,   0,   2,   0,   0,   0,   0,   0,  36, 185,
        226,   0,   0,   0,   0,   0,   0,   0,   2,   0,   0,   0,   0,
          0,  48, 247, 216,   1,   1,  68,  37, 228, 119,   0,   0,   0,
        203], dtype=uint8)                                              ]
slice, then access PHA field:  [array([], dtype=int16)]
slice, then access CID field:  [array([], dtype=uint8)]
slice, then access SDDID field:  [array([], dtype=uint8)]

access field, then CHANNEL slice:  [array([13, 19], dtype=uint8)]
access field, then PHA slice:  [array([21786, 22649], dtype=int16)]
access field, then CID slice:  [array([7, 7], dtype=uint8)]
access field, then SDDID slice:  [array([1, 0], dtype=uint8)]
```


The first four prints are garbage. The last four are correct. Between the two groups the program is working on something and a delay occurr. You can download the input file and the script [here](https://drive.google.com/file/d/1hLkWGYMOAu3ERA3F0uuH33nMjKQi2DDo/view?usp=sharing). Note that the problem occurs also if the fields are set only to `PHA`, which is signed. Some of these columns are variable length.

This occurred to me because I am working on a fits explorer application for the terminal. The application show FITS tables in short "pages". Each page consists of a slice of `FITS_rec`. I can't get the right output because of this problem. I'm trying to work on slices because, if some scaling or other slow astropy operation are carried on the whole table, it would introduce a lot of delays.

Just tested on Debian 12 bookworm, but observed the same behaviour also on windows 11 and MacOS Ventura.
Environment is the following, i'm on anaconda presently:

```
Package           Version
----------------- ------------------
astropy           6.1.3
astropy-iers-data 0.2024.9.2.0.33.23
click             8.1.7
linkify-it-py     2.0.3
markdown-it-py    3.0.0
mdit-py-plugins   0.4.1
mdurl             0.1.2
misfits           0.0.1
numpy             2.1.0
packaging         24.1
pandas            2.2.2
pip               24.2
platformdirs      4.2.2
pyerfa            2.0.1.4
Pygments          2.18.0
python-dateutil   2.9.0.post0
pytz              2024.1
PyYAML            6.0.2
rich              13.8.0
setuptools        72.2.0
six               1.16.0
textual           0.79.1
typing_extensions 4.12.2
tzdata            2024.1
uc-micro-py       1.0.3
wheel             0.44.0
```

**Comment by saimn** [comment] 2024-09-10 16:43
I don't think the data type from the original issue should be float, this line is commented so maybe it was just some trial?

Ah thanks @weaverba137 for commenting :), I was just looking at the issue and writing a comment.

@peppedilillo - your issue is a different one, it has to do with VLA columns. Interestingly if you first access the full columns and then slice it, it works. Please open a new issue.

**Closed by saimn** 2024-09-10 16:43 UTC
Labels: io.fits, Bug

**Comment by pllim** [comment] 2024-09-10 17:12
Thanks, all! I opened https://github.com/astropy/astropy/issues/16990 for you. Please continue there.

**Comment by peppedilillo** [comment] 2024-09-10 18:12
I realize that the commented assert should not work indeed. Thank you for having opened the new issue.
