### ISSUE TITLE
Astropysics Plotting? [newie]

### ISSUE THREAD

**Issue by NickJones2468** [astropy/astropy#3502] opened 2015-02-13 13:07 UTC
Hi,

I know this is Astropy, but this function may have moved over from Astropysics...
I'm doing a 3rd year Astrophysics project and am trying to plot how a star/constellation moves across the sky, depending on the observer's latitude/longitude. 
Some of the Astropysics modules seem to be aimed towards producing results similar to what I would like to achieve. However, I keep getting the same error message with all of the plotting routines.

The message I get is:

```
>>> runfile('C:/Users/Nick/Documents/Uni/Year 3/Project/Python shizz/error.py', wdir=r'C:/Users/Nick/Documents/Uni/Year 3/Project/Python shizz')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Nick\WinPython-64bit-2.7.5.3\python-2.7.5.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 538, in runfile
    execfile(filename, namespace)
  File "C:/Users/Nick/Documents/Uni/Year 3/Project/Python shizz/error.py", line 21, in <module>
    astp.obstools.Site.yearPlot(cardiff_Site, Gamma_CapLoc,startdate=None,n=13,months=12, utc=False,clf=True,colors=None)
  File "C:\Users\Nick\WinPython-64bit-2.7.5.3\python-2.7.5.amd64\lib\site-packages\astropysics\obstools.py", line 1740, in yearPlot
    from .plotting import _mpl_context
ImportError: cannot import name _mpl_context
```

The code that produces this is:

```
import astropysics as astp
from astropysics.constants import *
from astropysics.coords import CoordinateSystem

Gamma_CapRA = astp.coords.coordsys.AngularCoordinate('21h40m05.4563s')
Gamma_CapDec = astp.coords.coordsys.AngularCoordinate('-16:39:44.308')

cardiff_Lat = astp.coords.coordsys.AngularCoordinate('51.4833d')
cardiff_Long = astp.coords.coordsys.AngularCoordinate('-3.1833d')
cardiff_Site = astp.obstools.Site(cardiff_Lat, cardiff_Long, alt=0, tz=None, name=None)

Gamma_CapLoc = astp.coords.coordsys.LatLongCoordinates(long=Gamma_CapRA, lat=Gamma_CapDec, longerr=None, laterr=None, distancepc=None)

astp.obstools.Site.yearPlot(cardiff_Site, Gamma_CapLoc,startdate=None,n=13,months=12, utc=False,clf=True,colors=None)
```

Any help is appreciated

Cheers,
Nick

**Comment by embray** [comment] 2015-02-13 17:44
Hi Nick,

I'm going to close this as it's not an issue with Astropy.  In the future, the [AstroPy mailing list](http://mail.scipy.org/mailman/listinfo/astropy) is a good place for questions like this.  However, feel free to follow up in the comments on this issue since it's already here.  @eteq is the original author of Astropysics and may have something to say here.  I think *most* of the code in your example can be reproduced in Astropy.

**Closed by embray** 2015-02-13 17:44 UTC
