### ISSUE TITLE
exits none zero on updated header

### ISSUE THREAD

**Issue by mshemuni** [astropy/astropy#15780] opened 2023-12-21 21:11 UTC
### Description

astropy crashes and returns a non-zero value when `pixel_to_world` is called on an updated header.

When a transformation is done to the image data, the WCS on the header must be updated. A new WCS can be generated by `fit_wcs_from_points` or any other way.

The new WCS can be converted to a header and be written to the new file. However if one wants to preserve previous header information, the older header must be updated or extended with the new header generated by the new WCS.

After these steps `pixel_to_world` will crash.

### Expected behavior

The new header should have correct WCS so `pixel_to_sky` must be different and correspond to the correct point.

### How to Reproduce

1. `pip install astropy # conda`
2. Get the header using `get_header`
3. create WCS from the header
4. Create new wcs, by doing a transformation on the header. In this case, cropping is applied.
5. Copy the original header. 
6. extend the copied header with the new WCS. Make sure `unique` and `update` is True.
7. Try to use `pixel_to_world`

```python
from astropy.io import fits
from astropy.io.fits import Header
from astropy.wcs import WCS

x, y, w, h = 100, 100, 200, 200

header = fits.getheader("sample.fits")
wcs = WCS(header)
new_wcs = wcs[y:y + h, x:x + w]

new_header: Header = header.copy()
new_header.extend(new_wcs.to_header(), unique=True, update=True)
print(WCS(new_header).pixel_to_world(2, 2))

```

sample file: https://www.astropy.org/astropy-data/tutorials/FITS-images/HorseHead.fits

### Versions

Windows-10-10.0.22631-SP0
Python 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]
astropy 6.0.0
Numpy 1.26.2
pyerfa 2.0.1.1
Scipy 1.11.4
Matplotlib 3.8.2

# None-Conda
Using a none conda python error message appears to be:

```
WARNING: FITSFixedWarning: 'celfix' made the change 'Invalid parameter value'. [astropy.wcs.wcs]
Traceback (most recent call last):
  File "[PATH]\main.py", line 15, in <module>
    print(WCS(new_header).pixel_to_world(2, 2))
          ^^^^^^^^^^^^^^^
  File "[PATH]\local-packages\Python311\site-packages\astropy\wcs\wcs.py", line 600, in __init__
    self.wcs.set()
ValueError: ERROR 5 in wcsset() at line 2808 of file cextern\wcslib\C\wcs.c:
Invalid parameter value.
ERROR 4 in linset() at line 737 of file cextern\wcslib\C\lin.c:
Failed to initialize distortion functions.
ERROR 3 in tpdset() at line 1945 of file cextern\wcslib\C\dis.c:
Unrecognized field name for TPD on axis 1: DQ1.DSS.AMD.1.
```

### Versions

Windows-10-10.0.22631-SP0
Python 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]
astropy 6.0.0
Numpy 1.26.2
pyerfa 2.0.1.1
Scipy 1.11.4
Matplotlib 3.8.2

**Comment by pllim** [comment] 2023-12-21 21:54
I think this is a duplicate of https://github.com/astropy/astropy/issues/7828 reported by @larrybradley a long time ago.

**Closed** 2023-12-30 05:49 UTC
Labels: wcs, Bug, Close?, Duplicate, closed-by-bot
