### ISSUE TITLE
test failures in 1.0rc1 with Python 2.7.8, OS X 10.6.8

### ISSUE THREAD

**Issue by PBarmby** [astropy/astropy#3408] opened 2015-01-30 21:33 UTC
Failures in test_nohome and test_wcsapi_extension.  Both of the tracebacks include
```ImportError numpy version 1.6.0 or later must be installed to use astropy```
-- I do have numpy 1.9.0 but perhaps I messed up my conda environment somehow.

**Comment by mdboom** [comment] 2015-01-30 21:58
Thanks for the report.  Any chance you could post the full traceback?  That might help us get to the root cause.

**Comment by PBarmby** [comment] 2015-01-30 23:24
On Jan 30, 2015, at 4:58 PM, Michael Droettboom <notifications@github.com> wrote:

> Thanks for the report. Any chance you could post the full traceback? That might help us get to the root cause.
> 
> 


Will do; can’t get to it until Monday morning though.

Pauline Barmby
Department of Physics & Astronomy, Western University
1151 Richmond St., London, ON N6A 3K7 Canada
Voice: (519) 661-2111 x81557 Fax: (519) 661-2033

**Comment by PBarmby** [comment] 2015-02-02 14:47
There is a lot of snow between me and my OS X 10.6.8 machine, but I got the same issues under 10.9.5. Here's the traceback:
 
============================= test session starts ==============================
platform darwin -- Python 2.7.8 -- py-1.4.25 -- pytest-2.6.3

Running tests with Astropy version 1.0rc1.
Running tests in /Users/pauline/anaconda/envs/astropy_rc1/lib/python2.7/site-packages/astropy.

Platform: Darwin-13.4.0-x86_64-i386-64bit

Executable: /Users/pauline/anaconda/envs/astropy_rc1/bin/python

Full Python Version: 
2.7.8 |Anaconda 2.1.0 (x86_64)| (default, Aug 21 2014, 15:21:46) 
[GCC 4.2.1 (Apple Inc. build 5577)]

encodings: sys: ascii, locale: UTF-8, filesystem: utf-8, unicode bits: 15
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.9.0
Scipy: 0.14.0
Matplotlib: 1.4.0
h5py: 2.3.1

collected 8461 items

_erfa/tests/test_erfa.py .....
analytic_functions/tests/test_blackbody.py ....
config/tests/test_configs.py .............F.
constants/tests/test_constant.py ..............
constants/tests/test_pickle.py xxxxxxxxx
convolution/tests/test_convolve.py ...............................................................................................................
convolution/tests/test_convolve_fft.py ...................................................................................................................................................................................................................................................................................................................................................
convolution/tests/test_convolve_kernels.py ..............................................................
convolution/tests/test_discretize.py ...s...........s...............
convolution/tests/test_kernel_class.py ............................................................................................................................................................................
convolution/tests/test_pickle.py .xx.xx.xx
coordinates/tests/test_angles.py ............................................................................
coordinates/tests/test_angular_separation.py ....
coordinates/tests/test_api_ape5.py ....s
coordinates/tests/test_arrays.py ..........................
coordinates/tests/test_distance.py .........
coordinates/tests/test_earth.py ........................
coordinates/tests/test_formatting.py ....................
coordinates/tests/test_frames.py .......................
coordinates/tests/test_funcs.py ..
coordinates/tests/test_iau_fullstack.py ....................................................
coordinates/tests/test_matching.py .....
coordinates/tests/test_name_resolve.py ssssss
coordinates/tests/test_pickle.py ....xx.x...xx.x...xx.x.
coordinates/tests/test_representation.py .............................................................................
coordinates/tests/test_sky_coord.py .......................................................................................................................................................................................................................................................................................................................................................................................x..............
coordinates/tests/test_transformations.py ......................
coordinates/tests/accuracy/test_altaz_icrs.py ...x
coordinates/tests/accuracy/test_fk4_no_e_fk4.py .
coordinates/tests/accuracy/test_fk4_no_e_fk5.py .
coordinates/tests/accuracy/test_galactic_fk4.py .
coordinates/tests/accuracy/test_icrs_fk5.py .
cosmology/tests/test_cosmology.py ...................................
cosmology/tests/test_pickle.py ...
io/ascii/tests/test_c_reader.py ...........................x................x.......x.x.............
io/ascii/tests/test_cds_header_from_readme.py ...
io/ascii/tests/test_compressed.py .....
io/ascii/tests/test_connect.py ........................
io/ascii/tests/test_ecsv.py .......
io/ascii/tests/test_fixedwidth.py ............................................................
io/ascii/tests/test_html.py ........s.......
io/ascii/tests/test_ipac_definitions.py ........................................
io/ascii/tests/test_read.py ..................................................................................................................................................................................................
io/ascii/tests/test_types.py ......
io/ascii/tests/test_write.py ..........................
io/fits/tests/test_checksum.py ....................
io/fits/tests/test_connect.py .........................
io/fits/tests/test_core.py ........................................................
io/fits/tests/test_diff.py ..................................
io/fits/tests/test_division.py .....
io/fits/tests/test_groups.py .......
io/fits/tests/test_hdulist.py .........................................
io/fits/tests/test_header.py ..............................................................................................................................................
io/fits/tests/test_image.py ....................................................
io/fits/tests/test_nonstandard.py ...
io/fits/tests/test_structured.py .
io/fits/tests/test_table.py ...............................................................
io/fits/tests/test_uint.py ........
io/fits/tests/test_util.py .
io/misc/tests/test_hdf5.py .......................................
io/misc/tests/test_pickle_helpers.py ....
io/tests/test_registry.py ............................................................
io/votable/tests/converter_test.py ............................................
io/votable/tests/exception_test.py ..
io/votable/tests/table_test.py ..............
io/votable/tests/tree_test.py ...
io/votable/tests/ucd_test.py ..........
io/votable/tests/util_test.py ......................
io/votable/tests/vo_test.py ................................................................................................................................................................................................................................................................................................................................
modeling/tests/test_compound.py ..........................................
modeling/tests/test_constraints.py .....................
modeling/tests/test_core.py ........
modeling/tests/test_fitters.py ...................
modeling/tests/test_functional_models.py .........
modeling/tests/test_input.py ......................................................
modeling/tests/test_mappings.py ......
modeling/tests/test_models.py .......................................................sss........................................s.s.ssssss...
modeling/tests/test_parameters.py .....................................................
modeling/tests/test_polynomial.py .................
modeling/tests/test_projections.py ...................
modeling/tests/test_rotations.py .....
modeling/tests/test_utils.py ..
nddata/tests/test_decorators.py ..........
nddata/tests/test_flag_collection.py ....................
nddata/tests/test_nddata.py ..................................................................
nddata/tests/test_nddata_base.py .
nddata/tests/test_utils.py .........
stats/tests/test_funcs.py .............
stats/tests/test_sigma_clipping.py ...
table/tests/test_column.py ....................................................................................................................................................................
table/tests/test_groups.py ........................................
table/tests/test_init_table.py ......................................................................................................................................................................................................................................................................................................
table/tests/test_item_access.py ........................................................
table/tests/test_jsviewer.py .
table/tests/test_masked.py ..................................................................
table/tests/test_mixin.py .........................................................x.
table/tests/test_np_utils.py .
table/tests/test_operations.py ..........................................................................
table/tests/test_pickle.py ............
table/tests/test_pprint.py ....................................................................................................
table/tests/test_row.py ....................................................................
table/tests/test_subclass.py ....
table/tests/test_table.py ..........................................................................................................................................................................................................................................................................................x..................................................................................................................................................................................................................................................................................................................x........................
tests/test_logger.py ............................
tests/tests/test_imports.py ..
tests/tests/test_open_file_detection.py .
tests/tests/test_quantity_helpers.py .
tests/tests/test_run_tests.py ...[?1034h.....
tests/tests/test_skip_remote_data.py s
tests/tests/test_socketblocker.py ...
time/tests/test_basic.py ..............................................................................
time/tests/test_comparisons.py ...
time/tests/test_delta.py ................................................................................
time/tests/test_guess.py ....
time/tests/test_pickle.py .
time/tests/test_precision.py .......x..
time/tests/test_quantity_interaction.py ............
time/tests/test_sidereal.py ...................
time/tests/test_ut1.py ...s
units/tests/test_equivalencies.py ..................................................
units/tests/test_format.py ....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
units/tests/test_physical.py ......................
units/tests/test_quantity.py ....................................................................
units/tests/test_quantity_array_methods.py ..............x..............x............x.x.............
units/tests/test_quantity_decorator.py sssssssssssss...............
units/tests/test_quantity_non_ufuncs.py xx
units/tests/test_quantity_ufuncs.py ........................................ss.................................................................................................................
units/tests/test_units.py ..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
utils/compat/numpy/tests/test_broadcast_arrays.py ...
utils/iers/tests/test_iers.py .s
utils/tests/test_codegen.py .
utils/tests/test_collections.py .....
utils/tests/test_compat.py .
utils/tests/test_console.py ..................................................
utils/tests/test_data.py .sssss.........s..s..sssss.........s..s.
utils/tests/test_decorators.py .......
utils/tests/test_gzip.py ss
utils/tests/test_introspection.py ....
utils/tests/test_metadata.py ...............
utils/tests/test_misc.py .s...
utils/tests/test_odict.py sssssssssssssssssssssssssssssssssssssssssss
utils/tests/test_state.py ..
utils/tests/test_timer.py .
utils/tests/test_xml.py ........
visualization/scripts/tests/test_fits2bitmap.py ..
visualization/tests/test_interval.py .................
visualization/tests/test_norm.py s.....
visualization/tests/test_stretch.py ...................................................................................................
visualization/tests/test_ui.py ......
vo/client/tests/test_conesearch.py ssssssssssssss...x.
vo/client/tests/test_vos_catalog.py ..............s
vo/samp/tests/test_client.py ....
vo/samp/tests/test_errors.py ...
vo/samp/tests/test_hub.py ..
vo/samp/tests/test_hub_proxy.py .....
vo/samp/tests/test_hub_script.py .
vo/samp/tests/test_standard_profile.py .xx
vo/samp/tests/test_web_profile.py X.
vo/validator/tests/test_inpect.py ....
vo/validator/tests/test_validate.py sss
wcs/tests/test_pickle.py ......
wcs/tests/test_profiling.py ..................................
wcs/tests/test_utils.py ........................................
wcs/tests/test_wcs.py ......................................................................................................................................
wcs/tests/test_wcsprm.py ...........................................................................................x.......
wcs/tests/extension/test_extension.py F

=================================== FAILURES ===================================
_________________________________ test_no_home _________________________________

    def test_no_home():
        # "import astropy" fails when neither $HOME or $XDG_CONFIG_HOME
        # are set.  To test, we unset those environment variables for a
        # subprocess and try to import astropy.
    
        test_path = os.path.dirname(__file__)
        astropy_path = os.path.abspath(
            os.path.join(test_path, '..', '..', '..'))
    
        env = os.environ.copy()
        paths = [astropy_path]
        if env.get('PYTHONPATH'):
            paths.append(env.get('PYTHONPATH'))
        env[str('PYTHONPATH')] = str(os.pathsep.join(paths))
    
        for val in ['HOME', 'XDG_CONFIG_HOME']:
            if val in env:
                del env[val]
    
        retcode = subprocess.check_call(
            [sys.executable, '-c', 'import astropy'],
>           env=env)

config/tests/test_configs.py:325: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

popenargs = (['/Users/pauline/anaconda/envs/astropy_rc1/bin/python', '-c', 'import astropy'],)
kwargs = {'env': {'Apple_PubSub_Socket_Render': '/tmp/launch-FtSKEz/Render', 'CONDA_DEFAULT_ENV': 'astropy_rc1', 'DYLD_LIBRARY_PATH': '', 'FVTMP': '/tmp', ...}}
retcode = 1
cmd = ['/Users/pauline/anaconda/envs/astropy_rc1/bin/python', '-c', 'import astropy']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the Popen constructor.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           CalledProcessError: Command '['/Users/pauline/anaconda/envs/astropy_rc1/bin/python', u'-c', u'import astropy']' returned non-zero exit status 1

../../subprocess.py:540: CalledProcessError
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/pauline/anaconda/envs/astropy_rc1/lib/python2.7/site-packages/astropy/__init__.py", line 76, in <module>
    _check_numpy()
  File "/Users/pauline/anaconda/envs/astropy_rc1/lib/python2.7/site-packages/astropy/__init__.py", line 70, in _check_numpy
    raise ImportError(msg)
ImportError: numpy version 1.6.0 or later must be installed to use astropy
____________________________ test_wcsapi_extension _____________________________

tmpdir = local('/private/var/folders/wb/9bhym3152sxc87rrkkbscnqm0000gn/T/pytest-1/test_wcsapi_extension0')

    def test_wcsapi_extension(tmpdir):
        # Test that we can build a simple C extension with the astropy.wcs C API
    
        setup_path = os.path.dirname(__file__)
        astropy_path = os.path.abspath(
            os.path.join(setup_path, '..', '..', '..', '..'))
    
        env = os.environ.copy()
        paths = [str(tmpdir), astropy_path]
        if env.get('PYTHONPATH'):
            paths.append(env.get('PYTHONPATH'))
        env[str('PYTHONPATH')] = str(os.pathsep.join(paths))
    
        # Build the extension
        # This used to use subprocess.check_call, but on Python 3.4 there was
        # a mysterious Heisenbug causing this to fail with a non-zero exit code
        # *unless* the output is redirected.  This bug also did not occur in an
        # interactive session, so it likely had something to do with pytest's
        # output capture
        p = subprocess.Popen([sys.executable, 'setup.py', 'install',
                              '--install-lib={0}'.format(tmpdir),
                              astropy_path], cwd=setup_path, env=env,
                              stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    
        # Whether the process fails or not this isn't likely to produce a great
        # deal of output so communicate should be fine in almost all cases
        stdout, stderr = p.communicate()
    
        try:
            stdout, stderr = stdout.decode('utf8'), stderr.decode('utf8')
        except UnicodeDecodeError:
            # Don't try to guess about encoding; just display the text
            stdout, stderr = stdout.decode('latin1'), stderr.decode('latin1')
    
        # If compilation fails, we can skip this test, since the
        # dependencies necessary to compile an extension may be missing.
        # If it passes, however, we want to continue and ensure that the
        # extension created is actually usable.  However, if we're on
        # Travis-CI, or another generic continuous integration setup, we
        # don't want to ever skip, because having it fail in that
        # environment probably indicates something more serious that we
        # want to know about.
        if (not (str('CI') in os.environ or
                 str('TRAVIS') in os.environ or
                 str('CONTINUOUS_INTEGRATION') in os.environ) and
            p.returncode):
            pytest.skip("system unable to compile extensions")
            return
    
        assert p.returncode == 0, (
            "setup.py exited with non-zero return code {0}\n"
            "stdout:\n\n{1}\n\nstderr:\n\n{2}\n".format(
                p.returncode, stdout, stderr))
    
        code = """
        import sys
        import wcsapi_test
        sys.exit(wcsapi_test.test())
        """
    
        code = code.strip().replace('\n', '; ')
    
        # Import and run the extension
>       subprocess.check_call([sys.executable, '-c', code], env=env)

wcs/tests/extension/test_extension.py:75: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

popenargs = (['/Users/pauline/anaconda/envs/astropy_rc1/bin/python', '-c', 'import sys;     import wcsapi_test;     sys.exit(wcsapi_test.test())'],)
kwargs = {'env': {'Apple_PubSub_Socket_Render': '/tmp/launch-FtSKEz/Render', 'CONDA_DEFAULT_ENV': 'astropy_rc1', 'DYLD_LIBRARY_PATH': '', 'FVTMP': '/tmp', ...}}
retcode = 1
cmd = ['/Users/pauline/anaconda/envs/astropy_rc1/bin/python', '-c', 'import sys;     import wcsapi_test;     sys.exit(wcsapi_test.test())']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the Popen constructor.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           CalledProcessError: Command '['/Users/pauline/anaconda/envs/astropy_rc1/bin/python', u'-c', u'import sys;     import wcsapi_test;     sys.exit(wcsapi_test.test())']' returned non-zero exit status 1

../../subprocess.py:540: CalledProcessError
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/pauline/anaconda/envs/astropy_rc1/lib/python2.7/site-packages/astropy/__init__.py", line 76, in <module>
    _check_numpy()
  File "/Users/pauline/anaconda/envs/astropy_rc1/lib/python2.7/site-packages/astropy/__init__.py", line 70, in _check_numpy
    raise ImportError(msg)
ImportError: numpy version 1.6.0 or later must be installed to use astropy
 2 failed, 8296 passed, 118 skipped, 44 xfailed, 1 xpassed, 7 warnings in 452.65 seconds

**Comment by astrofrog** [comment] 2015-02-02 14:54
@PBarmby - just a side note for info - you can always include code and tracebacks in triple back-quotes to get it rendered using a fixed-width font (I fixed your comment above), e.g.:

    ```
    traceback here
    ```

**Comment by mdboom** [comment] 2015-02-02 16:58
Both of these are cases where Python is calling out to another Python interpreter, and then not finding things in the environment (like an installed Numpy) in that other interpreter.  I was able to reproduce this by starting with a clean environment, and running astropy's `python setup.py test` in it.  It gets Numpy built enough to use during the build, but not enough so that it's available from subenvironments.

Can you try doing a `conda install numpy` first and let me know if that resolves things?  Doing this in a more automated way will be tricky...

**Comment by astrofrog** [comment] 2015-02-02 17:03
@mdboom - just out of curiosity, why is it that we auto-download Numpy rather than simply crashing if it's not present? Is it to make sure we have access to the header files?

**Comment by mdboom** [comment] 2015-02-02 17:10
We need access to the header files during build, and then we need access to it once Numpy is used.  The auto-downloading generally works fine with `setup.py build` and `setup.py install`, but it seems to break (and only on conda) when *just* doing `setup.py test` (without `setup.py install` first).  It's enough of a corner case that I think we should just document that numpy needs to be installed first and anything else is unsupported -- but first we should confirm this is @PBarmby's problem.  I just guessed and tried something that broke in the same way :wink:

**Comment by PBarmby** [comment] 2015-02-02 17:51
Tried `conda install numpy` and re-ran `py.test`. Almost-but-not-quite-identical output: here's the diff between new and old log:
```
< platform darwin -- Python 2.7.9 -- py-1.4.25 -- pytest-2.6.3
---
> platform darwin -- Python 2.7.8 -- py-1.4.25 -- pytest-2.6.3
12c12
< 2.7.9 |Anaconda 2.1.0 (x86_64)| (default, Dec 15 2014, 10:37:34) 
---
> 2.7.8 |Anaconda 2.1.0 (x86_64)| (default, Aug 21 2014, 15:21:46) 
19c19
< Numpy: 1.9.1
---
> Numpy: 1.9.0
102c102
< modeling/tests/test_models.py .............................................................s..ss..................................ssssssss...
---
> modeling/tests/test_models.py .......................................................sss........................................s.s.ssssss...
149c149
< units/tests/test_quantity_array_methods.py .............................x............x.x.............
---
> units/tests/test_quantity_array_methods.py ..............x..............x............x.x.............
256c256
< tmpdir = local('/private/var/folders/wb/9bhym3152sxc87rrkkbscnqm0000gn/T/pytest-2/test_wcsapi_extension0')
---
> tmpdir = local('/private/var/folders/wb/9bhym3152sxc87rrkkbscnqm0000gn/T/pytest-1/test_wcsapi_extension0')
358c358
<  2 failed, 8297 passed, 118 skipped, 43 xfailed, 1 xpassed, 7 warnings in 425.94 seconds 
---
>  2 failed, 8296 passed, 118 skipped, 44 xfailed, 1 xpassed, 7 warnings in 452.65 seconds 
```

**Comment by embray** [comment] 2015-02-02 18:36
Might be worth adding something to the test runner allowing the package to specify minimum requirements to even run the tests, and immediately blow up the test runner if they're not satisfied (this should definitely be done in a configurable way though and not hard-code the requirements, since affiliated packages use astropy's test runner too).

**Comment by embray** [comment] 2015-02-02 18:39
I think this might have something to do with this:
```
env = os.environ.copy()
        paths = [str(tmpdir), astropy_path]
        if env.get('PYTHONPATH'):
            paths.append(env.get('PYTHONPATH'))
        env[str('PYTHONPATH')] = str(os.pathsep.join(paths))
```
the test copies the user's PYTHONPATH and runs the subprocess with it.

@PBarmby , do you have anything in your `$PYTHONPATH` enviroment variable?  That could have something to do with this.

**Comment by mdboom** [comment] 2015-02-02 18:53
Ok.  So my guess was incorrect -- @embray's question might be on to something, though.

**Comment by PBarmby** [comment] 2015-02-02 19:59
@embray yes, there was a lot of cruft in $PYTHONPATH, but unsetting it and then re-running the tests resulted in the same failures.

**Comment by embray** [comment] 2015-02-02 20:40
It's *conceivable*, albeit unlikely, that for some reason your Python is shoving extra stuff into either `os.environ['PYTHONPATH']` or into `sys.path` at startup.  Hard to say...

**Comment by pllim** [comment] 2016-06-15 14:06
Can we close this?

**Comment by PBarmby** [comment] 2016-06-15 14:21
Sufficiently old that it's not worth following up, IMO.

**Comment by pllim** [comment] 2016-06-15 14:27
Okay. Feel free to open a new issue if you have the same problem with 1.2. Thanks!

**Closed by pllim** 2016-06-15 14:27 UTC
Labels: Close?, installation, testing
