### ISSUE TITLE
1.3.3 fails to build wheel

### ISSUE THREAD

**Issue by anntzer** [astropy/astropy#6130] opened 2017-05-29 22:56 UTC
pip wheel astropy (python 3.6.1 from Arch Linux repos) fails with an interesting traceback...

note that importing just sphinxcontrib.websupport.core or jinja2 does NOT fail with this exception, so I guess something wrong actually happens on astropy's side.
```
Collecting astropy
  Using cached astropy-1.3.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0yrhncsp/astropy/setup.py", line 37, in <module>
        cmdclassd = register_commands(NAME, VERSION, RELEASE)
      File "/tmp/pip-build-0yrhncsp/astropy/.eggs/astropy_helpers-1.2-py3.6.egg/astropy_helpers/setup_helpers.py", line 140, in register_commands
        from .commands.build_sphinx import AstropyBuildSphinx, AstropyBuildDocs
      File "/tmp/pip-build-0yrhncsp/astropy/.eggs/astropy_helpers-1.2-py3.6.egg/astropy_helpers/commands/build_sphinx.py", line 16, in <module>
        from sphinx.setup_command import BuildDoc as SphinxBuildDoc
      File "/usr/lib/python3.6/site-packages/sphinx/setup_command.py", line 23, in <module>
        from sphinx.application import Sphinx
      File "/usr/lib/python3.6/site-packages/sphinx/application.py", line 33, in <module>
        from sphinx.environment import BuildEnvironment
      File "/usr/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 45, in <module>
        from sphinx.util.websupport import is_commentable
      File "/usr/lib/python3.6/site-packages/sphinx/util/websupport.py", line 11, in <module>
        from sphinxcontrib.websupport.utils import is_commentable  # NOQA
      File "/usr/lib/python3.6/site-packages/sphinxcontrib/websupport/__init__.py", line 15, in <module>
        from sphinxcontrib.websupport.core import WebSupport  # NOQA
      File "/usr/lib/python3.6/site-packages/sphinxcontrib/websupport/core.py", line 17, in <module>
        from jinja2 import Environment, FileSystemLoader
      File "/usr/lib/python3.6/site-packages/jinja2/__init__.py", line 33, in <module>
        from jinja2.environment import Environment, Template
      File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 15, in <module>
        from jinja2 import nodes
      File "/usr/lib/python3.6/site-packages/jinja2/nodes.py", line 19, in <module>
        from jinja2.utils import Markup
      File "/usr/lib/python3.6/site-packages/jinja2/utils.py", line 486, in <module>
        MutableMapping.register(LRUCache)
      File "/usr/lib/python3.6/abc.py", line 158, in register
        if issubclass(subclass, cls):
      File "/usr/lib/python3.6/abc.py", line 226, in __subclasscheck__
        if issubclass(subclass, scls):
      File "/usr/lib/python3.6/abc.py", line 226, in __subclasscheck__
        if issubclass(subclass, scls):
      File "/usr/lib/python3.6/typing.py", line 1145, in __subclasscheck__
        return super().__subclasscheck__(cls)
      File "/usr/lib/python3.6/abc.py", line 207, in __subclasscheck__
        ok = cls.__subclasshook__(subclass)
===<elided>===
      File "/usr/lib/python3.6/abc.py", line 207, in __subclasscheck__
        ok = cls.__subclasshook__(subclass)
      File "/usr/lib/python3.6/typing.py", line 877, in __extrahook__
        if issubclass(subclass, scls):
      File "/usr/lib/python3.6/typing.py", line 1145, in __subclasscheck__
        return super().__subclasscheck__(cls)
    RecursionError: maximum recursion depth exceeded while calling a Python object
    
    ----------------------------------------
```

**Comment by bsipocz** [comment] 2017-05-29 23:26
@anntzer - astropy 1.3.3 is known to be incompatible with sphinx 1.6+, would this be related to that?

**Comment by anntzer** [comment] 2017-05-29 23:38
Is that incompatibility specified (in code) somewhere?

**Comment by bsipocz** [comment] 2017-05-30 10:52
@anntzer - This is an upstream issue (in astropy-helpers and sphinx-automodapi), afaik there is no mention of it here. Frankly the behaviour of astropy hasn't changed, the docs building of 1.3.2 is just as incompatible with the new sphinx as the new bugfix release. 

Btw the new feature release v2.0 is out in about a month, so I'm very inclined to leave this as a ``won't fix``.

**Comment by anntzer** [comment] 2017-05-30 16:15
As far as I can see the issue should already have been resolved in sphinx-automodapi (e.g. they are testing with 1.6, https://github.com/astropy/sphinx-automodapi/pull/23), and they have released 0.4 since then, which was *before* astropy 1.3.3 was released.
Unless this understanding is wrong, I believe astropy should have vendored a more recent version of the packages.  Also, it is unclear why trying to build a wheel should trigger any doc-related issues.

**Comment by bsipocz** [comment] 2017-05-30 16:22
We switch to use ``sphinx-automodapi`` in v2.0. Could you maybe fix the sphinx version to 1.5.6 for the wheels? That will fix the issue, and our new release will deal with the new version.

**Comment by anntzer** [comment] 2017-05-31 04:21
Sure.
Once again I don't think sphinx should be needed to build a wheel (or any version of it be problematic), but feel free to close the issue if you disagree.

**Comment by saimn** [comment] 2017-05-31 07:24
"sphinx should be needed to build a wheel" : actually it is not, this case is handled. But the issue here is that Sphinx is installed and broken. There is now a 1.6.2 version with a fix that seem related (with the typing module - https://github.com/sphinx-doc/sphinx/blob/master/CHANGES#L83), maybe fixes the issue ?

**Comment by anntzer** [comment] 2017-05-31 07:29
Sphinx 1.6.2 does not solve the issue.
Even if sphinx is broken it is not clear to me why building an astropy wheel would even try to *import* sphinx.

**Comment by saimn** [comment] 2017-05-31 07:43
It is imported just to register the `build_docs` sub-command. That's how setuptools/distutils works, a lot of stuff is done even before it knows that the sub-command to execute is `bdist_wheel`.

**Comment by saimn** [comment] 2017-05-31 07:49
I cannot reproduce on Python 3.6 after upgrading Sphinx. Can you check if you have the `typing` package installed and remove it if it's the case ?

**Comment by anntzer** [comment] 2017-05-31 08:01
I have the stdlib typing only.

**Comment by MaxNoe** [comment] 2017-06-03 18:00
Also installing the current wheel fails:
https://travis-ci.org/fact-project/pyfact/jobs/239128275

**Comment by bsipocz** [comment] 2017-06-26 23:02
Closing this as #6140 is expected to solve the issue for the upcoming 2.0 release.

**Closed by bsipocz** 2017-06-26 23:02 UTC
Labels: installation, Upstream Fix Required, wont-fix
