### ISSUE TITLE
DOC: Bad change log fragment in main branch

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#13589] opened 2022-08-30 22:17 UTC
I think one of the change log fragments is bad. It is causing this warning in unrelated PRs, blocking their RTD checks because we set RTD check to fail on warnings:

`Finding news fragments...
.../docs/changelog.rst:7: WARNING: render_fragments() got multiple values for argument 'top_underline'`

How does one find out which one, @Cadair or @saimn ?

**Comment by eerovaher** [comment] 2022-08-30 22:55
The problem might be caused by a new version of `towncrier`. The last succeeding build on RTD used `towncrier` 21.9, but the first failing build used 22.8.

**Comment by ConorMacBride** [comment] 2022-08-30 23:02
This should hopefully be fixed by https://github.com/OpenAstronomy/sphinx-changelog/pull/14

**Closed** 2022-08-31 16:43 UTC
Labels: Upstream Fix Required, Docs, Bug, :fire:
