### ISSUE TITLE
tox -e codestyle fails on astropy/_erfa/core.py

### ISSUE THREAD

**Issue by aarchiba** [astropy/astropy#10444] opened 2020-06-04 15:06 UTC
### Description

`tox -e codestyle` always fails with a huge stream of code style violations in `astropy/_erfa/core.py`. This renders it largely useless for checking my own code for style violations.

I assume the file is auto-generated, so simply telling the job to ignore code style violations in that file might solve the problem. If not, a once-over with `black` or `autopep8` would probably resolve the issue.

### Expected behavior

`tox -e codestyle` succeeds on a clean master.

### Actual behavior

```
...
astropy/_erfa/core.py:20058:37: W291 trailing whitespace
astropy/_erfa/core.py:20101:37: W291 trailing whitespace
astropy/_erfa/core.py:20146:37: W291 trailing whitespace
astropy/_erfa/core.py:20187:37: W291 trailing whitespace
astropy/_erfa/core.py:20231:37: W291 trailing whitespace
astropy/_erfa/core.py:20272:37: W291 trailing whitespace
astropy/_erfa/core.py:20342:22: W292 no newline at end of file
244
ERROR: InvocationError for command /home/archibald/projects/astropy/astropy/.tox/codestyle/bin/flake8 astropy --count --select=E101,W191,W291,W292,W293,W391,E111,E112,E113,E30,E502,E722,E901,E902,E999,F822,F823 (exited with code 1)
_______________________________________________________ summary _______________________________________________________
ERROR:   codestyle: commands failed
```

### Steps to Reproduce

```sh
tox -e codestyle
```

### System Details

```
>>> import platform; print(platform.platform())
Linux-5.4.0-33-generic-x86_64-with-glibc2.29
>>> import sys; print("Python", sys.version)
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.18.4
>>> import astropy; print("astropy", astropy.__version__)
astropy 4.2.dev162+gd0a1e469f
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.4.1
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
Matplotlib 3.2.1
```

**Comment by pllim** [comment] 2020-06-04 17:59
`tox` might just be unnecessary here. This is what it really calls:

https://github.com/astropy/astropy/blob/370bb94d984aad53392a5e3429eb611ab2482c1d/tox.ini#L139

For the purpose of testing just the file being worked on, one can modify it to run:
```
flake8 path/to/file.py --count --select=E101,W191,W291,W292,W293,W391,E111,E112,E113,E30,E502,E722,E901,E902,E999,F822,F823
```

Perhaps this can be clarified somewhere in the docs?

**Comment by mhvk** [comment] 2020-06-04 18:44
Agreed, that's most annoying. The problem is that it is a generated file, so on travis we do not see it, since those are not included unless on builds astropy. Anyway, should just exclude it in `setup.cfg`! See #10445

**Comment by pllim** [comment] 2020-06-04 18:57
@aarchiba , hopefully this error will go away now with #10445 merged and after you rebase against `upstream/master`.

Thanks, @mhvk !

**Closed** 2020-06-04 18:57 UTC
Labels: Bug, Docs, testing

**Comment by aarchiba** [comment] 2020-06-05 14:52
Yes it runs cleanly. Thanks!
