### ISSUE TITLE
astropy.time.Time format conversion changes precision if input value is a large float

### ISSUE THREAD

**Issue by aripollak** [astropy/astropy#15099] opened 2023-07-28 16:02 UTC
### Description

If you initialize a Time object with a large float in JD format, like `Time(2456463.052272, format='jd')`, and then call `to_value('mjd')` on it, the result is `56462.552271999884`. 

### Expected behavior

I'd expect the result to be `56462.552272`. Interestingly, if you initialize the Time object with a string representation of the same float, like `Time('2456463.052272', format='jd')`, you get the expected result when calling `to_value('mjd')`.  I'm not sure if this is a bug or expected behavior, but it was surprising to me.

### How to Reproduce

```python
In [1]: from astropy.time import Time

In [2]: t = Time(2456463.052272, format='jd')

In [3]: t.value
Out[3]: 2456463.052272

In [4]: t.to_value("mjd")  # Expecting this to be the same result as [7]
Out[4]: 56462.552271999884

In [5]: t = Time('2456463.052272', format='jd')

In [6]: t.value
Out[6]: 2456463.052272

In [7]: t.to_value("mjd")
Out[7]: 56462.552272
```

### Versions

Linux-6.2.0-25-generic-x86_64-with-glibc2.37
Python 3.10.12 (main, Jul 26 2023, 16:20:13) [GCC 12.2.0]
astropy 5.2.2
Numpy 1.24.3
pyerfa 2.0.0.3
Scipy 1.10.1
Matplotlib 3.7.2

**Comment by mhvk** [comment] 2023-07-30 01:41
The problem is that you run into small rounding errors,
```
2456463.052272 - 2456463 - .052272
# -1.1560320756220932e-10
```
I.e., internally, python (or any double) cannot represent `2456463.052272` exactly.

Indeed, you get the "wrong" MJD also if you calculate it directly, without going through `Time`,
```
2456463.052272 - 2400000.5
# 56462.552271999884
```

The only solutions are to create a string (which will be interpreted at full precision), or to give two arguments, 
```
Time(2456463., .052272, format='jd').mjd
# 56462.552272
```

Removing `bug` label and adding `question` and `close?` since `Time` cannot fix this -- unfortunately, one has to deal carefully with JDs...

**Comment by aripollak** [comment] 2023-07-30 02:37
Ah interesting, thanks for the explanation. The float JD value originally came from MPC.get_observations in the epoch field. Would it make more sense to store that as a string there? Should the full-precision string behavior of Time be documented?

**Comment by pllim** [comment] 2023-07-30 14:06
Kinda documented at https://docs.astropy.org/en/latest/time/index.html#internal-representation ?

**Comment by pllim** [comment] 2023-07-30 14:07
Can you please clarify what is `MPC.get_observations`?

**Comment by mhvk** [comment] 2023-07-30 15:04
I think the first question is whether it actually matters: basically, there is an uncertainty of 2**-52 * 2400000 = 5e-10 day = 50 us if you use floats for JD. Do you care? Obviously, important for pulsar timing or VLBI, but really for very little else.

**Comment by aripollak** [comment] 2023-07-31 18:14
@pllim that's https://astroquery.readthedocs.io/en/latest/api/astroquery.mpc.MPCClass.html#astroquery.mpc.MPCClass.get_observations.

Full example:
```py
In [1]: from astroquery.mpc import MPC; from astropy.time import Time

In [2]: epoch = MPC.get_observations('2017 US4')[0]['epoch'].value

In [3]: epoch
Out[3]: 2458048.94753

In [4]: Time(epoch, format='jd').to_value('mjd')
Out[4]: 58048.447530000005

In [5]: Time(str(epoch), format='jd').to_value('mjd')
Out[5]: 58048.44753

```

**Comment by pllim** [comment] 2023-07-31 21:37
I cannot comment on MPC, but hoping @bsipocz or @keflavich can point the MPC maintainers here.

**Comment by keflavich** [comment] 2023-07-31 22:02
This looks like a [standard example of the limitations of floating point arithmetic](https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html), as @mhvk said.  If this level of precision is important (i.e., measurable), then it is up to the database provider to ensure the correct type is provided, which can be done in votables afaik.

I am not sure there is a bug here; the only possible bug is if the stated precision of the epoch is better than ~50 microseconds.

I think the value likely should not be stored as a string because that is much less efficient - but it depends on the use case and the expected precision.   I would default to a higher-precision float before going to string representation, though, for most use cases.

**Closed** 2023-08-06 05:47 UTC
Labels: time, Close?, closed-by-bot, question
