### ISSUE TITLE
Occasional failures in vo_test.py

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#4739] opened 2016-03-26 12:44 UTC
The Debian CI tests (which are run whenever one of the dependencies of astropy changed) sometimes show a segmentation fault on `io/votable/tests/vo_test.py`. I had this now the second time at the same place, so it was probably not just a glitch in our environment: [here](https://ci.debian.net/data/packages/unstable/amd64/p/python-astropy/20160325_141118.autopkgtest.log.gz) and [here](https://ci.debian.net/data/packages/unstable/amd64/p/python-astropy/20160317_060216.autopkgtest.log.gz).
The log excerpt there is

```
../../usr/lib/python2.7/dist-packages/astropy/io/votable/tests/vo_test.py ...........................................................................................................................................................................
bash: line 1:  1076 Segmentation fault      (core dumped) 
```

The relevant changes that lead to the CI test were new debian release of gfortran-5.3.1 (from debian relaease [11 to 12](https://ci.debian.net/data/packages/unstable/amd64/p/python-astropy/20160317_060216.log) and [12 to 13](https://ci.debian.net/data/packages/unstable/amd64/p/python-astropy/20160325_141118.log))
This may be similar to #4240 or #4352, but I am not sure.
Apart from the two failures, I have however ~20 succeeding [CI test runs](https://ci.debian.net/packages/p/python-astropy/unstable/amd64/). Platform is amd64.

**Comment by pllim** [comment] 2016-03-28 14:12
Are you able to reproduce this locally, on demand? If so, running it with `valgrind` can pinpoint where exactly the segfault is happening. 

http://valgrind.org/docs/manual/quick-start.html#quick-start.mcrun

**Comment by olebole** [comment] 2016-04-01 13:15
I didn't reproduce this yet, it is just an observation of our CI test runs.

**Comment by henrythroop** [comment] 2016-04-28 11:09
I am getting a crash consistently when calling conesearch.conesearch() from the 1.1.2 distribution.

Additionally, conesearch seems to fails the astropy tests. Is there test output produced that I can supply here that would be helpful?

```
astropy.test('vo', remote_data=True)
============================= test session starts ==============================
platform darwin -- Python 2.7.11, pytest-2.8.5, py-1.4.31, pluggy-0.3.1

Running tests with Astropy version 1.1.2.
Running tests in /Users/throop/anaconda/lib/python2.7/site-packages/astropy/vo.

Date: 2016-04-28T16:33:39

Platform: Darwin-15.4.0-x86_64-i386-64bit

Executable: /Users/throop/anaconda/bin/python

Full Python Version: 
2.7.11 |Anaconda 4.0.0 (x86_64)| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)]

encodings: sys: ascii, locale: UTF-8, filesystem: utf-8, unicode bits: 15
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.11.0
Scipy: 0.17.0
Matplotlib: 1.5.1
h5py: 2.5.0
Pandas: 0.18.0
Using Astropy options: remote_data.

rootdir: /Users/throop/anaconda/lib/python2.7/site-packages/astropy/vo, inifile: 
collected 62 items

../../anaconda/lib/python2.7/site-packages/astropy/vo/client/tests/test_conesearch.py ......F...F......x.
../../anaconda/lib/python2.7/site-packages/astropy/vo/client/tests/test_vos_catalog.py ..............
```

**Comment by pllim** [comment] 2016-04-28 13:15
@henrythroop , pretty sure I just fixed this a few weeks ago, so please check if the failures still appear in the dev version. Thanks.

**Comment by pllim** [comment] 2016-04-28 13:18
@henrythroop , although I am not sure why your Cone Search is crashing. Please open a new issue and post the commands you used and the entire traceback. This issue is for `io.votable`, not `vo`.

**Comment by henrythroop** [comment] 2016-04-28 18:29
Thanks. Still crashes in 1.2.dev14959 (segfault) and fails the test. I'm working on getting a traceback.

**Comment by pllim** [comment] 2016-04-28 18:40
Okay, I'll keep an eye open for your new issue about this. Than you.

**Comment by mhvk** [comment] 2016-06-07 19:21
Any progress on the random failures in `vo`? Fairly regularly, `travis` runs abruptly terminate somewhere in the `vo` tests, and it would be good to get to the bottom of those...

**Comment by olebole** [comment] 2016-06-21 08:10
1.2 still has occasional failures, [last I got](https://buildd.debian.org/status/fetch.php?pkg=python-astropy&arch=all&ver=1.2-1&stamp=1466495314) is
```
astropy/io/votable/tests/vo_test.py::TestThroughTableData::test_schema PASSED
astropy/io/votable/tests/vo_test.py::TestThroughBinary::test_string_test debian/rules:56: recipe for target 'test-python2.7' failed
```

**Comment by astrofrog** [comment] 2016-11-01 13:23
I just saw a segfault today with the latest version, so this is still an issue:

https://circleci.com/gh/astrofrog/astropy/17

However it's still non-deterministic, because when I re-ran, the failure disappeared.

**Comment by MSeifert04** [comment] 2016-12-05 16:52
It's still present and I've encountered it in https://travis-ci.org/astropy/astropy/jobs/181391581

**Comment by tomkooij** [comment] 2017-01-12 19:25
I am getting reproducable (as in everytime) segfaults/crashes in `votable` on my windows (python 3.6 64-bit) laptop and Appveyor python 3.6 32 and 64 bit (while python 2.7, 3.4 and 3.5 pass) in the 1.3 release and 2.0dev: https://ci.appveyor.com/project/tomkooij/astropy-wheels/build/1.0.27

**Comment by pllim** [comment] 2017-01-12 19:50
@tomkooij , any chance you can run that test from Astropy source checkout inside `gdb` and capture the stack trace? Example (tested on my Linux):

```
$ cd /my/astropy/source/checkout
$ gdb
(gdb) file python
(gdb) run setup.py test -t astropy/io/votable/tests/table_test.py
... # Reproduce the segfault
(gdb) where
(gdb) Quit
```

**Comment by tomkooij** [comment] 2017-01-12 20:00
@pllim I'm testing on Windows and cygwin and conda don't mix. So I do not have `gdb`. I'm completely unfamiliar with windows/MS debuggers...

However, I'll try to reproduce this on Linux.

**Comment by tomkooij** [comment] 2017-01-12 20:24
@pllim Ok, so I just found and download `gdb` for windows:

```
(gdb) file c:\\miniconda3\\envs\\py36\\python.exe
Reading symbols from c:\miniconda3\envs\py36\python.exe...(no debugging symbols found)...done.
(gdb) run setup.py test -t astropy/io/votable/tests/table_test.py
Starting program: c:\miniconda3\envs\py36\python.exe setup.py test -t astropy/io/votable/tests/table_test.py
[New Thread 6744.0x2648]
[New Thread 6744.0x2094]
[New Thread 6744.0x23e8]
[New Thread 6744.0x2504]
[New Thread 6744.0x21e4]
[New Thread 6744.0x18c0]
[Thread 6744.0x18c0 exited with code 0]
[Thread 6744.0x21e4 exited with code 0]
[New Thread 6744.0x2d80]
[New Thread 6744.0x30b0]
[Thread 6744.0x2d80 exited with code 0]
[Thread 6744.0x30b0 exited with code 0]
[New Thread 6744.0x31f0]
[New Thread 6744.0x78c]
[Thread 6744.0x31f0 exited with code 0]
[Thread 6744.0x78c exited with code 0]
[New Thread 6744.0x408]
[New Thread 6744.0x31a4]
[Thread 6744.0x408 exited with code 0]
[Thread 6744.0x31a4 exited with code 0]
[New Thread 6744.0x1794]
[New Thread 6744.0x3210]
[Thread 6744.0x1794 exited with code 0]
[Thread 6744.0x3210 exited with code 0]
running test
running build
running build_py
running pre_hook from astropy.modeling.setup_package for build_py command
running pre_hook from astropy._erfa.setup_package for build_py command
running build_ext
running pre_hook from astropy.modeling.setup_package for build_ext command
running pre_hook from astropy._erfa.setup_package for build_ext command
building 'astropy._compiler' extension
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\miniconda3\envs\py36\include -Ic:\miniconda3\envs\py36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcastropy\_compiler.c /Fobuild\temp.win-amd64-3.6\Release\astropy\_compiler.obj
_compiler.c
astropy\_compiler.c(67): warning C4005: 'COMPILER': macro redefinition
c:\miniconda3\envs\py36\include\pyconfig.h(132): note: see previous definition of 'COMPILER'
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\miniconda3\envs\py36\libs /LIBPATH:c:\miniconda3\envs\py36\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" /EXPORT:PyInit__compiler build\temp.win-amd64-3.6\Release\astropy\_compiler.obj /OUT:build\lib.win-amd64-3.6\astropy\_compiler.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6\Release\astropy\_compiler.cp36-win_amd64.lib
_compiler.obj : warning LNK4197: export 'PyInit__compiler' specified multiple times; using first specification
   Creating library build\temp.win-amd64-3.6\Release\astropy\_compiler.cp36-win_amd64.lib and object build\temp.win-amd64-3.6\Release\astropy\_compiler.cp36-win_amd64.exp
Generating code
Finished generating code
skipping 'astropy\table\_np_utils.c' Cython extension (up-to-date)
skipping 'astropy\table\_column_mixins.c' Cython extension (up-to-date)
skipping 'astropy\io\ascii\cparser.c' Cython extension (up-to-date)
skipping 'astropy\convolution\boundary_extend.c' Cython extension (up-to-date)
skipping 'astropy\convolution\boundary_fill.c' Cython extension (up-to-date)
skipping 'astropy\convolution\boundary_none.c' Cython extension (up-to-date)
skipping 'astropy\convolution\boundary_wrap.c' Cython extension (up-to-date)
skipping 'astropy\cosmology\scalar_inv_efuncs.c' Cython extension (up-to-date)
skipping 'astropy\stats\lombscargle\implementations\cython_impl.c' Cython extension (up-to-date)
================================================ test session starts =================================================
platform win32 -- Python 3.6.0, pytest-2.8.3, py-1.4.30, pluggy-0.3.1

Running tests with Astropy version 2.0.dev17685.
Running tests in astropy/io/votable/tests/table_test.py.

Date: 2017-01-12T21:22:57

Platform: Windows-10-10.0.14393-SP0

Executable: c:\miniconda3\envs\py36\python.exe

Full Python Version:
3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)]

encodings: sys: utf-8, locale: cp1252, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.11.3
Scipy: 0.18.1
Matplotlib: not available
h5py: not available
Pandas: not available
Cython: 0.25.2
Using Astropy options: remote_data: none.

rootdir: C:\Users\tomkooij\AppData\Local\Temp\astropy-test-e6zbzk0k\lib.win-amd64-3.6\astropy\io\votable\tests, inifile:
collected 9 items

astropy\io\votable\tests\table_test.py .[Thread 6744.0x23e8 exited with code 255]
[Thread 6744.0x2504 exited with code 255]
[Thread 6744.0x2094 exited with code 255]
[Inferior 1 (process 6744) exited with code 0377]
(gdb) where
No stack.
(gdb)
```

**Comment by pllim** [comment] 2017-01-12 20:58
Your output suggests that the error comes from the C-extension in `io.votable` module, i.e., `astropy/io/votable/src/tablewriter.c`. One way to test this hypothesis is to comment out all the lines in `test_read_through_table_interface()` *after* `assert len(t) == 5` and re-run that test. If I am correct, now it will either pass or fail at a different point.

If it is indeed the C-extension, I cannot offer an easy solution. Either there is a bug in the C-extension code or your C libraries linking are a bit messed up.

**Comment by tomkooij** [comment] 2017-01-12 21:12
Commenting out the suggest lines, does indeed cause a crash in a different test (which also calls `tablewriter.c`. 

I'm going to retry on python 3.5 first, to see if it is indeed only related to python 3.6.

**Comment by pllim** [comment] 2017-01-12 21:30
Re: Testing in Python 3.6 -- See #5642

**Comment by tomkooij** [comment] 2017-01-13 19:35
I have tracked the segfault down to: https://github.com/astropy/astropy/blob/master/astropy/io/votable/src/tablewriter.c#L74 
In `tablewriter.c` the first call to stdlib `realloc()` segfaults. 

Anyway, this is a recurrence of #2100. This may be related to the specific win64 anaconda python 3.6, but that is compiled with the same MSVC as I'm using on astropy. I'll see if I can test this with the official CPython binaries.

IMHO, even if it is specific to anconda python 3.6, this should be fixed: This calls `realloc` on a `Py_Object`, which is allocated by `Py_MemAlloc`. It should not be realloced by the stdlib `realloc` but through the python memory manager.

**Comment by mhvk** [comment] 2017-01-13 19:47
@tomkooij - nice tracking down!  Agree this should be fixed.

**Comment by pllim** [comment] 2017-01-13 19:48
@tomkooij , thanks for investigating. You are welcome to submit a PR!

**Comment by mhvk** [comment] 2017-01-13 19:53
`git blame` points to @mdboom: the fix here sounds utterly correct, but if you have a chance, could you have a look?

@tomkooij - a PR indeed most welcome, but if you prefer not to do the `git`ing etc let me know: since you already indicated what change to make, we can of course do it too.

**Comment by tomkooij** [comment] 2017-01-13 19:55
I'll push a PR (with just the `PyMem_Realloc`) and ping @mdboom

**Comment by pllim** [comment] 2017-01-13 20:23
Thanks for the PR!

Just for the record, the specific failure reported by @tomkooij is a bit different from the others reported prior in this same issue. There is a chance there are multiple bugs here but fixing one is better than nothing.

**Comment by MSeifert04** [comment] 2017-10-12 10:49
I just encountered one in CircleCI:

```
____________ lib.linux-i686-3.5/astropy/io/votable/tests/vo_test.py ____________
[gw2] linux -- Python 3.5.2 /usr/bin/python3
Slave 'gw2' crashed while running 'lib.linux-i686-3.5/astropy/io/votable/tests/vo_test.py::TestThroughBinary2::()::test_string_test'
```

**Comment by kakirastern** [comment] 2019-03-09 22:54
Hi, am triaging and wondering if this is still an on-going issue... looks like the last post was made in October 2017, which is more than one year ago. Personally, I haven't encountered the same issue since 
I started contributing a few months ago. Should we close this for now and re-open another issue a similar problem re-surfaces in the future?

**Comment by MSeifert04** [comment] 2019-03-09 23:04
> Should we close this for now and re-open another issue a similar problem re-surfaces in the future?

Maybe. Since this is a segfault this is quite a serious bug (with the potential to compromise systems) so it would be best if this is not forgotten - at least if it's not fixed yet.

**Comment by kakirastern** [comment] 2019-03-09 23:11
I see. Then let's keep this issue stay open for now... Meanwhile, I will help keep an eye on the bug should it crop up during CI tests again in the near future. I understand the gravitas of a segfault. And the bug appears to affect the `io/votable/tests/vo_test.py` only.

**Comment by olebole** [comment] 2019-03-10 09:09
Looking int our [Debian CI logs](https://ci.debian.net/packages/a/astropy/unstable/amd64/) (~300 tests), I couldn't find that segfault in the last year for the Python 3 package. So, I would guess this is somehow fixed and would propose to close it. If it comes back, we can still reopen.

**Comment by mhvk** [comment] 2019-03-10 15:51
Thanks for the triage, @kakirastern, and thanks for checking those many logs, @olebole. I agree that if there was no issue for that many, we can just close this for now. Hopefully, we did really solve it!

**Closed by mhvk** 2019-03-10 15:51 UTC
Labels: Bug, io.votable, testing
