### ISSUE TITLE
Bug in creating a fits Column

### ISSUE THREAD

**Issue by WilliamJamieson** [astropy/astropy#13748] opened 2022-09-23 18:02 UTC
### Description

In processing an extremely large amount of data, my code attempts to create a `fits.Column` object from that data which fails in a numpy call made by `astropy.io.fits`.

A simplified reproducer of the issue is

```python
import numpy as np
from astropy.io import fits

dat = np.zeros(2150000000)
fmt = f"{len(dat)}B"
column = fits.Column(array=dat, format=fmt)
```
Which produces the error:
```python
Traceback (most recent call last):
  File "/Users/wjamieson/projects/astropy/test.py", line 7, in <module>
    column = fits.Column(array=dat, format=fmt)
  File "/Users/wjamieson/projects/astropy/astropy/io/fits/column.py", line 663, in __init__
    array = self._convert_to_valid_data_type(array)
  File "/Users/wjamieson/projects/astropy/astropy/io/fits/column.py", line 1341, in _convert_to_valid_data_type
    dtype = np.dtype(numpy_format).base
ValueError: invalid shape in fixed-type tuple: dimension does not fit into a C int.
```
The part where astropy is failing is here: https://github.com/astropy/astropy/blob/c375a43e8878d304d22381cac7bce4947c23ae25/astropy/io/fits/column.py#L1318-L1341

Note that if `dat` is slightly smaller this succeeds, but larger `dat` cause the failure.

Diving into the astropy code shows that essentially, my inputs are resulting in the numpy call:
```python
np.dtype("=2150000000u1")
```
Which produces the error. However, if we run (remove one zero from the coefficient)
```python
np.dtype("=215000000u1")
```
it succeeds. Moreover, the astropy code immediately calls `.base` on the result of the above, which for the purposes of my code should always result in `uint8`. Indeed, this is reflected in the comment: https://github.com/astropy/astropy/blob/c375a43e8878d304d22381cac7bce4947c23ae25/astropy/io/fits/column.py#L1338-L1340

This makes me believe that there is no need to preserve the shape coefficient in the `numpy_format` string passed to `np.dtype` in this code. Meaning, the above should legitimately succeed.

### System Details

```
macOS-10.16-x86_64-i386-64bit
Python 3.10.5 (main, Jul 18 2022, 12:56:28) [Clang 12.0.0 (clang-1200.0.32.29)]
Numpy 1.23.1
pyerfa 2.0.0.1
astropy 5.1
Scipy 1.8.1
Matplotlib 3.5.1
```

**Comment by pllim** [comment] 2022-09-27 22:36
I think you said you had the same problem with 5.2.dev too, right?

**Comment by WilliamJamieson** [comment] 2022-09-27 23:12
> I think you said you had the same problem with 5.2.dev too, right?

Yes

**Comment by saimn** [comment] 2022-09-28 08:45
```
fmt = f"{len(dat)}B"
column = fits.Column(array=dat, format=fmt)
```
Are you sure this is what you want ?
By using `format=f"{len(dat)}B"` you are specifying that each element of the column is an array of 2150000000 values. Which is not possible because of a fundamental limitation in Numpy (same issue as #1840).
Also here you are trying to build a column of N element where each element would be an array of N element, even when removing a zero I doubt you will have enough memory:
```
In [4]: import numpy as np
   ...: from astropy.io import fits
   ...: 
   ...: dat = np.zeros(215000000)
   ...: fmt = f"{len(dat)}B"
   ...: column = fits.Column(array=dat, format=fmt, name='a')

In [5]: hdu = fits.BinTableHDU.from_columns([column])
...
MemoryError: Unable to allocate 41.1 PiB for an array with shape (46225000000000000,) and data type uint8
```

**Comment by saimn** [comment] 2022-09-28 14:58
Ok, but the code in ASDF is slightly different, the shape of the data array given to `Column` is 1xN. So you get an HDU with only one row (not N), and the row element is an array of N values. And so your bug is the same as #1840 (the shape of an array stored in a row is coded with an int32, and 2150000000 elements is too big for that...).

**Comment by saimn** [comment] 2022-09-28 14:59
And so closing as duplicate of #1840

**Closed by saimn** 2022-09-28 14:59 UTC
Labels: io.fits, Bug, Performance

**Comment by WilliamJamieson** [comment] 2022-09-28 15:28
Would it be possible to "cheat" and update asdf so that it creates a column of N rows but then still ends up with the same table (using a transpose or something)?

**Comment by saimn** [comment] 2022-09-28 15:36
Yes I guess you could do that.

**Comment by WilliamJamieson** [comment] 2022-09-28 15:54
As an extremely naive fits user, how might one accomplish this?

**Comment by saimn** [comment] 2022-09-29 10:33
I don't know what the asdf code is code so difficult to be more specific, but maybe we discuss that on Slack ?
