### ISSUE TITLE
OSError: Empty or corrupt FITS file (HEADER)

### ISSUE THREAD

**Issue by jacopovpsi** [astropy/astropy#5732] opened 2017-01-24 14:59 UTC
hello guys, I've a problem with

```
astropy.io.open()
>>> OSError: Empty or corrupt FITS file
```

in particular I'm loading some files .fits and I know that the headers have a not valid  character 
`TEMP    =           -64.000000 / Actual temperature (�C)                  `
so I've tried with fitsio.read() and it works, but I don't like to use it.
I've tried with `fits.open(path,ignore_missing_end=True)`
but I still have the same problem.
Do you have any idea on how to get the data without header issue??
Thank you

**Comment by pllim** [comment] 2017-01-24 15:11
Which version of Astropy are you using? Which Python version? What is the complete Python commands and traceback? What happens when you run `fitscheck` on the file?

**Comment by jacopovpsi** [comment] 2017-01-24 15:25
Metadata-Version: 1.1
Name: astropy
Version: 1.2.1

and python 3.5.2



`mpc:~$ fitscheck data.fits 
/anaconda/lib/python3.5/site-packages/pyfits/hdu/hdulist.py:848: VerifyWarning: Error validating header for HDU #0 (note: PyFITS uses zero-based indexing).
    'ascii' codec can't decode byte 0xb0 in position 1973: ordinal not in range(128)
There may be extra bytes after the last HDU or the file is corrupted.
  (len(hdulist), indent(str(exc))), VerifyWarning)
EXCEPTION 'data.fits' .. Empty or corrupt FITS file
1 errors
`


Thank you

**Comment by pllim** [comment] 2017-01-24 15:30
Looks like a duplicate of #5093 . For now, either use Python 2 or fix the FITS header.

**Comment by aburgasser** [comment] 2017-05-06 05:04
I'm having this same problem with NIRC2 imaging data - can someone explain how to "fix the FITS header"

**Comment by pllim** [comment] 2017-05-06 05:25
A workaround is to open it (successfully) in Python 2, and then use `writeto()` to write out a valid file for Python 3.

**Comment by saimn** [comment] 2017-05-19 20:28
Should be fixed by #6084 (if not, please reopen).

**Closed by saimn** 2017-05-19 20:28 UTC
Labels: Close?, Duplicate, io.fits
