### ISSUE TITLE
astropy.time.Time fits format incorrectly includes "(UTC)"

### ISSUE THREAD

**Issue by gijzelaerr** [astropy/astropy#5329] opened 2016-09-14 08:02 UTC
hi! When playing with astropy 1.2.1 I noticed this:

```
In [1]: import astropy.time
In [2]: t = astropy.time.Time('1999-01-01T00:00:00.123456789')
In [3]: t.format = 'fits'
In [4]: print(t)
1999-01-01T00:00:00.123(UTC)
```

I'm not sure why the (UTC) part is appended to the string, but the fits specification doesn't mention this:

http://fits.gsfc.nasa.gov/year2000.html
https://archive.stsci.edu/fits/fits_standard/node87.html#s:tsys

When this format is used in actual fits header, various fits header parser tools break.

there was a discussion on the astropy mailinglist, but it seems mail.scipy.org is down so I can't add a link.

**Comment by mhvk** [comment] 2016-09-14 09:03
@gijzelaerr - I implemented the `TimeFITS` format following http://arxiv.org/abs/1409.7583 (see #3000, #3547), which seemed to suggest that a timescale should generally be appended to time strings. But it also states that UTC is the default, so I guess that can be omitted to help old readers. I don't think it would be particularly onerous to allow this omission, but am not immediately sure how best to approach it (one needs to somehow allow this as an option in `astropy.time.formats.TimeFITS.parse_string`, possibly using an `outsubfmt` or so).  

p.s. As a short-cut, you can of course just use the `time.isot`, which does give exactly the required string.

p.s.2 More generally, this hasn't been properly integrated with `io.fits` -- contributions most welcome!

**Comment by timj** [comment] 2018-08-28 20:41
As I've written in #7781, I don't think Rots et al says this at all.  I can't see any evidence (at least that is obvious to me) that the trailing time scale is allowed in the standard.

**Comment by timj** [comment] 2018-09-10 14:35
We've been asked to move the discussion of #7781 to this ticket. On that ticket @mhvk agrees that the interpretation of the examples in Rots et al is incorrect. There is concern that we can't fix the `fits()` method since many people may be using it (hopefully not in fits headers). My suggestion is to add a `fitshdr()` method. The problem is that the time scale information gets lost (in a FITS header this is specified in a separate `TIMESYS` header) but I think we do need to do something to stop people using the incorrect form in FITS headers (as has already happened at LSST).

**Comment by Cadair** [comment] 2018-09-10 14:44
If it is wrong, I really think we should change it, even if it might break some stuff. (Should probably deprecate it first or something). People (me very much included) just assumed it was correct.

**Comment by astrofrog** [comment] 2018-09-11 08:29
I agree that in cases like this we should just change it even if it breaks things (it's unlikely to break much)

**Comment by mhvk** [comment] 2018-09-11 10:55
It breaks uniqueness of the FITS time strings (they'll be identical to `isot`). But not opposed to changing it (please go ahead and do it; I won't have time in the near future).

**Comment by bsipocz** [comment] 2018-09-11 17:21
> I agree that in cases like this we should just change it even if it breaks things (it's unlikely to break much)

it may break some doctests for downstream affiliates that support both LTS and latest? But even in that case it's an easy fix for them I think.

**Comment by astrofrog** [comment] 2018-10-29 15:43
Fixed in https://github.com/astropy/astropy/pull/7870

**Closed by astrofrog** 2018-10-29 15:43 UTC
Labels: Affects-release, Effort-low, Enhancement, Package-intermediate, Priority-Low, io.fits, time
