### ISSUE TITLE
Remote data or Numpy dev failures for 1.3.dev

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#5557] opened 2016-12-05 16:41 UTC
For example, see https://travis-ci.org/astropy/astropy/jobs/181378343

This needs to be resolved before release. c/c @astrofrog

**Comment by MSeifert04** [comment] 2016-12-05 16:47
Sure that these are remote-data failures? None of both is marked as "remotedata". But these could be numpy-dev errors.

**Comment by pllim** [comment] 2016-12-05 16:53
Oh yeah, I forgot it doubles as Numpy dev testbed now. You could be right!

**Comment by astrofrog** [comment] 2016-12-05 18:38
I wonder if the issue is that there may be multiple warnings returned in that test, and astropyuserwarning is no longer the first? In that sense, the warning testing may not be as robust as it could be.

**Comment by mhvk** [comment] 2016-12-05 21:01
I think the first failure is because indexing with booleans now requires the index to be as long as the array.  Will try to look later.

**Comment by mhvk** [comment] 2016-12-06 22:12
See #5565 for what should be a fix.

**Comment by mhvk** [comment] 2016-12-07 01:06
#5565 fixed the numpy-dev issue, but there is a remaining problem that `finals2000.all` gets loaded in the doctest. I'm actually a bit surprised this happens since the times are well within the IERS-B range. @taldcroft? See https://travis-ci.org/astropy/astropy/jobs/181782165#L2642

**Comment by taldcroft** [comment] 2016-12-07 02:16
@mhvk - downloading `finals2000.all` is the expected behavior if it is not already available in the cache and `iers.conf.auto_download is True` (default).   But what I don't understand is that the file should have been downloaded a few lines beforehand here:
```
    >>> lcoo = coo.transform_to(lf)  # this can load finals2000A.all # doctest: +IGNORE_OUTPUT
```
In any case it seems like setting `iers.conf.auto_download = False` for tests like this would be a good thing in order to [force using the bundled IERS-B](http://astropy.readthedocs.io/en/latest/utils/iers.html#working-offline).

**Comment by mhvk** [comment] 2016-12-07 03:07
Can one add a line to a doctest that is not shown in the final document?

But, now that you mention that line before (for which I wrote the comment; really, my memory...), it is weird that it doesn't use it. Could it be that I was just unlucky? In the travis log linked above, the downloading error is not listed...

**Comment by pllim** [comment] 2016-12-07 15:08
Huh. The latest dev shows remote tests are passing (https://travis-ci.org/astropy/astropy/jobs/181970925). Maybe it was just a transient error. Closing issue.

**Comment by mhvk** [comment] 2016-12-07 15:14
OK, good, that one was definitely weird.

**Comment by pllim** [comment] 2016-12-07 15:23
There is a new failure now that is somewhat related to remote data, so I am re-opening this... Please see https://travis-ci.org/astropy/astropy/jobs/181970916

**Comment by bsipocz** [comment] 2016-12-08 13:39
In current master there is no error on the remote tests, so this can be closed again.

**Closed** 2016-12-08 14:43 UTC
Labels: Affects-dev, testing
