### ISSUE TITLE
open_files test failures in 3.2rc1

### ISSUE THREAD

**Issue by dhomeier** [astropy/astropy#8714] opened 2019-05-16 00:20 UTC
After fixing #8671 building on OS X 10.12.6 succeeds with both numpy 1.14.5 and 1.16.3 and all standard tests pass when running under the respective same numpy version.
`astropy.test(open_files=True)` produced failures in
```
io/fits/tests/test_hdulist.py
io/fits/tests/test_image.py
visualization/tests/test_units.py
```

```
================================================================ test session starts ================================================================
platform darwin -- Python 3.7.3, pytest-3.10.1, py-1.7.0, pluggy-0.7.1

Running tests with Astropy version 3.2rc1.
Running tests in build/lib.macosx-10.12-x86_64-3.7/astropy/io/fits.

Date: 2019-05-16T01:28:35

Platform: Darwin-16.7.0-x86_64-i386-64bit

Executable: /sw/bin/python3.7

Full Python Version: 
3.7.3 (default, May  5 2019, 04:25:55) 
[Clang 9.0.0 (clang-900.0.39.2)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.14.5
Scipy: 1.2.1
Matplotlib: 3.0.3
h5py: not available
Pandas: not available
Cython: 0.28.5
Scikit-image: not available
astropy_helpers: 3.1
Using Astropy options: remote_data: none.

rootdir: /scratch.noindex/fink.build/astropy-py37-3.2rc1-1/astropy-3.2rc1, inifile: setup.cfg
plugins: remotedata-0.3.1, openfiles-0.3.2, doctestplus-0.3.0, arraydiff-0.3
collected 12662 items / 30 skipped
...
...
...
====================================================================== ERRORS =======================================================================
_______________________________________ ERROR at teardown of TestHDUListFunctions.test_replace_memmaped_array _______________________________________

item = <Function 'test_replace_memmaped_array'>, nextitem = <Function 'test_open_file_with_end_padding'>

    def pytest_runtest_teardown(item, nextitem):
        # a "skipped" test will not have been called with
        # pytest_runtest_setup, so therefore won't have an
        # "open_files" member
        if (not item.config.getvalue('open_files') or not hasattr(item, 'open_files')):
            return
    
        start_open_files = item.open_files
        del item.open_files
    
        open_files = _get_open_file_list()
    
        # This works in tandem with the test_open_file_detection test to
        # ensure that it creates one extra open file.
        if item.name == 'test_open_file_detection':
            assert len(start_open_files) + 1 == len(open_files)
            return
    
        not_closed = set()
        open_files_ignore = item.config.getini('open_files_ignore')
        for filename in open_files:
            ignore = False
    
            for ignored in open_files_ignore:
                if not os.path.isabs(ignored):
                    if os.path.basename(filename) == ignored:
                        ignore = True
                        break
                else:
                    if filename == ignored:
                        ignore = True
                        break
    
            if ignore:
                continue
    
            if filename not in start_open_files:
                not_closed.add(filename)
    
        if len(not_closed):
            msg = ['File(s) not closed:']
            for name in not_closed:
                msg.append('  {0}'.format(name))
>           raise AssertionError('\n'.join(msg))
E           AssertionError: File(s) not closed:
E             /private/tmp/fits-test-oowtx9_c/temp.fits

/sw/lib/python3.7/site-packages/pytest_openfiles/plugin.py:119: AssertionError
___________________________________________ ERROR at teardown of TestImageFunctions.test_append_uint_data ___________________________________________

item = <Function 'test_append_uint_data'>, nextitem = <Function 'test_scale_with_explicit_bzero_bscale'>

    def pytest_runtest_teardown(item, nextitem):
        # a "skipped" test will not have been called with
        # pytest_runtest_setup, so therefore won't have an
        # "open_files" member
        if (not item.config.getvalue('open_files') or not hasattr(item, 'open_files')):
            return
    
        start_open_files = item.open_files
        del item.open_files
    
        open_files = _get_open_file_list()
    
        # This works in tandem with the test_open_file_detection test to
        # ensure that it creates one extra open file.
        if item.name == 'test_open_file_detection':
            assert len(start_open_files) + 1 == len(open_files)
            return
    
        not_closed = set()
        open_files_ignore = item.config.getini('open_files_ignore')
        for filename in open_files:
            ignore = False
    
            for ignored in open_files_ignore:
                if not os.path.isabs(ignored):
                    if os.path.basename(filename) == ignored:
                        ignore = True
                        break
                else:
                    if filename == ignored:
                        ignore = True
                        break
    
            if ignore:
                continue
    
            if filename not in start_open_files:
                not_closed.add(filename)
    
        if len(not_closed):
            msg = ['File(s) not closed:']
            for name in not_closed:
                msg.append('  {0}'.format(name))
>           raise AssertionError('\n'.join(msg))
E           AssertionError: File(s) not closed:
E             /private/tmp/fits-test-dubi0ikr/test_new.fits

/sw/lib/python3.7/site-packages/pytest_openfiles/plugin.py:119: AssertionError
______________________________________ ERROR at teardown of TestImageFunctions.test_open_scaled_in_update_mode ______________________________________

item = <Function 'test_open_scaled_in_update_mode'>, nextitem = <Function 'test_scale_back'>

    def pytest_runtest_teardown(item, nextitem):
        # a "skipped" test will not have been called with
        # pytest_runtest_setup, so therefore won't have an
        # "open_files" member
        if (not item.config.getvalue('open_files') or not hasattr(item, 'open_files')):
            return
    
        start_open_files = item.open_files
        del item.open_files
    
        open_files = _get_open_file_list()
    
        # This works in tandem with the test_open_file_detection test to
        # ensure that it creates one extra open file.
        if item.name == 'test_open_file_detection':
            assert len(start_open_files) + 1 == len(open_files)
            return
    
        not_closed = set()
        open_files_ignore = item.config.getini('open_files_ignore')
        for filename in open_files:
            ignore = False
    
            for ignored in open_files_ignore:
                if not os.path.isabs(ignored):
                    if os.path.basename(filename) == ignored:
                        ignore = True
                        break
                else:
                    if filename == ignored:
                        ignore = True
                        break
    
            if ignore:
                continue
    
            if filename not in start_open_files:
                not_closed.add(filename)
    
        if len(not_closed):
            msg = ['File(s) not closed:']
            for name in not_closed:
                msg.append('  {0}'.format(name))
>           raise AssertionError('\n'.join(msg))
E           AssertionError: File(s) not closed:
E             /private/tmp/fits-test-mzrlp428/scale.fits

/sw/lib/python3.7/site-packages/pytest_openfiles/plugin.py:119: AssertionError
__________________________________________________________ ERROR at teardown of test_units __________________________________________________________

item = <Function 'test_units'>, nextitem = <Function 'test_units_errbarr'>

    def pytest_runtest_teardown(item, nextitem):
        # a "skipped" test will not have been called with
        # pytest_runtest_setup, so therefore won't have an
        # "open_files" member
        if (not item.config.getvalue('open_files') or not hasattr(item, 'open_files')):
            return
    
        start_open_files = item.open_files
        del item.open_files
    
        open_files = _get_open_file_list()
    
        # This works in tandem with the test_open_file_detection test to
        # ensure that it creates one extra open file.
        if item.name == 'test_open_file_detection':
            assert len(start_open_files) + 1 == len(open_files)
            return
    
        not_closed = set()
        open_files_ignore = item.config.getini('open_files_ignore')
        for filename in open_files:
            ignore = False
    
            for ignored in open_files_ignore:
                if not os.path.isabs(ignored):
                    if os.path.basename(filename) == ignored:
                        ignore = True
                        break
                else:
                    if filename == ignored:
                        ignore = True
                        break
    
            if ignore:
                continue
    
            if filename not in start_open_files:
                not_closed.add(filename)
    
        if len(not_closed):
            msg = ['File(s) not closed:']
            for name in not_closed:
                msg.append('  {0}'.format(name))
>           raise AssertionError('\n'.join(msg))
E           AssertionError: File(s) not closed:
E             /sw/lib/python3.7/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSansDisplay.ttf
E             /sw/lib/python3.7/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf

/sw/lib/python3.7/site-packages/pytest_openfiles/plugin.py:119: AssertionError
========================================= 12196 passed, 431 skipped, 65 xfailed, 4 error in 201.58 seconds ==========================================
```
Additional failures only occurred with numpy 1.16 (or just erratically?) in `io/fits/tests/test_table.py` and in `visualization` (`test_units.py` but sometimes others as well, i.e. not consistently):
```
_________________________________________________ ERROR at teardown of TestVLATables.test_copy_vla __________________________________________________

item = <Function 'test_copy_vla'>, nextitem = <Function 'test_column_format_interpretation'>

    def pytest_runtest_teardown(item, nextitem):
        # a "skipped" test will not have been called with
        # pytest_runtest_setup, so therefore won't have an
        # "open_files" member
        if (not item.config.getvalue('open_files') or not hasattr(item, 'open_files')):
            return
    
        start_open_files = item.open_files
        del item.open_files
    
        open_files = _get_open_file_list()
    
        # This works in tandem with the test_open_file_detection test to
        # ensure that it creates one extra open file.
        if item.name == 'test_open_file_detection':
            assert len(start_open_files) + 1 == len(open_files)
            return
    
        not_closed = set()
        open_files_ignore = item.config.getini('open_files_ignore')
        for filename in open_files:
            ignore = False
    
            for ignored in open_files_ignore:
                if not os.path.isabs(ignored):
                    if os.path.basename(filename) == ignored:
                        ignore = True
                        break
                else:
                    if filename == ignored:
                        ignore = True
                        break
    
            if ignore:
                continue
    
            if filename not in start_open_files:
                not_closed.add(filename)
    
        if len(not_closed):
            msg = ['File(s) not closed:']
            for name in not_closed:
                msg.append('  {0}'.format(name))
>           raise AssertionError('\n'.join(msg))
E           AssertionError: File(s) not closed:
E             /private/tmp/fits-test-me8xozu9/test.fits

__________________________________________________________ ERROR at teardown of test_units __________________________________________________________

item = <Function 'test_units'>, nextitem = <Function 'test_incompatible_units'>

    def pytest_runtest_teardown(item, nextitem):
        # a "skipped" test will not have been called with
        # pytest_runtest_setup, so therefore won't have an
        # "open_files" member
        if (not item.config.getvalue('open_files') or not hasattr(item, 'open_files')):
            return
    
        start_open_files = item.open_files
        del item.open_files
    
        open_files = _get_open_file_list()
    
        # This works in tandem with the test_open_file_detection test to
        # ensure that it creates one extra open file.
        if item.name == 'test_open_file_detection':
            assert len(start_open_files) + 1 == len(open_files)
            return
    
        not_closed = set()
        open_files_ignore = item.config.getini('open_files_ignore')
        for filename in open_files:
            ignore = False
    
            for ignored in open_files_ignore:
                if not os.path.isabs(ignored):
                    if os.path.basename(filename) == ignored:
                        ignore = True
                        break
                else:
                    if filename == ignored:
                        ignore = True
                        break
    
            if ignore:
                continue
    
            if filename not in start_open_files:
                not_closed.add(filename)
    
        if len(not_closed):
            msg = ['File(s) not closed:']
            for name in not_closed:
                msg.append('  {0}'.format(name))
>           raise AssertionError('\n'.join(msg))
E           AssertionError: File(s) not closed:
E             /sw/lib/python3.7/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf
E             /sw/lib/python3.7/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSansDisplay.ttf
```

**Comment by bsipocz** [comment] 2019-05-16 06:21
It may be an upstream bug in `pytest-openfiles`?

**Comment by pllim** [comment] 2019-05-16 12:07
I reran the 3.2rc1 tests with open files check (it is not required as per official instruction on wiki though) and I can reproduce your
```
>           raise AssertionError('\n'.join(msg))
E           AssertionError: File(s) not closed:
E             /sw/lib/python3.7/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSansDisplay.ttf
E             /sw/lib/python3.7/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf
```
among other known issues, some which have since been fixed on `master`, **but** I don't see any open files error from `io.fits`. My test header:
```
platform win32 -- Python 3.7.1, pytest-4.1.0, py-1.7.0, pluggy-0.8.0

Running tests with Astropy version 3.2rc1.
Running tests in Miniconda3\envs\py37\lib\site-packages\astropy.

Date: 2019-05-16T13:12:48

Platform: Windows-10-10.0.17763-SP0

Executable: C:\...\Miniconda3\envs\py37\python.exe

Full Python Version: 
3.7.1 (default, Oct 28 2018, 08:39:03) [MSC v.1912 64 bit (AMD64)]

encodings: sys: utf-8, locale: cp1252, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.16.2
Scipy: 1.1.0
Matplotlib: 3.0.3
h5py: 2.8.0
Pandas: 0.24.2
Asdf: 2.3.3
Cython: 0.29
Scikit-image: not available
astropy_helpers: 3.2rc1
Using Astropy options: remote_data: none.

Matplotlib: 3.0.3
Freetype: 2.9.1
rootdir: C:\..., inifile:
plugins: xdist-1.24.0, remotedata-0.3.1, openfiles-0.3.2, mpl-0.10, forked-0.2, doctestplus-0.1.3, arraydiff-0.2
collected 12639 items
```

**Comment by pllim** [comment] 2019-05-16 12:13
FWIW open files from matplotlib is probably beyond our control and should not block the release.

**Comment by dhomeier** [comment] 2019-05-16 13:18
Yes, the `visualization` errors are difficult to track down - I could skip almost half of the tests and the suite would fail in another test, always on the same two `.ttf` files, so that's probably more a matplotlib issue. I don't think any of the `io.fits` failures are release-blockers either...
No idea how to check if it's a bug in the tests themselves - `psutil` and `pytest-openfiles` both passed all their own tests (only 2 for the latter..), and the `fits-test-*` directories are already removed once `astropy.test()` has finished.

**Comment by pllim** [comment] 2019-06-13 14:03
@dhomeier , thank you for your report. With the release out the door, I am going to close this. But we can revisit again in the future if this is still a problem for 4.0.

**Closed by pllim** 2019-06-13 14:03 UTC
Labels: Release, io.fits, testing, visualization
