### ISSUE TITLE
ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)" when using `astropy.time.Time.to_datetime()`

### ISSUE THREAD

**Issue by lzkelley** [astropy/astropy#5809] opened 2017-02-14 19:22 UTC
I keep getting these warnings from the ERFA library when converting certain times to `datetime` objects:
```
/Users/lzkelley/anaconda3/lib/python3.5/site-packages/astropy/_erfa/core.py:118: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)"
```
No idea why, but I can reproduce it with:

```
> t = 1693612800.0
> ap.time.Time(t, format='unix').to_datetime()

File "/Users/lzkelley/anaconda3/bin/ipython", line 6, in <module>
    sys.exit(IPython.start_ipython())
  File "/Users/lzkelley/anaconda3/lib/python3.5/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/lzkelley/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/lzkelley/anaconda3/lib/python3.5/site-packages/IPython/terminal/ipapp.py", line 348, in start
    self.shell.mainloop()
  File "/Users/lzkelley/anaconda3/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 440, in mainloop
    self.interact()
  File "/Users/lzkelley/anaconda3/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 431, in interact
    self.run_cell(code, store_history=True)
  File "/Users/lzkelley/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/lzkelley/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2827, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/lzkelley/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-185-04e6f34e68d8>", line 1, in <module>
    ap.time.Time(t, format='unix').to_datetime()
  File "/Users/lzkelley/anaconda3/lib/python3.5/site-packages/astropy/time/core.py", line 1444, in to_datetime
    return tm._shaped_like_input(tm._time.to_value(timezone))
  File "/Users/lzkelley/anaconda3/lib/python3.5/site-packages/astropy/time/formats.py", line 596, in to_value
    self.jd1, self.jd2)
  File "/Users/lzkelley/anaconda3/lib/python3.5/site-packages/astropy/_erfa/core.py", line 21906, in d2dtf
    check_errwarn(c_retval_out, 'd2dtf')
  File "/Users/lzkelley/anaconda3/lib/python3.5/site-packages/astropy/_erfa/core.py", line 118, in check_errwarn
    warnings.warn('ERFA function "' + func_name + '" yielded ' + wmsg, ErfaWarning)
  File "/Users/lzkelley/Programs/zcode/zcode/inout/inout_core.py", line 845, in warn_with_traceback
    traceback.print_stack()
/Users/lzkelley/anaconda3/lib/python3.5/site-packages/astropy/_erfa/core.py:118: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)"
  warnings.warn('ERFA function "' + func_name + '" yielded ' + wmsg, ErfaWarning)
Out[185]: datetime.datetime(2023, 9, 2, 0, 0)
```

`ap.version.githash`: '552a2de83e23b89192a91b423eb69d35ef5424df'
`ap.version.version`: '1.3'

**Comment by lzkelley** [comment] 2017-02-14 19:28
The note that the warning refers to is (from `astropy/_erfa/core.py`, which must be autogenerated somehow??):

```
    5) The warning status "dubious year" flags UTCs that predate the
       introduction of the time scale or that are too far in the future
       to be trusted.  See eraDat for further details.
```

what does "too far in the future to be trusted" mean?  What sets the scale-time of trustability?

**Comment by gahjelle** [comment] 2017-03-24 16:17
Note 1 at https://github.com/liberfa/erfa/blob/master/src/dat.c is relevant. Essentially, future dates are hard to trust because we can not predict leap seconds. The note referred to by the warning can be found at https://github.com/liberfa/erfa/blob/master/src/d2dtf.c (note 5).

**Comment by lzkelley** [comment] 2017-03-24 16:26
Thanks @gahjelle.  There are surely lots of (possible) use cases where people are interested in accuracies of days-to-years, and worrying about leap-second inaccuracies is completely irrelevant.  Perhaps the `Time` class could accept a `erfa_warnings=False` argument to suppress such warnings.

**Comment by gahjelle** [comment] 2017-03-24 16:46
My pleasure, @lzkelley. That is essentially the use case that brought me here :) We have a file that uses 2050 to denote "so far into the future that we have no information" and when we used that as a date interval we got this warning...

**Comment by mhvk** [comment] 2017-03-24 20:13
@gahjelle really explained it already: leap second information is needed for the conversion, which is not available for dates far in the future, so a warning is given. The easiest way to get rid of the warning is to filter it out with the `warnings` module from the standard python library. I personally don't think it is worth adding flags to `Time` itself to filter for this; its purpose is specifically to do these kinds of transformations precisely and correctly, and I think it is very important that it warns the user if it cannot do that.

Indeed, for astronomical purposes, I would very strongly *discourage* using `datetime` because it has no real concept of leap seconds (see #4982, #4983 for somewhat related issues). Is there something specific that `datetime` helps you with that `Time` does not provide? If so, it may be more fruitful to try to implement that (e.g., there is a long-standing request to outputs times as arrays of years, months, etc.: #3831).

**Comment by lzkelley** [comment] 2017-03-24 20:52
Thanks for connecting those other issues @mhvk, I wasn't aware of the greater context.  The issue isn't in the `datetime` *per se*, if you construct a `Time` object and then ask for `decimalyear` (for example) you get the same issue.  My goal is to enter a unix time (possibly far in the future) and, in a simple way, get an easy to use format out (read: access to year/day information).  As long as erfa is being used behind the curtain, it seems like this will be an issue.

Adding a flag to `Time` definitely sounds ugly.  My thought process is simply: 1) getting future dates should be a perfectly reasonable operation and 2) reasonable operations shouldn't require filtering out warnings.  Thus it seems like there should be a way to do this without warnings.

I guess the most authentic solution would be that an error-estimate (or maximum possible error) should also be included, and the user can decide what is warn-worthy.

**Comment by mhvk** [comment] 2017-03-24 21:12
@lzkelley - the problem is also that the `unix` time is odd with leap seconds as well (if I recall correcly, in `unix` time on leap second days `23:59:59` occurs twice). If you are happy instead to work with `gps` or `cxcsec`, which are properly monotonic, things work fine:
```
In [31]: Time(t, format='gps').isot
Out[31]: '2033-09-06T00:00:19.000'

In [32]: Time(t, format='cxcsec').isot
Out[32]: '2051-09-02T00:00:00.000'

In [34]: Time(t, format='cxcsec').decimalyear
Out[34]: 2051.6684931506848
```

**Comment by mhvk** [comment] 2017-03-24 21:14
@lzkelley - in a broader picture, it would probably good if the documentation better addressed this.  Pull requests very welcome...

**Comment by mhvk** [comment] 2019-06-22 01:05
As this issue itself is not going to be addressed, I suggest to close this issue - doc updates would of course still be welcome.

**Comment by astrojuanlu** [comment] 2020-10-04 09:12
So, this issue is about improving the wording of the warning?

**Comment by astrofrog** [comment] 2020-10-04 13:07
Yes though we could open a separate issue and close this one if that would make it more explicit

**Comment by astrofrog** [comment] 2020-10-04 13:08
Actually we have one already: https://github.com/astropy/astropy/issues/9603

**Closed by astrofrog** 2020-10-04 13:08 UTC
Labels: Docs, Effort-low, Package-novice, erfa, good first issue, time
