### ISSUE TITLE
test_exception_logging and test_exception_logging_origin fail when pytest-qt is installed

### ISSUE THREAD

**Issue by dhomeier** [astropy/astropy#10402] opened 2020-05-26 17:56 UTC
### Description
Failure on Python 3.8.3 in 4.1rc1 and master

### Steps to Reproduce
```python3.8
import astropy
astropy.test(package='tests', args='-vk test_exception_log', remote_data=True, open_files=True)"                                                                 <
================================================================================== test session starts ===================================================================================
platform darwin -- Python 3.8.3, pytest-5.3.0, py-1.8.1, pluggy-0.13.0 -- /sw/bin/python3.8
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/Users/derek/Downloads/.hypothesis/examples')

Running tests with Astropy version 4.2.dev112+g595484597.
Running tests in lib/python3.8/site-packages/astropy/tests.

Date: 2020-05-26T19:50:54

Platform: macOS-10.12.6-x86_64-i386-64bit

Executable: /sw/bin/python3.8

Full Python Version: 
3.8.3 (default, May 14 2020, 22:17:35) 
[Clang 9.0.0 (clang-900.0.39.2)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Package versions: 
Numpy: 1.19.0rc1
Scipy: 1.4.1
Matplotlib: 3.2.1
h5py: 2.9.0
Pandas: not available
Cython: 0.29.16
Scikit-image: not available
asdf: 2.6.1.dev51+gcc88c58.d20200522

Using Astropy options: remote_data: any.

Matplotlib: 3.2.1
Freetype: 2.6.1
PyQt5 5.12.2 -- Qt runtime 5.7.1 -- Qt compiled 5.7.1
rootdir: /Users/derek
plugins: doctestplus-0.5.0, asdf-2.6.1.dev51+gcc88c58.d20200522, flaky-3.5.3, hypothesis-4.36.0, arraydiff-0.3, astropy-header-0.1.2, cov-2.6.1, expect-1.1.0, forked-1.1.3, mock-1.10.4, mpl-0.11, openfiles-0.3.2, qt-3.3.0, remotedata-0.3.1, xdist-1.30.0, requests-mock-1.7.0
collected 44 items / 38 deselected / 6 selected                                                                                                                                          

../lib/python3.8/site-packages/astropy/tests/test_logger.py::test_exception_logging_disable_no_enable PASSED                                                                       [ 16%]
../lib/python3.8/site-packages/astropy/tests/test_logger.py::test_exception_logging_enable_twice PASSED                                                                            [ 33%]
../lib/python3.8/site-packages/astropy/tests/test_logger.py::test_exception_logging_overridden PASSED                                                                              [ 50%]
../lib/python3.8/site-packages/astropy/tests/test_logger.py::test_exception_logging FAILED                                                                                         [ 66%]
../lib/python3.8/site-packages/astropy/tests/test_logger.py::test_exception_logging_origin FAILED                                                                                  [ 83%]
../lib/python3.8/site-packages/astropy/tests/test_logger.py::test_exception_logging_argless_exception SKIPPED                                                                      [100%]

======================================================================================== FAILURES ========================================================================================
_________________________________________________________________________________ test_exception_logging _________________________________________________________________________________
CALL ERROR: Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "/Users/derek/lib/python3.8/site-packages/astropy/tests/test_logger.py", line 207, in test_exception_logging
    raise Exception("This is an Exception")
Exception: This is an Exception
________________________________________________________________________________
Traceback (most recent call last):
  File "/Users/derek/lib/python3.8/site-packages/astropy/tests/test_logger.py", line 219, in test_exception_logging
    raise Exception("This is an Exception")
Exception: This is an Exception
________________________________________________________________________________
Traceback (most recent call last):
  File "/Users/derek/lib/python3.8/site-packages/astropy/tests/test_logger.py", line 234, in test_exception_logging
    raise Exception("This is an Exception")
Exception: This is an Exception
________________________________________________________________________________

---------------------------------------------------------------------------------- Captured stderr call ----------------------------------------------------------------------------------
Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "/Users/derek/lib/python3.8/site-packages/astropy/tests/test_logger.py", line 207, in test_exception_logging
    raise Exception("This is an Exception")
Exception: This is an Exception
________________________________________________________________________________
ERROR: Exception: This is an Exception [astropy.tests.test_logger]
Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "/Users/derek/lib/python3.8/site-packages/astropy/tests/test_logger.py", line 219, in test_exception_logging
    raise Exception("This is an Exception")
Exception: This is an Exception
________________________________________________________________________________
Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "/Users/derek/lib/python3.8/site-packages/astropy/tests/test_logger.py", line 234, in test_exception_logging
    raise Exception("This is an Exception")
Exception: This is an Exception
________________________________________________________________________________
----------------------------------------------------------------------------------- Captured log call ------------------------------------------------------------------------------------
ERROR    astropy:logger.py:263 Exception: This is an Exception
_____________________________________________________________________________ test_exception_logging_origin ______________________________________________________________________________
CALL ERROR: Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "/Users/derek/lib/python3.8/site-packages/astropy/tests/test_logger.py", line 254, in test_exception_logging_origin
    l.append('foo')
  File "/Users/derek/lib/python3.8/site-packages/astropy/utils/collections.py", line 47, in append
    self._assert(x)
  File "/Users/derek/lib/python3.8/site-packages/astropy/utils/collections.py", line 29, in _assert
    raise TypeError(
TypeError: homogeneous list must contain only objects of type '<class 'int'>'
________________________________________________________________________________

---------------------------------------------------------------------------------- Captured stderr call ----------------------------------------------------------------------------------
ERROR: TypeError: homogeneous list must contain only objects of type '<class 'int'>' [astropy.utils.collections]
Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "/Users/derek/lib/python3.8/site-packages/astropy/tests/test_logger.py", line 254, in test_exception_logging_origin
    l.append('foo')
  File "/Users/derek/lib/python3.8/site-packages/astropy/utils/collections.py", line 47, in append
    self._assert(x)
  File "/Users/derek/lib/python3.8/site-packages/astropy/utils/collections.py", line 29, in _assert
    raise TypeError(
TypeError: homogeneous list must contain only objects of type '<class 'int'>'
________________________________________________________________________________
----------------------------------------------------------------------------------- Captured log call ------------------------------------------------------------------------------------
ERROR    astropy:logger.py:263 TypeError: homogeneous list must contain only objects of type '<class 'int'>'
===Flaky Test Report===


===End Flaky Test Report===
================================================================= 2 failed, 3 passed, 1 skipped, 38 deselected in 1.37s ==================================================================
```

### System Details
MacOS X 10.12.6; tests pass with Python 3.6.10 and 3.7.7

**Comment by saimn** [comment] 2020-05-26 22:07
Are you using IPython ?
https://github.com/astropy/astropy/blob/0d1357ece96692d71d5c2cab363bb2388005dce6/docs/known_issues.rst#failing-logging-tests-when-running-the-tests-in-ipython
It is not clear to me why there is a Qt event loop here.

**Comment by dhomeier** [comment] 2020-05-26 22:25
> It is not clear to me why there is a Qt event loop here.

That surprised me a bit as well, but all tests were run in a regular Python session or with
`python -c 'import astropy; astropy.test()'`

**Comment by saimn** [comment] 2020-05-26 23:13
There must be a pytest plugin doing something and printing these lines:
```
Matplotlib: 3.2.1
Freetype: 2.6.1
PyQt5 5.12.2 -- Qt runtime 5.7.1 -- Qt compiled 5.7.1
```
You have a `qt-3.3.0` in your plugins, not sure if it is a specific plugin or if it comes with PyQt, but I would try without this ;)

**Comment by dhomeier** [comment] 2020-05-26 23:24
> You have a `qt-3.3.0` in your plugins, not sure if it is a specific plugin or if it comes with PyQt, but I would try without this ;)

Yes, this: https://pypi.org/project/pytest-qt/ – was only installed for python38, without the test passes!

**Comment by astrofrog** [comment] 2020-05-27 11:02
Interesting - we should make sure the tests pass with that plugin installed though!

**Comment by pllim** [comment] 2020-05-27 16:25
I have updated the title to reflect this new discovery. Thanks, everyone!

**Comment by pllim** [comment] 2020-05-28 21:54
Huh, I cannot reproduce this on Linux, so maybe it only affects OSX after all.
```
======================================= test session starts ========================================
platform linux -- Python 3.7.7, pytest-5.4.1, py-1.8.1, pluggy-0.13.1 -- ...miniconda/envs/py37/bin/python
cachedir: .pytest_cache
hypothesis profile 'normal' -> deadline=None, database=DirectoryBasedExampleDatabase('.../.hypothesis/examples')

Running tests with Astropy version 4.2.dev136+g399f7e11f.
Running tests in astropy/tests.

Date: 2020-05-28T17:48:47

Platform: Linux-3.10.0-1127.el7.x86_64-x86_64-with-redhat-7.7-Maipo

Executable: ....miniconda/envs/py37/bin/python

Full Python Version: 
3.7.7 (default, Mar 26 2020, 15:48:22) 
[GCC 7.3.0]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Package versions: 
Numpy: 1.18.1
Scipy: 1.4.1
Matplotlib: 3.1.3
h5py: not available
Pandas: not available
Cython: not available
Scikit-image: not available
asdf: not available

Using Astropy options: remote_data: any.

PyQt5 5.9.2 -- Qt runtime 5.9.7 -- Qt compiled 5.9.6
rootdir: ..., inifile: setup.cfg
plugins: openfiles-0.5.0, cov-2.8.1, hypothesis-5.13.0, astropy-header-0.1.2, filter-subpackage-0.1.1, doctestplus-0.6.1, arraydiff-0.3, remotedata-0.3.2, qt-3.3.0
collected 44 items / 38 deselected / 6 selected                                                    

.../astropy/tests/test_logger.py::test_exception_logging_disable_no_enable PASSED [ 16%]
.../astropy/tests/test_logger.py::test_exception_logging_enable_twice PASSED [ 33%]
.../astropy/astropy_core/astropy/tests/test_logger.py::test_exception_logging_overridden PASSED [ 50%]
.../astropy/tests/test_logger.py::test_exception_logging PASSED [ 66%]
.../astropy/astropy_core/astropy/tests/test_logger.py::test_exception_logging_origin PASSED [ 83%]
.../astropy/astropy_core/astropy/tests/test_logger.py::test_exception_logging_argless_exception SKIPPED [100%]

=========================== 5 passed, 1 skipped, 38 deselected in 0.27s ============================
<ExitCode.OK: 0>
```

**Comment by pllim** [comment] 2020-05-28 21:56
I installed `flaky` and things still passed with
```
plugins: openfiles-0.5.0, cov-2.8.1, hypothesis-5.13.0, astropy-header-0.1.2, filter-subpackage-0.1.1, doctestplus-0.6.1, arraydiff-0.3, remotedata-0.3.2, qt-3.3.0, flaky-3.6.1
```

**Comment by pllim** [comment] 2024-03-07 15:29
Haven't seen this resurface for 4 years, so closing.

**Closed by pllim** 2024-03-07 15:29 UTC
Labels: testing, Bug, logging, Mac OSX
