### ISSUE TITLE
Get scaled data from FITS GroupData

### ISSUE THREAD

**Issue by aplavin** [astropy/astropy#4502] opened 2016-01-18 16:36 UTC
After reading a data table (`GroupData`) from a FITS file there is no straightforward way to convert it to a plain `numpy` array with scaling applied. Currently I use code like this everywhere:

    np.rec.fromarrays([data[k] for k in data.dtype.names], dtype=data.dtype)

where `data` is the `GroupData` object.

I think something simple like a property implemented similar to the above would be nice. If that's OK, I can implement it.

**Comment by embray** [comment] 2016-01-19 16:11
I'm not exactly sure what you mean.  What do you mean by "scaling applied"?  Is this related to  #2751?

**Comment by aplavin** [comment] 2016-01-19 17:12
Well, I see that the issue description is a bit unclear :) So, example may show it better:

I have a data table in a fits file, and one of its columns is defined as so:

    >>> data.columns['DATE']
    name = 'DATE'; format = 'E'; bscale = 1.0; bzero = 2451910.0

Note the `bzero` (offset). When I get this column as `data['DATE']`, it returns correct values, with `bzero` added:

    >>> data['DATE'][0]
    2452095

And the returned array `data['DATE']` is just plain numpy array. But I see no direct way to get all the columns as an array, `np.asarray(data)` ignores `bzero` (and `bscale`):

    >>> np.asarray(data)['DATE'][0]
    185

**Comment by embray** [comment] 2016-01-19 17:37
I see. The issue you're having with `np.asarray` is the same as #3919.  What are are you actually trying to do?  There might be a simpler way.

**Comment by aplavin** [comment] 2016-01-19 18:10
I just need the data as a plain numpy array to use its features like selecting several columns (`data[['A', 'B']]` doesn't work with `GroupData` but works with numpy arrays), having the data stored sequentially (for interoperability with other code) and others.

**Comment by embray** [comment] 2016-01-19 22:18
Got it, that makes sense.  Your current workaround should work fine--a more comprehensive workaround isn't likely to come any time soon though.  There's a long history behind this issue.  As it is I'm going to close as a duplicate of #3919 since (although not obvious) it's the part and parcel of the same issue.

**Closed by embray** 2016-01-19 22:18 UTC
Labels: Duplicate, io.fits
