### ISSUE TITLE
Quantities are too mutable.

### ISSUE THREAD

**Issue by theXYZT** [astropy/astropy#7333] opened 2018-03-28 00:06 UTC
Example code:

```
import astropy.units as u

def f(x=4):
    x /= 2
    return x

def g(x=4*u.s):
    x /= 2
    return x

print(f()) # Expect 2.0
print(f()) # Expect 2.0
print(g()) # Expect 2.0 s
print(g()) # Expect 2.0 s ??
```
This generates the output:

```
2.0
2.0
2.0 s
1.0 s
```
---

By default, I would expect that an object to behave the same way with or without an astropy quantity attached to it. This doesn't seem to be the case. This seems to be a case of `Quantity` being too mutable.

**Comment by Cadair** [comment] 2018-03-28 10:37
interestingly this:

```python
def h(x=np.array(4)):                                                           
    x /=2                                                                       
    return x
```
throws:
```
TypeError: No loop matching the specified signature and casting was found for ufunc true_divide
```

(A `Quantity` is always a numpy array and not a integer)

**Comment by astrofrog** [comment] 2018-03-28 11:09
Python objects are either mutable or unmutable - and in the case of quantities I think they are intended to be mutable, so this is expected behavior? Using mutable objects as default keyword arguments is not recommended in general:

```
In [2]: def i(x=[]):
   ...:     x.append(1)
   ...:     print(x)
   ...:     

In [3]: i()
[1]

In [4]: i()
[1, 1]
```

**Comment by Cadair** [comment] 2018-03-28 11:14
I would also expect this behaviour, I just also expected numpy to do the same thing :laughing:

**Comment by pllim** [comment] 2018-03-28 13:06
```python
def g(x):
    x /= 2
    return x
```

I agree with @astrofrog . Using `x` is positional argument will not have this problem with Quantity.

**Comment by mhvk** [comment] 2018-04-13 15:44
I think given that numpy arrays are mutable, and so would have the same issue as in this example, users can surely expect that quantity arrays would have this issue as well. That then leaves the question whether quantity scalars should be mutable or not. For numpy, array scalars are mutable, but regular scalars are not. Personally, I would find it troubling if a function with `f(x=[4, 4]*u.s)` worked differently than `f(x=4*u.s)`. But perhaps there is a case to be made for a non-mutable `QuantityScalar` class? (this might resolve several other issues related to quantity scalars)

**Comment by mhvk** [comment] 2019-06-22 00:30
Closing this one as I do not see us doing anything about it; the `QuantityScalar` class is quite a bit of work for no obvious benefit.

**Closed by mhvk** 2019-06-22 00:30 UTC
Labels: question, units
