### ISSUE TITLE
Install not compatible with netcdf4?

### ISSUE THREAD

**Issue by njmessina** [astropy/astropy#8419] opened 2019-02-12 06:16 UTC
Hi there...
I recently updated Astropy via Anaconda so I can use the convolution routines.  The update did something to libssh2 such that netcdf4 no longer works.  When importing netcdf4, I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/joe/anaconda/lib/python3.6/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: dlopen(/Users/joe/anaconda/lib/python3.6/site-packages/netCDF4/_netCDF4.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libssl.1.0.0.dylib
  Referenced from: /Users/joe/anaconda/lib/libssh2.1.dylib
  Reason: image not found
```
I did not get this error before updating Astropy.  This happened today (Feb 11, 2019).  Netcdf4 is critical for my work so this is very disappointing.   I'm using a Macbook Air with OS X 10.11.6 if that makes a difference.  After this happened, I tried removing libssh2 and Netcdf4 and reinstalling both.  It did not fix the problem.  I got the same error as above.  Thank you...
Joe

**Comment by bsipocz** [comment] 2019-02-12 06:24
Please report this to `Netcdf4`, we can't do much about their broken installation neither their relationship to libssh.

As a workaround try to downgrade your libssh (to reiterate astropy is not sensitive to which version of that is installed, your conda must have independently updated it during the astropy update).
If nothing else work, I would suggest to uninstall astropy from your conda, downgrade the libssh version to what it used to be before the update and pip install astropy.

**Comment by astrofrog** [comment] 2019-02-12 09:38
Just to add to what @bsipocz said, you mentioned that the issue is when importing ``netcdf4`` - conda has a habit of updating a whole bunch of packages when updating another, and in this case since the issue you are having is with netcdf4 rather than astropy, I would recommend opening an issue at https://github.com/ContinuumIO/anaconda-issues/issues instead.

Are you having any issues importing astropy itself?

**Comment by njmessina** [comment] 2019-02-12 14:37
No, astropy seems to work fine.  Ok, thank you!
Joe

On Feb 12, 2019, at 2:38 AM, Thomas Robitaille <notifications@github.com<mailto:notifications@github.com>> wrote:


Just to add to what @bsipocz<https://github.com/bsipocz> said, you mentioned that the issue is when importing netcdf4 - conda has a habit of updating a whole bunch of packages when updating another, and in this case since the issue you are having is with netcdf4 rather than astropy, I would recommend opening an issue at https://github.com/ContinuumIO/anaconda-issues/issues instead.

Are you having any issues importing astropy itself?

**Comment by astrofrog** [comment] 2019-02-12 16:59
Ok - in that case I'll close this issue since you opened one for anaconda. Thanks!

**Closed by astrofrog** 2019-02-12 16:59 UTC
Labels: installation, question
