### ISSUE TITLE
Use numpy bin calculation where possible

### ISSUE THREAD

**Issue by mwcraig** [astropy/astropy#7982] opened 2018-10-26 18:17 UTC
It looks like numpy now supports a [pretty wide array of approaches calculating bin sizes](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.histogram_bin_edges.html#numpy.histogram_bin_edges), some of which overlap with what is currently in astropy.stats. When possible it seems like a good idea to defer to numpy, and astropy's hist/histogram should allow access to all of the numpy types.

**Comment by crawfordsm** [comment] 2018-12-06 05:16
Closing due to duplicate of #8011

**Closed by crawfordsm** 2018-12-06 05:16 UTC
Labels: stats, visualization
