### ISSUE TITLE
"UnitsError: __ and __ are not convertible" raised when converting compatible units

### ISSUE THREAD

**Issue by dannygoldstein** [astropy/astropy#3788] opened 2015-05-20 21:33 UTC
Using astropy version 1.0.1. 

I've defined a function `R(z)` that returns an `astropy.quantity.Quantity` with a somewhat unwieldy unit:

```python
In [25]: R(z)
Out[25]: <Quantity 0.22371094441030753 cm3 m(2/5) solMass(6/5) / (g(4/5) kg(2/5) solRad(12/5))>
```

This quantity has units of length (checkable by hand or via the third code block in this issue). However, I encounter the following:

```python
In [32]: R(z).to(u.solRad)
---------------------------------------------------------------------------
UnitsError                                Traceback (most recent call last)
<ipython-input-32-4c956766c9bf> in <module>()
----> 1 R(z).to(u.solRad)

/Users/dannygoldstein/anaconda/lib/python2.7/site-packages/astropy/units/quantity.pyc in to(self, unit, equivalencies)
    603         unit = Unit(unit)
    604         new_val = np.asarray(
--> 605             self.unit.to(unit, self.value, equivalencies=equivalencies))
    606         return self._new_view(new_val, unit)
    607

/Users/dannygoldstein/anaconda/lib/python2.7/site-packages/astropy/units/core.pyc in to(self, other, value, equivalencies)
    943             If units are inconsistent
    944         """
--> 945         return self._get_converter(other, equivalencies=equivalencies)(value)
    946
    947     def in_units(self, other, value=1.0, equivalencies=[]):

/Users/dannygoldstein/anaconda/lib/python2.7/site-packages/astropy/units/core.pyc in _get_converter(self, other, equivalencies)
    847         except UnitsError:
    848             return self._apply_equivalences(
--> 849                 self, other, self._normalize_equivalencies(equivalencies))
    850         return lambda val: scale * _condition_arg(val)
    851

/Users/dannygoldstein/anaconda/lib/python2.7/site-packages/astropy/units/core.pyc in _apply_equivalences(self, unit, other, equivalencies)
    838         raise UnitsError(
    839             "{0} and {1} are not convertible".format(
--> 840                 unit_str, other_str))
    841
    842     def _get_converter(self, other, equivalencies=[]):

UnitsError: 'cm3 m(2/5) solMass(6/5) / (g(4/5) kg(2/5) solRad(12/5))' and 'solRad' (length) are not convertible
```

However, the following works:

```python
In [33]: R(z).cgs
Out[33]: <Quantity 7701052083680.192 cm>
```

As does:

```python
In [35]: R(z).cgs.to(u.solRad)
Out[35]: <Quantity 110.72557157761223 solRad>
```

Danny

**Comment by dannygoldstein** [comment] 2015-05-20 21:42
Updated to 1.0.2 and the problem persists.

**Comment by mdboom** [comment] 2015-05-20 22:01
Hmm...  Checking by hand, I get that the unit reduces to (m g) (with some scaling factor).  So I'm surprised by this working:

```
R(z).cgs.to(u.solRad)
```

and, indeed, it doesn't work for me.

Can you provide a standalone example to reproduce?  I may be creating the unit in a slightly different way than you which is triggering something rather subtle.

**Comment by dannygoldstein** [comment] 2015-05-20 22:08
By hand:

```python
<Quantity 0.22371094441030753 cm3 m(2/5) solMass(6/5) / (g(4/5) kg(2/5) solRad(12/5))>
```

has units of `length**(15/5) * length**(2/5) * mass**(6/5) * mass**(-4/5) * mass**(-2/5) * length**(-12/5) = length ** (5/5) * mass**0  = length`

example coming up...

**Comment by mdboom** [comment] 2015-05-20 22:11
Oh, yeah -- sorry -- I made a mistake in my by hand calculations.  There's something fishy here...

**Comment by dannygoldstein** [comment] 2015-05-20 22:22
Here is the relevant code.

```python
@property
@output_in(u.solRad)
def R(self):
    t1 = 2 * c.c / (self.kappa * scipy.sqrt(scipy.pi))
    t2 = gamma(self.alpha + 1.5) / gamma(self.alpha + 1)
    t3 = (self.r_0**-self.q) / (self.rho_0 * self.y * self.beta * (self.a * c.G * self.m_h)**0.5)
    return (t1 * t2 * t3)**scipy.reciprocal(0.5 - self.q)
```

`output_in(unit)` is a decorator that just calls `.to(unit)` on the result of `R`. `alpha`, `beta`, `y`, `a`, and `q` are dimensionless constants (floats). `c.G` is `astropy.constants.G`. `c.c` is `astropy.constants.c`. `m_h` is an `astropy.quantity.Quantity` in `solMass`. `kappa` is an `astropy.quantity.Quantity` in `cm2 / g`. `gamma` is `scipy.special.gamma`. `rho_0` is an `astropy.quantity.Quantity` in `solMass / solRad3`.  `r_0` is an `astropy.quantity.Quantity` in `solRad`. 

Danny

**Comment by dannygoldstein** [comment] 2015-05-20 22:26
In my original post, I had defined `R` outside of the class that contains it in the post above, passing `z` in for `self` and removing the `property` decorator from the function.

Danny

**Comment by mdboom** [comment] 2015-05-21 00:22
Sorry -- I need a self-contained example (http://sscce.org).  There's too much room for doing it differently in your prose description.

This works:

```
In [1]: from astropy import units as u                                                           
In [2]: x = (u.cm ** 3 * u.m ** (2./5) * u.solMass**(6./5)) / (u.g ** (4./5) * u.kg ** (2./5) * u.solRad ** (12./5))

In [3]: x
Out[3]: Unit("cm3 m(2/5) solMass(6/5) / (g(4/5) kg(2/5) solRad(12/5))")

In [4]: x.decompose()
Out[4]: Unit("3.44241e+11 m")
```

**Comment by dannygoldstein** [comment] 2015-05-21 03:38
Here is the self-contained version, with variable values taken from my previous code block:

```python
from astropy import constants as c
from astropy import units as u
import scipy
from scipy.special import gamma

kappa = 0.34 * u.cm**2 / u.g
alpha = 1.2500000000000002
r_0 = 886221439924.7849 * u.cm
q = 1.7500000000000004
rho_0 = 5e-10 * u.solMass / u.solRad**3
y = 0.5
beta = 0.19047619047619049
a = 0.47619047619047628
m_h = 1e6*u.solMass

t1 = 2 * c.c / (kappa * scipy.sqrt(scipy.pi))
t2 = gamma(alpha + 1.5) / gamma(alpha + 1)
t3 = (r_0**-q) / (rho_0 * y * beta * (a * c.G * m_h)**0.5)

result = ((t1 * t2 * t3)**scipy.reciprocal(0.5-q))

print result.to(u.solRad) # produces astropy.units.core.UnitsError: 'cm3 m(2/5) solMass(6/5) / (g(4/5) kg(2/5) solRad(12/5))' and 'solRad' (length) are not convertible
print result.decompose() # produces 77010520836.8 m
```

**Comment by mdboom** [comment] 2015-05-21 13:40
Thanks for this great example -- it really exercises some nasty corner cases of unit simplification.

There's really two problems here, one in your code and one in astropy.

Setting `q` to `1.7500000000000004` results in a power that is not exactly `7/4` and therefore doesn't simplify away.  One could say that we expect astropy to "guess" and simplify this to `1.75` here, but we've been down that road early in `astropy.units` development, and that kind of guessing and implicit rounding can run into all kinds of confusing corner cases when the code stops "doing exactly what the user asked".  We can't promise to read the user's mind, but we can promise to maintain exactly what the user said...

...which leads to the problem inside astropy.  When the two `solMass` components are multiplied together we get this:

```
float(-1.5) * Fraction(-4, 5)  == float(1.2000000000000002)
```

So there we've introduced some floating-point rounding error.  What we should be doing is converting the lhs to a Fraction and multiplying using rational arithmetic (as we already do when adding powers -- not doing this for multiplying powers was just an oversight).  #3790 has a fix for this.

All of this is a bit complicated by an important optimization in astropy: when powers are perfectly represented as floating-point numbers (when the denominator is a power of 2), we want to store them that way because operations on floats are many times faster -- and most unit expressions tend to have whole number powers anyway.  But that means you have to be careful when mixing floats and Fractions.

**Closed** 2015-05-21 18:41 UTC
Labels: units
