### ISSUE TITLE
'astropy/_erfa/core.py' has no attribute '_s2c' in current dev version

### ISSUE THREAD

**Issue by luojing1211** [astropy/astropy#5333] opened 2016-09-14 17:07 UTC
Hi astropy developers, 

I am running into this error while using the '1.3.dev16076' version.  Can you tell me how to resolve it?

```
>>> import astropy
>>> astropy.__version__
u'1.3.dev16076'
>>> from astropy.time import Time
>>> from astropy.coordinates import solar_system_ephemeris, EarthLocation
>>> from astropy.coordinates import get_body_barycentric, get_body, get_moon
>>> t = Time("2014-09-22 23:22")
>>> loc = EarthLocation.of_site('greenwich')
>>> with solar_system_ephemeris.set('builtin'):
...      jup = get_body('jupiter', t, loc)

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "astropy/coordinates/solar_system.py", line 459, in get_body
    obsgeoloc, obsgeovel = location.get_gcrs_posvel(time)
  File "astropy/coordinates/earth.py", line 528, in get_gcrs_posvel
    obsgeoloc = itrs.transform_to(geocentric_frame).cartesian
  File "astropy/coordinates/baseframe.py", line 912, in transform_to
    return trans(self, new_frame)
  File "astropy/coordinates/transformations.py", line 916, in __call__
    curr_coord = t(curr_coord, curr_toframe)
  File "astropy/coordinates/transformations.py", line 707, in __call__
    res = self.func(fromcoord, toframe)
  File "astropy/coordinates/builtin_frames/intermediate_rotation_transforms.py", line 68, in cirs_to_gcrs
    return gcrs.transform_to(gcrs_frame)
  File "astropy/coordinates/baseframe.py", line 912, in transform_to
    return trans(self, new_frame)
  File "astropy/coordinates/transformations.py", line 916, in __call__
    curr_coord = t(curr_coord, curr_toframe)
  File "astropy/coordinates/transformations.py", line 707, in __call__
    res = self.func(fromcoord, toframe)
  File "astropy/coordinates/builtin_frames/icrs_cirs_transforms.py", line 215, in gcrs_to_gcrs
    return from_coo.transform_to(ICRS).transform_to(to_frame)
  File "astropy/coordinates/baseframe.py", line 912, in transform_to
    return trans(self, new_frame)
  File "astropy/coordinates/transformations.py", line 916, in __call__
    curr_coord = t(curr_coord, curr_toframe)
  File "astropy/coordinates/transformations.py", line 707, in __call__
    res = self.func(fromcoord, toframe)
  File "astropy/coordinates/builtin_frames/icrs_cirs_transforms.py", line 180, in gcrs_to_icrs
    i_ra, i_dec = aticq(gcrs_ra, gcrs_dec, astrom)
  File "astropy/coordinates/builtin_frames/utils.py", line 159, in aticq
    pos = erfa.s2c(ri, di)
  File "astropy/_erfa/core.py", line 24440, in s2c
    stat_ok = _core._s2c(it)
AttributeError: 'module' object has no attribute '_s2c'
```
Thank you.

**Comment by astrofrog** [comment] 2016-09-14 17:22
@luojing1211 - thanks for opening an issue - how did you install Astropy?

**Comment by MSeifert04** [comment] 2016-09-14 17:23
@luojing1211 Thank you for the report. However I can't reproduce this issue. 

This works without failure on Windows 10, Python 3.5. Maybe you need to recompile your development version of astropy.

**Comment by luojing1211** [comment] 2016-09-14 17:24
I get my astropy from github and ran 
```
$ python setup.py --offline install
```

**Comment by astrofrog** [comment] 2016-09-14 17:31
@luojing1211 - are you currently trying to import astropy from the actual git checkout? Can you make sure this error happens irrespective of which directory you are in when running Python?

**Comment by luojing1211** [comment] 2016-09-14 17:38
It worked just by getting out of astropy directory. Thank you.

**Comment by luojing1211** [comment] 2016-09-14 17:43
Is there anything I should know about? Can I close the issue right now?

**Comment by pllim** [comment] 2016-09-14 17:52
Seems resolved. Closing.

**Closed by pllim** 2016-09-14 17:52 UTC
Labels: coordinates
