### ISSUE TITLE
Time creation for unix time is very slow

### ISSUE THREAD

**Issue by Laubeee** [astropy/astropy#10587] opened 2020-07-20 16:54 UTC
This issue is very likely related to #5846 and #10167.

When using `astropy.time.Time` to convert unix timestamps (or utime) to datetime, it's more than factor 1000 slower than using `datetime.utcfromtimestamp()`.

I benchmarked converting 2000 values, which is not even much when reading fits files
```python
Time(times[i], format="unix")  # 1.61s
datetime.utcfromtimestamp(times[i])  # 998µs

Time(times[i], format="utime")  # 1.74s
datetime.utcfromtimestamp(times[i] + offset)  # 2ms, offset being set to Time(0, format="utime").to_value("unix")
```

Astropy does some special checks for leap seconds and so on, but I haven't found an example where the native conversion differs from astropy using seconds as the smallest unit.. is there any at all? If not, would it be feasible to convert those two formats using the native `datetime` module? If not, what is causing this huge difference..? seems a bit strange to me

**Comment by pllim** [comment] 2020-07-20 17:03
Thanks for reporting this!

Could you please give a fully reproducible example, including the data, if possible?

Is there a reason why you are looping through with `[i]` instead of passing in `times` all at once?

If you are interested to pursue this further, you can also try profiling it to see where the bottleneck is.

**Comment by Laubeee** [comment] 2020-07-20 17:30
Nothing fancy, really, it looks like this
```python
from random import randrange
times = [randrange(298724974, 1208724974) for i in range(2000)]


%%time
for i in range(len(times)):
    # examples from first post
```

so, the low values are surely inaccurate, but you get the idea. The difference is huge.
I just tried 200k values for the datetime functions, and got ~125 and ~300 ms respectively.

The reason is in my use case I go row-by-row through fits data and convert several fields before adding them to my data structure (right now pandas DF, might use astropy table in the future)

From what I read in the other issues, it sounds a lot like its quickly going to be diving into 3rd party native libs, so for now I'd prefer to discuss whether there are actual values that give different results for the respective examples

**Comment by taldcroft** [comment] 2020-07-21 09:54
@Laubeee - the upshot is that creating a `Time` object is a relatively expensive since there is a fair bit of infrastructure associated with the general support of many different formats and sub-nanosec precision.  If you cannot vectorize (create one `Time` object with all the values at once) and performance is an issue, then you are better off with your solution of using `datetime` to do the conversion.

I will note that astropy 4.1 will improve the speed of creation for this case by about a factor of 4:
### Astropy 4.0.1
```
In [2]: astro                                                                   
astropy=4.0.1.post1

In [3]: %timeit Time(1, format='unix')                                          
267 µs ± 2.86 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
### astropy 4.1
```
In [1]: astro                                                                   
astropy=4.2.dev396+g0fd0be3c3.d20200710

In [2]: %timeit Time(1, format='unix')                                          
66.9 µs ± 580 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

**Comment by taldcroft** [comment] 2020-07-21 09:56
Please also be aware that the astropy `TimeUnix` class has some caveats described in https://docs.astropy.org/en/latest/api/astropy.time.TimeUnix.html#astropy.time.TimeUnix.

You might also be interested in https://docs.astropy.org/en/latest/api/astropy.time.TimeUnixTai.html#astropy.time.TimeUnixTai, which will be available when 4.1 gets released.

**Comment by Laubeee** [comment] 2020-07-21 10:41
Well performance is not an issue per se, but speeding up loading data by a factor ~10 sure is a lot more convenient.

Thanks for the clarifications. I think since the instrument I am using reported the time in "utime", sub-nanosecond precision can be neglected / is not applicable anyway in that case. As far as I understand the "utime" convention, it is unix time shifted by 9 years, so using strict POSIX-compliant conversion should give correct results.

> I will note that astropy 4.1 will improve the speed of creation for this case by about a factor of 4:

isn't it factor 40? note that timeit ran 10k loops in 4.1, and only 1k in 4.01

**Comment by mhvk** [comment] 2020-07-21 14:02
> The reason is in my use case I go row-by-row through fits data and convert several fields before adding them to my data structure (right now pandas DF, might use astropy table in the future)

If you are reading from fits, would it not be possible to avoid going through a python datetime in the first place? Astropy is meant to be able to deal with FITS times and that will likely be both more accurate and faster. I'd generally try to avoid `datetime` as it simply cannot handle leap seconds (try an actual leap second, with seconds=60!).

**Comment by Laubeee** [comment] 2020-07-21 14:41
Not sure what your suggestion is.. in the first place I need some kind of conversion into a human readable format (and a few difference calculations, but they can also be done using the original number format).
So I used to convert them with `sunpy.time.parse_time` which then again uses `astropy.time.Time` (and conveniently allows to pass the format "utime") but as I pointed out, that was extremely slow, hence my fallback to `datetime`.

I have not yet tried converting times all at once which seems to be faster (is that what you suggest? I doubt faster than `datetime` though). It would need some tweaks for the "2D" fields and its only benefit is the display of hh:mm:60 times, right? Allowing that would indeed be the cleaner solution, even if I'm pretty sure it has no practical relevance in this case, but if it comes at the cost of significant performance drop I probably stick to `datetime`. 

```python
f = fits.open('http://hessi.ssl.berkeley.edu/hessidata/dbase/hessi_flare_list_200311.fits')
f[3].data.columns
```

```
ColDefs(
    name = 'ID_NUMBER'; format = '1J'
    name = 'START_TIME'; format = '1D'
    name = 'END_TIME'; format = '1D'
    name = 'PEAK_TIME'; format = '1D'
    name = 'BCK_TIME'; format = '2D'
    name = 'IMAGE_TIME'; format = '2D'
[...]
```

side note: I assume there is not (yet) something like a short guide on when to use what kind of time objects and differences over each other, maybe even with some code samples? That would be very nice.

**Comment by mhvk** [comment] 2020-07-21 15:50
An actual example is always useful! Since the `start_time` and `end_time` are just doubles, one would initialize from those (which you probably already did...). Going from your example:
```
from sunpy import time  # just to ensure utime is defined
from astropy.time import Time
from datetime import datetime
d  = f[3].data
nineyear = int(9*365.25*24*3600)
%timeit datetime.utcfromtimestamp(d['start_time'][0]+nineyear)                                
# 20.4 µs ± 55 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
%timeit Time(d['start_time'][0], format='utime')                                     
# 305 µs ± 1.15 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
which is oddly slower for `datetime` -- investigating it a bit it seems that getting the element out of the fits file completely dominates that duration... Still, arguably, since you have to do that regardless, it means the extra cost of `Time` is about a factor 15, not a 1000...

Less facetiously, as noted above and more closely to what I had in mind too, if you are actually interested in all the times, things do improve considerably:
```
# hardly a slowdown in you get all 1151 in one go
%timeit Time(d['start_time'], format='utime')
# 456 µs ± 1.04 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
# And easy to get human-readable if need be.
Time(d['start_time'], format='utime').isot                                                    
# array(['2003-11-01T00:01:36.000', '2003-11-01T04:51:56.000',
#        '2003-11-01T04:55:24.000', ..., '2003-11-30T22:41:12.000',
#        '2003-11-30T23:11:28.000', '2003-11-30T23:22:00.000'], dtype='<U23')
```

In the end, I fear that it is a bit like is the case for numpy - scalar work is much slower than for pure python:
```
d0 = d['start_time'][0]
type(d0)
# numpy.float64
%timeit d0 + nineyear
# 251 ns ± 1.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
%timeit float(d0) + nineyear                                                                  
# 93.6 ns ± 0.0879 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```
p.s. `sunpy.time.parse_time` seems to do the same, since it ihas the same speed.
p.s.2 On a short guide: that's very much were people who haven't use `Time` as much come in!

**Comment by Laubeee** [comment] 2020-07-21 16:16
> it means the extra cost of `Time` is about a factor 15, not a 1000...

once again, loop counts are different. Maybe I misunderstand this, but IMO its a factor of 150.

> `Time(d['start_time'], format='utime')`

this wont work for the 2D fields (BCK_/IMAGE_) though.. I could split them up since I anyway have to loop through the rows for other things.. or use numpy to flatten, convert, reshape it

**Comment by mhvk** [comment] 2020-07-21 16:53
@Laubeee - `%timeit` always reports per loop, it just tries more or less time depending on how long it taks.

There's no need to treat higher-dimensional arrays differently: `Time` will just have the corresponding shape.

**Comment by taldcroft** [comment] 2020-07-21 17:21
@mhvk - one thing I have pondered on and off is providing format_X to format_Y converter methods that bypass some of the Time machinery and basically go straight to ERFA.  I haven't gone any deeper than that level of thought, but if it were possible to make some very fast such methods I expect it would find use in the community. In other words one of main uses of `Time` is just as a conversion engine.

**Comment by mhvk** [comment] 2020-07-21 19:02
@taldcroft - interesting thought: It might be something that would fall back on `Time(value, format=<from-format>).to_value(<to-format>)`, but has short-cuts for specific `from/to-format` combinations. Possibly, the fast converters could stored on the `to-format` `TimeFormat` classes?

**Comment by taldcroft** [comment] 2020-07-22 10:20
@mhvk - yup, sounds about right.

**Comment by Laubeee** [comment] 2020-07-22 10:36
> There's no need to treat higher-dimensional arrays differently

Seems I made an error when I tried to quickly test if this works, my bad!

> `%timeit` always reports per loop, it just tries more or less time depending on how long it taks.

I see. This difference in our measurements made me replicate your experiment, its down to ~factor 12 at my end, which also makes sense with the overall-improvement I observed for the whole read-data function. (2.5 instead of 18.5 s for a given set of fits files of various size).

So I did a few more measurements (and btw: timeit also doesn't seem to be too accurate on such tiny operations, so i ran it a few times):
```python
%timeit Time(d['start_time'], format='utime')  # 762 µs ± 51.3 µs / 825 µs ± 80.8 µs / 745 µs ± 20.4 µs
```

```python
%%timeit
for t in d['start_time']:
    pass  # including the loop as I use it anyway, but tbh it doesnt add too much time
Time(d['start_time'], format='utime')
# 920 µs ± 72 µs / 942 µs ± 93 µs / 907 µs ± 60.7 µs
```

```python
%%timeit
for t in d['start_time']:
    datetime.utcfromtimestamp(t + nineyear)
# 734 µs ± 47.2 / 696 µs ± 31.1 µs / 681 µs ± 36.8 µs
```

interesting that also the `datetime` loop doesn't scale linearly, compared to the ~27 µs per op that timeit reports.
Anyway, conclusion: passing the whole thing at once seems feasible and fast enough. However I'd be happy if this could be pointed out in the docs e.g. [here ](https://docs.astropy.org/en/stable/time/) and [here](https://docs.astropy.org/en/stable/api/astropy.time.Time.html#astropy.time.Time) (and possibly in sunpy `parse_time`)

P.S. why is your nine-years *exactly* 6h off of "my" version? Check:
`Time(0, format="utime").to_value("unix") - 9*365.25*24*3600`
or
```
print(Time(1208754974, format='utime').isot)
print(datetime.utcfromtimestamp(1208754974 + int(9*365.25*24*3600)).isoformat())
```

I used the utime-offset because I thought (as it turns out wrongly) that the unix timestamps do include leap seconds

**Comment by taldcroft** [comment] 2020-07-22 11:43
>  timeit also doesn't seem to be too accurate on such tiny operations, so i ran it a few times

Notice the error bars, meaning the three values are statistically consistent.  Also, timeit (or any timing operation) can be subject to variations due to what is happening in the background on your computer. At least from my experience on a Mac, there are frequently system processes that impact timing.

**Comment by mhvk** [comment] 2020-07-22 13:41
@Laubeee - oops, the implicit leap-day correction in my simple-minded addition of 9 years is wrong; should be `(365*7+366*2)*24*3600`. Just goes to show...

**Comment by mhvk** [comment] 2020-07-22 13:50
On the docs, perhaps this is something that could go in `docs/time/performance.inc.rst`?

The trouble as always is to find a place where people who need it will find it, while it doesn't distract those who are just trying to find out how to use `Time` and hence do not need it. Though perhaps a general section on "Arrays are always better!" might not be a bad idea... (this most definitely holds for `SkyCoord` too).

**Comment by Laubeee** [comment] 2020-07-22 15:55
yeah.. and I suppose its generally the better way to use the fits data.
I could halve the 2.5s (originally 18.5s) for my testcase by building a dictionary containing lists and using `pd.DataFrame.from_dict()`, which allows to copy data more efficiently in most cases. Instead of row-by-row assignment I can just assign the whole column if I don't do anything with the values.

Then switching back from `datetime` to `parse_time(col, format="utime").to_value('datetime')` made the whole thing even faster (now at ~1s), which I suppose is because it is somehow faster in accessing the data from fits (like you stated initially), so its really about single value conversion that has a bad performance..

so right now, the actual read-fits operation is 36% of the time, some other conversions/calculations I do are 50%, and only 5% are time field conversions. Seems legit :)

Thanks for all the advice and the general good discussion.

Possible actions to close this issue (to summarize quickly)
- add some hints about performance in the docs, maybe a guide / a tutorial might be useful (or extending an existing one)
- fall back for conversion-only operations that omit some more sophisticated time logic

**Comment by mhvk** [comment] 2020-07-22 19:33
@Laubeee - happy to hear it now works well - these types of discussions are very valuable, also for us!

**Comment by mhvk** [comment] 2020-07-22 20:00
@Laubeee, @taldcroft - It seems easier to have new issues rather than have people read through all of the above, so I opened #10596 and #10597 about the two points resulting from our discussion. I'll close this one now; feel free to add to the two issues (or re-open this one if I missed something!).

**Closed by mhvk** 2020-07-22 20:01 UTC
Labels: Performance, time
