### ISSUE TITLE
MaskedColumn in fits for dtype float

### ISSUE THREAD

**Issue by Nicksname** [astropy/astropy#7452] opened 2018-05-11 09:31 UTC
When a MaskeColumn with dtype float is written to a fits file the information about the masked values is lost and the mask not generated when the table is read

```python 
import numpy as np
from astropy.table import Table

Table(np.ma.masked_array([1.], mask=True)).write('test.fits')
print(t.read('test.fits'))
```
returns an unmasked Table
```
col0
----
 nan
```
This is more problematic if the fill value is different from `nan`

```python
Table(np.ma.masked_array([1.], mask=True, fill_value=0)).write('test.fits')
print(t.read('test.fits'))
```
returns an unmasked Table
```
col0
----
 0.0
```
This is not the case if the data type is `int`.

**Comment by pllim** [comment] 2018-05-11 13:41
Is this a duplicate of #4708 ?

**Closed** 2018-05-15 09:54 UTC
Labels: Close?, io.fits, table
