### ISSUE TITLE
Unexpected results from sigma_clipped_stats for large np.float32 input arrays

### ISSUE THREAD

**Issue by prutschman-iv** [astropy/astropy#17185] opened 2024-10-15 21:21 UTC
### Description

I'm processing 63 megapixel FITS images using sigma_clipped_stats, and have run into behavior where the endianness of the 32-bit float data is apparently affecting the correctness of the output.

Specifically, data loaded directly out of the fits file `dtype('>f4')` is working correctly. But if I perform numerical operations on the data--or explicitly cast it--such that it becomes `dtype('<f4')` (which is the native float32 on x64: `dtype('<f4')==dtype('float32')`), I get what appear to be incorrect results.

This only happens with large arrays. I haven't determined the exact cutoff, but (4096,4096) appears to work correctly. (6388,9576) does not.

### Expected behavior

I expect `astropy.stats.sigma_clipped_stats(np.array(data,'>f4'))` and `astropy.stats.sigma_clipped_stats(np.array(data,'<f4'))` to produce identical, or at least substantially similar results.

(It appears that there's also a difference in precision calculated in these two cases--while odd, this is not the issue I'm reporting.)

### How to Reproduce

This can be reproduced by generating a random uniform [0-1] array with np.random.random. The mean and median should be approximately 0.5, and the stddev should be approximately 0.288.

The sample code generates arrays of two sizes, and processes them in each endianness. The first three lines have output values that I expect. The last line (larger array, '<f4') gives very different results.

```python
import numpy as np
import astropy, astropy.stats
rand_data = np.random.random(size=(1024,1024))
print(astropy.stats.sigma_clipped_stats(np.array(rand_data,'>f4'), sigma=3, maxiters=5))
print(astropy.stats.sigma_clipped_stats(np.array(rand_data,'<f4'), sigma=3, maxiters=5))
rand_data = np.random.random(size=(6388,9576))
print(astropy.stats.sigma_clipped_stats(np.array(rand_data,'>f4'), sigma=3, maxiters=5))
print(astropy.stats.sigma_clipped_stats(np.array(rand_data,'<f4'), sigma=3, maxiters=5))
```
When  I ran this, I got:
```
(0.4994579, 0.4990998, 0.2887525)
(0.49945005774497986, 0.4990997910499573, 0.28869783878326416)
(0.4999373, 0.49990413, 0.28868327)
(0.2742652893066406, 0.4999041259288788, 0.3462343215942383)
```

### Versions

```
Windows-10-10.0.19045-SP0
Python 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
astropy 6.1.4
Numpy 1.24.0
pyerfa 2.0.1.4
Scipy 1.11.2
Matplotlib 3.8.0
```

**Comment by pllim** [comment] 2024-10-15 21:31
I wonder if this has been fixed by https://github.com/astropy/astropy/pull/17086 . I cannot reproduce the error on `main`. Can you please try with dev version of astropy? Thanks!

https://docs.astropy.org/en/latest/install.html#install-pre-built-development-version

**Comment by prutschman-iv** [comment] 2024-10-15 22:28
I installed `7.0.0.dev1184+g8a8ee60208` and am still seeing the issue. However, after further experimentation I've determined that it only happens if `Bottleneck` is installed, in both 6.1.4 and 7.0.0.dev. I've reproduced this with the latest release of Bottleneck, 1.4.1.

This appears to be a bug in Bottleneck. I get the same erroneous values for mean and stddev by invoking `bn.nanmean` and `bn.nanstd` on the test vectors.

**Comment by pllim** [comment] 2024-10-15 22:42
Oh, thanks for the clarification! If you report upstream to https://github.com/pydata/bottleneck , please cross link here.

**Comment by prutschman-iv** [comment] 2024-10-15 22:52
I'll report upstream. This issue also appears to be at least related if not a dupe of https://github.com/astropy/astropy/issues/11492 but with potentially more serious consequences for accuracy.

**Comment by pllim** [comment] 2024-10-15 23:02
Hmm... Let's ping @larrybradley @astrofrog @saimn then. If they decide it is indeed duplicate, they will know how to handle the issues. Thanks!

**Comment by larrybradley** [comment] 2024-10-16 13:15
@mhvk Should we update Astropy's sigma clipping to always use `np.nan*` functions for `float32` input?

**Comment by saimn** [comment] 2024-10-16 15:58
Note this was reported at the time of #11492: https://github.com/pydata/bottleneck/issues/379
But bottleneck is lacking maintainers since a few years, we had other issues and discussed removing it in #11492. I think we should remove it, slower and correct is better than faster and incorrect ;), and people can still pass their mean/std func if they want to.

**Comment by prutschman-iv** [comment] 2024-10-16 16:17
@larrybradley 
> Do `float` (`float64`) arrays show this same problem?

For the array sizes and input range I tested, float64 results between numpy and bottleneck agree to many decimal places.

**Comment by larrybradley** [comment] 2024-10-16 16:52
@saimn What about removing it for only `float32` input?

**Comment by saimn** [comment] 2024-10-16 18:14
@larrybradley - maybe if bottleneck is still significantly faster than numpy, but numpy's performance improved a lot over recent years so not sure. Very quick tests doesn't show a huge gain:

```
In [16]: data = np.random.uniform(size=(8000, 8000))

In [17]: %timeit np.nanmedian(data)
522 ms ± 12.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [18]: %timeit np.nanmedian(data)
520 ms ± 6.96 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [19]: %timeit bn.nanmedian(data)
518 ms ± 7.95 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [20]: %timeit bn.nanmedian(data)
512 ms ± 1.74 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [21]: x = rng.integers(0, 8000, 100)

In [22]: y = rng.integers(0, 8000, 100)

In [23]: data[x,y] = np.nan

In [24]: %timeit np.nanmedian(data)
568 ms ± 3.77 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [25]: %timeit np.nanmedian(data)
569 ms ± 3.97 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [26]: %timeit bn.nanmedian(data)
526 ms ± 18.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [27]: %timeit bn.nanmedian(data)
556 ms ± 33.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by neutrinoceros** [comment] 2024-10-17 07:10
If the performance improvement is underwhelming, I would argue it's probably best to remove it unconditionally to reduce complexity and the probably that we find another confusing corner case in the future.

**Comment by neutrinoceros** [comment] 2024-10-17 07:16
In fact, it seems relatively straightforward to remove so I'll just do it as an experiment.

**Comment by astrofrog** [comment] 2024-10-17 10:23
Regarding the timings, calling ``np.nanmedian`` was never much slower than ``bn.nanmedian`` when called just with an array, the biggest difference (and this is used in ``stats``) is when using the ``axis`` keyword argument:

```python
In [1]: import numpy as np

In [2]: import bottleneck as bn

In [3]: array = np.random.random((256, 256, 256))

In [4]: array[array < 0.1] = np.nan

In [5]: %timeit np.nanmedian(array, axis=1)
792 ms ± 13.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [6]: %timeit bn.nanmedian(array, axis=1)
155 ms ± 1.66 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

```

**Comment by larrybradley** [comment] 2024-10-17 15:46
@astrofrog In that case, it seems like a good idea to continue using bottleneck for `float` input.

I took a quick look at the code and unfortunately it doesn't appear that removing bottleneck only for `float32` will be simple.  The functions are pre-defined before accessing any data arrays.

**Comment by neutrinoceros** [comment] 2024-10-18 08:00
Indeed this would involve a bit more design but I *think* we can still retro-fit this by changing functions in astropy/stats/nanfunctions.py to be thin wrappers around both numpy and bottleneck, that would dispatch on the input array's dtype, without breaking any API. I'll give this a try now.

**Closed** 2024-10-18 20:52 UTC
Labels: Upstream Fix Required, Bug, stats, Duplicate
