### ISSUE TITLE
3.2rc1 ASDF test_backwards_compat failed

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8683] opened 2019-05-09 18:48 UTC
```
============================= test session starts =============================
platform win32 -- Python 3.7.1, pytest-4.1.0, py-1.7.0, pluggy-0.8.0

Running tests with Astropy version 3.2rc1.
Running tests in Miniconda3\envs\py37\lib\site-packages\astropy.

Date: 2019-05-09T14:24:44

Platform: Windows-10-10.0.17763-SP0

Executable: C:\...\Miniconda3\envs\py37\python.exe

Full Python Version: 
3.7.1 (default, Oct 28 2018, 08:39:03) [MSC v.1912 64 bit (AMD64)]

encodings: sys: utf-8, locale: cp1252, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.16.2
Scipy: 1.1.0
Matplotlib: 3.0.3
h5py: 2.8.0
Pandas: 0.23.4
Asdf: 2.3.3
Cython: 0.29
Scikit-image: not available
astropy_helpers: 3.2rc1
Using Astropy options: remote_data: any.

Matplotlib: 3.0.3
Freetype: 2.9.1
rootdir: C:\..., inifile:
plugins: xdist-1.24.0, remotedata-0.3.1, openfiles-0.3.0, mpl-0.10, forked-0.2, doctestplus-0.1.3, arraydiff-0.2
collected 12639 items
```

```
____________________________ test_backwards_compat ____________________________

    def test_backwards_compat():
        """
        Make sure that we can continue to read FITS HDUs that use the schema from
        the ASDF Standard.
    
        This test uses the examples in the fits schema from the ASDF Standard,
        since these make no reference to Astropy's own fits definition.
        """
    
        def check(asdffile):
            assert isinstance(asdffile['example'], fits.HDUList)
    
>       run_schema_example_test('stsci.edu', 'asdf', 'fits/fits', '1.0.0', check)

..\Miniconda3\envs\py37\lib\site-packages\astropy\io\misc\asdf\tags\fits\tests\test_fits.py:55: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

organization = 'stsci.edu', standard = 'asdf', name = 'fits/fits'
version = '1.0.0'
check_func = <function test_backwards_compat.<locals>.check at 0x000002316C136730>

    def run_schema_example_test(organization, standard, name, version, check_func=None):
    
        import asdf
        from asdf.tests import helpers
        from asdf.types import format_tag
        from asdf.resolver import default_resolver
    
        tag = format_tag(organization, standard, version, name)
        schema_path = urllib.parse.urlparse(default_resolver(tag)).path
    
>       with open(schema_path, 'rb') as ff:
E       OSError: [Errno 22] Invalid argument: '/C:/Users/PL/Miniconda3/envs/py37/lib/site-packages/asdf/schemas/stsci.edu/asdf/fits/fits-1.0.0.yaml'

..\Miniconda3\envs\py37\lib\site-packages\astropy\io\misc\asdf\tags\tests\helpers.py:21: OSError
____________________________ test_backwards_compat ____________________________

    def test_backwards_compat():
        """
        Make sure that we can continue to read tables that use the schema from
        the ASDF Standard.
    
        This test uses the examples in the table schema from the ASDF Standard,
        since these make no reference to Astropy's own table definition.
        """
    
        def check(asdffile):
            assert isinstance(asdffile['example'], table.Table)
    
>       run_schema_example_test('stsci.edu', 'asdf', 'core/table', '1.0.0', check)

..\Miniconda3\envs\py37\lib\site-packages\astropy\io\misc\asdf\tags\table\tests\test_table.py:244: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

organization = 'stsci.edu', standard = 'asdf', name = 'core/table'
version = '1.0.0'
check_func = <function test_backwards_compat.<locals>.check at 0x000002316C157D90>

    def run_schema_example_test(organization, standard, name, version, check_func=None):
    
        import asdf
        from asdf.tests import helpers
        from asdf.types import format_tag
        from asdf.resolver import default_resolver
    
        tag = format_tag(organization, standard, version, name)
        schema_path = urllib.parse.urlparse(default_resolver(tag)).path
    
>       with open(schema_path, 'rb') as ff:
E       OSError: [Errno 22] Invalid argument: '/C:/Users/PL/Miniconda3/envs/py37/lib/site-packages/asdf/schemas/stsci.edu/asdf/core/table-1.0.0.yaml'

..\Miniconda3\envs\py37\lib\site-packages\astropy\io\misc\asdf\tags\tests\helpers.py:21: OSError
```

**Comment by pllim** [comment] 2019-05-09 19:15
I tried using a dev version of `asdf` but can't even get the tests to start:

```
ImportError: Error importing plugin "asdf.tests.schema_tester": No module named 'asdf.tests.schema_tester'
```

**Comment by jdavies-st** [comment] 2019-05-09 19:35
To run the tests, you need to do an install in order to have the schema tester available via `entry_points` I believe.

**Comment by pllim** [comment] 2019-05-09 20:10
@jdavies-st , I am following the instructions from the https://github.com/astropy/astropy/wiki/v3.2-RC-testing

```
pip install astropy==3.2rc1
python -c "import astropy; astropy.test(remote_data=True)"
```

**Comment by jdavies-st** [comment] 2019-05-09 20:19
I was referring to the `asdf` tests.  But thanks for the info.  I will run both the `astropy` and `asdf` tests.

**Comment by bsipocz** [comment] 2019-05-09 20:27
Oh, good point both. I didn't update the instructions in the wiki. But even then I don't see `asdf` listed in `tests` but only in `all` in `setup.cfg`

**Comment by nden** [comment] 2019-05-10 13:08
I think the problem is in `asdf.uitl.filepath_to_url`. If that's the case asdf tests should fail on Windows too. I'm not sure when we stopped testing asdf on Win but we should start that job. Since `filepath_to_url` is only used in testing I suggest astropy xfails those tests on Win until this is fixed in asdf.

**Comment by jdavies-st** [comment] 2019-05-10 15:12
Asdf is testing on Windows.  If you look at the Travis CI results, the last couple tests in the `tox` env do it on Windows.  But clearly this test case is not covered.  I tried covering it here

https://github.com/spacetelescope/asdf/pull/680

but that seems to not have covered the same case.  Hmm.

**Closed** 2019-05-10 22:24 UTC
Labels: Release, Upstream Fix Required, Windows, io.misc.asdf, testing
