### ISSUE TITLE
FITS Table columns read as 2D arrays

### ISSUE THREAD

**Issue by damonge** [astropy/astropy#12064] opened 2021-08-16 18:10 UTC
### Description

The following code:
```
from astropy.io import fits
from astropy.table import Table

with fits.open('whatever.fits') as f:
    d = Table.read(f)
print(d['SUPRA'].shape)
```
outputs `(1294, 1)` in v4.2.1 and `(1294,)` in v3.1.2.

This makes quite a bit of our previous code non-backwards compatible.

### Expected behavior

I expected `(1294,)` as in previous versions.

### Actual behavior

Output is `(1294, 1)` with v4.2.1.

### Steps to Reproduce

See code above.

### System Details

```
Linux-5.11.0-25-generic-x86_64-with-glibc2.29
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0]
Numpy 1.20.2
astropy 4.2.1
Scipy 1.6.2
Matplotlib 3.4.1
```

**Comment by damonge** [comment] 2021-08-16 18:12
I should add, the format of the `'SUPRA'` column mentioned above is `'1D'`.

**Comment by pllim** [comment] 2021-08-16 18:30
Are you able to provide "whatever.fits" or the code to generate it?

**Comment by damonge** [comment] 2021-08-16 18:47
Thanks for your quick response.
A file that reproduces the same behaviour with a smaller number of rows (10) can be found [here](http://ssa.roe.ac.uk/tmp/tmp_radial/results16_19_41_51_5.fits.gz)

**Comment by pllim** [comment] 2021-08-17 14:10
Thanks! The release is too old. I failed to bisect it. You are free to try though.

Here is the header info for that column:

```
TFORM12 = '1D      '
TUCD12  = 'unknown '
TCOMM12 = 'unknown '
TDIM12  = '(1)     '
TTYPE12 = 'SUPRA   '
```

I suspect maybe #10768 . Maybe @maxnoe , @dhomeier , or @saimn remember.

**Comment by damonge** [comment] 2021-08-17 14:38
Thanks @pllim . FWIW, I verified that the behaviour is the same with the latest stable version on pip. It'd be great if there was a way to force table columns with one element per row to be read as 1-dimensional arrays (even if the TFORM was e.g. "1D").

**Comment by dhomeier** [comment] 2021-08-17 15:10
Yes, I'd say this had been changed in #10768, and the previous behaviour was not following the standard and also not round-tripping. One could certainly add an option to `fits.open` or `Table.read` to revert the change in
https://github.com/astropy/astropy/blob/2460e58e225e3bb1682726e720e72b57dba636c9/astropy/io/fits/column.py#L1442

if running `d['SUPRA'] = d['SUPRA'].squeeze()` is not an alternative, but that's perhaps a question of feature-bloat.

**Comment by damonge** [comment] 2021-08-17 16:13
Thanks @dhomeier 
Yes, that's how I've currently patched things up. It's a bit annoying, since it adds quite a bit of extra code to our pipeline (this is not the only column suffering from this issue), so I wanted to check if there is a way to revert to the old behaviour from the Table read method. This FITS file came straight from an SQL query, so I don't think this is an odd example of a file generated with `1D`-type format!

**Comment by maxnoe** [comment] 2021-08-17 16:24
The Problem is not TFORM, but TDIM.

An empty TDIM is a 0D element, so the whole column is 1D. A TDIM of `(1)` means that each element is a 1d array of 1 element, so the while column becomes 2D.

Please fix the code producing your files if having 2d columns is not the intention. The FITS standard is pretty clear on this:

> TDIMn keywords. Thevalue field of this indexedkeywordshall contain a character string describing how to interpret the contents of Field n as a multi-dimensional array with a format of ’(l,m,n...)’, where l, m, n, ...are the dimensions of the array. The data are ordered such that the array index of the first dimension given (l) is the most rapidly varying, and that of the last dimension given is the least rapidly varying. The total number of elements in the array equals the product of the dimensions specified in the TDIMn keyword

**Comment by maxnoe** [comment] 2021-08-17 16:26
So the behavior of astropy here is correct and following the standard.

**Comment by damonge** [comment] 2021-08-17 16:34
Thanks @maxnoe 
The FITS file was generated by the SuperCOSMOS Science Archive SQL query system (you can reproduce this file by running `SELECT TOP 10 * FROM TWOMPZ..twompzPhotoz` [here](http://ssa.roe.ac.uk//sql.html)). So it may well be the case that the code generating these FITS files needs fixing, but this leads me to think that the issue must be more systemic.
I'll raise this with those maintaining the database though.

**Comment by maxnoe** [comment] 2021-08-17 16:39
Maybe they want that column to be interpreted that way? I mean the file is completely valid, it's the choice of the producing system to add or not add the `TDIM` header and someone took the decision to add it in this case.

**Comment by dhomeier** [comment] 2021-08-17 16:53
Looks more like a design oversight, since the `TDIM` keyword has been added to every column, although it's only `!=1` for two of them.

**Comment by pllim** [comment] 2021-08-17 17:19
So, is it correct to summarize that there is nothing needs fixing here in `astropy`? If so, can we close this issue? Thanks, everyone!

**Comment by saimn** [comment] 2021-08-18 17:09
Given the explanations above (thanks @maxnoe) about TDIM, I agree there is nothing to fix on Astropy side. Adding an option for this case doesn't seem appropriate, `io.fits`'s API is already complicated enough, and removing the extra dimension is easy enough to do in the downstream code.

**Closed by saimn** 2021-08-18 17:09 UTC
Labels: io.fits, question, Downstream Fix Required
