### ISSUE TITLE
hdf5 table with BoolCol cannot be read with h5py (ok with pytables)

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy#6473] opened 2017-08-23 15:03 UTC
I encountered an hdf5 table (incidentally, I received this table from @taldcroft in one of the rare non-astropy related conversation we have) which cannot be read with the Table interface, but "by hand" with pytables.
I don't really understand the difference (I know little about hdf5), but it seems to me that it might be useful to add a pytables interface to the io framework for cases like this.
(Unfortunately, I don't know if I'm allowed to share the table and I don't know enough about hdf5 to make a new minimal example to reproduce the problem.)
```
In [1]: from astropy.table import Table

In [2]: t = Table.read('guide_stats.h5')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-a67c7fbabf30> in <module>()
----> 1 t = Table.read('guide_stats.h5')

/nfs/melkor/d1/guenther/soft/anaconda/lib/python2.7/site-packages/astropy/table/table.pyc in read(cls, *args, **kwargs)
   2428         passed through to the underlying data reader (e.g. `~astropy.io.ascii.read`).
   2429         """
-> 2430         return io_registry.read(cls, *args, **kwargs)
   2431 
   2432     def write(self, *args, **kwargs):

/nfs/melkor/d1/guenther/soft/anaconda/lib/python2.7/site-packages/astropy/io/registry.pyc in read(cls, *args, **kwargs)
    466 
    467         reader = get_reader(format, cls)
--> 468         data = reader(*args, **kwargs)
    469 
    470         if not isinstance(data, cls):

/nfs/melkor/d1/guenther/soft/anaconda/lib/python2.7/site-packages/astropy/io/misc/hdf5.pyc in read_table_hdf5(input, path)
    129 
    130         try:
--> 131             return read_table_hdf5(f, path=path)
    132         finally:
    133             f.close()

/nfs/melkor/d1/guenther/soft/anaconda/lib/python2.7/site-packages/astropy/io/misc/hdf5.pyc in read_table_hdf5(input, path)
     99 
    100             # Find all structured arrays in group
--> 101             arrays = _find_all_structured_arrays(input)
    102 
    103             if len(arrays) == 0:

/nfs/melkor/d1/guenther/soft/anaconda/lib/python2.7/site-packages/astropy/io/misc/hdf5.pyc in _find_all_structured_arrays(handle)
     33         if isinstance(obj, h5py.Dataset) and obj.dtype.kind == 'V':
     34             structured_arrays.append(name)
---> 35     handle.visititems(append_structured_arrays)
     36     return structured_arrays
     37 

/nfs/melkor/d1/guenther/soft/anaconda/lib/python2.7/site-packages/h5py/_hl/group.pyc in visititems(self, func)
    462                 name = self._d(name)
    463                 return func(name, self[name])
--> 464             return h5o.visit(self.id, proxy)
    465 
    466     @with_phil

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2696)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2654)()

h5py/h5o.pyx in h5py.h5o.visit (/home/ilan/minonda/conda-bld/work/h5py/h5o.c:4994)()

h5py/defs.pyx in h5py.defs.H5Ovisit_by_name (/home/ilan/minonda/conda-bld/work/h5py/defs.c:15698)()

h5py/h5o.pyx in h5py.h5o.cb_obj_simple (/home/ilan/minonda/conda-bld/work/h5py/h5o.c:4710)()

/nfs/melkor/d1/guenther/soft/anaconda/lib/python2.7/site-packages/h5py/_hl/group.pyc in proxy(name)
    461                 """ Use the text name of the object, not bytes """
    462                 name = self._d(name)
--> 463                 return func(name, self[name])
    464             return h5o.visit(self.id, proxy)
    465 

/nfs/melkor/d1/guenther/soft/anaconda/lib/python2.7/site-packages/astropy/io/misc/hdf5.pyc in append_structured_arrays(name, obj)
     31 
     32     def append_structured_arrays(name, obj):
---> 33         if isinstance(obj, h5py.Dataset) and obj.dtype.kind == 'V':
     34             structured_arrays.append(name)
     35     handle.visititems(append_structured_arrays)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2696)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2654)()

/nfs/melkor/d1/guenther/soft/anaconda/lib/python2.7/site-packages/h5py/_hl/dataset.pyc in dtype(self)
    228     def dtype(self):
    229         """Numpy dtype representing the datatype"""
--> 230         return self.id.dtype
    231 
    232     @property

h5py/h5d.pyx in h5py.h5d.DatasetID.dtype.__get__ (/home/ilan/minonda/conda-bld/work/h5py/h5d.c:2350)()

h5py/h5d.pyx in h5py.h5d.DatasetID.dtype.__get__ (/home/ilan/minonda/conda-bld/work/h5py/h5d.c:2284)()

h5py/h5t.pyx in h5py.h5t.TypeID.dtype.__get__ (/home/ilan/minonda/conda-bld/work/h5py/h5t.c:4799)()

h5py/h5t.pyx in h5py.h5t.TypeID.dtype.__get__ (/home/ilan/minonda/conda-bld/work/h5py/h5t.c:4756)()

h5py/h5t.pyx in h5py.h5t.TypeCompoundID.py_dtype (/home/ilan/minonda/conda-bld/work/h5py/h5t.c:10772)()

h5py/h5t.pyx in h5py.h5t.TypeID.py_dtype (/home/ilan/minonda/conda-bld/work/h5py/h5t.c:4926)()

TypeError: No NumPy equivalent for TypeBitfieldID exists
```

However, I can read it like this:
```
from astropy.table import Table
import tables
filehdf5 = tables.open_file('guide_stats.h5')
tab = Table(filehdf5.root.data.read())
```
It looks to me as if tables converts the Bytefield just to a number, which I think is much better than not reading the entire table at all.

**Comment by bsipocz** [comment] 2019-03-19 00:12
@hamogu - without the file in question it's impossible to test whether this is still an issue. Could you please upload an example file somewhere?

**Comment by taldcroft** [comment] 2019-03-19 00:37
@bsipocz - here is a minimal example to reproduce:
```
In [6]: t = Table([[True, False]])

In [7]: t
Out[7]: 
<Table length=2>
 col0
 bool
-----
 True
False

In [8]: td = t.as_array()

In [9]: td
Out[9]: 
array([( True,), (False,)], 
      dtype=[('col0', '?')])

In [10]: import tables

In [11]: h5 = tables.open_file('junk.h5', 'w')

In [12]: h5.create_table(h5.root, 'data', td)
Out[12]: 
/data (Table(2,)) ''
  description := {
  "col0": BoolCol(shape=(), dflt=False, pos=0)}
  byteorder := 'irrelevant'
  chunkshape := (65536,)

In [13]: h5.close()

In [14]: Table.read('junk.h5', format='hdf5')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-7cf772ad4a6a> in <module>()
----> 1 Table.read('junk.h5', format='hdf5')
...
TypeError: No NumPy equivalent for TypeBitfieldID exists
```

**Comment by bsipocz** [comment] 2019-03-19 00:39
Thanks. Well, it's then not one of those self resolving ones 😄

**Comment by taldcroft** [comment] 2019-03-19 00:43
Upstream https://github.com/h5py/h5py/issues/641

**Comment by taldcroft** [comment] 2019-03-19 00:44
Of course we *could* still add in the PyTables backend.

**Comment by pllim** [comment] 2023-01-25 18:35
Not clear to me which package `import tables` came from. Since the linked issues are closed upstream, I am also closing this. Feel free to re-open if I am wrong. Thanks!

**Closed by pllim** 2023-01-25 18:35 UTC
Labels: Upstream Fix Required, table, Bug
