### ISSUE TITLE
Comparing a FITS file with one in a subdirectory

### ISSUE THREAD

**Issue by philhodge** [astropy/astropy#6760] opened 2017-10-17 18:50 UTC
I knew that when running fitsdiff to compare a file in the default directory with one of the same name in a subdirectory that it was necessary to explicitly give the name of the file in the subdirectory, but today I typed the following by mistake:

    fitsdiff dms_230_491_refpix.fits today_prev/

and fitsdiff reported "No differences found."  However, I knew that the files did differ, so I ran fitsdiff again:

    fitsdiff dms_230_491_refpix.fits today_prev/dms_230_491_refpix.fits

and fitsdiff showed several differences.

It's probably relevant that there was only one file in `today_prev/`.

**Comment by drdavella** [comment] 2017-10-17 18:56
It sounds like `fitsdiff` should make sure that all of the file arguments are real files (i.e. not directories).

**Comment by pllim** [comment] 2017-10-17 19:07
Or it can try to be smart and run `fitsdiff` with all the FITS found in the given sub-directory... (No, don't do it.)

**Comment by philhodge** [comment] 2017-10-17 19:17
Unix diff works fine to compare a file with one of the same name in a subdirectory, and the original fitsdiff did as well.

**Comment by pllim** [comment] 2017-10-17 19:20
> compare a file with one of the same name in a subdirectory

Ah, that sounds more reasonable than just blinding matching all FITS.

**Comment by saimn** [comment] 2017-11-06 20:55
>>  compare a file with one of the same name in a subdirectory
>
> Ah, that sounds more reasonable than just blinding matching all FITS.

Yes, that's what I understand from the usage documentation: https://github.com/astropy/astropy/blob/master/astropy/io/fits/scripts/fitsdiff.py#L18

> If both are directory names, all files in each of
the directories will be included; if only one is a directory name, then the
directory name will be prefixed to the file name(s) specified by the other
argument.

But there is clearly something broken here:
```
$ fitsdiff astropy/io/fits/tests/data/arange.fits astropy/io/fits/tests/data/

...

OSError: error opening file b (/home/simon/dev/astropy/arange.fits): FileNotFoundError: 2
```

Looks like the second directory name is not joined with the file names.

**Comment by sushobhana** [comment] 2018-01-14 05:23
Hi @saimn !!
i want to work on this ..
if only one is a directory name ..we need to check the file names are same..right??
we can use `os.path.splits` to get the file name(last name of the path) and check it..is it enough??

**Comment by saimn** [comment] 2018-01-15 21:16
@sushobhana - Yes, the fix should be simple enough (and the issue is quite well described above, ask if you need more specific precision). It will also need unit tests, you may want to read the [developer documentation](http://docs.astropy.org/en/latest/index.html#developer-documentation) to get a better understanding of the process.
The is also an attempt in #6993 but it seems to be stalled.

**Closed** 2018-02-07 14:04 UTC
Labels: Affects-release, Bug, Effort-low, Package-novice, io.fits
