### ISSUE TITLE
Searching for Astropy Documentation returns forks

### ISSUE THREAD

**Issue by nabobalis** [astropy/astropy#17007] opened 2024-09-13 17:26 UTC
### Description

I was using Google to try and search for astropy documentation.

I get results from:

![Screenshot_20240912_104533](https://github.com/user-attachments/assets/536173de-a964-4857-933a-c687e480555a)

These are forks of astropy with very old versions

Or this one:

![Screenshot_20240913_102545](https://github.com/user-attachments/assets/903ad8db-f9a1-4404-b1e3-82970e55618c)

### Expected behavior

Linked to the main astropy documentation for the lastest or stable release.

### How to Reproduce

Google, astropy documentation 

### Fixing it?

Deleting these fork RTD projects might be a start?
The other issue is to improve SEO on the main documentation and that's outside of my wheelhouse. 

Not sure if adding https://sphinxext-opengraph.readthedocs.io/en/latest/ (if not there already) would help.

RTD have pages on SEO: https://blog.readthedocs.com/seo-for-technical-docs/ and https://docs.readthedocs.io/en/stable/guides/technical-docs-seo-guide.html

**Comment by pllim** [comment] 2024-09-16 21:01
We do have a https://github.com/astropy/astropy/blob/main/docs/robots.txt but maybe it is incomplete?

**Comment by pllim** [comment] 2024-09-17 11:22
Not sure if `robots.txt` helps with really old stuff from forks. As for https://docs.readthedocs.io/en/stable/canonical-urls.html , we already have Domains set for `astropy.org` and say that is canonical, so not sure if setting `READTHEDOCS_CANONICAL_URL` would help either. Ideas welcome.

**Comment by pllim** [comment] 2024-09-17 11:29
Another option is to submit manual requests to search engine but I cannot make sense of the form.

**Comment by astrofrog** [comment] 2024-09-17 11:46
We can also ask the users responsible for the forks if they can delete the project, as they likely don't realise it is causing this.

**Comment by pllim** [comment] 2024-09-17 14:18
One has to explicitly set up fork to build their own doc on RTD. It is not something that just happened by accident. I wonder why they exist... 🤔 

As for `eteq.github.io`, let's ask @eteq .

**Comment by pllim** [comment] 2024-09-17 14:20
RTD from forks I see in the screenshot:

* `astropy-cjhang` -- @cjhang 
* `kbarbary-astropy` -- @kbarbary 
* `astropy-astrofrog` -- @astrofrog (ehem...)

**Comment by nabobalis** [comment] 2024-09-17 14:30
> One has to explicitly set up fork to build their own doc on RTD. It is not something that just happened by accident. I wonder why they exist... 🤔

I would suspect that this is from the early days of pre RTD building PRs and having a robust docs CI.
I used to have my own RTD version of sunpy many years ago due to this.

**Comment by ayshih** [comment] 2024-09-17 14:41
Another RTD one that comes up frequently is:
* `keflavich-astropy` -- @keflavich

**Comment by keflavich** [comment] 2024-09-17 14:55
yeah..... help me disable that build please.  I thought it was a good idea to have around for the same reason @nabobalis said, but I don't like it showing up in google searches!

**Comment by pllim** [comment] 2024-09-17 15:00
1. Go to `https://readthedocs.org/dashboard/<your_project_name_here>/edit/`
2. Scroll all the way down.
3. Click `Delete project`.

**Comment by pllim** [comment] 2024-09-17 15:01
Or if you want something less drastic, you can try deactivate everything under `https://readthedocs.org/projects/<your_project_name_here>/versions/` instead. But then if you ever activate anything there again, we will have the same problem.

**Comment by cjhang** [comment] 2024-09-20 13:14
I have also remove astropy-cjhang

**Comment by pllim** [comment] 2024-09-20 14:32
Hmm. There is no `astropy` folder in https://github.com/eteq/eteq.github.io so I don't know where https://eteq.github.io/astropy is even coming from.

**Comment by astrofrog** [comment] 2024-09-20 15:00
It's probably in the go-pages branch of @eteq 's fork if I had to guess? (Can't check as am on phone)

**Comment by pllim** [comment] 2024-09-20 15:37
That site only has `main`, no `gh-pages`.

**Comment by lgarrison** [comment] 2024-09-23 15:32
I just ran into this. I think the problem might be this line in the HTML of `docs.astropy.org` (it showed up on all the documentation pages I spot-checked):

```html
<meta name="robots" content="noindex, nofollow">
```

According to Google, this is the canonical way to drop a page from search results (https://developers.google.com/search/docs/crawling-indexing/block-indexing).

It appears to be coming from here: https://github.com/astropy/astropy/blob/766c3c53899833652730f90c2b705cb420f371b0/docs/_templates/layout.html#L21-L23

I see some comments indicating that `version_slug` ought to be populated by RTD, and `to_be_indexed` seems to be populated here:
https://github.com/astropy/astropy/blob/766c3c53899833652730f90c2b705cb420f371b0/docs/conf.py#L266

But maybe one of the two isn't getting propagated to the template?

**Comment by pllim** [comment] 2024-09-23 15:40
Hmm `layout.html` was added in https://github.com/astropy/astropy/pull/7909 (where `robots.txt` was deleted). But then the same author added back `robots.txt` in https://github.com/astropy/astropy/pull/8383 . These PRs pre-dated our switch to `pydata-sphinx-theme` though theoretically the theme shouldn't affect such things?

**Comment by pllim** [comment] 2024-09-23 15:49
Indeed, `<meta name="robots" content="noindex, nofollow">` shows up in https://docs.astropy.org/en/stable/ and https://docs.astropy.org/en/latest/ which is bad. Is the syntax of `{% if not version_slug in to_be_indexed  %}` actually correct?

If you look at the raw build log from the last `latest` doc build (e.g., https://readthedocs.org/api/v2/build/25712560.txt), `"to_be_indexed": ["stable", "latest"]` is passed into the build. However, `html_context` is only mentioned one other time in the log to render `files_to_render = ["index_dev", "install"]` only. Is it auto-magically used somewhere else, or are we missing something here?

How do we debug this?

**Comment by lgarrison** [comment] 2024-09-23 15:59
I *think* that's valid Jinja syntax, and the Sphinx docs suggest `html_context` is a known variable: https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_context

This could be a red herring, but there was a RTD change 1 month ago that could be related: https://github.com/readthedocs/readthedocs.org/pull/11085

Anybody know the difference between a RTD slug and a version name?

One way to debug this would be to build the docs and print the Jinja vars (or just render them to HTML, not sure which is easier...).

**Comment by humitos** [comment] 2024-09-23 16:14
Hi 👋🏼 -- The difference between a "Version slug" and a "Version verbose name" is that the slug is the slugified version of the name. Example: if the version name is `release/3.4.1` the slug will be `release-3.4.1`. Note that it replaces `/` by `-`. We do this because the slug is used in URLs which does not support a bunch of characters. The "Version verbose name" is usually exposed to users.

**Comment by astrofrog** [comment] 2024-09-23 16:20
> How do we debug this?

Maybe we can try a build injecting both variables in the if statement into the actual content of the page to see what they are set to?

**Comment by humitos** [comment] 2024-09-23 16:33
> How do we debug this?

You can use a Sphinx extension that allows you to write Jinja code in a `.rst` file. I've used this in the past to show all the variables included in the context: 

- Live example: https://test-builds.readthedocs.io/en/full-feature/sphinx-context.html
- Source code: https://github.com/readthedocs/test-builds/blob/full-feature/docs/sphinx-context.rst
- Sphinx extension: https://sphinx-jinja2.readthedocs.io/en/latest/

I hope that helps.

**Comment by kbarbary** [comment] 2024-09-23 18:48
I don't seem to have admin permission to delete the `kbarbary-astropy` RTD project. The maintainer is `astropy`. If someone with access to that RTD account could delete it, that would be great.

![image](https://github.com/user-attachments/assets/42a8dd17-d34d-45e8-b48e-e9b4cc54ed4d)

**Comment by pllim** [comment] 2024-09-23 19:36
@kbarbary , didn't know astropy owns it (weird!). Deleted. Thanks for letting us know!

**Comment by pllim** [comment] 2024-09-24 16:17
Trying to print out the vars in a PR seems not very useful. But if I experiment directly on `main`, I fear that is going to pollute the commit history.

https://github.com/astropy/astropy/pull/17066

**Comment by pllim** [comment] 2024-09-24 16:17
Maybe we should just disable that meta stuff for now on `main`.

**Comment by astrofrog** [comment] 2024-09-24 22:20
It looks like the context RTD injects is now organized into a dictionary:

https://dev.readthedocs.io/en/latest/design/theme-context.html#context-injected

so perhaps ``version_slug`` on its own doesn't work anymore. I am currently testing things out in a test project:

https://rtd-slug-debug.readthedocs.io/en/latest/

and noticed that ``version_slug`` is not defined even on e.g. ``latest``. More soon...

**Comment by pllim** [comment] 2024-09-24 22:46
So, like `readthedocs.v1.version.slug`? (Though aren't we using v2?)

**Comment by astrofrog** [comment] 2024-09-24 22:52
Hmm wait that document I linked to is a design document and it says not implemented yet at the top. But I think they have also deprecated a lot of the injected variables, there is some discussion here: https://github.com/readthedocs/addons/issues/72. I think in short it may not actually be possible to do what we used to do and therefore maybe for now #17068 makes the most sense.

**Comment by pllim** [comment] 2024-09-24 22:53
Unless we inject our own slug thingy into `html_context` but that also feels hacky.

**Comment by astrofrog** [comment] 2024-09-24 22:53
Ah wait I may have a solution...

**Comment by astrofrog** [comment] 2024-09-24 22:58
See https://github.com/astropy/astropy/pull/17071

**Comment by pllim** [comment] 2024-09-25 00:37
I can confirm that `<meta name="robots" content="noindex, nofollow">` no longer appears in https://docs.astropy.org/en/latest/ but not sure when that will propagate to search bots.

**Comment by humitos** [comment] 2024-09-25 09:23
> It looks like the context RTD injects is now organized into a dictionary:

No. That is an old design document and it's not implemented. There a warning note at the top saying: "This design document details future features that are not yet implemented."

**Comment by eteq** [comment] 2024-09-30 18:59
I just did several searches for various astropy things that I think a user might want, and they are now showing docs.astropy.org again instead of the forks.

(for good measure I renamed my `gh-pages` branch in eteq/astropy as well, although I think #17071 is probably what did it not that since I wasn't seeing my own branches when I checked this last week)

**Comment by eteq** [comment] 2024-09-30 19:10
In slack, @astrofrog, @Cadair, and @pllim all reported things seem to be back and working.  I got two other confirmations from random users, so I think we can declare this fixed.  So I'll go ahead and close this, but open up a separate one for @humitos 's comment above (since that's a different but soon pending issue maybe...)

**Closed by eteq** 2024-09-30 19:10 UTC
Labels: Docs, Bug
