### ISSUE TITLE
astropy.io.fits does not handle CONTINUE keywords in FITS headers correctly

### ISSUE THREAD

**Issue by cbethge** [astropy/astropy#11298] opened 2021-02-04 19:45 UTC
### Description

The FITS standard allows header keyword values to be longer than 67 characters by using the CONTINUE convention, see this [link](https://fits.gsfc.nasa.gov/registry/continue/continue.pdf). The astropy.io.fits module seems to apply some formatting when doing this for better readability, but under some circumstances does not write the correct content to the fits header and omits information.

### Expected behavior

If a keyword value is longer than 67 characters, it should get split in 67 character chunks with an ampersand at the end as the 68th character, and then the value should be continued in the next line with the CONTINUE keyword:

```
In [1]: from astropy.io import fits
   ...: hdu = fits.PrimaryHDU()
   ...: keyword = "WHATEVER"
   ...: value = "SuperCalibrationParameters_XXXX_YYYY_ZZZZZ_KK_01_02_03)-AAABBBCCC.n.h5 SuperNavigationParameters_XXXX_YYYY_ZZZZZ_KK_01_02_03)-AAABBBCCC.n.xml"
   ...: hdu.header.append((keyword, value, ' '))
   ...: hdu.header
Out[1]:
SIMPLE  =                    T / conforms to FITS standard
BITPIX  =                    8 / array data type
NAXIS   =                    0 / number of array dimensions
EXTEND  =                    T
WHATEVER= 'SuperCalibrationParameters_XXXX_YYYY_ZZZZZ_KK_01_02_03)-AAABBBCCC.n&'
CONTINUE  '.h5 SuperNavigationParameters_XXXX_YYYY_ZZZZZ_KK_01_02_03)-AAABBBCC&'
CONTINUE  'C.n.xml'
```

### Actual behavior

The keyword value seems to get reformatted for the FITS header after a blank in the value, and in the last CONTINUE entry, information from the keyword value gets omitted (the "xml" at the end is missing):

```
In [1]: from astropy.io import fits
   ...: hdu = fits.PrimaryHDU()
   ...: keyword = "WHATEVER"
   ...: value = "SuperCalibrationParameters_XXXX_YYYY_ZZZZZ_KK_01_02_03)-AAABBBCCC.n.h5 SuperNavigationParameters_XXXX_YYYY_ZZZZZ_KK_01_02_03)-AAABBBCCC.n.xml"
   ...: hdu.header.append((keyword, value, ' '))
   ...: hdu.header
Out[1]:
SIMPLE  =                    T / conforms to FITS standard
BITPIX  =                    8 / array data type
NAXIS   =                    0 / number of array dimensions
EXTEND  =                    T
WHATEVER= 'SuperCalibrationParameters_XXXX_YYYY_ZZZZZ_KK_01_02_03)-AAABBBCCC.n&'
CONTINUE  '.h5 &'
CONTINUE  'SuperNavigationParameters_XXXX_YYYY_ZZZZZ_KK_01_02_03)-AAABBBCCC.n.'
```

### Steps to Reproduce

See above.

### System Details

Darwin-20.3.0-x86_64-i386-64bit
Python 3.7.9 (default, Aug 31 2020, 07:22:35) 
[Clang 10.0.0 ]
Numpy 1.19.2
astropy 4.0.2
Scipy 1.4.1
Matplotlib 3.3.2

**Comment by saimn** [comment] 2021-02-04 20:10
Your string reveals some issues with the `_word_group` function which is supposed to split strings without cutting words (cc @embray) :
``` 
In [9]: from astropy.io.fits.util import _words_group

In [10]: _words_group("SuperCalibrationParameters_XXXX_YYYY_ZZZZZ_KK_01_02_03)-AAABBBCCC.n.h5 Su
    ...: perNavigationParameters_XXXX_YYYY_ZZZZZ_KK_01_02_03)-AAABBBCCC.n.xml", 67)
Out[10]: 
['SuperCalibrationParameters_XXXX_YYYY_ZZZZZ_KK_01_02_03)-AAABBBCCC.n',
 '.h5 ',
 'SuperNavigationParameters_XXXX_YYYY_ZZZZZ_KK_01_02_03)-AAABBBCCC.n.']
```
https://github.com/astropy/astropy/blob/783be4f00819ac959dfb899e05b46e3ec72431c8/astropy/io/fits/util.py#L760-L796

**Comment by embray** [comment] 2021-02-07 15:50
Confirmed.  That code hasn't been updated in a long time that I can recall, so I'm amazed in the last 10+ years no one has noticed this problem.  I can't say I know yet what's causing it but I'll take a look.

**Comment by embray** [comment] 2021-02-07 15:56
IIUC any fix for this should target v4.3.0 but separate PRs made to backport it (this can be backported to 4.2.x and 4.0.x).

**Comment by dhomeier** [comment] 2021-02-07 21:01
I find it surprising to begin with that this is handled by a prettifier like that. @cbethge is right that it may well improve readability, but I don't see how that has a place in the strings written to the FITS header – I'd expect it to be simply split in 67-char substrings, to be recombined exactly in that form when the header is read.

**Comment by pllim** [comment] 2021-02-08 15:03
> I'm amazed in the last 10+ years no one has noticed this problem

I have only put very long text in COMMENT or HISTORY, both of which are "special," myself. 💭

**Comment by saimn** [comment] 2021-02-08 15:09
I agree with @dhomeier, I don't see the current behavior as a really useful feature.

**Comment by cbethge** [comment] 2021-02-08 16:01
Thanks for addressing this so quickly. I also agree with @dhomeier and @saimn that a prettifier is not really necessary or desirable for this.

**Comment by embray** [comment] 2021-02-08 23:53
Let's keep the issue open until a fix is actually merged.

**Comment by embray** [comment] 2021-02-08 23:58
Like many things in astropy.io.fits / PyFITS there is history here. This code could easily simply wrap at the character boundary without regard to formatting. Or it could even be replaced with a call to `textwrap.wrap`. The problem is that this specific formatting scheme has been in place for over a decade and if you change it, it will actually cause headers that have been formatted the same way in the past to be formatted differently resulting in unexpected diffs between file versions. It shouldn't matter of course, but you'd be surprised by how many complaints arise when little things like this have been changed in the past.

**Comment by cbethge** [comment] 2021-02-09 00:06
Fair point. I guess what I was trying to say is: it shouldn't have been done with a prettifier in the first place. It might improve readability, but it also adds complexity and wastes space in the fits header. There's a saying in German: the opposite of good is good intentions. That's a little bit how I feel about this :-) Anyway, totally agree that changing it now is undesirable, as it would break consistency for existing data products.

**Comment by embray** [comment] 2021-02-22 19:38
>  I guess what I was trying to say is: it shouldn't have been done with a prettifier in the first place

I don't think it adds much space, particularly given we are no longer in the age of magnetic tape (except for large scale back-ups :)

I agree a lot of people would not need it, but there are still some people who enjoy looking at FITS headers in terminals, so...

**Closed** 2021-02-22 22:36 UTC
Labels: Bug, io.fits

**Comment by cbethge** [comment] 2023-06-23 21:55
Hi all, I just came back to this after a while. This is marked fixed - I just tried it the same example as before with astropy 5.3, and I would say it is "sort-of fixed": 

```
In [1]: from astropy.io import fits
   ...: hdu = fits.PrimaryHDU()
   ...: keyword = "WHATEVER"
   ...: value = "SuperCalibrationParameters_XXXX_YYYY_ZZZZZ_KK_01_02_03)-AAABBBCCC.n.h5 SuperNavigationParameters_XXXX_YYYY_ZZZZZ_KK_01_02_03)-AAABBBCCC.n.xml"
   ...: hdu.header.append((keyword, value, ' '))
   ...: hdu.header
Out[1]: 
SIMPLE  =                    T / conforms to FITS standard                      
BITPIX  =                    8 / array data type                                
NAXIS   =                    0 / number of array dimensions                     
EXTEND  =                    T                                                  
WHATEVER= 'SuperCalibrationParameters_XXXX_YYYY_ZZZZZ_KK_01_02_03)-AAABBBCCC.n&'
CONTINUE  '.h5 &'                                                               
CONTINUE  'SuperNavigationParameters_XXXX_YYYY_ZZZZZ_KK_01_02_03)-AAABBBCCC.n.&'
CONTINUE  'xml&'                                                                
CONTINUE  '' / 
```
The "xml" at the end doesn't get dropped anymore, but it is still doing an odd formatting thing, wasting space and introducing unnecessary empty CONTINUE lines.

**Comment by saimn** [comment] 2023-06-24 16:05
@cbethge - Well that's what was discussed above (https://github.com/astropy/astropy/issues/11298#issuecomment-775546162), I agree we should not try to split strings with spaces, but changing that now is problematic...

**Comment by cbethge** [comment] 2023-06-26 14:14
Sorry, must have missed/forgotten about that. Alright, it is what it is then!
