### ISSUE TITLE
Precision issue when adding 0 seconds to a Time

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#7899] opened 2018-10-15 20:01 UTC
I'm running into a weird issue on 32-bit systems

```python
>>> from astropy.time import Time
>>> from astropy import units as u
>>> t = Time('2016-03-22T12:30:31.000')
>>> t == t
True
>>> t + 0 * u.s == t
False
```

It looks like jd2 is being modified even though the offset is 0:

```python
>>> t.jd1
2457470.0
>>> t.jd2
0.021192129629629575
>>> (t + 0 * u.s).jd1
2457470.0
>>> (t + 0 * u.s).jd2
0.02119212962962962
```

To reproduce, do this in the astropy repo:

```
docker run -v $PWD:/repo -it quay.io/pypa/manylinux1_i686 /bin/bash
```

then this in the docker image shell:

```
/opt/python/cp36-cp36m/bin/pip install numpy scipy "pytest<3.7" pytest-astropy pytest-xdist Cython jinja2
/opt/python/cp36-cp36m/bin/python setup.py develop
/opt/python/cp36-cp36m/bin/python
```

then run the code above.

**Comment by lrm25** [comment] 2018-10-24 01:28
Hi.  Hacktoberfest brought me here.  I just reproduced this.  I'll take a look at it.

**Comment by lrm25** [comment] 2018-10-24 01:50
And you don't even need to add the units, just "t + 0" results in the same incorrect value

**Comment by pllim** [comment] 2018-10-25 14:13
@lrm25 , unfortunately due to release activities going on right now, you might not hear back soon enough. For the sake of Hacktoberfest PR count, feel free to submit a PR of what you think is the best solution and we can discuss there. Otherwise, please move on to other issues that you can tackle without further inputs. We apologize for any inconvenience caused and really appreciate your interest to contribute!

**Comment by StuartLittlefair** [comment] 2018-10-29 12:03
HI @lrm25; there's a very good reason not to allow the adding of UTC seconds to a ```Time``` object.

**Comment by StuartLittlefair** [comment] 2018-10-29 12:09
The underlying issue is that the conversion from UTC--TAI--UTC doesn't round-trip correctly - see https://github.com/astropy/astropy/issues/6970 for more details.

**Comment by lrm25** [comment] 2018-10-29 22:46
Thanks.

So, just out of curiosity, I'm assuming that you don't use UTC to add
because a second is subtracted or added periodically due to changing Earth
rotation rates, right?  If not, what's the reason?

Also, did you ever come up with a decision regarding whether or not to
change the upstream code or just to not use perfect equals comparisons?  It
seems like that discussion is still going on in the ticket link you sent me.

**Comment by StuartLittlefair** [comment] 2018-10-30 10:00
Hi @lrm25 - that's correct about UTC seconds.

The upstream fix is not up to us unfortunately. Astropy uses the [ERFA](https://github.com/liberfa/erfa) library for these calculations. ERFA itself is a more-or-less direct port of [SOFA](http://www.iausofa.org), which implements the IAU standards.

To avoid divergence of ERFA and SOFA, the upstream fix means first persuading SOFA to make a change to their library.

**Comment by bsipocz** [comment] 2019-03-18 05:23
I think this may have been solved in the meantime:

```
In [64]: >>> from astropy.time import Time
    ...: >>> from astropy import units as u
    ...: >>> t = Time('2016-03-22T12:30:31.000')
    ...: >>> t == t
Out[64]: True

In [65]: >>> t + 0 * u.s == t
Out[65]: True

In [66]: >>> t.jd1
Out[66]: 2457470.0

In [67]: >>> t.jd2
Out[67]: 0.021192129629629575

In [68]: >>> (t + 0 * u.s).jd1
Out[68]: 2457470.0

In [69]: >>> (t + 0 * u.s).jd2
Out[69]: 0.021192129629629575
```

**Comment by bsipocz** [comment] 2019-03-18 05:28
It's weird though as the other "precision" issues, https://github.com/astropy/astropy/issues/6970 and  https://github.com/astropy/astropy/issues/7898, are still around.

**Comment by mhvk** [comment] 2019-03-25 14:46
Looking back through the text here, the bug was for a specific 32-bit version, but more generally represented UTC and TAI not perfectly round-tripping.  I'll close this in favour of #6970, which deals with that as well (and a bit more generally).

**Closed by mhvk** 2019-03-25 14:46 UTC
Labels: Bug, Close?, Duplicate, Upstream Fix Required, precision, time
