### ISSUE TITLE
A (Q)Table join that scrambles row order

### ISSUE THREAD

**Issue by HealthyPear** [astropy/astropy#13999] opened 2022-11-10 15:27 UTC
This is most probably (your) bug, as I tested that with mock simple astropy tables it works, but I am asking for help on how to debug the problem as I have no idea how to proceed.

I have 2 astropy tables created with a class from a particular data format.

The first (the left one) is basically a row

```python
a = np.array([1.])
left_table= QTable([a],names=('a'))
```

the second contains other data with units, but one of the columns is the same (even same `dtype` in my case), e.g.

```python
a = np.array([1., 1., 1.])
b = [2.0, 5.0, 8.5]
c = ['x', 'y', 'z']
d = [10, 20, 30]

r = QTable([a, b, c, d], names=('a', 'b', 'c', 'd'), units={"d":"m/s"})
```

If I join these mock tables it works,

```python
t = join(l, r, keys=["a"])
assert all(t["b"]==r["b"])
```

but in my case the order of the rows of the right table is all scrambled.

Unfortunately my code is not public for the moment also quite long and complex as its the first version, so I thought it might be easier to ask if someone has ever stumbled upon a similar issue and how did they debugged it.

For the moment I checked succesully that the single tables are as I expect and that the 2 common columns are equivalent and that their dtype is the same.

**Comment by HealthyPear** [comment] 2022-11-10 17:32
OK I have discovered that this issue can be fixed with the workaround described in #11619, though I do not understand why the simple mock example I show above works natively

**Comment by pllim** [comment] 2022-11-10 17:46
So is this a duplicate of #11619 ?

**Comment by HealthyPear** [comment] 2022-11-10 17:50
@pllim technically yes, but doesn't that snippet above work? isn't that basically the same thing? the order in that case seems to be preserved

**Comment by pllim** [comment] 2022-11-10 17:54
I am not a table expert. Would be easier if you can also share the minimal example that does not work, so we can compare. If not, then it is a lot of guessing.

**Closed** 2022-11-11 13:16 UTC
Labels: table, Close?, Duplicate
