### ISSUE TITLE
Using astropy.time.sidereal_time to convert from GPS time to LMST gives the error:    erfa.core.ErfaError: ERFA function "taiutc" yielded 1 of "unacceptable date"

### ISSUE THREAD

**Issue by nsteinle** [astropy/astropy#16294] opened 2024-04-15 17:35 UTC
### Description

I am using  a python module for gravitational wave computations called gwfast (https://github.com/CosmoStatGW/gwfast) which requires astropy<6.0.0,>=5.2.1 and for which I need to compute timescales of merging binaries that can range from a few years to hundreds of Megayears. 

I use the astropy.time.sidereal_time() to convert from GPS time to LMST via:

```python
    from astropy.coordinates import EarthLocation
    import astropy.time as aspyt
    import astropy.units as u
    import astropy
    astropy.utils.iers.conf.iers_degraded_accuracy='ignore'
    lat = 0.0
    long = 0.0
    t_Myr = 10.0
    t_GPS = t_Myr*(1.0e+6)*(3.156e+7)       # convert GPS time from Myr to seconds
    loc = EarthLocation(lat=lat*u.deg, lon=long*u.deg)
    t = aspyt.Time(t_GPS, format='gps', location=(loc))
    t_LMST = t.sidereal_time('mean').value
    return np.array(LMST/24.)
```

(1) When I use a short length of time, eg t_Myr = 1e-4 Myr, astropy works fine and gives t_LSMT=0.06963637342034819.

(2) When I use an intermediate length of time, eg 0.1 Myr, astropy gives a warning with t_LSMT=0.40555665106748884,
```
>  /home/lnx/Projects/MultiMess_stellarmass/compasmos/compasmos_env/lib/python3.10/site-packages/erfa/core.py:133: ErfaWarning: ERFA function "taiutc" yielded 1 of "dubious year (Note 4)"
            warn(f'ERFA function "{func_name}" yielded {wmsg}', ErfaWarning)
          /home/lnx/Projects/MultiMess_stellarmass/compasmos/compasmos_env/lib/python3.10/site-packages/erfa/core.py:133: ErfaWarning: ERFA function "utcut1" yielded 1 of "dubious year (Note 3)"
            warn(f'ERFA function "{func_name}" yielded {wmsg}', ErfaWarning)
          WARNING: Tried to get polar motions for times after IERS data is valid. Defaulting to polar motion from the 50-yr mean for those. This may affect precision at the arcsec level. Please check your astropy.utils.iers.conf.iers_auto_url and point it to a newer version if necessary. [astropy.coordinates.builtin_frames.utils]
```
(3) When I use a long length of time, e.g. 10 Myr, astropy gives the following error without a t_LSMT:
```
> Traceback (most recent call last):
  File "/home/lnx/Projects/MultiMess_stellarmass/compasmos/run_population/run_pipe.py", line 924, in <module>
    print(t_GPS, test_astropy_time(t_GPS))
  File "/home/lnx/Projects/MultiMess_stellarmass/compasmos/run_population/run_pipe.py", line 889, in test_astropy_time
    LMST = t.sidereal_time('mean').value
  File "/home/lnx/Projects/MultiMess_stellarmass/compasmos/compasmos_env/lib/python3.10/site-packages/astropy/time/core.py", line 2278, in sidereal_time
    return self._sid_time_or_earth_rot_ang(longitude=longitude, **model_kwargs)
  File "/home/lnx/Projects/MultiMess_stellarmass/compasmos/compasmos_env/lib/python3.10/site-packages/astropy/time/core.py", line 2328, in _sid_time_or_earth_rot_ang
    theta = self._call_erfa(function, scales)
  File "/home/lnx/Projects/MultiMess_stellarmass/compasmos/compasmos_env/lib/python3.10/site-packages/astropy/time/core.py", line 2352, in _call_erfa
    erfa_parameters = [
  File "/home/lnx/Projects/MultiMess_stellarmass/compasmos/compasmos_env/lib/python3.10/site-packages/astropy/time/core.py", line 2353, in <listcomp>
    getattr(getattr(self, scale)._time, jd_part)
  File "/home/lnx/Projects/MultiMess_stellarmass/compasmos/compasmos_env/lib/python3.10/site-packages/astropy/time/core.py", line 1647, in __getattr__
    tm._set_scale(attr)
  File "/home/lnx/Projects/MultiMess_stellarmass/compasmos/compasmos_env/lib/python3.10/site-packages/astropy/time/core.py", line 773, in _set_scale
    jd1, jd2 = conv_func(*args)
  File "/home/lnx/Projects/MultiMess_stellarmass/compasmos/compasmos_env/lib/python3.10/site-packages/erfa/core.py", line 16910, in taiutc
    check_errwarn(c_retval, 'taiutc')
  File "/home/lnx/Projects/MultiMess_stellarmass/compasmos/compasmos_env/lib/python3.10/site-packages/erfa/core.py", line 124, in check_errwarn
    raise ErfaError(f'ERFA function "{func_name}" yielded {emsg}')
erfa.core.ErfaError: ERFA function "taiutc" yielded 1 of "unacceptable date"
```
I've reproduced these errors with versions in astropy<6.0.0,>=5.2.1.

Might this problem be fixed in more recent versions of astropy, ie 6.0+, in which case may someone help me understand how I could manually edit my astropy installation to fix it since gwfast is incompatible with the more recent astropy versions? 

Or are there astronomical data tables I need to install manually for astropy<6.0.0 to handle these long times? 

It would be very nice if there was a physically sensible work around for this. Any advice/help is appreciated. Thanks!

### Expected behavior

I expected astropy.time.sidereal_time() to produce an estimate of the LSMT for given GPS coordinate time. 

### How to Reproduce

1. Get astropy<6.0.0,>=5.2.1
2. Then run the above python script for a few different t_Myr.
3. The error occurs depending on the value of t_Myr.

### Versions

```python 3.10.4
   astropy<6.0.0,>=5.2.1
```

**Comment by neutrinoceros** [comment] 2024-04-15 17:46
Do you know _why_ gwfast pi she astropy<6 ? It might be that it's not _actually_ incompatible and that the pin was just added as a precautionary measure. Pip allows upgrading a package even beyond upper bounds set by other packages (it just displays a warning), so it might be worth a try before digging deeper.

**Comment by nsteinle** [comment] 2024-04-15 18:16
@neutrinoceros  Thanks for the suggestion. I just tried deleting the older astropy version and re-running with astropy==6.0.1 but the same error still arises from astropy time computation. This is why I removed all reference to gwfast in my code snipper issue submission here, since this seems to be localized to astropy? Sorry if Im missing something here!

**Comment by pllim** [comment] 2024-04-15 18:20
Hello @nsteinle , what is the exact command you used to create `t_Myr`? Thanks.

**Comment by nsteinle** [comment] 2024-04-15 18:25
> Hello @nsteinle , what is the exact command you used to create `t_Myr`? Thanks.

Hi! Ah, sorry for not specifying. I am defining t_Myr to be a double, e.g., t_Myr = 1.0

**Comment by nsteinle** [comment] 2024-04-15 18:55
@pllim Ah yes, sorry for that. I'm setting lat=0.0 and long=0.0. Here's a complete MWE:


`def test_astropy_time(t_Myr, lat=0.0, long=0.0):
    from astropy.coordinates import EarthLocation
    import astropy.time as aspyt
    import astropy.units as u
    import astropy
    astropy.utils.iers.conf.iers_degraded_accuracy='ignore'
    t_GPS = t_Myr*(1.0e+6)*(3.156e+7)       # convert GPS time from Myr to seconds
    loc = EarthLocation(lat=lat*u.deg, lon=long*u.deg)
    t = aspyt.Time(t_GPS, format='gps', location=(loc))
    t_LMST = t.sidereal_time('mean').value
    return np.array(t_LMST/24.)

# main
if __name__ == "__main__":
    t_Myr = 10.0
    print(t_Myr, test_astropy_time(t_Myr))
`

**Comment by mhvk** [comment] 2024-04-15 19:06
The problem is simpler: You cannot get sidereal time or UTC for a million years in the future, because we do not know Earth's rotation sufficiently well - i.e., how many leap seconds will have happened by then. This is also why you are just getting a warning for earlier times - for those, UTC will be off a bit, but the result will still be meaningful.

**Comment by pllim** [comment] 2024-04-15 19:10
So, does that mean there is nothing to fix here?

**Comment by nsteinle** [comment] 2024-04-15 19:33
@mhvk  This is what I suspected, but wasn't sure if it was this fundamental uncertainty or something astropy related. Well, I'm left to wonder how would one handle this for modelling astrophysical sources whose signals originate ~ Myr ago but we want to compute the local time when it would arrive? Seems like a relevant issue for astropy, but that's up to y'all to decide! Thanks for confirming this, though.

**Comment by mhvk** [comment] 2024-04-15 19:56
@nsteinle - that assumes we would know the distance to a source accurate enough to know to the fraction of a day when a signal would arrive...

Anyway, will close this now...

**Closed by mhvk** 2024-04-15 19:56 UTC
Labels: time, question

**Comment by pllim** [comment] 2024-04-15 20:05
> I apologize for my initial mislabeling of this issue

No worries! And thanks for posting it here so others can benefit from this discussion in the future. 😸
