### ISSUE TITLE
Segmentation Fault When Using astropy.io.ascii.read()

### ISSUE THREAD

**Issue by tslmy** [astropy/astropy#7100] opened 2018-01-18 23:56 UTC
Minimal code to invoke the fault:

```python3
from astropy.io import ascii
ascii.read(['scintific packaging industries, inc., a new york corporation, is a wholly-   ', 'owned subsidiary of the company, and does business under the name "scientific', 'packaging industries".                                                       '])
```

Output:
```
[1]    58525 segmentation fault (core dumped)  python temp.py
```

I then executed this test:
```
python -c "import astropy; astropy.test(package='io.ascii')"
```

getting the output: (This is very long, so I put it [here](https://pastebin.com/embed_iframe/hDbe0ANe)).

I am aware that many have filed issues about segfaults, but even with astropy updated to the newest version, I still cannot get around this problem.

I am also aware that the list given in my minimal code is not representing a table at all. The problem is, I have no control over the input data. Can someone please help me out of this? Thanks!

**Comment by pllim** [comment] 2018-01-19 01:03
Hi. The problem here is badly placed double quotes plus guessing behind the scene. The following works for me, does it work for you? Also the test log that you provided showed that no `io.ascii` tests failed.
```python
In [1]: lines = ['scintific packaging industries, inc., a new york corporation, 
   ...: is a wholly-   ', 'owned subsidiary of the company, and does business un
   ...: der the name "scientific', 'packaging industries".                      
   ...:                                  ']

In [2]: from astropy.io import ascii

In [3]: tab = ascii.read(lines, format='no_header', guess=False, names=['col1'], delimiter='\n')
```

**Comment by tslmy** [comment] 2018-01-19 02:23
Hi Lim! 
Thanks for this quick reply.
As you can see, once deployed in production environment, I would have zero knowledge about whether an input (list of strings) represents a table or not, let alone the format of the table. in other words, I'm very much replying on the 'guess' option there.
I wonder if there is a version of astropy that does not give segfaults, or if i should better off give up the "fast" method?

**Comment by taldcroft** [comment] 2018-01-19 11:36
@tslmy - in the case of tables which may be be very badly formed, you should not use the `fast` method.  That said, we should certainly track down this bug!

**Comment by neutrinoceros** [comment] 2024-01-16 15:28
I tried to reproduce, and with astropy 6.1dev, I don't see a segfault. Instead an exception is raised (`astropy.io.ascii.core.InconsistentTableError`), so it's much less of a show-stopper. My understanding of the conversation and docs is that autoguessing is a convenience that was never 100% reliable so I think the current behaviour is good enough ?

**Comment by tslmy** [comment] 2024-01-16 21:01
I utterly don't remember filing this issue.

How time flies.

**Comment by pllim** [comment] 2024-01-16 21:34
No one else has commented here that they ran into the same error. And if original reporter has moved on... @taldcroft , should we close this issue?

**Closed** 2024-01-24 05:54 UTC
Labels: io.ascii, Bug, Close?, closed-by-bot
