### ISSUE TITLE
ValueError: year -4713 is out of range

### ISSUE THREAD

**Issue by CAReeser** [astropy/astropy#11393] opened 2021-03-17 02:14 UTC
Get the following error:
```
cvl_twl_set = (obs.sun_set_time(time_now, horizon=-12*u.degree,which='nearest').to_datetime()).replace(tzinfo=from_zone)
  File "/usr/local/lib/python3.8/dist-packages/astropy/time/core.py", line 2115, in to_datetime
    return tm._shaped_like_input(tm._time.to_value(timezone))
  File "/usr/local/lib/python3.8/dist-packages/astropy/time/formats.py", line 1010, in to_value
    out[...] = datetime.datetime(iy, im, id, ihr, imin, isec, ifracsec)
ValueError: year -4713 is out of range
```
code executing is:
```python

    obs = Observer(latitude=lat*u.deg, longitude=lon*u.deg,elevation=elv*u.m, name='', timezone='UTC', pressure=1*bar)
    time_now = Time(datetime.utcnow())

         ast_dwn_rise = (obs.sun_rise_time(time_now, horizon=-18*u.degree,which='nearest').to_datetime()).replace(tzinfo=from_zone)
            w_time = ast_dwn_rise.astimezone(to_zone)
            sast_dwn_rise = w_time.strftime("%Z:%H:%M:%S")

            cvl_twl_set = (obs.sun_set_time(time_now, horizon=-12*u.degree,which='nearest').to_datetime()).replace(tzinfo=from_zone)
            w_time = cvl_twl_set.astimezone(to_zone)
            scvl_twl_set = w_time.strftime("%Z:%H:%M:%S")

            cvl_twl_rise = (obs.sun_rise_time(time_now, horizon=-12*u.degree,which='nearest').to_datetime()).replace(tzinfo=from_zone)
            w_time = cvl_twl_rise.astimezone(to_zone)
            scvl_twl_rise = w_time.strftime("%Z:%H:%M:%S")
```
The first section of code (ast_dwn_rise...) executes as expected, the code only errors on the second group of code (cvl_twl_set...).

This occcurs infrequently, about 1 in 20 times.  
Ubuntu 20.04
astropy 4.2
python 3.8.5
VSCode

**Comment by pllim** [comment] 2021-03-17 13:55
Hello. Thanks for the traceback but unfortunately it isn't very useful without a complete minimally reproducible example. For instance, it is pretty clear that `Observer` isn't from `astropy`. And based on the indentation, looks like you have taken out some code that probably run some of the posted code in a loop. Therefore, there are too many unknowns to provide you with an useful answer.

On your part, you could attempt to use `try ... except ...` to catch when the exception happens and the inspect the suspected variable values, or try out `pdb`.

Hope this helps.

**Comment by mhvk** [comment] 2021-03-17 18:41
Thanks for reporting! Maybe a duplicate of #9231? Could you check, @CAReeser?

**Comment by CAReeser** [comment] 2021-03-17 23:27
Not the same because I am only using the current date, as #9231 is looking
up old dates.
I suspect it is an issue with the use of a non-astropy observer. I will try
an astropy observer.  Good catch on that, BTW.
Thanks,
Cliff

**Comment by CAReeser** [comment] 2021-03-17 23:42
My mistake.
I am using all astroplan functions: observer, sun_set_time, sun_rise_time,
etc.
No astropy.
Not your issue.
Thanks for your quick responses.

**Comment by pllim** [comment] 2021-03-18 00:20
Thanks for the update, @CAReeser . Unfortunately, I am unable to transfer the issue for you. Please open a new issue at https://github.com/astropy/astroplan/issues .

**Closed by pllim** 2021-03-18 00:20 UTC
Labels: Needs-clarification
