### ISSUE TITLE
Can't create ITRS coordinates from EarthLocations for sources that move along with the Earth

### ISSUE THREAD

**Issue by tomfelker** [astropy/astropy#12678] opened 2021-12-31 07:42 UTC
Perhaps this is more of a question or feature request: Given an EarthLocation for some source object (basically, GPS coordinates) fixed relative to Earth, how can I turn this into a coordinate in ITRS (or any other frame), such that I can point my telescope at it by transforming it into the AltAz coordinates of my telescope?

For background: I'm trying to write software to point a telescope at planes and satellites.  For planes, I can get ADS-B data with their GPS coordinates, and I know my telescope's GPS coordinates.  But the discussions here:

https://docs.astropy.org/en/latest/coordinates/common_errors.html#altaz-calculations-for-earth-based-objects

https://github.com/astropy/astropy/issues/10983

suggest that it's not as simple as specifying EarthLocations for the plane and telescope, and converting the plane's EarthLocation to ITRS and thence into an AltAz with the telescope's location.  The explanation suggests that if I do that, the plane's ITRS location will be something like "where the plane, not moving with respect to the solar system barycenter, would have to have been, such that it would appear at the given location to an observer at the geocenter".  And that location can be hundreds of meters away from where the plane actually is, so the angles will be very wrong if the plane is close to the telescope.

In other words, the plane's location in ITRS seems to be tweaked to remove stellar aberration based on the Earth's motion around the sun.  But that seems correct only if the plane were not moving relative to the Sun.  Yet I specified the plane's position as an EarthLocation, so I'd expect it to move along with the Earth.  (I also never specified a time, so whatever velocity for Earth it's using in these calculations is arbitrary and surprising.)

The first link above shows a workaround, but that doesn't seem to include computing a coordinate for the plane that is "correct" in the sense that you could use it like any other coordinate to point your telescope at it by transforming it into AltAz.

I actually stumbled upon this while testing my own direct itrs_to_altaz() transform, which I was doing for performance reasons (and to avoid specifying an arbitrary obstime for the AltAz, without which, it crashes when transforming ITRS to AltAz).  And indeed, my result was slightly different from using itrs.transform_to(altaz) for nearby observers, probably in the same way as the issue linked above.

It's possible this is a bug in how AltAz treats the observer location EarthLocations, not doing the same inverse stellar aberration calculation that it does for incoming ITRS coordinates.  Or perhaps EarthLocation.get_itrs() would need to give a coordinate with differentials, so that the stellar aberration calculation could be cancelled out by a light time-of-flight calculation.  Or perhaps there's an easier, more straightforward way?

It's also possible that I'm just confused... any thoughts?

**Comment by mkbrewer** [comment] 2022-01-03 19:06
I'd suggest taking a look at `test_straight_overhead()` in `/astropy/coordinates/tests/test_intermediate_transformations.py` to give you an idea how to do this correctly.

**Comment by mkbrewer** [comment] 2022-01-03 19:14
Of course, that assumes that the object is stationary. If it is moving, you may need to correct for light travel time.

**Comment by mkbrewer** [comment] 2022-01-03 19:32
Oh, I didn't look at the first link that you posted. That should be equivalent, in which case I don't understand this: 

> The first link above shows a workaround, but that doesn't seem to include computing a coordinate for the plane that is "correct" in the sense that you could use it like any other coordinate to point your telescope at it by transforming it into AltAz.

Have you verified that the resulting AltAz is incorrect?

**Comment by tomfelker** [comment] 2022-01-03 21:05
So I guess what I'm getting at is, I'm specifying the telescope's location, and the object's location, in the same way (with EarthLocation).  So whatever assumption is being made about the telescope's or the object's motion, I'd expect to be the _same_ assumption.  And so, given that the relative motion between the telescope and the object is zero (and light transit time is negligible), the pointing ought to come out simple, with any aberration, transit times, or relativistic beaming calculations cancelling out perfectly... so if the plane is directly overhead in the GPS coordinates, it ought to tell me to point the telescope up 90 degrees.  Yet it doesn't...

It may be that the business in test_straight_overhead() is just what I need to do to determine where to point the telescope, for any target object... in which case it seems like there should be a utility function for it, and the more simple AltAz stuff should be documented that it only works for distant targets.

But I don't see how it could be something wrong with what I'm doing with coordinates, since I'm treating them the same way for both telescope and object.  That diagram showing how the object is really not overhead because of stellar aberration as viewed from the center of the earth... that same argument should also apply to the telescope's position.

Here's some example code, showing my own (alas, partially broken because of the up vector, and incomplete) implementation, which sort of short circuits any Earth motion or solar system barycenter stuff and keeps it in ITRS.

```
import astropy.coordinates
#from astropy.coordinates import frame_transform_graph
import numpy as np

import astropy.units as u

# one could use this globally like this:
#@astropy.coordinates.frame_transform_graph.transform(astropy.coordinates.FunctionTransform, astropy.coordinates.ITRS, astropy.coordinates.AltAz)
# but it changes the behavior globally, in a way that likely isn't correct
def itrs_to_altaz_direct(obj_itrs_coord, home_altaz_frame):
    # what is the Alt and Az for me, standing at home, to view the object?
    home_itrs = home_altaz_frame.location.itrs.cartesian
    # this is probably not correct, as it should be tangent to the ellipsoid, but just assume radial for now
    home_up = home_itrs / home_itrs.norm()
    home_east = astropy.coordinates.CartesianRepresentation(-home_itrs.y, home_itrs.x, home_itrs.z * 0)
    home_east /= home_east.norm()
    home_north = home_up.cross(home_east)
    home_north /= home_north.norm() # this normalization not strictly necessary
    
    home_to_obj = obj_itrs_coord.cartesian - home_itrs

    home_to_obj_dot_up = home_to_obj.dot(home_up)
    home_to_obj_dot_east = home_to_obj.dot(home_east)
    home_to_obj_dot_north = home_to_obj.dot(home_north)

    az = astropy.coordinates.Longitude(np.arctan2(home_to_obj_dot_east, home_to_obj_dot_north))
    home_to_obj_forward = np.sqrt(np.square(home_to_obj_dot_east) + np.square(home_to_obj_dot_north))
    alt = astropy.coordinates.Latitude(np.arctan2(home_to_obj_dot_up, home_to_obj_forward))
    distance = home_to_obj.norm()
    return astropy.coordinates.AltAz(alt = alt, az = az, distance = distance)

# using lat=0 rather than 52, otherwise exact overheadness is broken by Earth's oblateness?
obj = astropy.coordinates.EarthLocation(-1*u.deg, 0*u.deg, height=10.*u.km) 
home = astropy.coordinates.EarthLocation(-1*u.deg, 0*u.deg, height=0.*u.km)

home_altaz = astropy.coordinates.AltAz(location = home)
home_altaz_with_time = astropy.coordinates.AltAz(location = home, obstime = 'J2000')

# crashes without time
reference_obj_altaz = obj.itrs.transform_to(home_altaz_with_time)
print(f"AstroPy gives: {reference_obj_altaz}")
# gives altitude of 86.31338888 deg

# same answer with or without time
direct_obj_altaz = itrs_to_altaz_direct(obj.get_itrs(), home_altaz_with_time)
print(f"Would rather get: {direct_obj_altaz}")
# gives altitude of 90. deg
```

**Comment by mkbrewer** [comment] 2022-01-03 23:02
The 86.3 degrees there is expected. You are doing exactly what is described as the wrong way to do it in the first link that you posted. When you do `obj.itrs.transform_to(home_altaz_with_time)`, what that does is transform the object's geocentric position to ICRS referenced to the solar system barycenter removing aberration _as seen from the geocenter_. Then it transforms back from the ICRS to CIRS adding in aberration _as seen from the observer's location_. These do not cancel. To do this correctly using Astropy's transforms, you can either transform the small difference vector to CIRS as is shown in that link, or you can transform both locations to CIRS and then difference them as is done in `test_straight_overhead()`. 

On the other hand, you can bypass Astropy's transforms altogether, which is what you are doing in `itrs_to_altaz_direct()`. This will be much faster. I do think it would be a bit more straightforward there to just rotate the vectors about the z axis by the observer's longitude and then about the y axis by 90 - the observer's latitude. This will effectively place the observer at the pole and make the AltAz calculation trivial. 

Regarding oblateness, that is taken into account when setting up an `EarthLocation` from geodetic coordinates, so you don't need to worry about that.

**Comment by tomfelker** [comment] 2022-01-03 23:59
Indeed, I am basically banging my head against the "wrong way" presented in the first link, and just trying to understand why it's wrong.  I was under the impression that one could take coordinates (correctly specified in any frame), transform them (using the cool pathing-through-the-transform-graph thing) into AltAz (with location correctly set to where the telescope is), and thus learn where to point the telescope.

If that doesn't work, it implies that either we're specifying the coordinates wrong, or transforming them into AltAz wrong, or AltAz is using the wrong location, or that doing all this isn't expected to tell us where to point the telescope.

Perhaps the problem is that object_earth_location.get_itrs() is assuming the object is not moving relative to the SS barycenter, and is being observed from the (moving) geocenter.  So perhaps I need a way to convert an EarthLocation into ITRS with the assumption that it's moving along with the Earth (in which case, the object's relativistic beaming should cancel out its stellar aberration when viewed from the geocenter).  Or (equivalently?) a way to disable the removal of stellar aberration in EarthLocation.get_itrs().  That way, the object would be treated the same as the telescope (AltAz.location), which presumably is treated as moving along with the Earth.

That rotation thing you mention would be better, thanks! - I just need to refactor so I still have the lat lon at that point.

**Comment by mkbrewer** [comment] 2022-01-04 00:13
You are overthinking this. Astropy's transforms work exactly as they should. The accuracy is less than 1 milli-arcsecond. The issue with aberration is as I explained.

**Comment by mkbrewer** [comment] 2022-01-04 00:27
btw, the "problem" is with the transforms, not `EarthLocation.get_itrs()`. That just returns the geocentric coordinates of the `EarthLocation`. No assumptions are made and no aberration is removed.

**Comment by mkbrewer** [comment] 2022-01-04 00:36
It does assume the WGS84 for geodetic coordinates, which is used by GPS, unless you tell it otherwise.

**Comment by tomfelker** [comment] 2022-01-04 00:46
In the physical situation I'm trying to describe, the telescope and the target object are both moving along with the Earth, so have negligible relative velocity (only that caused by their displacement vector rotating with Earth).  So, thinking in an Earth-centered pseudo-inertial frame, there is no aberration.  Or, thinking in a solar system barycenter inertial frame, the observer-dependent 'stellar aberration' and source-dependent 'relativistic aberration' cancel out.

Somehow, though, it's computing one aberration but not the other, and then taking that angle difference over a large baseline (Earth's radius), and coming up with an angle that doesn't really make any physical sense.  Not really saying that it's wrong, just that I've somehow described a physical system that I don't understand, and I'm trying to figure out how to describe the physical system I want.

**Comment by mkbrewer** [comment] 2022-01-04 00:54
https://github.com/astropy/astropy/issues/10983#issuecomment-721163692

**Comment by tomfelker** [comment] 2022-01-04 01:30
Looking at that diagram again makes me think that it's not right to be doing the parallax calculation (moving the observer from the geocenter to the specified EarthLocation) using apparent positions (post-aberration), rather than astrometric positions (aberration subtracted away).  It would work only if the ratio of the ranges before and after the moving the observer is very nearly 1 - that is, only for very distant sources, or when the direction of parallax is nearly perpendicular to the direction to the source.  In practice, nearly perfect for stars, fine for planets, okay-ish for satellites, bad for aircraft.

I need to dig more to find where that's actually happening, though.

**Comment by mkbrewer** [comment] 2022-01-04 02:22
Well, it works perfectly, so long as you do it correctly. I do agree that things would be much simpler if one could do an ITRS->ITRS transform without going back through CIRS and ICRS. See  #10920. And therein lies a feature request. Good luck with that.

**Comment by mkbrewer** [comment] 2022-01-04 21:29
Thinking on this further, the main issue is that in Astropy AltAz is derived from the CIRS frame. This is due to the way that the underlying ERFA code works. Therefore, one must transform a topocentric ITRS position into the corresponding topocentric CIRS position in order to calculate AltAz. Now Astropy's ITRS frame is a simple geocentric frame with no topocentric option, so one must form the topocentric ITRS position manually as is done in the first link that you posted in order to properly derive the corresponding CIRS position. 

So how to fix this so that it would work like you would like it to? One fairly simple way would be to recognize that ITRS vectors have no time dependency and can therefore simply be added or subtracted. Then the ITRS->topocentric frame transforms could be modified to subtract the output frame's `EarthLocation` from the input ITRS vector before doing the transform.  This would allow the ITRS->CIRS topocentric transform to work directly with no need to go back to ICRS and get aberration involved. 

Another issue is that of the required `obstime`. Both ITRS and CIRS have a default `obstime`, but unfortunately the AltAz frame does not. In fact, the default `obstime` for AltAz is `None`. If AltAz were to be modified to share the same default at ITRS and CIRS, then this would work without the need to specify `obstime`.

With these modifications:
```
obj = EarthLocation(-1*u.deg, 52*u.deg, height=10.*u.km)
home = EarthLocation(-1*u.deg, 52*u.deg, height=0.*u.km)
obj.get_itrs().transform_to(AltAz(location=home)
```
should work.

**Comment by mkbrewer** [comment] 2022-01-04 21:45
Actually, the intermediate frame needs to know the observer's location also, so this would still be a two step process:
```
obj = EarthLocation(-1*u.deg, 52*u.deg, height=10.*u.km)
home = EarthLocation(-1*u.deg, 52*u.deg, height=0.*u.km)
cirs_topo = obj.get_itrs().transform_to(CIRS(location=home)
aa = cirs_topo.transform_to(AltAz(location=home))
```

**Comment by mkbrewer** [comment] 2022-01-04 22:02
An alternative would be to define a topocentric ITRS frame also. Then one could do:
```
obj = EarthLocation(-1*u.deg, 52*u.deg, height=10.*u.km)
home = EarthLocation(-1*u.deg, 52*u.deg, height=0.*u.km)
itrs_topo = obj.get_itrs().transform_to(ITRS(location=home))
aa = itrs_topo.transform_to(AltAz(location=home))
```
which might be a bit more intuitive for the user.

**Comment by tomfelker** [comment] 2022-01-09 20:57
Unless there's a subtlety I'm missing, I'd expect coordinate transforms to be transitive in the sense that
```
a.transform_to(b).transform_to(c) == a.transform_to(c)
```
If that is true, then it shouldn't be possible to 'fix' this case by introducing new frames or introducing shortcuts in the transform graph.

One question I have: are EarthLocations and ITRS coordinates intended to be astrometric or apparent?

I think the problem may be that the answer differs by context: AltAz(location = home_itrs) is treating it as astrometric (the observatory "actually is" displaced from the geocenter by home_itrs), but elsewhere (somewhere along the line when transforming obj_itrs to ICRS), they're being treated as apparent (the object "appears" at obj_itrs when viewed from the geocenter (with the geocenter moving, and the object not moving, relative to the SS barycenter)).

**Comment by mkbrewer** [comment] 2022-01-10 01:30
These topocentric transforms are transitive so long as the times and coordinate origins are the same. The problem is that, as currently written, ITRS coordinates have no topocentric option. Therefore the origin is always the geocenter. When the transform to AltAz is called, the ITRS coordinates are first transformed to CIRS at the geocenter and then when it tries to transform from CIRS to AltAz, the origins are different, so it transforms back to ICRS and then to topocentric CIRS at the given location. In this transform the geocentric CIRS coordinates are treated as apparent. This is natural for Astropy. Its focus is astronomical observations, so in the CIRS frame, target body coordinates are always treated as apparent, whereas observer coordinates are always treated as astrometric.  The trick to getting this working is to add a topocentric option to ITRS coordinates so that they can share an origin with AltAz coordinates thereby obviating the need to do an origin translation which involves recalculating aberration. The problem with getting that done is that given Astropy's focus, there is really no need for topocentric ITRS coordinates.

**Comment by tomfelker** [comment] 2023-03-07 09:00
> [...] so in the CIRS frame, target body coordinates are always treated as apparent, whereas observer coordinates are always treated as astrometric

That seems to be the crux of the issue... I'm specifying the two EarthLocations in exactly the same way, but apparently the "home" location I pass into AltAz() gets treated as astrometric (where it 'actually' is, and moving along with Earth), while "obj", which I convert to ITRS and transform into that AltAz, is treated as apparent (where it would appear from the center of the moving earth, if it itself were not moving).

Is there a way I can specify what I actually mean, that both should be astrometric and moving along with Earth's surface, in such a way that it would complain, or do some conversion, before treating them differently like that?

**Comment by mkbrewer** [comment] 2023-03-07 14:30
This has all been resolved by introducing the topocentric ITRS frame that I mentioned in Astropy 5.2. Please take a look at the first link in your original post to see how to do this now. You still need to specify an `obstime` since the `AltAz` frame doesn't default to `J2000` like others do. I'm not sure why this is, but I didn't change that.

**Comment by mhvk** [comment] 2023-03-07 21:38
@tomfelker - I think there now is a documented answer to your question, even if it is perhaps not as easy as one would like, so OK to close this issue?

**Comment by tomfelker** [comment] 2023-03-08 07:11
Indeed, okay to close - thanks for your help everyone!

I've tried the code now suggested in the "Common Mistakes" doc, and it does work - and it's nice (and probably faster, which is helpful for me) not to have to go through CIRS for that.

I'm still a bit confused where the assumption about astrometric vs apparent comes in, given the symmetry of what I was trying to do.  Perhaps it's something like, 'all coordinates that are given a location are astrometric (co-moving with that location), and otherwise they're apparent (fixed relative to solar system barycenter)'?  And so then the vector math to construct itrs_vec is just so that we can plug it into itrs_topo while also giving it a location, and thus communicating that it should be interpreted as astrometric?

**Comment by mkbrewer** [comment] 2023-03-08 16:10
I think that what is leading you astray is this false concept of symmetry. In celestial mechanics there is an observed and an observer. All corrections are applied to the observed but not to the observer. For instance, when observing a planet, we care about where the planet was when the light left it, but we don't care about where the observer was at that time. We only care about where the observer is when the light is received. This is the astrometric position of the planet with respect to the observer in the BCRS. Next we transform to GCRS by applying aberration and the gravitational deflection of light to the observed position, but not to the position of the observer. The same goes for the transformation to CIRS. We apply precession and nutation to the observed position only to arrive at the apparent position of the planet as seen by the observer. 

In the case of an observed position in the ITRS, if one just naively tries to transform the geocentric ITRS position of the observed to topocentric AltAz, all of those corrections are reversed to arrive at the astrometric position of the observed with respect to the geocenter in the BCRS. Then the astrometric position of the observed with respect to the observer in the BCRS is calculated by subtracting the geocentric position of the observer. Then all of the corrections are reapplied to this new position to arrive at the apparent position of the observed with respect to the observer, which will be different than what one would expect due to the difference between the subtracted aberration with respect to the geocenter and the added aberration with respect to the observer. 

The addition of a topocentric ITRS frame allows one to short circuit all of this by forming the astrometric position of the observed with respect to the observer in the ITRS rather than the BCRS. Then the AltAz position can be calculated without leaving the ITRS by merely doing a rotation of the coordinate system to yield the expected result.

**Comment by mhvk** [comment] 2023-03-08 16:23
@tomfelker - if the above helps you (as it does me!), and would have helped you had it been in the documentation, do you want to make a PR to add it?? There is something along those lines already, but perhaps you can make it clearer?

**Comment by tomfelker** [comment] 2023-03-10 07:05
Hmm, looking again and thinking about the meaning of location in a Coordinate, I think I now understand - does this sound right?

In the example of a common mistake:
```
aa = obj.get_itrs(t).transform_to(AltAz(obstime=t, location=home))
```
one should know that ITRS's default location is the geocenter, so it really means something like
```
obj_apparent_as_viewed_from_geocenter=obj.get_itrs(t, location=geocenter)
aa = obj_apparent_as_viewed_from_geocenter.transform_to(AltAz(obstime=t, location=home))
```

and further, that transform_to() between coordinates with different locations doesn't convert apparent as viewed from old location -> astrometric -> apparent as viewed new location, as one might expect.  It still seems to me like it should, but admittedly, the 600 meter error there is probably acceptable for artificial satellites and negligible for anything further out.

It'd be cool if get_itrs() could take a location parameter and return a topocentric ITRS frame, now that (woo!) such things exist.

**Comment by mkbrewer** [comment] 2023-03-10 14:58
> and further, that transform_to() between coordinates with different locations doesn't convert apparent as viewed from old location -> astrometric -> apparent as viewed new location, as one might expect.

That's exactly what it does. In the context of `transform_to()`, all observed positions in the ITRS are considered apparent. This doesn't matter so long as one stays in the ITRS as there is no difference between astrometric and apparent there. However, if one invokes `transform_to()` in a manner that requires leaving the ITRS frame, then this does matter. The two things that will do this are a change in the observer's position or a change in `obstime`. The former we have discussed here ad infinitum at this point. The latter opens up a whole can of worms, which in fact, is the ultimate cause of  the difficulty with the former.  Since Astropy is based on SOFA/ERFA, which is oriented towards stellar observation, the velocity of an observed position is always treated as zero with respect to the solar system barycenter in the fundamental frame transforms. If the velocity were handled appropriately, then, for an observed position that is stationary in the ITRS, a change in the position of the observer would not cause a change in the aberration correction as the relative velocity between the observed position and the observer would be zero. so there would be no aberration correction in the first place. Similarly, a change in `obstime` would not expose the passengers in your airplane to the vacuum of space by leaving the airplane behind in the Earth's orbit around the Sun.

I do like the idea of modifying `EarthLocation.get_itrs()` to have the option of returning a topocentric frame as that would obviate the need for manually setting up this frame. @mhvk what do you think about doing this? It seems easy enough to me.

**Comment by mhvk** [comment] 2023-03-10 16:13
I like the idea of modifying `el.get_itrs()` to make this easier, since we have had so much confusion about this. What exactly would it entail? Would it mean allowing the `location` to be set? And then making the coordinates relative to that position? If so, should taking the difference be optional, or need to be controlled via another argument? I think this should be a relatively simple addition.

Just in case: I guess the goal is not to produce a coordinate-less frame in which `el` is the `location`, right? Since really the annoyance is the part where one has to take the vector out and calculate a difference.

**Comment by mkbrewer** [comment] 2023-03-10 16:34
I think that the idea would be to simply add a `location` argument to `get_itrs()` that defaults to `None`. Then if a location is provided, `get_itrs()` would return a topocentric ITRS frame containing the difference between the object's position and that of the `location` argument. One could also use `EARTH_CENTER` as the default and always return the difference.

**Comment by tomfelker** [comment] 2023-03-10 17:22
> all observed positions in the ITRS are considered apparent

It appears they're considered apparent _as viewed from the geocenter_, regardless of the location that can now be given to the ITRS Coordinate.  In both cases observer's barycentric velocity is (almost) the same, so the plane (with assumed-zero barycentric velocity) abberates by the same up to 20.5 arcseconds, but the baseline changes from a few thousand meters to a few thousand kilometers, so it starts making an appreciable distance.

Another way of saying this is, probably the ITRS to AltAz calculation is subtracting an astrometric vector (the observer's AltAz's location) from the apparent-from-geocenter vector to the object.  My understanding is that since aberration isn't merely a shift, these are two fundamentally different vector spaces, so it's not correct to mix them like that.  I suspect the problem would go away if it aberrated or de-aberrated one of the vectors to match the other before doing subtracting.

I wonder if it's logically consistent to have a flag for whether a given coordinate is apparent or astrometric, and to complain (or do something different) when trying to add and subtract coordinates with mismatching flags.

And yeah - it's also true that if I could teach it that the plane is moving along with the Earth's surface (which using an EarthLocation apparently doesn't do...) then it would have the same nonzero barycentric velocity as the observer, and its relativistic beaming would exactly cancel the aberration from the moving observer.  That would at least hide the above issue (though I think it'd break down if the plane's velocity relative to the observer was large, as again, there would start to be a misalignment between apparent and astrometric vectors).

**Comment by mkbrewer** [comment] 2023-03-10 17:39
> It appears they're considered apparent as viewed from the geocenter, regardless of the location that can now be given to the ITRS Coordinate.

Not true. A topocentric ITRS position is also presumed to include diurnal aberration.

> Another way of saying this is, probably the ITRS to AltAz calculation is subtracting an astrometric vector (the observer's AltAz's location) from the apparent-from-geocenter vector to the object. 

As I explained above, this subtraction occurs in the BCRS where both vectors are, in fact, astrometric.

**Comment by mhvk** [comment] 2023-03-11 01:18
I like the idea of the `location` argument. Unlikely to have time to do it myself soon, though. @tomfelker - might you be interested? If nobody can do it here, it may be an idea to open a specific feature request for it - coding-wise, this is an easy one good for beginners.

**Closed** 2023-03-15 05:46 UTC
Labels: coordinates, Close?, closed-by-bot, question
