### ISSUE TITLE
astropy.units.isclose broken in astropy 5.1

### ISSUE THREAD

**Issue by maxnoe** [astropy/astropy#13280] opened 2022-05-27 11:16 UTC
### Description

`astropy.units.isclose` returns false for values within floating point precisions

### Expected behavior

`astropy.units.isclose` returns true for values within floating point precisions

### Actual behavior

`astropy.units.isclose` returns false for values within floating point precisions

### Steps to Reproduce

```python
In [1]: import astropy.units as u

In [2]: import numpy as np

In [3]: u.isclose(0 * u.m, np.finfo(np.float64).eps * u.m)
Out[3]: False

In [4]: u.isclose(0, np.finfo(np.float64).eps)
Out[4]: False

In [5]: np.isclose(0, np.finfo(np.float64).eps)
Out[5]: True.
```

### System Details

```
Linux-5.10.109-1-MANJARO-x86_64-with-glibc2.10
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18) 
[GCC 10.3.0]
Numpy 1.22.3
pyerfa 2.0.0.1
astropy 5.1
Scipy 1.8.0
Matplotlib 3.5.1
```

**Comment by pllim** [comment] 2022-05-27 12:41
Thanks for reporting this. But has this ever worked? The discrepancy is because the defaults are different. I went through the `_unquantify_allclose_arguments` logic and these are the numbers passed into numpy at the end.

```python
actual = 0.0
desired = 2.220446049250313e-16
rtol = 1e-05
atol = 0.0
```

Meanwhile, this is the numpy default: `Signature: np.isclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)`

So, you should do this instead when comparing zeroes:

```python
>>> u.isclose(0 * u.m, np.finfo(np.float64).eps * u.m, atol=1e-8 * u.m)
True
```

I am not sure if the different default setting was by design, and outdated default (maybe numpy changed it upstream?), or a bug. If we decided to patch this behavior, should add a test with the use case stated above.

**Comment by maxnoe** [comment] 2022-05-27 13:02
I got a broken test in the CI of ctapipe after it started using 5.1

**Comment by maxnoe** [comment] 2022-05-27 13:03
https://github.com/cta-observatory/ctapipe/runs/6625449488?check_suite_focus=true

**Comment by pllim** [comment] 2022-05-27 13:08
All this code that I mentioned has not been touched for at least 2 years. What version of astropy did you upgrade from? For now, explicitly setting `atol` for your test is backward compatible and will fix your pipeline failure.

**Comment by maxnoe** [comment] 2022-05-27 13:08
THe previous runs were using 5.0.4

**Comment by pllim** [comment] 2022-05-27 13:13
What was the value of `back.x` with astropy 5.0.x? Maybe this is a symptom of a different bug.

Fun fact: I came across this:

* numpy/numpy#10161

**Comment by maxnoe** [comment] 2022-05-27 13:22
Mmh. I am confused now. I cannot reproduce locally. Test passes with 5.1 locally... So it has to be something else, sorry for the fuzz. Still confusing why it worked before.

**Comment by mhvk** [comment] 2022-06-05 16:05
@maxnoe - the reasoning behind the different default for `atol` is that for quantities with units it really is not obvious what the default should be. As in the discussion pointed to by @pllim, there is even a more general question why one would pick any `atol` - are `1e-20` and `1e-10` really close? It would seem to depend on what one is interested in!

Anyway, I'll close this since it doesn't seem there was a change in behaviour from the astropy side...

**Closed by mhvk** 2022-06-05 16:05 UTC
Labels: units, Bug, Close?
