### ISSUE TITLE
astropy.modeling returns too many Parameters when defining a new Model as a subclass of another Model

### ISSUE THREAD

**Issue by Onoddil** [astropy/astropy#9108] opened 2019-08-09 14:27 UTC
When creating an `astropy.modeling.Model` that is a subclass of another `astropy.modeling.Model` (instead of just being a subclass of a `Fittable1DModel` or `Fittable2DModel`, e.g.) the `Parameters` of both the new Model and the super Model are returned, resulting in `TypeError: evaluate() takes X positional arguments but Y were given`.

MWE to reproduce the error:
```
import astropy
print('astropy version', astropy.__version__)

from astropy.modeling import Fittable2DModel, Parameter


class classmodel(Fittable2DModel):
    f = Parameter(default=1)
    x = Parameter(default=0)
    y = Parameter(default=2)

    def __init__(self, f=f.default, x=x.default, y=y.default):
        print(self.param_names)
        print('class input values', f, x, y)
        super().__init__(f, x, y)

    def evaluate(self):
        pass


class subclassmodel(classmodel):
    f = Parameter(default=3)
    x = Parameter(default=10)
    y = Parameter(default=12)
    h = Parameter(default=5)

    def __init__(self, f=f.default, x=x.default, y=y.default, h=h.default):
        print('subclass input values', f, x, y, h)
        super().__init__(f, x, y)

    def evaluate(self):
        pass


print('class should be: f=1, x=0, y=2')
print('subclass should be: f=3, x=10, y=12, h=5')
a = classmodel()
print('class params + names', a.parameters, a.param_names)
b = subclassmodel()
print('subclass params + names', b.parameters, b.param_names)
```

which gives:

```
astropy version 3.2.1
class should be: f=1, x=0, y=2
subclass should be: f=3, x=10, y=12, h=5
('f', 'x', 'y')
class input values 1 0 2
class params + names [1. 0. 2.] ('f', 'x', 'y')
subclass input values 3 10 12 5
('f', 'x', 'y', 'h')
class input values 3 10 12
subclass params + names [ 3. 10. 12.  5.] ('f', 'x', 'y', 'h')
```
and
```
astropy version 4.0.dev25505
class should be: f=1, x=0, y=2
subclass should be: f=3, x=10, y=12, h=5
('f', 'x', 'y')
class input values 1 0 2
class params + names [1. 0. 2.] ('f', 'x', 'y')
subclass input values 3 10 12 5
('f', 'x', 'y', 'f', 'x', 'y', 'h')
class input values 3 10 12
subclass params + names [ 3. 10. 12.  5.] ('f', 'x', 'y', 'f', 'x', 'y', 'h')
```

I am not sure what changed in the new v4.0 modeling framework updates from last week, but a cursory dig into the code suggests that the extension of `param_names` occurs somewhere in [here](https://github.com/astropy/astropy/blob/984461ff0bf4a000e1c037a26560cdc4689b4854/astropy/modeling/core.py#L114-L120), as `param_names` is length 4 before the loop and length 7 afterwards. My initial feeling is that that's a `CompoundModel` thing which multi-nesting subclasses of `Model`s is tripping up, but I am not an expert on the modeling framework.

See astropy/photutils#921 for a reproduction of a 'proper' failing use case, cc @eteq @larrybradley

**Comment by perrygreenfield** [comment] 2019-08-09 14:34
Thanks for the report. Yes, there were substantial changes in how parameters were changed and that is almost certainly the cause of the problem. I'll look into it, probably next week.

**Comment by bsipocz** [comment] 2019-08-13 01:21
@perrygreenfield - photutils has been fixed by removing defaulting the same parameters in the nested subclassing case (https://github.com/astropy/photutils/pull/931). Not sure whether that case is suppose to be supported, I would say it was rather confusing and shouldn't be used like that.

**Comment by perrygreenfield** [comment] 2019-08-13 21:03
@Onoddil Can you give me the example that causes the evaluate error?

**Comment by Onoddil** [comment] 2019-08-13 22:43
Hi @perrygreenfield the actual run in Photutils which causes the error is in [this Travis CI job](https://travis-ci.org/astropy/photutils/jobs/569054120), and the error is `TypeError: evaluate() takes 6 positional arguments but 9 were given`. The photutils code for the two `model`s that breaks in 4.0 modeling, before the fix currently in place in photutils/master, can be seen [here](https://github.com/Onoddil/photutils/blob/2f290dab7838c02f35a169b55d0944eb8774be6a/photutils/psf/models.py), but essentially boils down to:

```
class FittableImageModel(Fittable2DModel):
    flux = Parameter(description='Intensity scaling factor for image data.',
                     default=1.0)
    x_0 = Parameter(description='X-position of a feature in the image in '
                    'the output coordinate grid on which the model is '
                    'evaluated.', default=0.0)
    y_0 = Parameter(description='Y-position of a feature in the image in '
                    'the output coordinate grid on which the model is '
                    'evaluated.', default=0.0)
class EPSFModel(FittableImageModel):
    flux = Parameter(description='Intensity scaling factor for image data.',
                     default=1.0)
    x_0 = Parameter(description='X-position of a feature in the image in '
                    'the output coordinate grid on which the model is '
                    'evaluated.', default=0.0)
    y_0 = Parameter(description='Y-position of a feature in the image in '
                    'the output coordinate grid on which the model is '
                    'evaluated.', default=0.0)
```

Calling `evaluate` breaks like it does because `EPSFModel` has `self.parameters` as `(flux, x_0, y_0, flux, x_0, y_0)`, as seen in the Travis CI log. Let me know if that's enough to work on or if you have any questions or any other information you need to help with digging into this.

**Comment by perrygreenfield** [comment] 2019-08-14 12:21
That should be sufficient. Although it seems that in this case the definition of the parameters in the subclass is unnecessary since nothing is different in their definition in the subclass. Still, it's a bug that needs to be fixed.

**Closed** 2019-08-15 20:28 UTC
Labels: Affects-dev, Bug, modeling
