### ISSUE TITLE
astropy.io.fits Column memory problem

### ISSUE THREAD

**Issue by cassandra-sh** [astropy/astropy#6649] opened 2017-10-03 15:17 UTC
I'm having a crash every time I try to work with a fits table after having added something to it. This is especially problematic when trying to add a column and then save the resultant fits table to a new file.

Here's a really simple code that gets the error:

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct  3 10:15:54 2017

Trying to demonstrate an issue with fits columns
"""

from astropy.io import fits
import numpy as np
import os

fits_file_path = "/scr/depot0/csh4/all_wise_quasars.fits"

size = os.path.getsize(fits_file_path)
print("File size is " + str(size/1000000) + " megabytes")

f = fits.open(fits_file_path)
print("Getting length the first time")
length = len(f[1].data)
print("Length is " + str(length))

values_to_add = np.empty(length).fill(False)
column = fits.Column(name='false_vals', format="L", array=values_to_add)
f[1].columns.add_col(column)

print("Going to get length again")
length = len(f[1].data)
print("Length is " + str(length))
```

Which has the output

```
File size is 133.2288 megabytes
Getting length the first time
Length is 581728
Going to get length again
Traceback (most recent call last):

  File "<ipython-input-9-0a6cbaf424c2>", line 1, in <module>
    runfile('/scr/depot0/csh4/astropy_problem.py', wdir='/scr/depot0/csh4')

  File "/scr/depot0/csh4/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 688, in runfile
    execfile(filename, namespace)

  File "/scr/depot0/csh4/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/scr/depot0/csh4/astropy_problem.py", line 31, in <module>
    length = len(f[1].data)

  File "/scr/depot0/csh4/anaconda3/lib/python3.6/site-packages/astropy/utils/decorators.py", line 736, in __get__
    val = self.fget(obj)

  File "/scr/depot0/csh4/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/table.py", line 388, in data
    data = self._get_tbdata()

  File "/scr/depot0/csh4/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/table.py", line 171, in _get_tbdata
    self._data_offset)

  File "/scr/depot0/csh4/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py", line 480, in _get_raw_data
    return self._file.readarray(offset=offset, dtype=code, shape=shape)

  File "/scr/depot0/csh4/anaconda3/lib/python3.6/site-packages/astropy/io/fits/file.py", line 285, in readarray
    buffer=self._mmap)

TypeError: buffer is too small for requested array
```
This same error is thrown if I try to do anything with the table. However, I can still access `f[1].header` and `f[1].columns` just fine. 

The fits catalog file I'm running on can be found at
http://faraday.uwyo.edu/~admyers/wisemask2017/all_wise_quasars.fits

I'm running these versions:
conda 4.3.25
astropy 2.0.1
python 3.6.1
numpy 1.13.1
spyder 3.2.1

My OS is Springdale Linux 
Release 6.9 (Pisa)
GNOME 2.28.2
Kernel Linux 2.6.32-696.10.1.el6.x86_64
with 16 GB RAM

The memory usage in this code is not much, so I think these are the possible problems

- I'm not adding to this file in the right way
- there is a problem with this fits file (possible, but topcat has no problem with it)
- there is a problem with the combination of versions of codes that I am using
- astropy doesn't run well on files at this size (~100 MB)
- astropy has a memory issue here

It isn't clear which of these is the problem, so I figured I'd submit the issue here. 

Thanks!

**Comment by pllim** [comment] 2017-10-03 15:55
The error is due to
```python
values_to_add = np.empty(length).fill(False)
```
[np.fill()](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ndarray.fill.html) is an in-place operation. Therefore, `values_to_add` is not the array but just a `None`.

If you do this instead, it will work:
```python
values_to_add = [False] * length
```

If this fixes your problem, please close the issue.

**Comment by cassandra-sh** [comment] 2017-10-03 15:59
That did not fix the problem. The output is unchanged.

**Comment by pllim** [comment] 2017-10-03 16:00
Did you try with a fresh Python session? The fix worked for me ™️ .

**Comment by cassandra-sh** [comment] 2017-10-03 16:02
I've tried an external system terminal and its seems to have the same problem.

**Comment by cassandra-sh** [comment] 2017-10-03 16:03
It could be that your version is different from mine

**Comment by pllim** [comment] 2017-10-03 16:04
Astropy is 2.0.2 now. Upgrade astropy and try again? Admittedly I am using dev on Python 3.5, so at least that combo worked.

**Comment by cassandra-sh** [comment] 2017-10-03 16:08
I updated it, and the output is the same.

**Comment by pllim** [comment] 2017-10-03 16:15
Also works using astropy dev under Python 3.6, so if it is a bug, it is already fixed.
```python
>>> from astropy.io import fits
>>> filename = 'all_wise_quasars.fits'
>>> pf = fits.open(filename) 
>>> values_to_add = [False] * 581728
>>> column = fits.Column(name='false_vals', format="L", array=values_to_add)
>>> pf[1].columns.add_col(column) 
ColDefs(
    name = 'NAME'; format = '19A'
    name = 'RA'; format = 'D'
    name = 'DEC'; format = 'D'
    name = 'SIGRA'; format = 'D'
    name = 'SIGDEC'; format = 'D'
    name = 'SIGRADEC'; format = 'D'
    name = 'W1'; format = 'E'
    name = 'W1ERR'; format = 'E'
    name = 'W2'; format = 'E'
    name = 'W2ERR'; format = 'E'
    name = 'W3'; format = 'E'
    name = 'W3ERR'; format = 'E'
    name = 'W4'; format = 'E'
    name = 'W4ERR'; format = 'E'
    name = 'N_A'; format = 'E'
    name = 'N_B'; format = 'E'
    name = 'CC_FLAGS'; format = '4A'
    name = 'EXT_FLAG'; format = 'I'
    name = 'VAR_FLG'; format = '4A'
    name = 'PH_QUAL'; format = '4A'
    name = 'MOON_LEV'; format = '4A'
    name = 'W1MAG_2'; format = 'E'
    name = 'W2MAG_2'; format = 'E'
    name = 'W3MAG_2'; format = 'E'
    name = 'W4MAG_2'; format = 'E'
    name = 'RA_AS'; format = 'D'
    name = 'DEC_AS'; format = 'D'
    name = 'SIGRA_AS'; format = 'D'
    name = 'SIGDEC_AS'; format = 'D'
    name = 'SIGRADEC_AS'; format = 'D'
    name = 'W1_AS'; format = 'E'
    name = 'W1ERR_AS'; format = 'E'
    name = 'W2_AS'; format = 'E'
    name = 'W2ERR_AS'; format = 'E'
    name = 'W3_AS'; format = 'E'
    name = 'W3ERR_AS'; format = 'E'
    name = 'W4_AS'; format = 'E'
    name = 'W4ERR_AS'; format = 'E'
    name = 'N_A_AS'; format = 'E'
    name = 'N_B_AS'; format = 'E'
    name = 'CC_FLAGS_AS'; format = '4A'
    name = 'EXT_FLAG_AS'; format = '8A'
    name = 'MOON_LEV_AS'; format = '4A'
    name = 'false_vals'; format = 'L'
)
```

**Comment by cassandra-sh** [comment] 2017-10-03 16:16
are you able to call pf[1].data after that operation?

**Comment by pllim** [comment] 2017-10-03 16:35
Ah, yes. I missed that important last step to get the error. Sorry for the oversight! If I turn `memmap` off, there is some traceback below that might be useful. I'll mark this as a bug. Thanks for the report! @saimn or @MSeifert04 , the error seems to come from `lazyproperty`, do you have any idea what is happening here? p.s. Adding `mode='update'` also gives the same error:
```python
.../astropy/utils/decorators.py in __get__(self, obj, owner)
    730         try:
--> 731             return obj.__dict__[self._key]
    732         except KeyError:

KeyError: 'data'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-42-4139ea16bb42> in <module>()
----> 1 pf[1].data

.../astropy/utils/decorators.py in __get__(self, obj, owner)
    731             return obj.__dict__[self._key]
    732         except KeyError:
--> 733             val = self.fget(obj)
    734             obj.__dict__[self._key] = val
    735             return val

.../astropy/io/fits/hdu/table.py in data(self)
    400     @lazyproperty
    401     def data(self):
--> 402         data = self._get_tbdata()
    403         data._coldefs = self.columns
    404         # Columns should now just return a reference to the data._coldefs

.../astropy/io/fits/hdu/table.py in _get_tbdata(self)
    165         else:
    166             raw_data = self._get_raw_data(self._nrows, columns.dtype,
--> 167                                           self._data_offset)
    168             if raw_data is None:
    169                 # This can happen when a brand new table HDU is being created

.../astropy/io/fits/hdu/base.py in _get_raw_data(self, shape, code, offset)
    474                               offset=offset)
    475         elif self._file:
--> 476             return self._file.readarray(offset=offset, dtype=code, shape=shape)
    477         else:
    478             return None

.../astropy/io/fits/file.py in readarray(self, size, offset, dtype, shape)
    309                 self._file.seek(offset)
    310                 data = _array_from_file(self._file, dtype, count, '')
--> 311                 data.shape = shape
    312                 return data
    313         finally:

ValueError: cannot reshape array of size 576698 into shape (581728,)
```

**Comment by pllim** [comment] 2017-10-03 16:46
There is a workaround though. For now, you need to create it "from scratch" like this (I used `pf` instead of `f` out of habit):
```python
newcols = [c for c in pf[1].columns] + [column]
tnew = fits.BinTableHDU.from_columns(newcols)
pf[1] = tnew
pf.writeto('table_with_extra_col.fits')
```
Hope this helps.

**Comment by saimn** [comment] 2017-10-03 16:50
Looks like a real bug :scream: 
It's related to this : https://github.com/astropy/astropy/blob/9fc44c4aeb5740641c472526365bd8e2eb8b41b4/astropy/io/fits/hdu/table.py#L210 
After adding the column the in-memory data is deleted and loaded back from the file but with a wrong dtype (which contains the new columns).

**Comment by saimn** [comment] 2017-10-03 16:55
Ref #3647 (and  #4674 for a similar error with `del_col`)

**Comment by pllim** [comment] 2017-10-03 16:56
The commit listed in https://github.com/astropy/astropy/issues/6649#issuecomment-333907680 is not accurate. That code was originally introduced in #3283.

**Comment by pllim** [comment] 2017-10-03 16:57
@saimn , should we close this as a duplicate of #3647 then?

**Comment by saimn** [comment] 2017-10-03 17:11
Yes, no need to keep this one. And you already gave the workaround, though it can be simplified a bit:
```
fits.BinTableHDU.from_columns(f[1].columns + column)
```
or, as `add_col` both modifies inplace and return a new Coldefs:
```
fits.BinTableHDU.from_columns(f[1].columns.add_col(column))
```
I guess we should remove `add_col` and `del_col`.

**Closed by saimn** 2017-10-03 17:11 UTC
Labels: Affects-release, Bug, Duplicate, io.fits
