### ISSUE TITLE
1.1.1: ImportError on importing wcs and failure of astropy.test()

### ISSUE THREAD

**Issue by astroleo** [astropy/astropy#4467] opened 2016-01-11 13:45 UTC
`from astropy import wcs` fails with the following error on my fresh installation of astropy 1.1.1 on Mac OS X 10.11.2:
```
In [1]: from astropy import wcs
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-3a8fe028b946> in <module>()
----> 1 from astropy import wcs

/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/astropy/wcs/__init__.py in <module>()
     28 try:
     29     # Not guaranteed available at setup time
---> 30     from .wcs import *
     31     from . import utils
     32 except ImportError:

/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/astropy/wcs/wcs.py in <module>()
     48 from . import _docutil as __
     49 try:
---> 50     from . import _wcs
     51 except ImportError:
     52     if not _ASTROPY_SETUP_:

ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/astropy/wcs/_wcs.cpython-35m-darwin.so, 2): Symbol not found: _wcslib_version
  Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/astropy/wcs/_wcs.cpython-35m-darwin.so
  Expected in: flat namespace
 in /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/astropy/wcs/_wcs.cpython-35m-darwin.so
```

I ran into this issue because I executed `astropy.test()` which failed because of this issue (and then apparently got stuck in reporting the error, too):
```
In [2]: astropy.test()
====================================================================== test session starts =======================================================================
platform darwin -- Python 3.5.1 -- py-1.4.30 -- pytest-2.7.3
rootdir: /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/astropy, inifile: 

Running tests with Astropy version 1.1.1.
Running tests in /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/astropy.

Date: 2016-01-11T14:32:49

Platform: Darwin-15.2.0-x86_64-i386-64bit

Executable: /opt/local/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5

Full Python Version: 
3.5.1 (default, Jan 11 2016, 12:45:30) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.10.4
Scipy: 0.16.1
Matplotlib: 1.5.0
h5py: not available
Pandas: 0.17.1

collected 0 items / 1 errors 

============================================================================= ERRORS =============================================================================
_______________________________________________________________________ ERROR collecting  ________________________________________________________________________
_pytest.runner:149: in __init__
    ???
_pytest.main:437: in _memocollect
    ???
_pytest.main:314: in _memoizedcall
    ???
_pytest.main:437: in <lambda>
    ???
_pytest.main:596: in collect
    ???
_pytest.main:611: in _collect
    ???
py._path.common:332: in visit
    ???
py._path.common:378: in gen
    ???
py._path.common:367: in gen
    ???
py._path.common:368: in <listcomp>
    ???
_pytest.main:634: in _recurse
    ???
_pytest.main:162: in __getattr__
    ???
_pytest.config:695: in _getmatchingplugins
    ???
_pytest.config:524: in getconftestmodules
    ???
_pytest.config:548: in importconftest
    ???
E   _pytest.config.ConftestImportFailure: (local('/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/astropy/table/tests/conftest.py'), (<class 'ImportError'>, ImportError('dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/astropy/wcs/_wcs.cpython-35m-darwin.so, 2): Symbol not found: _wcslib_version\n  Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/astropy/wcs/_wcs.cpython-35m-darwin.so\n  Expected in: flat namespace\n in /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/astropy/wcs/_wcs.cpython-35m-darwin.so',), <traceback object at 0x118610c48>))
==================================================================== 1 error in 0.62 seconds =====================================================================
Out[2]: ---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/traitlets/traitlets.py in get(self, obj, cls)
    459         try:
--> 460             value = obj._trait_values[self.name]
    461         except KeyError:

KeyError: 'ipython_display_formatter'

During handling of the above exception, another exception occurred:

DeprecationWarning                        Traceback (most recent call last)
<ipython-input-2-572f3607969c> in <module>()
----> 1 astropy.test()

/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/IPython/core/displayhook.py in __call__(self, result)
    244             self.start_displayhook()
    245             self.write_output_prompt()
--> 246             format_dict, md_dict = self.compute_format_data(result)
    247             self.update_user_ns(result)
    248             self.fill_exec_result(result)

/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/IPython/core/displayhook.py in compute_format_data(self, result)
    150 
    151         """
--> 152         return self.shell.display_formatter.format(result)
    153 
    154     def write_format_data(self, format_dict, md_dict=None):

/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/IPython/core/formatters.py in format(self, obj, include, exclude)
    161         md_dict = {}
    162 
--> 163         if self.ipython_display_formatter(obj):
    164             # object handled itself, don't proceed
    165             return {}, {}

/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/traitlets/traitlets.py in __get__(self, obj, cls)
    486             return self
    487         else:
--> 488             return self.get(obj, cls)
    489 
    490     def set(self, obj, value):

/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/traitlets/traitlets.py in get(self, obj, cls)
    461         except KeyError:
    462             # Check for a dynamic initializer.
--> 463             dynamic_default = self._dynamic_default_callable(obj)
    464             if dynamic_default is None:
    465                 raise TraitError("No default value found for %s trait of %r"

/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/traitlets/traitlets.py in _dynamic_default_callable(self, obj)
    440                 if meth_name in cls.__dict__:
    441                     warn("_[traitname]_default handlers are deprecated: use default"
--> 442                          " decorator instead", DeprecationWarning, stacklevel=2)
    443                     return getattr(obj, meth_name)
    444 

DeprecationWarning: _[traitname]_default handlers are deprecated: use default decorator instead
```

**Comment by astroleo** [comment] 2016-01-11 13:46
I don't think this is connected to other recent wcs-related reports (#4460, #4441)

**Comment by astroleo** [comment] 2016-01-11 13:52
When exiting from the Python session with the failed `astropy.test()` run, there is a warning: `sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/null' mode='w' encoding='UTF-8'>`

**Comment by astroleo** [comment] 2016-01-12 13:05
`from astropy import modeling` also fails due to the same issue.

**Comment by astroleo** [comment] 2016-01-12 13:47
Re-installed astropy 1.1.1 using pip, the problems disappear. Will notify Mac ports package maintainer @astrofrog .

**Comment by astrofrog** [comment] 2016-01-12 14:43
Ah yes I need to update the wcslib package in MacPorts

**Comment by astrofrog** [comment] 2016-01-12 15:25
@astroleo - I upgraded wcslib in MacPorts, but it will take an hour to take effect. So in an hour or so, run:

```
sudo port selfupdate
sudo port upgrade py35-astropy
```

It should automatically update wcslib. If you still see the error after this, let me know.

**Comment by astroleo** [comment] 2016-01-12 20:14
Apparently the update has not yet been registered at macports (https://trac.macports.org/browser/trunk/dports/science/wcslib/Portfile). I'll try again tomorrow night.

**Comment by embray** [comment] 2016-01-12 20:51
FWIW pip always uninstalls a previous version of a package before installing the new one.  I can't speak for anything else.  Since this isn't an issue with the original astropy source distribution I'm closing this.

**Comment by cdeil** [comment] 2016-01-15 08:11
I'm also running into this issue with Macports  `wcslib @4.25.1_0` and `py35-astropy @1.1.1_0`

@astrofrog Looks like your WCSlib update in Macports wasn't committed!?
https://trac.macports.org/log/trunk/dports/science/wcslib/Portfile

**Comment by astrofrog** [comment] 2016-01-15 09:51
@cdeil @astroleo - should be updated now: https://trac.macports.org/changeset/144684/trunk/dports/science/wcslib/Portfile

**Comment by astrofrog** [comment] 2016-01-15 09:51
(you'll need to wait an hour before the update takes effect)

**Comment by astroleo** [comment] 2016-01-15 15:55
Thanks. It works now.

**Comment by cdeil** [comment] 2016-01-15 18:50
Works for me as well. Thanks!

**Comment by embray** [comment] 2016-01-19 16:36
I didn't realize, or forgot, that we have a Macports package for astropy.
On one hand, that's an "upstream package".  But on the other hand, if there are people relying on it, and we (by which I mean @astrofrog) are the ones maintaining it, then should this be written up as part of the release procedure?  Or at least a separate section from the main release procedure for upstream packaging system releases?

**Comment by ShiftyMate** [comment] 2016-01-27 04:24
I'm seeing a similar error, this is after attempting to update things to python 3.5 while maintaining a version of python 2.7. On Mac OSX 10.9.5, astropy used to work on python 2.7. Currently have py27-astropy @1.1.1_1, py35-astropy @1.1.1_1 and py-astropy @0.3_0 (seems to have been installed when I installed py35-gobject3). Also have wcslib @5.12_0 installed.

        from astropy.convolution import convolve, Box1DKernel
       File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/convolution/__init__.py", line 6, in <module>
         from .core import *
       File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/convolution/core.py", line 25, in <module>
         from .utils import (discretize_model, add_kernel_arrays_1D,
       File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/convolution/utils.py", line 7, in <module>
         from ..modeling.core import FittableModel, custom_model
       File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/modeling/__init__.py", line 11, in <module>
         from . import models
       File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/modeling/models.py", line 10, in <module>
         from .core import custom_model
       File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/modeling/core.py", line 48, in <module>
         from ..nddata.utils import add_array, extract_array
       File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/nddata/__init__.py", line 23, in <module>
         from .utils import *
       File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/nddata/utils.py", line 11, in <module>
         from astropy.coordinates import SkyCoord
       File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/coordinates/__init__.py", line 18, in <module>
         from .name_resolve import *
       File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/coordinates/name_resolve.py", line 23, in <module>
         from .sky_coordinate import SkyCoord
       File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/coordinates/sky_coordinate.py", line 14, in <module>
         from ..wcs.utils import skycoord_to_pixel, pixel_to_skycoord
       File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/__init__.py", line 30, in <module>
         from .wcs import *
       File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/wcs.py", line 50, in <module>
         from . import _wcs
     ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/_wcs.so, 2): Symbol not found: _wcslib_version
       Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/_wcs.so
       Expected in: flat namespace
      in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/_wcs.so

**Comment by embray** [comment] 2016-01-27 16:45
Your best bet is to uninstall all old versions first.

**Comment by paulray** [comment] 2016-01-27 22:35
I'm having this problem as well.  I'm using MacPorts and have the following installed:
  py27-astropy @1.1.1_1 (active)
  wcslib @5.12_0 (active)

But, I get this error:
```
In [1]: from astropy.coordinates import EarthLocation
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-01edc5a34980> in <module>()
----> 1 from astropy.coordinates import EarthLocation

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/coordinates/__init__.py in <module>()
     16 from .transformations import *
     17 from .builtin_frames import *
---> 18 from .name_resolve import *
     19 from .matching import *
     20 from .representation import *

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/coordinates/name_resolve.py in <module>()
     21 from ..extern.six.moves import urllib
     22 from .. import units as u
---> 23 from .sky_coordinate import SkyCoord
     24 from ..utils import data
     25 from ..utils import state

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/coordinates/sky_coordinate.py in <module>()
     12 from ..units import Unit, IrreducibleUnit
     13 from .. import units as u
---> 14 from ..wcs.utils import skycoord_to_pixel, pixel_to_skycoord
     15 from ..utils.exceptions import AstropyDeprecationWarning
     16 from ..utils.data_info import MixinInfo

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/__init__.py in <module>()
     28 try:
     29     # Not guaranteed available at setup time
---> 30     from .wcs import *
     31     from . import utils
     32 except ImportError:

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/wcs.py in <module>()
     48 from . import _docutil as __
     49 try:
---> 50     from . import _wcs
     51 except ImportError:
     52     if not _ASTROPY_SETUP_:

ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/_wcs.so, 2): Symbol not found: _wcslib_version
  Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/_wcs.so
  Expected in: flat namespace
 in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/_wcs.so
```
I tried uninstalling all previous versions of wcslib and astropy and re-installing, but no joy.
Anyone have a suggestion for how to get back to working again?

**Comment by cdeil** [comment] 2016-01-28 06:53
@paulray - That's weird. I have the exact same versions with Macports and it works for me. No idea why your `_wcs.so` doesn't contain the `_wcslib_version` symbol as it should.

```
$ port installed py27-astropy
The following ports are currently installed:
  py27-astropy @1.1.1_1 (active)
$ port installed wcslib
The following ports are currently installed:
  wcslib @5.12_0 (active)
$ python2 -c 'import astropy.wcs; print(astropy.wcs)'
<module 'astropy.wcs' from '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/__init__.pyc'>
$ nm /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/_wcs.so | grep _wcslib_version
000000000004022d T _wcslib_version
```
Maybe the `port install py27-astropy` log reveals an issue?
(you could paste it in a https://gist.github.com/ if you want us to have a look).

**Comment by paulray** [comment] 2016-01-28 12:10
@cdeil Thanks for the reply.  I tried rebuilding astropy with -v, but there is no log kept, since the build does not fail.  How does one get port install to not delete the build log after a successful build?

Anyway, here is what I currently get from the same commands you used.  
```
$ port installed py27-astropy
The following ports are currently installed:
  py27-astropy @1.1.1_1 (active)
$ port installed wcslib
The following ports are currently installed:
  wcslib @5.12_0 (active)
$ python2 -c 'import astropy.wcs; print(astropy.wcs)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/__init__.py", line 30, in <module>
    from .wcs import *
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/wcs.py", line 50, in <module>
    from . import _wcs
ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/_wcs.so, 2): Symbol not found: _wcslib_version
  Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/_wcs.so
  Expected in: flat namespace
 in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/_wcs.so
$ nm /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/_wcs.so | grep _wcslib_version
                 U _wcslib_version

```

One thing I notice is that although I rebuilt astropy after uninstalling, the _wcs.so does not have today's date
```
% ls -al /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/_wcs.so
-rwxr-xr-x  1 root  wheel  1007256 Jan 12 10:26 /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/_wcs.so
```
Perhaps it is stale somehow?

Note that on my system, I can build astropy myself from the github source and it does work.  It is something about the MacPorts packaging, I believe.

**Comment by paulray** [comment] 2016-01-28 14:40
@cdeil Well, for now I fixed the problem by copying _wcs.so from the build directory of my development repo of astropy into /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs

**Comment by astroleo** [comment] 2016-01-29 15:52
Hi everyone (Servus @cdeil!), is it really necessary to support astropy for Macports? Wouldn't it be acceptable to ask people using Macports to install pip (using Macports) and then do a `pip install astropy`?

**Comment by paulray** [comment] 2016-01-29 15:58
I've preferred to stick with an all-MacPorts solution.  I don't really know how dependencies interact if you mix installing packages with pip and MacPorts (e.g. say I install astropy with pip, then what happens when I try to install aplpy (which depends on astropy) with port?) .  Normally MacPorts works really well for me, so I hope @astrofrog  will keep maintaining it!

**Comment by weaverba137** [comment] 2016-01-29 16:08
Sorry, but on close reading, I can't determine what the actual solution to this problem was.

**Comment by bsipocz** [comment] 2016-01-29 16:09
@paulray - Does it mean that you've found macports versions for all the python packages you want to use? 

I was less lucky with fink (and my obsolete OS at the time), and thus now have the solution to use fink for everything but python packages, and use pip for all the python packages.

**Comment by paulray** [comment] 2016-01-29 16:20
@bsipocz Mostly I've found what I need in MacPorts (I'm much happier since switching from fink a year or two ago).  For the few I don't find, I just build myself with "python setup.py install --user so they don't pollute the MacPort distro. This seems to work well.

**Comment by paulray** [comment] 2016-01-29 16:24
@weaverba137 I never found the real solution.  In the end, I copied a good copy of _wcs.so into the MacPorts repo, and now it works fine.  What will happen when either wcslib or astropy is updated and rebuilt by MacPorts, I have no idea...

**Comment by weaverba137** [comment] 2016-01-29 16:25
Thanx @paulray.

**Comment by weaverba137** [comment] 2016-01-29 16:39
@paulray's suggestion worked for me as well.  For reference what I did was:

1. Download astropy-1.1.1.tar.gz from PyPI.
2. untar and run python setup.py build (using my MacPorts version of Python).
3. copy build/lib.macosx-10.11-x86_64-2.7/astropy/wcs/_wcs.so to  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs.

**Comment by bsipocz** [comment] 2016-01-29 16:40
@paulray - You can also say ``pip install --user``, so no need to download the source manually, etc.

**Comment by astrofrog** [comment] 2016-01-29 16:42
Copying files into the MacPorts tree is a bad idea - it would be best to uninstall astropy from MacPorts until the issue is resolved, and do what @bsipocz suggested instead.

**Comment by cdeil** [comment] 2016-01-29 18:49
I've also been using Macports for years. It usually works very well, install and update just works. For Python packages that aren't available in Macports I use `pip install --user` or `python setup.py install --user`. Macports handles all the hard-to-build C / C++ / Fortran libraries and provides update functionality much better than just using pip.

Packages installed with `pip install --user` will be found first, i.e. if you `pip install astropy --user` there's no need to copy a `.so` file into the `/opt/local` folder managed by Macports. For Macports to be able to work reliable (e.g. for updates) you should never manually change files in `/opt/local`.

---

I still don't understand what the cause if for the linker error that @paulray is getting.
It's possible to track this down, e.g. by running `port install -v` for verbose output or `port install -d` for debug output  or `port install -s` to force building from source or `port install -b` to force binary install or by posting the files (see `port content py27-astropy`) online for inspection.

But it's not clear that it's worth the effort to do this here, right?

@paulray or anyone else -- if you want to figure this out, please open a new issue in the Macports tracker and link to it from here (there's Macports experts there that will help with build / install issues like this one).

**Comment by MartynBrake** [comment] 2016-02-08 10:44
Hello,
I have installed/uninstalled astropy (2.7 and 3.5) and wcslib several times using MacPorts and pip, but I'm still getting the following error when I import astropy.wcs:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/__init__.py", line 30, in <module>
    from .wcs import *
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/wcs.py", line 50, in <module>
    from . import _wcs
ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/_wcs.so, 2): Symbol not found: _wcslib_version
  Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/_wcs.so
  Expected in: flat namespace
 in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/_wcs.so

Your help on this would be very much appreciated.
Martyn

**Comment by cdeil** [comment] 2016-02-08 10:50
@MartynBrake - I gave some suggestions in https://github.com/astropy/astropy/issues/4467#issuecomment-176907726 on how progress in identifying  the issue could be made. @astrofrog  and I can't reproduce the issue, so someone that is seeing the issue will have to do the grunt work and track this down.

**Comment by astrofrog** [comment] 2016-02-08 10:59
Huh, weird, I managed to reproduce it once and then the error now no longer appears.

**Comment by astrofrog** [comment] 2016-02-08 11:02
I think it happens because the latest astropy binary port must have still been compiled against an older WCSLIB. The error would not happen if the port was installed from source.

**Comment by cdeil** [comment] 2016-02-08 11:06
> I think it happens because the latest astropy binary port must have still been compiled against an older WCSLIB. The error would not happen if the port was installed from source.

How can one check if the installed port was from binary or source?

Maybe just bump Astropy in Macports so that a re-build is forced on the buildbot?

**Comment by astrofrog** [comment] 2016-02-08 11:15
I just bumped the revision. The new port will be available in 1 hour. Since there will not be a binary build yet (takes longer), anyone installing then will not have any issues because it will have to build from source, but we'll have to check again once the binary build is available.

To force a build from source:

```
sudo port install -s py27-astropy
```

@cdeil - I don't know if one can find out retroactively whether a binary build was used.

**Comment by MartynBrake** [comment] 2016-02-08 11:31
Hi,
Many thanks for checking this. I will install from source in an hour.

Martyn

**Comment by MartynBrake** [comment] 2016-02-08 13:05
Hi astrofrog,

Great job, installed from source no problem. importing astropy.wcs not reporting any errors.

Thanks very much,
Martyn

**Comment by embray** [comment] 2016-02-08 15:02
Unless the Astropy project itself is committed to maintaining a MacPorts release I don't think problems with the MacPorts release belong on the Astropy issue tracker itself (unless there's specifically a problem in Astropy that affects upstream releases).

**Comment by astrofrog** [comment] 2016-02-08 17:58
Indeed - there's a MacPorts issue tracker for that. I'll close this and if people run into the issue again, please open an issue at https://trac.macports.org/wiki/Tickets

**Closed by astrofrog** 2016-02-08 17:58 UTC
Labels: installation, Upstream Fix Required

**Comment by bsipocz** [comment] 2016-02-08 18:08
I'm just trying to understand the nomenclature, so I'm either wrong or nitpicking: Isn't it downstream rather than upstream? I always thought that upstream is out dependencies, and down where we're a dependency.

**Comment by astrofrog** [comment] 2016-02-08 18:23
Good point :) I think this is indeed downstream.

**Comment by paulray** [comment] 2016-02-08 20:13
Just for completeness, I'll report that the fix @astrofrog pushed fixed my problem as well, so I no longer have the undesirable situation of a modified library in /opt/local. Thanks!

**Comment by MartynBrake** [comment] 2016-02-09 08:02
To be fair, this was not clearly a macports problem. No error was reported when the port was installed. The only error occurred when wcs was imported. I had assumed it was a fault with astropy, not the port. Thanks for the fix though - great work.
