### ISSUE TITLE
Problem with base classes for coordinate-frame classes needing to have `name`

### ISSUE THREAD

**Issue by ayshih** [astropy/astropy#11096] opened 2020-11-27 06:02 UTC
A recent code change in #11090 is causing errors in SunPy:

https://github.com/astropy/astropy/blob/87df980318eac43850a3add1e5f32286dad9d723/astropy/coordinates/baseframe.py#L289-L297

We have a base class for a frame that does not have a `name` attribute, so the `base.name` access produces an error.  It's easy enough to add a dummy `name` attribute to "fix" this on our side, but presumably the Astropy code needs some protection?

**Comment by adrn** [comment] 2020-11-27 14:27
Ah, yes, an oversight on my part - oops! I'll submit a follow-up PR now, and add a regression test.

**Comment by adrn** [comment] 2020-11-27 14:34
I'm assuming this is `RotatedSunFrame`? I'm a little confused about why it misses the first `if` clause then, if it doesn't have a defined `name` attribute?

**Comment by ayshih** [comment] 2020-11-27 15:32
The error does not occur directly with our `RotatedSunFrame` metaframe, but rather when it tries to dynamically create a coordinate frame.  For example, `RotatedSunFrame` can create `RotatedSunHeliographicStonyhurst`, which has two base classes: the coordinate frame `HeliographicStonyhurst` and the non-coordinate-frame `RotatedSunFrame`.  The problem is that the latter doesn't have the `name` attribute.

Astropy's `SkyOffsetFrame` doesn't have an issue because that metaframe itself subclasses `BaseCoordinateFrame`, so will automatically have `.name`.  I found that I needed `RotatedSunFrame` to *not* subclass `BaseCoordinateFrame` to work properly, although I don't currently recall why.

**Comment by adrn** [comment] 2020-11-28 18:50
Hm. First off, I think that `RotatedSunFrame` should probably just subclass from `BaseCoordinateFrame`. I did some experiments with the Sunpy frames to figure out why that was failing before, and I think I now know why. For `SkyOffsetFrame`, we intentionally do not use the frame-specific representation information from the parent coordinate frame class because we wanted the `SkyOffsetFrame` to have the same (default) component names as the default representation class. So, for example, a `SkyOffsetFrame` with an `ICRS` origin expects `lon, lat, distance` not `ra, dec, distance`. But it looks like that is not how you want `RotatedSunFrame` to work: It looks like your tests expect `RotatedSunFrame` to have the same component names as the `base` frame? So, in the construction of the `Rotated<framecls>`'s in `RotatedSunMeta`, I think you need to copy the `_frame_specific_representation_info` from the frame class into `members`. See sunpy/sunpy#4691 for a possible solution (fingers crossed)

**Comment by ayshih** [comment] 2020-11-29 03:09
Thanks for fixing the bug in Astropy!  Re `RotatedSunFrame`, I'll continue the discussion in SunPy PR.

**Comment by mhvk** [comment] 2020-11-29 15:34
fixed by #11101

**Closed by mhvk** 2020-11-29 15:34 UTC
Labels: Bug, coordinates
