### ISSUE TITLE
Clarify whether Gaussian2D.theta is measured from x or y axis

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3550] opened 2015-02-26 22:37 UTC
The docstring currently says *Rotation angle in radians. The rotation angle increases counterclockwise.* but doesn't say from where it is measured.

**Comment by embray** [comment] 2015-02-26 23:38
Why would it matter?

**Comment by astrofrog** [comment] 2015-02-26 23:43
Because if you are fitting a real astrophysical source, the absolute position angle is meaningful. But PAs in astronomy are often measured from north, not from the positive x-axis as is done in maths.

**Comment by embray** [comment] 2015-02-26 23:47
Oh, that's weird (though understandable). But okay.

**Comment by astrofrog** [comment] 2015-02-27 00:08
Just for reference, http://en.wikipedia.org/wiki/Position_angle

**Comment by embray** [comment] 2015-02-27 17:20
Yeah, I can see why it would be useful to be clear about that, especially when looking at a fit result.

**Comment by vortex-ape** [comment] 2015-03-01 22:22
@astrofrog Does this require a change in the docs only? I've changed it to "Rotation angle in radians. The rotation angle increases counterclockwise, relative to the North Celestial Pole." What else is required?

**Comment by embray** [comment] 2015-03-02 21:29
I don't think that's actually how it's defined.

**Comment by vortex-ape** [comment] 2015-03-02 21:31
@embray - I changed it to ".. from the positive y-axis." after @astrofrog pointed it out.

**Comment by embray** [comment] 2015-03-02 21:39
But that's still arbitrary.  It's trying to attach some particular coordinate frame to this abstract object.

**Comment by embray** [comment] 2015-03-02 21:48
Though if you want to talk about where the angle is measured from it would be the positive x-axis in this case (then going counter-clockwise).

**Comment by vortex-ape** [comment] 2015-03-02 21:54
If we consider the image at the wikipedia page, NCP corresponds to negative y-axis and theta goes counter-clockwise, I'm confused :neutral_face:

**Comment by embray** [comment] 2015-03-02 21:55
I think @astrofrog's point was that what this model actually does is different from his expectation, hence all the more reason for the documentation.

**Comment by vortex-ape** [comment] 2015-03-02 22:03
So, should I change it to positive x-axis?

**Comment by cdeil** [comment] 2015-03-03 12:17
While we're at it, the description of the `x_stddev` and `y_stddev` parameters is slightly incorrect:

> x_stddev : Standard deviation of the Gaussian in x. 

The issue is that this parameter does *not* represent the with in the `x` direction, e.g. for a rotation of 90 deg it represents the width in the `y` direction.

This would be correct:

> x_stddev : Standard deviation of the Gaussian in `x` before rotating by `theta`.

**Comment by cdeil** [comment] 2015-03-03 12:31
I'd like to suggest one more related doc clarification for [Ellipse2D](http://astropy.readthedocs.org/en/latest/api/astropy.modeling.functional_models.Ellipse2D.html)

The `a` and `b` parameters are described as semi-major and semi-minor axis, but actually `b` could very well be larger than `a`.
It's the same as for the [Gaussian2D](http://docs.astropy.org/en/v1.0/api/astropy.modeling.functional_models.Gaussian2D.html), `a` is the width in the `x` direction and `b` in the `y` direction before rotating by `theta`.

I doubt that changing the `Gaussian2D` parameter names is possible now after the 1.0 release (their names are really mis-leading, whereas the `Ellipse2D` names are OK).

So my suggestion is:
- Describe that theta is the angle by which the model is rotated in the counterclockwise direction ... it's not "from the x-axis" or "from the y-axis" ... it's just rotated with respect to any axis.
- Change the wording in the width parameter `a` and `b` and `x_stddev` and `y_stddev` to say "width along x / y axis before rotation by theta".

Then I think it's correct and only adding pictures to the docstrings (similar to the one in the SExtractor manual describing the parameters) would help to make this more easy to understand for users, but it's a bit of work to add such plots.

cc @larrybradley

**Comment by embray** [comment] 2015-03-03 18:26
@cdeil Agreed--also for both Gaussian1D and Gaussian2D I think there still needs to be some clarification about how "width" is represented.  I know some of my colleagues have had confusion about that lately.

**Comment by cdeil** [comment] 2015-03-03 18:57
@embray – For the width parameter I'm not sure how to say it more clearly for [Gaussian1D](http://docs.astropy.org/en/v1.0/api/astropy.modeling.functional_models.Gaussian1D.html) ... it's clearly visible in the formula. Maybe add a sentence how it relates to FWHM like Sherpa [gauss1d](http://cxc.harvard.edu/sherpa/ahelp/gauss1d.html) does?
> The constant f = 2.7725887 = 4log2 relates the full-width at half-maximum F to the Gaussian sigma so that F=sqrt(8log2)*sigma.

For [Gaussian2D](http://docs.astropy.org/en/v1.0/api/astropy.modeling.functional_models.Gaussian2D.html) the formula given is a bit hard to grok ... I find the equivalent formulas given in Sherpa [gauss2d](http://cxc.harvard.edu/sherpa/ahelp/gauss2d.html) or the SExtractor manual easier to grok.

Actually, now that @embray implemented compound models, maybe it would be worth to implement elongated and rotated versions of a few more 2D models, e.g. for my work I now need this for [Ring2D](http://docs.astropy.org/en/v1.0/api/astropy.modeling.functional_models.Ring2D.html). The problem is, it's not possible to do this in a clean way without braking compatibility with Astropy 1.0.

**Comment by embray** [comment] 2015-03-03 22:09
That's basically what I meant.

**Comment by larrybradley** [comment] 2015-03-03 22:49
>Because if you are fitting a real astrophysical source, the absolute position angle is meaningful. But PAs in astronomy are often measured from north, not from the positive x-axis as is done in maths.

@astrofrog  But the `Gaussian2D` model doesn't know anything about WCS -- it is defined purely in pixel space.  I agree with @cdeil's suggestion for improving the docs:  the `a/b` `x/y_stddev` parameters are the widths along the x/y axis before CCW rotation by theta.

Perhaps a better parameterization for `Gaussian2D` would be major stddev and minor stddev.  But to be literal, that would require somehow constraining the minor axis parameter to be always less than the major axis.

@embray Is it possible to constrain allowed parameter values (e.g. `a > b` or even `x_stddev > 0`) when defining the model (not in the fitting)?  I've actually ran into an amusing case where a `Gaussian2D` fit returned negative `x_stddev` and `y_stddev`.

Also, note that one has to be careful when fitting a `Gaussian2D` because in addition to the `theta - 180deg` model degeneracy, there is a degeneracy for swapping `x_stddev` and `y_stddev` with `theta +- 90deg`.  The mathematical model is perfectly correct, but it confuses the interpretation of astronomical sources.  In general you really want the major/minor axes and rotation angle of the major axis (like what `photutils.segmentation.SegmentProperties` returns).

@cdeil I'm thinking about adding a formal `EllipseAnnulus2D` model to `astropy` (for use with `photutils`).  But in the meantime you could simply subtract two `Ellipse2D` models with different radii (I've done that).

**Comment by vortex-ape** [comment] 2015-03-03 23:16
Still a bit unclear about Ellipse2D, maybe we can open another issue for that?

**Comment by larrybradley** [comment] 2015-03-03 23:17
@vortex-ape I'll submit a separate PR for an `EllipseAnnulus2D` model.

**Comment by embray** [comment] 2015-03-04 18:34
> @astrofrog But the Gaussian2D model doesn't know anything about WCS -- it is defined purely in pixel space.

That's sort of what I was saying too.  I think his point was that it should be clarified how it's interpreted in pixel space (again, that assumes a particular orientation of the coordinates as well, but that is already assumed for the rotation direction too).

> @embray Is it possible to constrain allowed parameter values (e.g. a > b or even x_stddev > 0) when defining the model (not in the fitting)? I've actually ran into an amusing case where a Gaussian2D fit returned negative x_stddev and y_stddev.

Sort of, but that still needs some work.  This has been discussed some in #1574 and #1105, and possibly elsewhere.  The idea would be to apply parameter constraints outside just the context of fitting, though there is still some argument over how that should really work.

**Comment by embray** [comment] 2015-03-19 22:14
Anyway, the original issue this was for is fixed in #3550.  Thanks @vortex-ape

**Closed by embray** 2015-03-19 22:14 UTC
Labels: Affects-dev, Docs, Effort-low, modeling, Package-novice
