### ISSUE TITLE
Weird behaviour of values from astropy.table

### ISSUE THREAD

**Issue by iloveastropy** [astropy/astropy#5872] opened 2017-03-10 08:38 UTC
I use the function photutils.detection.find_peaks with subpixel precision. This gives me an astropy table object. I convert the values to float using float(), so that I can use that in the rest of my code. However if I later want to truncate it to an int, I get a wrong result. More specifically, I have the following lines of code:
`a = float(photutils.find_peaks(image, threshold, box_size=15, subpixel=True, npeaks=1)['x_centroid']) // the value in the astropy table is 6.0`
`b = int(a) // b is now 5` 
Why is 6.0 rounded down to 5?

**Comment by mhvk** [comment] 2017-03-10 14:17
My guess is that the position is very close but just below 6.0; maybe try subtracting 6 and see what is left? In general, to avoid things like this, use `round` (even more generally, don't worry about converting to `float` -- it is a float already, just in array form and should behave like one).

**Comment by pllim** [comment] 2017-03-10 16:46
I have no solution to offer but I like your username.

**Comment by bsipocz** [comment] 2019-10-30 19:40
There hasn't been any follow-up on this after the answer above, so I suggest to close it.

Please reopen is the issue is still present and it's turned out to be not a side effect of float rounding.

**Closed by bsipocz** 2019-10-30 19:40 UTC
Labels: table
