### ISSUE TITLE
Enable doctest for io.fits narrative docs

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#6010] opened 2017-05-05 13:44 UTC
``doctest-skip`` is used quite widely in the io.fits docs (e.g. in docs/io/fits/usage/table.rst).  We need to aim to make most of the snippets tested, ideally it would be done easily with the addition of a few small fits files, either to this repo or to data.astropy.org

**Comment by pllim** [comment] 2017-05-05 13:46
That is a good idea. We have had reports before that the examples don't actually work when someone runs them (I think those were fixed though).

**Comment by bsipocz** [comment] 2017-05-05 13:49
@pllim - Yes, #6009 urged me to open this issue, as that PR is not a real solution for the problem. Let alone most of the PRs opened through the docs GH integration are generating more work than they solve when opened to the wrong branch.

**Comment by pllim** [comment] 2017-05-08 12:39
Update: I spoke to @jhunkeler and he might take this on when his other projects calm down a little in a few weeks. Of course, this does not prevent anyone from contributing. First come, first serve.

**Comment by bsipocz** [comment] 2017-05-08 13:49
@pllim - Excellent!

**Comment by saimn** [comment] 2017-05-09 18:15
Good idea, but the issue is that for many examples the FITS files are not available. So one need to change the examples to use other FITS files, possibly from `astropy/io/fits/tests/data`. (For `docs/io/fits/usage/table.rst` it was even worse before https://github.com/astropy/astropy/commit/ddd3a4f386fd7e0703146f9528fe4db498995951 ;), the remaining examples could be easily adapted).

**Comment by pllim** [comment] 2017-05-09 18:16
> the issue is that for many examples the FITS files are not available

Yes, either use existing local data or host the new data at the remote data server and mark it as remote doctest.

**Comment by bsipocz** [comment] 2017-05-09 19:22
@saimn - Yes, exactly that's the plan. Most of those examples are using dummy small fits files, so they could live in this repo, while others could live at data.astropy.org with the rest of the files.

**Comment by saimn** [comment] 2017-10-07 22:06
Fixed by #6664 , thanks @MSeifert04 🎉

**Closed by saimn** 2017-10-07 22:06 UTC
Labels: Docs, Effort-medium, io.fits, Package-novice, testing

**Comment by MSeifert04** [comment] 2017-10-07 22:08
The `verify` documentation is still "doctest-skip" because I didn't understand some of it (and several parts didn't work the way the documentation stated) and Warnings aren't checked by the doctests. 

So I'm not sure if this issue is *fully* adressed.

**Comment by saimn** [comment] 2017-10-07 22:13
Ok, I thought you skipped some examples because testing warnings does not work (?). Not sure if it's realistic to have all examples tested, that's why I closed the issue, but having examples that does not work as documented is more problematic. Maybe it deserves a specific issue ?

**Comment by MSeifert04** [comment] 2017-10-07 22:19
@saimn Yes, a new issue would be fine. I planned to work some more on that this weekend but it shouldn't be forgotten if I don't have time to finish it.
