### ISSUE TITLE
Intermittent segfaults with ascii loader

### ISSUE THREAD

**Issue by ChrisBeaumont** [astropy/astropy#3691] opened 2015-04-16 20:52 UTC
My python interpreter crashes with a segfault about 10% of the time when I try to run

```
In [1]: from astropy.table import Table
In [2]: Table.read('test.csv', format='ascii')
```

when called using [this file](https://gist.github.com/ChrisBeaumont/8c39956f3e78483c647c)

the original file is about 10x larger, and it crashes everytime. I haven't been able to track down much more information than that. It doesn't crash if I don't set format='ascii'

**Comment by mdboom** [comment] 2015-04-16 21:05
Hmm.  Valgrind shows nothing amiss.  Just to confirm -- it this with git master, or some other released version of astropy?  What platform are you on, and what version of Python and Numpy?

**Comment by mdboom** [comment] 2015-04-16 21:08
There have been some recent fixes in this area: #3545, #3546, probably others...

**Comment by ChrisBeaumont** [comment] 2015-04-16 21:10
This was on conda-installed astropy 1.0.1, py 2.7.9, numpy 1.9.2, OSX. I'll check if this exists on master

**Comment by mdboom** [comment] 2015-04-16 21:14
FWIW, I can't reproduce this on astropy 1.0.1, python 2.7.9, numpy 1.9.2 on Linux (all from source).  I don't know if OSX or anaconda matters.

Do you have valgrind on your OSX box?  The output of the following may be helpful:

```
valgrind --tool=memcheck --log-file=output.vg `which python` script.py
```

(where script.py contains the two lines at the top of this post).

**Comment by ChrisBeaumont** [comment] 2015-04-16 21:19
On master, I don't hit the segfault on the truncated gist file, but I still hit it on the full dataset. I don't have valgrind and it doesn't look like homebrew provides it for Yosemite :( . I'll try to find another way to install it and post the report here if I succeed.

**Comment by mdboom** [comment] 2015-04-16 21:21
Something that may also be helpful is a gdb traceback (though that's less helpful for figuring out where things *first* went wrong).

```
gdb `which python`
> run script.py
... segfaults ...
> bt
```

**Comment by ChrisBeaumont** [comment] 2015-04-16 23:14
gdb traceback is below. Interestingly I installed valgrind but so far, the program doesn't crash or finish under valgrind

```
#0  0x000000010775f3cc in htmlParseCharData () from /Users/cbeaumont/anaconda/lib/libxml2.2.dylib
#1  0x000000010776652c in htmlParseTryOrFinish ()
   from /Users/cbeaumont/anaconda/lib/libxml2.2.dylib
#2  0x0000000107766b92 in htmlParseChunk () from /Users/cbeaumont/anaconda/lib/libxml2.2.dylib
#3  0x0000000107592461 in __pyx_f_4lxml_5etree_11_FeedParser_close ()
   from /Users/cbeaumont/anaconda/lib/python2.7/site-packages/lxml/etree.so
#4  0x0000000107592ed3 in __pyx_pw_4lxml_5etree_11_FeedParser_3close ()
   from /Users/cbeaumont/anaconda/lib/python2.7/site-packages/lxml/etree.so
#5  0x00000001000c3f96 in PyEval_EvalFrameEx ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#6  0x00000001000c541b in PyEval_EvalFrameEx ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#7  0x00000001000c541b in PyEval_EvalFrameEx ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#8  0x00000001000c6063 in PyEval_EvalCodeEx ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#9  0x000000010003e4d0 in function_call () from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#10 0x000000010000cab2 in PyObject_Call () from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#11 0x000000010001dfed in instancemethod_call ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#12 0x000000010000cab2 in PyObject_Call () from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#13 0x0000000100079588 in slot_tp_init () from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#14 0x0000000100076405 in type_call () from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#15 0x000000010000cab2 in PyObject_Call () from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#16 0x00000001000c0add in PyEval_EvalFrameEx ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#17 0x00000001000c6063 in PyEval_EvalCodeEx ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#18 0x00000001000c40d0 in PyEval_EvalFrameEx ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#19 0x00000001000c6063 in PyEval_EvalCodeEx ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#20 0x00000001000c40d0 in PyEval_EvalFrameEx ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#21 0x00000001000c6063 in PyEval_EvalCodeEx ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#22 0x000000010003e4d0 in function_call () from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#23 0x000000010000cab2 in PyObject_Call () from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#24 0x000000010001dfed in instancemethod_call ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#25 0x000000010000cab2 in PyObject_Call () from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#26 0x00000001000c0add in PyEval_EvalFrameEx ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#27 0x00000001000c6063 in PyEval_EvalCodeEx ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#28 0x00000001000c40d0 in PyEval_EvalFrameEx ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#29 0x00000001000c6063 in PyEval_EvalCodeEx ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#30 0x00000001000c40d0 in PyEval_EvalFrameEx ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#31 0x00000001000c6063 in PyEval_EvalCodeEx ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#32 0x000000010003e4d0 in function_call () from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#33 0x000000010000cab2 in PyObject_Call () from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#34 0x00000001000bedca in PyEval_EvalFrameEx ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#35 0x00000001000c6063 in PyEval_EvalCodeEx ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#36 0x000000010003e4d0 in function_call () from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#37 0x000000010000cab2 in PyObject_Call () from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
---Type <return> to continue, or q <return> to quit---
#38 0x00000001000bedca in PyEval_EvalFrameEx ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#39 0x00000001000c6063 in PyEval_EvalCodeEx ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#40 0x000000010003e4d0 in function_call () from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#41 0x000000010000cab2 in PyObject_Call () from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#42 0x00000001000bedca in PyEval_EvalFrameEx ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#43 0x00000001000c6063 in PyEval_EvalCodeEx ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#44 0x00000001000c40d0 in PyEval_EvalFrameEx ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#45 0x00000001000c6063 in PyEval_EvalCodeEx ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#46 0x00000001000c6186 in PyEval_EvalCode () from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#47 0x00000001000eb43e in PyRun_FileExFlags ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#48 0x00000001000eb6da in PyRun_SimpleFileExFlags ()
   from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#49 0x000000010010272d in Py_Main () from /Users/cbeaumont/anaconda/lib/libpython2.7.dylib
#50 0x0000000100000f54 in start ()
```

**Comment by taldcroft** [comment] 2015-04-17 02:27
That's interesting, it looks like it is crashing in the HTML reader which uses libxml.  This is consistent with what you've said:

- With the `format='ascii'` option it goes through the full generic guess list, which will end up trying HTML before comma-separated.
- With no `ascii` option then it uses the `.csv` suffix to determine it should call the `Csv` parser, which then succeeds.

OT, about guessing again, this makes me wonder if the `format` keyword could be a list of acceptable formats.  Right now it is either *all* possible formats or just one.

**Comment by mdboom** [comment] 2015-04-17 02:31
Interesting that the traceback is in lxml.  libxml has notoriously
difficult memory semantics, and the lxml wrappers that superceded the
standard libxml bindings were supposed to address some of that.  I didn't
even realize `io.ascii` was using lxml...

Do you know which version of lxml you have?  That may explain why I can't
reproduce...

**Comment by mdboom** [comment] 2015-04-17 02:46
And to make things even farther out of our control, astropy only uses lxml
through BeautifulSoup.  (I was wondering what it would take to replace lxml
with our own expat-based pull parser that we already have, and
unfortunately the answer would involve hacking BeautifulSoup...)

**Comment by embray** [comment] 2015-04-17 14:20
This sounds almost exactly like #3611 and #3280, both of which have remained mysteries.

**Comment by embray** [comment] 2015-04-17 14:38
Just to confirm, looking at @tomr-stargazer's report in #3611, it's crashing in the exact same place.

**Comment by embray** [comment] 2015-04-17 14:50
Well I haven't found any obvious reports about anything known or fixed in `htmlParseCharData`, but it sounds like by passing these big ASCII blobs through it we're inadvertently fuzz testing it :D

**Comment by ChrisBeaumont** [comment] 2015-04-17 16:24
> Do you know which version of lxml you have?

3.4.0

I finally waited for valgrind to finish, which it did without crashing. Maybe there's a race condition somewhere that disappears when you add valgrind's overhead?

**Comment by mdboom** [comment] 2015-04-17 17:48
It's fairly common that code that breaks without valgrind will not crash with valgrind, because it changes how memory is allocated.  However, did valgrind produce any warnings in its log file about "invalid writes" while doing so (even without crashing)?

**Comment by ChrisBeaumont** [comment] 2015-04-17 18:19
No invalid writes, but a bunch of invalid reads (not sure if that's relevant)

Here's the report
https://gist.github.com/ChrisBeaumont/529e54dd5567e4196ff0

**Comment by eteq** [comment] 2015-05-08 14:16
FWIW, I just tried this about 20 times on a self-compiled astropy 1.0 on Yosemite, and I can't reproduce it. I do have a vague memory of encountering segfaults a few times on other tables, though.

**Comment by taldcroft** [comment] 2015-05-08 14:49
@eteq - do you have the same versions?
python version=3.4.0, shared library is libxml2.2.dylib

**Comment by ChrisBeaumont** [comment] 2015-05-08 16:29
@eteq  What if you make the table bigger and read it twice? This makes the crash more consistent for me:

```
 python -c "from astropy.table import Table; import pandas as pd; df = pd.read_csv('error.csv'); pd.concat([df] * 10, ignore_index=True).to_csv('test2.csv'); Table.read('test2.csv', format='ascii'); Table.read('test2.csv', format='ascii')"
Segmentation fault: 11
```

**Comment by adrn** [comment] 2015-05-08 17:02
Just saw this issue -- I have been experiencing the same problems / behavior. If I try to load 2 CSV tables in the same IPython cell using `ascii.read()`, it consistently kills the kernel. If I split in to 2 cells, they run fine. I'm happy to share the CSV files and a demo notebook if that helps.

Python version 2.7.9, Astropy 1.0.2

**Comment by taldcroft** [comment] 2015-05-08 18:58
And I confirmed that this does fix the problem.

**Comment by eteq** [comment] 2015-05-09 16:10
@ChrisBeaumont @taldcroft  - I'm trying with conda py 3.4.3, libxml 2.9, and I don't see it at all - I made the file 25x bigger by copying the non-header lines, and I tried twice, and it still doesn't segfault.  (Ironic to be frustrated by this when I *know* I've seen it before and it was frustrating *then*...)

Anyway, it sounds like @taldcroft's solution is the way to go regardless.

**Comment by taldcroft** [comment] 2015-05-09 18:33
@eteq - maybe you can try py 2.7.9 which is what @adrn and I were using (and @ChrisBeaumont at one point).

**Comment by astrofrog** [comment] 2015-05-09 21:09
I can't reproduce the issue either, with Python 2.7.9 or 3.4.3, and libxml 2.9. I don't think I can downgrade to libxml 2.2 in conda.

**Comment by embray** [comment] 2015-05-12 20:33
Since the issue is related to libxml (and particularly a version shipped with some versions of Anaconda) I still think it's a bit much to disable a feature entirely.  We should be able to check the libxml version (in fact it is available in `lxml.etree`, though we could do this without requiring lxml too).

**Comment by astrofrog** [comment] 2015-05-12 21:00
I think that most users should be reading tables with ``Table.read`` instead of ``ascii.read``. If they use ``Table.read``, we currently go directly to the HTML reader if the extension is ``html`` (or at least, I think we do!). So removing HTML from the ``ascii.read`` guesses shouldn't affect users who are using ``Table.read``.

**Comment by embray** [comment] 2015-05-12 21:04
In that case I'm less bothered by it.

**Comment by taldcroft** [comment] 2015-05-12 21:43
> We should be able to check the libxml version ...

I think it would be confusing to have a command like `Table.read('file.html', format='ascii')` (which enables guessing) work for some users and not work for others, depending on the version of a library they probably don't even know they have.  Since this bug is out there and relatively common, I think its better to bite the bullet and disable guessing for HTML.

**Comment by embray** [comment] 2015-05-12 21:56
For my own edification, could someone who can reproduce this problem run (in Anaconda)
```python
import lxml.etree
print(lxml.etree.LIBXML_VERSION)
```
?

**Comment by ChrisBeaumont** [comment] 2015-05-12 22:26
(2, 9, 0)

**Comment by eteq** [comment] 2015-05-14 06:44
I also can't reproduce on py 2.7.9 with libxml 2.9.0, @taldcroft (with a 10x size of the sample table)...

@taldcroft - the problem with disabling it completely now that I think about it, is that it introduces a potentially major backwards compatibility problem.  So anyone who counted on HTML guessing  who upgrade to e.g. 1.0.3 will suddenly have their code not work anymore.  But if we go with @embray's suggestion of trying to find exactly when it fails and giving a warning for that, anyone who previously relied on that instead got segfaults, so they won't be surprised by code previously working now failing.

**Comment by taldcroft** [comment] 2015-05-14 12:30
@eteq - I agree that disabling HTML entirely would have to wait for 1.1.

The segfault occurs when attempting to read a big CSV file with the HTML reader (via libxml) during the guessing process.  Maybe I'm missing your logic, but the only warning that would be useful is "Warning: skipping the HTML reader during guessing because you have libxml 2.9.0 installed".  But this would show up commonly for non-HTML files and this would be annoying and confusing to most users.

So I think the choice is to disable guessing of HTML for all users (bigger footprint but consistent), or disable guessing of HTML for users with libxml 2.9.0 (smaller footprint but platform-dependent behavior).  These choices guarantee never getting a segfault.  The footprint for change can be reduced further by having the HTML reader immediately reject any file that doesn't look like HTML, *but* this would still allow segfaults still for the unusual case of large CSV files that have some HTML-table-like content.

Another option is the long-standing issue to improve guessing heuristics so a valid table file that is not an HTML table never gets to the HTML reader.  For the most part the current guessing strategy is pretty robust, but it is insanely inefficient.

BTW, has this bug in libxml been reported upstream?

Finally, sooner rather than later we should add a known issue for this.

**Comment by embray** [comment] 2015-05-14 14:49
I need to see if I can figure out exactly how to reproduce this.  I've built libxml 2.9 locally and tried running the sample error.csv through its HTML parser and did not get a segfault.  Though it's still not clear to me if this is something that happens deterministically or what.

**Comment by embray** [comment] 2015-05-14 15:05
So it looks like libxml is only used if the lxml module is available (if not, BeautifulSoup has its own built-in fallbacks) so that's a start.  Using libxml straight up doesn't crash on this file, but looking at the HTMLParser class in lxml it looks like it does some slightly complicated things.  The problem might exist somewhere between lxml and libxml.

**Comment by embray** [comment] 2015-05-14 16:26
Okay, when I try to reproduce this, when io.ascii goes into beautifulsoup, the attempt to parse the "HTML" file just results in a UnicodeDecodeError:
```python
>>> soup = BeautifulSoup('\n'.join(lines))
ERROR: UnicodeDecodeError: 'utf8' codec can't decode byte 0x88 in position 0: invalid start byte [unknown]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/internal/1/root/home/embray/.virtualenvs/lxml/lib/python2.7/site-packages/bs4/__init__.py", line 172, in __init__
    self._feed()
  File "/internal/1/root/home/embray/.virtualenvs/lxml/lib/python2.7/site-packages/bs4/__init__.py", line 185, in _feed
    self.builder.feed(self.markup)
  File "/internal/1/root/home/embray/.virtualenvs/lxml/lib/python2.7/site-packages/bs4/builder/_lxml.py", line 175, in feed
    self.parser.close()
  File "parser.pxi", line 1322, in lxml.etree._FeedParser.close (src/lxml/lxml.etree.c:111100)
  File "parser.pxi", line 1352, in lxml.etree._FeedParser.close (src/lxml/lxml.etree.c:110937)
  File "parsertarget.pxi", line 142, in lxml.etree._TargetParserContext._handleParseResult (src/lxml/lxml.etree.c:126528)
  File "parsertarget.pxi", line 130, in lxml.etree._TargetParserContext._handleParseResult (src/lxml/lxml.etree.c:126294)
  File "lxml.etree.pyx", line 324, in lxml.etree._ExceptionContext._raise_if_stored (src/lxml/lxml.etree.c:10737)
  File "saxparser.pxi", line 499, in lxml.etree._handleSaxData (src/lxml/lxml.etree.c:120816)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x88 in position 0: invalid start byte
```
which doesn't make a whole lot of sense either.

We have the same version of *libxml*, but I wonder if I'm using a different version of *lxml* and/or BS?

**Comment by embray** [comment] 2015-05-14 16:27
@ChrisBeaumont Could you also check what `lxml.etree.__version__` is?  Thanks.

**Comment by tomr-stargazer** [comment] 2015-05-14 16:40
Since I was tagged above as reporting a similar issue, here's my version numbers (in case that's helpful - otherwise, sorry for the spam). My install is on a Mac OS X, via anaconda.

```python
In [1]: import lxml.etree
In [2]: print(lxml.etree.LIBXML_VERSION)
(2, 9, 0)

In [3]: print(lxml.etree.__version__)
3.3.1
```

**Comment by adrn** [comment] 2015-05-14 16:55
And since I have been experiencing this as well, here are my version:

    In [1]: import lxml.etree
    In [2]: print(lxml.etree.LIBXML_VERSION)
    (2, 9, 0)
    In [3]: print(lxml.etree.__version__)
    3.2.3

**Comment by embray** [comment] 2015-05-14 16:59
Thanks, that might help narrow it down more.

**Comment by embray** [comment] 2015-05-14 17:10
Well this is interesting--with lxml 3.2.3 I'm not getting a segfault, unfortunately, but I am getting that same `UnicodeDecodeError` as above.  However, it occurs at different locations, sometimes with different invalid bytes (that shouldn't be appearing in the data at all), and sometimes it just works fine.  I'm not sure why I don't get a segfault, but at least it's something.  Are you all using Anaconda, and if so do you know what version/platform?

**Comment by tomr-stargazer** [comment] 2015-05-14 17:12
```
Python 2.7.9 |Anaconda 1.9.1 (x86_64)| (default, Dec 15 2014, 10:37:34)
Type "copyright", "credits" or "license" for more information.

IPython 2.4.1 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
Using matplotlib backend: MacOSX
```

**Comment by adrn** [comment] 2015-05-14 17:16
```
Python 2.7.9 |Anaconda 1.8.0 (x86_64)| (default, Dec 15 2014, 10:37:34)
Type "copyright", "credits" or "license" for more information.

IPython 3.1.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
```

**Comment by ChrisBeaumont** [comment] 2015-05-14 18:10
> Could you also check what lxml.etree.__version__ is?

3.4.2

Python 3.4.3, Anaconda 2.2.0, IPython 3.0.0

**Comment by bsipocz** [comment] 2019-03-18 05:15
I suspect/hope this has gone away in the past years, too? @taldcroft @eteq  what do you think, can we close?

**Comment by taldcroft** [comment] 2019-03-18 10:23
> Another option is the long-standing issue to improve guessing heuristics so a valid table file that is not an HTML table never gets to the HTML reader. 

This was done, and I think it would prevent this issue.  In any case we have not gotten new reports in the mean time.

**Closed by taldcroft** 2019-03-18 10:23 UTC
Labels: Bug, io.ascii
