### ISSUE TITLE
Astropy Exmples not working

### ISSUE THREAD

**Issue by antiseptic2017** [astropy/astropy#6478] opened 2017-08-25 04:45 UTC
Hi

The examples from this web site are just not working, I have tried deleting astropy and clean install several times and this simple program is just not working.

This is just one of many examples I am trying to have up and running.

Using python 3.5.2 on Ubuntu 16.04

Thanks

http://docs.astropy.org/en/stable/time/

from astropy.time import Time

t = t.sidereal_time('apparent', 'greenwich')  

print (t)

Traceback (most recent call last):
  File "/home/ladyhawk/Desktop/astro.py", line 3, in <module>
    t.sidereal_time('apparent', 'greenwich')
NameError: name 't' is not defined

**Comment by adrn** [comment] 2017-08-25 13:25
You have to define the time array `t` before calling `.sidereal_time()`, as is done earlier in the examples page. To get it working:

```python
>>> from astropy.time import Time
>>> times = ['1999-01-01T00:00:00.123456789', '2010-01-01T00:00:00']
>>> t = Time(times, format='isot', scale='utc')
>>> t = t.sidereal_time('apparent', 'greenwich')
>>> print(t)
```

**Comment by pllim** [comment] 2017-08-25 13:38
This is a duplicate of #6467. Closing this one.

**Closed by pllim** 2017-08-25 13:38 UTC
