### ISSUE TITLE
FITS file corruption via fits.open(mode='update')

### ISSUE THREAD

**Issue by mkelley** [astropy/astropy#5754] opened 2017-01-30 13:11 UTC
Hello,

I typically use `mode='update'` for modifying FITS data and headers with great success, but I have found a file where this fails.  After opening for an update and adding 7 new keywords to the header, the updated file is double the original size and the data is corrupted:

```
from astropy.io import fits

with fits.open('update-corruption.fits', mode='readonly') as hdu:
    print('Image mean = ', hdu[0].data.mean())

print('Add keywords')
with fits.open('update-corruption.fits', mode='update') as hdu:
    for i in range(7):
        hdu[0].header['kw{:02d}'.format(i)] = 'foo'

with fits.open('update-corruption.fits', mode='readonly') as hdu:
    print('Image mean = ', hdu[0].data.mean())
```

Saving the above as corrupt.py and executing:

```
$ cp original-data.fits update-corruption.fits
$ ls -l original-data.fits update-corruption.fits 
-rw-rw-r-- 1 msk msk 75542400 Jan 30 07:42 original-data.fits
-rw-rw-r-- 1 msk msk 75542400 Jan 30 07:54 update-corruption.fits
$ python3 corrupt.py
Image mean =  123.848496001
Add keywords
Verify data
WARNING: VerifyWarning: Error validating header for HDU #1 (note: Astropy uses zero-based indexing).
    'ascii' codec can't decode byte 0x80 in position 2: ordinal not in range(128)
There may be extra bytes after the last HDU or the file is corrupted. [astropy.io.fits.hdu.hdulist]
Image mean =  0.0
$ ls -l original-data.fits update-corruption.fits 
-rw-rw-r-- 1 msk msk  75542400 Jan 30 07:42 original-data.fits
-rw-rw-r-- 1 msk msk 151067520 Jan 30 07:57 update-corruption.fits
```

I checked the documentation and the FAQ, but did not find any information on update mode limitations.

As a workaround, I can open the file with `readonly` and overwrite it after making the same changes.  If having this file helps: [original-data.fits](http://www.astro.umd.edu/~msk/outgoing/original-data.fits).

Thanks for the help,
Mike Kelley

**Comment by mkelley** [comment] 2017-01-30 13:19
Ah, this fails using astropy version 1.3.

**Comment by pllim** [comment] 2017-01-30 15:30
Sounds similar to #5396, maybe? But I cannot reproduce your error using the latest dev. I used your data and script codes. My Python version is 3.5.2.

```
$ cp original-data.fits update-corruption.fits 
$ python3 corrupt.py 
Image mean =  123.848496001
Add keywords
Image mean =  123.848496001
```

**Comment by mkelley** [comment] 2017-01-30 16:11
Hmm, I just installed 2.0.dev17767 (after setup.py clean) with Python 3.5.2 and I still get a corrupted file.  I've run the astropy tests on the io.fits module without any failures (516 passed, 3 skipped).  Is there some other way I can diagnose this?

```
Platform: Linux-4.4.0-53-generic-x86_64-with-Ubuntu-16.04-xenial
Full Python Version: 
3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609]
Numpy: 1.11.0
Scipy: 0.17.0
Matplotlib: 1.5.1
h5py: 2.6.0
Pandas: 0.17.1
Cython: 0.23.4
```

**Comment by pllim** [comment] 2017-01-30 16:27
Does it still happen when you enter your codes line-by-line in an interactive Python session? What about on another machine? There is my setup:

```
Platform: Linux-2.6.32-642.6.2.el6.x86_64-x86_64-with-redhat-6.8-Santiago
Full Python Version: 
3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.11.2
Scipy: 0.18.1
Matplotlib: 1.5.3
h5py: 2.6.0
Pandas: 0.19.0
Cython: 0.24

=== 516 passed, 3 skipped in 29.39 seconds ===
```

**Comment by mkelley** [comment] 2017-01-30 17:28
Same corruption with an interactive session.  But now I've tried it on another machine, and the update works with both astropy 1.2.1 and latest dev.  I can add 100 new header keywords, and the file is correctly written.  On the alternate system:

```
platform linux -- Python 3.5.2, pytest-2.8.3, py-1.4.30, pluggy-0.3.1
Running tests with Astropy version 1.2.1.
Platform: Linux-3.10.0-327.28.3.el7.x86_64-x86_64-with-redhat-7.3-Maipo

Full Python Version: 
3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.11.1
Scipy: 0.18.1
Matplotlib: 1.5.3
h5py: not available
Pandas: not available
========= 491 passed, 3 skipped, 1 pytest-warnings in 24.90 seconds =========
```

The gcc version is different between my system, and the two systems that work (yours and my alternate).  I have gcc 4.9 installed, so I tried compiling astropy with gcc 4.9 via `CC=gcc-4.9 python3 setup.py install`.  The resulting library shows it was somehow used:

```
$ strings -a _compiler.cpython-35m-x86_64-linux-gnu.so |grep GCC
GCC version 4.9.3
GCC: (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
GCC: (Ubuntu 4.9.3-13ubuntu2) 4.9.3
```

But the corruption still remains.

Finally, I tried building astropy using my system's cfitsio libraries, but that also corrupts the file.

**Comment by pllim** [comment] 2017-01-30 17:37
So, this is either caused by Ubuntu or GCC 5. Your last command listed both GCC versions, so there could be some weird confusion going on too in regards of C library linking. Unfortunately, Ubuntu and GCC are beyond my expertise. For now, if you only need to update the header one time, you can update it in the other machine that works, and copy/move the updated file back to this Ubuntu machine?

**Comment by mkelley** [comment] 2017-01-30 18:25
My workaround is to open the file in `readonly` mode, modify the header, and overwrite the file, which is fine.

Just now I created a clean Python 3.5 virtual environment, and installed astropy, etc. via pip.  The FITS file is updated without any problems.  But that probably isn't surprising since astropy wasn't compiled on my machine.

Thanks for the help so far!

**Comment by pllim** [comment] 2017-02-01 15:26
@mkelley , since this is pretty specific to your machine setup and you found a fix/workaround, I am closing this issue.

**Closed by pllim** 2017-02-01 15:26 UTC
Labels: Affects-release, Bug, io.fits
