### ISSUE TITLE
wrong line terminator in csv and ecsv on windows

### ISSUE THREAD

**Issue by p3trus** [astropy/astropy#5299] opened 2016-09-02 10:26 UTC
On windows, writing a csv or ecsv results in a `'\r\r\n'` line terminator similar to this [problem](http://stackoverflow.com/questions/3348460/csv-file-written-with-python-has-blank-lines-between-each-row)

**Comment by pllim** [comment] 2017-06-15 12:41
Duplicate of #5126, so closing this one as @bsipocz suggested.

**Closed by pllim** 2017-06-15 12:41 UTC
Labels: Affects-release, Bug, Duplicate, io.ascii, Windows
