### ISSUE TITLE
Astropy: SkyCoord.from_name() - module 'urllib.request' has no attribute 'HTTPSHandler' (pyiodide)

### ISSUE THREAD

**Issue by strangeguyfromastrangecountry** [astropy/astropy#15744] opened 2023-12-15 05:51 UTC
### Description

I'm new to Python and just started learning this. I'm trying to figure out how to work with Astropy on jupyter.org for searching for an object name in online databases. I wrote version of the code, but this give an error: 
`AttributeError: module 'urllib.request' has no attribute 'HTTPSHandler'`

It is curious that if we return the list of attributes of the `urllib.request` in alphabetical order, then the `HTTPSHandler ` attribute will not really be found there, but the `HTTPHandler` attribute  will be there.

But the `from_name` instruction uses the `HTTPSHandler`.

A similar problem was discussed here: [AttributeError: module 'urllib.request' has no attribute 'HTTPSHandler' when using astropy](https://github.com/koenvo/pyodide-http/issues/33) But none of the methods suggested there worked.

### Expected behavior

The result should be like this:
`<SkyCoord (ICRS): (ra, dec) in deg    (88.79293899, 7.40706399)>`

### How to Reproduce

**To reproduce the error:**
1. Go to [jupyter.org](https://jupyter.org/try-jupyter/notebooks/?path=Untitled2.ipynb)
2. Choose _Python (Pyodide)_
3. Insert and Run `# Code 1` (presented below)

```
# Code 1
import micropip
await micropip.install("ssl")
from astropy.coordinates import SkyCoord
crab = SkyCoord.from_name('M1')
print(crab)
```

**To check and compare attributes:**
1. Go to [jupyter.org](https://jupyter.org/try-jupyter/notebooks/?path=Untitled2.ipynb)
2. Choose _Python (Pyodide)_
3. Insert and Run `# Code 2` (presented below)

```
# Code 2
import urllib
dir(urllib.request)
```

### Versions

Emscripten-3.1.45-wasm32-32bit
Python 3.11.3 (main, Sep 25 2023, 20:45:01)
astropy 5.3.2
FireFox Browser 120.0.1 (64-bit)

**Comment by ManonMarchand** [comment] 2023-12-15 09:11
Hi, thanks for opening this here.

What I tried: 
- the astropy version on pyodide does correctly use the https link to Sesame
- on the latest jupyter lite release [here](https://jupyterlite.readthedocs.io/en/latest/) the bug is still reproducible
- looking at the network window after executing the snippet, there are no calls to Sesame so the bug happens before the request is done

**Comment by strangeguyfromastrangecountry** [comment] 2023-12-15 13:32
> Hi, thanks for opening this here.
> 
> What I tried:
> 
>     * the astropy version on pyodide does correctly use the https link to Sesame
> 
>     * on the latest jupyter lite release [here](https://jupyterlite.readthedocs.io/en/latest/) the bug is still reproducible
> 
>     * looking at the network window after executing the snippet, there are no calls to Sesame so the bug happens before the request is done

Hi, thank you! So the thing is that `urllib.request` contains `HTTPHandler `attribute, but for some reason does not contain the `HTTPSHandler ` that SkyCoord uses. Could one of the attributes not connect as a result of some bug? And is it possible to change the attribute used from HTTPS to HTTP?

**Comment by pllim** [comment] 2023-12-15 14:15
We don't control the pyiodide stuff here. Shouldn't this be submitted as a pyiodide help call or something?

**Comment by pllim** [comment] 2023-12-15 14:17
Perhaps @jobovy has ideas since they worked on #12904 ?

**Comment by strangeguyfromastrangecountry** [comment] 2023-12-15 15:27
> We don't control the pyiodide stuff here. Shouldn't this be submitted as a pyiodide help call or something?

Perhaps yes, perhaps no. Nobody knows for sure what is causing this problem.

**Comment by pllim** [comment] 2023-12-15 15:37
This is for sure not a problem in CI or users not using pyiodide, so would be nice if someone from pyiodide can chime in here.

**Comment by strangeguyfromastrangecountry** [comment] 2023-12-15 15:38
> This is for sure not a problem in CI or users not using pyiodide, so would be nice if someone from pyiodide can chime in here.

Yes, but for now I will study the topic you referred to. I'll try to find some tips there.

**Comment by jobovy** [comment] 2023-12-15 15:39
I can take a closer look later, but it seems this is related to https://github.com/koenvo/pyodide-http/issues/33. Basically, I think you need to do something like
```python
await micropip.install(["ssl","pyodide-http>=0.2.1"])
import pyodide_http
pyodide_http.patch_all()
# Currently need to reload these http and urllib libraries (see koenvo/pyodide-http/issues/33)
from importlib import reload
import http.client
import urllib.request
reload(http.client)
reload(urllib.request)
```

**Comment by ManonMarchand** [comment] 2023-12-15 16:22
Thanks! Doing this returns a different error:

```
NameResolveError: All Sesame queries failed. Unable to retrieve coordinates. See errors per URL below: 
 https://cds.unistra.fr/cgi-bin/nph-sesame/A?M1: [Errno 23] Host is unreachable
http://vizier.cfa.harvard.edu/viz-bin/nph-sesame/A?M1: [Errno 23] Host is unreachable
```

But I know for sure that Sesame is not down. I tracked the logs upstream and there is no request coming to us. 

The bug can be reproduced without Astropy nor Sesame. After @jobovy snippet, do:

```python
req = urllib.request.Request('https://github.com')
r = urllib.request.urlopen(req) 
```

and you'll get the same message.

**Comment by jobovy** [comment] 2023-12-15 21:20
When I run the code that I mentioned [above](https://github.com/astropy/astropy/issues/15744#issuecomment-1858077834) and then run the code at the start of this issue again, I get an error in the console about Mixed Content
```
pyodide.asm.js:9 Mixed Content: The page at 'https://jupyterlite.github.io/demo/extensions/@jupyterlite/pyodide-kernel-extension/static/568.621d55d3f28fca39d88b.js?v=621d55d3f28fca39d88b' 
was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://cds.unistra.fr:443/'. 
This request has been blocked; this endpoint must be available over WSS.
```
This might be the source of the problem, but I can't figure out why or where the URL is turned into a websocket and I can't get my browser to allow Mixed Content to see whether this is the full issue. We should raise this again at koenvo/pyodide-http/issues/33, because obviously the fix there stopped working for some reason.

**Comment by jobovy** [comment] 2023-12-15 21:29
Note that this seems to be specific to using `urllib` to do the request. In `galpy` I have a similar `from_name` function that queries Simbad using `astroquery`, which uses `requests` in the backend, and that still works fine., e.g., in the try.jupyter.org notebook, do
```python
import micropip
await micropip.install(["ssl","pyodide-http>=0.2.1"])
import pyodide_http
pyodide_http.patch_all()
# Currently need to reload these http and urllib libraries (see koenvo/pyodide-http/issues/33)
from importlib import reload
import http.client
import urllib.request
reload(http.client)
reload(urllib.request)

import micropip
await micropip.install('astroquery')
from galpy.orbit import Orbit
Orbit.from_name('Large Magellanic Cloud').ra()
```
(note that `galpy` gets 6D coordinates, so M1 itself doesn't work in `galpy`). 

`astroquery` doesn't have a `Sesame` interface, presumably to avoid duplication with `astropy`, but if there's a bigger issue here that can't be resolved, one option could be to implement the name resolution using a `requests`-based approach. 

By the way, progress is being made in making `urllib3` and `requests` run directly in the `pyodide` without the `pyodide-http` patching, so that might also lead to a natural resolution eventually.

**Comment by strangeguyfromastrangecountry** [comment] 2023-12-18 04:41
> Hi humans 👋 - this issue was labeled as **Close?** approximately 15 hours ago. If you think this issue should not be closed, a maintainer should remove the **Close?** label - otherwise, I will close this issue in 7 days.
> 
> _If you believe I commented on this issue incorrectly, please report this [here](https://github.com/pllim/action-astropy-stalebot/issues)_

don't close it yet

**Comment by ManonMarchand** [comment] 2023-12-18 08:19
Yes, please. I can reproduce that it works just fine with `requests`.

**Comment by pllim** [comment] 2023-12-18 14:32
I don't see any action item for this repo. If I understood correctly, the fix is somewhere in pyiodide land?

**Comment by jobovy** [comment] 2023-12-18 16:49
I think it would be good to keep this open for a little while to track whether an upstream fix actually happens, but otherwise close it in a while if nothing happens (I don't know whether `astropy` has a stale bot that could do this). 

Obviously, `astropy` doesn't officially support `pyodide`, so there's no need to fix this in the code, even if it could (but switching the relevant code to use `requests` is probably non-trivial and there's no reason to think that `requests` couldn't be affected by a similar bug in the future).

Because. try.jupyter.org has largely switched to using `jupyterlite` (and, thus, `pyodide` for running Python code), people will run into these types of issues more and more, so `astropy` might want to consider supporting some functionality in `pyodide` in the medium-term. I should note that I added a bunch of the `astropy` test suite to `pyodide`'s test suite, so compatibility is tested on every `pyodide` change, but I mainly focused on pure calculation tests. Code that makes network requests is always going to be tricky to run in `pyodide` and `jupyterlite`, so I wouldn't suggest trying to support that in the medium-term. Hopefully that will all get sorted out when Python itself adopts the browser as a main environment to support.

**Comment by pllim** [comment] 2023-12-18 16:58
> has a stale bot that could do this

Yes but https://github.com/astropy/astropy/issues/15744#issuecomment-1859540267 . Current stale policy to close issue is 7 days.

I guess this can be kept open for now as long as we all agree that the fix is upstream. Thanks!

**Comment by strangeguyfromastrangecountry** [comment] 2023-12-19 06:48
> > has a stale bot that could do this
> 
> Yes but [#15744 (comment)](https://github.com/astropy/astropy/issues/15744#issuecomment-1859540267) . Current stale policy to close issue is 7 days.
> 
> I guess this can be kept open for now as long as we all agree that the fix is upstream. Thanks!

I agree. Now I'm working with the code options that were suggested by @jobovy in this topic. Reloading some modules and working with a different database temporarily is a good idea.

**Comment by ManonMarchand** [comment] 2023-12-19 10:55
FYI, Sesame (called `from_name` in astropy) queries Simbad, Vizier, and NED. So you can emulate by interfacing the three.

**Comment by Prithwis-2023** [comment] 2024-01-06 10:24
For some reason, I am facing the same issue, tried the implementations that all of you have attempted to narrow down the issue, but in vain! Any thoughts on its fix?

**Comment by tactipus** [comment] 2024-01-06 14:45
Did we ever figure out whether the problem is in another castle (so to speak)?

**Comment by Prithwis-2023** [comment] 2024-01-06 14:48
> Did we ever figure out whether the problem is in another castle (so to speak)?

I guess since its an open issue, we didn't!

**Comment by pllim** [comment] 2024-01-06 19:05
The fix should be upstream. See https://github.com/astropy/astropy/issues/15744#issuecomment-1861032474 and the labels. Thanks.

**Comment by ManonMarchand** [comment] 2024-01-08 10:09
Hi there, if you're in pure pyodide it works with pyodide_http (see snippet [here](https://github.com/koenvo/pyodide-http/issues/33#issuecomment-1880700871)) but for Jupyterlite it's less clear.

**Comment by jobovy** [comment] 2024-01-17 15:19
(Cross-posted from https://github.com/koenvo/pyodide-http/issues/33 with some additional comments)

I found that the issue in `jupyterlite` is that `ssl` wasn't installed when `http.client` and `urllib.request` are first imported (these are likely imported in their `IPython` setup) and for some reason reloading them doesn't fix the issue in `jupyterlite` as it does in pure `pyodide`. So I fixed the issue by just installing `ssl` before anything else is installed in the initialization of `jupyterlite`'s `pyodide-kernel`, which is enough to fix this issue here: https://github.com/jupyterlite/pyodide-kernel/pull/79. 

A new version of `pyodide-kernel` was released that includes this fix, which you can check here: https://jupyterlite-pyodide-kernel.readthedocs.io/en/latest/_static/ (of course, you still need the `pyodide-http` patching, so try this example:
```python
>>> import micropip
>>> await micropip.install(["ssl", "pyodide-http>=0.2.1", "astropy"])
>>> from astropy.coordinates import SkyCoord
>>> import pyodide_http; pyodide_http.patch_all()
>>> SkyCoord.from_name('NGC3256')
```
). 

[try.jupyter.org](try.jupyter.org) will need a new release as well for this to be propagated through all the way there, but that should happen soon and I think this issue here can therefore be closed now.

**Comment by ManonMarchand** [comment] 2024-01-17 16:25
Wonderful! Thanks a lot @jobovy!

**Comment by pllim** [comment] 2024-01-17 16:57
Thank you very much for the update! Closing as requested.

**Closed by pllim** 2024-01-17 16:57 UTC
Labels: Upstream Fix Required, Bug, coordinates
