### ISSUE TITLE
Quantity.info.indices is None when read from FITS

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#9435] opened 2019-10-22 17:38 UTC
### Description

When a Quantity is round-tripped through FITS it comes back with no `info.indices` attribute defined.

```
In [1]: from astropy import units as u                                                                                                                                 

In [2]: from astropy.table import QTable   

In [22]: qt = QTable([[1,2] * u.m])

In [23]: qt['col0'].info.indices
Out[23]: []

In [24]: qt.write('junk.fits', overwrite=True)

In [25]: qt2 = QTable.read('junk.fits')

In [26]: qt2.indices
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-26-e8cd296b92da> in <module>()
----> 1 qt2.indices

~/git/astropy/astropy/table/table.py in indices(self)
    692         lst = []
    693         for column in self.columns.values():
--> 694             for index in column.info.indices:
    695                 if sum([index is x for x in lst]) == 0:  # ensure uniqueness
    696                     lst.append(index)

TypeError: 'NoneType' object is not iterable

In [27]: print(qt2['col0'].info.indices)
None
```

### Expected behavior

Expect no exception for `qt2.indices` and to get an empty list `[]` for `qt2['col0'].info.indices`.

### System Details

Darwin-17.7.0-x86_64-i386-64bit
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 13:42:17) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy 1.16.5
astropy 4.0.dev26195

**Comment by bsipocz** [comment] 2019-10-22 18:44
I can't see this on v3.2.2, so added `Affects-dev` for now.

**Comment by pllim** [comment] 2019-10-22 20:34
Hmm, someone should `git bisect` this before release.

**Comment by bsipocz** [comment] 2019-10-22 21:07
I'll try to do it today.

**Comment by bsipocz** [comment] 2019-10-22 21:49
Now I'm not sure any more. If I go to the v3.2.2 tag, it also fails, while in a different environment, the installed v3.2.2 works. In theory the python  and numpy versions are the same now.

**Comment by bsipocz** [comment] 2019-10-22 22:25
this is a very weird one, I have one setup  where this issue doesn't  even show on the latest master, and that was the env I've tested when  said that  I don't see this for the release.

**Comment by bsipocz** [comment] 2019-10-22 22:52
OK, so this is totally dependent on pyyaml (which is not installed in the env where the test passes), which is retrospectively not that surprising.

**Comment by pllim** [comment] 2019-10-22 23:45
Interesting... Let me see if I can reproduce this...

**Comment by pllim** [comment] 2019-10-23 00:16
Okay, here is what I see with `astropy` 3.2.2, `numpy` 1.16.3, and Python 3.7.1 (on Windows 10 no less!).

**A. With pyyaml 5.1**

I see the reported behavior above.

**B. Without pyyaml 5.1**

When I jump straight to doing `QTable.read('junk.fits')`, where `junk.fits` is from **A**, I get an error that is:

```
ImportError: `import yaml` failed, PyYAML package is required for serializing mixin columns
```

When I run the entire example, it roundtrips without problem.

**Conclusion**

@bsipocz is correct that this depends on `pyyaml`. `pyyaml` does something to the serialization in mixin column, causing FITS failure to roundtrip.

**Comment by pllim** [comment] 2019-10-23 00:20
Here is the EXT 1 header from the file generated **without** `pyyaml`:
```
XTENSION= 'BINTABLE'           / binary table extension
BITPIX  =                    8 / array data type
NAXIS   =                    2 / number of array dimensions
NAXIS1  =                    8 / length of dimension 1
NAXIS2  =                    2 / length of dimension 2
PCOUNT  =                    0 / number of group parameters
GCOUNT  =                    1 / number of groups
TFIELDS =                    1 / number of table fields
TTYPE1  = 'col0    '
TFORM1  = 'D       '
TUNIT1  = 'm       '
```
Here is the EXT 1 header from the file generated **with** `pyyaml`:
```
XTENSION= 'BINTABLE'           / binary table extension
BITPIX  =                    8 / array data type
NAXIS   =                    2 / number of array dimensions
NAXIS1  =                    8 / length of dimension 1
NAXIS2  =                    2 / length of dimension 2
PCOUNT  =                    0 / number of group parameters
GCOUNT  =                    1 / number of groups
TFIELDS =                    1 / number of table fields
TTYPE1  = 'col0    '
TFORM1  = 'D       '
TUNIT1  = 'm       '
COMMENT --BEGIN-ASTROPY-SERIALIZED-COLUMNS--
COMMENT datatype:
COMMENT - {name: col0, unit: m, datatype: float64}
COMMENT meta:
COMMENT   __serialized_columns__:
COMMENT     col0:
COMMENT       __class__: astropy.units.quantity.Quantity
COMMENT       unit: !astropy.units.Unit {unit: m}
COMMENT       value: !astropy.table.SerializedColumn {name: col0}
COMMENT --END-ASTROPY-SERIALIZED-COLUMNS--
```

**Comment by pllim** [comment] 2019-10-24 15:43
Alright, since this is not affects dev anymore, I am removing the milestone.

**Comment by bsipocz** [comment] 2021-03-12 19:57
I get an empty list for both cases (no exception), so would consider closing this issue. Please reopen if you still see it on the current HEAD.

**Closed by bsipocz** 2021-03-12 19:57 UTC
Labels: Bug, table
