### ISSUE TITLE
Test failure in io.ascii's fast reader

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#9528] opened 2019-11-05 02:04 UTC
This test was added in #9082, cc @dhomeier.

```
❯ pytest astropy/io/ascii/tests/test_c_reader.py      
/home/simon/dev/astropy/astropy/conftest.py:47: MatplotlibDeprecationWarning: 
The examples.directory rcparam was deprecated in Matplotlib 3.0 and will be removed in 3.2. In the future, examples will be found relative to the 'datapath' directory.
  matplotlibrc_cache.update(matplotlib.rcParams)
===================================== test session starts =====================================
platform linux -- Python 3.7.4, pytest-5.2.2, py-1.8.0, pluggy-0.13.0

Running tests with Astropy version 4.0.dev26777.
Running tests in astropy/io/ascii/tests/test_c_reader.py.

Date: 2019-11-04T22:58:24

Platform: Linux-5.3.8-arch1-1-x86_64-with-arch

Executable: /home/simon/.pyenv/versions/3.7.4/bin/python3.7

Full Python Version: 
3.7.4 (default, Aug  5 2019, 19:45:04) 
[GCC 9.1.0]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Package versions: 
Numpy: 1.17.3
Scipy: 1.3.1
Matplotlib: 3.1.1
h5py: 2.10.0
Pandas: 0.25.2
Cython: 0.29.13
Scikit-image: 0.16.2
asdf: not available
astropy-helpers: 3.1rc1

Using Astropy options: remote_data: none.

rootdir: /home/simon/dev/astropy, inifile: setup.cfg
plugins: remotedata-0.3.2, arraydiff-0.3, doctestplus-0.4.0, openfiles-0.4.0, astropy-header-0.1.1, cov-2.8.1
collected 136 items                                                                           

astropy/io/ascii/tests/test_c_reader.py .............................x................. [ 34%]
.............x.......x.x.................ssssss..ssss..ss..FFssssss.................... [ 98%]
..                                                                                      [100%]

========================================== FAILURES ===========================================
______________________ test_data_at_range_limit[False-fast_reader2-True] ______________________

parallel = False, fast_reader = {'parallel': False, 'use_fast_converter': True}, guess = True

    @pytest.mark.parametrize("guess", [True, False])
    # fast_reader configurations: False| 'use_fast_converter'=False|True
    @pytest.mark.parametrize('fast_reader', [False, dict(use_fast_converter=False),
                                             dict(use_fast_converter=True)])
    @pytest.mark.parametrize("parallel", [False, True])
    def test_data_at_range_limit(parallel, fast_reader, guess):
        """
        Test parsing of fixed-format float64 numbers near range limits
        (|~4.94e-324 to 1.7977e+308|) - within limit for full precision
        (|~2.5e-307| for strtod C parser, factor 10 better for fast_converter)
        exact numbers shall be returned, beyond that an Overflow warning raised.
        Input of exactly 0.0 must not raise an OverflowError.
        """
        # Python reader and strtod() are expected to return precise results
        rtol = 1.e-30
    
        # Update fast_reader dict; adapt relative precision for fast_converter
        if fast_reader:
            fast_reader['parallel'] = parallel
            if fast_reader.get('use_fast_converter'):
                rtol = 1.e-15
            elif np.iinfo(np.int).dtype == np.dtype(np.int32):
                # On 32bit the standard C parser (strtod) returns strings for these
                pytest.xfail("C parser cannot handle float64 on 32bit systems")
    
        if parallel:
            if not fast_reader:
                pytest.skip("Multiprocessing only available in fast reader")
            elif TRAVIS:
                pytest.xfail("Multiprocessing can sometimes fail on Travis CI")
    
        # Test very long fixed-format strings (to strtod range limit w/o Overflow)
        for D in 99, 202, 305:
            t = ascii.read(StringIO(99*'0' + '.' + D*'0' + '1'), format='no_header',
                           guess=guess, fast_reader=fast_reader)
            assert_almost_equal(t['col1'][0], 10.**-(D+1), rtol=rtol, atol=1.e-324)
        for D in 99, 202, 308:
            t = ascii.read(StringIO('1' + D*'0' + '.0'), format='no_header',
                           guess=guess, fast_reader=fast_reader)
            assert_almost_equal(t['col1'][0], 10.**D, rtol=rtol, atol=1.e-324)
    
        # 0.0 is always exact (no Overflow warning)!
        for s in '0.0', '0.0e+0', 399*'0'+'.'+365*'0':
            with pytest.warns(None) as w:
                t = ascii.read(StringIO(s), format='no_header',
                               guess=guess, fast_reader=fast_reader)
            assert t['col1'][0] == 0.0
>           assert len(w) == 0
E           assert 1 == 0
E            +  where 1 = len(WarningsChecker(record=True))

astropy/io/ascii/tests/test_c_reader.py:1152: AssertionError
_____________________ test_data_at_range_limit[False-fast_reader2-False] ______________________

parallel = False, fast_reader = {'parallel': False, 'use_fast_converter': True}, guess = False

    @pytest.mark.parametrize("guess", [True, False])
    # fast_reader configurations: False| 'use_fast_converter'=False|True
    @pytest.mark.parametrize('fast_reader', [False, dict(use_fast_converter=False),
                                             dict(use_fast_converter=True)])
    @pytest.mark.parametrize("parallel", [False, True])
    def test_data_at_range_limit(parallel, fast_reader, guess):
        """
        Test parsing of fixed-format float64 numbers near range limits
        (|~4.94e-324 to 1.7977e+308|) - within limit for full precision
        (|~2.5e-307| for strtod C parser, factor 10 better for fast_converter)
        exact numbers shall be returned, beyond that an Overflow warning raised.
        Input of exactly 0.0 must not raise an OverflowError.
        """
        # Python reader and strtod() are expected to return precise results
        rtol = 1.e-30
    
        # Update fast_reader dict; adapt relative precision for fast_converter
        if fast_reader:
            fast_reader['parallel'] = parallel
            if fast_reader.get('use_fast_converter'):
                rtol = 1.e-15
            elif np.iinfo(np.int).dtype == np.dtype(np.int32):
                # On 32bit the standard C parser (strtod) returns strings for these
                pytest.xfail("C parser cannot handle float64 on 32bit systems")
    
        if parallel:
            if not fast_reader:
                pytest.skip("Multiprocessing only available in fast reader")
            elif TRAVIS:
                pytest.xfail("Multiprocessing can sometimes fail on Travis CI")
    
        # Test very long fixed-format strings (to strtod range limit w/o Overflow)
        for D in 99, 202, 305:
            t = ascii.read(StringIO(99*'0' + '.' + D*'0' + '1'), format='no_header',
                           guess=guess, fast_reader=fast_reader)
            assert_almost_equal(t['col1'][0], 10.**-(D+1), rtol=rtol, atol=1.e-324)
        for D in 99, 202, 308:
            t = ascii.read(StringIO('1' + D*'0' + '.0'), format='no_header',
                           guess=guess, fast_reader=fast_reader)
            assert_almost_equal(t['col1'][0], 10.**D, rtol=rtol, atol=1.e-324)
    
        # 0.0 is always exact (no Overflow warning)!
        for s in '0.0', '0.0e+0', 399*'0'+'.'+365*'0':
            with pytest.warns(None) as w:
                t = ascii.read(StringIO(s), format='no_header',
                               guess=guess, fast_reader=fast_reader)
            assert t['col1'][0] == 0.0
>           assert len(w) == 0
E           assert 1 == 0
E            +  where 1 = len(WarningsChecker(record=True))

astropy/io/ascii/tests/test_c_reader.py:1152: AssertionError
==================== 2 failed, 112 passed, 18 skipped, 4 xfailed in 9.13s =====================
```
One of the catched warning gives this:
```
(Pdb++) str(w.list[0])
"{message : AstropyWarning('OverflowError converting to FloatType in column col1, possibly resulting in degraded precision.'), category : 'AstropyWarning', filename : '/home/simon/dev/astropy/astropy/io/ascii/fastbasic.py', lineno : 128, line : None}"
```
It could be some locale issue as it happened in the past, but running with `LANG=C` gives the same error.

**Comment by dhomeier** [comment] 2019-11-05 15:33
> One of the catched warning gives this:
> 
> ```
> (Pdb++) str(w.list[0])
> "{message : AstropyWarning('OverflowError converting to FloatType in column col1, possibly resulting in degraded precision.'), category : 'AstropyWarning', filename : '/home/simon/dev/astropy/astropy/io/ascii/fastbasic.py', lineno : 128, line : None}"
> ```
> 
> It could be some locale issue as it happened in the past, but running with `LANG=C` gives the same error.

Anything else should be even more confusing, since the text is parsed inside a `locale='C'` context:
```
        with _set_locale('C'):
            data, comments = self.engine.read(try_int, try_float, try_string)
```
I cannot reproduce this on OS X; rebuilt everything with gcc 9.2 but no difference to the clang build.
Can you find out it for which of the values of `s` the warning popped up (first)?
Will try to investigate this on a Linux system later.

But the last change involving `fastbasic.py` or anything else in `io.ascii` would seem to be #9471, which still passed all tests on Travis and CircleCI...

**Comment by dhomeier** [comment] 2019-11-05 16:11
> But the last change involving `fastbasic.py` or anything else in `io.ascii` would seem to be #9471, which still passed all tests on Travis and CircleCI...

OK, but I cannot tell for sure if #9471 had been rebased to master after #9082 was merged...

**Comment by pllim** [comment] 2019-11-05 16:55
How is this not caught by the CI in `master`?

**Closed** 2019-11-05 17:38 UTC
Labels: Bug, io.ascii, testing
