### ISSUE TITLE
Time allows addition with unit less quantities

### ISSUE THREAD

**Issue by maxnoe** [astropy/astropy#12887] opened 2022-02-23 20:51 UTC
I was debugging an issue with times when I found that something I assumed had a unit and in fact did not.

It turns out, that `Time` objects allow addition with unit less numbers, that are than interpreted as a timedelta in days, probably because of the inheritance from array and the basis being JD.

```
In [1]: from astropy.time import Time

In [2]: Time("2020-01-01T00:00") + 5
Out[2]: <Time object: scale='utc' format='isot' value=2020-01-06T00:00:00.000>

```

I feel like this shouldn't be allowed

**Comment by mhvk** [comment] 2022-02-24 10:56
@maxnoe - somewhat of a duplicate of #10355, though that was for comparisons. The underlying reason is that for interaction with other objects, the code simply tries `TimeDelta(other)` and happily continues as long as that works. I agree that this is probably too generous, but in https://github.com/astropy/astropy/issues/10355#issuecomment-634638830 @taldcroft argued that it might not be worth fixing since there is code in the wild that makes use of this.

**Comment by maxnoe** [comment] 2022-02-24 11:00
There is also (as I found) code in the wild that has bugs because of this.

**Comment by taldcroft** [comment] 2022-02-24 11:18
> There is also (as I found) code in the wild that has bugs because of this.

Unfortunately, at this point with almost a decade of this behavior as legacy, I think it's going to take a much stronger argument to justify an API change that is certain to break code (e.g. a bunch of Chandra operations code depends on this feature). See #12841 for a fine example of the consequences of a well-meaning effort to enforce correctness which ended up breaking downstream code.

@mhvk - I'd propose to close both this issue and #10355 with a `wont-fix` label.

**Comment by maxnoe** [comment] 2022-02-24 11:26
I disagree. Legacy workloads can keep using the major versions they were developed against. That should not be a reason not to improve the situation for all other users of the software!

**Comment by taldcroft** [comment] 2022-02-24 11:55
In practice that doesn't really work for two reasons. 

First, there is undoubtedly single-user scientist code out there which relies of this "feature". In other words, not everyone chooses to use units. On-purpose or accidentally, people will have found that adding float days just works and then baked that into their code. Another way to think about this is being liberal on input (Postel's law), in the way that the FITS parser accepts all sorts of non-FITS compliant file inputs.

Second, production environments cannot stay fixed at a particular LTS version forever.  For packages like astropy the LTS version only gets bugfixes for 1.5 years, so institutions really need to update at that timescale.

The bigger point is simply that core astropy is expected to be extremely stable at this point. An API change like you propose is a big break, and so it can be only be considered if there is a correspondingly large benefit. I don't see a benefit that can justify all the complaints we will get from people about their code breaking and astropy being not stable. If we were having this discussion 9 years ago it would be a completely different story.

**Comment by maxnoe** [comment] 2022-02-24 12:46
> First, there is undoubtedly single-user scientist code out there which relies of this "feature". In other words, not everyone chooses to use units. 

Any single scientist user code might be broken by another of the breaking changes that by definition are made when releasing a new major version. 

> Another way to think about this is being liberal on input (Postel's law), in the way that the FITS parser accepts all sorts of non-FITS compliant file inputs.

That is something completely different. Having an input file parse successfully or not vs. having `Time('2021-10-01 20:00:00') + 5` doing *something*. Look at that code. Ask users
* Whether it should work
* What the answer will be
I bet that most will say 1) it should not work and b) will not guess that the 5 is interpreted as 5 days.

I am not arguing that this change should be made immediately and I do recognise it is a breaking change.

But we just released a new LTS so time is quite far until the next. So we can now for 5.1 introduce a deprecation warning if `TimeDelta` has not unit specified, which I gather is the underlying cause here.

It is not even documented, that the default format for time is `JD`:

```
format : str, optional
    Format of input value(s)
```

And when listing the supported formats, `jd` is not the first in that list:

```
In [10]: TimeDelta.FORMATS
Out[10]: 
OrderedDict([('sec', astropy.time.formats.TimeDeltaSec),
             ('jd', astropy.time.formats.TimeDeltaJD),
             ('datetime', astropy.time.formats.TimeDeltaDatetime)])
```

there is absolutely no indication anywhere in the astropy documentation that this should work and what the expected result is.

It also breaks with the behavior of `Time`. `TimeDelta` has two numeric formats: sec and jd. So inputing just a number without format (which has default `None`) is not unique. But instead of raising an error like `Time` does:

```
In [14]: Time(5)
...
ValueError: No time format was given, and the input is not unique
```

`TimeDelta` just chooses `jd`:

```
In [15]: TimeDelta(5)
Out[15]: <TimeDelta object: scale='None' format='jd' value=5.0>
```


So I would propose to add a warning when doing this. The point where this is removed can be discussed. Maybe never. But at least the warning should be raised and then legacy software can choose to either update or ignore the warning.

**Comment by taldcroft** [comment] 2022-02-24 13:51
OK, I'm happy enough to introduce a new warning (subclass of `DeprecationWarning`) that is easy enough to disable. At the same time update the docs to document clearly the existing behavior. @maxnoe - can you do the PR?

**Comment by eerovaher** [comment] 2022-02-24 14:01
Is a new warning class needed or would the already existing `AstropyPendingDeprecationWarning` be good enough?

**Comment by maxnoe** [comment] 2022-02-24 14:14
PR is here: https://github.com/astropy/astropy/pull/12888

**Comment by taldcroft** [comment] 2022-02-24 14:24
@eerovaher - see https://github.com/astropy/astropy/pull/12888#discussion_r813925654

**Closed** 2022-02-25 15:42 UTC
Labels: time, Bug, Duplicate
