### ISSUE TITLE
Some tests run much slower with coverage testing on Python 3 compared to Python 2

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4826] opened 2016-05-01 16:22 UTC
If I run just the astropy.units tests with:

```
python setup.py test -P units --coverage
```

On Python 2 it runs in:

```
============= 2739 passed, 15 skipped, 3 xfailed in 115.31 seconds =============
```

while on Python 3 it runs in:

```
============= 1658 passed, 3 xfailed in 335.95 seconds =============
```

Note that Python 3 runs fewer tests (because it doesn't do the tests with unicode_literals) and even then it's 3 times slower. I'm not sure if the bottleneck is in our functionality, or the coverage testing itself.

**Comment by astrofrog** [comment] 2016-05-02 17:45
Once this is solved, we can enable coverage testing in ``.travis.yml`` for Python 3.x

**Comment by pllim** [comment] 2016-05-02 17:45
Just to re-iterate something I said in #4822 -- Is it slow in *all* Python 3.x or just 3.4?

**Comment by pllim** [comment] 2016-05-02 17:48
@astrofrog said slow in both 3.4 and 3.5.

**Comment by astrofrog** [comment] 2016-05-02 17:49
Yep - the above timings were done on Python 3.5

**Comment by astrofrog** [comment] 2016-05-02 17:51
I think the next thing to look at would be to try and output the times for all the tests and see if there's a specific kind of test that is slow.

**Comment by astrofrog** [comment] 2016-05-02 18:37
On my laptop, the tests take about 15 minutes to run in Python 3.5 with coverage enabled:

```
=============== 1 failed, 7589 passed, 92 skipped, 37 xfailed in 931.81 seconds ===============
```

**Comment by pllim** [comment] 2016-05-02 19:28
Just want to be clear -- So, when coverage is *not* enabled, the testing times are comparable between Python 2 and 3?

**Comment by astrofrog** [comment] 2016-05-02 20:52
### With no coverage:

**Python 2**

```
10101 passed, 426 skipped, 45 xfailed in 281.13 seconds
```

**Python 3**

```
1 failed, 7589 passed, 92 skipped, 37 xfailed in 206.43 seconds
```

### With coverage:

**Python 2**

```
10101 passed, 426 skipped, 45 xfailed in 374.28 seconds
```

**Python 3**

```
1 failed, 7589 passed, 92 skipped, 37 xfailed in 931.81 seconds
```

**Comment by pllim** [comment] 2016-05-02 20:55
I wonder if this is a `pytest` problem rather than an Astropy problem. If only there is a convenient way to also run coverage in both Python 2 and 3 for something that is not related to Astropy and see if it has the same timing difference. Hmm...

**Comment by astrofrog** [comment] 2016-05-02 20:56
@pllim - yes, I think it would good to do that test

**Comment by astrofrog** [comment] 2016-05-02 21:14
I don't think it's a pytest issue. Results for glue:

### Without coverage:

** Python 2 **

```
2 failed, 1666 passed, 43 skipped, 1 xfailed in 82.43 seconds
```

*** Python 3 ***

```
1707 passed, 4 skipped, 1 xfailed in 104.01 seconds
```

### With coverage:

** Python 2 **

```
2 failed, 1666 passed, 43 skipped, 1 xfailed in 98.55 seconds
```

*** Python 3 ***

```
1707 passed, 4 skipped, 1 xfailed in 98.75 seconds
```

**Comment by pllim** [comment] 2016-05-02 21:15
:scream: @astrofrog , thanks for confirming!

**Comment by astrofrog** [comment] 2016-05-02 22:02
Here are some of the worst offenders:

```
                                                                            before   after    ratio
astropy/units/tests/test_units.py::test_compose_cgs_to_si::[41]           0.024508  1.823121 74.388083
astropy/units/tests/test_units.py::test_compose_cgs_to_si::[34]           0.013608  1.601368 117.674463
astropy/units/tests/test_units.py::test_compose_cgs_to_si::[28]           0.012572  1.807674 143.785174
astropy/units/tests/test_units.py::test_compose_cgs_to_si::[11]           0.012421  1.835840 147.799762
astropy/units/tests/test_units.py::test_compose_cgs_to_si::[43]           0.012080  1.873355 155.082738
astropy/units/tests/test_units.py::test_compose_cgs_to_si::[42]           0.011663  1.848627 158.497608
astropy/units/tests/test_units.py::test_compose_cgs_to_si::[0]            0.024875  4.003081 160.929906
astropy/units/tests/test_units.py::test_compose_cgs_to_si::[27]           0.011474  1.877320 163.609803
astropy/units/tests/test_units.py::test_compose_cgs_to_si::[13]           0.024590  4.048595 164.647049
astropy/units/tests/test_units.py::test_compose_si_to_cgs::[25]           0.004337  0.856900 197.586476
astropy/units/tests/test_units.py::test_compose_cgs_to_si::[23]           0.008799  1.814737 206.236161
astropy/units/tests/test_units.py::test_compose_cgs_to_si::[33]           0.012993  3.553029 273.455126
astropy/units/tests/test_format.py::test_roundtrip_ogip::[46]             0.003167  1.148633 362.643282
astropy/units/tests/test_format.py::test_roundtrip_ogip::[21]             0.001228  1.122911 914.175272
astropy/units/tests/test_format.py::test_roundtrip_ogip::[1]              0.001049  1.143710 1090.738745
astropy/units/tests/test_format.py::test_roundtrip_ogip::[25]             0.000924  1.120119 1212.105263
astropy/units/tests/test_format.py::test_roundtrip_ogip::[9]              0.001155  2.314179 2003.378741
astropy/units/tests/test_format.py::test_roundtrip_ogip::[49]             0.001093  2.282247 2087.317706
astropy/units/tests/test_format.py::test_roundtrip_ogip::[38]             0.001083  3.353577 3095.493618
astropy/units/tests/test_format.py::test_roundtrip_ogip::[29]             0.001103  3.540889 3209.761184
astropy/units/tests/test_format.py::test_roundtrip_ogip::[22]             0.000908  3.380517 3723.454832
astropy/units/tests/test_format.py::test_roundtrip_ogip::[32]             0.001072  4.545379 4240.369440
astropy/units/tests/test_format.py::test_roundtrip_ogip::[14]             0.001052  4.602006 4375.926547
astropy/units/tests/test_format.py::test_roundtrip_ogip::[10]             0.001020  4.632741 4543.166706
astropy/units/tests/test_format.py::test_roundtrip_ogip::[24]             0.001059  6.849442 6467.501801
```

**Comment by pllim** [comment] 2016-05-03 14:48
@astrofrog , thanks! But what do the numbers in square brackets mean?

**Comment by astrofrog** [comment] 2016-05-03 15:15
@pllim - these are parametrized tests, so it's just the index of which exact test was being run.

**Comment by pllim** [comment] 2016-05-03 15:46
@astrofrog , how do you get pytest to print out the run times with coverage? Inserting print statement in the test function seems insufficient. My pytest-fu is not strong enough...

**Comment by astrofrog** [comment] 2016-05-03 15:47
@pllim - I ran the tests with the ``--json=report.json`` flag and did that with and without coverage, then used the following code to print out the table above:

```python
import json

def get_test_times(results):
    tests = results['report']['tests']
    times = {}
    for test in tests:
        times[test['name']] = test['duration']
    return times

with open('report.json') as f:
    results_nocov = json.load(f)
times_nocov = get_test_times(results_nocov)

with open('report_cov.json') as f:
    results_cov = json.load(f)
times_cov = get_test_times(results_cov)

for name in sorted(times_nocov):
    print("{0:72s} {1:9.6f} {2:9.6f} {3:9.6f}".format(name, times_nocov[name], times_cov[name], times_cov[name] / times_nocov[name]))
```

**Comment by pllim** [comment] 2016-05-03 16:00
I am using pytest 2.9.1 but it gives me error when I use `--json` option. :cry: 

```
$ python setup.py test -c -P units -V --json=report.json
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --json not recognized
```

**Comment by bsipocz** [comment] 2016-05-03 16:01
I think you'll need ``pytest-json`` installed.

**Comment by pllim** [comment] 2016-05-03 16:20
Thanks, @bsipocz ! Finally got that to work but as follows:

1. Install `pytest-json`, as you suggested.
2. Modify Astropy `setup.cfg` to have `json_report = report.json` under `[pytest]`.
3. Install Astropy using modified `setup.cfg`.
4. Run `python setup.py test -c -V -P units`.

**Comment by astrofrog** [comment] 2016-05-03 16:27
@pllim - ah yes I think you could also run with ``python setup.py test -a "--json='report.json'"`` - I was actually running the tests with ``py.test`` directly (after building with ``python setup.py build_ext --inplace``)

**Comment by pllim** [comment] 2016-05-03 16:29
Thanks. I just realized that the `report.json` generated using `setup.cfg` method is directly put in my system's temporary directory, which was promptly deleted by the system. Trying `py.test` now.

**Comment by pllim** [comment] 2016-05-03 17:10
So, I used the following incantations in Python 3.5.1:

```
py.test astropy/units/tests/test_format.py --json=report.json
========================= 665 passed in 27.98 seconds ==========================
```

```
py.test --cov=astropy astropy/units/tests/test_format.py --json=report_cov.json
========================= 665 passed in 60.85 seconds ==========================
```

I see some bad performance with coverage on but not as bad as yours:
[report_rpt_cov.txt](https://github.com/astropy/astropy/files/247347/report_rpt_cov.txt)

**Comment by astrofrog** [comment] 2016-05-03 17:38
@pllim - ok, thanks for checking! It looks like you do still have some that are worse by a factor of ~1000?

**Comment by pllim** [comment] 2016-05-03 18:40
After I changed how `test_roundtrip_ogip()` works (see #4836), the total time does not change but individual test times did (see 
[newreport_rpt_cov.txt](https://github.com/astropy/astropy/files/247510/newreport_rpt_cov.txt)).

Am I going crazy? Can you reproduce the same thing using my PR, @astrofrog ?

If that is indeed real, then the culprit lies within whatever I took out of the test function into module level operation. Somehow that few lines of codes take a lot longer in Python 3 when coverage is enabled. I cannot make sense of it.

Here is my test info (this is with coverage on):
```
============================= test session starts ==============================
platform linux -- Python 3.5.1, pytest-2.8.1, py-1.4.30, pluggy-0.3.1

Running tests with Astropy version 1.2.dev14976.
Running tests in astropy/units/tests/test_format.py.

Date: 2016-05-03T14:24:39

Platform: Linux-2.6.32-573.22.1.el6.x86_64-x86_64-with-redhat-6.7-Santiago

Executable: ~/anaconda/envs/py3k/bin/python

Full Python Version: 
3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.10.0
Scipy: 0.17.0
Matplotlib: 1.5.1
h5py: not available
Pandas: not available

rootdir: .../astropy/astropy_core, inifile: setup.cfg
plugins: cov-2.2.1, json-0.4.0
collected 665 items 

(blah blah blah)

========================= 665 passed in 61.00 seconds ==========================
```

**Comment by astrofrog** [comment] 2016-05-05 15:54
@pllim - I do see the total time decreasing a little.

I think there are some fundamental performance issues behind the scenes in the OGIP parser for instance. Check this out:

```
In [10]: %timeit Unit('kg m**2 / (A**2 s**2)')
1000 loops, best of 3: 553 µs per loop

In [11]: %timeit Unit('kg m**2 / (A**2 s**2)', format='ogip')
1 loop, best of 3: 475 ms per loop
```

So the OGIP parser is 1000 times slower than the default one. It also seems to spend a lot of time in ``did_you_mean``:

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       52    0.164    0.003    0.811    0.016 misc.py:407(did_you_mean)
   150644    0.135    0.000    0.249    0.000 difflib.py:676(real_quick_ratio)
    41660    0.118    0.000    0.163    0.000 difflib.py:647(quick_ratio)
       52    0.102    0.002    0.573    0.011 difflib.py:688(get_close_matches)
   150696    0.056    0.000    0.056    0.000 difflib.py:227(set_seq1)
   192392    0.055    0.000    0.055    0.000 difflib.py:38(_calculate_ratio)
```

Also, that's a lot of calls to difflib functions - maybe that's what slows down the coverage? (the sheer number of function calls)

**Comment by astrofrog** [comment] 2016-05-05 15:55
I'm going to also cc @mhvk as one of the units package maintainers :)

**Comment by pllim** [comment] 2016-05-05 15:59
> maybe that's what slows down the coverage?

The mystery here is why only slow in Python 3 but not Python 2 :question:

**Comment by pllim** [comment] 2016-05-05 16:08
Do you think it might be `from __future__ import unicode_literals`? In `did_you_mean()`, there is extra logic done for unicode string.

```python
In [1]: from astropy.extern import six
In [2]: from astropy.utils.misc import did_you_mean
In [3]: s1 = 'blah'
In [4]: isinstance(s1, six.text_type)
Out [4]: False
In [5]: %timeit did_you_mean(s1, ['s', 'b', 'c'])
10000 loops, best of 3: 22 µs per loop
In [6]: s2 = u'blah'
In [7]: isinstance(s2, six.text_type)
Out [7]: True
In [8]: %timeit did_you_mean(s2, ['s', 'b', 'c'])
10000 loops, best of 3: 29.1 µs per loop
```

**Comment by astrofrog** [comment] 2016-05-05 16:12
The real question is, why is ``did_you_mean`` getting called 52 times for this simple case??

**Comment by astrofrog** [comment] 2016-05-05 16:12
But yes then if it's normal it's called, it could indeed be a unicode thing :)

**Comment by astrofrog** [comment] 2016-05-05 16:22
@pllim - wow and now I'm really confused, apparently ``did_you_mean`` is getting called with:

```
in did_you_mean log
in did_you_mean ln
in did_you_mean exp
in did_you_mean sqrt
in did_you_mean sin
in did_you_mean cos
in did_you_mean tan
in did_you_mean asin
in did_you_mean acos
in did_you_mean atan
in did_you_mean sinh
in did_you_mean cosh
in did_you_mean tanh
in did_you_mean log
in did_you_mean ln
in did_you_mean exp
in did_you_mean sqrt
in did_you_mean sin
in did_you_mean cos
in did_you_mean tan
in did_you_mean asin
in did_you_mean acos
in did_you_mean atan
in did_you_mean sinh
in did_you_mean cosh
in did_you_mean tanh
in did_you_mean log
in did_you_mean ln
in did_you_mean exp
in did_you_mean sqrt
in did_you_mean sin
in did_you_mean cos
in did_you_mean tan
in did_you_mean asin
in did_you_mean acos
in did_you_mean atan
in did_you_mean sinh
in did_you_mean cosh
in did_you_mean tanh
in did_you_mean log
in did_you_mean ln
in did_you_mean exp
in did_you_mean sqrt
in did_you_mean sin
in did_you_mean cos
in did_you_mean tan
in did_you_mean asin
in did_you_mean acos
in did_you_mean atan
in did_you_mean sinh
in did_you_mean cosh
in did_you_mean tanh
```

**Comment by astrofrog** [comment] 2016-05-05 16:25
And just for info, this is the call stack:

```
CALLER 1 astropy.utils.misc.did_you_mean
CALLER 2 astropy.units.format.generic._parse_unit
CALLER 3 astropy.units.format.generic._get_unit
CALLER 4 astropy.units.format.generic.t_UNIT
CALLER 5 astropy.extern.ply.lex.Lexer.token
CALLER 6 astropy.extern.ply.yacc.LRParser.parseopt_notrack
CALLER 7 astropy.extern.ply.yacc.LRParser.parse
CALLER 8 astropy.units.format.generic._do_parse
CALLER 9 astropy.units.format.generic.parse
CALLER 10 astropy.units.core._UnitMetaClass.__call__
CALLER 11 astropy.units.core.CompositeUnit.__eq__
CALLER 12 astropy.units.format.ogip.p_unit_expression
CALLER 13 astropy.extern.ply.yacc.LRParser.parseopt_notrack
CALLER 14 astropy.extern.ply.yacc.LRParser.parse
CALLER 15 astropy.units.format.ogip.parse
CALLER 16 astropy.units.core._UnitMetaClass.__call__
CALLER 17 __main__
```

**Comment by astrofrog** [comment] 2016-05-05 16:29
@pllim - the guilty lines are:

```
            if p[1] in cls._functions and p[1] != 'sqrt':
                raise ValueError(
                    "The function '{0}' is valid in OGIP, but not understood "
                    "by astropy.units.".format(
                        p[1]))
```

in ``ogip.py``. I think somehow calling ``_functions`` then does something slow... If I comment out these lines, the OGIP tests run at normal speed.

**Comment by astrofrog** [comment] 2016-05-05 16:33
Interestingly, ``_functions`` is a lazy property, but what's slow is actually:

```
            f = p[1] in cls._functions
```

every time it executes that line, it tries to parse all the functions as units!

**Comment by astrofrog** [comment] 2016-05-05 16:38
Huh so apparently when one does:

```
Unit('kg') in ['a','b','c','d','e','f','g','h','i','j','k','l']
```

it tries to parse all the strings as units!

**Comment by astrofrog** [comment] 2016-05-05 16:43
Ah, I think it's because we do the parsing in ``__eq__``.

**Comment by mhvk** [comment] 2016-05-05 16:43
Seems like real progress -- just on the last line, this goes back to testing equality for units:
`__eq__` tries to parse `other` as a unit, so that things like `u.kg == 'kg'` can evaluate to `True`. 

I think this is desired behaviour, but it does suggest we need to rewrite that `p[1] in cls._functions` line. In particular, since `_functions` contains only strings, it could be `str(p[1]) in cls._functions`

**Comment by astrofrog** [comment] 2016-05-05 16:44
Oh damn:

```
In [2]: Unit('kg') in ['kg']
Out[2]: True
```

@mhvk - I think indeed using ``str`` would fix this.

**Comment by astrofrog** [comment] 2016-05-05 16:47
With the original code:

```
            if p[1] in cls._functions and p[1] != 'sqrt':
```

I get:

```
665 passed in 4.64 seconds
```

and with:

```
            if str(p[1]) in cls._functions and p[1] != 'sqrt':
```

I get 

```
665 passed in 44.53 seconds
```

I think we found our culprit!

I'll open a pull request later this evening and will see if there are other similar bottlenecks.

**Comment by astrofrog** [comment] 2016-05-05 16:49
And if I do the same fix for other instances of p[1] comparison in that function, I get

```
665 passed in 4.31 seconds
```

**Comment by mhvk** [comment] 2016-05-05 16:50
Since we're looking for a string, maybe explicitly test that `p[1]` still is a string (rather than already a unit), i.e.,
```
if type(p[1]) is str and p[1] != 'sqrt' and p[1] in cls._functions
```
(I think you don't need to do `six.string_types` in this case)

**Comment by pllim** [comment] 2016-05-05 16:50
:clap: Nice detective work!

**Comment by pllim** [comment] 2016-05-05 16:53
A bit late to the discussions but since I spent time making the diagrams, I'll just post them anyway.

Here is the code profiled:
```python
#!/usr/bin/python
from astropy import units as u
x = u.Unit('kg m**2 / (A**2 s**2)', format='ogip')
```

Here is the profiling for Python 2:
![outpy2](https://cloud.githubusercontent.com/assets/2090236/15050206/46635956-12c0-11e6-819e-0c010fd26c9c.png)

Here is the profiling for Python 3:
![outpy3](https://cloud.githubusercontent.com/assets/2090236/15050214/4d375a70-12c0-11e6-93b0-98e74858c259.png)

**Comment by astrofrog** [comment] 2016-05-06 12:05
Apart from the fixes in https://github.com/astropy/astropy/pull/4849, I don't have time to investigate this further, so maybe someone else can look into this. There are still big performance differences, although the unit format tests are now much faster.

**Comment by bsipocz** [comment] 2016-05-14 18:35
@pllim - What did you use to generate these maps?

**Comment by pllim** [comment] 2016-05-14 19:16
https://github.com/jrfonseca/gprof2dot

**Comment by pllim** [comment] 2016-05-16 19:04
There is also https://jiffyclub.github.io/snakeviz/ if you want some other kind of visualization.

**Comment by pllim** [comment] 2016-09-06 18:08
@astrofrog , is this still a problem on your end? If not, then maybe we can close this. Using the latest `master` that includes #5306, among other things merged since we visited this issue, Python 3 is twice as fast as Python 2 (which is expected because Python 2 runs with and without `unicode_literals`.

Using your command:
```
python setup.py test -P units --coverage
```

In Python 2:
```python
=== 2394 passed, 13 skipped, 3 xfailed in 59.60 seconds ===
```

In Python 3:
```python
=== 1490 passed, 3 xfailed in 34.56 seconds ===
```

**Comment by mhvk** [comment] 2016-09-06 18:47
@pllim - I'm not sure I fully understand how it could have gotten that much better, but it certainly seems good news! And I get essentially the same timings as you do, python3 being nearly a factor 2 faster. Running all tests, python2 takes 345s and python3 247s, so for those it helps a lot too.

However, we should not close this before having moved travis over to coverage testing on python 3.5. See #5308.

**Comment by pllim** [comment] 2016-09-06 18:51
@mhvk , I don't either, since @MSeifert04 claimed that his PR is not supposed to fix this particular problem... Maybe Travis CI timing will confirm for sure.

**Comment by mhvk** [comment] 2016-09-06 23:54
Let me move the discussion back here: @astrofrog - do you get much longer times on your own computer? I ask since both @pllim and I seemed to get short ones, at least with the simple `python3 setup.py test --coverage -P units` line you had at the very top of this file (while travis obviously still is very slow).

**Comment by pllim** [comment] 2016-09-07 17:28
I am running a series of coverage tests, once per module, and then altogether, and recording the run times on both Python versions. Hopefully it will be finished before Thanksgiving.

**Comment by mhvk** [comment] 2016-09-07 17:38
If you're thinking of Canadian thanksgiving, we only have to wait about a month...

**Comment by MSeifert04** [comment] 2016-09-07 22:08
@pllim and @mhvk What versions of `coverage` are you using locally? As I noted in https://github.com/astropy/astropy/pull/5308#issuecomment-245132916 it may just be something that was fixed in a newer version of `coverage`.

**Comment by pllim** [comment] 2016-09-07 23:07
The latest I could get via conda update on both Python versions. I'll check when I'm back at work tomorrow.

**Comment by mhvk** [comment] 2016-09-08 01:12
I'm using what Debian testing provides, which is 4.2 (i.e., the newest according to the comment you linked to). Since we seem to install `apt`, it may be possible to get it via that? It would seem a good possibility!

**Comment by pllim** [comment] 2016-09-08 16:45
See potential fix in astropy/ci-helpers#132

**Comment by pllim** [comment] 2016-09-08 17:24
Attached is my report from running coverage tests on each of the sub-package, and then the whole thing in the end. My conclusion is that the slowness in Python 3 is no longer an issue (at least with `coverage` 4.2). I agree with @MSeifert04 and @mhvk that the culprit might be the older `coverage` version, not Astropy itself. The one failure you see in the report is reported separately in #5316.

[zcov_result.txt](https://github.com/astropy/astropy/files/462254/zcov_result.txt)

**Comment by MSeifert04** [comment] 2016-09-08 17:28
Would be nice if it's indeed the coverage version.

**Comment by bsipocz** [comment] 2016-10-10 18:11
Travis runs 2 mins faster for me for astropy when testing for @pllims PR in ci-helpers, so hopefully some of that gain is real. https://travis-ci.org/bsipocz/astropy/builds/166497095

**Comment by mhvk** [comment] 2016-10-12 21:06
I think this is mostly solved, so closing!

**Closed by mhvk** 2016-10-12 21:06 UTC
Labels: Performance, testing, units

**Comment by holvianssi** [comment] 2022-07-28 12:08
As this happens to be first hit on Google, and I just spent a lot of time chasing why coverage is slow, I'm going to leave a hint here for the future:

Check you have C extensions installed in your coverage package!
