### ISSUE TITLE
u.Unit(str(u.ABmag)) fails: cannot init ABmag unit with str representation

### ISSUE THREAD

**Issue by lpsinger** [astropy/astropy#7040] opened 2017-12-28 23:40 UTC
Certain units do not survive a round trip of writing and reading a table.

For example, `units.mag` is fine:

```python
>>> from astropy.table import Table
>>> from astropy import units as u
>>> 
>>> table1_in = Table(
...     [[1, 2, 3] * u.day, [20, 21, 22] * u.mag],
...     names=['time', 'magnitude'])
>>> table1_in.write('table1.ecsv', format='ascii.ecsv')
>>> table1_out = Table.read('table1.ecsv', format='ascii.ecsv')
>>> assert table1_out['time'].unit == u.day
>>> assert table1_out['magnitude'].unit == u.mag
```

But `units.ABmag` is not:

```python
>>> table2_in = Table(
...     [[1, 2, 3] * u.day, [20, 21, 22] * u.ABmag],
...     names=['time', 'magnitude'])
>>> table2_in.write('table2.ecsv', format='ascii.ecsv')
>>> table2_out = Table.read('table2.ecsv', format='ascii.ecsv')
>>> assert table2_out['time'].unit == u.day
>>> assert table2_out['magnitude'].unit == u.ABmag
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
>>> table2_out['magnitude'].unit
UnrecognizedUnit(mag(AB))
```

This occurs with version 2.0.2 and also on master.

**Comment by taldcroft** [comment] 2017-12-29 10:29
The root cause here is that the string representation of `u.ABmag` cannot be used to initialize `u.Unit`:
```
In [6]: u.Unit(str(u.ABmag))
ValueError: 'mag(AB)' did not parse as unit: At col 4, AB is not a valid unit. Did you mean aB, aWb, ab, daB or dab?
```
So basically the `ABmag` unit does not round-trip even within units.  I'm labeling this a units issue.

**Comment by taldcroft** [comment] 2017-12-29 10:33
@lpsinger - I changed the issue title to more closely describe the root issue.

**Comment by mhvk** [comment] 2017-12-29 19:06
This is indeed a more general problem - for discussion see #5030. Need to think a bit about how best to solve this...

**Comment by lpsinger** [comment] 2017-12-30 01:33
OK, going back to my example, this works:

```python
>>> with u.magnitude_zero_points.enable():
...     table3_in = Table(
...         [[1, 2, 3] * u.day, [20, 21, 22] * u.ABmag],
...         names=['time', 'magnitude'])
...     table3_in.write('table3.ecsv', format='ascii.ecsv')
...     table3_out = Table.read('table3.ecsv', format='ascii.ecsv')
...     assert table3_out['time'].unit == u.day
...     assert table3_out['magnitude'].unit == u.ABmag
```

But I just don't understand from the discussion in #5030, what is the point of this context handler? Why aren't the `STmag` and `ABmag` units always enabled?

**Comment by mhvk** [comment] 2017-12-30 01:46
The context handler decides whether `u.ST` and `u.AB` are enabled, i.e., the flux densities corresponding to magnitude 0 in the respective systems. These are usually not useful, but here they obviously are! I think in principle your problem would be solved by doing the magnitude unit retrieval inside this context, but I would like to think a bit whether there isn't a more elegant method -- which would make this work all the time.

**Comment by lpsinger** [comment] 2017-12-30 01:48
OK, fair enough that they are not usually useful, but can you give an example of a situation where you would actually need them to be *disabled*?

**Comment by mhvk** [comment] 2017-12-30 23:29
@lpsinger - just for completeness (partially for myself), there are really two things that do not work: `"mag(AB)"` and "ABmag" - the former can be solved with `u.magnitude_zero_points.enable()`, the latter not. So far all that we've added is support for `"mag('AB')"`. I do think all of these should just work out of the box.

**Comment by mhvk** [comment] 2017-12-31 22:31
Just realized a larger implications: @taldcroft - things like `'inch'` will currently not round-trip either. Possibly, we should do the unit comprehension with all units enabled by default (generous on input and all that...).

**Comment by mhvk** [comment] 2019-06-22 00:35
The actual issue here has been fixed, so closing.

**Closed by mhvk** 2019-06-22 00:35 UTC
Labels: Affects-release, Bug, units
