### ISSUE TITLE
"Illegal instruction : 4" when using transform_to

### ISSUE THREAD

**Issue by domkirke** [astropy/astropy#7241] opened 2018-02-27 15:00 UTC
This bug seems to be computer specific because it works on some other installations with my own code, but if it happens to me it should happen to other people so I dare posting this here : 

When using the **transform_to** of the package **astropy.coordinates** on a **SkyCoord** object, I get an **"Illegal instruction: 4"** error that crashes the Python kernel. I tried to print deeper and deeper, but I came into the stomach of the library when it begins to be hard to understand anything..
if you could give an hand at this I would be thankful as hell!

Installation details : 
Python : 3.6.3
Astropy : 3.0
Numpy : 1.14.1 (tried to downgrade, didn't change anything unfortunately)

**Comment by adrn** [comment] 2018-02-27 15:58
Could you provide a little more information? Specifically:
* Your system architecture
* What Python distribution are you using?
* A minimal example that produces this failure

Thanks!

**Comment by pllim** [comment] 2018-02-27 16:16
These are the top 3 results from the Internet, all of which seem plausible:

ContinuumIO/anaconda-issues#6400
numpy/numpy#9532
gevent/gevent#791 (the solution to this one is to use `--no-use-wheel` in case that also somehow solves your problem)

**Comment by domkirke** [comment] 2018-02-27 17:42
Of course!

System : macOS Sierra 10.12.5
processor : 2,7GHz Intel Core i7
Memory : 16Gà 2133 MHz LPDDR3

i installed everything with `python3` and `pip3` installed by `brew` .

And, finally, a little bit of code : 
```
import matplotlib
#matplotlib.use('agg')
import astrolib.astrofabiolib3 as al
import os, math

inputfile='Master-objects-list.txt'
listfile=os.path.dirname(os.path.realpath(__file__))+"/astrolib/"+inputfile

mycoord = [48.901389, 2.378889]
myday   = '2015-10-03'
myhour  = '20'
mymin   = '3'
mytimezone = 'Europe/Paris'
ephemdate = '2015/10/3'
data = al.getdata(listfile,ephemdate)
filters=["EtoilesB"] # TEST
figure, astrodict = al.astroplot(data,myday,myhour,mymin,mytimezone,mycoord,filters)
```
whose final line yields to `Illegal instruction: 4`. 

I checked the three solutions, the first two are concerning old hardware, and I tried the final one but unfortunately did not work..
Thanks again!

**Comment by pllim** [comment] 2018-02-27 19:14
This is weird. I got a notification via email but I don't see the reply here.

```
Of course!
System : macOS Sierra 10.12.5
processor : 2,7GHz Intel Core i7
Memory : 16Gà 2133 MHz LPDDR3
i installed everything with python3 and pip3 installed by brew .
And, finally, a little bit of code :

import matplotlib
#matplotlib.use('agg')
import astrolib.astrofabiolib3 as al
import os, math

inputfile='Master-objects-list.txt'
listfile=os.path.dirname(os.path.realpath(__file__))+"/astrolib/"+inputfile

mycoord = [48.901389, 2.378889]
myday   = '2015-10-03'
myhour  = '20'
mymin   = '3'
mytimezone = 'Europe/Paris'
ephemdate = '2015/10/3'
data = al.getdata(listfile,ephemdate)
filters=["EtoilesB"] # TEST
figure, astrodict = al.astroplot(data,myday,myhour,mymin,mytimezone,mycoord,filters)

whose final line yields to Illegal instruction: 4.
I checked the three solutions, the first two are concerning old hardware, and I tried the final one but unfortunately did not work..
Thanks again!
```

In the reply that I got, I don't see any `astropy` import. I am not familiar with `import astrolib.astrofabiolib3 as al`. Perhaps this issue is posted to the wrong repository?

**Comment by astrofrog** [comment] 2018-02-27 22:22
The original description of the issue does mention 'When using the transform_to of the package astropy.coordinates on a SkyCoord object' though, so maybe the posted example is wrong?

**Comment by domkirke** [comment] 2018-02-27 22:25
Yes, I am trying to figure out more deeply of does this error come from, because while trying to make a test code I figured out that my test code worked... Such a mess! I will go deeper tomorrow

**Comment by domkirke** [comment] 2018-02-28 13:57
Ok, a little update about this :

I figured out that in face the error occurs with the line  
`pos_list.transform_to( c.AltAz(obstime=mydate, location=myloc) )`
**with the `matplotlib.pyplot` imported**. Function `transform_to`and `c.AltAz(obstime=mydate, location=myloc)` work separately, and make the code crash only when combined...

**Comment by pllim** [comment] 2018-02-28 17:23
Thanks for digging at this, @domkirke . Can you please provide a fully function snippet that includes values of `pos_list`, `mydate`, and `myloc`?

**Comment by pllim** [comment] 2018-02-28 17:24
Thanks for digging at this, @domkirke . Can you please provide a fully function snippet that includes values of `pos_list`, `mydate`, and `myloc`?

**Comment by domkirke** [comment] 2018-02-28 22:20
Thanks to you! Sure, there is : 
```
import astropy.coordinates as c
import astropy.units as u
import pickle
import matplotlib.pyplot

mydate = "2015-10-03 18:00:00.000"
mycoord = [48.901389, 2.378889]
myloc = c.EarthLocation( lat=mycoord[0]*u.deg, lon=mycoord[1]*u.deg ) # Paris
#self.data = al.getdata(self.listfile,self.ephemdate)
with open('Master-objects-list.pickle','rb') as f:
    name,types,dists,pos_list = pickle.load(f)
    data = [name,types,dists,pos_list]

names,types,dists,pos_list = data
altaz = pos_list.transform_to( c.AltAz(obstime=mydate, location=myloc) )
```
You will need the attached pickle, git does not allow me to upload a `.pickle` so here is a link : https://www.dropbox.com/s/0ep6d5nb31qasd4/Master-objects-list.pickle?dl=0

**Comment by drdavella** [comment] 2018-03-01 19:19
@domkirke, no offense intended to you, but I think many people would be hesitant to open a pickle from an unknown source on their personal/work computers. Is there any chance this can be reproduced without using pickle?

**Comment by domkirke** [comment] 2018-03-01 20:27
Ow, sorry for that, there is a pickle-free version : 
```
import astropy.coordinates as c
import astropy.units as u
import pickle
import matplotlib
#matplotlib.use('Qt5Agg')
import matplotlib.pyplot
mycoord = [48.901389, 2.378889]
myloc = c.EarthLocation( lat=mycoord[0]*u.deg, lon=mycoord[1]*u.deg ) # Paris
#self.data = al.getdata(self.listfile,self.ephemdate)
mydate = '2015-10-03 18:00:00.00'
lon = [83.63307625, 31.4043, 6.3397]
lat = [22.01449328, 64.8283, 64.1408]
pos_list = c.SkyCoord(lon, lat, frame='fk5', unit='deg')
altaz = pos_list.transform_to( c.AltAz(obstime=mydate, location=myloc) )
```

**Comment by pllim** [comment] 2018-03-06 22:00
It does seem weird that somehow this interacts with `matplotlib` and Qt5. As suspected above, indeed I can't reproduce this locally on RHEL7. I see
```
Downloading http://maia.usno.navy.mil/ser7/finals2000A.all
|==========================================| 3.1M/3.1M (100.00%)         0s
```
and then
```python
>>> altaz
<SkyCoord (AltAz: obstime=2015-10-03 18:00:00.000, location=(4197084.994369475, 174360.84505676336, 4783357.016988893) m, pressure=0.0 hPa, temperature=0.0 deg_C, relative_humidity=0, obswl=1.0 micron): (az, alt) in deg
    [(19.94075536, -16.72375522), (30.42505513,  36.86166511),
     (38.22097753,  45.89152854)]>
```

Maybe someone with the same Mac OSX can give it a shot?

**Comment by StuartLittlefair** [comment] 2018-05-10 14:19
I can't reproduce using Python 3.6 and astropy 3.0.2

**Comment by astrofrog** [comment] 2018-05-10 14:29
@domkirke - if you use conda, can you try updating matplotlib, numpy, and astropy to see if this is fixed? (I think there was a related conda matplotlib issue that was fixed)

**Comment by domkirke** [comment] 2018-05-10 14:33
Hello all,
thanks for digging up the thread!
Yes, i don't know why, i really have the feeling that it happens just for myself (the soft I programmed is now used by other people, but they do not suffer this issue while it still happen on my laptop...)... could I edit a useful profile (pip log or something like that) that could help you?

@astrofrog I only use pip unfortunately, and everything is up-to-date...

**Comment by adrn** [comment] 2021-05-24 16:35
Many versions of Python have come and gone, and versions of macOS, so closing this. But please reopen if you run into this again!

**Closed by adrn** 2021-05-24 16:35 UTC
Labels: Mac OSX, coordinates
