### ISSUE TITLE
Investigate Gaussian2D bounding box shape mismatch in numpy 1.25 or later

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#14766] opened 2023-05-05 22:01 UTC
This is a follow-up of https://github.com/astropy/astropy/pull/14718 and https://github.com/astropy/astropy/issues/14705 and the goal is to remove the `if` and have the test not fail.

https://github.com/astropy/astropy/blob/e3b2444227a1bcb06931bc61cdd039936e421e8a/astropy/modeling/tests/test_models.py#L255-L258

**Comment by WilliamJamieson** [comment] 2023-05-06 13:29
This will be fixed by #14771.

This was not a bug on our end. The inputs were specifically constructed to be within the bounding box however some upstream bug in numpy was throwing one point out of the box. This bug was corrected upstream.

**Closed** 2023-05-06 14:54 UTC
Labels: testing, Bug, modeling
