### ISSUE TITLE
Incorrect Column Labels in MRT Format with astropy.io.ascii

### ISSUE THREAD

**Issue by Mubin17** [astropy/astropy#14873] opened 2023-05-28 13:03 UTC
### Description

I ran into an issue while using ascii.write from astropy.io.ascii to save a table in the Machine Readable Table (MRT) format. The problem arises when attempting to write the column labels, as they are not correctly identified in the resulting MRT file. Instead, the labels are displayed as "Unknown."

### Expected behavior

The resulting MRT file should have the column labels correctly displayed, corresponding to the column names in the table.

### How to Reproduce

Run the code below:
```python
from astropy.cosmology import Planck18
from astropy.io import ascii

# Step 1: Convert cosmology object to a table
table = Planck18.to_format("astropy.table")

# Step 2: Replace the m_nu column with N columns
m_nu = table['m_nu']  # Get the m_nu column
N = len(m_nu[0])  # Get the number of elements in m_nu

# Remove the m_nu column from the table
table.remove_column('m_nu')

# Add N new columns to the table with names 'm_nu_0', 'm_nu_1', 'm_nu_2', ...
for i in range(N):
    column_name = f'm_nu{i}'
    column_data = m_nu[0][i]
    table.add_column(column_data, name=column_name, index=-2)
    
# Step 3: Save as an MRT
ascii.write(table, "ascii_write_mrt_check.mrt", format="mrt", overwrite=True)
```
Check the ascii_write_mrt_check.mrt file, it will look like this:

```plaintext
Title:
Authors:
Table:
================================================================================
Byte-by-byte Description of file: table.dat
--------------------------------------------------------------------------------
 Bytes Format Units  Label     Explanations
--------------------------------------------------------------------------------
 1- 8  A8           ---    name    Description of name
10-14  F5.2   km.Mpc-1.s-1 Unknown [67.66/67.66] Hubble constant as an
                            `~astropy.units.Quantity` at z=0.
16-22  F7.5         ---    Om0     [0.3/0.31] Omega matter; matter
                            density/critical density at z=0.
24-29  F6.4         K      Unknown [2.72/2.73] Temperature of the CMB as
                            `~astropy.units.Quantity` at z=0.
31-35  F5.3         ---    Neff    [3.04/3.05] Number of effective neutrino
                            species.
37-39  F3.1         eV     Unknown Description of Unknown
41-43  F3.1         eV     Unknown Description of Unknown
45-48  F4.2         eV     Unknown [0.06/0.06] Description of Unknown
50-56  F7.5         ---    Ob0     [0.04/0.05] Omega baryon; baryonic matter
                            density/critical density at z=0.
--------------------------------------------------------------------------------
Notes:
--------------------------------------------------------------------------------
Planck18 67.66 0.30966 2.7255 3.046 0.0 0.0 0.06 0.04897
```

### Versions

macOS-13.0.1-arm64-arm-64bit
Python 3.10.11 (main, Apr 20 2023, 13:58:42) [Clang 14.0.6 ]
astropy 5.3
Numpy 1.24.3
pyerfa 2.0.0.3
Scipy 1.10.1

**Comment by Mubin17** [comment] 2023-05-28 13:08
@taldcroft would you be able to take a look at this? Thanks

**Comment by hamogu** [comment] 2023-10-15 09:35
This is a duplicate of #12804. I'm closing this one,  so we keep the discussion in one place.

**Closed by hamogu** 2023-10-15 09:35 UTC
Labels: io.ascii, Bug, unified-io
