### ISSUE TITLE
Replace Example Gallery with Example Index

### ISSUE THREAD

**Issue by kelle** [astropy/astropy#6589] opened 2017-09-21 16:08 UTC
- incorporate all examples into the documentation
- add tag to examples so they can be indexed
- create Example Index

**Comment by sosey** [comment] 2018-12-10 15:34
@kelle  @eteq You could put a link in the sphinx docs directly to a notebook with the example you want to show, this will pop it up in colab, which might be an interesting option for people:

 https://colab.research.google.com/github/astropy/astropy-workshop

More info:
https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb

**Comment by eteq** [comment] 2018-12-10 18:37
It turns out #7242 is a duplicate of this.  @kelle indicated we should close this one since #7242 has a bit more detail.  So I will do that.  But I like @sosey's suggestion so will cross-post it there!

**Closed by eteq** 2018-12-10 18:37 UTC
Labels: Docs, Refactoring
