### ISSUE TITLE
Improve error message when attempting to write CompImageHDU with integer data

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4250] opened 2015-10-20 08:02 UTC
The following example:

```python
import numpy as np
from astropy.io import fits

image = np.arange(9).reshape((3,3))
header = fits.Header()

hdu = fits.CompImageHDU(image, header)
hdu.writeto('compressed_image.fits', clobber=True)
```

produces the following error:

```
Traceback (most recent call last):
  File "create_compressed.py", line 8, in <module>
    hdu.writeto('compressed_image.fits', clobber=True)
  File "/Users/tom/miniconda3/envs/gluedev/lib/python3.4/site-packages/astropy-1.1.dev13845-py3.4-macosx-10.5-x86_64.egg/astropy/io/fits/hdu/base.py", line 1766, in writeto
    checksum=checksum)
  File "/Users/tom/miniconda3/envs/gluedev/lib/python3.4/site-packages/astropy-1.1.dev13845-py3.4-macosx-10.5-x86_64.egg/astropy/io/fits/hdu/hdulist.py", line 689, in writeto
    hdu._prewriteto(checksum=checksum)
  File "/Users/tom/miniconda3/envs/gluedev/lib/python3.4/site-packages/astropy-1.1.dev13845-py3.4-macosx-10.5-x86_64.egg/astropy/io/fits/hdu/compressed.py", line 1815, in _prewriteto
    self._update_compressed_data()
  File "/Users/tom/miniconda3/envs/gluedev/lib/python3.4/site-packages/astropy-1.1.dev13845-py3.4-macosx-10.5-x86_64.egg/astropy/io/fits/hdu/compressed.py", line 1679, in _update_compressed_data
    heapsize, self.compressed_data = compression.compress_hdu(self)
RuntimeError: writing to compressed image is not supported
```

This is misleading because it makes it seem like writing to compressed images is not supported at all, when in fact changing the data type to float fixes the issue.

**Comment by embray** [comment] 2015-10-20 14:16
That doesn't seem right, because the default RICE_1 compression method is intended only for integers to begin with.

**Comment by embray** [comment] 2015-10-20 14:18
Oh I see. It's because you're writing 64-bit ints.  In that case this is a duplicate of  #2153

**Closed by embray** 2015-10-20 14:18 UTC
Labels: io.fits
