### ISSUE TITLE
1.0rc2: install into anaconda fails on OS X

### ISSUE THREAD

**Issue by PBarmby** [astropy/astropy#3492] opened 2015-02-12 18:21 UTC
Don't know if this is related to my earlier issue (#3408), but here I am installing with PYTHONPATH not explicity defined, and `.pydistutils.cfg` removed. It seemed like the install was going OK, then
```
copying astropy/wcs/tests/extension/wcsapi_test.c -> build/lib.macosx-10.5-x86_64-2.7/astropy/wcs/tests/extension

running build_ext

running pre_hook from astropy._erfa.setup_package for build_ext command

WARNING: The autogenerated wrappers in astropy._erfa seem to be older than the source templates used to create them. Because this is a release version we will use them anyway, but this might be a sign of some sort of version mismatch or other tampering. Or it might just mean you moved some files around or otherwise accidentally changed timestamps.

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/private/var/folders/+t/+th0HF8gGJevLBRMku2Vy++++TI/-Tmp-/pip_build_pauline/astropy/setup.py", line 122, in <module>

    **package_info

  File "/Users/pauline/progs/anaconda/envs/astropy_rc/lib/python2.7/distutils/core.py", line 151, in setup

    dist.run_commands()

  File "/Users/pauline/progs/anaconda/envs/astropy_rc/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/Users/pauline/progs/anaconda/envs/astropy_rc/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/Users/pauline/progs/anaconda/envs/astropy_rc/lib/python2.7/site-packages/setuptools-5.8-py2.7.egg/setuptools/command/install.py", line 61, in run

  File "/Users/pauline/progs/anaconda/envs/astropy_rc/lib/python2.7/distutils/command/install.py", line 563, in run

    self.run_command('build')

  File "/Users/pauline/progs/anaconda/envs/astropy_rc/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/Users/pauline/progs/anaconda/envs/astropy_rc/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/Users/pauline/progs/anaconda/envs/astropy_rc/lib/python2.7/distutils/command/build.py", line 127, in run

    self.run_command(cmd_name)

  File "/Users/pauline/progs/anaconda/envs/astropy_rc/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/Users/pauline/progs/anaconda/envs/astropy_rc/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/private/var/folders/+t/+th0HF8gGJevLBRMku2Vy++++TI/-Tmp-/pip_build_pauline/astropy/astropy_helpers/astropy_helpers/setup_helpers.py", line 360, in run

    orig_run(self)

  File "/private/var/folders/+t/+th0HF8gGJevLBRMku2Vy++++TI/-Tmp-/pip_build_pauline/astropy/astropy_helpers/astropy_helpers/commands/build_ext.py", line 147, in run

    orig_run(self)

  File "/Users/pauline/progs/anaconda/envs/astropy_rc/lib/python2.7/site-packages/setuptools-5.8-py2.7.egg/setuptools/command/build_ext.py", line 54, in run

  File "/Users/pauline/progs/anaconda/envs/astropy_rc/lib/python2.7/distutils/command/build_ext.py", line 306, in run

    force=self.force)

  File "/Users/pauline/progs/anaconda/envs/astropy_rc/lib/python2.7/site-packages/numpy/distutils/ccompiler.py", line 557, in new_compiler

    module = sys.modules[module_name]

AttributeError: 'NoneType' object has no attribute 'modules'

----------------------------------------
Cleaning up...
Command /Users/pauline/progs/anaconda/envs/astropy_rc/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/+t/+th0HF8gGJevLBRMku2Vy++++TI/-Tmp-/pip_build_pauline/astropy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/+t/+th0HF8gGJevLBRMku2Vy++++TI/-Tmp-/pip-x_Sbge-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /private/var/folders/+t/+th0HF8gGJevLBRMku2Vy++++TI/-Tmp-/pip_build_pauline/astropy
Traceback (most recent call last):
  File "/Users/pauline/progs/anaconda/envs/astropy_rc/bin/pip", line 6, in <module>
    sys.exit(main())
  File "/Users/pauline/progs/anaconda/envs/astropy_rc/lib/python2.7/site-packages/pip/__init__.py", line 198, in main
    return command.main(cmd_args)
  File "/Users/pauline/progs/anaconda/envs/astropy_rc/lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 70: ordinal not in range(128)
```

**Comment by embray** [comment] 2015-02-12 21:00
Was this from a git repository, or...?

**Comment by PBarmby** [comment] 2015-02-12 21:32
From pip install --pre astropy. But it was user error (sorry!) trying to install into a conda environment that already had astropy. Apologies.

**Comment by embray** [comment] 2015-02-12 21:32
Reopening just because I don't see any reason that shouldn't work, much less not crash with completely baffling exceptions.

**Comment by embray** [comment] 2015-02-12 21:41
```
  File "/Users/pauline/progs/anaconda/envs/astropy_rc/lib/python2.7/site-packages/setuptools-5.8-py2.7.egg/setuptools/command/build_ext.py", line 54, in run
```
this is a pretty old version of setuptools and might have something to do with it.  It isn't *that* old either though.

**Comment by embray** [comment] 2015-02-12 21:45
No, I don't think that was it.  Unless someone can find a way to reproduce this I don't think there's much to do.  But it's not user error to try to upgrade an existing astropy installation.

**Comment by PBarmby** [comment] 2015-02-13 14:21
For what it's worth, after I deleted the old astropy, the install with pip did work, and the tests passed.

**Comment by embray** [comment] 2015-02-13 17:50
Do you know what version of Astropy was installed before?  Was it from the conda package or was it from pip?

**Comment by PBarmby** [comment] 2015-02-13 18:37
I'm not completely sure, so I attempted to reproduce the problem. Made a new conda environment, switched to it, and did `pip install --pre --upgrade astropy` (wouldn't do anythin without the `upgrade` flag); seemed to work without problems. Went to the environment that I had made for v1.0rc1, and tried  `pip install --pre  astropy`; that failed with the same error as above. So the problem seems to be in installing the new release candidate over the old one.

**Comment by embray** [comment] 2015-02-13 21:51
I tried doing something akin to that and still wasn't able.  In your last comment are you saying you managed to reproduce the problem again?  If so, if you find the time, would you be willing to report an exact list of steps?

If not then don't worry about it.

**Comment by PBarmby** [comment] 2015-02-19 16:46
I thought I had reproduced it with:
```
conda create -n astropy_rc2a anaconda
source activate astropy_rc2a
pip install --pre --upgrade astropy
```
but of course now this seems to work fine. I'm sure the whole business is just due to my overly-encrusted-many-versions Python installation..

**Comment by embray** [comment] 2015-02-19 17:45
Yeah, I tried something like that too.  

> I'm sure the whole business is just due to my overly-encrusted-many-versions Python installation

Entirely possible, though still a bizarre and surprising error.  I like a good mystery :)  I guess since neither of us can reproduce and no one else has reported the issue I'll close this now but please reopen if it occurs again.  Thanks for taking the time to investigate!

**Closed by embray** 2015-02-19 17:45 UTC
Labels: build, installation
