### ISSUE TITLE
TST: image-tests-mpldev is failing

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8678] opened 2019-05-08 20:12 UTC
Example log: https://circleci.com/gh/astropy/astropy/30970

* `TestBasic.test_axislabels_regression`
* `TestBasic.test_patches_distortion`

both failed with 

`matplotlib.testing.exceptions.ImageComparisonFailure: Image sizes do not match expected size`

@astrofrog ?

UPDATE: Need to undo #8696 to see the failures.

**Comment by pllim** [comment] 2019-05-09 17:40
I also posted at matplotlib/matplotlib#14180 . Maybe disabling image *size* comparison in the test (if possible) is the best route to go.

**Comment by astrofrog** [comment] 2019-05-11 16:01
We shouldn't disable the image size comparison, as this should definitely count as a failure. The current output is currently wrong, either due to a bug in Matplotlib or a change in API in Matplotlib, so we need to address the underlying cause either way.

For example, **test_patches_distortion** has:

**Before:**

![baseline-test_patches_distortion](https://user-images.githubusercontent.com/314716/57572132-6114c680-73e4-11e9-821f-fd42c8f06d99.png)

**After:**

![test_patches_distortion](https://user-images.githubusercontent.com/314716/57572133-6114c680-73e4-11e9-810d-fd36582b0bb3.png)

I'm currently bisecting Matplotlib to understand why this changed (and is now wrong)

**Comment by astrofrog** [comment] 2019-05-11 16:34
Bisecting points to 71db23e6863031414cda1f105a75f6ebb1e735bf as the culprit. I'll try and understand if this is an actual bug in MPL or whether we need to fix anything in WCSAxes.

**Comment by astrofrog** [comment] 2019-05-11 16:51
A minimal example that demonstrates the issue is:

```python
from astropy.wcs import WCS
import matplotlib.pyplot as plt

wcs = WCS()
fig = plt.figure(figsize=(3, 3))
ax = fig.add_axes([0.25, 0.25, 0.5, 0.5], projection=wcs, aspect='equal')
ax.set_xlim(0, 10000)
ax.set_ylim(0, 10)
fig.savefig('test.png', bbox_inches='tight')
```

this seems to happen only when ``aspect='equal'``. I'll investigate further.

**Comment by astrofrog** [comment] 2019-05-11 17:07
I've posted a comment [here](https://github.com/matplotlib/matplotlib/pull/14134#issuecomment-491527998) in case there are any insights on the Matplotlib side.

**Comment by astrofrog** [comment] 2019-05-11 17:26
And I've now narrowed this down to a minimal example in https://github.com/matplotlib/matplotlib/pull/14134#issuecomment-491529552, so let's see what they say.

**Comment by pllim** [comment] 2019-05-15 15:45
`mpldev` job is failing now with a different error:
```
! LaTeX Error: File `type1ec.sty' not found.
```

https://circleci.com/gh/astropy/astropy/31251

**Comment by astrofrog** [comment] 2019-05-15 19:00
Whaaaaaat

**Comment by astrofrog** [comment] 2019-05-17 12:20
See https://github.com/matplotlib/matplotlib/pull/14151 - PR forthcoming

**Comment by pllim** [comment] 2019-05-17 15:44
Thanks, @astrofrog ! #8722 did indeed fix `sty not found` error, but we still have the xfail-ed ones to deal with whenever you can get to it (no rush currently unless they are released that version soon).

**Comment by astrofrog** [comment] 2019-05-17 17:00
The xfailed ones will be fixed by https://github.com/matplotlib/matplotlib/pull/14216 :)

**Closed** 2019-05-24 17:37 UTC
Labels: testing, visualization.wcsaxes
