### ISSUE TITLE
Data corruption using FITS variable record-length column

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#8533] opened 2019-03-29 01:00 UTC
I'm not sure if this is the minimal example, but basically there are two ways that one might add a column to a table from existing FITS file.  The example below demonstrates that if the original column is a variable record-length column, then it can get corrupted when another column gets added.

**[EDIT: I originally posted this thinking that the `right.fits` output was correct, but in fact that method for adding a column is apparently not working either nor does it produce any output indicating a problem].**

```python
import numpy as np
from astropy.io import fits

# Make a FITS table with a variable-length array column
var = np.array([[45., 56],
                [11, 12, 13],
                [45, 55, 65, 75]], dtype=np.object)

c1 = fits.Column(name='var', format='PJ()', array=var)
hdu = fits.BinTableHDU.from_columns([c1])
hdu.writeto('var.fits', overwrite=True)

with fits.open('var.fits', mode='readonly', memmap=False) as hdus:
    cols = hdus[1].data.columns

    # Add a column to cols and using hdus.writeto()
    newcol = fits.Column(name='count', format='1I', array=[1, 2, 3])
    cols.add_col(newcol)
    hdus.writeto('right.fits', overwrite=True)

    # Write using hdu from BinTableHDU.from_columns()
    hdu = fits.BinTableHDU.from_columns(cols)
    hdu.writeto('wrong.fits', overwrite=True)

with fits.open('right.fits') as hdus:
    print(hdus[1].columns)
    print(hdus[1].data)

with fits.open('wrong.fits') as hdus:
    print(hdus[1].columns)
    print(hdus[1].data)
```
Running this gives this output:
```python
# right.fits [not really right since adding the column didn't actually work]
ColDefs(
    name = 'var'; format = 'PJ(4)'
)
[([45, 56],) ([11, 12, 13],) ([45, 55, 65, 75],)]

# wrong.fits [ PJ(4) converted to PJ(2) and data values dropped]
ColDefs(
    name = 'var'; format = 'PJ(2)'
    name = 'count'; format = '1I'
)
[([ 2,  0], 1) ([ 3,  8], 2) ([ 4, 20], 3)]
```

EDIT: Syntax highlighting.

**Comment by pllim** [comment] 2019-03-29 14:03
`add_col` calls
 https://github.com/astropy/astropy/blob/1b8981d55906798e3d2b7736dc424e655f05e8f9/astropy/io/fits/column.py#L1712

but it is not obvious to me how FITS is "listening" to this particular event.

Also I see a some comments like "hack for this" or "hack for that" in

https://github.com/astropy/astropy/blob/13e3af0ca28ec88deba15bd3e22cc6484b352986/astropy/io/fits/fitsrec.py#L270

which also does not inspire confidence.

*This is where I slowly back away...*

**Comment by saimn** [comment] 2019-03-29 16:45
The issue with `add_col` is known: #3647
About VLA, last time I looked (#7810) it went nowhere, so good luck ;)

**Comment by taldcroft** [comment] 2019-03-29 17:03
@saimn - thanks for the update.  FYI this issue was on behalf of a collaborator.  Workaround is to use `fitsio`, which is able to handle this case.  Hrrmph.

Is this an exact repeat of #3647?  If so feel free to mark as duplicate and close.

**Comment by saimn** [comment] 2019-03-29 17:10
There are two issues here:
-  one with `add_col` which explains why your `right.fits` file does not contain the additional column, this is #3647
- the other one is specific to the use of VLA, and corresponds to the data corruption in `wrong.fits`. I think that this is a new issue, slightly different from #7810 which was using a multi-dimensional column, but maybe the root of the issue is the same.

**Comment by saimn** [comment] 2020-10-18 21:00
Actually it seems that both issues are caused by `add_col`. If I don't use it I get the correct file:
```
In [2]: import numpy as np
   ...: from astropy.io import fits
   ...: 
   ...: # Make a FITS table with a variable-length array column
   ...: var = np.array([[45., 56],
   ...:                 [11, 12, 13],
   ...:                 [45, 55, 65, 75]], dtype=np.object)
   ...: 
   ...: c1 = fits.Column(name='var', format='PJ()', array=var)
   ...: newcol = fits.Column(name='count', format='1I', array=[1, 2, 3])
   ...: 
   ...: hdu = fits.BinTableHDU.from_columns([c1, newcol])
   ...: hdu.writeto('var.fits', overwrite=True)

In [3]: with fits.open('var.fits') as hdus:
   ...:     print(hdus[1].columns)
   ...:     print(hdus[1].data)
   ...: 
ColDefs(
    name = 'var'; format = 'PJ(4)'
    name = 'count'; format = '1I'
)
[([45, 56], 1) ([11, 12, 13], 2) ([45, 55, 65, 75], 3)]
```

**Comment by saimn** [comment] 2021-02-20 19:49
As shown above the issue is with `add_col`, so closing in favor of #3647.

**Closed by saimn** 2021-02-20 19:49 UTC
Labels: Bug, io.fits
