### ISSUE TITLE
io.fits: Erroneous 'IOError: Header missing end card'?

### ISSUE THREAD

**Issue by mommermi** [astropy/astropy#5328] opened 2016-09-14 05:31 UTC
Hi, I'm having trouble opening [this](http://134.114.60.45/tmp/test.fits) FITS file (warning: 19MB). Even this minimal script:

`from astropy.io import fits`
`hdulist = fits.open('test.fits')` 

produces an 'IOError: Header missing end card'. Using ds9, I can open the file without problems and see that the 'END' card is actually present in the header. Can anybody reproduce this error and let me know what causes it?

I am using astropy 1.2.1 and numpy 1.11.1 on a Ubuntu 16.04 system.

**Comment by pllim** [comment] 2016-09-14 13:45
Is this a duplicate of #4351?

**Comment by MSeifert04** [comment] 2016-09-14 14:02
@pllim I think so. Using

```
from astropy.io import fits
with fits.open('C:/Users/Admin/Downloads/test.fits', ignore_missing_end=True) as hdus:
    hdus.info()
```

works on Python2 (but unfortunatly it doesn't fix it with Python3.5).

**Comment by pllim** [comment] 2016-09-14 14:10
Okay, then let's keep the discussion on that other issue. I am closing this one as duplicate. Thanks!

**Closed by pllim** 2016-09-14 14:10 UTC
Labels: io.fits
