### ISSUE TITLE
FAILURES: TestUtilMode.test_mode_pil_image -- conda update astropy

### ISSUE THREAD

**Issue by luciahh** [astropy/astropy#6109] opened 2017-05-22 16:41 UTC
I have updated my astropy version running 
```
> conda update astropy 
```
Then, to test the installed version of astropy I ran the function astropy.test() and I got this error: 
```
========================================================================== FAILURES ==========================================================================
______________________________________________________________ TestUtilMode.test_mode_pil_image ______________________________________________________________

self = <astropy.io.fits.tests.test_util.TestUtilMode object at 0x1181cb190>

    @pytest.mark.skipif("not HAS_PIL")
    def test_mode_pil_image(self):
        img = np.random.randint(0, 255, (5, 5, 3)).astype(np.uint8)
        result = Image.fromarray(img)
    
        result.save(self.temp('test_simple.jpg'))
        # PIL doesn't support append mode. So it will allways use binary read.
>       with Image.open(self.temp('test_simple.jpg')) as fileobj:

anaconda/lib/python2.7/site-packages/astropy/io/fits/tests/test_util.py:91: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=5x5 at 0x112DBF8C0>, name = '__exit__'

    def __getattr__(self, name):
        if name == "__array_interface__":
            # numpy array interface support
            new = {}
            shape, typestr = _conv_type_shape(self)
            new['shape'] = shape
            new['typestr'] = typestr
            new['data'] = self.tostring()
            return new
>       raise AttributeError(name)
E       AttributeError: __exit__

anaconda/lib/python2.7/site-packages/PIL/Image.py:512: AttributeError
======================================== 1 failed, 11357 passed, 177 skipped, 43 xfailed, 3 xpassed in 387.18 seconds ========================================
1
```
Is there something I can do to fix the problem?

**Comment by pllim** [comment] 2017-05-22 16:49
Duplicate of #5590 ?

**Comment by saimn** [comment] 2017-05-23 20:37
It's indeed the same issue. But it's weird that it happens after running `conda update astropy`.

@luciahh - Can you check which package is installed in your conda env, `pil` or `pillow` ?
Sadly I didn't find a way in conda to know when a package was installed or updated, it would have been useful to know when PIL got installed in your env.

**Comment by astrofrog** [comment] 2017-06-02 22:59
@saimn @luciahh - you can find this out with ``conda list --revisions``

**Comment by saimn** [comment] 2017-06-03 20:41
@astrofrog - Excellent, thanks ! 
@luciahh - Can you check when PIL was installed with this command ?

**Comment by bsipocz** [comment] 2017-08-02 12:03
A workaround was offered in #5590, so I'm closing this issue.

**Closed by bsipocz** 2017-08-02 12:03 UTC
Labels: Close?, Duplicate, io.fits, testing
