### ISSUE TITLE
SkyCoords very slow due to FRAME_ATTR_NAMES_SET

### ISSUE THREAD

**Issue by dmopalmer** [astropy/astropy#5698] opened 2017-01-13 22:28 UTC
Can we replace FRAME_ATTR_NAMES_SET() with a lazily-reevaluated version?  This would cure a lot of speed woes with SkyCoord.

Just creating a SkyCoords object, or accessing an attribute, is very slow (milliseconds or millions of clock cycles) regardless of whether it is one point or a thousand.   Profiling shows that the time is almost all spent in FRAME_ATTR_NAMES_SET() sky_coordinate.py:38 :
```
%timeit x=SkyCoord(5,5,unit=u.deg)
100 loops, best of 3: 3.03 ms per loop
%timeit x=SkyCoord(np.linspace(0,360,1000),np.arange(0,360,1000),unit=u.deg)
100 loops, best of 3: 3.07 ms per loop
x=SkyCoord(5,5,unit=u.deg, frame='fk5')
%timeit x.equinox
1000 loops, best of 3: 846 µs per loop
%prun x=[SkyCoord(5,5,unit=u.deg) for i in range(1000)]
from astropy.coordinates.sky_coordinate import FRAME_ATTR_NAMES_SET
%timeit FRAME_ATTR_NAMES_SET()
1000 loops, best of 3: 875 µs per loop
```

The profiling shows that FRAME_ATTR_NAMES_SET calls getattr() 252 times each time it is called, which is believable given that the code walks a tree:
```
def FRAME_ATTR_NAMES_SET():
    """Set of all possible frame-specific attributes"""
    out = set()
    for frame_cls in frame_transform_graph.frame_set:
        for attr in frame_cls.get_frame_attr_names().keys():
            out.add(attr)
    return out
```

To make astropy less slow, can we do some caching so that it doesn't have to be re-evaluated every single time somebody looks at a SkyCoord attribute or makes a new SkyCoord?

(Do we have to worry about invalidating the cached value?  Can we invalidate the cached value if frame_transform_graph.frame_set is changed?).

**Comment by mhvk** [comment] 2017-01-14 00:37
Sounds like a very good idea. CC @taldcroft. Solving this may partially address #3323 as well.

**Comment by MSeifert04** [comment] 2017-01-14 00:38
I already tried that once, don't know why I abandoned that feature branch though. I'll see if I can find it again to see what made it complicated.

**Comment by MSeifert04** [comment] 2017-01-14 00:45
ok, I can't find it anymore. Sorry for the noise.

**Comment by taldcroft** [comment] 2017-01-14 01:30
@dmopalmer +1000 on this.  

> Do we have to worry about invalidating the cached value?

Yes.

> Can we invalidate the cached value if frame_transform_graph.frame_set is changed?

That sounds like a good start.  There are two places I can imagine hooking for invalidating the cache.  First, `baseframe.FrameMeta` is the metaclass that gets run when a new `Frame` class is defined.  So when a new class gets defined then you invalidate the cache.  The second is the `@frame_transform_graph.transform` decorator that registers each individual transform.  In practice either one should work, I think.

**Comment by dmopalmer** [comment] 2017-01-14 17:20
(Apologies for accidentally closing and reopening this issue.)

**Comment by pllim** [comment] 2017-01-15 00:25
I am in favor of closing this as duplicate of #5022.

**Comment by dmopalmer** [comment] 2017-01-15 04:33
I made a version that uses a cache (manually updated) to return a frozenset.

`x=SkyCoord(5,5,unit=u.deg)` goes from 3.03 ms to 1.25 ms
`x.equinox` 847 µs -> 17.3 µs
`c0.separation(c1)` 22 ms -> 4.26 ms
`c0.position_angle(c1)` 4.5 ms -> 1.76 ms

**Comment by taldcroft** [comment] 2017-01-15 12:10
@dmopalmer - cool, waiting for the PR!  I agree with @pllim this is a duplicate of #5022 and am closing.  Subsequent discussion will be in your PR anyway.

**Closed by taldcroft** 2017-01-15 12:10 UTC
Labels: coordinates, Duplicate, Performance
