### ISSUE TITLE
group_by fails with a Time column

### ISSUE THREAD

**Issue by aarchiba** [astropy/astropy#9357] opened 2019-10-12 11:16 UTC
The following code:
```python
import numpy as np

from astropy import table
from astropy.time import Time

mjds = [Time(58000, format="mjd")]

table.Table([[58000.], ["gbt"]], names=("mjd", "obs")).group_by("obs")
table.Table([mjds, ["gbt"]], names=("mjd", "obs")).group_by("obs")
```
fails on the version with a Time column but not on the version with a float column:
```
Traceback (most recent call last):
  File "../table-problem.py", line 8, in <module>
    table.Table([mjds, ["gbt"]], names=("mjd", "obs")).group_by("obs")
  File "/home/archibald/projects/astropy/astropy/astropy/table/table.py", line 2949, in group_by
    return groups.table_group_by(self, keys)
  File "/home/archibald/projects/astropy/astropy/astropy/table/groups.py", line 18, in table_group_by
    return _table_group_by(table, keys)
  File "/home/archibald/projects/astropy/astropy/astropy/table/groups.py", line 54, in _table_group_by
    table_index = get_index_by_names(table, keys)
  File "/home/archibald/projects/astropy/astropy/astropy/table/index.py", line 666, in get_index_by_names
    for index in table.indices:
  File "/home/archibald/projects/astropy/astropy/astropy/table/table.py", line 667, in indices
    for index in column.info.indices:
TypeError: 'NoneType' object is not iterable
```

**Comment by aarchiba** [comment] 2019-10-12 11:16
This behaviour is new in 4.0dev.

**Comment by mhvk** [comment] 2019-10-13 14:37
cc @taldcroft

**Comment by pllim** [comment] 2019-10-14 15:46
I have nothing useful to contribute. I was just curious and want to document this:
```python
>>> t1 = table.Table([[58000.], ["gbt"]], names=("mjd", "obs"))
>>> t1 
<Table length=1>
  mjd   obs 
float64 str3
------- ----
58000.0  gbt
>>> t1.group_by("obs")
<Table length=1>
  mjd   obs 
float64 str3
------- ----
58000.0  gbt
```
```python
>>> t2 = table.Table([mjds, ["gbt"]], names=("mjd", "obs"))
>>> t2
<Table length=1>
  mjd   obs 
 object str3
------- ----
58000.0  gbt
```

**Comment by astrofrog** [comment] 2019-10-30 18:27
I'm removing the milestone since, as a bug, this can be fixed in a bug fix release and is not critical for 4.0.

**Comment by aarchiba** [comment] 2019-11-25 17:35
I would like to point out that it's a fairly major functionality of Table that simply does not work. A bug, but a serious one.

**Comment by mhvk** [comment] 2019-11-25 18:03
Ping @taldcroft - it would be nice to fix this! Especially as it seems to be a regression.

**Comment by aarchiba** [comment] 2019-11-25 19:15
It is a regression, and one that makes it impossible for PINT to use astropy 4.

**Comment by taldcroft** [comment] 2019-11-25 19:30
Sorry.  I'll have a look later today and see if there is a quick fix.  Worst case we get a fix in 4.0.1.

**Comment by taldcroft** [comment] 2019-11-25 22:32
One line fix in #9680.

**Comment by taldcroft** [comment] 2019-11-25 22:42
@aarchiba - just one comment that it seems from your example that you are initializing a Table from a list of `Time` objects.  Prior to #9165 this was actually giving a `Column` with `object `dtype containing the individual `Time` objects.  I'm wondering if it is intentional that PINT is working with a list of `Time` instead of a single `Time` object with array values.  (Or maybe I'm just misinterpreting your comments.)

**Comment by aarchiba** [comment] 2019-11-26 00:31
PINT is probably doing it wrong. Worth checking.

**Closed** 2019-11-26 00:44 UTC
Labels: Affects-dev, Bug, table, time
