### ISSUE TITLE
Trouble Running NASA Kepler FITS File

### ISSUE THREAD

**Issue by StevenKreyche** [astropy/astropy#5282] opened 2016-08-31 03:06 UTC
I am trying to use the fits function to run a FITS file from the Kepler data set, I obtained from http://archive.stsci.edu/kepler/data_search/search.php.  This is the code I am running on Python 2.7:

import os.path
from astropy.io import fits

filename = 'kplr011904151-2009131105131_llc.fits'
os.path.isfile(filename)

hdulist = fits.open(filename) 
lightcurve =  hdulist['LIGHTCURVE']
time = lightcurve.data.field('TIME')
print(np.nanmax(time))

My issue is that the code is halted at line 5, with the error: "IOError: Header missing END card".  I am able to bypass this error with the following addition:

hdulist = fits.open(filename, ignore_missing_end=True)

However, there is now another issue that arises with the value being printed .  It returns:

print(np.nanmax(time))
2.24711748982e+307

This answer is nonsensical, as it is implying that the max time a time that is extraordinarily huge, far past even the current Julian date.  I assume that astropy should be discarding this outlier data point to prevent the rest of the code from generating poor results.  Could it be possible that NASA has changed the format of their FITS file that is incompatible with the current version of astropy, as this code worked months back with an older FITS file?

Thank you for your support

.

**Comment by astrofrog** [comment] 2016-08-31 12:32
@barentsen: tagging you since this is about your favorite telescope AND Astropy! (in case you have time to look into this)

**Comment by astrofrog** [comment] 2016-08-31 12:33
@StevenKreyche - can you check if the file works properly here: http://fits.gsfc.nasa.gov/fits_verify.html

**Comment by pllim** [comment] 2016-08-31 13:14
Personally, I think this is something for the Kepler Help Desk -- http://keplergo.arc.nasa.gov/Helpdesk.shtml

**Comment by astrofrog** [comment] 2016-08-31 13:17
It looks like the file validates at the fits_verify page though, so it may be an astropy bug...

**Comment by pllim** [comment] 2016-08-31 13:55
@astrofrog , it seems the issue here is why the data is nonsensical. Even if a file passes FITS standards verification, there is no guarantee the data are correct. Perhaps Kepler has a way to mask out "bad" data (like HST does with DQ arrays), so that is a question for Kelper Help Desk, no?

**Comment by astrofrog** [comment] 2016-08-31 14:25
@pllim - yes that's true, sorry!

**Comment by saimn** [comment] 2016-08-31 15:47
With http://archive.stsci.edu/missions/kepler/lightcurves/0119/011904151/kplr011904151-2009131105131_llc.fits I get a valid file, no missing END error:

```
In [2]: import os.path
   ...: import numpy as np
   ...: from astropy.io import fits
   ...: 
   ...: filename = 'kplr011904151-2009131105131_llc.fits'
   ...: os.path.isfile(filename)
   ...: 
   ...: hdulist = fits.open(filename)
   ...: lightcurve = hdulist['LIGHTCURVE']
   ...: time = lightcurve.data.field('TIME')
   ...: print(np.nanmax(time))
   ...: 
130.245395276
```

Maybe a corrupted file ?

**Comment by barentsen** [comment] 2016-08-31 17:39
Hi -- this is Geert from Kepler.  At this time I am unable to reproduce the `IOError` message and do not see the nonsensical time:
```Python
In [1]: from astropy.io import fits
In [2]: import numpy as np
In [3]: hdulist = fits.open('http://archive.stsci.edu/missions/kepler/lightcurves/0119/011904151/kplr011904151-2009131105131_llc.fits')
In [4]: np.nanmax(hdulist['LIGHTCURVE'].data['TIME'])
Out[4]: 130.24539527622983
```

@StevenKreyche Before anything else, could you try re-downloading the file? It is unfortunately not uncommon for FITS files to go corrupt while being transferred over http.

**Comment by StevenKreyche** [comment] 2016-08-31 20:20
Thanks for the replies everyone, I appreciate it.  I will try to re-download the file again, however I have already downloaded the file twice to check for this possible corruption.  I will update how it goes after testing this as soon as I can.

**Comment by barentsen** [comment] 2016-08-31 20:26
Please do let us know your Astropy and Python version if it fails again.

**Comment by StevenKreyche** [comment] 2016-09-01 03:43
I re-downloaded the file and it did not work again, however then I used the file from the link that you used and it worked! So the fault seems to be in the downloading process from the retrieval process which I am still unsure of.   When I mark the file,  kplr011904151-2009131105131, for ftp retrieval, it then brings me to the next page to download two files of identical names but different class, CLC and TPL.  Do you happen to know if that is where I am going wrong?

**Comment by pllim** [comment] 2016-09-01 13:55
Since this is totally unrelated to Astropy, I am closing the issue. You can still comment here but again, Kepler Help Desk is the appropriate platform for such an issue.

**Closed by pllim** 2016-09-01 13:55 UTC
Labels: Close?, io.fits

**Comment by StevenKreyche** [comment] 2016-09-01 15:43
I understand, thanks again for quick responses and help with my issue!

**Comment by barentsen** [comment] 2016-09-01 16:00
@StevenKreyche Would you mind sending me a screenshot of exactly where you obtained the file? Please e-mail this to keplergo@mail.arc.nasa.gov and we'll take it from there! Thx++

**Comment by StevenKreyche** [comment] 2016-09-01 18:49
Sure, will do!
