### ISSUE TITLE
Memory leak (or circular reference) when slicing Column

### ISSUE THREAD

**Issue by yymao** [astropy/astropy#7831] opened 2018-09-19 00:01 UTC
After slicing a Column and discarding the reference to the original Column, the memory of the Column cannot be released. It seems that the original column is still referenced somewhere invisible.  

Here's the code to reproduce the issue. When using `top` to see memory usage, one finds that it climbs up quickly (and eventually runs out of memory) even though it shouldn't.
 
```python
# WARNING: following code results in excessive memory usage

import gc
import numpy as np
from astropy.table import Column

col = Column(data=np.random.rand(10000000), name='random')
for _ in range(1000):
    col = col[col > 0.5]
    gc.collect()
```

Below are the versions that I used, installed with conda, and are running on a 64-bit linux machine:
```
astropy 3.0.4
numpy   1.15.1
python  3.6.6
```

This issue might be related to #6276 (but the fix is in 3.0.4) and/or #6346, but I am not entirely sure.

**Comment by mhvk** [comment] 2018-09-19 00:58
Thanks for reporting! I tried to reproduce and think this may be a numpy problem: I could not reproduce your problem with astropy 3.0.4, numpy 1.14.5 (Debian testing), or with current astropy but still numpy 1.14.5, but I do reproduce it when I use numpy current master, independent of astropy version; given your result, I suspect it started in numpy 1.15.

With a quick test, I found this is a problem for even the simplest possible `ndarray` subclass, so this is an upstream bug: See https://github.com/numpy/numpy/issues/11983

**Comment by mhvk** [comment] 2018-09-19 13:52
Numpy PR with fix at https://github.com/numpy/numpy/pull/11989

**Comment by pllim** [comment] 2018-09-19 16:44
Since numpy/numpy#11989 is merged, I am closing this. Thanks for the quick fix!

**Comment by yymao** [comment] 2018-09-26 18:16
Note that this issue is still not yet fully fixed in numpy 1.15.2; see https://github.com/numpy/numpy/issues/12037.

**Comment by mhvk** [comment] 2018-09-26 18:38
OK, reopening until that is solved...

**Comment by astrofrog** [comment] 2018-10-12 00:16
@mhvk - it looks like it might be solved now?

**Comment by mhvk** [comment] 2018-10-12 17:35
Yes, this is fixed in numpy master - so closing.

**Closed by mhvk** 2018-10-12 17:35 UTC
Labels: Bug, Upstream Fix Required, coordinates, table, units
