### ISSUE TITLE
Numpy 1.10 issues for io.fits

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#3854] opened 2015-06-14 00:53 UTC
@embray - sadly, it appears in some recent change in numpy-dev again broke fits. I very much suspect https://github.com/numpy/numpy/pull/5947.

**Comment by mhvk** [comment] 2015-06-14 01:36
But it may be good to check whether https://github.com/numpy/numpy/pull/5943 resolves it.

**Comment by astrofrog** [comment] 2015-06-15 16:32
Maybe Numpy should include ``astropy.test()`` into their test suite ;)

**Comment by mhvk** [comment] 2015-06-17 19:07
For the record, https://github.com/numpy/numpy/pull/5943 does not resolve the issues.

**Comment by mhvk** [comment] 2015-06-17 20:09
@charris commented (https://github.com/numpy/numpy/pull/5962#issuecomment-112922996) that 

> Fixing the astropy.io.fits problem looks like a 1.10 blocker. Could you spend some time on that?

I'll try, but I fear I may need help! @embray?

**Comment by embray** [comment] 2015-06-17 21:05
Could you provide some more details?  What test is broken?  

I don't see why one of our tests failing is necessarily a blocker for Numpy.  `astropy.io.fits` does some funky stuff anyways that may be stretching the intended use (or at the very least has workarounds).

**Comment by charris** [comment] 2015-06-17 21:09
@embray I'll let you folks decide on the severity. My thought was that `io.fits` is probably one of the more used packages in astropy at this time.

**Comment by embray** [comment] 2015-06-17 21:11
I just looked at the latest test build on Travis against numpy-dev (https://travis-ci.org/astropy/astropy/jobs/67227038) and didn't see any io.fits failures, so I'm not sure what this is referring to.

**Comment by embray** [comment] 2015-06-17 21:40
Oh, I get some failures locally though.  I guess maybe whatever was in that Travis build wasn't bleeding edge.

**Comment by embray** [comment] 2015-06-17 21:46
Oh, scratch that. I was on another branch of Astropy that didn't have my more recent fixes for Numpy.  On Python 2 all the tests pass locally with Numpy-dev.  However, I can confirm that there *are* test failures on Python 3 (which would explain why they didn't show up in Travis since we only have it testing against numpy-dev on Python 2).

I don't *think* it's anything too severe though. It appears to be an issue with string handling.

**Comment by mhvk** [comment] 2015-06-17 23:51
@embray - thanks for checking. It does seem to be just a python3 issue.

**Comment by mhvk** [comment] 2015-06-18 00:44
But a very odd one: lots of strings just "disappear"! The least convoluted test that shows the problem is
`test_table.TestTableFunctions.test_string_column_padding`. Minimal test case
```
from astropy.io import fits; from numpy import char as chararray
acol = fits.Column(name='MEMNAME', format='A10', array=chararray.array(['img1', 'p']))
acol.array
# chararray(['img1', 'p'], dtype='<U10')
ahdu = fits.BinTableHDU.from_columns([acol])
ahdu.data
# FITS_rec([(''), ('')], dtype=(numpy.record, [('MEMNAME', 'S10')]))
```

I quickly checked whether it mattered whether I passed `unicode=False` to the chararray definition, but while this changes `acol.array` it does not affect the result.

**Comment by mhvk** [comment] 2015-06-18 01:12
The problem seems to be that in `FITS_rec.from_columns`, `outarr = field[:n]` leads to an object which is *not* a view of `field` (`np.may_share_memory(field[:], field)` returns `False`). Not quite sure why that is, though.

**Comment by mhvk** [comment] 2015-06-18 02:20
The lack of memory sharing happens in `recarray.__getitem__` --
https://github.com/numpy/numpy/blob/master/numpy/core/defchararray.py#L1850
Specifically,in the `temp = val.rstrip()` stanza...

But, darn, that seems to be true for numpy 1.8 already. So, perhaps the problem is that `field` is not quite the right type of object? Well, too sleepy now to investigate further; hopefully, I at least managed to narrow it down a bit...

**Comment by ahaldane** [comment] 2015-06-18 03:12
This might be caused by my PR https://github.com/numpy/numpy/pull/5505 from January. That changed things so recarrays no longer convert arrays of string type to chararrays (which are deprecated, or similar).

I'll look in more detail tomorrow.

**Comment by embray** [comment] 2015-06-18 14:25
@ahaldane This is not directly caused by that issue, because I already modified the `FITS_rec` class (which is a subclass of `recarray`) to still return chararray objects for string arrays, at least for now, to maintain backward compat (although eventually they will be done away with...)

**Comment by embray** [comment] 2015-06-18 15:59
Confirmed what @mhvk wrote:

> The problem seems to be that in `FITS_rec.from_columns`, `outarr = field[:n]` leads to an object which is not a view of field (`np.may_share_memory(field[:], field)` returns `False`). Not quite sure why that is, though.

I'm not sure either.  I guess it has something to do with it being a chararray, which may have been more hobbled than I realized.  I can probably make a workaround for this for now.  For the next version I will work on deprecation of pyfits' use of chararrays.  (But I don't think this is a problem in Numpy; or even if it is I don't think it's a blocker for Numpy).

**Comment by embray** [comment] 2015-06-18 16:16
Ah, okay, silly me for not reading the rest of the comments already here.  It's definitely due to the rstrip.  I don't know why this worked before and then broke, but I can work around this.  It's related to my fixes in #3419

**Comment by ahaldane** [comment] 2015-06-18 16:38
Good catch both of you.

In case it's helpful, my only observation is that in python3 (but not python2) `io.fits` has its own definition of `chararray.__getitem__`, which differs from the normal getitem in the case that the strings are empty.

Compare [this](https://github.com/numpy/numpy/blob/master/numpy/core/defchararray.py#L1852) to [this](https://github.com/astropy/astropy/blob/master/astropy/io/fits/py3compat.py#L71).

Not sure if that's related to the problem...

**Comment by embray** [comment] 2015-06-18 16:50
Okay, I think I see.  The code in `chararray.__getitem__` really shouldn't be getting used when taking a slice of a chararray--the rstrip() stuff is only meant for scalar items and not slices.  On Python 2 the slice goes through the `array_slice` function in `PyArray_Type.tp_as_sequence` so this isn't an issue.  On Python 3 `array_slice` is ignored (when going through `tp_as_sequence`) so the `__getitem__` stuff is run even when it shouldn't be.

I'll submit a patch to Numpy.

**Comment by embray** [comment] 2015-06-18 16:50
I also still have no idea why this hasn't come up before, but there it is...

**Comment by mhvk** [comment] 2015-06-18 18:46
@embray, @ahaldane - great that it was found! I think it didn't come up because we weren't testing consistently against python3, plus that in my tests I found that `astropy` seems to decide to use the numpy in my system environment rather than that in the virtual environment (I end up having to remove a line in `easy_install.pth`).

As for the solution: yes, `chararray.__getitem__` seemed very odd indeed, but I was thrown off by it not having been touched in many years...

**Comment by embray** [comment] 2015-06-18 22:59
I went ahead and submitted a patch for Numpy.  I also found out why this only seems to have just broken.  It turns out I already added a workaround for this a loooong time ago: https://github.com/astropy/astropy/blob/master/astropy/io/fits/py3compat.py#L69

However, in #3419 I didn't use my monkeypatched version of chararray.  My bad :crying_cat_face:

**Comment by mhvk** [comment] 2015-06-19 00:06
Great! Better to have things fixed upstream rather than monkeypatch it ourselves; possibly, we can put the fixed version in `utils.compat.numpy`.  Link to numpy PR: https://github.com/numpy/numpy/pull/5982

**Comment by ahaldane** [comment] 2015-06-19 04:17
Nice bug hunting, that was a tricky one!

**Comment by embray** [comment] 2015-06-23 13:19
Fixed upstream!

**Comment by embray** [comment] 2015-06-23 13:20
Actually, reopening since I still need to fix the code on the Astropy side that wasn't properly using the workaround for this issue, since the workaround is still needed for older versions of Numpy

**Comment by mhvk** [comment] 2015-09-01 19:07
@embray - numpy 1.10 release candidates are out, and they give a number of problems, including these `io.fits` ones (I'll summarize the others elsewhere). Would you be able to have a look? As far as I can tell, they are identical to the ones one sees with trying numpy-dev (e.g., https://travis-ci.org/astropy/astropy/jobs/78275589).

**Comment by mhvk** [comment] 2015-09-01 19:20
actually, I was wrong: the only errors with numpy 1.10 are the ones in `io.fits`.

**Comment by embray** [comment] 2015-09-01 21:35
I thought I already fixed most of these somewhere or other.  I'll have to revisit....

**Comment by embray** [comment] 2015-09-17 19:52
Just to update, I haven't forgotten about this.  I've gotten most of the issues fixed, but there are still some bits that need a little more work....  hope to have this soon though.

**Comment by mhvk** [comment] 2015-09-17 20:33
OK, great!

**Comment by mhvk** [comment] 2015-09-29 16:59
Since numpy 1.10 is about to be released, and since ideally we support this out of the box for our 1.10, I'm putting a 1.10 milestone here. Feel free to remove if you think otherwise or it just will take too much time.

**Comment by embray** [comment] 2015-09-29 17:37
It should actually go in a patch release--more likely v1.0.6 but I'm not sure yet.

**Comment by mhvk** [comment] 2015-10-06 14:40
@embray, @astrofrog - I tagged this 1.1.0 so it isn't forgotten (I do think we should support numpy 1.10!) though as @embray mentioned above, possibly more logical is to tag it 1.0.6 since we do want to backport it as well.

**Comment by embray** [comment] 2015-10-06 17:12
Okay. I'll see what I can do.

**Comment by embray** [comment] 2015-10-06 17:23
So just as a quick update (since I haven't worked on this in a couple weeks) I have all the tests passing against Numpy 1.10 on Python 2, but a handful of failures still on Python 3 that I'm investigating (no doubt related to string handling somewhere....)

**Comment by mhvk** [comment] 2015-10-06 17:29
@embray - I started looking into it as well. The problem is that `recarray.view` has been rewritten to generally return a `recarray` even if the contents no longer warrant it. If I restore `FITSrec.view` to be that of the original recarray, only 1 failure in `io.fits` remains (which seems stringlike):
```
    if not NUMPY_LT_1_10:
        # Override view to be the same as it was in NUMPY < 1.10
        def view(self, dtype=None, type=None):
            if dtype is None:
                return np.ndarray.view(self, type)
            elif type is None:
                try:
                    if issubclass(dtype, np.ndarray):
                        return np.ndarray.view(self, dtype)
                except TypeError:
                    pass
                dtype = np.dtype(dtype)
                if dtype.fields is None:
                    return self.__array__().view(dtype)
                return np.ndarray.view(self, dtype)
            else:
                return np.ndarray.view(self, dtype, type)
```

**Comment by embray** [comment] 2015-10-06 17:40
Yeah, I know about that change.  Leave it to me...

**Comment by embray** [comment] 2015-10-06 17:41
Though I think I'll take the above `if not NUMPY_LT_1_10` code above.  Earlier I was trying to get around this in a way that was just naturally compatible with all versions, but now that I think about it your version above, while unfortunate, is a lot simpler for getting the job done :)

**Comment by charris** [comment] 2015-10-06 17:44
You probably want to use NumpyVersion for such checks. `from numpy.lib import NumpyVersion`.

**Comment by charris** [comment] 2015-10-06 17:46
Although that only works for numpy >= 1.9.0.

**Comment by embray** [comment] 2015-10-06 17:49
@charris Thanks for the tip, though this already uses a generic utility I wrote for this, and we need to support Numpy >= 1.6 so it's simpler right now not to use that.

**Comment by embray** [comment] 2015-10-06 17:50
(One known shortcoming of that utility is that it doesn't work well with pre-releases but I'm not really concerned about that right now.)

**Comment by mhvk** [comment] 2015-10-06 17:53
@embray - the last bug is one of those annoying bytes vs string ones. It can be resolved by adding, in `_scale_back_ascii` (fitsrec.py, l1128):
```
            if isinstance(value, bytes):
                value = fmt % value.decode('utf8')
            else:
                value = fmt % value
```
(note: did not test this does not introduce problems for earlier numpy/python)

**Comment by mhvk** [comment] 2015-10-06 17:54
p.s.  Obviously, it may well be better to handle this further up, in ensuring a single item from the field names is always returned as a string. But hopefully the above localization helps.

**Comment by embray** [comment] 2015-10-06 18:51
I figured that was the "one" that still failed :)

**Comment by embray** [comment] 2015-10-06 18:59
@mhvk
> Obviously, it may well be better to handle this further up, in ensuring a single item from the field names is always returned as a string. But hopefully the above localization helps.

Indeed, I think this is actually indicating something I need to fix further up.  To demonstrate, if I do the following I can create an ASCII table from a binary table like so:

```python
>>> h = fits.open('astropy/io/fits/tests/data/tb.fits')
>>> ascii_table = fits.TableHDU(data=h[1].data)
```
However, if you compare the resulting data in the ASCII table with the original binary table, you see that in the ASCII table the string field is returned as bytes instead of strings:

```python
FITS_rec([(1, 'abc', 3.7000000715255736, False),
       (2, 'xy', 6.6999997138977054, True)], 
      dtype=[('c1', '>i4'), ('c2', 'S3'), ('c3', '>f4'), ('c4', 'i1')])
>>> ascii_table.data
FITS_rec([(1, b'abc', 1.1, 'F'), (2, b'xy ', 2.0999999, 'T')], 
      dtype=(numpy.record, [('c1', 'S11'), ('c2', 'S3'), ('c3', 'S15'), ('c4', 'S1')]))
```

A further oddity is that if I open the original binary table, print the data first, and *then* create the ASCII table it outright crashes:

```python
>>> h = fits.open('astropy/io/fits/tests/data/tb.fits')
>>> h[1].data
FITS_rec([(1, 'abc', 3.7000000715255736, False),
       (2, 'xy', 6.6999997138977054, True)], 
      dtype=[('c1', '>i4'), ('c2', 'S3'), ('c3', '>f4'), ('c4', 'i1')])
>>> ascii_table = fits.TableHDU(data=h[1].data)
ERROR: AttributeError: '_AsciiColumnFormat' object has no attribute 'p_format' [astropy.io.fits.fitsrec]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/internal/1/root/src/astropy/astropy/astropy/io/fits/hdu/table.py", line 702, in __init__
    super(TableHDU, self).__init__(data, header, name=name)
  File "/internal/1/root/src/astropy/astropy/astropy/io/fits/hdu/table.py", line 303, in __init__
    self.data = data
  File "/internal/1/root/src/astropy/astropy/astropy/utils/decorators.py", line 522, in __set__
    ret = self.fset(obj, val)
  File "/internal/1/root/src/astropy/astropy/astropy/io/fits/hdu/table.py", line 438, in data
    data = FITS_rec.from_columns(new_columns)
  File "/internal/1/root/src/astropy/astropy/astropy/io/fits/fitsrec.py", line 469, in from_columns
    columns._arrays[idx] = data.field(idx)
  File "/internal/1/root/src/astropy/astropy/astropy/io/fits/fitsrec.py", line 654, in field
    converted = self._convert_other(column, field, recformat)
  File "/internal/1/root/src/astropy/astropy/astropy/io/fits/fitsrec.py", line 832, in _convert_other
    if not column.ascii and column.format.p_format:
AttributeError: '_AsciiColumnFormat' object has no attribute 'p_format'
```

I don't understand why it does this in this case, and not in the previous case. But I suspect the bugs are related.

**Comment by embray** [comment] 2015-10-06 19:22
@mhvk 
Meanwhile, even with your patch to the .view() method, I'm getting a bunch of this exception when I run the tests:

```python
astropy/io/fits/tests/test_connect.py:127: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
astropy/io/fits/hdu/base.py:1766: in writeto
    checksum=checksum)
astropy/io/fits/hdu/hdulist.py:691: in writeto
    hdu._writeto(hdulist._file)
astropy/io/fits/hdu/base.py:743: in _writeto
    data_offset, data_size = self._writedata(fileobj)
astropy/io/fits/hdu/base.py:680: in _writedata
    size += self._writedata_internal(fileobj)
astropy/io/fits/hdu/table.py:858: in _writedata_internal
    self._writedata_by_row(fileobj)
astropy/io/fits/hdu/table.py:908: in _writedata_by_row
    item = field[idx]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = chararray(['a', 'b', 'c', 'd'], 
      dtype='<U1'), obj = 0

    def __getitem__(self, obj):
>       val = ndarray.__getitem__(self, obj)
E       UnicodeDecodeError: 'utf-32-le' codec can't decode bytes in position 0-3: codepoint not in range(0x110000)
```

granted, I'm still actually on an older dev version.  So let me update to Numpy 1.10 final and see what I get...

**Comment by embray** [comment] 2015-10-06 19:40
No, I still get those failures with Numpy 1.10 final.  But it occurs to me now that I'm working on a branch where I've made other changes, so this failure might actually be related to other changes I've made in the effort to improve unicode handling in tables.  I'll figure it out...

**Comment by mhvk** [comment] 2015-10-06 19:47
It seems likely that is indeed related to the other changes, since I got zero failures with the two changes mentioned above (where I agree the second is probably treating the symptom rather than the cause).

**Comment by embray** [comment] 2015-10-07 16:28
I figured it out.  It was an issue related to byte swapping

**Comment by embray** [comment] 2015-10-07 18:04
Should be fixed by #4228

**Comment by mhvk** [comment] 2015-10-19 14:33
Changed title so that people will find there is an existing issue with numpy 1.10.

**Comment by mhvk** [comment] 2015-10-23 18:05
See #4266 for one outstanding issue still.

**Comment by eteq** [comment] 2015-11-09 10:34
@mhvk @embray - just to be clear, do we think it's ok to go ahead with v1.1 without #4266 fixed? (Or does anyone know how to fix #4266 now?)  I see that the skip mentioned in #4266 was already backported to v1.1, so it should work, but the real question is if there's a genuine issue that needs to be addressed... If we're ok with delaying that to 1.1.1, I'd say we can close this, right?

**Comment by mhvk** [comment] 2015-11-09 14:21
Not sure - I'll leave this for @embray ...

**Comment by embray** [comment] 2015-11-12 20:22
I'll try to fix it ASAP, but it's not a blocker.  It's fine to have the test marked xfail for now.

**Closed** 2015-11-12 20:22 UTC
Labels: Bug, io.fits
