### ISSUE TITLE
spherical_offsets_to gives error with array: AttributeError: 'Quantity' object has no 'hypot' member

### ISSUE THREAD

**Issue by richardgmcmahon** [astropy/astropy#5163] opened 2016-07-07 23:20 UTC
I have followed the example at:

http://docs.astropy.org/en/stable/coordinates/matchsep.html#matching-catalogs

my example/test is:

```
import astropy
print('astropy.__version__:', astropy.__version__)

from astropy.table import Table
from astropy import units as u
from astropy.coordinates import SkyCoord
from astropy.coordinates import match_coordinates_sky

from astroquery.irsa import Irsa
from astroquery.sdss import SDSS

c = SkyCoord(ra=ra1*u.degree, dec=dec1*u.degree, distance=distance1*u.kpc)  
catalog = SkyCoord(ra=ra2*u.degree, dec=dec2*u.degree, distance=distance2*u.kpc)  
idx, d2d, d3d = c.match_to_catalog_3d(catalog)  

matches = catalog[idx]  
dra, ddec = c.spherical_offsets_to(matches) 
```

no specfic catalogue is used. In my example I use astroquery as shown below:

```
region_center = SkyCoord(9.81625*u.deg, 0.88806*u.deg, frame='icrs')
allwise_irsa = Irsa.query_region(coordinates=region_center, radius=4*u.arcmin,
                            catalog='wise_allwise_p3as_psd')
print('Number of ALLWISE sources:', len(allwise_irsa))

sdss = SDSS.query_region(coordinates=region_center, radius=4*u.arcmin,
                         spectro=False,
                         photoobj_fields=['ra','dec','u','g','r','i','z'])

ra = allwise_irsa['ra']
dec = allwise_irsa['dec']
radec_allwise = SkyCoord(ra, dec,unit=(u.degree, u.degree), frame='icrs')

ra = sdss['ra']
dec = sdss['dec']
radec_sdss = SkyCoord(ra, dec,unit=(u.degree, u.degree), frame='icrs')

idx, d2d, d3d = match_coordinates_sky(radec_allwise, radec_sdss)

idx, d2d, d3d = radec_allwise.match_to_catalog_sky(radec_sdss)
print('Number of xmatch sources:', len(idx))

matches = radec_sdss[idx]
print('Test single source')
print(matches[0])
print(radec_allwise[0])
dra, ddec = radec_allwise[0].spherical_offsets_to(matches[0])
print('dra, ddec:', dra.arcsec, ddec.arcsec)

print('Test array')
dra, ddec = radec_allwise.spherical_offsets_to(matches)
```

I am using astropy 1.2.1

```
Traceback (most recent call last):
  File "spherical_offsets_to_test.py", line 55, in <module>
    dra, ddec = radec_allwise.spherical_offsets_to(matches)
  File "/home/rgm/anaconda/lib/python2.7/site-packages/astropy/coordinates/sky_coordinate.py", line 747, in spherical_offsets_to
    acoord = tocoord.transform_to(aframe)
  File "/home/rgm/anaconda/lib/python2.7/site-packages/astropy/coordinates/sky_coordinate.py", line 403, in transform_to
    new_coord = trans(self.frame, generic_frame)
  File "/home/rgm/anaconda/lib/python2.7/site-packages/astropy/coordinates/transformations.py", line 915, in __call__
    curr_coord = t(curr_coord, curr_toframe)
  File "/home/rgm/anaconda/lib/python2.7/site-packages/astropy/coordinates/transformations.py", line 833, in __call__
    newrep = newrep.represent_as(fromcoord.data.__class__)
  File "/home/rgm/anaconda/lib/python2.7/site-packages/astropy/coordinates/representation.py", line 90, in represent_as
    return other_class.from_cartesian(self.to_cartesian())
  File "/home/rgm/anaconda/lib/python2.7/site-packages/astropy/coordinates/representation.py", line 421, in from_cartesian
    s = np.hypot(cart.x, cart.y)
  File "/home/rgm/anaconda/lib/python2.7/site-packages/astropy/units/quantity.py", line 753, in __getattr__
    attr))
AttributeError: 'Quantity' object has no 'hypot' member`
```

**Comment by mhvk** [comment] 2016-07-08 00:48
This is most bizarre. Is it possible to make a simple example without astroquery? Also, what numpy version are you using?

**Comment by richardgmcmahon** [comment] 2016-07-08 07:46
<script src="https://gist.github.com/richardgmcmahon/aa883ebd8107d06ec6aee6aea3988418.js"></script>

**Comment by mhvk** [comment] 2016-08-11 16:06
@richardgmcmahon - I've been slow here, but trying to simplify your example further, I see that `spherical_offsets_to` fails for any non-scalar `SkyCoord`:
```
from astropy.coordinates import SkyCoord
sc = SkyCoord('12h00m00s', '+10d00m00s')
sc.spherical_offsets_to(sc)             
# (<Angle 2.5057879273476366e-14 deg>, <Angle 0.0 deg>)
sc = SkyCoord(['12h00m00s'], ['+10d00m00s'])
sc.spherical_offsets_to(sc)                 
# AttributeError: 'Quantity' object has no 'hypot' member
```
The problem is that a wrong transformation matrix is created, full of `Quantity` objects. It definitely is higher up than a problem with `Quantity`...

Still investigating further...

**Comment by mhvk** [comment] 2016-08-11 16:13
OK, this actually happens to be solved already in current master (perhaps somewhat inadvertently...), due to my removal of the use of numpy matrices (#5104). This will be in astropy 1.3, but I don't know whether we now should consider back-porting it to 1.2 (or even 1.0?). @eteq, @astrofrog?

**Comment by mhvk** [comment] 2016-08-11 16:15
p.s. At the very least we should include some array-shaped test cases, so that we don't regress on this...

**Comment by eteq** [comment] 2016-11-29 07:07
Given how close 1.3 is, I think we can probably call this closed if it's fixed for 1.3?  `spherical_offsets_to` is not in 1.0.x, so no need to port it there...

**Comment by eteq** [comment] 2016-11-29 07:09
That is, the actual underlying issue.  If we're agreed on that, it's probably best to create a separate issue/PR specifically about creating array-shaped tests.

**Comment by eteq** [comment] 2016-11-29 15:55
With #5519 in and passing, I think this is OK to close, so I will do so.  But @richardgmcmahon, if you're still seeing the error in the lastest master, feel free to re-open this!

**Closed by eteq** 2016-11-29 15:55 UTC
Labels: Bug, Close?, coordinates
