### ISSUE TITLE
Gauss does not decompose into cgs bases 

### ISSUE THREAD

**Issue by MaxNoe** [astropy/astropy#9830] opened 2020-01-03 14:18 UTC
### Description
The gauss unit does not decompose at all into the cgs base system, unlike e.g. StatCoulomb.

### Expected behavior
Perform unit conversions according to gaussian cgs units

### Actual behavior

Minimal example:

```python
import astropy.units as u

u.Gauss.decompose(bases=u.cgs.bases)
```

results in:
```
UnitConversionError: Unit A can not be decomposed into the requested bases
```

where it should be:
` Unit("g(1/2) / (cm(1/2) s)")`

See https://en.wikipedia.org/wiki/Gauss_(unit)

**Comment by pllim** [comment] 2020-01-03 22:51
Hi, @MaxNoe ! I think this might be a duplicate of either #5879 or #5736 

xref https://github.com/astropy/astropy/issues/5879#issuecomment-287550246

**Closed** 2020-02-13 08:30 UTC
Labels: Close?, Duplicate, closed-by-bot, units
