### ISSUE TITLE
Support for Header initialization with a dictionary

### ISSUE THREAD

**Issue by vlas-sokolov** [astropy/astropy#4648] opened 2016-02-29 13:18 UTC
The `__init__` method of the [Header class](https://github.com/astropy/astropy/blob/master/astropy/io/fits/header.py#L82-L114) states that a header can be created from an iterable. A logical choice for this option is passing a dictionary to `__init__`, but it only grabs the key, and not the value, from the dict,
```python
In [32]: fits.Header({'foo': 'bar'})
Out[32]: FOO     = ''                                                                
```
because of the following implementation:
```python
for card in cards:
    self.append(card, end=True)
```
Is it a good idea to add dictionary functionality here? Something along the lines of
```python
cards = cards.items() if type(cards) is dict else cards
```
before actually appending the values should do the trick.
(briefly discussed before here: https://github.com/pyspeckit/pyspeckit/pull/138)

**Comment by pllim** [comment] 2016-02-29 14:19
I don't see the point. You can append dictionary like this:
```python
hdr = fits.Header()
hdr.update({'foo': 'bar'})
```

**Comment by saimn** [comment] 2016-02-29 14:53
Or `fits.Header({'foo': 'bar'}.items())`. But I agree it make sense to support creating the object from a dict, as `Header` implements many dict-like methods.

**Comment by mwcraig** [comment] 2016-03-01 00:25
At a minimum a mention in the docs off how to create a `Header` from a dictionary would be nice.

**Comment by keflavich** [comment] 2016-03-01 14:50
I agree that there should be a way to initialize Headers from dictionaries, since they behave like dicts in other ways.

@pllim That's a useful workaround, but it still would be useful to have a more direct & intuitive way to initialize headers.  Apparently at least some users expect to be able to do so.

More importantly, though, it is very unlikely that a user doing `h = fits.Header({'BUNIT': 'K'})` would expect the output to have an empty `BUNIT`.

**Comment by pllim** [comment] 2016-03-01 15:04
Okay.

**Comment by mcara** [comment] 2016-03-02 07:31
I agree that it seems "natural" to be able to initialize a Header from a dictionary. However, I have a couple of concerns related to this and to what was said above.

For example, @keflavich (and others, along the same line) said: *"More importantly, though, it is very unlikely that a user doing `h = fits.Header({'BUNIT': 'K'})` would expect the output to have an empty `BUNIT`."* The fundamental problem here is that users **should not** expect code to do things it was not designed to do. Nowhere in the documentation it says that Header() accepts dictionaries! It accepts **lists of Cards** or lists of tuples. So, the notion that there is something "natural" that users expect to get when creating Headers from unsupported types is just not "natural". That is, users simply should not expect code such as `h = fits.Header({'BUNIT': 'K'})` to work (at least with existing design of the Header).

Now, let me address a concern related to use of dictionaries: they do not have order! While this may not be a serious problem in *some* applications, it is of big concern when creating real files: I would really hate if header would have CRVAL1 and CRVAL2 separated by 'BUNIT' or 'PHOTFLAM' (or SIP coefficients spread throughout a fits header). Most of the HST files created at STScI (and I assume at other institutions) have a logical structure. It would be impossible to create headers having a predefined structure when using dictionaries. Here is an example of what will happen when using dictionaries:
```python
>>> h = fits.Header({'a':11, 'b':12, 'c':13, 'd':14, 'e':15}.items())
>>> h
A       =                   11                                                  
C       =                   13                                                  
B       =                   12                                                  
E       =                   15                                                  
D       =                   14                                                  
```

Of course, creating an empty header and then using `Header.update(dict)` will result in the same mess. So, using lists of cards (or tuples) is a better choice overall unless the header created from a dictionary will be used only for internal computations and is not intended for human consumption.

```python
>>> h = fits.Header([('a', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5)])
>>> h
A       =                    1                                                  
B       =                    2                                                  
C       =                    3                                                  
D       =                    4                                                  
E       =                    5                                                  
# after the initial structure of the header was created, updating the 
# values with a dictionary is OK (the intended structure is preserved):
>>> h.update({'a':11, 'b':12, 'c':13, 'd':14, 'e':15})
>>> h
A       =                   11                                                  
B       =                   12                                                  
C       =                   13                                                  
D       =                   14                                                  
E       =                   15                                                  
```

In the end, of course if users do not care how the files look, it may be useful to allow header initialization from dictionaries.

**Comment by keflavich** [comment] 2016-03-02 07:51
@mcara Since `Headers` behave like dicts in many other ways, especially having an `update` method and a `key:value` structure, I think it is reasonable for a user to expect them to be initialized from dictionaries as well.  I'm also fairly confident that there was a previous version of pyfits/astropy.io.fits that *did* allow initialization from a dictionary, though I can't point you to it and it may be ancient now.

Since software in general does not care about the order of cards - except the first 6 or so; `SIMPLE`, `BITPIX`, `NAXIS`, `EXTEND` - I don't care about the order of the keywords.  If you want to clean up a header, using `header.update(wcs.WCS(header).to_header())` is effective for all of the WCS parameters (though I'm not sure about the SIP parameters - will those be reordered by WCS?).

However, if there really is a problem with initializing from unordered dicts, as you're suggesting, then `fits.Header(dict)` should raise an exception.  There is no need to allow *all* iterables when some will result in what I would call unexpected behavior.  Probably `update` should disallow dicts in this case too.

**Comment by saimn** [comment] 2016-03-02 08:26
If it was supporting initialization from a dict, it should also work with `OrderedDict` which is a good alternative if one want to keep the order of cards. And I think for example `Table.meta` uses an `OrderedDict`.

**Comment by mcara** [comment] 2016-03-02 16:21
@keflavich Look, if it is convenient to be able to instantiate a Header from a dict and users are OK with a disorganized header, that's fine. However, I disagree with the suggestion that just because a function accepts lists of objects (as it is clearly specified in the documentation), this somehow implies that it is "expected" that that function would work with dictionaries (well, it actually does "work" in the sense that it does not crashes). Also, if I were to dig through astropy code I am confident that I will find many examples when functions do not do a rigorous check of types of the arguments.

Again, I am OK with adding support for dict, but I would have preferred an explicit one-liner `fits.Header(dic.items())` so that users understand why their final results are disorganized.

**Comment by pllim** [comment] 2016-03-02 16:35
IMHO, there is much work to do this for little gain. But if someone wants to submit a PR, I won't object.

**Comment by astrofrog** [comment] 2016-05-11 22:50
This was done in #4663, so closing this!

**Closed by astrofrog** 2016-05-11 22:50 UTC
Labels: Feature Request, io.fits
