### ISSUE TITLE
Column added to fits table disappears when writing to a file

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy#4324] opened 2015-11-19 12:59 UTC
In the example below, I try to add a column to a fits hdu using
```
new_col = fits.Column(name='time', format='E', array=np.arange(2))
hdulist[1].data.columns.add_col(new_col)
```
That seems to work in memory, but the new column disappears when I try to save the object to a file.

```
[Hanss-MacBook-Air:~/marx/oneoff/point] hamogu% ipython
Python 2.7.10 |Anaconda 2.2.0 (x86_64)| (default, Sep 15 2015, 14:29:08) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import numpy as np

In [2]: from astropy.table import Table
/Users/hamogu/anaconda/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)

In [3]: from astropy.io import fits

In [4]: # make a table to experiment with

In [5]: tab = Table([[1,2], [3,4]])

In [6]: tab.write('tab.fits')

In [7]: # load with io.fits and try to add a column

In [8]: hdulist = fits.open('tab.fits', mode='update')

In [9]: new_col = fits.Column(name='time', format='E', array=np.arange(2))

In [10]: hdulist[1].data.columns.add_col(new_col)
Out[10]: 
ColDefs(
    name = 'col0'; format = 'K'
    name = 'col1'; format = 'K'
    name = 'time'; format = 'E'
)

In [11]: hdulist.flush()

In [12]: # Or better write to a new file?

In [13]: hdulist.writeto('tab2.fits', clobber=True)

In [14]: hdulist.close()

In [15]: # Now see what we get when reading it in again

In [16]: hdus = fits.open('tab.fits')

In [17]: print hdus[1].data
[(1, 3) (2, 4)]

In [18]: hdus = fits.open('tab2.fits')

In [19]: print hdus[1].data
[(1, 3) (2, 4)]

In [20]: # but if we use the table interface?

In [21]: tin = Table.read('tab.fits')

In [22]: print tin
col0 col1
---- ----
   1    3
   2    4

In [23]: tin = Table.read('tab2.fits')

In [24]: print tin
col0 col1
---- ----
   1    3
   2    4
```
This was discovered by @eblur . I tried to debug it (with no success) and thus decided to report it here.

@embray

**Comment by pllim** [comment] 2015-11-19 14:42
This is the source of the confusion:
```python
In [10]: hdulist[1].data.columns.add_col(new_col)
Out[10]: 
ColDefs(
    name = 'col0'; format = 'K'
    name = 'col1'; format = 'K'
    name = 'time'; format = 'E'
)
```

`add_col()` returned a new `ColDef` instead of appending to the existing one. Try this instead:

```python
with fits.open('tab.fits') as hdulist:
    newhdu = fits.BinTableHDU.from_columns(hdulist[1].data.columns + new_col)
newhdu.writeto('tab.fits', clobber=True)
```

Now you should see the new column in your original table.

**Comment by embray** [comment] 2015-11-19 16:18
Yeah, like @pllim said--this is basically a duplicate of #3065 and has the same (unfortunate) answer.

There is an open issue for fixing this in #3647, but it's probably not worth the effort compared to deprecating the old FITS table interface.

**Closed by embray** 2015-11-19 16:18 UTC
Labels: Duplicate, io.fits
