### ISSUE TITLE
Possible precision issue in astropy.time ISO formatting

### ISSUE THREAD

**Issue by timj** [astropy/astropy#3879] opened 2015-06-24 00:40 UTC
The following code:
```python
from __future__ import print_function
from astropy.time import Time

ref = 631151996
for delta in range(10):
    t1 = Time(ref+delta, format="unix", scale="utc")
    t1.precision = 6
    print(t1.unix, ">> ", t1.isot)
```
has the following output:
```
631151996.0 >>  1989-12-31T23:59:56.999954
631151997.0 >>  1989-12-31T23:59:57.999965
631151998.0 >>  1989-12-31T23:59:58.999977
631151999.0 >>  1989-12-31T23:59:59.999988
631152000.0 >>  1990-01-01T00:00:00.000000
631152001.0 >>  1990-01-01T00:00:01.000000
631152002.0 >>  1990-01-01T00:00:02.000000
631152003.0 >>  1990-01-01T00:00:03.000000
631152004.0 >>  1990-01-01T00:00:04.000000
631152005.0 >>  1990-01-01T00:00:05.000000
```
Works fine with millisecond precision but then breaks down. Integer unix times should stringify as integer seconds. There is a leap second transition involved. Given that the documentation for `astropy.time` states sub-nanosecond precision I would expect this to work fine. Are my expectations too high? Is this a limitation of `format="unix"`? Can I force the seconds to be integers somehow?

**Comment by mhvk** [comment] 2015-06-24 01:14
@timj - the problem is related to the fact that the day with a leap second is 86401 seconds long.
The docstring of `TimeUnix` states:
```
    """
    Unix time: seconds from 1970-01-01 00:00:00 UTC.
    For example, 946684800.0 in Unix time is midnight on January 1, 2000.

    NOTE: this quantity is not exactly unix time and differs from the strict
    POSIX definition by up to 1 second on days with a leap second.  POSIX
    unix time actually jumps backward by 1 second at midnight on leap second
    days while this class value is monotonically increasing at 86400 seconds
    per UTC day.
    """
```
I guess this involved a choice between being able to represent every possible time as a Unix time, or getting multiple possibilities. Here, the choice was made to make every unix second on a leap-second day effectively a bit more than one second. Not sure if there is a better/alternative solution; posix seems somewhat broken...  cc @taldcroft

**Comment by timj** [comment] 2015-06-24 04:24
Thanks. What I really want is a "seconds since epoch" time so I think I'll have to do that myself with a `TimeDelta` from Unix epoch reference. I had only looked at the top level docs and not the `TimeUnix` specifics. Sorry about that (and I still am amazed at how broken unix time really is and how life would be so much easier if they had picked TAI as the basis).

**Comment by taldcroft** [comment] 2015-06-24 11:36
You can subclass `TimeUnix` and change the epoch scale to be TAI.  Because of the meta-class magic this custom format gets registered so you can use it like any other format:
```
class TimeTaiSinceUnix(TimeUnix):
    """
    Unix time: TAI seconds from 1970-01-01 00:00:00 UTC.
    """
    name = 'taiunix'
    epoch_scale = 'tai'

In [52]: t = Time.now()

In [53]: t.taiunix
Out[53]: 1435145315.0957341

In [54]: t.taiunix - t.unix
Out[54]: 35.0
```

I'm closing this but feel free to re-open if you think there is anything that needs fixing.

**Closed by taldcroft** 2015-06-24 11:36 UTC

**Comment by taldcroft** [comment] 2015-06-24 11:38
Now it just occurred to me this might be a nice doc example for making a custom format subclass.  Maybe it's too trivial though?

**Comment by mhvk** [comment] 2015-06-24 13:05
@taldcroft - no, an excellent example, and certainly not trivial at all (at least in the sense that I would have done what @timj wrote about, use a `TimeDelta`, which needs keeping track of things).

**Comment by timj** [comment] 2015-06-24 14:39
Thanks @taldcroft that was just what I needed. I think an example like that would be great and I do wonder what argument there is against having `taiunix` part of the package itself. Actual number of seconds elapsed since unix epoch seems useful in general.

**Comment by embray** [comment] 2015-06-24 17:08
Would it be worth putting the above example in the docs?  Or is there already one like it?

**Comment by taldcroft** [comment] 2015-06-25 01:57
OK, I will do a PR for this example.
