### ISSUE TITLE
TST: (numpy dev) DeprecationWarning: `__array_wrap__` must accept context and return_scalar arguments

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/astropy#15924] opened 2024-01-22 10:16 UTC
### Description

In this week's episode: a new deprecation warning !

see for example https://github.com/astropy/astropy/actions/runs/7609351554/job/20720426870?pr=15923

xref https://github.com/numpy/numpy/pull/25409
 
"fixing" it could be as simple as adding a `return_scalar` argument to all implementations of `__array_wrap__` but
- I don't if the simplest fix will actually be portable (i.e., wouldn't it break with numpy 1.x ?)
- We probably ought to _do_ something with the new argument, not just accept it. At the moment I don't know how hard this'll be, but I'm working on it.

### How to Reproduce

Install numpy dev, build pyerfa + astropy against it, then run (for instance)
```shell
pytest astropy/time/tests/test_precision.py
```

### Versions

```
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import astropy; print("astropy", astropy.__version__)
import numpy; print("Numpy", numpy.__version__)
import erfa; print("pyerfa", erfa.__version__)
#import scipy; print("Scipy", scipy.__version__)
#import matplotlib; print("Matplotlib", matplotlib.__version__)
```
```
macOS-14.2.1-arm64-arm-64bit
Python 3.12.0 (main, Oct 27 2023, 11:50:57) [Clang 15.0.0 (clang-1500.0.40.1)]
astropy 6.1.dev349+g1d9088ad03
Numpy 2.0.0.dev0+git20240122.89eac8b
pyerfa 2.0.1.2.dev11+gc498084
```

**Comment by matteobachetti** [comment] 2024-01-22 10:32
Seeing this problem in Stingray tests agains dev versions of Numpy (in many of the tests using Astropy tables: https://github.com/StingraySoftware/stingray/actions/runs/7607203592/job/20714174462 ).

**Comment by bsipocz** [comment] 2024-01-22 20:42
I see the lot of these for astroquery, too: https://github.com/astropy/astroquery/actions/runs/7606693153/job/20712874287#step:5:14225

**Comment by pllim** [comment] 2024-01-22 20:47
Yup, also here:

* https://github.com/spacetelescope/reftools/issues/63

**Comment by larrybradley** [comment] 2024-01-23 17:58
@pllim https://github.com/astropy/photutils/issues/1697 is caused by the `__array_wrap__` in Table columns, which will be fixed in https://github.com/astropy/astropy/pull/15925

**Closed** 2024-01-23 21:48 UTC
Labels: numpy-dev
