### ISSUE TITLE
Issue with mathematical operations on astropy.table.Column

### ISSUE THREAD

**Issue by fred3m** [astropy/astropy#3820] opened 2015-06-05 03:29 UTC
For example:

    a = Column([1,2,3],unit='arcsec')
    b = Column([2000,4000,6000],unit='mas')
    a+b

displays:

    <Column dtype='int64' unit='arcsec' length=3>
    2001
    4002
    6003

Similar problems exist with multiplication, division, and subtraction. This does not seem to be an issue with quantities as

    a = 2*u.arcsec
    b = 2000*u.mas
    a+b

properly gives

    <Quantity 4.0 arcsec>

The same is true for subtraction.

**Comment by mhvk** [comment] 2015-06-05 13:50
@fred3m - thanks for raising this issue.  You have hit a very annoying situation where `Column` behaves somewhat like `Quantity`, but not quite. This is a consequence of the code for them being written before `Quantity` could support arrays. We had a very long discussion about whether to change `Column` to be like a quantity, but in the end the decision was not to, since it might break too much existing code that would simply ignore the `unit` attribute. Instead, we have a new `QTable`, in which columns are `Quantity` by default.  Please see http://docs.astropy.org/en/latest/table/mixin_columns.html#quantity-and-qtable

If you're new to astropy, I would strong recommend to start using `QTable` exclusively.

(I'll close this since we cannot really change it. cc @taldcroft in case he wants to pipe in.)

**Closed by mhvk** 2015-06-05 13:50 UTC

**Comment by taldcroft** [comment] 2015-06-05 13:55
@mhvk - this could be a good example for the docs on why to use `QTable`.  For astropy 1.1 we will make this recommendation more prominent since mixins should be stable then.

**Comment by astrofrog** [comment] 2015-06-05 14:05
@mhvk @taldcroft - I wonder if we could maybe consider raising a warning if two columns with units are combined mathematically, to point out that units are not taken into account properly? (and this would only happen if units don't match). After all, this would be a case where we are almost certain the result would be 'wrong'?

**Comment by taldcroft** [comment] 2015-06-05 14:11
That might prevent some unexpected behavior like this.  I don't see any big downside as long as we make it easy for users to disable this warning (maybe an astropy config option?).

**Comment by astrofrog** [comment] 2015-06-05 14:26
@taldcroft - yes, a config option would be fine here. The warning could even recommend QTable.

**Comment by fred3m** [comment] 2015-06-05 14:29
I agree, I was working late last night and read about QTable but forgot to update this thread. I do agree that a warning would be very helpful, but perhaps raising an error would be better. I can't think of a situation where it would ever be a good idea to add two different units. It already generates an error in some cases when trying to add tables with quantities in the columns.

**Comment by mhvk** [comment] 2015-06-05 15:00
I created a new issue (#3821) to remind us of the idea of warning or raising an exception.
