### ISSUE TITLE
Table Merge Error

### ISSUE THREAD

**Issue by astro-alice** [astropy/astropy#11991] opened 2021-07-29 21:23 UTC
### Description

We are trying to take an astropy table with missing values and merge it with another data table to replace those missing values with. The bug here is there is a masked column that doesn't want to take in those values. 

### Expected behavior

Allow us to merge two data tables and be able to replace missing values with the ones provided.

### Actual behavior

We get a TableMerge Error and don't know how to go about fixing it. 

### Steps to Reproduce

```python
from astropy.table import Table, join
import pyvo as vo
from astropy.table import Table
import astropy.io.votable
from astropy.io.votable import parse

 # In Online Mode (default), we will query the latest catalog from the Exoplanet Archive.
nasa_service = vo.dal.TAPService("https://exoplanetarchive.ipac.caltech.edu/TAP")
nasa_search_query = "SELECT pl_name, hostname,sy_snum,sy_pnum, pl_orbper, pl_orbpererr1, pl_orbpererr2, pl_orbperlim, pl_bmassj, \
                        pl_orbeccen,pl_orbeccenerr1,pl_orbeccenerr2, \
                        pl_orbeccenlim,st_spectype,st_rad,st_raderr1,st_raderr2, st_radlim,st_mass,st_masserr1, \
                        st_masserr2,st_masslim,st_age,st_ageerr1,st_ageerr2,st_agelim \
                        FROM pscomppars "
nasa_results = nasa_service.search(nasa_search_query)
nasa_table_data = vo.dal.TAPResults.to_table(nasa_results)
        
        # In Online Mode (default), we will query the latest catalog from the eu catalog for missing data .
eu_service =vo.dal.TAPService("http://voparis-tap-planeto.obspm.fr/tap")
eu_search_query = "SELECT target_name, star_name, mass, mass_error_min, mass_error_max, mass_sin_i, mass_sin_i_error_min, mass_sin_i_error_max \
                    period, period_error_min, period_error_max, \
                    eccentricity,eccentricity_error_min, eccentricity_error_max FROM exoplanet.epn_core"   
eu_results = eu_service.search(eu_search_query)
eu_table_data = vo.dal.TAPResults.to_table(eu_results)
        
       
        #merge nasa_table_data & eu_table_data tables here and name it merged_table using Archive colunm names
names = ('target_name','star_name','period', 'period_error_min', 'period_error_max', 'eccentricity','eccentricity_error_min', 'eccentricity_error_max')
new_names = ('pl_name','host_name', 'pl_orbper', 'pl_orbpererr2','pl_orbpererr1', 'pl_orbeccen','pl_orbeccenerr2','pl_orbeccenerr1')
eu_table_data.rename_columns(names, new_names)
#print(t)
        

print(join(nasa_table_data, eu_table_data, join_type='right'))


---------------------------------------------------------------------------
TableMergeError                           Traceback (most recent call last)
/tmp/ipykernel_802/2606867453.py in <module>
     31 
     32 
---> 33 print(join(nasa_table_data, eu_table_data, join_type='right'))

/opt/conda/lib/python3.9/site-packages/astropy/table/operations.py in join(left, right, keys, join_type, uniq_col_name, table_names, metadata_conflicts, join_funcs)
    382 
    383     col_name_map = OrderedDict()
--> 384     out = _join(left, right, keys, join_type,
    385                 uniq_col_name, table_names, col_name_map, metadata_conflicts,
    386                 join_funcs)

/opt/conda/lib/python3.9/site-packages/astropy/table/operations.py in _join(left, right, keys, join_type, uniq_col_name, table_names, col_name_map, metadata_conflicts, join_funcs)
   1125                                       .format(arr_label, name))
   1126             if hasattr(arr[name], 'mask') and np.any(arr[name].mask):
-> 1127                 raise TableMergeError('{} key column {!r} has missing values'
   1128                                       .format(arr_label, name))
   1129 

TableMergeError: Left key column 'pl_orbper' has missing values
```

### System Details
 Linux-3.10.0-862.14.4.el7.x86_64-x86_64-with-glibc2.31
Python 3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:32:32) 
[GCC 9.3.0]
Numpy 1.21.0
astropy 4.2.1
Scipy 1.7.0
Matplotlib 3.3.4

**Comment by eerovaher** [comment] 2021-07-29 22:43
Does calling
```python
join(nasa_table_data, eu_table_data, join_type='right', keys='pl_name')
```
result in something useful?

**Comment by astro-alice** [comment] 2021-07-30 00:33
when we print that, it shows us a table with values for rows that don't have any values. However, when we print that we get this warning 
`WARNING: MergeConflictWarning: In merged column 'pl_name' the 'description' attribute does not match (Planet Name != Standard IAU name of target (from a list related to target class), case sensitive).  Using Standard IAU name of target (from a list related to target class), case sensitive for merged output [astropy.utils.metadata]`
My research partner was wondering why when adding keys something is displayed compared to when keys isn't specified? Also, we tried `join_type='left'` and that didn't work as well.
But thank you for that insight!

**Comment by pllim** [comment] 2021-07-30 13:47
I cannot tell if this is because something is wrong with the query results or actual table bug. Is there some minimally reproducible example not involving calls to `pyvo`?

**Comment by eerovaher** [comment] 2021-07-30 14:05
Table columns can have a `description` attribute, and in this case both input tables have a `description` for `'pl_name'`. The warning is letting you know that the two descriptions are different and which of the two was chosen for the output. You didn't see this warning before because the code produced an error instead of a merged table. I don't think the warning alone is cause for concern. It is possible to prevent this warning from appearing by adding `metadata_conflicts='silent'` to the function call.

**Comment by JPGlaser** [comment] 2021-07-30 19:26
Hey all,
I'm Alicia's mentor for her REU. So right now we are pulling data down from NASA's Exoplanet Archive's Composite catalog. The idea is to take that Astropy Table and replace missing values with values present in Exoplanet.EU's Archive. They both use the vo interface for pulling data down via a query. We have to rename the columns in the Exoplanet.EU table to match that of the NASA Exoplanet Archive.

Switching to `'pl_name'` as the key does help. However, we end up with duplicate columns instead of a proper merge/replace:
```
<TableColumns names=('pl_name','hostname_1','sy_snum','sy_pnum','pl_orbper_1','pl_orbpererr1_1','pl_orbpererr2_1','pl_bmassj','pl_orbeccen_1','pl_orbeccenerr1_1','pl_orbeccenerr2_1','st_rad','st_raderr1','st_raderr2','st_mass','st_masserr1','st_masserr2','st_age','st_ageerr1','st_ageerr2','hostname_2','mass','mass_error_min','mass_error_max','mass_sin_i','mass_sin_i_error_min','mass_sin_i_error_max','pl_orbper_2','pl_orbpererr2_2','pl_orbpererr1_2','pl_orbeccen_2','pl_orbeccenerr2_2','pl_orbeccenerr1_2')>
```

Is there any way to just directly map one Astropy Table's columns to another and replace only the missing values (rather than going row by row in a loop)? I feel like there should be a vectored version of this ...

~ Joe G.

**Comment by eerovaher** [comment] 2021-07-30 20:50
If the inputs of `join()` contain matching non-key column names then the output will indeed contain columns from both tables, which are renamed to be distinguishable. It is possible to have some control over how the renaming gets done, see the documentation for details: https://docs.astropy.org/en/v4.2/table/operations.html#column-renaming

Let `column_names` be the the column names of your primary data and `replacement_column_names` the corresponding column names of the replacement values. If a column contains missing values then its `mask` attribute tells where the missing values are. So you can do something like
```python
for col, replacement_col in zip(column_names, replacement_column_names):
    mask = joined_table[col].mask
    joined_table[col][mask] = joined_table[replacement_col][mask]
    joined_table.remove_column(replacement_col)    # If it's not needed anymore it can be removed
```
This has to be done using the joined table because `join()` makes sure the rows are aligned.

**Comment by pllim** [comment] 2021-07-30 21:53
Hello, all. If the answers provided solve your problem, please close the issue. Thanks!

**Comment by astro-alice** [comment] 2021-07-30 21:59
Testing it out still, but will do!

**Closed** 2021-08-02 20:27 UTC
Labels: question, table
