### ISSUE TITLE
Bayesian Blocks warning

### ISSUE THREAD

**Issue by ebouff** [astropy/astropy#6922] opened 2017-12-01 19:00 UTC
Hi, 
Whenever I use Bayesian Blocks with the events methods, I get the following warning:

> WARNING: p0 does not seem to accurately represent the false positive rate for event data. It is highly recommended that you run random trials on signal-free noise to calibrate ncp_prior to achieve a desired false positive rate. [astropy.stats.bayesian_blocks]

Does anyone know how I can make sure that my p0 accurately represents the false positive rate ? I know there's already threads about this but I could not find a satisfying answer about what to do. 

Also, how does this code compare with Peter William's ? (https://newton.cx/~peter/2013/05/bayesian-blocks-analysis-in-python/) Is it more robust ?

Thanks

**Comment by pllim** [comment] 2017-12-04 15:58
There were some prior discussions about the warning in #4927 and #5826 regarding the warning, but perhaps @jakevdp could chime (thanks!)?

**Comment by bsipocz** [comment] 2017-12-04 16:18
For generic usage questions like this, there are more appropriate forums to use than GitHub issues (that are meant for bug reports or feature requests). 
In the future, please consider one of the alternatives as there may be more people to better assist you there (e.g. facebook group, astropy mailing list, etc http://www.astropy.org/help.html)

**Comment by crawfordsm** [comment] 2017-12-04 16:40
As this has come up several times now, I'd like to leave this open as an issue to improve the documentation on this section.   Thanks for asking about it @ebouff.   Although I'm not really sure how it differs from Peter's implementation, and it might be useful to ask about this in some of the other forums mentioned by @bsipocz if @jakevdp or @Quantum-cross do not chime in.

**Comment by bsipocz** [comment] 2017-12-04 16:54
@crawfordsm - I take #4927 is already about improving the documentation, and then this is a duplicate and thus be closed.

**Comment by jakevdp** [comment] 2017-12-04 21:06
Hi @ebouff – you can make certain that ``p0`` represents accurate false positive rates by running Monte Carlo simulations that reflect the structure of the problem you're using it for. This is exactly how the ``p0`` value in the implementation was arrived at (as described in the Scargle paper).

This warning was meant to prevent people from assuming that ``p0`` is correctly calibrated for every possible situation. In my opinion, it leads to more confusion than clarity, and should probably be removed in favor of more detailed documentation.

**Comment by crawfordsm** [comment] 2018-05-01 19:41
Following @bsipocz suggestion closing as it is a duplicate of #4927, but please re-open @ebouff if you have further questions.

**Closed by crawfordsm** 2018-05-01 19:41 UTC
Labels: Docs, Duplicate, stats
