### ISSUE TITLE
Handling of logarithmic units in tables inconsistent and breaks matching

### ISSUE THREAD

**Issue by jbrinchmann** [astropy/astropy#5342] opened 2016-09-18 16:35 UTC
I have tried to use logarithmic units in my table columns but this seems to work less than optimal - at least the way I have created them. I have an example piece of code below, but the two problems are:

1. A column created to have  a logarithmic unit [e.g.: t['log_R'] = u.dex(u.pc)], is created as a Quantity column and has no 'physical' attribute:
   e.g. t['log_R'].quantity.value works, but t['log_R'].quantity.physical gives

```
/Users/jarle/anaconda/lib/python2.7/site-packages/astropy/units/quantity.pyc in __getattr__(self, attr)
    732                 "'{0}' object has no '{1}' member".format(
    733                     self.__class__.__name__,
--> 734                     attr))
    735 
    736         def get_virtual_unit_attribute():

AttributeError: 'Quantity' object has no 'physical' member
```

2. When trying to join tables with logarithmic quantities, the join fails with:

```
Traceback (most recent call last):
  File "/Users/jarle/Desktop/example_problem.py", line 27, in <module>
    print astropy.table.join(tbl1, tbl2, keys=['col1'])
  File "/Users/jarle/anaconda/lib/python2.7/site-packages/astropy/table/operations.py", line 188, in join
    _merge_col_meta(out, [left, right], col_name_map, metadata_conflicts=metadata_conflicts)
  File "/Users/jarle/anaconda/lib/python2.7/site-packages/astropy/table/operations.py", line 70, in _merge_col_meta
    elif left_attr != right_attr:
  File "/Users/jarle/anaconda/lib/python2.7/site-packages/astropy/units/function/core.py", line 291, in __ne__
    self.funtional_unit != getattr(other, 'function_unit', other))
AttributeError: 'DexUnit' object has no attribute 'funtional_unit'
```

An example code that reproduces this is given below. 

This is certainly not what I expected, but it might be that I have misunderstood the way I should indicate units on the columns! 

```
# Show how joins break when logarithmic units are included  - the first join succeeds 
# and prints out the combined table, while the second fails
import astropy.units as u
from astropy.io import ascii
import astropy.table

# Create two simple example tables
t1 = """
a 5.2
b 7.2
"""

t2 = """
a 6.3
c 7.4
b 1.2
"""

tbl1 = ascii.read(t1, format='fixed_width_no_header', delimiter=' ')
tbl2 = ascii.read(t2, format='fixed_width_no_header', delimiter=' ')

# Simple units:
tbl1['col2'].unit = u.kilometer

print astropy.table.join(tbl1, tbl2, keys=['col1'])

# Logarithmic units
tbl1['col2'].unit = u.dex()
print astropy.table.join(tbl1, tbl2, keys=['col1'])

```

**Comment by mhvk** [comment] 2016-09-19 20:42
@jbrinchmann - there is both a problem with your example and a real bug. The problem is that if you use `ascii.read`, you get a `Table` rather than a `QTable`, which does not have full support for quantities. However, even with `QTable.read(t1, format='ascii.fixed_width_no_header', delimiter=' ')`, one gets `Column` instances, which are (incorrectly) converted to `Quantity` by setting the unit. 
...
I should have a fix for that shortly....

**Comment by mhvk** [comment] 2016-09-19 21:13
OK, it turned out this exposed not one but two bugs, but with #5345, this should be fixed!

**Comment by mhvk** [comment] 2016-09-19 21:13
p.s. Thanks for reporting!

**Closed** 2016-09-24 15:09 UTC
Labels: Bug, table, units
