### ISSUE TITLE
Test Failures Encountered When Running Pytest in Astropy Development Version

### ISSUE THREAD

**Issue by TanviPooranmal** [astropy/astropy#15788] opened 2023-12-23 20:47 UTC
### Description

While testing the ``Astropy Development Version``, some tests failed running ``Pytest``.

### Expected behavior

All the tests should have ``passed`` or otherwise ``xfailed``.

### How to Reproduce

1. Setup ``Astropy Development Version`` as stated [here](https://docs.astropy.org/en/latest/development/workflow/get_devel_version.html#try-the-development-version).
2. Then run the following command:

    ```python
    pip install -e ".[test]"
    ```
3. The test completes with ``FAILURES``.

```python
======================================================================== short test summary info ========================================================================
FAILED astropy/coordinates/tests/test_representation.py::TestCartesianRepresentation::test_transform_non_contiguous_matrix - assert False
FAILED astropy/visualization/tests/test_units.py::test_units - ValueError: Failed to find font DejaVu Sans:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0, and fallback to the default font was disabled
FAILED astropy/visualization/wcsaxes/tests/test_display_world_coordinates.py::TestDisplayWorldCoordinate::test_cube_coords - ValueError: Failed to find font DejaVu Sans:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0, and fallback to the default font was disabled
FAILED astropy/visualization/wcsaxes/tests/test_display_world_coordinates.py::TestDisplayWorldCoordinate::test_cube_coords_uncorr_slicing - ValueError: Failed to find font DejaVu Sans:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0, and fallback to the default font was disabled
FAILED astropy/visualization/wcsaxes/tests/test_misc.py::test_slicing_warnings - ValueError: Failed to find font DejaVu Sans:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0, and fallback to the default font was disabled
FAILED astropy/visualization/wcsaxes/tests/test_misc.py::test_grid_type_contours_transform - ValueError: Failed to find font DejaVu Sans:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0, and fallback to the default font was disabled
FAILED astropy/visualization/wcsaxes/tests/test_misc.py::test_bbox_size[0.2] - assert False
FAILED astropy/visualization/wcsaxes/tests/test_misc.py::test_bbox_size[1e-08] - assert False
================================================= 8 failed, 28248 passed, 317 skipped, 246 xfailed in 874.83s (0:14:34) =================================================
```

### Versions

Windows-10-10.0.22631-SP0
Python 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]
astropy 6.1.dev238+gf5909190d5
Numpy 1.24.3
pyerfa 2.0.0
Scipy 1.11.1
Matplotlib 3.8.2

**Comment by MridulS** [comment] 2023-12-23 20:53
Interesting, this is a matplotlib issue.
Can you try running this code in a python console in your dev env:
```
import matplotlib
matplotlib.get_cache_dir()
```

**Comment by TanviPooranmal** [comment] 2023-12-24 10:03
@MridulS - I tried accessing the cache directory of ``Matplotlib``, seems like it doesn't exist in my system.
```python
>>> import matplotlib

>>> matplotlib.get_cache_dir()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 1
----> 1 matplotlib.get_cache_dir()

File ~\anaconda3\Lib\site-packages\matplotlib\_api\__init__.py:217, in caching_module_getattr.<locals>.__getattr__(name)
    215 if name in props:
    216     return props[name].__get__(instance)
--> 217 raise AttributeError(
    218     f"module {cls.__module__!r} has no attribute {name!r}")

AttributeError: module 'matplotlib' has no attribute 'get_cache_dir'
```
I checked the ``Matplotlib`` directory and found only one file [``fontlist-v330.json``](https://github.com/astropy/astropy/files/13761396/fontlist-v330.json).

**Comment by MridulS** [comment] 2023-12-25 12:58
Hmm, could you just try doing the installation again? (start from scratch and remove the environment). This is probably a matplotlib installation issue on windows, not an astropy one.

**Comment by eerovaher** [comment] 2023-12-25 16:56
The one test that fails in `coordinates` is a regression test for a bug in `pyerfa` that was fixed in `pyerfa` 2.0.1.1 (see #15511). Our CI tests use the latest version of `pyerfa`, so the test succeeds, but `astropy` also supports older versions without the bugfix: https://github.com/astropy/astropy/blob/b50e9cfc8bf862816ea9ddd7193f0cf801b44c71/pyproject.toml#L43 It is therefore indeed possible to have a failing test even though the `astropy` development version is properly installed. There are two simple possible solutions to this: 1) skip the test if the installed version of `pyerfa` doesn't have the bugfix, or 2) update the minimum required `pyerfa` version. Both would be simple to implement, but I'm not sure which of the two would be preferable.

The test is not failing in our `oldestdeps` CI job because that job also uses `pyerfa` 2.0.1.1 despite that being the latest version: https://github.com/astropy/astropy/blob/b50e9cfc8bf862816ea9ddd7193f0cf801b44c71/tox.ini#L72
To me it looks like the `oldestdeps` job isn't properly configured, but `tox` configuration is not really my area of responsibility, so I'm not sure if any changes should be made there.

**Comment by eerovaher** [comment] 2024-01-10 16:18
I don't know about the failures regarding `matplotlib`, but the problem in `coordinates` is real.

**Comment by mhvk** [comment] 2024-01-11 16:14
@eerovaher - nice sleuthing! I think we should go for your second suggestion, of updating our minimum requirement. `pyerfa` is a bit special compared to `numpy`, etc., in that we are in control of it (used to be developed inside astropy), and I think the particular bug could bite people in ways that are very opague.

**Comment by mhvk** [comment] 2024-01-11 16:22
See #15865 for discussion about how we should set `olddestdeps` (and version limits more generally).

**Comment by eerovaher** [comment] 2024-03-08 18:56
The problem in `coordinates` has been fixed and it looks like the problems in `visualization` were not caused by us.

**Closed by eerovaher** 2024-03-08 18:56 UTC
Labels: testing, Bug, coordinates
