### ISSUE TITLE
Signature missing on pypi

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#10937] opened 2020-10-26 09:31 UTC
### Description

Previous versions of astropy always came signed by @bsipocz; however the current version is not. It would be good to keep tis since it ensures a trust chain of the package for Debian.

### System Details

astropy 4.1 on PyPI

**Comment by Cadair** [comment] 2020-10-26 09:46
The most recent releases have been uploaded directly from the CI, there is probably no practical way to sign them with any meaning when doing automated deploys?

**Comment by pllim** [comment] 2020-10-26 13:33
Can't we create a PGP for Astropy team email or something? @astrofrog ?

**Comment by pllim** [comment] 2020-10-26 13:34
👍 to signed release.

**Comment by Cadair** [comment] 2020-10-26 13:35
But what's that signature verifying? We don't control the host so there is no promise that there isn't someone doing something malicious there.

**Comment by pllim** [comment] 2020-10-26 13:37
I thought the PyPI upload part is still manual? Is it not anymore?

**Comment by astrofrog** [comment] 2020-10-26 13:47
If this was crucial we could go back to having the sdist be a manual upload

**Comment by pllim** [comment] 2020-10-26 13:50
A release being made once every few months, I would prefer a signed one even if it means one manual step back. If we nightly release or something, it's different, but we don't. Let's wait and see what @olebole thinks.

**Comment by olebole** [comment] 2020-10-26 14:01
Pragmatically, I could live without the signature. I just think it is a plus in security if I can simply prove that the source tarball is an "official" one. Together with my own signature on the Debian changes, people can easily verify the integrity of the package.
IMO it would also be just useful if someone would have a look to the resulting PyPI tarball and give the "all seem OK here" signature -- as I do f.e. for each Debian upload.
So, I would support having a manual signature.
However, this obviously puts some load to someone, which I do not want to push.

**Comment by astrofrog** [comment] 2020-10-26 14:28
It's a tricky topic because auto generating the sdist does have benefits in the sense it is not sensitive to the state of the repo of the person doing the release or permissions etc - so in that sense the auto generated sdist is more 'reliable'. Does anyone know if we can sign a release that is already on PyPI?

**Comment by pllim** [comment] 2020-10-26 14:30
> Does anyone know if we can sign a release that is already on PyPI?

When I forgot to sign mine a year or two or ten ago, I couldn't find a way other than do a new release.

**Comment by olebole** [comment] 2020-10-26 18:47
Can't one just upload the signature file? The tarball would remain unchanged.

**Comment by bsipocz** [comment] 2020-10-26 18:56
you can certainly upload the signature after the rest is uploaded. Whether it's good practice to download the tarball, sign it, and upload the signature is a separate question though, I would be much more comfortable to make the tarball locally and sign off on it than doing this, but ymmv.

**Comment by Cadair** [comment] 2020-10-26 20:09
Is our tarball build reproducible, could someone build a tarball locally and validate the hash vs the one already uploaded to pypi and then sign it?

**Comment by pllim** [comment] 2020-10-26 20:15
Might as well do manual tarball upload at this point?

**Comment by Cadair** [comment] 2020-10-26 20:19
Might as well not sign it at all...

**Comment by Cadair** [comment] 2020-10-26 20:21
I am really not sure what the purpose of the cryptographic signature is. A signature verifies something by a trusted party. What are we trying to verify and what's the trust chain?

**Comment by olebole** [comment] 2020-10-27 07:21
@plim for the current moment, one could just download the tarball, verify it, create the signature file and upload it.
@Cadair The signature certifies that the tarball really contains the actual astropy release and was not (accidently or on purpose) changed. If f.e. the Astropy account on PyPI is compromised, someone else could just replace the tarball.

**Comment by Cadair** [comment] 2020-10-27 09:39
I am pretty sure you can't change the tarball once it's been uploaded to PyPI, so it would have to be compromised. I am not sure I see much value in a human downloading the tarball and "verifying" it without also automating that verification. Humans are fallible, and are not about to check every line of the source or anything.

What I *think* you are asking for is some cryptographic verification that the source tarball is built off the tag. We could automate this on hardware we control.

**Comment by olebole** [comment] 2020-10-27 09:42
@Cadair One could just upload a compromised 4.1.1.

**Comment by Cadair** [comment] 2020-10-27 09:44
(I pressed send on the last message a bit quick, I edited it.)

The best way to mitigate the risk of a malicious tarball being uploaded is to massively reduce the people who have upload access to PyPI imo. We really only need one account and the automated token.

**Comment by Cadair** [comment] 2020-10-27 09:46
I would also argue, that given you are (I assume) blindly trusting the GPG key, it's not a lot different form blindly trusting the PyPI username & password of the person doing the upload?

(This discussion is really interesting, and something I have spent a long time wondering about in the past. I am just trying to drill down to what the actual threat model is and what we are trying to attest to with a signature.)

**Comment by Cadair** [comment] 2020-10-27 10:16
What I meant by "blindly" was you haven't signed Brigitta's GPG key? Do you have an idea of what extra value (outside of workflow things) a signature by a "astropy developers" key would give you over the implicit PyPI auth promise? I am trying to understand the benefit to know if it's worth looking into or not!

**Comment by olebole** [comment] 2020-10-27 11:09
@Cadair 
> What I meant by "blindly" was you haven't signed Brigitta's GPG key?

No, I pragmatically used the same key since 2017 (version 2.0.1). Since we have many versions since then, I am pretty convinced that I use the right key.

> Do you have an idea of what extra value (outside of workflow things) a signature by a "astropy developers" key would give you over the implicit PyPI auth promise?

A signature adds security that does not depend on the trust to the server (or any transport/storage medium): even if PyPI is compromised (or the Astropy account is), one can still verify that the file is valid. Even when (in some distant future) PyPI is switched off, this can be verified.

**Comment by astrofrog** [comment] 2020-10-27 11:49
We are currently moving to a model where each release might have a different release manager - in fact I released 4.0.3 and @eteq did 4.1. There might also be new people in future. So at that point you really would need a proper way to trust the keys each time there is a new release manager.

Wouldn't it be more useful to ensure we have reproducible sdist builds and you can check whether building the tag yourself gives the same result?

Or could we make a key specifically for Azure to sign releases with?

**Comment by Cadair** [comment] 2020-10-27 12:07
> A signature adds security that does not depend on the trust to the server (or any transport/storage medium): even if PyPI is compromised (or the Astropy account is), one can still verify that the file is valid. Even when (in some distant future) PyPI is switched off, this can be verified.

This is fair, however, it's important to note that you are trusting the word of the person with the signing key. How important is it that that is a human? If that's not important then we could have Azure sign the release, but then we are trusting the word of Azure rather than a person.

**Comment by olebole** [comment] 2020-10-27 12:08
@astrofrog 
Different people would probably not be a problem for me -- I can (and would) cross-check the key and use a new one if the old fails. I could even have several keys here. Main problem then would be how I can trust the individual keys if they live only short-term; they would probably need to be signed by others.

Reproducibility is ofcourse another way; recreating the "upstream tarball" is however not part of the Debian workflow.

I am not sure whether a special (shared) key is a good idea, it may be a compromise of security and comfort. The disadvantage is that it is somehow shared, and may diffuse over time and changing release maintainers. But that is the danger with any organizational key.

**Comment by bsipocz** [comment] 2020-10-27 13:56
A shared key sounds weird, not something I would be comfortable with using to sign stuff. I either sign off on it or not, but if I'm then it should be with my own one, and later own the mistakes went into it.

**Comment by Cadair** [comment] 2020-10-27 14:00
Well the shared key would be for automated signing, which would be on infrastructure the project setup and therefore it could attest the "officialness" of the release. Or at least that would be the theory.

**Comment by bsipocz** [comment] 2020-10-27 14:10
Yes, that seems fine, assuming only a very small infrastructure group has access in addition to the machine.

**Comment by pllim** [comment] 2020-11-03 16:52
Should probably decide a way forward before the next release (4.2?).

**Comment by Cadair** [comment] 2020-11-04 15:05
I am still not sure I have a clear understanding of the benefits here vs the cost of adding manual steps back into what is a nicely automated release pipeline.

Specifically, I do not feel that having Azure sign the tarball is any more secure than just uploading to PyPI unsigned. As Azure is untrusted hardware, so I am not sure what it would be attesting to by signing the release in that manner.

In addition to this, I am :-1: on putting a human back in the loop of the build & push part of the release procedure.

**Comment by olebole** [comment] 2020-11-05 19:03
I agree with @Cadair that as long as the procedure is automated (and not fully under our control), a signature does not additional security, so it is probably useful to not apply it. Also just having someone manually checking the result ans signing is too much effort.

**Comment by pllim** [comment] 2020-12-03 19:52
So, we have a consensus that signature is no longer necessary?

**Comment by olebole** [comment] 2020-12-03 19:53
That is my understanding.

**Comment by pllim** [comment] 2020-12-03 19:54
Closing then. Thanks!

**Closed by pllim** 2020-12-03 19:54 UTC
Labels: Bug, Close?, Release, wont-fix
