### ISSUE TITLE
0e69c4db introduced asv regression

### ISSUE THREAD

**Issue by mdboom** [astropy/astropy#3232] opened 2014-12-18 17:24 UTC
I'm not saying this an issue to be resolved -- just reporting it FYI.

0e69c4db appears to have introduced a major speed regression in many of the `io.ascii` benchmarks:
- AastexFloat
- AastexInt
- FixedWidthFloat
- FixedWidthInt
- FixedWidthNoHeaderFloat
- FixedWidthNoHeaderInt
- FixedWidthString
- IpacFloat
- IpacInt
- IpacString
- CoreSuite.time_base_splitter
- CoreSuite.time_continuation_inputter
- CoreSuite.time_convert_vals

It's a very simple change -- I suspect most of the time is just from adding a `__getitem__` vs. not having one.  I'm not sure if there's a way to fix the bug in another way, or if it matters.  Like I say, just reporting it at this point.

**Comment by taldcroft** [comment] 2015-01-15 14:52
@astrofrog @mhvk - I think the performance regression introduced by #3095 is pretty serious and we should seriously considering backing it out for 1.0 (unless of course we can figure a way to keep that patch functionality without impacting performance).

As I mentioned above, #3095 fixes a bug that it is more in the category of corner case, while performance for integer access of column values is front-and-center in terms of normal use cases.

**Comment by mhvk** [comment] 2015-01-15 18:06
I think the way to solve it is to have a separate column class for the case where each item is multidimensional, in which the only difference would be that there is a `__getitem__` method. Then, in `Column.__new__`, one can view the `ndarray` appropriately.

Anyway, that as a possible solution. Since it is not trivial, I'm OK with pulling #3095 out for now, and reraising it as an issue.

**Comment by taldcroft** [comment] 2015-02-18 19:26
@astrofrog @embray - my fault for not milestoning this properly, but I just remembered about this issue today.  I really would like to back out #3095 since it introduces a serious performance regression for a common use case.  Probably too late for 1.0, but hopefully there will be a bug fix release soon after where we can take out #3095?

**Comment by embray** [comment] 2015-02-18 21:36
Was just talking to @astrofrog about this, and we're leaning toward maybe waiting 'til 1.0.1 to sort this out, as most users are unlikely to actually notice the performance regression.

**Comment by embray** [comment] 2015-08-12 20:51
This was basically fixed by #3930 .  However, #3915 has demonstrated the need for further workaround to this, and in fact implements `get_item` methods so that it does not have to override (and hence slow down) `__getitem__` for the common cases.

I have a crazy idea that might significantly ease this problem, and also possibly do away with the need for the hack in #3930.  What if we define mixin classes that *just* define the `__getitem__` implementation?  From my own experimentation it seems that most of the overhead of defining `__getitem__` in the subclass relates to looking up `'__getitem__'` in the class `__dict__`, as well as looking up the base implementation (whether via `super()`, `np.ndarray.__getitem__`, or a global variable referencing the former).  Implementing a type in Cython with a `__getitem__` slot eliminates much of this overhead.  Then, directly calling `PyArray_Type.tp_as_mapping.mp_subscript` for the general case takes care of the rest.  I have a prototype demonstrating the basic concept, and my timing shows that it's just as fast as the base implementation for the most common case.  I'll try to have something up in a bit.

**Comment by bsipocz** [comment] 2017-05-10 14:03
Closing this as #3930 is solved this and #3915 also seems to be addressed. We may want to revisit this and reopen once asv is up and running again and this turns out to be an issue with current master.

**Closed by bsipocz** 2017-05-10 14:03 UTC
Labels: Performance
