### ISSUE TITLE
Issue when slicing a row in a Table

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#14007] opened 2022-11-15 14:48 UTC
### Description

Slicing a row can under some circumstances return the whole column

### Steps to Reproduce

```python
In [1]: from astropy.table import Table
   ...: t = Table()
   ...: t['a'] = [1, 2, 3]
   ...: t['b'] = [4, 5, 6]
   ...: t['c'] = [7, 8 ,8]
```

### Actual behavior

```python
In [2]: t[0]
Out[2]: 
<Row index=0>
  a     b     c  
int64 int64 int64
----- ----- -----
    1     4     7

In [3]: t[0][1:]
Out[3]: 
<Column name='b' dtype='int64' length=3>
4
5
6
```

### Expected behavior

I was expecting something like:

```python
In [3]: t[0][1:]
Out[3]: 
(4, 7)
```

which is what ``tuple(t[0])[1:]`` would return or something similar or a Row object with the first entry missing but I understand maybe that's difficult to do, but I certainly didn't expect to see the whole column.

**Comment by neutrinoceros** [comment] 2023-12-14 16:46
I think this is actually a dupe of #4068

**Closed** 2023-12-19 15:23 UTC
Labels: table, Bug, Duplicate
