### ISSUE TITLE
download_files_in_parallel with cache=False doesn't work on Windows

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#6662] opened 2017-10-05 06:44 UTC
In #6658 I had problems locally with `cache=False`. For example:

```
from astropy.utils.data import download_files_in_parallel
import os
dwn = download_files_in_parallel(['http://www.google.de', 'http://www.wikipedia.org'])
assert all([os.path.isfile(f) for f in dwn]), dwn
```

This fails locally - while it works if one just adds `cache=True`:

```
from astropy.utils.data import download_files_in_parallel
import os
dwn = download_files_in_parallel(['http://www.google.de', 'http://www.wikipedia.org'], cache=True)
assert all([os.path.isfile(f) for f in dwn]), dwn
```

Could be a Windows-thing with subprocesses that remove temp-files created upon exit. But I don't have the experience to make more than guesses. Would be interesting to know if that's a fundamental problem with that function or just a Windows thing.

**Comment by saimn** [comment] 2017-10-05 09:46
Works for me on Linux, so it may be a Windows specific issue with the temporary directory (on Linux files goes on `/tmp` when `cache=False`).

**Comment by pllim** [comment] 2017-10-05 13:52
Any chance #6651 fixed this problem?

**Comment by drdavella** [comment] 2017-10-05 13:57
@pllim, no I don't believe #6651 is related to this issue.

**Comment by drdavella** [comment] 2017-10-05 13:59
@MSeifert04 any chance you can provide a traceback for the error?

**Comment by MSeifert04** [comment] 2017-10-05 14:02
@drdavella No error, it works fine. Just the files aren't there. 

My suspicion is that the files are clean up when "not cached" as soon as the subprocess ends.

**Comment by drdavella** [comment] 2017-10-05 14:36
Sorry, it's not clear to me what the actual problem is here. When you use `cache=False` the files get downloaded but then they are not available to other processes? That seems like it would be the expected behavior to me, but I'm not sure I understand the issue.

**Comment by saimn** [comment] 2017-10-05 14:41
Actually it is expected that files are deleted at the process exit when `cache=False`, there is even a config item for this:
```
In [2]: astropy.utils.data.conf.delete_temporary_downloads_at_exit
Out[2]: True
```
The weird point here is that the files are deleted before the process exit: if `assert all([os.path.isfile(f) for f in dwn])` fails, it means that the files are not available just after download ?!

**Comment by MSeifert04** [comment] 2017-10-05 14:49
Well it uses multiprocessing to download the files. Probably uses seperate processes that clean up the files on Windows and ones that share the temp-files with the main process on *NIX systems.

**Comment by saimn** [comment] 2017-10-05 15:07
@MSeifert04 - Good point, but exit handlers are not called when subprocesses terminate (https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Process.terminate).

From a quick search, it's not obvious if the behavior is different for Windows, https://bugs.python.org/issue23489 suggests atexit handlers are not executed, but http://perfspy.blogspot.fr/2017/05/python-multiprocessing-behaves.html shows the opposite. If you want to investigate :wink:

**Comment by drdavella** [comment] 2017-10-05 15:16
@saimn I have been looking into the same kinds of questions: https://stackoverflow.com/a/34507557

It doesn't seem like there's any magic in the temporary directories being used on Windows (as far as I can tell), so my guess would be it has something to do with astropy accidentally removing the files too early. Unfortunately I've been having trouble getting a development environment set up on a Windows VM or else I would start to do some investigation myself.

**Comment by MSeifert04** [comment] 2017-10-05 15:20
Well, astropy just uses a [global variable](https://github.com/astropy/astropy/blob/master/astropy/utils/data.py#L1179-L1181) to store to-be-removed files.

I don't know if there's any online python interpreter but if there's something I could change/do to test it I would welcome suggestions.

**Comment by saimn** [comment] 2017-10-05 15:32
@MSeifert04 - just to be sure, could you check if the exit handler is called when the sub-processes terminate ? (https://github.com/astropy/astropy/blob/master/astropy/utils/data.py#L1184)

**Comment by pllim** [comment] 2017-10-05 17:47
>  could you check if the exit handler is called when the sub-processes terminate ?

Yes. On Windows, with `cache=False`, when I insert a print statement right before `os.remove` there, I see both downloaded files deleted (even before the progress bar reports that download is finished).

When `cache=True`, it is still called but nothing is done because `_tempfilestodel` is an empty list.

Maybe this is beyond our control and we should just document this behavior in the API?

**Comment by MSeifert04** [comment] 2017-10-05 17:51
> even before the progress bar reports that download is finished

That makes sense because before the status-update is made the process has to signal "termination" to the super process. So it's subprocess->download->statusupdate+termination->cache-clear...

Thanks for testing it. I had some problems with `print` in the subprocess and then the other two PRs sidetracked me.

**Comment by MSeifert04** [comment] 2017-10-05 17:53
Well, we could make the cache-list a process-safe queue that is protected in subprocesses and only touched in the main process. But that's probably a lot easier said than done... Maybe we should rather set `cache=True` for the single downloads, collect them and add them to the to-be-deleted list after the multiprocess finished.

**Comment by drdavella** [comment] 2017-10-05 17:56
This would be a bit of a hack, but could you maybe stash the PID of the main process in a global variable and then condition the `atexit` code on `if os.getpid() == main_pid` or some such?

**Comment by MSeifert04** [comment] 2017-10-05 17:59
Are these not-cached files deleted on Linux/Mac after the main process terminates? I mean a list is not thread-safe and if the subprocesses don't call `atexit` how does the main process know what to delete?

**Comment by pllim** [comment] 2017-10-05 18:05
Re Linux -- I inserted the same print statements on my Linux install and no, `_deltemps` is not called at all regardless of `cache` value.

Re: hacking for this to work on Windows -- I don't think it is worth the effort; Who knows what can of worms that can be. We wouldn't want to cause Windows users to get BSOD.

Off topic: I can't figure out how to copy-and-paste text from Anaconda command prompt on Windows. The best I could do is take a screen shot, which is not desirable. Arghh.

**Comment by MSeifert04** [comment] 2017-10-05 18:09
@pllim Even when the main process ends?

**Comment by pllim** [comment] 2017-10-05 18:16
Yes. It never showed up in the Python session in which I ran these commands that you provided (but slightly modified):
```python
import os
from astropy.utils.data import download_files_in_parallel
dwn = download_files_in_parallel(['https://www.google.com', 'https://www.wikipedia.org'], cache=False)
assert all([os.path.isfile(f) for f in dwn]), dwn
```

**Comment by saimn** [comment] 2017-10-05 22:56
Oh yes indeed, on Linux it's also broken as the subprocess cannot modify the global variable `_tempfilestodel` (the list of downloaded files). It's not a big issue as files go to `/tmp` which is usually cleaned at reboot (though its depend on Linux distributions I believe).

> @MSeifert04 : That makes sense because before the status-update is made the process has to signal "termination" to the super process. So it's subprocess->download->statusupdate+termination->cache-clear...

No, the doc states that exit handlers are not called in sub-processes, and https://bugs.python.org/issue23489 shows that this was also the case on Windows. As seen from the comments in this report, this behavior is expected, and so it was closed as "not a bug", but it seems that now Windows behaves differently. So for me, this a Python stdlib bug. 

But I also agree with the conclusion of the #6667, we should not spend too much time on this ;). Maybe we could just add a warning and force `cache=True` ?

**Comment by eteq** [comment] 2021-04-12 16:27
This now gives the following warning:
```
WARNING: Disabling the cache does not work because of multiprocessing, it will b e set to ``"update"``. You may need to manually remove the cached files with cle ar_download_cache() afterwards. [astropy.utils.data] 
```
whether this "doesn't work" is a bit ambiguous, but it's really a larger issue: the locking mechanisms means *any* platform will have issues with multiprocessing and caching, which is why that warning is triggered in the first place.  So closing this since at least it doesn't *fail* anymore in windows.

**Closed by eteq** 2021-04-12 16:27 UTC
Labels: Bug, Windows, utils
