### ISSUE TITLE
Stacking table but column incompatible

### ISSUE THREAD

**Issue by Vincentbruga** [astropy/astropy#14965] opened 2023-06-20 13:52 UTC
### Description

I am using vstack to merge two table. I have a column for the Right ascension in the two table and i keep getting this error : 

"The 'ra' columns have incompatible types: ['str1024', 'float64']"

Im 90% sure that first they are both float value so its strange but is there a way to merge even if its string or float ? I dont really care since its only used to print them , i wont be doing operation with it.

### How to Reproduce

1. Get package from '...'
2. Then run '...'
3. An error occurs.

```python
# Put your Python code snippet here.
```

### Versions

import platform; print(platform.platform())
import sys; print("Python", sys.version)
import astropy; print("astropy", astropy.__version__)
import numpy; print("Numpy", numpy.__version__)
import erfa; print("pyerfa", erfa.__version__)
import scipy; print("Scipy", scipy.__version__)
import matplotlib; print("Matplotlib", matplotlib.__version__)

**Comment by pllim** [comment] 2023-06-20 14:50
Hello! Can you please provide a minimally reproducible example? Your data probably needs to be sanitized but hard to tell without more info. Thanks.

**Comment by eerovaher** [comment] 2023-06-29 18:07
[Apparently this is a duplicate of #4507](https://github.com/astropy/astropy/issues/4507#issuecomment-1598943027), so I'm closing this issue.

**Closed by eerovaher** 2023-06-29 18:07 UTC
Labels: table, Bug, Needs-clarification, Duplicate
