### ISSUE TITLE
io.ascii should name columns starting from 'col0' not 'col1'

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/astropy#7016] opened 2017-12-21 15:29 UTC
When using `astropy.io.ascii.read` to read a file with no header, the columns are named by default as `colX` where `X` is a number starting from 1.

This is counter-intuitive to me, as Python reads indexes starting from zero. I would expect the first column to be named `col0`.

**Comment by pllim** [comment] 2017-12-21 15:49
IMHO, "the ship has sailed" on this one...

Such a change now would be confusing and break backward-compatibility, no? For example, custom converters written as instructed in http://docs.astropy.org/en/latest/io/ascii/read.html#converters to use `col1` for first column would now magically read the second one with this change.

Whether 0 or 1 is more intuitive is quite subjective too.

**Comment by hamogu** [comment] 2018-03-06 20:22
I agree with @Gabriel-p that starting with `col0` would be more in line with normal Python conventions, and is potentially confusing. Thanks a lot for pointing that out.

However, @pllim is absolutely right that this would potentially break user code in ways that may not lead to an exception but just silently produce wrong results. I wish we would have chosen 0 originally, but it's not important enough to potentially break code now and thus I'm deciding to close this for now. Please add comments or re-open if you disagree.

(If you try `tab["col0"]` at least you'll get an error so you know you need to check what's going on.)

**Closed by hamogu** 2018-03-06 20:22 UTC
Labels: io.ascii

**Comment by Gabriel-p** [comment] 2018-03-31 21:28
I just realized that this is even inconsistent with how `Tables` work. If I create a table as:

    aa = Table([ra, dec])

the columns will be named by default:

       col0   col1

as one would expect.

I think this issue should be reopened and reconsidered.

**Comment by taldcroft** [comment] 2018-04-01 11:36
Yes, in the end the pain caused by making this change and the almost certain breakage of code is not worth fixing this minor inconsistency.

**Comment by astrofrog** [comment] 2018-04-01 12:30
I wonder if we should keep a list somewhere of 'known inconsistencies/sub-optimal APIs' in case we ever develop new APIs?

**Comment by taldcroft** [comment] 2018-04-02 10:19
@astrofrog - are you imagining an astropy <N>.0 that starts fresh with any API changes / annoyances that have accrued over the years?
