### ISSUE TITLE
np.nanmedian vs quantities

### ISSUE THREAD

**Issue by fdeugenio** [astropy/astropy#15225] opened 2023-08-23 23:36 UTC
### Description

When slicing a quantity array and taking the nanmedian along one axis, I get an exception. The behaviour depends on the size of the slice. `numpy` channels slices with less than 600 values to a different algorithm, which then results in an exception.

Affected packages: numpy==1.25.2; astropy==5.3.2
Was working: numpy==1.24.1; astropy==5.2.1

### Expected behavior

Always raise, or always work. Was working before.

### How to Reproduce

```
from astropy import units
import numpy as np

heights = np.zeros((5000, 100, 100))*units.km
mask = np.zeros(heights.shape[0], dtype=bool)

print('This is all good (empty mask)')
print(np.nanmedian(heights[mask, :, :], axis=0))

mask[:1000] = True
print('Oh, this is also good (many pixels)')
print(np.nanmedian(heights[mask, :, :], axis=0))

print('Buckle up')
mask = np.zeros(heights.shape[0], dtype=bool)
mask[:100] = True

print('This works (different axes)')
print(np.nanmedian(heights[mask, :, :], axis=(1,2)))

print('This broken')
print(np.nanmedian(heights[mask, :, :], axis=0))
```

### Versions

Affected packages: numpy==1.25.2; astropy==5.3.2
Was working: numpy==1.24.1; astropy==5.2.1

**Comment by byrdie** [comment] 2023-08-24 01:12
@fdeugenio, thanks for raising this issue. Can you please post the full traceback of the error?

**Comment by fdeugenio** [comment] 2023-08-24 08:07
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[1], line 22
     19 print(np.nanmedian(heights[mask, :, :], axis=(1,2)))
     21 print('This broken')
---> 22 print(np.nanmedian(heights[mask, :, :], axis=0))

File /science/projects/327_jekyll/pyjek/lib/python3.10/site-packages/astropy/units/quantity.py:1846, in Quantity.__array_function__(self, function, types, args, kwargs)
   1833 # A function should be in one of the following sets or dicts:
   1834 # 1. SUBCLASS_SAFE_FUNCTIONS (set), if the numpy implementation
   1835 #    supports Quantity; we pass on to ndarray.__array_function__.
   (...)
   1843 # function is in none of the above, we simply call the numpy
   1844 # implementation.
   1845 if function in SUBCLASS_SAFE_FUNCTIONS:
-> 1846     return super().__array_function__(function, types, args, kwargs)
   1848 elif function in FUNCTION_HELPERS:
   1849     function_helper = FUNCTION_HELPERS[function]

File /science/projects/327_jekyll/pyjek/lib/python3.10/site-packages/numpy/lib/nanfunctions.py:1217, in nanmedian(a, axis, out, overwrite_input, keepdims)
   1214 if a.size == 0:
   1215     return np.nanmean(a, axis, out=out, keepdims=keepdims)
-> 1217 return function_base._ureduce(a, func=_nanmedian, keepdims=keepdims,
   1218                               axis=axis, out=out,
   1219                               overwrite_input=overwrite_input)

File /science/projects/327_jekyll/pyjek/lib/python3.10/site-packages/numpy/lib/function_base.py:3823, in _ureduce(a, func, keepdims, **kwargs)
   3820             index_out = (0, ) * nd
   3821             kwargs['out'] = out[(Ellipsis, ) + index_out]
-> 3823 r = func(a, **kwargs)
   3825 if out is not None:
   3826     return out

File /science/projects/327_jekyll/pyjek/lib/python3.10/site-packages/numpy/lib/nanfunctions.py:1094, in _nanmedian(a, axis, out, overwrite_input)
   1089 else:
   1090     # for small medians use sort + indexing which is still faster than
   1091     # apply_along_axis
   1092     # benchmarked with shuffled (50, 50, x) containing a few NaN
   1093     if a.shape[axis] < 600:
-> 1094         return _nanmedian_small(a, axis, out, overwrite_input)
   1095     result = np.apply_along_axis(_nanmedian1d, axis, a, overwrite_input)
   1096     if out is not None:

File /science/projects/327_jekyll/pyjek/lib/python3.10/site-packages/numpy/lib/nanfunctions.py:1109, in _nanmedian_small(a, axis, out, overwrite_input)
   1102 """
   1103 sort + indexing median, faster for small medians along multiple
   1104 dimensions due to the high overhead of apply_along_axis
   1105 
   1106 see nanmedian for parameter usage
   1107 """
   1108 a = np.ma.masked_array(a, np.isnan(a))
-> 1109 m = np.ma.median(a, axis=axis, overwrite_input=overwrite_input)
   1110 for i in range(np.count_nonzero(m.mask.ravel())):
   1111     warnings.warn("All-NaN slice encountered", RuntimeWarning,
   1112                   stacklevel=5)

File /science/projects/327_jekyll/pyjek/lib/python3.10/site-packages/numpy/ma/extras.py:734, in median(a, axis, out, overwrite_input, keepdims)
    731     else:
    732         return m
--> 734 return _ureduce(a, func=_median, keepdims=keepdims, axis=axis, out=out,
    735                 overwrite_input=overwrite_input)

File /science/projects/327_jekyll/pyjek/lib/python3.10/site-packages/numpy/lib/function_base.py:3823, in _ureduce(a, func, keepdims, **kwargs)
   3820             index_out = (0, ) * nd
   3821             kwargs['out'] = out[(Ellipsis, ) + index_out]
-> 3823 r = func(a, **kwargs)
   3825 if out is not None:
   3826     return out

File /science/projects/327_jekyll/pyjek/lib/python3.10/site-packages/numpy/ma/extras.py:816, in _median(a, axis, out, overwrite_input)
    813     s = np.ma.sum(low_high, axis=axis, out=out)
    814     np.true_divide(s.data, 2., casting='unsafe', out=s.data)
--> 816     s = np.lib.utils._median_nancheck(asorted, s, axis)
    817 else:
    818     s = np.ma.mean(low_high, axis=axis, out=out)

File /science/projects/327_jekyll/pyjek/lib/python3.10/site-packages/numpy/lib/utils.py:1111, in _median_nancheck(data, result, axis)
   1108 if np.ma.isMaskedArray(n):
   1109     n = n.filled(False)
-> 1111 if not n.any():
   1112     return result
   1114 # Without given output, it is possible that the current result is a
   1115 # numpy scalar, which is not writeable.  If so, just return nan.

File /science/projects/327_jekyll/pyjek/lib/python3.10/site-packages/astropy/units/quantity.py:2001, in Quantity.any(self, axis, out)
   2000 def any(self, axis=None, out=None):
-> 2001     raise TypeError(
   2002         "cannot evaluate truth value of quantities. "
   2003         "Evaluate array with q.value.any(...)"
   2004     )

TypeError: cannot evaluate truth value of quantities. Evaluate array with q.value.any(...)

```

**Comment by byrdie** [comment] 2023-08-24 13:49
I would think `np.ma.isMaskedArray(n)` would return `False` in your case since you did not pass in a masked array, but I haven't reviewed all the code up to this point.

Seems to me the problem is the use of the `any()` method here. I think we need to either open a PR with numpy to find an alternative expression, or overload `np.nanmedian` since it's currently marked as `SUBCLASS_SAFE`.

**Comment by fdeugenio** [comment] 2023-08-24 13:55
Uhm, unless I did some mistake I think that from inside _median_nancheck n does satisfy the condition. The additional issue is this: `filled` returns normally a masked array, which would work okay with `any`. But if no elemenst are masked (as per my example), then `filled` returns a ndarray, which then triggers `any` from `quantity.py` with grim consequences

**Comment by byrdie** [comment] 2023-08-24 22:22
Ah, I see. Sorry about that! I will need to think more on what should be done here.

**Closed** 2023-08-27 06:48 UTC
Labels: units, Bug
