### ISSUE TITLE
Improve coordinate equality comparison

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#2154] opened 2014-02-27 20:53 UTC
As mentioned in #1832, coordinate comparisons currently just check that the internal angles and distances are the same:

```
>>> c1 = ICRS(1, 2, unit=['deg','deg'])
>>> c2 = FK5(1, 2, unit=['deg','deg'])
>>> c1 == c2
True
```

A more nuanced implementation of equality is needed, details TBD in APE5.

**Comment by bsipocz** [comment] 2017-07-31 22:33
The original snippet is not working any more, and
```
c1 = SkyCoord(1, 2, unit='deg',frame='icrs')
c2 = SkyCoord(1, 2, unit='deg',frame='fk5')
c1 == c2
False
```

so I wonder whether this can be closed now?

**Comment by adrn** [comment] 2017-09-19 19:49
I'm closing this because it is a duplicate of #3182 and I think the discussion there is more relevant now.

**Closed** 2017-09-19 19:49 UTC
Labels: Close?, coordinates, Effort-medium, Package-intermediate
