### ISSUE TITLE
Astropy not installing anymore with pip in Python 3.3?

### ISSUE THREAD

**Issue by matteobachetti** [astropy/astropy#3281] opened 2015-01-08 22:52 UTC
Hi all,
I'm developing a code that uses astropy for a few things like FITS tables and astronomical units.
I use tox to test the installation with different Python versions (2.6, 2.7, 3.3, 3.4), and to verify that a few crucial unit tests work correctly.
But tox's virtual environment with Python 3.3 is throwing me the following error when it tries to install astropy with pip:

```
  Using version 0.4.2 (newest of versions: 0.4.2, 0.4.1, 0.4, 0.4rc2, 0.4rc1, 0.3.2, 0.
3.1, 0.3, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.2, 0.1)
  Downloading from URL https://pypi.python.org/packages/source/a/astropy/astropy-0.4.2.
tar.gz#md5=6dc4f643cde37ba0a8b4967dc8becee8 (from https://pypi.python.org/simple/astrop
y/)
  Running setup.py (path:/Users/meo/devel/spyder_projects/maltpynt/.tox/py33/build/astropy/setup.py) egg_info for package astropy
    git submodule command failed unexpectedly:
    error: pathspec '.tox/py33/build/astropy/astropy_helpers' did not match any file(s) known to git.
    Did you forget to 'git add'?
   
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/Users/meo/devel/spyder_projects/maltpynt/.tox/py33/build/astropy/setup.py", line 18, in <module>
        import astropy
    ImportError: No module named 'astropy'
    Complete output from command python setup.py egg_info:
    git submodule command failed unexpectedly:

error: pathspec '.tox/py33/build/astropy/astropy_helpers' did not match any file(s) known to git.

Did you forget to 'git add'?



Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Users/meo/devel/spyder_projects/maltpynt/.tox/py33/build/astropy/setup.py", line 18, in <module>

    import astropy

ImportError: No module named 'astropy'

----------------------------------------
Cleaning up...
  Removing temporary dir /Users/meo/devel/spyder_projects/maltpynt/.tox/py33/build...
Command python setup.py egg_info failed with error code 1 in /Users/meo/devel/spyder_projects/maltpynt/.tox/py33/build/astropy
Exception information:
Traceback (most recent call last):
  File "/Users/meo/devel/spyder_projects/maltpynt/.tox/py33/lib/python3.3/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/Users/meo/devel/spyder_projects/maltpynt/.tox/py33/lib/python3.3/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/Users/meo/devel/spyder_projects/maltpynt/.tox/py33/lib/python3.3/site-packages/pip/req.py", line 1229, in prepare_files
    req_to_install.run_egg_info()
  File "/Users/meo/devel/spyder_projects/maltpynt/.tox/py33/lib/python3.3/site-packages/pip/req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/Users/meo/devel/spyder_projects/maltpynt/.tox/py33/lib/python3.3/site-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in /Users/meo/devel/spyder_projects/maltpynt/.tox/py33/build/astropy
```
I work on Mac OSX 10.9.5. The Python version is 3.3.5.
It worked correctly a few days ago. pip installed astropy and all dependencies flawlessly.
2.6, 2.7 and 3.4 don't give this problem.
Thanks in advance for your help,
Matteo

**Comment by matteobachetti** [comment] 2015-01-12 08:44
Apparently, this went away. Maybe a problem with the pip servers? 
Closing.

**Comment by embray** [comment] 2015-01-13 15:57
I don't think this is anything specifically to do with pip.   Could you please provide the steps you took to produce this issue, if at all possible?  This could be a real issue with astropy-helpers.

**Comment by matteobachetti** [comment] 2015-01-13 19:47
Hi Erik,
The steps are easy: I just ran `tox` using this tox.ini file and starting from a clean tox environment (I had deleted all previous virtualenvs):
```
[tox]
envlist = py26, py27, py33, py34

[testenv]
commands = {envpython} tests/utests.py
envlist = py27, py33, py34
deps =
    numpy
    astropy
    scipy
    matplotlib
    netCDF4

[testenv:py26]
envlist = py26
deps =
    numpy
    astropy
    scipy
    matplotlib
    netCDF4
    unittest2
```
I didn't have the time to produce a "more minimal" case before the problem went away, sadly. It was weird, because I had already used tox for a couple weeks with no problems also with py33.

**Comment by embray** [comment] 2015-01-14 17:11
Thanks for the info.  It's entirely possible that if it was a problem with pip that it was just something transient.  I use tox with a Python 3.3 environment as well and hadn't seen this problem, but I wonder if it might have had something to do with the fact that it was being used in a different project, and not Astropy itself.  So I'll have to try that out.  If I can't reproduce though I'll probably close this again.  Thanks for the report!

**Comment by embray** [comment] 2015-01-15 16:16
Well, I wasn't able to find any obvious way to reproduce this.  And looking closely at the error again it's strange--it's running the astropy setup.py, but then failing to import astropy, as though the source archive didn't fully extract or something (normally astropy imports itself from the source during installation, and this shouldn't be a problem).  So I'll go ahead and close this as some kind of transient environment issue until and unless it comes up again.

**Closed by embray** 2015-01-15 16:16 UTC
Labels: astropy-helpers, installation, Needs-clarification, Package-expert
