### ISSUE TITLE
scikit-learn 1.4: KFold raises error on astropy Table input

### ISSUE THREAD

**Issue by maxnoe** [astropy/astropy#15911] opened 2024-01-18 17:43 UTC
### Description

See:

* https://github.com/scikit-learn/scikit-learn/issues/28174

### Expected behavior

Works...

```
❯ python sklearn_astropy.py
sklearn: 1.3.2, astropy: 6.0.0
(array([2, 3]), array([0, 1]))
```

### How to Reproduce

Minimal example in scikit-learn issue

```python
from astropy.table import Table
from sklearn.model_selection import KFold
from astropy import __version__ as astropy_version
from sklearn import __version__ as sklearn_version

print(f"sklearn: {sklearn_version}, astropy: {astropy_version}")


t = Table({"a": [1, 2, 3, 4], "b": [4, 5, 6, 7]})

fold = KFold(2)
print(next(fold.split(t)))
```

```
sklearn: 1.4.0, astropy: 6.0.0
Traceback (most recent call last):
File "sklearn_astropy.py", line 12, in
print(next(fold.split(t)))
^^^^^^^^^^^^^^^^^^^
File "sklearn/model_selection/_split.py", line 367, in split
X, y, groups = indexable(X, y, groups)
^^^^^^^^^^^^^^^^^^^^^^^
File "sklearn/utils/validation.py", line 476, in indexable
check_consistent_length(*result)
File "sklearn/utils/validation.py", line 427, in check_consistent_length
lengths = [_num_samples(X) for X in arrays if X is not None]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "sklearn/utils/validation.py", line 427, in
lengths = [_num_samples(X) for X in arrays if X is not None]
^^^^^^^^^^^^^^^
File "sklearn/utils/validation.py", line 351, in _num_samples
if _use_interchange_protocol(x):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "sklearn/utils/validation.py", line 288, in _use_interchange_protocol
return not _is_pandas_df(X) and hasattr(X, "dataframe")
^^^^^^^^^^^^^^^^
File "sklearn/utils/validation.py", line 2073, in _is_pandas_df
if hasattr(X, "columns") and hasattr(X, "iloc"):
^^^^^^^^^^^^^^^^^^
File "astropy/table/table.py", line 1046, in iloc
return TableILoc(self)
^^^^^^^^^^^^^^^
File "astropy/table/index.py", line 949, in init
super().init(table)
File "astropy/table/index.py", line 832, in init
raise ValueError("Cannot create TableLoc object with no indices")
ValueError: Cannot create TableLoc object with no indices
```

### Versions

scikit-learn 1.4
astropy 6.0

**Comment by maxnoe** [comment] 2024-01-18 17:44
Seems to be the same error as #5973

**Comment by pllim** [comment] 2024-01-18 17:52
Seems like sklearn also blindly assumes only pandas has "iloc"

```
File "sklearn/utils/validation.py", line 2073, in _is_pandas_df
if hasattr(X, "columns") and hasattr(X, "iloc"):
```

**Comment by maxnoe** [comment] 2024-01-18 17:53
Still, raisinh an error on a friendly `__hasattr__`

**Comment by pllim** [comment] 2024-01-18 17:55
Do you think this is a duplicate of https://github.com/astropy/astropy/issues/5973 ?

**Comment by maxnoe** [comment] 2024-01-18 18:39
Same underlying issue, yes.

**Comment by maxnoe** [comment] 2024-01-18 19:05
Attempt of a fix in https://github.com/astropy/astropy/pull/15913

**Closed** 2024-02-06 21:18 UTC
Labels: table, Bug
