### ISSUE TITLE
Failing sphinx gallery examples should emit proper warnings

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#5019] opened 2016-06-02 22:18 UTC
Currently, Travis passes even if some gallery examples fail. However, if we make the gallery emit warnings when there is a failure, the Travis sphinx build will then fail, allowing us to catch issues.

cc @adrn @eteq

**Comment by eteq** [comment] 2016-06-02 22:19
Prompted by #4996

**Comment by adrn** [comment] 2016-07-03 16:22
Is this now fixed @eteq ?

**Comment by astrofrog** [comment] 2016-07-25 18:08
Noe that there is now a proper solution in the sphinx gallery extension for making sure that failing examples cause the build to error: https://github.com/sphinx-gallery/sphinx-gallery/pull/122

**Comment by cdeil** [comment] 2017-01-27 08:13
@monodera ran into this issue and reported it on the Astropy mailing list:
https://mail.scipy.org/pipermail/astropy/2017-January/004445.html

This is the cryptic error one gets at the moment:
```
Generating gallery
________________________________________________________________________________
Example directory /Users/monodera/packages/astropy-1.3/docs/../examples does not have a README.txt file
Skipping this directory
________________________________________________________________________________
Traceback (most recent call last):
  File "<stdin>", line 33, in <module>
  File "/Users/monodera/anaconda3/envs/astroconda/lib/python3.5/site-packages/Sphinx-1.5.1-py3.5.egg/sphinx/application.py", line 244, in __init__
    self._init_builder(self.buildername)
  File "/Users/monodera/anaconda3/envs/astroconda/lib/python3.5/site-packages/Sphinx-1.5.1-py3.5.egg/sphinx/application.py", line 315, in _init_builder
    self.emit('builder-inited')
  File "/Users/monodera/anaconda3/envs/astroconda/lib/python3.5/site-packages/Sphinx-1.5.1-py3.5.egg/sphinx/application.py", line 589, in emit
    results.append(callback(self, *args))
  File "/Users/monodera/anaconda3/envs/astroconda/lib/python3.5/site-packages/sphinx_gallery/gen_gallery.py", line 125, in generate_gallery_rst
    .format(examples_dir))
FileNotFoundError: Main example directory /Users/monodera/packages/astropy-1.3/docs/../examples does not have a README.txt file. Please write one to introduce your gallery.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 39, in <module>
NameError: name 'self' is not defined
Sphinx Documentation subprocess failed with return code 1
```
Full log: https://gist.github.com/monodera/4911502cfe70daaedd14c9c98d71a627#file-gistfile1-txt-L1638

@saimn confirmed, and now after installing sphinx-gallery I get the same error. To reproduce:
```
pip install sphinx-gallery
Go to https://pypi.python.org/pypi/astropy/1.3 and click on astropy-1.3.tar.gz
tar zxf astropy-1.3.tar.gz
cd astropy-1.3
python setup.py build_docs
```

I'm not familiar with sphinx-gallery. So what are the action items here to fix this?
- Add `README.txt` or configure sphinx-gallery that we don't want it?
- Where does the second exception with the `NameError` originate from? Do we need to change something about how we use sphinx-gallery, or report it as an issue to them or Sphinx?

**Comment by bsipocz** [comment] 2017-01-27 12:20
I wonder why it works on travis. Do we miss the error as we still use sphinx <1.5? (1.4.8 in the latest build)

**Comment by saimn** [comment] 2017-01-27 12:42
I don't think the error comes from sphinx-gallery: I was able to reproduce the failure when pyyaml and matplotlib are not installed, but after installing them I was able to build the docs without sphinx-gallery.

@cdeil : Can you try to build with a `make html SPHINXOPTS=-vv` inside the `docs/` directory ? This allows to make sphinx more verbose, which is not possible with `build_docs`.

**Comment by cdeil** [comment] 2017-01-27 12:48
@saimn - here's what I get for `make html SPHINXOPTS=-vv`:
https://gist.github.com/cdeil/46b07b782ae5e7a0665328c310a1d419

The `FileNotFoundError` is the same as before.

The second `NameError` isn't there.
Presumably that comes from Astropy or Astropy-helpers then?

**Comment by adrn** [comment] 2017-01-27 13:23
Hm, I guess we need to add a README file -- see: https://github.com/sphinx-gallery/sphinx-gallery/pull/175/files

**Comment by adrn** [comment] 2017-01-27 13:32
Oh, wait, it looks like we do already have README files in all directories except `template`...but the error @cdeil reports complains about not finding one in the main example directory.

**Comment by adrn** [comment] 2017-01-27 13:38
@cdeil just reproduced the error by following the steps you posted. The error is definitely from sphinx-gallery, but the main issue is that when I downloaded the `astropy-1.3` source from pypi, there is no examples directory! Does it need to be added to the [MANIFEST](https://github.com/astropy/astropy/blob/master/MANIFEST.in)?

**Comment by saimn** [comment] 2017-01-27 13:40
Ok, so you indeed have an error from sphinx-gallery. I have a warning "Example directory /home/simon/dev/astropy/docs/../examples/template does not have a README.txt file" but this does not fail the build in my case...
Then the `NameError: name 'self' is not defined` is probably due to the hackish [way](https://github.com/astropy/astropy-helpers/blob/master/astropy_helpers/commands/build_sphinx.py#L133) sphinx is run, in a subprocess. It explains why I was also seeing this error but with a different root: the errors from the subprocess are maybe not handled (and reported) correctly.

**Comment by saimn** [comment] 2017-01-27 13:44
@adrn Ah yes indeed ! As the `examples` directory is not inside `docs` it should be added to the MANIFEST.

**Comment by bsipocz** [comment] 2017-01-27 13:49
Good detective work. This also explains why we don't see this error on travis.

**Comment by cdeil** [comment] 2017-01-27 14:15
Over the past years, we've seen several major issues after release, that would have been easy to avoid if we have CI builds that
1. package following the instructions how to release
2. install and run tests / docs like a user would, from the sdist or conda package

I think the time has come to add those extra CI builds?
I'd be willing to spend a day next week to do it (help for Astropy, do it for Gammapy and maybe other affiliated packages like photutils, regions, astroplan)

@bsipocz - Do we already have an issue with that suggestion where we discuss how to best implement it?
Everyone - Available for a few hours next week to go on Gitter or Google hangout and do it together?

**Comment by bsipocz** [comment] 2017-06-27 00:36
I believe this issue has been solved, so I'm closing it. As always, feel free to reopen if you think otherwise.

**Closed by bsipocz** 2017-06-27 00:36 UTC
Labels: Docs

**Comment by bsipocz** [comment] 2017-06-27 00:40
@mwcraig - @cdeil has yet again very good points that are best, and most effective, to discuss (and share existing solutions) face to face, e.g. at a pyastro...
