### ISSUE TITLE
astropy.table.Table.read() FITS extreme I/O load

### ISSUE THREAD

**Issue by jlvdb** [astropy/astropy#8438] opened 2019-02-20 18:25 UTC
I am trying to read 4GB fits file from disk. After 19 minutes of CPU time my system monitor tells me that the python process has read **1.6 TB** of data from disk without ever finishing. No problems with astropy.io.fits however.

**Comment by pllim** [comment] 2019-02-20 20:58
This looks like a duplicate of #6491 . What Astropy version are you using?

**Comment by saimn** [comment] 2019-02-20 21:57
Not sure if this is the same, it would be useful to have more details: @jlvdb , could you please provide some information about the Astropy version, FITS header, numbers about the memory usage with `Table.read` and `io.fits`, available RAM on your computer. 
It is also possible to use memmap with Astropy 3.0 and later, with `Table.read(..., memmap=True)`, could you try this ?

**Comment by jlvdb** [comment] 2019-02-21 00:27
Apparently, the problem was the swapping behaviour. I probably did not have enough free RAM when I was working earlier today which I did not realize. I am experiencing this often - probably not good for my SSD - so I did not consider this to be the problem.

In case people are still interested:

`astropy.__version__`
`'3.1'`
I was not aware that `Table.read` now supports memory mapping and it works in deed as expected, requiring only 76 MiB in RAM (ipython).
The table has 3224753 rows and 302 columns and occupies 4.0 GiB out of 7.7 GiB when load with `io.fits` and memory mapping disabled. Figures are similar with `Table.read`.
The data types present are:
`np.unique([d[1] for d in f[1].data.dtype.descr])`
`array(['>f4', '>f8', '>i2', '>i4', '|S16'], dtype='<U4')`

**Comment by bsipocz** [comment] 2019-02-21 00:30
>  was not aware that `Table.read` now supports memory mapping and it works in deed as expected, requiring only 76 MiB in RAM (ipython).

this case I'm closing this issue. Feel free to reopen if there is still something outstanding that we need to address on the astropy side.

**Closed by bsipocz** 2019-02-21 00:30 UTC
Labels: Close?, Duplicate, Performance, table
