### ISSUE TITLE
Full-Sky (360deg) image with projection=WCS not drawing the horizontal axis ticks/labels.

### ISSUE THREAD

**Issue by mireianievas** [astropy/astropy#10201] opened 2020-04-24 07:55 UTC
I'm trying to overlay some sources over a full-sky image from the Fermi-LAT (in my case the diffuse model, can be found here: https://fermi.gsfc.nasa.gov/ssc/data/analysis/software/aux/4fgl/gll_iem_v07.fits ).

I open the fits file with astropy as follows

```
import astropy.io.fits as pyfits
diffusemap = pyfits.open("gll_iem_v07.fits")

```
Then I get the WCS information from the hdu using astropy.wcs.WCS and use the projection option in add_subplot to adapt the axes.

```
mywcs = astropy.wcs.WCS(diffusemap[0])

MyFig = plt.figure(figsize=(8,3),dpi=150)
MyPlot = MyFig.add_subplot(111, projection=mywcs[0], label='overlays')
data = np.sum(diffusemap[0].data,axis=0)

im = MyPlot.imshow(data,
              norm=mcolors.LogNorm(vmin=np.min(data),vmax=0.1*np.max(data)),
              cmap='inferno',
              origin='lower',zorder=-100)

overlay = MyPlot.get_coords_overlay('fk5')
overlay.grid(color='white', lw=0.3, ls='dotted')

MyFig.colorbar(im)

MyPlot.set_ylabel("Galactic Latitude")
MyPlot.set_xlabel("Galactic Longitude")

im.set_clip_path(MyPlot.coords.frame.patch)

MyFig
```

What I get

![image](https://user-images.githubusercontent.com/2607760/80080111-6addfe00-8551-11ea-9c7d-8dfe9f57cd2d.png)

Is there any reason why the 'Galactic Longitude' (horizontal axis) is now drawn at all? There are no ticks, or labels and the axis label is ignored completely. I tried to set the zorder and tried to see if the axis is hidden by specifying an alpha=0.5, but there is simply no X axis.

**Expected outcome**

The expected plot should contain both x-label and y-label ticks. 

**Package versions**

  * Operating system: Linux-4.19.99-1-lts-x86_64-with-arch
  * Python version: 3.7.6 (conda-forge)
  * Numpy: 1.17.3
  * Matplotlib version: 3.1.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): agg
  * Scipy version: 1.4.1
  * Astropy version: 4.0 (healpix 0.7.0) 
  * Jupyter version (if applicable): 4.6.1 (jupyter-core) / 5.3.4 (client) / 6.0.0 (console)

I installed everything through conda and pip.

**Comment by Cadair** [comment] 2020-04-24 08:17
Thanks for submitting the bug report :smile: 

I think this is effectively the same bug as #9784 it happens because the lower axis of the plot is out of the coordinate system (maybe by only a pixel) so as there is no intersection between the axes and the projection the coordinates along the axis are not calculated.

The easiest work around is to zoom in (ax.axis() in a script) and then the ticks should appear. If this doesn't work let us know as it's probably a different bug then.

**Comment by mireianievas** [comment] 2020-04-25 19:27
Found the issue, related to what you mentioned. A get_ylim was reporting (-0.5,1440.5). Setting it to (0,1440.5) shows the x-axis. The first value cannot be negative.

**Comment by Cadair** [comment] 2020-04-27 17:54
yeah, so -0.5 is the "right" answer as it's the edge of the image (and projection) so the projection never makes it to the x axis, so it doesn't draw ticks. I will close this as a duplicate of #9784 thanks for reporting :smile:

**Closed by Cadair** 2020-04-27 17:54 UTC
Labels: Bug, Close?, Duplicate, visualization.wcsaxes
