### ISSUE TITLE
Stripping trailing whitespace in FITS data read into astropy table

### ISSUE THREAD

**Issue by Abelink23** [astropy/astropy#11205] opened 2021-01-04 09:02 UTC
I typically work with FITS tables (BinTableHDU), and so far I have used the astropy.io.fits approach to manipulate them or do crossmatches of elements of the tables with elements in lists (strings both), etc. Now I started to use astropy.table to open those tables, but (maybe is just the wrong approach) I have format issues crossmatching with items, for example: 
If my table has a column with names - table['Name'] - each element of that column has extra spaces to match with the column format (e.g.  'BD+60544     ') while using the astropy.io.fits it would be stripped of spaces 'BD+60544', and therefore the solution is not straitforward. Should I stick to astropy.io.fits or is there a way to solve this particular issue with astropy.table. 

Many thanks and happy new year!

**Comment by taldcroft** [comment] 2021-01-04 12:10
@Abelink23 - your FITS table presumably has trailing spaces in the data fields. According to the FITS standard the end of the character string in a binary table is specified by the NULL (ASCII zero) character. To be honest it is not clear to me from the spec whether trailing spaces should be stripped when reading. If someone that understands the FITS standard says this is wrong, we can change it.

The current implementation when reading to a `Table` is that that the trailing spaces are left in place. A workaround is that you can do:
```
table['Name'] = np.char.strip(table['Name'])
```

**Comment by pllim** [comment] 2021-01-04 14:44
I took the liberty to change the title, so that future users who encounter the same issue can find this. Hope you don't mind. Happy New Year!

**Comment by Abelink23** [comment] 2021-01-04 17:49
@taldcroft - I think that workaround is good enough for what I need, thanks! And thanks @pllim for renaming the title, it's more accurate than what I wrote :)

**Comment by pllim** [comment] 2021-01-04 18:06
Since @Abelink23 is satisfied with the provided workaround, I have added a "Close?" label. Please remove the label if you disagree. Thanks, all!

**Comment by taldcroft** [comment] 2021-01-09 10:18
Closing since the OP seems satisfied. This can be re-opened if someone feels the need.

**Closed by taldcroft** 2021-01-09 10:18 UTC
Labels: Close?, question, table

**Comment by astro-friedel** [comment] 2021-02-08 18:59
So I have come across a related issue to this. I am working with a fits binary table that has a single text based column. Reading the column is not an issue, however if the file is opened in 'update' mode and that data are read, when the file handle is closed all of the trailing spaces are converted to trailing NULL's. Why would just reading the data trigger an update to be written out? Also why would every trailing space get replaced by a NULL, instead of a single NULL?

**Comment by saimn** [comment] 2021-02-09 13:06
@astro-friedel - Please open a new issue with more details, a way to reproduce would be much appreciated.

**Comment by saimn** [comment] 2021-02-10 14:45
> Closing since the OP seems satisfied. This can be re-opened if someone feels the need.

Actually there is already an issue: #2608

**Comment by Abelink23** [comment] 2021-04-14 16:44
It has been some time since I posted this issue but after some iterations with other astrophysicists who also make use of Table.read() with FITS files we think it would be good to stripe trailing whitespaces in the table data that contain strings in the columns. The workaround we use --see code below-- (or the one proposed by @taldcroft) is something now that I have to use every time when I crossmatch FITS and non-FITS tables opened both with Table.read(), becoming quite annoying (even more when several columns have to be stripped).

For example:

```
table1 = Table.read('table1.fits',format='fits') # Table containing column 'Name'  (e.g. 'HD1234   ')
table2 = Table.read('table2.txt',format='ascii',delimiter=' ') # Table also containing column 'Name' (e.g. 'HD1234')
table3 = join(table1,table2,keys='Name')
```
- This first case would produce no matches unless the matching string in a row during the join fills the column with no trailing spaces.

```
table1 = Table.read('table1.fits',format='fits') # Table containing column 'Name'  
table2 = Table.read('table2.txt',format='ascii',delimiter=' ') # Table also containing column 'Name' 
table1['Name'] = [i.strip() for i in table1['Name']] # The workaround to be able to get a successful match
table2['Name'] = [i.strip() for i in table2['Name']]
table3 = join(table1,table2,keys='Name')
```
- This second case I get the desired behaviour, being able to properly match the content of both tables.

I had a look at the documentation of the FITS standards and found _" Leading spaces are significant; trailing spaces are
not. -  4.2.1. Character string (Version 4.0)"_ Moreover this behaviour of stripping trailing spaces is also found in other astronomical packages such IRAF. 

So I would now prefer to re-open this issue and make it a request for future updates. This was the first time I opened an issue in Git so I don't really know yet how to do this 😅   

Many thanks in advance!

**Comment by pllim** [comment] 2021-04-14 16:55
@Abelink23 , is #2608 not the same issue?

**Comment by Abelink23** [comment] 2021-04-14 17:22
@pllim It is, yes :) I just saw your comment from 2017 in there. Any chance for this behaviour to change in the future? Thanks.

**Comment by pllim** [comment] 2021-04-14 17:42
Given that it is "effort high" + "package expert", I wouldn't hold my breath. 😬

**Comment by Abelink23** [comment] 2021-04-15 08:29
I think so too. Well, in case is helpful for anyone basically I have done this workaround whenever I read a fits table:

```
data = Table.read(table_path,format='fits')
to_strip = [data.colnames[i] for i in range(len(data.dtype)) if data.dtype[i].char == 'S']
for col in to_strip: 
    data[col] = [i.strip() for i in data[col]]
```
