### ISSUE TITLE
Can't import astropy.coordinates in 1.1.1.

### ISSUE THREAD

**Issue by weaverba137** [astropy/astropy#4541] opened 2016-01-29 00:59 UTC
I can't import astropy.coordinates with astropy/1.1.1.  Here are two different ways I tried:

```
In [2]: from astropy.coordinates import SkyCoord
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-a44fc1d186bf> in <module>()
----> 1 from astropy.coordinates import SkyCoord

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/coordinates/__init__.py in <module>()
     16 from .transformations import *
     17 from .builtin_frames import *
---> 18 from .name_resolve import *
     19 from .matching import *
     20 from .representation import *

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/coordinates/name_resolve.py in <module>()
     21 from ..extern.six.moves import urllib
     22 from .. import units as u
---> 23 from .sky_coordinate import SkyCoord
     24 from ..utils import data
     25 from ..utils import state

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/coordinates/sky_coordinate.py in <module>()
     12 from ..units import Unit, IrreducibleUnit
     13 from .. import units as u
---> 14 from ..wcs.utils import skycoord_to_pixel, pixel_to_skycoord
     15 from ..utils.exceptions import AstropyDeprecationWarning
     16 from ..utils.data_info import MixinInfo

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/__init__.py in <module>()
     28 try:
     29     # Not guaranteed available at setup time
---> 30     from .wcs import *
     31     from . import utils
     32 except ImportError:

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/wcs.py in <module>()
     48 from . import _docutil as __
     49 try:
---> 50     from . import _wcs
     51 except ImportError:
     52     if not _ASTROPY_SETUP_:

ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/_wcs.so, 2): Symbol not found: _wcslib_version
  Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/_wcs.so
  Expected in: flat namespace
 in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/_wcs.so
```

```
In [5]: import astropy.coordinates as c
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-56016e0bcdee> in <module>()
----> 1 import astropy.coordinates as c

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/coordinates/__init__.py in <module>()
     16 from .transformations import *
     17 from .builtin_frames import *
---> 18 from .name_resolve import *
     19 from .matching import *
     20 from .representation import *

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/coordinates/name_resolve.py in <module>()
     21 from ..extern.six.moves import urllib
     22 from .. import units as u
---> 23 from .sky_coordinate import SkyCoord
     24 from ..utils import data
     25 from ..utils import state

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/coordinates/sky_coordinate.py in <module>()
     12 from ..units import Unit, IrreducibleUnit
     13 from .. import units as u
---> 14 from ..wcs.utils import skycoord_to_pixel, pixel_to_skycoord
     15 from ..utils.exceptions import AstropyDeprecationWarning
     16 from ..utils.data_info import MixinInfo

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/__init__.py in <module>()
     28 try:
     29     # Not guaranteed available at setup time
---> 30     from .wcs import *
     31     from . import utils
     32 except ImportError:

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/wcs.py in <module>()
     46 from ..extern import six
     47 from ..io import fits
---> 48 from . import _docutil as __
     49 try:
     50     from . import _wcs

ImportError: cannot import name _docutil
```

**Comment by mirca** [comment] 2016-01-29 12:15
Could you print the error log, if any, after trying ``import astropy.wcs``?

**Comment by astrofrog** [comment] 2016-01-29 12:31
@weaverba137 - there was an issue in the MacPorts port for Astropy. Can you do:

```
sudo port selfupdate
sudo port upgrade py27-astropy
```

? If it doesn't work, can you send the output of:

```
port installed wcslib
port installed py27-astropy
```

?

**Comment by weaverba137** [comment] 2016-01-29 15:16
Thanx, I'll answer both questions at the same time.

## import astropy.wcs

Before doing any upgrades, as suggested by the other question:
```
weaver@172-17-57-202[2]: python
Python 2.7.11 (default, Dec  8 2015, 15:56:30) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from astropy.wcs import *
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/__init__.py", line 30, in <module>
    from .wcs import *
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/wcs.py", line 50, in <module>
    from . import _wcs
ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/_wcs.so, 2): Symbol not found: _wcslib_version
  Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/_wcs.so
  Expected in: flat namespace
 in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/wcs/_wcs.so
```

## Existing version and upgrade.

Before trying to upgrade, here were the versions I had:

* wcslib @5.12_0 (active)
* py27-astropy @1.1.1_1 (active)

After upgrade:

* wcslib did not change.
* py27-astropy did not change.

So it looks like I'm already using the most recent version.

**Comment by embray** [comment] 2016-01-29 15:32
This is effectively a duplicate of #4467.

Since it's not an issue with astropy itself I'm closing, but feel free to continue discussion in the comments until the issue is resolved for you.

**Closed by embray** 2016-01-29 15:32 UTC
Labels: Duplicate, installation
