### ISSUE TITLE
DOC: Warnings about duplicate object description of astropy.coordinates.builtin_frames

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#11723] opened 2021-05-10 18:53 UTC
I started seeing these warnings in RTD. Is this related to the recent doc refactoring, @nstarman , @adrn , or @mhvk ?

```
.../astropy/coordinates/builtin_frames/galactic.py:docstring of astropy.coordinates.builtin_frames.galactic.Galactic:1: WARNING: duplicate object description of astropy.coordinates.builtin_frames.galactic.Galactic, other instance in api/astropy.coordinates.Galactic, use :noindex: for one of them
.../astropy/coordinates/builtin_frames/lsr.py:docstring of astropy.coordinates.builtin_frames.lsr.GalacticLSR:1: WARNING: duplicate object description of astropy.coordinates.builtin_frames.lsr.GalacticLSR, other instance in api/astropy.coordinates.GalacticLSR, use :noindex: for one of them
.../astropy/coordinates/builtin_frames/galactocentric.py:docstring of astropy.coordinates.builtin_frames.galactocentric.Galactocentric:1: WARNING: duplicate object description of astropy.coordinates.builtin_frames.galactocentric.Galactocentric, other instance in api/astropy.coordinates.Galactocentric, use :noindex: for one of them
.../astropy/coordinates/builtin_frames/ecliptic.py:docstring of astropy.coordinates.builtin_frames.ecliptic.GeocentricMeanEcliptic:1: WARNING: duplicate object description of astropy.coordinates.builtin_frames.ecliptic.GeocentricMeanEcliptic, other instance in api/astropy.coordinates.GeocentricMeanEcliptic, use :noindex: for one of them
.../astropy/coordinates/builtin_frames/ecliptic.py:docstring of astropy.coordinates.builtin_frames.ecliptic.GeocentricTrueEcliptic:1: WARNING: duplicate object description of astropy.coordinates.builtin_frames.ecliptic.GeocentricTrueEcliptic, other instance in api/astropy.coordinates.GeocentricTrueEcliptic, use :noindex: for one of them
.../astropy/coordinates/builtin_frames/hcrs.py:docstring of astropy.coordinates.builtin_frames.hcrs.HCRS:1: WARNING: duplicate object description of astropy.coordinates.builtin_frames.hcrs.HCRS, other instance in api/astropy.coordinates.HCRS, use :noindex: for one of them
.../astropy/coordinates/builtin_frames/ecliptic.py:docstring of astropy.coordinates.builtin_frames.ecliptic.HeliocentricEclipticIAU76:1: WARNING: duplicate object description of astropy.coordinates.builtin_frames.ecliptic.HeliocentricEclipticIAU76, other instance in api/astropy.coordinates.HeliocentricEclipticIAU76, use :noindex: for one of them
.../astropy/coordinates/builtin_frames/ecliptic.py:docstring of astropy.coordinates.builtin_frames.ecliptic.HeliocentricMeanEcliptic:1: WARNING: duplicate object description of astropy.coordinates.builtin_frames.ecliptic.HeliocentricMeanEcliptic, other instance in api/astropy.coordinates.HeliocentricMeanEcliptic, use :noindex: for one of them
.../astropy/coordinates/builtin_frames/ecliptic.py:docstring of astropy.coordinates.builtin_frames.ecliptic.HeliocentricTrueEcliptic:1: WARNING: duplicate object description of astropy.coordinates.builtin_frames.ecliptic.HeliocentricTrueEcliptic, other instance in api/astropy.coordinates.HeliocentricTrueEcliptic, use :noindex: for one of them
.../astropy/coordinates/builtin_frames/icrs.py:docstring of astropy.coordinates.builtin_frames.icrs.ICRS:1: WARNING: duplicate object description of astropy.coordinates.builtin_frames.icrs.ICRS, other instance in api/astropy.coordinates.ICRS, use :noindex: for one of them
.../astropy/coordinates/builtin_frames/itrs.py:docstring of astropy.coordinates.builtin_frames.itrs.ITRS:1: WARNING: duplicate object description of astropy.coordinates.builtin_frames.itrs.ITRS, other instance in api/astropy.coordinates.ITRS, use :noindex: for one of them
.../astropy/coordinates/builtin_frames/lsr.py:docstring of astropy.coordinates.builtin_frames.lsr.LSR:1: WARNING: duplicate object description of astropy.coordinates.builtin_frames.lsr.LSR, other instance in api/astropy.coordinates.LSR, use :noindex: for one of them
.../astropy/coordinates/builtin_frames/lsr.py:docstring of astropy.coordinates.builtin_frames.lsr.LSRD:1: WARNING: duplicate object description of astropy.coordinates.builtin_frames.lsr.LSRD, other instance in api/astropy.coordinates.LSRD, use :noindex: for one of them
.../astropy/coordinates/builtin_frames/lsr.py:docstring of astropy.coordinates.builtin_frames.lsr.LSRK:1: WARNING: duplicate object description of astropy.coordinates.builtin_frames.lsr.LSRK, other instance in api/astropy.coordinates.LSRK, use :noindex: for one of them
.../astropy/coordinates/builtin_frames/gcrs.py:docstring of astropy.coordinates.builtin_frames.gcrs.PrecessedGeocentric:1: WARNING: duplicate object description of astropy.coordinates.builtin_frames.gcrs.PrecessedGeocentric, other instance in api/astropy.coordinates.PrecessedGeocentric, use :noindex: for one of them
.../astropy/coordinates/builtin_frames/skyoffset.py:docstring of astropy.coordinates.builtin_frames.skyoffset.SkyOffsetFrame:1: WARNING: duplicate object description of astropy.coordinates.builtin_frames.skyoffset.SkyOffsetFrame, other instance in api/astropy.coordinates.SkyOffsetFrame, use :noindex: for one of them
.../astropy/coordinates/builtin_frames/supergalactic.py:docstring of astropy.coordinates.builtin_frames.supergalactic.Supergalactic:1: WARNING: duplicate object description of astropy.coordinates.builtin_frames.supergalactic.Supergalactic, other instance in api/astropy.coordinates.Supergalactic, use :noindex: for one of them
.../astropy/coordinates/builtin_frames/equatorial.py:docstring of astropy.coordinates.builtin_frames.equatorial.TEME:1: WARNING: duplicate object description of astropy.coordinates.builtin_frames.equatorial.TEME, other instance in api/astropy.coordinates.TEME, use :noindex: for one of them
```

**Comment by adrn** [comment] 2021-05-10 18:58
Hm, I don't think so - this looks like a potential automodapi issue?

**Comment by astrojuanlu** [comment] 2021-05-11 16:10
@larrybradley what do you mean by `astropy-sphinx` exactly? 

Also, I went to the last photutils build https://readthedocs.org/projects/photutils/builds/13703740/ and it ran Sphinx v3.5.4 (Sphinx 4 was released two days later). If you open a new PR and observe this warning there, feel free to ping me.

Also, if this is because Sphinx 4, I guess it's natural that it doesn't appear in #11724, right? We'd have to wait until Sphinx 4.0.2 is released with a fix for https://github.com/sphinx-doc/sphinx/issues/9210 to unpin the version and see if this happens again.

**Comment by larrybradley** [comment] 2021-05-11 16:14
It was the nightly `photutils` cron job last night:  https://github.com/astropy/photutils/runs/2552715843?check_suite_focus=true

And I can reproduce this locally.

Sorry, I had them reversed.  It's `sphinx-astropy`:  https://github.com/astropy/sphinx-astropy, which `photutils` and `astropy` use.

**Comment by pllim** [comment] 2021-05-20 19:16
Opened astropy/sphinx-automodapi#130

**Closed** 2022-12-09 23:31 UTC
Labels: Docs, Bug, coordinates
