### ISSUE TITLE
AttributeError when setting QTable column unit

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#6098] opened 2017-05-18 18:24 UTC
I'm trying to write some code that takes a Table or QTable and sets a new unit for a given column.

Table and Column work as expected:
```python
>>> from astropy.table import Table, Column
>>> t = Table(dict(a=[1, 2, 3]))
>>> t['a'].unit = 's'
>>> t['a'].info.unit = 's'
```

But for QTable I'm sometimes getting AttributeError (and sometimes not):
```python
>>> from astropy.table import QTable, Column
>>> t = QTable(dict(a=[1, 2, 3]))
>>> t['a'].unit = 's'  # works
>>> t['a'].info.unit = 's'
AttributeError: can't set attribute
```
and then if I create a column by creating and assigning a `Column`, both going via `.info` or not fails (so somehow the `b` column is different from the `a` column in a subtle way?):
```python
>>> t['b'] = Column([4, 5, 6], unit='s')
>>> t['b'].unit = 'm'
AttributeError: can't set attribute
>>> t['b'].info.unit = 'm'
AttributeError: can't set attribute
```
@mhvk or @taldcroft) - Is this a bug or a feature?

(this is on Astropy 2.0.dev18336)

**Comment by mhvk** [comment] 2017-05-18 19:38
@cdeil - the problem is not with `info.unit` vs `unit`, but that for a `Quantity`, one cannot set the unit. What really happens is that you first make a table with a `Column`, and by setting the unit the first time, you turn the `Column` into a `Quantity` (in fact you even change the dtype, from int to float). Then, the next time setting the unit fails.

I realize this is confusing, but I don't really know how to avoid it.... Ideally, we'd never have input that only got a unit after the fact, but that is not always easy to arrange.

**Comment by cdeil** [comment] 2017-05-18 19:47
I have a QTable and need to change the unit on some columns (from "ph cm-2 s-1" to "cm-2 s-1", to standardise units like I was mentioning a while ago). Is there a workaround, i.e. code that let's me do that (ideally with little code, preserving other attributes like column dtype / description)?

**Comment by cdeil** [comment] 2017-05-18 20:11
For now I'm making a Table copy of my QTable:
```
    table = Table(table)
    for column in table.columns.values():
        if column.unit:
            column.unit = standardise_unit(column.unit)
    return table
```
This works OK for my current use case, because memory / speed is not so important.

---

@mhvk - Did you see this case?
```
>>> from astropy.table import QTable, Column
>>> t = QTable(dict(a=[1, 2, 3]))
>>> t['a'].unit = 's'  # works
>>> type(t['a'])
astropy.table.column.Column
```
Is this the intended behaviour or should that have created a quantity column?

To be honest - I find this mix of `Quantity` and `Column` objects in a `QTable` and the mix in behaviour super confusing.

How can I see which column is which type?

I would have expected this info to show up here, but it's currently not:
```
>>> t.info()
<QTable length=3>
name dtype
---- -----
   a int64
```

**Comment by taldcroft** [comment] 2017-05-18 20:21
This is really not so nice, but ...
```
In [43]: t = QTable([[1,2]*u.m], names=['a'])  # Unit is m
In [44]: t['a'].info.meta = {1:2}
In [46]: ta = t['a']
In [47]: t['a'] = Column(ta.value, unit='s', meta=ta.info.meta, 
                         description=ta.info.description, format=ta.info.format)

In [48]: t['a']
Out[48]: <Quantity [ 1., 2.] s>

In [49]: t['a'].info.meta
Out[49]: {1: 2}
```

It looks like there is a bug because `Column(t['a'])` loses the meta data like `description`.  Except for that bug one could do something more general like:
```
t['a'] = Column(t['a'].view(Column), unit='s')
```

**Comment by mhvk** [comment] 2017-05-18 20:22
Right now, the only way using public methods I can think of doing the unit change is by
```
t['a'] = t['a'].to(new_unit, equivalencies=(...))
```
This does keep `info` intact. (Of course, one can just do `t['a']._unit = ...`, but that's not great)

There are some ways to address this. First, right now, the `Quantity` initializer can pass through quantities that have consistent unit already:
```
b = u.Quantity(t['a'], u.m, copy=False)
b is t['a']
# True
```
We could extend this by adding an `equivalencies` keyword. Or, somewhat equivalently, adding a `copy` argument to `to`, which would not do a copy when the units are the same (including equivalencies).

Maybe more direct would be to either:
1. Give `Quantity.to` an `inplace` argument;
2. Define a new `set_unit` method with an argument that would indicate whether the original unit should simply be overridden, or whether values should be converted, or whether no conversion is allowed (i.e., the units should be the same, given equivalencies).

With the latter option, we could redefine `info.unit` (and `unit`?) setting to point to `set_unit` with the no conversion allowed option (which would solve your case if you are inside a context with the proper equivalencies set).

**Comment by taldcroft** [comment] 2017-05-18 20:24
@cdeil - I see the expected result for astropy 1.3 + Py3.5.  What version are you using?
```
In [58]: >>> from astropy.table import QTable, Column
    ...: >>> t = QTable(dict(a=[1, 2, 3]))
    ...: >>> t['a'].unit = 's'  # works
    ...: >>> type(t['a'])
    ...: 
Out[58]: astropy.units.quantity.Quantity
```

**Comment by cdeil** [comment] 2017-05-18 20:25
I'm on Astropy master (2.0.dev18379, bf3c4adf0e2b81788edc15d2c3b1666506efd728) and see this on Python 2.7 and 3.6

**Comment by cdeil** [comment] 2017-05-18 20:29
@mhvk - To me `set_unit` sounds simplest, but I don't have a feeling if it's the best way to do it.

I do think that changing the unit on a table column in an efficient and simple way is important, so +1 to make some kind of addition for `QTable`.

**Comment by taldcroft** [comment] 2017-05-18 20:33
👍  on `set_unit`

**Comment by mhvk** [comment] 2017-05-18 20:34
@cdeil - yes, I did see your example, and, yes, it is confusing. Indeed, at first I also thought one had started with a quantity with no unit. But I think in itself it is not strange for `QTable` that arrays without units are treated differently from those with units; especially for integers, `Quantity` would in general be the wrong class to use. The real confusion comes from the implicit change to `Quantity` (independent of astropy version):
```
 In [21]: t = QTable(dict(a=[1, 2, 3]))

In [22]: type(t['a'])
Out[22]: astropy.table.column.Column

In [23]: t['a'].info.unit = 'm'

In [24]: type(t['a'])
Out[24]: astropy.units.quantity.Quantity
```
Here, being able to set the unit and get a `Quantity` (it cannot stay a `Column`) was intended as a convenience; the only alternative would seem to make setting the unit illegal for a `Column` inside a `QTable`.

**Comment by cdeil** [comment] 2017-05-18 20:39
@mhvk - I think QTable is too clever for me, I prefer the consistent behaviour from Table (always behaves the same, for all columns).

Make it easier for users to see which columns in a QTable are Quantity and which are Column would be extremely useful. Probably via `table.info()`, no (ha ha)?

**Comment by mhvk** [comment] 2017-05-18 20:39
It does sound like we're getting to at least some solution: have `Quantity.set_unit`. Which is a units issue.

For `QTable`, I wonder if the conversion of `Column` to `Quantity` should respect the `dtype` (i.e., work with views).

**Comment by taldcroft** [comment] 2017-05-18 20:40
@cdeil - on the confusion of Quantity vs Column -- agreed it is not a perfect situation.  The driver for this decision is that Quantity is still not a perfect replacement for Column.  It does not (yet) support masking so if you want full support for table operations like join() then using Quantity for any numeric value would be a problem for QTable.

**Comment by taldcroft** [comment] 2017-05-18 20:48
I have thought about having the default Table repr show the class of mixin columns.  That might help things out.  E.g.
```
In [11]: qt = QTable([[1.00000003,2]*u.m, [3,4], ['a', 'b']])

In [12]: qt
Out[12]: 
<QTable length=2>
   col0     col1 col2
 Quantity
    m                
 float64   int64 str1
---------- ----- ----
1.00000003     3    a
       2.0     4    b
```

**Comment by mhvk** [comment] 2017-05-18 20:49
@cdeil - for `info`, your example is one that happens to fall in another convenience (which possibly is not convenient?), that if all columns of a class have the same type, and it is the standard type for that class, the class is removed. With more columns, you don't run into this:
```
t = QTable(dict(a=[1, 2, 3], b=[3,4,5]*u.m))
t.info()
<QTable length=3>
name  dtype  unit  class  
---- ------- ---- --------
   b float64    m Quantity
   a   int64        Column
```

More generally, you are actually trying to do something difficult for quantities, which is fiddle with their units. The whole class is based on the idea that the unit is "sacred," to be preserved at all cost! Unfortunately, historically, in fits files and otherwise, units have been not been considered very carefully... (which obviously we should be able to deal with; but it does mean that `np.sin(t['b'])` correctly throws a `UnitsError`).

**Comment by mhvk** [comment] 2017-05-18 20:55
On the note of doing something difficult: while it is not great, I think if unpleasantness was expected anywhere, it would be between fits and table, i.e., between two different ways of storing information. In your place, I might just do `t['a']._unit = ...` with appropriate checks around it. After all, that is what `Table.read('...fits')` does as well.

Possibly, another route to your actual problem would be to insert a hook in the table reader in which the fits header gets edited before making it into a table.

**Comment by cdeil** [comment] 2017-05-18 21:01
This is what I did for now in Gammapy (https://github.com/gammapy/gammapy/pull/1032) and I do plan to just go all-in on Table for now (https://github.com/gammapy/gammapy/issues/980#issuecomment-302538745).

I'm still fuzzy on the differences: Table can store Time and SkyCoord, right?
The difference (from a user perspective) is mainly in what magic `table[colname]` does for getting / setting?
IMO getting the simpler behaviour of Table and calling `table[colname].quantity` everywhere where we need quantities is a very nice and simple solution.
Thinking about it now ... I guess it's making a copy and is inefficient to work that way in analysis codes?

**Comment by mhvk** [comment] 2017-05-18 21:02
@taldcroft - Adding the class to the `repr` seems like a good idea.

**Comment by mhvk** [comment] 2017-05-18 21:07
@cdeil - before you decide, see my note on the interface being the tricky part: you can make that easy by using `Table`, but then everywhere else you're stuck with doing `.quantity`; if you forget it once on a column with angular degrees, and do `np.sin`, bad luck, wrong result. Or you can make the interface somewhat hacky -- and everywhere else things will work correctly, your users mistakes with units will get caught, etc.

p.s. But, no, `.quantity` does not make a copy.

**Comment by mhvk** [comment] 2017-05-19 20:33
@cdeil - on the actual use case, it suddenly occurred to me that by far the easiest way to remove `u.ph` in both `Column` and `Quantity` is simply to divide by it, i.e., 
```
In [3]: t = QTable()

In [4]: t['a'] = [1., 5.] * u.ph/u.s/u.cm**2

In [5]: t
Out[5]: 
<QTable length=2>
     a      
ph / (cm2 s)
  float64   
------------
         1.0
         5.0

In [6]: t['a'] /= u.ph

In [7]: t
Out[7]: 
<QTable length=2>
     a     
1 / (cm2 s)
  float64  
-----------
        1.0
        5.0
```

In fact, for a general unit change, you can always do `q / q.unit * new_unit` (note that the unit can be  a string).

**Comment by mhvk** [comment] 2017-05-21 15:28
@cdeil, @taldcroft - I made two feature requests based on our discussion here (#6106 -- `set_unit`; #6107 -- mixin class in table repr), and will now close this issue.

@taldcroft - above (https://github.com/astropy/astropy/issues/6098#issuecomment-302530175) you mentioned a bug in loosing metadata when doing `Column(t['a'])` -- I don't seem to be able to reproduce that. Obviously, do raise it if I'm just misunderstanding what the bug is...

**Closed by mhvk** 2017-05-21 15:28 UTC
Labels: table, units

**Comment by taldcroft** [comment] 2017-05-21 17:28
> above (#6098 (comment)) you mentioned a bug in loosing metadata when doing Column(t['a']) -- I don't seem to be able to reproduce that.

Weird, because I cannot reproduce either now.  When I wrote the comment I was using a computer that I don't normally use, so maybe it was running an old version or there was something else funky happening with the installation.  I'll try to remember next week when I'm sitting at that computer to check the version and maybe I'll find the terminal window still there...  For now we don't have to worry about this.
