### ISSUE TITLE
Format specifier for float columns in tables not being honored.

### ISSUE THREAD

**Issue by tonywong94** [astropy/astropy#14557] opened 2023-03-20 17:49 UTC
### Description

Recently a script which sets the format for table columns explicitly before writing to ascii.ecsv has started to behave differently.  The formats are set using commands like:
```
for cname in tab.colnames:
    if cname == 'coRactr_'+base or cname == 'coDectr_'+base:
        gtab[cname].format='.4f'
    elif cname != 'Name':
        gtab[cname].format='.3f'
gtab.write('edge_coflux_'+base+'.csv', format='ascii.ecsv', delimiter=',', overwrite=True)
```
The requested format is not used in the output table, although it still appears in the ECSV header.
`# - {name: coRactr_smo7, unit: deg, datatype: float64, format: .4f, description: Reference R.A. of smo7 CARMA cube}
`...
`ARP220,233.738333333,23.5036666667,...`

### Expected behavior

I expect the floats to be truncated to the requested number of digits before printing.  I tried replacing ".format" with ".info.format" but this did not seem to have any effect.

### How to Reproduce

I think the description above suffices but I can provide additional files and code if needed.

### Versions

macOS-13.2.1-arm64-arm-64bit
Python 3.10.10 (main, Feb 24 2023, 04:10:25) [Clang 14.0.0 (clang-1400.0.29.202)]
astropy 5.2.1
Numpy 1.24.1
pyerfa 2.0.0.1
Scipy 1.10.0
Matplotlib 3.7.1

**Comment by eerovaher** [comment] 2023-03-20 17:59
This is a duplicate of #14461

**Closed by eerovaher** 2023-03-20 17:59 UTC
Labels: io.ascii, Duplicate, question

**Comment by tonywong94** [comment] 2023-03-20 19:33
Ah, did not see the previous report (perhaps it was closed already).  Thanks for your prompt reply.  I thought the purpose of ECSV was to be human-readable, so I find this choice disappointing.  The numerical precision of the computer is irrelevant for most astronomical measurements.  I suggest that the AstroPy documentation be updated to note the change in behavior as well as the version number at which it was made.

**Comment by eerovaher** [comment] 2023-03-21 15:04
If you think that the documentation should be improved then I recommend you leave a comment in the original issue. If the `io.ascii` maintainers agree that improvements can be made then they can reopen the issue and all the relevant discussion stays together rather than being spread out over duplicate issues.
