### ISSUE TITLE
Astropy test runner no longer automatically runs doctests

### ISSUE THREAD

**Issue by drdavella** [astropy/astropy#7764] opened 2018-08-23 14:52 UTC
This was originally reported in https://github.com/astropy/pytest-doctestplus/issues/24, although I believe the name of that issue is misleading. Git bisect led me to 10359e46a277525debcb09e8e07f354f0c26c247, which was part of #7463. Unfortunately, that means that this has been happening for quite some time, and it appears to affect any affiliated package that uses the test runner.

More investigation required, but hopefully this will be easy to resolve.

**Comment by drdavella** [comment] 2018-08-23 15:05
It's worth mentioning that explicitly giving the docs path seems to work:
`./setup.py test -t docs`

**Comment by hamogu** [comment] 2018-08-23 15:06
Duplicate of #7762 - I bet you on opening an issue ;-) .
I'll close this issue and copy your comments over to #7762.

**Closed by hamogu** 2018-08-23 15:06 UTC
Labels: Bug, Docs, testing
