### ISSUE TITLE
python3 setup.py test -t <filename> does not work any more???

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#5798] opened 2017-02-10 20:54 UTC
I tend to run tests using single filenames to speed up things, but somehow things like
```
python3 setup.py test -t astropy/coordinates/tests/test_arrays.py
```
now starts to run the full test suite.

Any ideas??

**Comment by mhvk** [comment] 2017-02-10 20:57
Also, when I test just a single module (like `-P coordinates`), now *all* documentation gets tested, instead of just the documentation belonging to that module

**Comment by pllim** [comment] 2017-02-10 21:15
Any chance things work in pytest 2.x, assuming you are using pytest 3.x? Maybe something was overlooked when we did the transition to pytest 3.x.

**Comment by pllim** [comment] 2017-02-10 21:16
In the meantime, you can try
```
pytest astropy/coordinates/tests/test_arrays.py
=== 13 passed, 1 pytest-warnings in 4.63 seconds ===
```

**Comment by bsipocz** [comment] 2017-02-11 01:02
Weird, I'll look into this during the weekend. Affiliates also have this issue, while v1.3 is working as expected.

**Comment by bsipocz** [comment] 2017-02-12 00:24
@Cadair - I'm afraid your #5758 have introduced this regression. Do you have an idea how to fix it?

**Comment by pllim** [comment] 2017-02-13 16:30
I added a "critical" tag because this seems pretty serious from a testing standpoint. If there is no fix in sight, we should undo #5758. What do you think?

**Comment by mhvk** [comment] 2017-02-13 16:39
Agreed, this does need to work.

**Comment by bsipocz** [comment] 2017-02-13 17:13
Agreed, too. Also, there need to be tests for this, and probably for the other tests shortcuts, too.

**Comment by pllim** [comment] 2017-02-13 17:17
To test the test runner... This is getting very meta. :sweat_smile:

**Comment by bsipocz** [comment] 2017-02-13 17:20
Well, we need to make sure this never brake again.

**Comment by Cadair** [comment] 2017-02-13 17:43
I will try and get to this sometime this week. I have no idea why #5758 would have broken it, is it definitely that and not the original PR for 1.3?

**Comment by bsipocz** [comment] 2017-02-13 17:53
@Cadair - It works with the 1.3 release, and actually works with 598bbdf461fe18b23aa30722d8b4f6a8802944f5, too (that's the last merge before #5758).

**Comment by mhvk** [comment] 2017-02-13 17:58
@Cadair - I just checked and the problem is with [copying `self.keywords`](https://github.com/astropy/astropy/pull/5758/files#diff-836e0185b50212c030b8d95210ff52e8R145); if I replace that line with `keywords = self.keywords`, i.e., allow in-place updates, everything works again.

**Comment by mhvk** [comment] 2017-02-13 18:03
But as @saimn notes, the real issue is https://github.com/astropy/astropy/pull/5758#discussion_r100855219; nice find!!

**Comment by saimn** [comment] 2017-02-13 18:30
Pushed the fixed quickly as I have to go !

**Closed** 2017-02-13 19:35 UTC
Labels: Affects-dev, Bug, Critical, testing
