### ISSUE TITLE
Table join with differently named columns

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#5470] opened 2016-11-11 15:30 UTC
A use case that has come up a few times for me/others is being able to join two tables where the key is named differently in each table. At the moment, the only solution is to rename one of the columns:

```python
In [12]: from astropy.table import Table, join

In [13]: t1 = Table()
    ...: t1['a'] = [1,2,3]
    ...: t1['b'] = ['a','b','c']
    ...: 

In [14]: t2 = Table()
    ...: t2['c'] = [3,2]
    ...: t2['d'] = [4.4, 4.3]

In [15]: t2.rename_column('c', 'a')

In [16]: join(t1, t2, 'a')
Out[16]: 
<Table length=2>
  a    b      d   
int64 str1 float64
----- ---- -------
    2    b     4.3
    3    c     4.4
```

But this seems like a common use case, and changing the tables is not ideal. One idea would be to allow ``keys`` to be a dict:

```python
In [16]: join(t1, t2, {'a':'c'})
Out[16]: 
<Table length=2>
  a    b      d   
int64 str1 float64
----- ---- -------
    2    b     4.3
    3    c     4.4
```

The keys of the dictionary would be the equivalent of the current ``keys`` for the first table, and the values would be the ``keys`` for the right table.

This would be backward-compatible since there's no need to remove any of the current behavior.

**Comment by bsipocz** [comment] 2019-02-26 07:16
Oh, this would be such a nice feature :) (maybe mosty as I could just use it right now).

**Comment by taldcroft** [comment] 2019-02-26 11:39
How about a context manager for temporarily renaming columns:
```
with t1.context_rename_columns(['a', 'b'], ['A', 'B']):
    out = table.join(t1, t2)
```
This could also be used for `vstack`, where you cannot use the `dict` construct above since there may be more than 2 tables.

One detail of implementation.  We *could* make the `rename_columns` method (#8070) return a context manager.  Here is the example for `rename_column` which does exist now.  The main downside is that doing `tbl.rename_column('c', 'C')` returns an object might find confusing.  We could give it a nicer repr() that makes it a bit more obvious?
```
class Rename:
    def __init__(self, tbl, name, new_name):
        self.name = name
        self.new_name = new_name
        self.tbl = weakref.ref(tbl)
        tbl.rename_column(name, new_name)

    def __enter__(self):
        return

    def __exit__(self, type, value, traceback):
        self.tbl().rename_column(self.new_name, self.name)


def rename_column(self, name, new_name):
    return Rename(self, name, new_name)

In [17]: t = simple_table()

In [18]: with t.rename_column_cm('c', 'C'):
    ...:     print(t)
    ...:     
 a   b   C 
--- --- ---
  1 1.0   c
  2 2.0   d
  3 3.0   e

In [19]: print(t)
 a   b   c 
--- --- ---
  1 1.0   c
  2 2.0   d
  3 3.0   e

In [20]: t.rename_column_cm('c', 'C')
Out[20]: <__main__.Rename at 0x117c8a080>

In [21]: t
Out[21]: 
<Table length=3>
  a      b     C  
int64 float64 str1
----- ------- ----
    1     1.0    c
    2     2.0    d
    3     3.0    e
```

**Comment by bsipocz** [comment] 2019-02-26 20:21
> This could also be used for `vstack`, where you cannot use the `dict` construct above since there may be more than 2 tables.

good point. I have started implementing the dictionary solution yesterday evening, but abandoned it to go home, and haven't yet thinking about vstack and hstack (though currently neither of those accept `keys` as an arg)

**Comment by taldcroft** [comment] 2019-02-26 20:59
But vstack does have the concept of trying to match up columns, and here you might also have the problem that you want column `'a'` to stack on top of column `'A'`.  Admittedly that case is probably less common.

Part of the issue here is that I'm scared to mess with this beast of a function that always confuses me each time I look at it:
https://github.com/astropy/astropy/blob/e112f5b1bc887eba46e35425fc51f9f3a12c046c/astropy/table/operations.py#L502
This gets used for join, hstack and vstack to organize the input and output columns.

**Comment by bsipocz** [comment] 2019-09-26 22:16
This is a duplicate of https://github.com/astropy/astropy/issues/3752, closing this to keep the older one.

**Closed by bsipocz** 2019-09-26 22:16 UTC
Labels: Duplicate, Feature Request, table
