### ISSUE TITLE
Quantity issue with np.ma.std and np.ma.var

### ISSUE THREAD

**Issue by larrybradley** [astropy/astropy#10792] opened 2020-10-02 18:02 UTC
Just ran across this puzzling behavior with `np.ma.std` and `np.ma.var` with `Quantity` inputs:

```python
>>> import numpy as np
>>> import astropy.units as u
>>> a = np.arange(5.) << u.km
>>> np.std(a)
1.4142136 km
>>> np.ma.std(a)  # returns wrong unit!
1.4142136 km(1/2)

>>> np.var(a)
2.0 km2
>>> np.ma.var(a)  # returns wrong unit!
2.0 km
```

`np.ma.mean` works fine:
```python
>>> np.mean(a)
2 km
>>> np.ma.mean(a)
2 km
```

Is this an upstream bug in `numpy`?
@mhvk

**Comment by mhvk** [comment] 2020-10-02 18:41
@larrybradley - `Quantity` has never really interacted well with masked arrays, sadly. The problem is that both override standard numpy behaviour, and the way they do it interferes with each other. So, I fear "upstream fix required" is the right answer....  That said, it may be worth checking what exactly goes wrong in your examples, since it may be fixable (my guess is that `np.ma.var` is the culprit, and `np.ma.std` just a consequence of taking a square room after, but I haven't actually looked...)

**Comment by mhvk** [comment] 2021-04-12 18:33
Going to call this fixed by #11127 even if that really means one has to use our own `Masked` class.

**Comment by larrybradley** [comment] 2021-08-05 14:45
@mhvk The `Masked` class is great!  Any chance this will make it's way to `numpy`? 😃 

It might be good to mention somewhere in the `Masked` documentation that `Masked` objects shouldn't be used with `np.ma` functions:

```python
>>> a = Masked(np.arange(3) << u.km, [True, False, False])
>>> np.ma.mean(a)
<MaskedQuantity ——— km>

>>> np.ma.var(a)
...
UnitConversionError: '' (dimensionless) and 'km' (length) are not convertible
```

**Comment by mhvk** [comment] 2021-08-05 17:46
I've been meaning to at least let numpy know about this, but I think the chance that it will get in is tiny...

But, yes, you are right it should be documented that one should not use the `np.ma` functions!

**Closed** 2021-08-05 18:53 UTC
Labels: Upstream Fix Required, units, Bug
