### ISSUE TITLE
1.0rc1: test_read failures on s390x, powerpc, and mips

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#3415] opened 2015-02-01 10:31 UTC
On S390x, Powerpc, and mips, I found the following tests failing:
- `TestSingleTable.test_read_from_fileobj`
- `TestMultipleHDU.test_read`
- `TestMultipleHDU.test_read_with_hdu_1[1]`
- `TestMultipleHDU.test_read_with_hdu_1[first]`

They all seem to have the same cause, so I show only the first trace:

```
self = <astropy.io.fits.tests.test_connect.TestSingleTable object at 0x3fff70a2e48>
tmpdir = local('/tmp/pytest-0/test_read_from_fileobj0')

    def test_read_from_fileobj(self, tmpdir):
        filename = str(tmpdir.join('test_read_from_fileobj.fits'))
        hdu = BinTableHDU(self.data)
        hdu.writeto(filename)
        with open(filename, 'rb') as f:
            t = Table.read(f)
>       assert equal_data(t, self.data)
E       assert equal_data(<Table masked=False length=4>\n  a      b        c   \nint64 string32 float64\n--...a     2.3\n    2     b     4.5\n    3     c     6.7\n    4     d     8.9, array([(1, u'a', 2.3), (2, u'b', 4.5), (3, u'c', 6.7), (4, u'd', 8.9)], \n      dtype=[('a', '>i8'), ('b', '>U1'), ('c', '>f8')]))
E        +  where array([(1, u'a', 2.3), (2, u'b', 4.5), (3, u'c', 6.7), (4, u'd', 8.9)], \n      dtype=[('a', '>i8'), ('b', '>U1'), ('c', '>f8')]) = <astropy.io.fits.tests.test_connect.TestSingleTable object at 0x3fff70a2e48>.data

astropy/io/fits/tests/test_connect.py:130: AssertionError
```

Full log [here for s390x](https://buildd.debian.org/status/fetch.php?pkg=python-astropy&arch=s390x&ver=1.0~rc1-1&stamp=1422725318), [here for powerpc](https://buildd.debian.org/status/fetch.php?pkg=python-astropy&arch=powerpc&ver=1.0~rc1-1&stamp=1422725045), and [here for mips](https://buildd.debian.org/status/fetch.php?pkg=python-astropy&arch=mips&ver=1.0~rc1-1&stamp=1422748119).

**Comment by olebole** [comment] 2015-02-12 10:20
Not fixed with rc2 (just for reference, not that I'd expected it since the issue is still open)

**Comment by astrofrog** [comment] 2015-02-12 14:26
@olebole - since I don't have access to one of these machines, could you add a debug print statement on line 21 of ``connect.py``, so that the function looks like:

```
def equal_data(a, b):
    for name in a.dtype.names:
        print(a[name], b[name])
        if not np.all(a[name] == b[name]):
            return False
    return True
```

**Comment by astrofrog** [comment] 2015-02-12 14:37
I'm currently trying to set up Qemu to emulate these systems, so may be able to debug interactively later today.

**Comment by olebole** [comment] 2015-02-12 14:38
I also hope to find some time tonight to have a look on a Debian porterbox.

**Comment by astrofrog** [comment] 2015-02-12 17:46
I finally managed to get an emulated machine running (and it's veeeery slow). Investigating.

**Comment by astrofrog** [comment] 2015-02-12 17:52
So the issue is that for the failing comparison ``a[name]`` has dtype ``S4`` and ``b[name]`` has dtype ``U1``.

**Comment by astrofrog** [comment] 2015-02-12 17:55
cc @embray in case you have ideas, still looking into it.

**Comment by astrofrog** [comment] 2015-02-12 19:34
I've been looking into this but am stumped - if I try and reproduce the error outside of the astropy tests and I don't get anywhere.

@olebole - let me know if you have any ideas!

**Comment by astrofrog** [comment] 2015-02-12 19:34
In any case, I classify this as non-critical for 1.0 since it doesn't seem to be a major issue, just some strange bug when comparing the arrays. But the data isn't corrupt or anything.

**Comment by olebole** [comment] 2015-02-12 20:00
I just made them `xfail` during the Debian build; however from the affected architectures this looks like an endianess problem.

**Comment by astrofrog** [comment] 2015-02-12 22:55
@olebole - the weird thing is that if I create arrays by hand with types ``|S4`` and ``>U1`` I don't get any issue.

**Comment by astrofrog** [comment] 2015-02-13 09:49
For anyone debugging this, here is the output (on powerpc) of various diagnostic print statements on ``a[name]`` and ``b[name]`` (just a screenshot to save time, otherwise need to figure out transferring data out of the emulator):

![screen shot 2015-02-13 at 9 48 04 am](https://cloud.githubusercontent.com/assets/314716/6185383/8c9bc84c-b365-11e4-8b83-f7e9fd710bfa.png)

**Comment by astrofrog** [comment] 2015-02-13 09:59
I should say that in the above log I also changed the assert in ``test_read_with_hdu_1`` to use ``t.as_array()`` instead of ``t`` to get rid of any column types to simplify things.

**Comment by astrofrog** [comment] 2015-02-13 11:16
It probably is related to the ``\x00\x00\x00a``

**Comment by astrofrog** [comment] 2015-02-13 11:18
By the way, this may be related to https://github.com/astropy/astropy/issues/3419 which has failures in the same tests with numpy dev on MacOS X

**Comment by astrofrog** [comment] 2015-02-13 11:27
Ok so on Mac, with a passing test, the ``S4`` array is ``'a\x00\x00\x00b\x00\x00\x00c\x00\x00\x00d\x00\x00\x00'`` while on the PowerPC machine it is ``'\x00\x00\x00a\x00\x00\x00b\x00\x00\x00c\x00\x00\x00d'``

However, I didn't think that endianness changed the order of the characters:

```
In [1]: import numpy as np

In [2]: x = np.array(['a','b','c','d'], dtype='<S4')

In [3]: y = np.array(['a','b','c','d'], dtype='>S4')

In [4]: x.tobytes()
Out[4]: b'a\x00\x00\x00b\x00\x00\x00c\x00\x00\x00d\x00\x00\x00'

In [5]: y.tobytes()
Out[5]: b'a\x00\x00\x00b\x00\x00\x00c\x00\x00\x00d\x00\x00\x00'
```

(this is on Mac)

so I'm not sure why the strings are right-aligned on the PowerPC.

@embray - do you have any ideas, with all the information above?

**Comment by embray** [comment] 2015-02-13 17:34
@astrofrog In your test in the last comment you were making arrays of dtype `S4`, where endianness is irrelevant.  But the array the test is failing on is of dtype `U1` and for unicode strings endianness does matter.  The bug here has to do with assuming endianness of unicode strings.

**Comment by bsipocz** [comment] 2017-05-10 13:56
@olebole - This is a rather old issue. Do you, or anyone else with access to such platform, still see these failures?

**Comment by olebole** [comment] 2017-05-10 14:17
Please give me a week or so, I will test.

**Comment by astrofrog** [comment] 2018-11-01 16:46
I just ran the test in Debian on MIPS and PowerPC, and I don't see this failure anymore, so I'm going to close this. I'm suspecting this may have been a Numpy bug that has been fixed since (the failures above were with Numpy 1.8)

@olebole - if you still this specific failure, feel free to re-open.

**Closed by astrofrog** 2018-11-01 16:46 UTC
Labels: io.fits, platform-ppc, testing
