### ISSUE TITLE
[3.1] Convolve problems in some affiliated packages

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#8312] opened 2018-12-29 21:01 UTC
I just uploaded astropy 3.1 to Debian (which succeeds all its own tests on build time), and found that gammapy now shows some [CI test errors](https://ci.debian.net/data/autopkgtest/unstable/amd64/g/gammapy/1603966/log.gz):
```
__________ ERROR collecting astro/darkmatter/tests/test_profiles.py ___________
ImportError while importing test module '/usr/lib/python3/dist-packages/gammapy/astro/darkmatter/tests/test_profiles.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3/dist-packages/astropy/convolution/convolve.py:27: in <module>
    _convolve = load_library("_convolve", LIBRARY_PATH)
/usr/lib/python3/dist-packages/numpy/ctypeslib.py:131: in load_library
    from numpy.distutils.misc_util import get_shared_lib_extension
/usr/lib/python3/dist-packages/numpy/distutils/__init__.py:6: in <module>
    from . import ccompiler
/usr/lib/python3/dist-packages/numpy/distutils/ccompiler.py:11: in <module>
    from distutils import ccompiler
E   ImportError: cannot import name 'ccompiler' from 'distutils' (/usr/lib/python3.7/distutils/__init__.py)

During handling of the above exception, another exception occurred:
/usr/lib/python3/dist-packages/gammapy/astro/darkmatter/__init__.py:4: in <module>
    from .spectra import *
/usr/lib/python3/dist-packages/gammapy/astro/darkmatter/spectra.py:9: in <module>
    from ...spectrum.models import TableModel
/usr/lib/python3/dist-packages/gammapy/spectrum/__init__.py:4: in <module>
    from .observation import *
/usr/lib/python3/dist-packages/gammapy/spectrum/observation.py:12: in <module>
    from ..irf import EffectiveAreaTable, EnergyDispersion, IRFStacker
/usr/lib/python3/dist-packages/gammapy/irf/__init__.py:10: in <module>
    from .psf_gauss import *
/usr/lib/python3/dist-packages/gammapy/irf/psf_gauss.py:9: in <module>
    from astropy.convolution import Gaussian2DKernel
/usr/lib/python3/dist-packages/astropy/convolution/__init__.py:10: in <module>
    from .convolve import convolve, convolve_fft, interpolate_replace_nans, convolve_models  # noqa
/usr/lib/python3/dist-packages/astropy/convolution/convolve.py:29: in <module>
    raise ImportError("Convolution C extension is missing. Try re-building astropy.")
E   ImportError: Convolution C extension is missing. Try re-building astropy.
```
It seems that #7293 caused this. I already filed gammapy/gammapy#1974, but when looking into the stacktrace again, it looks more a bug in astropy, right?
Photutils has the same problem, as seen [here](https://ci.debian.net/data/autopkgtest/unstable/amd64/p/photutils/1604010/log.gz); also [radio-beam](https://ci.debian.net/data/autopkgtest/unstable/amd64/r/radio-beam/1603812/log.gz), [spectral-cube](https://ci.debian.net/data/autopkgtest/unstable/amd64/r/radio-beam/1603812/log.gz) and others.
It may well be that my specific build was done errornously; however I am then wondering why the build time tests succeeded. Build log (including tests) is [here](https://buildd.debian.org/status/fetch.php?pkg=astropy&arch=amd64&ver=3.1-1&stamp=1546085168&raw=0). I couldn't find anything that did not build there.
This happens with numpy 1.16rc1 (which is now in Debian unstable); I applied #8264 to my package to make it compatible. Maybe I missed something here?

**Comment by bsipocz** [comment] 2018-12-29 21:07
@olebole - Do you think this issue is still there with astropy master? I'm about to do a bugfix release, most probably tomorrow night for 3.1.1 and 2.0.11.

**Comment by olebole** [comment] 2018-12-29 21:10
If you have a specific commit that I could apply, I can test it. Otherwise, I would just wait that day for a test (our machinery isn't very quick anyway, so it would take ~ a day to get an answer).

**Comment by bsipocz** [comment] 2018-12-29 21:17
Top of 3.1.x (9faaa01bee242c64092f8e7da44b426c0d5426d0) would do. 

But honestly, I'm sceptic that anything is fixed in this regard given that this issue of came up during RC testing and the solution was to give this more explicit error message rather than revamp more of the C stuff (https://github.com/astropy/astropy/pull/8035)

cc @astrofrog

**Comment by olebole** [comment] 2018-12-29 21:33
I meant that if there is a specific commit (or PR) that I could apply to a 3.1 release, then I could test without big problems.
Looking into #8035, and specifically into @saimn's [comment](https://github.com/astropy/astropy/pull/8035#issuecomment-434498510), a wild guess would be that `numpy.ctypeslib.load_library` works differently with the new numpy version (or maybe buggy there).

**Comment by saimn** [comment] 2018-12-29 23:02
Looking at the first part of the traceback, it seems that the `numpy.distutils.ccompiler` import fails because `distutils.ccompiler` is not found, which is probably because of the way debian package python and distutils ?

**Comment by olebole** [comment] 2018-12-29 23:11
python3-distutils is really missing in the list of packages on the gammapy CI test. But shouldn't it on the requirements list of numpy (or astropy) if it is needed?

**Comment by saimn** [comment] 2018-12-29 23:18
distutils is part of python's stdlib, and used by setuptools, so I have no idea how it can be missing here. Or maybe there is something special with the `ccompiler` module ?

**Comment by saimn** [comment] 2018-12-29 23:20
On a debian stable, `distutils.ccompiler` comes with the `libpython3.5-stdlib` package.

**Comment by saimn** [comment] 2018-12-29 23:38
Actually only distutils is required, setuptools is only optional for entry points (and is listed in http://docs.astropy.org/en/latest/install.html)

**Comment by olebole** [comment] 2018-12-31 10:07
@saimn the missing distutils package was the cause of the problem, thank you very much for the hint!
I don't know whether this should be added to setup.py, so I leave it open for that case. Pls close otherwise.

**Comment by saimn** [comment] 2019-01-02 22:53
distutils is part of the stdlib so there is no point in adding it to setup.py, it is not an external package, and the issue is only because of the way debian package it.
Also, thinking again about this, distutils should be a (debian) dependency for numpy instead of astropy, as astropy only use it via `numpy.distutils`.

**Closed** 2019-01-02 22:54 UTC
Labels: Close?, convolution, installation
