### ISSUE TITLE
QTable init from list of dict fails for scalar Quantity

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#3378] opened 2015-01-28 12:17 UTC
I frequently [create table objects from a list of dicts](http://astropy.readthedocs.org/en/latest/table/construct_table.html#row-data) when computing results one row at a time.

In https://github.com/gammapy/gammapy/pull/235 I've run into this error when I have scalar Quantity objects as values:

```
ValueError: setting an array element with a sequence.
```

Here's a small example that reproduces the issue:

``` python
>>> import numpy as np
>>> from astropy.table import Table, QTable
>>> from astropy.units import Quantity
>>> QTable([dict(a=Quantity(1, 'meter'))])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deil/Library/Python/3.4/lib/python/site-packages/astropy-1.0.dev11738-py3.4-macosx-10.10-x86_64.egg/astropy/table/table.py", line 2053, in __init__
    super(QTable, self).__init__(data, masked, names, dtype, meta, copy, rows)
  File "/Users/deil/Library/Python/3.4/lib/python/site-packages/astropy-1.0.dev11738-py3.4-macosx-10.10-x86_64.egg/astropy/table/table.py", line 309, in __init__
    init_func(data, names, dtype, n_cols, copy)
  File "/Users/deil/Library/Python/3.4/lib/python/site-packages/astropy-1.0.dev11738-py3.4-macosx-10.10-x86_64.egg/astropy/table/table.py", line 431, in _init_from_list
    self._init_from_list_of_dicts(data, names, dtype, n_cols, copy)
  File "/Users/deil/Library/Python/3.4/lib/python/site-packages/astropy-1.0.dev11738-py3.4-macosx-10.10-x86_64.egg/astropy/table/table.py", line 423, in _init_from_list_of_dicts
    self._init_from_dict(cols, names, dtype, n_cols, copy)
  File "/Users/deil/Library/Python/3.4/lib/python/site-packages/astropy-1.0.dev11738-py3.4-macosx-10.10-x86_64.egg/astropy/table/table.py", line 496, in _init_from_dict
    self._init_from_list(data_list, names, dtype, n_cols, copy)
  File "/Users/deil/Library/Python/3.4/lib/python/site-packages/astropy-1.0.dev11738-py3.4-macosx-10.10-x86_64.egg/astropy/table/table.py", line 454, in _init_from_list
    copy=copy)
  File "/Users/deil/Library/Python/3.4/lib/python/site-packages/astropy-1.0.dev11738-py3.4-macosx-10.10-x86_64.egg/astropy/table/column.py", line 775, in __new__
    unit=unit, format=format, meta=meta, copy=copy)
  File "/Users/deil/Library/Python/3.4/lib/python/site-packages/astropy-1.0.dev11738-py3.4-macosx-10.10-x86_64.egg/astropy/table/column.py", line 213, in __new__
    self_data = np.array(data, dtype=dtype, copy=copy)
ValueError: setting an array element with a sequence.
```

Note that these incarnations all seem to work OK:

``` python
>>> QTable([dict(a=Quantity([1], 'meter'))])
<QTable masked=False length=1>
 a [1] 
float64
-------
    1.0
>>> QTable([dict(a=1)])
<QTable masked=False length=1>
  a  
int64
-----
    1
>>> QTable([dict(a=np.array(1))])
<QTable masked=False length=1>
  a  
int64
-----
    1
```

@taldcroft @mhvk Is it possible to make the scalar quantity case shown above work?

**Comment by mhvk** [comment] 2015-01-28 14:28
@taldcroft - had only the quickest of looks: the problem is that in the last line `data` is a list holding the quantity, rather than the quantity itself. This happens in `_init_from_list_of_dicts`, but I don't quite see why the non-scalar case would work...

**Comment by taldcroft** [comment] 2015-01-28 19:00
This appears to be a relatively deep issue and we may want to add this to the section on Details and Caveats.  The problem is that for any kind of row-style inputs (either `rows=..` or a list of dicts), the code first assembles each column as a plain list.  It then defers to numpy to coerce this into a numpy array.  This part of the code is basically not mixin-capable because of the general problem of assembling a mixin column from a list of (potentially arbitrary) inputs is difficult.

Fundamentally the exception is equivalent to this:
```
In [30]: np.array([1*u.m, 2*u.m])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-30-209308a69e26> in <module>()
----> 1 np.array([1*u.m, 2*u.m])

ValueError: setting an array element with a sequence.
```
Numpy doesn't know what to do with those Quantity elements.  In astropy table we can, in theory, intervene and search for known mixin types, or maybe use the first element in order to infer that a `Quantity` column is needed.  But even if we guessed that all the list elements are Quantity, I don't know of a built-in way to concatenate them into a final array `Quantity` that is needed for the table.

The upshot is that I don't think this can be fixed in time for 1.0 in a general way.  These are the kinds of real-life issues that we were expecting and will need to be worked through.

A short term working might be the following, which is roughly 
```
outs = collections.defaultdict(list)
for row in get_my_rows_iterator():
    for key, val in row.items():
        outs[key].append(val)

for key, values in outs.items():
    if has_quantities(values):
        outs[key] = convert_list_quantity_to_array_quantity(values)

t = QTable(outs, names=sorted(outs))
```
The implementation of `has_quantities` and `convert_list_quantity_to_array_quantity` is left as an exercise for the reader... difficulty depends on how much you know about your inputs.

**Comment by taldcroft** [comment] 2015-01-28 19:01
Documentation update PR coming shortly.

**Comment by taldcroft** [comment] 2015-01-28 19:21
#3382 updates the mixin documentation to reflect this known issue.

**Comment by mhvk** [comment] 2015-01-28 19:32
@taldcroft - in principle, if we typecheck the first element, one could let `Quantity` deal with it:
```
In [1]: import astropy.units as u, numpy as np

In [2]: u.Quantity([1*u.m, 2*u.m])
Out[2]: <Quantity [ 1., 2.] m>
```
Might it be an idea for `QTable` to just *default* to letting `Quantity` handle it, and only use `np.array` if that fails? (e.g., because the input is string or boolean)

**Comment by bsipocz** [comment] 2019-09-17 02:06
The example  in the original description now works, so I'm closing this issue. Feel free to reopen, or rather open another for cases that are still not covered.

```
In [1]: >>> import numpy as np 
   ...: >>> from astropy.table import Table, QTable 
   ...: >>> from astropy.units import Quantity 
   ...: >>> QTable([dict(a=Quantity(1, 'meter'))])                                                                    
Out[1]: 
<QTable length=1>
   a   
   m   
float64
-------
    1.0
```

**Closed by bsipocz** 2019-09-17 02:06 UTC
Labels: Bug, table, units
