### ISSUE TITLE
test_read.py:1175: AssertionError

### ISSUE THREAD

**Issue by pmaxted** [astropy/astropy#4953] opened 2016-05-19 10:06 UTC
Testing my development version of astropy  (1.2.dev15412)  with ..

"python setup.py test  "  

.. on ..

Python 3.5.1 |Anaconda 4.0.0 (x86_64)| (default, Dec  7 2015, 11:24:55) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin

produces  ..

```
=================================== FAILURES ===================================
______________________ test_non_C_locale_with_fast_reader ______________________

    @pytest.mark.skipif('not HAS_DE_LOCALE')
    def test_non_C_locale_with_fast_reader():
        """Test code that forces "C" locale while calling fast reader (#4364)"""
        current = locale.setlocale(locale.LC_ALL)
    
        try:
            locale.setlocale(locale.LC_ALL, str('de_DE'))
    
            for fast_reader in (True, False, {'use_fast_converter': False}, {'use_fast_converter': True}):
                t = ascii.read(['a b', '1.5 2'], format='basic', guess=False,
                               fast_reader=fast_reader)
>               assert t['a'].dtype.kind == 'f1'
E               assert 'f' == 'f1'
E                 - f
E                 + f1

test_read.py:1175: AssertionError
```

**Comment by astrofrog** [comment] 2016-05-19 11:06
Duplicate of https://github.com/astropy/astropy/issues/4832

**Closed by astrofrog** 2016-05-19 11:06 UTC
