### ISSUE TITLE
Use asv on travis?

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#6149] opened 2017-05-31 21:26 UTC
In https://github.com/astropy/astropy/pull/6127#issuecomment-304956348, @bsipocz wondered whether it was really not possible to run `asv` as part of CI. We don't have it, but it turns out `numpy` does: it has an entry in `.travis.yml` and some actual code at https://github.com/numpy/numpy/blob/master/tools/travis-test.sh#L131-L140

Could we do something similar? (It might make sense to look at what they don in `.travis.yml` more generally; it seems there are some caching options which perhaps we can use too?)

**Comment by bsipocz** [comment] 2017-05-31 21:47
@mhvk - I had the caching in my radar, just never get that far down on my todo list. Overall I don't think it would mean a huge speedup as we use conda for most of the dependencies anyway. There are other possible enhancements that may help more, such as figuring out whether we could use the new travis beta "build stages", or creating custom tags, e.g. ``[docs only]`` to skip most of the builds semi manually (https://github.com/astropy/ci-helpers/issues/188)

**Comment by bsipocz** [comment] 2017-05-31 21:51
For asv: I was thinking of having it separately from our CI (but using the same services), maybe even in a separate organization to avoid queuing it in the same place. Unless you think it worth running on every commit that has CI running.

**Comment by mhvk** [comment] 2017-05-31 21:57
I think I'd mostly want to have a semi-reliable record, so perhaps on merging to master would be most relevant.

**Comment by saimn** [comment] 2017-05-31 22:01
It seems difficult to get reliable timings on Travis, isn't it ? Also are there some limits on cpu time or memory that could be hit if the benchmark suite grows ? 
(I don't remember how much time it takes to run for one commit, last time I tried it starting to run for all commits and never finished, and I stopped the experiment there).

**Comment by saimn** [comment] 2017-05-31 22:04
From https://github.com/numpy/numpy/pull/6830: "This should ensure the suite stays in working condition, not to produce reliable timing information."

**Comment by mhvk** [comment] 2017-05-31 22:06
Thanks for checking that... So much for that idea, then...

**Comment by bsipocz** [comment] 2017-05-31 22:45
travis max job time is 50mins currently: https://docs.travis-ci.com/user/customizing-the-build/#Build-Timeouts

One way to avoid the timeout is to divide the benchmarks to submodules and run separate jobs on them.

**Comment by astrofrog** [comment] 2017-06-01 16:22
We shouldn't run asv on travis, using any cloud-based infrastructure isn't going to give reliable results unless we have dedicated access to a CPU.

**Comment by astrofrog** [comment] 2017-06-01 16:26
If we were to run on Travis, there is a way to run a subset of commits to stay within the time allocation - for example you can run e.g. 10 random commits every time the CI runs. However, the issue is that even on a dedicated machine, it took me >1 month (on a single core) to catch up with all previous commits. I really think it would be easier to simply use a dedicated machine at someone's institution.

**Comment by bsipocz** [comment] 2017-06-01 16:40
Ouch. however do we need to run in to each and every commit, or just on the merge commits? If a a merge one is awful, we then need to go into the details?

**Comment by bsipocz** [comment] 2017-06-01 16:47
Also, while I see that we need a dedicated machine, running it in the cloud is still looks better than nothing, at least I suspect that we should be able to detect slowing down trends (while the overall result is very noisy from commit to commit). But as it has ambiguous prospects, probably noone should spend much time setting it up, unless on a hackday...

**Comment by Cadair** [comment] 2017-06-01 16:54
If someone want's to help me get this setup for SunPy as well I can offer semi-reliable hardware in my house.

**Comment by astrofrog** [comment] 2017-06-01 18:36
@bsipocz - the time estimate I gave before was for running just on merge commits I think

**Comment by Cadair** [comment] 2017-06-01 18:40
Does asv have a separation between the web/database and the worker? Can you run them on two different boxes?

**Comment by astrofrog** [comment] 2017-06-01 18:44
@Cadair - the database is kept in the GitHub repo. In principle you could run on two different boxes. But that would produce separate sets of results, i.e. you can't use parallelization to run all commits faster.

**Comment by pllim** [comment] 2017-06-05 14:10
So, can we close this since the topic is "asv on Travis" and answer is obviously "no"?

**Closed** 2017-06-05 14:49 UTC
Labels: Performance, testing
