### ISSUE TITLE
astropy.io.fits regression?

### ISSUE THREAD

**Issue by nden** [astropy/astropy#5087] opened 2016-06-13 14:07 UTC
Assigning to fits.ImageHDU.data does not work any more. Was this intentional?
It's a recent change, it showed in our regression tests a couple of days ago.

```
ar = np.arange(34)
im = fits.ImageHDU()
im.data = ar
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-18-8ee0b26e686a> in <module>()
----> 1 im.data = ar

/grp/hst/ssb/rhel6/ssbdev/python/lib/python2.7/site-packages/astropy/utils/decorators.pyc in __set__(self, obj, val)
    507         obj_dict = obj.__dict__
    508         if self.fset:
--> 509             ret = self.fset(obj, val)
    510             if ret is not None and obj_dict.get(self._key) is ret:
    511                 # By returning the value set the setter signals that it took

/grp/hst/ssb/rhel6/ssbdev/python/lib/python2.7/site-packages/astropy/io/fits/hdu/image.pyc in data(self, data)
    252             else:
    253                 self._data_replaced = True
--> 254             was_unsigned = _is_pseudo_unsigned(self.__dict__['data'].dtype)
    255         else:
    256             self._data_replaced = True

AttributeError: 'NoneType' object has no attribute 'dtype'

```

**Comment by pllim** [comment] 2016-06-13 14:14
I always just do `im = fits.ImageHDU(ar)`. There is no point to split it into 2 lines, right?

**Comment by nden** [comment] 2016-06-13 14:16
I guess it depends when you have the data available. In any case there's a lot of code out there which does this and will be broken.

**Comment by pllim** [comment] 2016-06-13 14:19
Also, I cannot reproduce your error... It works fine for me. I notice you're usingg SSBDEV. What version is it using?

**Comment by mwcraig** [comment] 2016-06-13 14:32
This is an error introduced in a PR I wrote that was merged a couple days ago. I can as a test and a fix this evening, or perhaps one of you could add it earlier. Would get it in around 8pm CDT.

**Comment by pllim** [comment] 2016-06-13 15:22
Yeah, I can confirm that I also see the same error now with latest master. Sorry for the noise.

**Comment by pllim** [comment] 2016-06-13 15:23
Also, the PR is #5053, right?

**Comment by mwcraig** [comment] 2016-06-13 15:51
Yes, that is the one. Basically just need a check that data is not none, but I almost think the regression test is more important.

**Comment by pllim** [comment] 2016-06-13 16:06
Should we tag this as 1.2 as well?

**Comment by mwcraig** [comment] 2016-06-13 16:06
I think so, yes.

**Closed** 2016-06-14 12:01 UTC
Labels: Affects-release, Bug, io.fits
