### ISSUE TITLE
Unable to import astropy.io.ascii

### ISSUE THREAD

**Issue by kvoggel** [astropy/astropy#13486] opened 2022-07-22 16:26 UTC
I get this error message when importing the ascii package from astropy as:
from astropy.io import ascii

I just recently changed mac laptops but not my python version. It's 3.8.1. I have tried all the suggested solutions to the error messages below but none of them worked. The same error also happens when I use different codes that use ascii packages, or just try to manually import it without any other code. I have also tried to rename it as ascii seems now an included funtion in python itself. But that also resulted in the same error. Anyone knows any help? I used the ascii function in a ton of old codes that I cannot run anymore due to this issue.

`Traceback (most recent call last):
  File "/Users/kvoggel/Library/Python/3.8/lib/python/site-packages/astropy/units/_typing.py", line 9, in <module>
    from typing import Annotated
ImportError: cannot import name 'Annotated' from 'typing' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/typing.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calculate_mass.py", line 4, in <module>
    from astropy.io import ascii
  File "/Users/kvoggel/Library/Python/3.8/lib/python/site-packages/astropy/io/ascii/__init__.py", line 7, in <module>
    from .core import (InconsistentTableError,
  File "/Users/kvoggel/Library/Python/3.8/lib/python/site-packages/astropy/io/ascii/core.py", line 31, in <module>
    from astropy.table import Table
  File "/Users/kvoggel/Library/Python/3.8/lib/python/site-packages/astropy/table/__init__.py", line 5, in <module>
    from .column import Column, MaskedColumn, StringTruncateWarning, ColumnInfo
  File "/Users/kvoggel/Library/Python/3.8/lib/python/site-packages/astropy/table/column.py", line 12, in <module>
    from astropy.units import Unit, Quantity, StructuredUnit
  File "/Users/kvoggel/Library/Python/3.8/lib/python/site-packages/astropy/units/__init__.py", line 39, in <module>
    from .decorators import *
  File "/Users/kvoggel/Library/Python/3.8/lib/python/site-packages/astropy/units/decorators.py", line 13, in <module>
    from . import _typing as T
  File "/Users/kvoggel/Library/Python/3.8/lib/python/site-packages/astropy/units/_typing.py", line 18, in <module>
    from typing_extensions import *  # override typing
AttributeError: module 'typing_extensions' has no attribute 'OrderedDictTypedDict'`

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

```python
# Put your Python code snippet here.
```

**Comment by eerovaher** [comment] 2022-07-22 17:02
This is a duplicate of #12551. The solution is to upgrade `typing_extensions` to at least 3.10.0.1.

**Closed** 2022-07-22 17:02 UTC
Labels: Bug
