### ISSUE TITLE
TST: Cron jobs for s390x and arm64 failed with hypothesis error

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#10450] opened 2020-06-05 01:15 UTC
Example log: https://travis-ci.org/github/astropy/astropy/builds/694700963

```
____________ ERROR collecting astropy/time/tests/test_precision.py _____________
astropy/time/tests/test_precision.py:9: in <module>
    from hypothesis import assume, example, given, target
E   ImportError: cannot import name 'target' from 'hypothesis' (/usr/lib/python3/dist-packages/hypothesis/__init__.py)
____________ ERROR collecting astropy/time/tests/test_precision.py _____________
ImportError while importing test module '/home/travis/build/astropy/astropy/astropy/time/tests/test_precision.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
astropy/time/tests/test_precision.py:9: in <module>
    from hypothesis import assume, example, given, target
E   ImportError: cannot import name 'target' from 'hypothesis' (/usr/lib/python3/dist-packages/hypothesis/__init__.py)
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
```

@mhvk or @Zac-HD , any ideas? Thanks.

**Comment by Zac-HD** [comment] 2020-06-05 03:53
Looks like yet another problem with distro-provided packages :roll_eyes:   
(we [explicitly ask](https://hypothesis.readthedocs.io/en/latest/packaging.html) not to be repackaged unless you keep up to date, and yet...)

```
Installing collected packages: ..., hypothesis, ...
    ...
  Attempting uninstall: hypothesis
    Found existing installation: hypothesis 4.36.2
    Not uninstalling hypothesis at /usr/lib/python3/dist-packages, 
        outside environment /home/travis/build/astropy/astropy/tests
    Can't uninstall 'hypothesis'. No files were found to uninstall.
Successfully installed ... hypothesis-5.16.0 ...

============================= test session starts ==============================
plugins: ..., hypothesis-4.36.2, ...
____________ ERROR collecting astropy/time/tests/test_precision.py _____________
astropy/time/tests/test_precision.py:9: in <module>
    from hypothesis import assume, example, given, target
E   ImportError: cannot import name 'target' from 'hypothesis'
        (/usr/lib/python3/dist-packages/hypothesis/__init__.py)
```

In short: `pip install` encountered a much older version of Hypothesis, attempted to replace it with the required new version, and *failed but reported success anyway*, and then the tests failed because they do in fact require the newer features.

You can probably get around this with the `--user` flag, but IMO you'd be much better off with a virtualenv and avoiding dist-packages entirely.

**Comment by mhvk** [comment] 2020-06-05 13:22
@pllim - thanks for noticing! I think I now what the problem is - the `pip3` command as written tries to write outside the virtual environment. Hopefully fixed by #10452!

@Zac-HD - I can fully see that hypothesis is a young package and thus still changing quite rapidly, as one finds out what does and does not work. But I will add that a rapidly changing dependency is a horror for any package that depends on it - we've had many annoying problems with pytest changing its API, and try hard for astropy to not be similarly annoying (as does, fortunately, numpy). And it is important for our users on supercomputers that a system manager can just install astropy without having to worry about the security nightmare that is pip, yet test that the installation
in fact works.

Anyway, the problem here is that the set-up that aims to work around possibly outdated packages was incorrect, so in a way hypothesis found another bug...

**Comment by mhvk** [comment] 2020-06-05 13:50
Hmm, even with the fix, I have problems, because we get `hypothesis` 5.16, which is fine according to our own `pytest-astropy`, but not good enough for our actual tests. So, the problem is ours, not the distribution's.

**Comment by mhvk** [comment] 2020-06-05 14:04
Hmm, now I am even more confused: hypothesis 5.16 *should work*. Investigating...

**Comment by Zac-HD** [comment] 2020-06-05 14:08
That can't be right, Hypothesis 5.16 is newer than those tests!  Are you sure it's actually using the version you tried to install, instead of an older one?

More generally, Hypothesis is *fanatical* about backwards compatibility because we know that this is a really important "feature" for our users. If a non-major release has broken *anything*, our whole development process has failed catastrophically 😬

I think it's more likely you're encountering what we calk "the curse of Hypothesis", where unrelated things start breaking. There's no good explanation for this beyond karma, but... for what it's worth I'm sorry!

**Comment by mhvk** [comment] 2020-06-05 14:20
@Zac-HD - yes, this is *not* related to hypothesis, sorry!! There is something really weird going on with it failing on using `attr`, even though that should have the right version as well.

**Comment by Zac-HD** [comment] 2020-06-05 14:32
Whew, that's a real relief! I can totally understand suspicion of a new dependency though, especially when we've just had install issues, and remain glad to help out however I can.

**Comment by mhvk** [comment] 2020-06-05 15:26
Thanks!

**Closed** 2020-06-08 19:12 UTC
Labels: Bug, testing
