### ISSUE TITLE
Add support for passing in a PendingWarning class to deprecated decorator and improve message about removal  

### ISSUE THREAD

**Issue by nabobalis** [astropy/astropy#16461] opened 2024-05-15 18:22 UTC
### What is the problem this feature will solve?

In sunpy we have been using a subclass of the original deprecated decorator to account for the fact that older versions of did not let us use our own deprecation warning class. 

But I noticed that the pending version is hard coded and while we don't use it (yet) in sunpy, it would be nice to be able to pass in our own one.

Also we override the message to tell users what the min version will be when said deprecated item would be removed.

### Describe the desired outcome

Go from
"The foo function is deprecated and may be removed in a future version"
to 
"The foo function is deprecated and may be removed in version 3.1"

Also allow us to raise a SunpyPendingDeprecationWarning instead of an AstropyPendingDeprecationWarning

### Additional context

Happy to try doing this myself.

**Comment by neutrinoceros** [comment] 2024-05-15 18:27
`typing_extensions.deprecated` already supports this and there's an existing discussion to decide whether we want to replace our decorator with it at https://github.com/astropy/astropy/issues/15301

**Comment by pllim** [comment] 2024-05-15 18:37
I thought you already can do that?

https://github.com/astropy/astropy/blob/51fc19be4bc44c317ff44ec5641e676f1d55f56b/astropy/utils/decorators.py#L38

**Comment by pllim** [comment] 2024-05-15 18:38
@bsipocz implemented it back in https://github.com/astropy/astropy/pull/8178

**Comment by nabobalis** [comment] 2024-05-15 18:39
I meant the pending warning.

**Comment by bsipocz** [comment] 2024-05-15 18:51
Lol, @Cadair was seeing the future: https://github.com/astropy/astropy/issues/8190

@nabobalis - certainly go ahead and make the pending class an input option, too. And given this is going into utils without breaking backwards compatibility, I would advocate for backporting and including it in the bugfix release, too.

**Comment by pllim** [comment] 2024-05-15 18:52
Theoretically you could say `pending=False` and then set the `warning_type` to your own pending class though that does not seem very clean.

**Comment by pllim** [comment] 2024-05-15 18:53
Oh, thanks for digging that out, @bsipocz . I have no recollection opening that issue. 😅

**Comment by bsipocz** [comment] 2024-05-15 18:59
> Theoretically you could say pending=False and then set the warning_type to your own pending class though that does not seem very clean.

I think it is reasonable enough as the functionality is targeting developers not end users. But a new `pending_type=AstropyPendingDeprecationWarning`, could be a cleaner way to go.

**Comment by bsipocz** [comment] 2024-05-15 19:00
> I have no recollection opening that issue.

I certainly cannot recall all the 400+ issues I opened and are still open :)

**Comment by Cadair** [comment] 2024-05-15 19:14
I do frequently see the future.

**Comment by Cadair** [comment] 2024-05-16 08:08
Closing as a dupe of #8190

**Closed by Cadair** 2024-05-16 08:08 UTC
Labels: Feature Request, utils, Close?, Duplicate
