### ISSUE TITLE
deprecated decorator and NDDataArray results in a TypeError

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy#4830] opened 2016-05-02 13:41 UTC
There is a deprecated-decorator that should work for classes but somehow I cannot get it to work properly. For example:

```
from astropy.nddata import NDDataArray, NDData
from astropy.utils import deprecated
NDDataArray = deprecated('sometime')(NDDataArray)
NDDataArray([1,2,3])

WARNING: AstropyDeprecationWarning: The NDDataArray class is deprecated and may be removed in a future version. [__main__]

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-bbc1072871d3> in <module>()
----> 1 NDDataArray([1,2,3])

C:\...\astropy\utils\decorators.py in deprecated_func(*args, **kwargs)
    118             warnings.warn(message, category, stacklevel=2)
    119 
--> 120             return func(*args, **kwargs)
    121 
    122         # If this is an extension function, we can't call

C:\...\astropy\nddata\compat.py in __init__(self, data, *args, **kwd)
     88 
     89         # Initialize with the parent...
---> 90         super(NDDataArray, self).__init__(data, *args, **kwd)
     91 
     92         # ...then reset uncertainty to force it to go through the

TypeError: super(type, obj): obj must be an instance or subtype of type
```

Somehow the "super" call isn't possible anymore when using "deprecated". But the [documentation](http://docs.astropy.org/en/stable/api/astropy.utils.decorators.deprecated.html#astropy.utils.decorators.deprecated) explicitly states that it should be possible to use the decorator with classes. Or am I doing something wrong?

**Comment by pllim** [comment] 2016-05-02 13:56
Try this:

```python
@deprecated('sometime')
class NDDataArray(NDData):
    pass
```

**Comment by MSeifert04** [comment] 2016-05-02 14:17
@pllim Thank you. Using it directly on the class works. Just using it from outside the module doesn't.

So this might not be an issue after all since you would seldom or never deprecate something from outside the source code. I'll leave it to you to close it or keep it open.

**Comment by pllim** [comment] 2016-05-02 14:22
I didn't use it in a module, I created the class in a Python session. I don't see this as an issue since decorator works when used with `@` as intended but I'll keep this open for now in case others want to chime in.

**Comment by bsipocz** [comment] 2017-04-20 12:01
@pllim @MSeifert04 - Shall we close this or do you think we need to make the original example work?

**Comment by MSeifert04** [comment] 2017-04-20 12:16
I encoutered it while debugging another issue so there was no real use-case anyway. But it was definetly weird that it didn't work so something is definetly wrong, but if it's broken by design or something that needs fixing: no idea.

**Comment by pllim** [comment] 2017-04-20 13:20
Maybe we will just re-open if there is a real use case? Closing for now.

**Closed by pllim** 2017-04-20 13:20 UTC
Labels: Close?, nddata, utils
