### ISSUE TITLE
rdb table fails to read as guess

### ISSUE THREAD

**Issue by adamjts** [astropy/astropy#4998] opened 2016-05-31 16:19 UTC
Unable to read table when guessed

```
In [11]: t = table.Table.read("marxs/missions/chandra/HESSdesign.rdb")
---------------------------------------------------------------------------
InconsistentTableError                    Traceback (most recent call last)
<ipython-input-11-4a5ab22025a8> in <module>()
----> 1 t = table.Table.read("marxs/missions/chandra/HESSdesign.rdb")

/Users/adamtheriault-shay/anaconda/lib/python2.7/site-packages/astropy-1.2.dev15522-py2.7-macosx-10.5-x86_64.egg/astropy/table/table.pyc in read(cls, *args, **kwargs)
   2330         passed through to the underlying data reader (e.g. `~astropy.io.ascii.read`).
   2331         """
-> 2332         return io_registry.read(cls, *args, **kwargs)
   2333 
   2334     def write(self, *args, **kwargs):

/Users/adamtheriault-shay/anaconda/lib/python2.7/site-packages/astropy-1.2.dev15522-py2.7-macosx-10.5-x86_64.egg/astropy/io/registry.pyc in read(cls, *args, **kwargs)
    349 
    350         reader = get_reader(format, cls)
--> 351         data = reader(*args, **kwargs)
    352 
    353         if not isinstance(data, cls):

/Users/adamtheriault-shay/anaconda/lib/python2.7/site-packages/astropy-1.2.dev15522-py2.7-macosx-10.5-x86_64.egg/astropy/io/ascii/connect.pyc in io_read(format, filename, **kwargs)
     35     from .ui import read
     36     format = re.sub(r'^ascii\.', '', format)
---> 37     return read(filename, format=format, **kwargs)
     38 
     39 

/Users/adamtheriault-shay/anaconda/lib/python2.7/site-packages/astropy-1.2.dev15522-py2.7-macosx-10.5-x86_64.egg/astropy/io/ascii/ui.pyc in read(table, guess, **kwargs)
    311         # through below to the non-guess way so that any problems result in a
    312         # more useful traceback.
--> 313         dat = _guess(table, new_kwargs, format, fast_reader_param)
    314         if dat is None:
    315             guess = False

/Users/adamtheriault-shay/anaconda/lib/python2.7/site-packages/astropy-1.2.dev15522-py2.7-macosx-10.5-x86_64.egg/astropy/io/ascii/ui.pyc in _guess(table, read_kwargs, format, fast_reader)
    494                    '************************************************************************']
    495             lines.extend(msg)
--> 496             raise core.InconsistentTableError('\n'.join(lines))
    497 
    498 def _get_guess_kwargs_list(read_kwargs):

InconsistentTableError: 
ERROR: Unable to guess table format with the guesses listed below:
Reader:FastRdb fill_values: [('', '0')]
Reader:Rdb fill_values: [('', '0')]
Reader:Rdb fill_values: [('', '0')]

************************************************************************
** ERROR: Unable to guess table format with the guesses listed above. **
**                                                                    **
** To figure out why the table did not read, use guess=False and      **
** appropriate arguments to read().  In particular specify the format **
** and any known attributes like the delimiter.                       **
************************************************************************
```

but able to read table when explicit

```
In [12]: t = table.Table.read("marxs/missions/chandra/HESSdesign.rdb", format="ascii.rdb")

In [13]: 
```

This is the table:

https://github.com/Chandra-MARX/marxs/blob/master/marxs/missions/chandra/HESSdesign.rdb

**Comment by hamogu** [comment] 2016-05-31 16:26
I've tried to reproduce that on my computer (with an astropy version that's only about 15 min newer) and I cannot reproduce it.

@taldcroft

**Comment by taldcroft** [comment] 2016-05-31 22:34
I also cannot reproduce.  Here is my setup:
```
platform darwin -- Python 2.7.11, pytest-2.8.3, py-1.4.30, pluggy-0.3.1

Running tests with Astropy version 1.2.dev15527.
Running tests in lib.macosx-10.5-x86_64-2.7/astropy docs.

Date: 2016-05-31T18:30:05

Platform: Darwin-13.4.0-x86_64-i386-64bit

Executable: /Users/aldcroft/anaconda/envs/astropy/bin/python

Full Python Version: 
2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)]

encodings: sys: ascii, locale: UTF-8, filesystem: utf-8, unicode bits: 15
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.11.0
Scipy: 0.17.0
Matplotlib: 1.5.1
h5py: not available
Pandas: not available
```
@adamjts - can you provide this info on your system?  `python setup.py test --args='-k blahblah'`.  (I expect there is a more elegant way to get this sys info but I don't know it).

**Comment by bsipocz** [comment] 2019-09-26 16:58
At least 3 of us couldn't reproduce this, and no follow-up was given, so I go ahead and close the issue.
(My guess would be that the local file was corrupt and thus wasn't recognized as a valid 'rdb' format, e.g. it didn't recognized the originally linked url (as it was pointing to a html page), but now works with the raw file link)

**Closed by bsipocz** 2019-09-26 16:58 UTC
Labels: table
