### ISSUE TITLE
Test failure with Numpy dev

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#10638] opened 2020-08-10 10:27 UTC
There is a new failure with Numpy dev on Travis:

```
=================================== FAILURES ===================================
______________________ TestAccessingParts.test_trim_zeros ______________________
filt = <Quantity [0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ] m>
trim = 'fb'
    @array_function_dispatch(_trim_zeros)
    def trim_zeros(filt, trim='fb'):
        """
        Trim the leading and/or trailing zeros from a 1-D array or sequence.
    
        Parameters
        ----------
        filt : 1-D array or sequence
            Input array.
        trim : str, optional
            A string with 'f' representing trim from front and 'b' to trim from
            back. Default is 'fb', trim zeros from both front and back of the
            array.
    
        Returns
        -------
        trimmed : 1-D array or sequence
            The result of trimming the input. The input data type is preserved.
    
        Examples
        --------
        >>> a = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
        >>> np.trim_zeros(a)
        array([1, 2, 3, 0, 2, 1])
    
        >>> np.trim_zeros(a, 'b')
        array([0, 0, 0, ..., 0, 2, 1])
    
        The input data type is preserved, list/tuple in means list/tuple out.
    
        >>> np.trim_zeros([0, 1, 2, 0])
        [1, 2]
    
        """
        try:
>           return _trim_zeros_new(filt, trim)
../../.tox/py37-test-devdeps/lib/python3.7/site-packages/numpy/lib/function_base.py:1629: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
filt = <Quantity [0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ] m>
trim = 'fb'
    def _trim_zeros_new(filt, trim='fb'):
        """Newer optimized implementation of ``trim_zeros()``."""
        arr = np.asanyarray(filt).astype(bool, copy=False)
    
        if arr.ndim != 1:
            raise ValueError('trim_zeros requires an array of exactly one dimension')
        elif not len(arr):
            return filt
    
        trim_upper = trim.upper()
        first = last = None
    
        if 'F' in trim_upper:
            first = arr.argmax()
            # If `arr[first] is False` then so are all other elements
>           if not arr[first]:
../../.tox/py37-test-devdeps/lib/python3.7/site-packages/numpy/lib/function_base.py:1659: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <Quantity True m>
    def __bool__(self):
        """Quantities should always be treated as non-False; there is too much
        potential for ambiguity otherwise.
        """
        warnings.warn('The truth value of a Quantity is ambiguous. '
                      'In the future this will raise a ValueError.',
>                     AstropyDeprecationWarning)
E       astropy.utils.exceptions.AstropyDeprecationWarning: The truth value of a Quantity is ambiguous. In the future this will raise a ValueError.
../../.tox/py37-test-devdeps/lib/python3.7/site-packages/astropy/units/quantity.py:1071: AstropyDeprecationWarning
The above exception was the direct cause of the following exception:
self = <astropy.units.tests.test_quantity_non_ufuncs.TestAccessingParts object at 0x7fc5e4013588>
    def test_trim_zeros(self):
        q = self.q.ravel()
>       out = np.trim_zeros(q)
../../.tox/py37-test-devdeps/lib/python3.7/site-packages/astropy/units/tests/test_quantity_non_ufuncs.py:361: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
<__array_function__ internals>:6: in trim_zeros
    ???
../../.tox/py37-test-devdeps/lib/python3.7/site-packages/astropy/units/quantity.py:1504: in __array_function__
    return super().__array_function__(function, types, args, kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
filt = <Quantity [0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ] m>
trim = 'fb'
    @array_function_dispatch(_trim_zeros)
    def trim_zeros(filt, trim='fb'):
        """
        Trim the leading and/or trailing zeros from a 1-D array or sequence.
    
        Parameters
        ----------
        filt : 1-D array or sequence
            Input array.
        trim : str, optional
            A string with 'f' representing trim from front and 'b' to trim from
            back. Default is 'fb', trim zeros from both front and back of the
            array.
    
        Returns
        -------
        trimmed : 1-D array or sequence
            The result of trimming the input. The input data type is preserved.
    
        Examples
        --------
        >>> a = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
        >>> np.trim_zeros(a)
        array([1, 2, 3, 0, 2, 1])
    
        >>> np.trim_zeros(a, 'b')
        array([0, 0, 0, ..., 0, 2, 1])
    
        The input data type is preserved, list/tuple in means list/tuple out.
    
        >>> np.trim_zeros([0, 1, 2, 0])
        [1, 2]
    
        """
        try:
            return _trim_zeros_new(filt, trim)
        except Exception as ex:
            # Numpy 1.20.0, 2020-07-31
            warning = DeprecationWarning(
                "in the future trim_zeros will require a 1-D array as input "
                "that is compatible with ndarray.astype(bool)"
            )
            warning.__cause__ = ex
>           warnings.warn(warning, stacklevel=3)
E           DeprecationWarning: in the future trim_zeros will require a 1-D array as input that is compatible with ndarray.astype(bool)
../../.tox/py37-test-devdeps/lib/python3.7/site-packages/numpy/lib/function_base.py:1637: DeprecationWarning
```

We could simply add the warning to those to include, but I'm guessing we probably actually want to fix the code to avoid breakage in future.

cc @mhvk

**Comment by mhvk** [comment] 2020-08-11 00:23
The problem is https://github.com/numpy/numpy/pull/16911 - in https://github.com/numpy/numpy/pull/16911#issuecomment-671654140, I suggest an easy fix that should make things work again, so I hope this can simply be resolved. If not, it is not difficult to fix on our side.

**Comment by pllim** [comment] 2020-08-13 15:36
I  *think* this will fix itself after numpy/numpy#17058 is merged?

**Comment by mhvk** [comment] 2020-08-14 00:16
Yes, that's the hope!

**Comment by mhvk** [comment] 2020-08-19 13:41
Upstream fix has been merged, so as soon as "nightly" is updated, we should be fine again...

**Comment by pllim** [comment] 2020-08-24 17:55
"nightly" is sure taking its own sweet time to pick up the patch. Still waiting... 👀

**Comment by pllim** [comment] 2020-08-28 14:04
Nightly finally updated. Fixed!

**Closed by pllim** 2020-08-28 14:04 UTC
Labels: Upstream Fix Required, numpy-dev, testing, units
