### ISSUE TITLE
Question: Why is io.fits convenience 'getdata' much faster than fits.open()?

### ISSUE THREAD

**Issue by mcara** [astropy/astropy#5918] opened 2017-03-28 18:13 UTC
```python
>>> import sys
>>> print(sys.version)
2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
>>> import astropy 
>>> astropy.__version__
u'2.0.dev17848'
>>> import timeit
>>> timeit.timeit("h=fits.open('jcdua3f4q_flc.fits'); d=h[3].data; h.close()",
... setup="from astropy.io import fits", number=1000) 
22.351375102996826
>>> timeit.timeit("d=fits.getdata('jcdua3f4q_flc.fits', ext=3)",
... setup="from astropy.io import fits", number=1000)
8.482270956039429
```
How is this possible and what can be done to make "regular" ``fits.io`` operations as fast as "convenience" functions?

**Comment by MSeifert04** [comment] 2017-03-28 18:24
That's really weird because essentially `_getext` (what is called by `getdata`) just does `fitsopen` and then extracts the relevant data. So these should be equivalent.

**Comment by pllim** [comment] 2017-03-28 18:26
Is caching done and affected the second test? Try do the timing in different Python sessions?

**Comment by MSeifert04** [comment] 2017-03-28 18:27
Well, timing IO is tricky at best but I have similar timings.

**Comment by mcara** [comment] 2017-03-28 18:27
@pllim Order of operations as well as number of sessions does not affect the outcome

**Comment by mcara** [comment] 2017-03-28 18:29
@MSeifert04 wrote:
> That's really weird because essentially ``_getext`` (what is called by ``getdata``) just does ``fitsopen`` and then extracts the relevant data. So these should be equivalent.

A possible hint may come from:

```python
>>> timeit.timeit("h=fits.open('jcdua3f4q_flc.fits', memmap=False);d=h[3].data", setup="from astropy.io import fits", number=1000) 
11.85682988166809
```

So, it appears that ``close()`` is responsible for most of the differences (but not all).

**Comment by MSeifert04** [comment] 2017-03-28 18:31
not closing the file gives you halves the timings?

**Comment by mcara** [comment] 2017-03-28 18:32
Yes. However, ``getdata()`` does close the files so things are still strange. However, maybe this last test could point to a culprit?

**Comment by pllim** [comment] 2017-03-28 18:33
Profiling it would give you some answers.

**Comment by mcara** [comment] 2017-03-28 18:43
This reading of all HDUs defeats any sort of "lazy" reading in fits.

**Comment by saimn** [comment] 2017-03-28 18:45
The explanation is in a comment in `getheader`:
https://github.com/astropy/astropy/blob/master/astropy/io/fits/convenience.py#L115

        # Use _close instead of close to close without loading any
        # remaining HDUs for pre-lazy-loading backwards compatibility
        # In other words, when the full HDUList is opened by a user they
        # previously expected to be able to look at arbitrary HDUs even
        # after the file was closed, but for getheader and other convenience
        # functions this is irrelevant

**Comment by mcara** [comment] 2017-03-28 18:49
Are we then supposed to use "private" ``_close()`` instead of ``close()`` if we no longer need ``HDUList``?

**Comment by mcara** [comment] 2017-03-28 19:13
It seems that ``close()`` was re-designed in https://github.com/astropy/astropy/pull/5065/commits/5c66c2d9d04ad561c774247d5c7497775b404d27 and this has destroyed any advantage that ``memmap=True`` might have had (which kind of was supposed to be a sort of "lazy" loading).

The irony of this comment https://github.com/astropy/astropy/pull/4634#issuecomment-221211151 can't be avoided.

**Comment by mcara** [comment] 2017-03-28 19:14
It seems that ``close()`` was re-designed in https://github.com/astropy/astropy/pull/5065/commits/5c66c2d9d04ad561c774247d5c7497775b404d27 and this has destroyed any advantage that ``memmap=True`` might have had (which kind of was supposed to be a sort of "lazy" loading).

The irony of this comment https://github.com/astropy/astropy/pull/4634#issuecomment-221211151 can't be avoided.

CC: @jhunkeler

**Comment by mcara** [comment] 2017-03-28 19:14
It seems that ``close()`` was re-designed in https://github.com/astropy/astropy/pull/5065/commits/5c66c2d9d04ad561c774247d5c7497775b404d27 and this has destroyed any advantage that ``memmap=True`` might have had (which kind of was supposed to be a sort of "lazy" loading).

The irony of this comment https://github.com/astropy/astropy/pull/4634#issuecomment-221211151 can't be avoided.

CC: @jhunkeler

**Comment by MSeifert04** [comment] 2017-03-28 19:16
Ah, great, I remember... never seen that deprecation warning though 😄

**Comment by MSeifert04** [comment] 2017-03-28 19:19
@mcara I think you pinged the wrong one, juliantaylor submitted the PR.

**Comment by MSeifert04** [comment] 2017-03-28 19:20
I thought we added a deprecation warning when accessing closed files. However I can do that without any problems (and/or warnings).

**Comment by saimn** [comment] 2017-03-28 19:31
@MSeifert04 - The commit mentioned by @mcara added the warning: https://github.com/astropy/astropy/pull/5065/commits/5c66c2d9d04ad561c774247d5c7497775b404d27#diff-817bd3a22004516f0dd0080e2cd0d9baR1028

Also, as written in this commit, this is only for headers. Reading data after close was already disabled, so I don't think there is an issue with `memap`, @mcara ?

And instead of using directly `_close`, an option would be to add a keyword to disable this behavior:
```
hdulist.close(no_really_do_not_load_all_other_hdus_please=True)
```
(This is also suggested in the commit message)

**Comment by mcara** [comment] 2017-03-28 19:33
Eh, here is the issue mentioned previously:
https://github.com/astropy/astropy/issues/5582

However in https://github.com/astropy/astropy/pull/5589 @mwcraig decided not to fix ``close()``.

Due to this weird implementation of "lazy", now regular functions are slower than "convenience" functions.

**Comment by saimn** [comment] 2017-03-28 19:37
If it can be removed for v2.0 it's even better indeed.

**Comment by pllim** [comment] 2017-03-28 19:44
Should we close this as duplicate of #5582 then?

**Comment by mwcraig** [comment] 2017-03-28 19:49
> However in #5589 @mwcraig decided not to fix close()

IIRC, that came down to running out of time before feature freeze. 😀 

In addition, the goal was not to change the previous behavior (in which headers remained available even after closing).

> hdulist.close(no_really_do_not_load_all_other_hdus_please=True)

I'd rather just remove this old behavior in 2.0.
 
> Should we close this as duplicate of #5582 then?

Sure; could you please also add a note over there referring to this issue? Would do it myself but about to run to a meeting...

**Closed** 2017-03-28 19:50 UTC
Labels: Duplicate, io.fits, Performance

**Comment by embray** [comment] 2017-03-30 08:56
> Due to this weird implementation of "lazy", now regular functions are slower than "convenience" functions.

In fairness, they're just as slow as they always were ;)
