### ISSUE TITLE
astropy time format error

### ISSUE THREAD

**Issue by luojing1211** [astropy/astropy#3237] opened 2014-12-19 03:32 UTC
Dear Astropy developer, 
I just updated my astropy to 1.0.dev10836. But I have the error when I creating time object. The message says:

```
>>> astropy.time.Time('2000-01-01 12:00:00.0',format = 'iso' ,scale='utc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jingluo/anaconda/lib/python2.7/site-packages/astropy-1.0.dev10836-py2.7-macosx-10.5-x86_64.egg/astropy/time/core.py", line 194, in __init__
    self._init_from_vals(val, val2, format, scale, copy)
  File "/Users/jingluo/anaconda/lib/python2.7/site-packages/astropy-1.0.dev10836-py2.7-macosx-10.5-x86_64.egg/astropy/time/core.py", line 236, in _init_from_vals
    self._time = self._get_time_fmt(val, val2, format, scale)
  File "/Users/jingluo/anaconda/lib/python2.7/site-packages/astropy-1.0.dev10836-py2.7-macosx-10.5-x86_64.egg/astropy/time/core.py", line 274, in _get_time_fmt
    raise ValueError('Input values did not match {0}'.format(err_msg))
ValueError: Input values did not match the format class iso
```

Can someone help me with this?

**Comment by profxj** [comment] 2015-01-11 02:31
I may be having a similar issue, but with SkyCoord:

from astropy.coordinates import SkyCoord

dumps with:

ValueError: Input values did not match any of the formats where the format keyword is optional [u'astropy_time', u'datetime', u'jyear_str', u'iso', u'isot', u'yday', u'byear_str']

Am running numpy 1.9.0

X

**Comment by profxj** [comment] 2015-01-11 02:36
Ah, a clean and rebuild did the trick:

git clean -fxd

**Comment by embray** [comment] 2015-01-13 15:52
It's also an unrelated issue.  The original issue seems to relate to a Numpy compatibility issue, though I have not confirmed this yet.

**Comment by luojing1211** [comment] 2015-01-14 15:37
I tried git clean -fxd. If works if I put the argument "format". It works
fine. But If I did not put "format",  it will break. I think that problem
will course trouble when import astropy. coordinate.
"""
>>> import astropy.time as t
>>> t.Time('2000-01-01 12:00:00.0',format = 'iso' ,scale='utc')
<Time object: scale='utc' format='iso' value=2000-01-01 12:00:00.000>
>>> t.Time('2000-01-01 12:00:00.0',scale='utc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File
"/Users/jingluo/anaconda/lib/python2.7/site-packages/astropy-1.0.dev11111-py2.7-macosx-10.5-x86_64.egg/astropy/time/core.py",
line 193, in __init__
    self._init_from_vals(val, val2, format, scale, copy)
  File
"/Users/jingluo/anaconda/lib/python2.7/site-packages/astropy-1.0.dev11111-py2.7-macosx-10.5-x86_64.egg/astropy/time/core.py",
line 235, in _init_from_vals
    self._time = self._get_time_fmt(val, val2, format, scale)
  File
"/Users/jingluo/anaconda/lib/python2.7/site-packages/astropy-1.0.dev11111-py2.7-macosx-10.5-x86_64.egg/astropy/time/core.py",
line 269, in _get_time_fmt
    self.in_subfmt, self.out_subfmt)
  File
"/Users/jingluo/anaconda/lib/python2.7/site-packages/astropy-1.0.dev11111-py2.7-macosx-10.5-x86_64.egg/astropy/time/core.py",
line 1590, in __new__
    'astropy Time type.'.format(cls.name))
TypeError: Input values for astropy_time class must all be same astropy
Time type.
"""

**Comment by mhvk** [comment] 2015-01-14 15:53
@luojing1211 - this is very weird indeed. Since for numpy <=1.8 there were some issues with scalar vs more dimensions, could you try:
```
t.Time(['2000-01-01 12:00:00.0'],scale='utc')
```

**Comment by mhvk** [comment] 2015-01-14 16:00
p.s. Sadly, I cannot reproduce the error on my Debian machine, even with numpy 1.8.1 (I'm at astropy 1.0.dev11388).

**Comment by luojing1211** [comment] 2015-01-14 17:12
I tried 
```
t.Time(['2000-01-01 12:00:00.0'],scale='utc')
```

It is still show the same error. By the way, I am at the version of 1.0dev111111

**Comment by luojing1211** [comment] 2015-01-14 21:02
I updated my astropy version to '1.0.dev11395'. But it still gives the error. Is it possibly a Mac issue?

**Comment by embray** [comment] 2015-01-14 21:39
I can't reproduce it either.  Where did your copy of Numpy come from?

**Comment by embray** [comment] 2015-01-14 21:40
@luojing1211 Also, as it seems you are building Astropy from source, what version of Cython are you using?  It's conceivable your version of Cython has a bug (it would not be the first time that's happened).

**Comment by luojing1211** [comment] 2015-01-15 16:22
My Numpy should come from pip and my Cython version is 0.20.1

**Comment by embray** [comment] 2015-01-15 17:54
It looks like you're using Anaconda though.  I suspect there's something wrong with your Numpy installation--maybe try removing all installations of Numpy and Astropy and reinstall Numpy using conda.

**Comment by luojing1211** [comment] 2015-01-15 18:05
I somehow used both. but I think pip install the package to conda. But I
will try it.

-Luo Jing

**Comment by luojing1211** [comment] 2015-01-16 05:27
I reinstalled numpy and astropy. It seems working. Thank you.

**Comment by astrofrog** [comment] 2015-01-16 15:11
Ok, great! Closing this issue.

**Closed by astrofrog** 2015-01-16 15:11 UTC
Labels: Affects-dev, Bug, Needs-clarification, time
