### ISSUE TITLE
ValueError upon importing `SkyCoord` from `astropy.coordinates` in virtualenv

### ISSUE THREAD

**Issue by karenyyng** [astropy/astropy#3536] opened 2015-02-23 07:07 UTC
I am unable to run the following code for `astropy v1.0`  without error 
```py
>>> from astropy.coordinates import SkyCoord
```
`astropy v0.4.4` works without error for the same command.

And the following is the pytest failure report at `VIRTUALENV/python2.7/site-packages/astropy/tests/tests`

```
$ py.test .
======================================= test session starts ========================================
platform darwin -- Python 2.7.9 -- py-1.4.26 -- pytest-2.6.4
/Users/karenyng/Documents/Illustris_analysis/IEnv/lib/python2.7/site-packages/h5py/__init__.py:13: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility
  from h5py import _conv
/Users/karenyng/Documents/Illustris_analysis/IEnv/lib/python2.7/site-packages/h5py/__init__.py:16: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility
  from h5py import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z
/Users/karenyng/Documents/Illustris_analysis/IEnv/lib/python2.7/site-packages/h5py/_hl/group.py:15: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility
  from h5py import h5g, h5i, h5o, h5r, h5t, h5l, h5p

Running tests with Astropy version 1.0.
Running tests in ..

Platform: Darwin-14.1.0-x86_64-i386-64bit

Executable: /Users/karenyng/Documents/Illustris_analysis/IEnv/bin/python2.7

Full Python Version:
2.7.9 (default, Dec 14 2014, 10:02:06)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]

encodings: sys: ascii, locale: UTF-8, filesystem: utf-8, unicode bits: 15
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.9.1
Scipy: 0.15.1
Matplotlib: 1.4.2
h5py: 2.4.0

collected 16 items

test_imports.py F.
test_open_file_detection.py .
test_quantity_helpers.py .
test_run_tests.py ........
test_skip_remote_data.py s
test_socketblocker.py ...

============================================= FAILURES =============================================
___________________________________________ test_imports ___________________________________________

    def test_imports():
        """
        This just imports all modules in astropy, making sure they don't have any
        dependencies that sneak through
        """

        from ...utils import find_current_module

        pkgornm = find_current_module(1).__name__.split('.')[0]

        if isinstance(pkgornm, six.string_types):
            package = pkgutil.get_loader(pkgornm).load_module(pkgornm)
        elif (isinstance(pkgornm, types.ModuleType) and
                '__init__' in pkgornm.__file__):
            package = pkgornm
        else:
            msg = 'test_imports is not determining a valid package/package name'
            raise TypeError(msg)

        if hasattr(package, '__path__'):
            pkgpath = package.__path__
        elif hasattr(package, '__file__'):
            pkgpath = os.path.split(package.__file__)[0]
        else:
            raise AttributeError('package to generate config items for does not '
                                 'have __file__ or __path__')

        if six.PY3:
            excludes = _py2_packages
        else:
            excludes = _py3_packages

        prefix = package.__name__ + '.'

        def onerror(name):
            if not any(name.startswith(excl) for excl in excludes):
                # A legitimate error occurred in a module that wasn't excluded
                raise

        for imper, nm, ispkg in pkgutil.walk_packages(pkgpath, prefix,
>                                                     onerror=onerror):
            imper.find_module(nm)

test_imports.py:67:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py:116: in walk_packages
    onerror(name)
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py:110: in walk_packages
    __import__(name)
../../coordinates/__init__.py:17: in <module>
    from .builtin_frames import *
../../coordinates/builtin_frames/__init__.py:28: in <module>
    from .fk5 import FK5
../../coordinates/builtin_frames/fk5.py:10: in <module>
    from .. import earth_orientation as earth
../../coordinates/earth_orientation.py:19: in <module>
    jd1950 = Time('B1950', scale='tai').jd
../../time/core.py:198: in __init__
    self._init_from_vals(val, val2, format, scale, copy)
../../time/core.py:240: in _init_from_vals
    self._time = self._get_time_fmt(val, val2, format, scale)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <[AttributeError("'Time' object has no attribute '_time'") raised in repr()] SafeRepr object at 0x1099d1f80>
val = array(u'B1950',
      dtype='<U5'), val2 = None, format = 'byear_str', scale = 'tai'

    def _get_time_fmt(self, val, val2, format, scale):
        """
            Given the supplied val, val2, format and scale try to instantiate
            the corresponding TimeFormat class to convert the input values into
            the internal jd1 and jd2.

            If format is `None` and the input is a string-type or object array then
            guess available formats and stop when one matches.
            """

        if format is None and val.dtype.kind in ('S', 'U', 'O'):
            formats = [(name, cls) for name, cls in self.FORMATS.items()
                       if issubclass(cls, TimeUnique)]
            err_msg = ('any of the formats where the format keyword is '
                       'optional {0}'.format([name for name, cls in formats]))
        elif not (isinstance(format, six.string_types) and
                  format.lower() in self.FORMATS):
            if format is None:
                raise ValueError("No time format was given, and the input is "
                                 "not unique")
            else:
                raise ValueError("Format {0} is not one of the allowed "
                                 "formats {1}".format(repr(format),
                                                      sorted(self.FORMATS)))
        else:
            formats = [(format, self.FORMATS[format])]
            err_msg = 'the format class {0}'.format(format)

        for format, FormatClass in formats:
            try:
                return FormatClass(val, val2, scale, self.precision,
                                   self.in_subfmt, self.out_subfmt)
            except (ValueError, TypeError):
                pass
        else:
>           raise ValueError('Input values did not match {0}'.format(err_msg))
E           ValueError: Input values did not match any of the formats where the format keyword is optional [u'astropy_time', u'datetime', u'jyear_str', u'iso', u'isot', u'yday', u'byear_str']

../../time/core.py:278: ValueError
========================== 1 failed, 14 passed, 1 skipped in 1.14 seconds ==========================
```

**Comment by embray** [comment] 2015-02-23 22:12
Hi @karenyyng thanks for the report.

The recommended (if not required) ways to run the Astropy tests are as follows:

1. If running out of a source checkout run `python setup.py test`

2. If running the tests for an installed version of Astropy run `astropy.test()` from the Python prompt.

This is for a number of reasons.

In this case the specific error you got is a bit odd though and suggests that you have *overlapping* astropy installations in the same virtualenv (I wasn't able to reproduce this directly).  The best thing to do would be to uninstall and reinstall at least for that virtualenv).  This looks like a duplicate of #3278 which again just has to do with upgrading versions without a bit of cleanup first.

**Comment by embray** [comment] 2015-02-25 15:58
I'm closing this for now, but feel free to reopen if you're continuing to have trouble, thanks!

**Closed by embray** 2015-02-25 15:58 UTC
Labels: testing
