### ISSUE TITLE
Missing values in rows when initializing Table

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#6713] opened 2017-10-11 12:00 UTC
In the following example it would be nice if Table could gracefully set ``b`` to be a masked element in the second row:

```
In [6]: t = Table(rows=[{'a':1, 'b':2}, {'a':2}], masked=True, names=['a','b'])
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/miniconda3/envs/dev/lib/python3.6/site-packages/astropy/table/table.py in _init_from_list_of_dicts(self, data, names, dtype, n_cols, copy)
    636                 try:
--> 637                     cols[name].append(row[name])
    638                 except KeyError:

KeyError: 'b'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-6-e7f8da490031> in <module>()
----> 1 t = Table(rows=[{'a':1, 'b':2}, {'a':2}], masked=True, names=['a','b'])

~/miniconda3/envs/dev/lib/python3.6/site-packages/astropy/table/table.py in __init__(self, data, masked, names, dtype, meta, copy, rows, copy_indices, **kwargs)
    411 
    412         # Finally do the real initialization
--> 413         init_func(data, names, dtype, n_cols, copy)
    414 
    415         # Whatever happens above, the masked property should be set to a boolean

~/miniconda3/envs/dev/lib/python3.6/site-packages/astropy/table/table.py in _init_from_list(self, data, names, dtype, n_cols, copy)
    648         """
    649         if data and all(isinstance(row, dict) for row in data):
--> 650             self._init_from_list_of_dicts(data, names, dtype, n_cols, copy)
    651             return
    652 

~/miniconda3/envs/dev/lib/python3.6/site-packages/astropy/table/table.py in _init_from_list_of_dicts(self, data, names, dtype, n_cols, copy)
    637                     cols[name].append(row[name])
    638                 except KeyError:
--> 639                     raise ValueError('Row {0} has no value for column {1}'.format(i, name))
    640         if all(name is None for name in names):
    641             names = sorted(names_from_data)

ValueError: Row 1 has no value for column b
```

@taldcroft - what do you think?

**Comment by ayush1999** [comment] 2017-10-17 16:58
@astrofrog I think we could set the values of columns not defined (such as 'b' in the second line of the above table) to be None , if the person hasn't explicitly mentioned in the `rows` argument.

Doing this, we would get:
```
>>> t = Table(rows=[{'a':1, 'b':2}, {'a':2}], masked=True, names=['a','b'])
>>> t
 a    b 
---- ---
   1   2
   2   None

```

If this is a correct approach, I'd like to implement it. Any thoughts?

**Comment by pllim** [comment] 2017-10-17 17:47
@ayush1999 , the original request wants the missing value to be *masked*, so just setting it to `None` without any masking is not quite sufficient.

**Comment by ayush1999** [comment] 2017-10-18 07:24
@pllim We could set the mask value for all those keys with value False to True in that case.

**Comment by taldcroft** [comment] 2019-04-01 09:41
This is duplicate of #5283.

**Closed by taldcroft** 2019-04-01 09:41 UTC
Labels: Duplicate, table
