### ISSUE TITLE
Unit parser only issues warning rather than throwing an exception for completely invalid string when using "vounit" format

### ISSUE THREAD

**Issue by JeremyMcCormick** [astropy/astropy#16199] opened 2024-03-14 21:17 UTC
### Description

The following warning prints when I define a unit in "vounit" format with a non-sensical string:

```
WARNING: UnitsWarning: Unit 'bad' not supported by the VOUnit standard. Did you mean Ba (deprecated), aD, ad or g.cm**-1.s**-2? [astropy.units.format.vounit]
```

This should be throwing an exception, because "bad" is a completely invalid string for a units definition.

### Expected behavior

The parser for "vounit" should be throwing an exception in this case and not just issuing a warning when `parse_strict="raise"` is set. Otherwise, it cannot be used programmatically to check VOUnit and raise errors when invalid ones are used.

The regular expression matching used [here](https://github.com/astropy/astropy/blob/92a96e111bd80f3d53d08f51049eefef69af287a/astropy/units/format/vounit.py#L102) represents undesirable behavior to me. The parser should not be doing fuzzy matching on strings which do not represent valid units and then issuing warnings instead of exceptions when it finds a string that _kind of_ appears similar. 

### How to Reproduce

```
from astropy.unit import Unit
Unit("bad", format="vounit", parse_strict="raise")  # This should raise an exception but does not.
```

### Versions

```
In [20]: astropy.__version__
Out[20]: '5.3.4'
```

**Comment by pllim** [comment] 2024-03-14 21:49
That said, this throws an exception even though theoretically it went though similar logic route. 🤯 

```python
from astropy.units.format.cds import CDS
CDS._parser.parser.parse("bad")
```

**Comment by pllim** [comment] 2024-03-14 21:57
FWIW if I comment out this line, it would respect `parse_strict` but I don't know why this line was added back in #11258 by @aragilar (and approved by @adrn).

```diff
--- a/astropy/units/format/vounit.py
+++ b/astropy/units/format/vounit.py
@@ -111,7 +111,7 @@ class VOUnit(generic.Generic):
                     core.UnitsWarning,
                 )

-                return cls._def_custom_unit(t.value)
+                #return cls._def_custom_unit(t.value)

             raise
```

**Comment by gpdf** [comment] 2024-03-15 02:44
There's clearly tension between
* flexibly dealing with units that users find in datasets in the wild (as well as avoiding avalanches of nuisance warning messages); and
* assisting data publishers in rigorously verifying that their published data follows applicable standards.

The former is of course of interest to way more users of Astropy.  But I think it's important for data publishers (@JeremyMcCormick and I are with the Rubin Observatory) to have the tools to do this properly.  Our intent is to validate our published units specifically against VOUnit.  From what I understand, the `parse_strict` option is the tool we should be using to do this.

**Comment by aragilar** [comment] 2024-03-15 09:28
Looking at git blame, that was part of the changes @mhvk made to the PR. @mhvk do you recall why the VOUnit changes were made?

**Comment by mhvk** [comment] 2024-03-15 12:45
I don't recall in detail, but recall the vounit specification has a very liberal idea about custom units. I do agree it would be nice to allow checking things without having to turn warnings into errors, and `parse_strict` seems logical for it... I think passing that down would make sense!

**Comment by neutrinoceros** [comment] 2024-03-15 15:23
I think this is somewhat up my alley so if no one else is already working on a fix I'm happy to give it a go !

**Comment by eerovaher** [comment] 2024-03-15 16:58
From what I can tell this is a duplicate of #6302 and #13017. #13042 was an attempt to fix the problem.

I am not very familiar with the VOUnit standard, but from what I remember from participating in the discussions the last time this was brought up is that apparently `"bad"` is a valid unit as far as VOUnit is concerned. You can look up the details and references in the issues and pull request I mentioned.

**Comment by gpdf** [comment] 2024-03-15 18:15
@eerovaher I think you are in essence referring to the following text from the standard?

> In general, this Recommendation is concerned almost exclusively with the syntactic question of what is and is not a valid unit string, leaving most questions of interpretation or enforcement to a higher layer in an application stack. Specifically:
> 
> * The specification does not forbid `unknown' units. An implementation of this specification should be able to recognise, and communicate, that a unit is unknown, but it is not required to reject a unit string on the grounds that it is unrecognised.

(I.e., I don't think `bad` is exactly like `furlong` with its famous prefix interpretation.)

Let's be clear what this says: "an implementation ... is not required to reject [an unrecognized] unit string".  But it is not _forbidden_ from doing so.  This goes to my previous comment.

If we expect Astropy to be used by people who are *creating* data, not just *reading existing* data in a permissive, annoyance-reducing way, it absolutely should have a way to validate units for being recognized VOUnit strings (the issue in this ticket) as well as a simple way to verify that in-memory `Unit` objects can be written out as a recognized VOUnit expression (not exactly the subject of this ticket).

The more we support writing valid VOUnit strings, the less, over time, the leniencies at read time may be needed.

**Comment by mhvk** [comment] 2024-03-15 18:26
Thanks, @eerovaher, for finding those older issues - I knew there was something but didn't find them quickly enough! And thanks, @gpdf, for the good summary.

Looking at the older issues, there seemed a general consensus on the outcome `parse_strict='raise'` should, in fact, raise on an unrecognized unit.

I'd love to see a new PR, though clearly the travails of #13042 shows that it is not as trivial as one might think.

**Comment by JeremyMcCormick** [comment] 2024-03-18 20:05
I would like to point out if it is not clear from the discussion that the unit validation in "vounit" format just prints warnings for other non-standard unit strings and not just in my "bad" example. :)

```
WARNING: UnitsWarning: Unit 'day' not supported by the VOUnit standard. Did you mean daJy, daRy or dayr? [astropy.units.format.vounit]
WARNING:astropy:UnitsWarning: Unit 'day' not supported by the VOUnit standard. Did you mean daJy, daRy or dayr?
WARNING: UnitsWarning: Unit 'degree' not supported by the VOUnit standard.  [astropy.units.format.vounit]
WARNING:astropy:UnitsWarning: Unit 'degree' not supported by the VOUnit standard. 
WARNING: UnitsWarning: Unit 'DN' not supported by the VOUnit standard. Did you mean dN or daN? [astropy.units.format.vounit]
WARNING:astropy:UnitsWarning: Unit 'DN' not supported by the VOUnit standard. Did you mean dN or daN?
WARNING: UnitsWarning: Unit 'second' not supported by the VOUnit standard.  [astropy.units.format.vounit]
WARNING:astropy:UnitsWarning: Unit 'second' not supported by the VOUnit standard. 
WARNING: UnitsWarning: Unit 'nmgy' not supported by the VOUnit standard.  [astropy.units.format.vounit]
WARNING:astropy:UnitsWarning: Unit 'nmgy' not supported by the VOUnit standard. 
```

When running with "vounit" format, deviations from the VOUnit standard should result in an exception when `parse_strict='raise'` is set. If the user wants less strict parsing of their unit strings with exceptions still enabled, then the format argument can simply be left to the default, which will accept these units without complaining.

Additional minor issue: Warnings messages are being printed twice.

**Comment by JeremyMcCormick** [comment] 2024-04-17 23:42
Any progress on this or plans to include a fix in an upcoming release?

We would very much like to be able to validate against the IVOA units specification and get proper exceptions when errors occur.

**Comment by neutrinoceros** [comment] 2024-04-18 13:57
It's definitely non trivial to fix, and there were already multiple failed attempts, so I don't want to make any promises here. However, I am still up for it if others think it's worth prioritizing.

**Closed** 2024-10-24 14:49 UTC
Labels: io.votable, units, Bug
