### ISSUE TITLE
Potential Bug in u.quantity_input

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy#3289] opened 2015-01-13 09:33 UTC
I will test this and write a patch this evening, but I wanted to just raise it here.

Please see sunpy/sunpy#1255.

**Comment by embray** [comment] 2015-01-13 17:33
Did you intend to close this?

**Comment by Cadair** [comment] 2015-01-13 17:34
@embray see #3293.

**Comment by embray** [comment] 2015-01-13 17:40
Issues should only be closed if the PR addressing the issue is merged.

**Comment by Cadair** [comment] 2015-01-13 17:44
fair enough, as this was just a stub, I thought I would replace it with a more detailed issue in #3293.

**Comment by Cadair** [comment] 2015-01-22 15:37
This was closed by #3293.

**Closed** 2015-01-22 15:44 UTC
Labels: Affects-dev, Bug, units
