### ISSUE TITLE
 astropy not future proof( Python 4 )

### ISSUE THREAD

**Issue by yeganer** [astropy/astropy#4552] opened 2016-02-02 09:32 UTC
While having a look at the pytest_plugins i noticed several occassions where
```
if six.PY2:
    <code>
elif six.PY3:
    <code>
```
was used.
For future proof applications that won't need a complete code review(like what happened when python3 was released), checking for `six.PY3` should be avoided. Instead write `if six.PY2` and put the python3 code into `else` instead of `elif six.PY3`. By treating python2 as the special case python3 and python3+ will behave the same which is desirable since the python dev team announced they won't do major changes to the code like what they did when going from python2 to python3

I know this won't be an issue for the near future. But since i think this awesome project will witness python4, I just wanted to let you know this Issue so new additions to the code can be made with this knowledge.

**Comment by astrofrog** [comment] 2016-02-02 09:55
@yeganer - thanks for opening this! It's a duplicate of https://github.com/astropy/astropy/issues/4477 so I'm going to close this, but feel free to continue the discussion then! If you're happy to work on fixing this, that would be great!

**Closed by astrofrog** 2016-02-02 09:55 UTC
