### ISSUE TITLE
WCSAxes do not accept fontsize for set_xlabel and set_ylabel

### ISSUE THREAD

**Issue by stephtdouglas** [astropy/astropy#5686] opened 2017-01-10 16:33 UTC
When using a WCSAxes object, I can't set the fontsize for the x and y labels. I get this error:

TypeError: set_xlabel() got an unexpected keyword argument 'fontsize'

I found the error while developing this code:

and a minimum working example is attached. 
[min_ex.py.zip](https://github.com/astropy/astropy/files/696729/min_ex.py.zip)

**Comment by astrofrog** [comment] 2017-01-10 16:55
It looks like we need to add a ``**kwargs`` to ``WCSAxes.set_xlabel`` and ``WCSAxes.set_ylabel`` and pass it to the ``set_axislabel`` call. In addition, we should add a ``labelpad`` keyword argument and pass it to ``minpad`` in ``set_axislabel``. I think then we'll reproduce the ``set_xlabel``/``set_ylabel`` API.

**Comment by astrofrog** [comment] 2017-01-10 16:57
Marking this as a bug since the original intent was that ``set_xlabel`` and ``set_ylabel`` should work seamlessly.

In the mean time, you can set the axis label properly with font size using

```
ax.coords[0].set_axislabel('x label', fontsize=10)
ax.coords[1].set_axislabel('y label', fontsize=10)
```

**Closed** 2017-05-12 10:17 UTC
Labels: Bug, Effort-low, Package-novice, visualization.wcsaxes
