### ISSUE TITLE
fits.writeto(<newfile>, output_verify="ignore") modifies .fits header

### ISSUE THREAD

**Issue by chrisleet** [astropy/astropy#5221] opened 2016-08-07 00:11 UTC
The code:

``` python
g = fits.open("foo")
g.writeto("bar", output_verify="ignore")
```

Produces the output:

``` python
WARNING: Overwriting existing file u'Spectra/Corrected/bar'. [astropy.io.fits.file]
WARNING: VerifyWarning: Verification reported errors: [astropy.io.fits.verify]
WARNING: VerifyWarning: Card 'GAINS' is not FITS standard
(invalid value string: "'5.00000, 5.17000, 4.73000, 5.40000, 1.30900, 1.28300, 1.26600, 1.25").
Fixed 'GAINS' card to meet the FITS standard. [astropy.io.fits.verify]
WARNING: VerifyWarning: Note: PyFITS uses zero-based indexing.
 [astropy.io.fits.verify]
```

The GAINS card is changed in the header. If .writeto is called with output_verify="warn", there is no such problem. 

My understanding of ignore is:
"This option will ignore any FITS standard violation. On output, it will write the HDU List content to the output FITS file, whether or not it is conforming to FITS standard...No warning message will be printed out. This is like a silent warn (see below) option."

Am I messing up, or is this incorrect behaviour?

**Comment by pllim** [comment] 2016-08-08 13:31
Some questions:

1. What version of Astropy are you using?
2. Do you still see the same behavior using the `dev` version from `master`?
3. The printed warnings do not match your command. The warnings suggest a behavior of `fix+warn`. Are you sure you are not accidentally looking at warnings produce by other parts of your codes? It is best to provide a standalone working example in which someone else can reproduce the same problem.

**Comment by chrisleet** [comment] 2016-08-11 11:11
I might have been a total dope and forgot to upgrade. Let me upgrade and
test. Thanks for the error reporting advice - registered for further use.

I am sure that the warning doesn't come from anywhere else in my code,
however, because I only call writeTo once in the entire program. Let me
create a toy program for you to see if I can replicate the problem.

**Comment by bsipocz** [comment] 2016-12-05 03:29
@pllim - It looks like to be a duplicate of #5146, or vice versa.

**Comment by pllim** [comment] 2016-12-05 15:00
@bsipocz , yes does seem like a duplicate. Let's keep the earlier issue and close this one.

**Closed by pllim** 2016-12-05 15:00 UTC
Labels: io.fits
