### ISSUE TITLE
Failing test in time/test_precision.py

### ISSUE THREAD

**Issue by larrybradley** [astropy/astropy#13302] opened 2022-06-02 02:16 UTC
### Description

The `test_day_fract_exact` test is failing for me locally (macOS w/Python 3.10.4):

```
i = 1, f = 0.49999999999999994

    @given(integers(-2**52+2, 2**52-2), floats(-0.5, 0.5))
    @example(i=65536, f=3.637978807091714e-12)
    def test_day_frac_exact(i, f):
        assume(abs(f) < 0.5 or i % 2 == 0)
        i_d, f_d = day_frac(i, f)
>       assert i == i_d
E       assert 1 == 2.0

tests/test_precision.py:345: AssertionError
```

### System Details

macOS-10.15.7-x86_64-i386-64bit
Python 3.10.4 (main, May 18 2022, 14:44:41) [Clang 12.0.0 (clang-1200.0.32.29)]
Numpy 1.22.4
pyerfa 2.0.0.1
astropy 5.2.dev94+g2288ecd4e
Scipy 1.8.1
Matplotlib 3.5.2

**Comment by pllim** [comment] 2022-06-02 02:25
I think this is a duplicate of #13275

**Closed** 2022-06-02 03:58 UTC
Labels: testing, time, Bug, Duplicate
