### ISSUE TITLE
HCRS frame : scalar 'CartesianRepresentation' object is not iterable

### ISSUE THREAD

**Issue by dragonlost** [astropy/astropy#7565] opened 2018-06-15 00:56 UTC
Hello.

I have a bug. Or, a bad use:
```python
a = HCRS(x=0*u.km, y=0*u.km, z=0*u.km, v_x=0*u.km/u.s, v_y=0*u.km/u.s, v_z=0*u.km/u.s, representation_type=CartesianRepresentation, differential_type=CartesianDifferential)
```
Then
```python
a.transform_to(ICRS) 
```
I get : 
```python
TypeError: scalar 'CartesianRepresentation' object is not iterable.
```
Same if I do the opposite.

EDIT: Formatting.

**Comment by adrn** [comment] 2018-08-05 07:47
Strange. No immediate idea what's going on here - will take a look. One other piece of info: this works

```python
a = HCRS(x=0*u.km, y=0*u.km, z=0*u.km, 
         representation_type=CartesianRepresentation)
a.transform_to(ICRS)
```

**Comment by adrn** [comment] 2018-08-05 07:55
Just found #6835 - this is a duplicate of that issue, so closing this one in favor of that (in which @mhvk comments with a better idea of what's going on!)

**Closed by adrn** 2018-08-05 07:55 UTC
Labels: coordinates
