### ISSUE TITLE
Selecting an ephemeris other than "builtin" produces inconsistent GCRS frames

### ISSUE THREAD

**Issue by mcbeth** [astropy/astropy#7760] opened 2018-08-23 12:52 UTC
When selecting a different ephemeris for the solar system (which provides ICRS locations of the different bodies, including earth), the default GCRS coordinate system stops being geocentric.

For example:
```python
In [1]: from astropy.coordinates import get_body_barycentric, ICRS, GCRS

In [2]: from astropy.time import Time

In [3]: time = Time("2005-01-01")

In [4]: ICRS(get_body_barycentric('earth', Time("2005-01-01"), ephemeris='jpl')).transform_to(GCRS(obstime=time)).cartesian
Out[4]: 
CartesianRepresentation (x, y, z) in km
    (4.86300568, 1.52534008, 1.54617195)
```

**Comment by Juanlu001** [comment] 2018-08-24 11:14
Thanks for reporting @mcbeth, I was writing the same issue right now and decided to gave a look first :sweat_smile: 

One thing to add is that the default builtin ephemeris produces the expected result:

```
In [8]: ICRS(get_body_barycentric('earth', t, ephemeris='jpl')).transform_to(GCRS(obstime=t)).cartesian
Out[8]: 
<CartesianRepresentation (x, y, z) in km
    (6.79952462, 5.24546869, 3.41473439)>

In [9]: ICRS(get_body_barycentric('earth', t)).transform_to(GCRS(obstime=t)).cartesian
Out[9]: 
<CartesianRepresentation (x, y, z) in AU
    (0., 0., 0.)>
```

It was hypothesized that this could be because of the known errors of epv00 from ERFA:

https://github.com/liberfa/erfa/blob/27c2153cfb28d2e373b145c1188b46d84487fead/src/epv00.c#L76-L86

However, as far as I see it, this function is only being called for the builtin ephemerides:

https://github.com/astropy/astropy/blob/7fe49707f980519a500fd1aba9cde0152d593b7f/astropy/coordinates/solar_system.py#L216-L218

and it's not being called in the `ICRS -> GCRS` transformation:

https://github.com/astropy/astropy/blob/e9dee2e9589adfe4f0c803246add11164da03b83/astropy/coordinates/builtin_frames/icrs_cirs_transforms.py#L118-L133

https://github.com/liberfa/erfa/blob/27c2153cfb28d2e373b145c1188b46d84487fead/src/apcs.c#L84-L87

**Comment by Juanlu001** [comment] 2018-08-24 11:38
The fact that the global ephemerides is used means that, if it's properly set, the results are self consistent:

```
In [40]: solar_system_ephemeris.set("builtin")
Out[40]: <ScienceState solar_system_ephemeris: 'builtin'>

In [41]: get_body("earth", t).cartesian
Out[41]: 
<CartesianRepresentation (x, y, z) in AU
    (0., 0., 0.)>

In [42]: solar_system_ephemeris.set("jpl")
Out[42]: <ScienceState solar_system_ephemeris: 'jpl'>

In [43]: get_body("earth", t).cartesian
Out[43]: 
<CartesianRepresentation (x, y, z) in km
    (0., 0., 0.)>
```

So the problems arise when using an ephemeris different from the one that is globally set for the position. I can hardly see this as a buggy behavior, although the fact that it tooks us a while to realize what was going on means that there's some missing warning or documentation somewhere.

**Comment by mcbeth** [comment] 2018-08-24 11:42
Looks like that went in here:
https://github.com/astropy/astropy/commit/2961e46babfc61002e4882c6e51d10da7e1f840f#diff-e3c1a68894242b256b6fc6a14db4a099

**Comment by Juanlu001** [comment] 2018-08-24 11:45
Thanks for the pointer. From the corresponding pull request:

> This PR fixes #4942 by allowing the coordinate transformations, and the light travel time corrections which use them to respect the state of the solar_system_ephemeris context manager. [...] The reason for this decision was that adding an ephemeris argument to the co-ordinate transforms meant adding a kwargs argument to all frame transforms when this was not really needed for most of them.

So I guess this is by design.

**Comment by mcbeth** [comment] 2018-08-24 11:45
I agree that this no longer looks like a bug.

I got mislead by getting the same answer when I was building the minimum reproduceable example getting the same answer on new astropy with a local ephemeris override as on old astropy with a global ephemeris override (my real code).

Thanks for your attention

**Comment by mhvk** [comment] 2018-08-26 19:03
@mcbeth, @Juanlu001 - thanks for investigating. I agree with the conclusion that this is not really a bug, but given that it took a bit of to and fro to figure out what was happening, it seems clear the documentation could be clearer. But how? One place might be `get_body_barycentric` - there is already a note about the ephemeris, so it might be a good place to note that if one uses coordinate transformations as well, one has to be sure to be consistent, and that the easiest way to ensure that is to use the context manager.

**Comment by mhvk** [comment] 2019-01-28 20:48
@mcbeth, @Juanlu001 - would either of you be willing to update the documentation to help prevent get others confused? If not, no big deal, but probably good to just close the issue then.

**Comment by Juanlu001** [comment] 2019-01-28 22:14
@mhvk I revisited `get_body_barycentric` documentation and I can't think of a way to improve it. _Problem in chair, not in computer_? :)

I agree with closing this issue.

**Comment by mhvk** [comment] 2019-01-28 22:58
OK, thanks! Closing.

**Closed by mhvk** 2019-01-28 22:58 UTC
Labels: Close?, coordinates, question
