### ISSUE TITLE
Stable docs have unstable version number

### ISSUE THREAD

**Issue by dstansby** [astropy/astropy#11673] opened 2021-04-30 13:47 UTC
https://docs.astropy.org/en/stable/ appears to have a development version number (see top left). It should have a stable version number. Interestingly we're also seeing the same issue over at sunpy (https://github.com/sunpy/sunpy/issues/5225)

**Comment by pllim** [comment] 2021-04-30 14:15
Can't speak for SunPy but I think the one in `astropy` is a side effect of us fixing RTD after release without making a `post` release. It should go back to normal after 4.3 release, which is going to happen soon. 🤞

**Comment by pllim** [comment] 2021-04-30 14:16
But let's keep this open to double check. I'll assign this to the release manager for 4.3.

**Comment by eteq** [comment] 2021-05-12 15:58
To leave a bit more here (since it might be good for future releasers): in #11734 we're doing a quick change *just* in the `stable` branch to update the version number. As @pllim pointed out the cause of this problem was that the RTD build for 4.2.1 failed due to an upstream dependency, so we had to do a quick-and-dirty fix just to get the docs to build, which screwed up the bersion number. In #11734 we're just hacking the version number to be what it should be for RTD.

**Comment by pllim** [comment] 2021-05-12 16:19
Fixe in #11734

**Closed by pllim** 2021-05-12 16:19 UTC
Labels: Docs, Release

**Comment by astrojuanlu** [comment] 2021-05-12 16:53
Just for the record, #11734 is a "temporary hack", and the SunPy folks https://github.com/sunpy/sunpy/issues/5225 also solved it by hardcoding the version. There is no issue upstream about this on the RTD side, only a support conversation by @nabobalis -- mentioning this in case anyone wants to open such issue. In any case, I will look into this when we clear some internal deadlines.

**Comment by pllim** [comment] 2021-05-12 16:59
I can't speak for SunPy, but over here, having to fix RTD post-release is pretty rare and personally, I am okay with temporary hack as needed for this case and don't think there is upstream fix necessary.
