### ISSUE TITLE
Can't install astropy automatically as a dependency

### ISSUE THREAD

**Issue by josePhoenix** [astropy/astropy#3541] opened 2015-02-23 20:30 UTC
Since Astropy 1.0 was released, I've been seeing problems installing [POPPY](https://github.com/mperrin/poppy) and [WebbPSF](https://github.com/mperrin/webbpsf) with pip. (It's possible this was true with the preceding Astropy release as well. The last time I went through this process of installing "from scratch" was Fall 2014.) They both refer to Astropy through `setup_requires` and `install_requires` in their `setup.py`, and the error seems to implicate astropy in both cases. (It could be something to do with the helpers/package template too, but I don't know enough to say.)

The relevant error: `distutils.errors.DistutilsError: Setup script exited with error: [Errno 2] No such file or directory: 'poppy/_compiler.c'` (or likewise with s/poppy/webbpsf/)

## Output from `pip install poppy`

```
(test032)15:22:26 kitsune:~ jlong$ pip install poppy
Downloading/unpacking poppy
  Downloading poppy-0.3.4.tar.gz (1.8MB): 1.8MB downloaded
  Running setup.py (path:/Users/jlong/.virtualenvs/test032/build/poppy/setup.py) egg_info for package poppy
    Searching for astropy
    Reading https://pypi.python.org/simple/astropy/
    Reading http://astropy.org
    Best match: astropy 1.0
    Downloading https://pypi.python.org/packages/source/a/astropy/astropy-1.0.tar.gz#md5=1f15b51eb7cbad3345a34770c87ef906
    Processing astropy-1.0.tar.gz
    Writing /var/folders/2t/m92rpkyn2ps064ffwv0qxrbm0001dr/T/easy_install-Y6iJZH/astropy-1.0/setup.cfg
    Running astropy-1.0/setup.py -q bdist_egg --dist-dir /var/folders/2t/m92rpkyn2ps064ffwv0qxrbm0001dr/T/easy_install-Y6iJZH/astropy-1.0/egg-dist-tmp-dbr7m7
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/Users/jlong/.virtualenvs/test032/build/poppy/setup.py", line 122, in <module>
        **package_info
      File "/Users/jlong/homebrew/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/dist.py", line 260, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/dist.py", line 285, in fetch_build_eggs
        replace_conflicting=True
      File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/pkg_resources.py", line 631, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/pkg_resources.py", line 871, in best_match
        return self.obtain(req, installer)
      File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/pkg_resources.py", line 883, in obtain
        return installer(requirement)
      File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/dist.py", line 335, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 595, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 625, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 822, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1028, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1016, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: [Errno 2] No such file or directory: 'poppy/_compiler.c'
    Complete output from command python setup.py egg_info:
    Searching for astropy

Reading https://pypi.python.org/simple/astropy/

Reading http://astropy.org

Best match: astropy 1.0

Downloading https://pypi.python.org/packages/source/a/astropy/astropy-1.0.tar.gz#md5=1f15b51eb7cbad3345a34770c87ef906

Processing astropy-1.0.tar.gz

Writing /var/folders/2t/m92rpkyn2ps064ffwv0qxrbm0001dr/T/easy_install-Y6iJZH/astropy-1.0/setup.cfg

Running astropy-1.0/setup.py -q bdist_egg --dist-dir /var/folders/2t/m92rpkyn2ps064ffwv0qxrbm0001dr/T/easy_install-Y6iJZH/astropy-1.0/egg-dist-tmp-dbr7m7

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Users/jlong/.virtualenvs/test032/build/poppy/setup.py", line 122, in <module>

    **package_info

  File "/Users/jlong/homebrew/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/dist.py", line 260, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/dist.py", line 285, in fetch_build_eggs

    replace_conflicting=True

  File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/pkg_resources.py", line 631, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/pkg_resources.py", line 871, in best_match

    return self.obtain(req, installer)

  File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/pkg_resources.py", line 883, in obtain

    return installer(requirement)

  File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/dist.py", line 335, in fetch_build_egg

    return cmd.easy_install(req)

  File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 595, in easy_install

    return self.install_item(spec, dist.location, tmpdir, deps)

  File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 625, in install_item

    dists = self.install_eggs(spec, download, tmpdir)

  File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 822, in install_eggs

    return self.build_and_install(setup_script, setup_base)

  File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1028, in build_and_install

    self.run_setup(setup_script, setup_base, args)

  File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1016, in run_setup

    raise DistutilsError("Setup script exited with %s" % (v.args[0],))

distutils.errors.DistutilsError: Setup script exited with error: [Errno 2] No such file or directory: 'poppy/_compiler.c'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /Users/jlong/.virtualenvs/test032/build/poppy
Storing debug log for failure in /Users/jlong/.pip/pip.log
```

## Output from `pip install webbpsf`

```
(test032)15:22:48 kitsune:~ jlong$ pip install webbpsf
Downloading/unpacking webbpsf
  Downloading webbpsf-0.3.2.tar.gz (15.6MB): 15.6MB downloaded
  Running setup.py (path:/Users/jlong/.virtualenvs/test032/build/webbpsf/setup.py) egg_info for package webbpsf
    Searching for astropy
    Reading https://pypi.python.org/simple/astropy/
    Reading http://astropy.org
    Best match: astropy 1.0
    Downloading https://pypi.python.org/packages/source/a/astropy/astropy-1.0.tar.gz#md5=1f15b51eb7cbad3345a34770c87ef906
    Processing astropy-1.0.tar.gz
    Writing /var/folders/2t/m92rpkyn2ps064ffwv0qxrbm0001dr/T/easy_install-3rxciS/astropy-1.0/setup.cfg
    Running astropy-1.0/setup.py -q bdist_egg --dist-dir /var/folders/2t/m92rpkyn2ps064ffwv0qxrbm0001dr/T/easy_install-3rxciS/astropy-1.0/egg-dist-tmp-FL8U7K
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/Users/jlong/.virtualenvs/test032/build/webbpsf/setup.py", line 122, in <module>
        **package_info
      File "/Users/jlong/homebrew/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/dist.py", line 260, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/dist.py", line 285, in fetch_build_eggs
        replace_conflicting=True
      File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/pkg_resources.py", line 631, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/pkg_resources.py", line 871, in best_match
        return self.obtain(req, installer)
      File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/pkg_resources.py", line 883, in obtain
        return installer(requirement)
      File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/dist.py", line 335, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 595, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 625, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 822, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1028, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1016, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: [Errno 2] No such file or directory: 'webbpsf/_compiler.c'
    Complete output from command python setup.py egg_info:
    Searching for astropy

Reading https://pypi.python.org/simple/astropy/

Reading http://astropy.org

Best match: astropy 1.0

Downloading https://pypi.python.org/packages/source/a/astropy/astropy-1.0.tar.gz#md5=1f15b51eb7cbad3345a34770c87ef906

Processing astropy-1.0.tar.gz

Writing /var/folders/2t/m92rpkyn2ps064ffwv0qxrbm0001dr/T/easy_install-3rxciS/astropy-1.0/setup.cfg

Running astropy-1.0/setup.py -q bdist_egg --dist-dir /var/folders/2t/m92rpkyn2ps064ffwv0qxrbm0001dr/T/easy_install-3rxciS/astropy-1.0/egg-dist-tmp-FL8U7K

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Users/jlong/.virtualenvs/test032/build/webbpsf/setup.py", line 122, in <module>

    **package_info

  File "/Users/jlong/homebrew/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/dist.py", line 260, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/dist.py", line 285, in fetch_build_eggs

    replace_conflicting=True

  File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/pkg_resources.py", line 631, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/pkg_resources.py", line 871, in best_match

    return self.obtain(req, installer)

  File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/pkg_resources.py", line 883, in obtain

    return installer(requirement)

  File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/dist.py", line 335, in fetch_build_egg

    return cmd.easy_install(req)

  File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 595, in easy_install

    return self.install_item(spec, dist.location, tmpdir, deps)

  File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 625, in install_item

    dists = self.install_eggs(spec, download, tmpdir)

  File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 822, in install_eggs

    return self.build_and_install(setup_script, setup_base)

  File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1028, in build_and_install

    self.run_setup(setup_script, setup_base, args)

  File "/Users/jlong/.virtualenvs/test032/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1016, in run_setup

    raise DistutilsError("Setup script exited with %s" % (v.args[0],))

distutils.errors.DistutilsError: Setup script exited with error: [Errno 2] No such file or directory: 'webbpsf/_compiler.c'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /Users/jlong/.virtualenvs/test032/build/webbpsf
Storing debug log for failure in /Users/jlong/.pip/pip.log
```

**Comment by embray** [comment] 2015-02-23 22:59
Hmm, this is really a thing with astropy-helpers so I'll open a corresponding issue there.  Do poppy and/or webbpsf use astropy-helpers?  Otherwise this shouldn't happen (not that it should at all, but it especially shouldn't happen in those cases).

**Comment by embray** [comment] 2015-02-23 23:06
What happens if astropy is already installed first?

**Comment by embray** [comment] 2015-02-23 23:24
Also do you have astropy-helpers *installed* in your environment?  If so, make sure to uninstall it first, what ever else you do.

**Comment by embray** [comment] 2015-02-23 23:28
If I *install* the latest astropy-helpers, then install poppy into an environment that doesn't have astropy, then I get
```
distutils.errors.DistutilsError: Setup script exited with error: package directory 'poppy' does not exist
```
which is slightly different, but similar problem.  Obviously this shouldn't happen.  It doesn't seem to be an issue at all if I uninstall astropy-helpers first.

**Comment by embray** [comment] 2015-02-23 23:30
Oh that's weird.  Actually I uninstalled astropy-helpers and then I got the same exception you reported.  But there weren't any issues at all *before* I installed astropy-helpers.  And yet after installing and and subsequently uninstalling it it started this...

**Comment by embray** [comment] 2015-02-23 23:33
I'm also getting
```
    WARNING: The autogenerated wrappers in astropy._erfa seem to be older than the source templates used to create them. Because this is a release version we will use them anyway, but this might be a sign of some sort of version mismatch or other tampering. Or it might just mean you moved some files around or otherwise accidentally changed timestamps.
```
this is unrelated but a bit odd.  It might be that when the source file are unpacked it isn't preserving the timestamps, and unpacking them in such an order.  I think that warning should just be squelched entirely.

**Comment by josePhoenix** [comment] 2015-02-23 23:34
Starting from a fresh Python 2.7 virtualenv, I install numpy with `pip install numpy` (to avoid https://github.com/numpy/numpy/issues/2434). Then I do `pip install poppy` to get the error described.

Not much installed:

```
$ pip freeze
numpy==1.9.1
wsgiref==0.1.2
```

I made sure to cd to my home directory before trying to install.. since where I was running it before (~/dev/webbpsf) had astropy_helpers in that folder (and might have been imported at some point in the build process). Didn't seem to make a difference.

**Comment by embray** [comment] 2015-02-23 23:40
What if astropy is manually installed first too?

**Comment by josePhoenix** [comment] 2015-02-23 23:40
that works

**Comment by embray** [comment] 2015-02-23 23:44
I think this might have something to do with the new astropy-helpers command hooks interfering with the build of other packages even if they don't use astropy-helpers.  Or maybe even something more generally when multiple packages are using astropy-helpers during the same install session and from within the same process.  There may be some globals that don't get reset.

**Comment by embray** [comment] 2015-02-23 23:48
I think I can reproduce this now, but it's weird that it was working for a bit.

**Comment by embray** [comment] 2015-02-24 00:27
I think I know what's probably happening here, in particular.  I don't think it has anything specifically to do with the command-hooks, at least.

It seems that poppy has astropy listed in setup_requires, which is fine.  And it's also using astropy_helpers, albeit a previous version.  Depending on the exact order in which things happen, if the astropy_helpers shipped with poppy first gets loaded that gets used first.  However, when the install of poppy then tries to get astropy, astropy's install runs (via easy_install, since pip doesn't properly handle ordering for setup_requires yet), and when it runs it sees that astropy_helpers is already available on the path, rather then use the newer version of astropy_helpers shipped with astropy it goes on using the old one used by poppy.

Furthermore, the old one already has some global variables set in it that are associated with poppy, resulting in further havoc (though it might break later for other reasons as well).  

I think I can make a workaround to this and make a patch release of astropy-helpers that will address it without requiring any changes in any other packages affected by this issue, since the astropy-helpers auto-upgrade is working fine in this case.  It needs to allow for multiple different versions of astropy-helpers to be swapped in and out when installing multiple packages within the same Python session.  I think that the sandboxing already provided by `setuptools.sandbox.run_setup` should make this doable without too much hassle.

**Comment by josePhoenix** [comment] 2015-02-24 00:30
Wow, that's pretty arcane. I'm glad you figured it out! We'll have to update astropy_helpers for POPPY and WebbPSF in our next point releases. Can you comment here or send me an email when that feature lands?

**Comment by embray** [comment] 2015-02-24 00:33
Yeah it would be worth updating anyways.  I believe there was a package-template update that coincided with the astropy 1.0 release.  But in principle it shouldn't be necessary to switch to it (otherwise we of course would have given people more time!)  In the meantime the simplest workaround is to install astropy first.

When the patch to astropy-helpers lands it should *just work*.

**Comment by josePhoenix** [comment] 2015-02-24 00:34
Is there a low-traffic announcement list for astropy helpers and package template changes? It seems like I just updated those recently, but evidently not recently enough.

**Comment by embray** [comment] 2015-02-24 15:55
@josePhoenix That sounds like a good idea.  My preference would be to have an all encompassing list that includes updates to affiliated packages and Astropy itself.  But what do you think?  Either way I think there should definitely be a better channel for that.

**Comment by josePhoenix** [comment] 2015-02-24 16:47
That would be fine too. If there were an announce-only list that's ≤1 email/week of things of interest to affiliated package maintainers, I'd read it. (Minor wrinkle: ST's new mail filtering system means we can't participate in Google Groups under our work emails. Bah.)

**Comment by embray** [comment] 2015-02-24 23:06
Didn't quite get a chance to fix this today.

**Comment by embray** [comment] 2015-02-26 20:10
@josePhoenix I think under the present circumstances there is a chicken/egg problem that makes it almost impossible to fix this entirely, at least not without egregious monkeying around.  Would it be possible to just put out patch releases for webbpsf and poppy that include an upgraded astropy-helpers?  

With the changes I have been able to make this won't be a problem in the future. But in the meantime it's really hard since it needs a package to be able to replace itself with a newer version of the package. Except only the newer version of the package knows how to actually do that :/

Alternatively (or additionally) I can make a patch release of Astropy that is able to handle this.

**Comment by embray** [comment] 2015-02-26 20:11
I guess the immediate course of action depends on what's higher priority.

**Comment by josePhoenix** [comment] 2015-02-26 21:27
Ideally, Astropy helpers would function in such a way that it doesn't have to make any assumptions about what other packages are doing. We can certainly put out a bugfix release of POPPY and WebbPSF (cc @cslocum, but this probably doesn't affect the stable Ureka release timeline?). It sounds like a bugfix release of Astropy is in order as well?

**Comment by embray** [comment] 2015-02-26 21:38
That would be fine except when two different packages are depending on two different versions of astropy-helpers that need to be used simultaneously in the same Python process because the installer for one of those packages is trying to also bootstrap the other package :)  This is a problem far beyond just astropy-helpers.

**Comment by embray** [comment] 2015-02-27 17:24
To clarify, also, if I release a new patch release of Astropy the issue will be essentially resolved, as neither WebbPSF or POPPY seem to be pinning their `setup_requires` to any particular version of Astropy, if I release a new one with the fix then that's the version they'll grab except under very unusual conditions that wouldn't affect an "average" user anyways.

**Comment by embray** [comment] 2015-02-27 20:47
Didn't really intend to close this, since it won't really be fixed until the new releases are made.

**Comment by embray** [comment] 2015-03-06 23:55
Confirmed that this is now fixed with the just released [Astropy v1.0.1](https://pypi.python.org/pypi/astropy/1.0.1).  @josePhoenix, could you confirm that it works for you?

**Comment by embray** [comment] 2015-03-06 23:57
(I do seem to be having some problems running `pip install webbpsf` is Numpy also isn't installed first, but at that state I don't think it has anything to do with astropy).

**Comment by josePhoenix** [comment] 2015-03-07 21:22
If I pre-install NumPy, the issue is fixed with no additional changes in POPPY. We'll put out patch releases to POPPY and WebbPSF requiring `astropy>=1.0.1`.

As far as the second issue, being unable to pre-install NumPy, it does indeed seem to be something to do with astropy. If I remove all the setup-related `astropy_helpers` code from POPPY, it successfully installs both numpy and astropy without any additional monkeying around. See https://github.com/josephoenix/poppy/tree/remove_helpers for that version.

That is, at least, a separate issue. I could open an issue on the package template or helpers, whichever you think is more appropriate.

**Comment by embray** [comment] 2015-03-09 14:32
Perhaps, though I can't think of any reason it would interfere with Numpy installation.  Numpy does some pretty wild stuff in its setup too though.

**Closed** 2015-03-09 14:46 UTC
Labels: astropy-helpers, Bug

**Comment by embray** [comment] 2015-03-09 15:56
I've traced the problems with Numpy to this: https://github.com/numpy/numpy/blob/master/numpy/distutils/core.py#L92

There's several levels of wrong with this, not all of which are Numpy's fault.  A lot of it goes to the heart of the badness of distutils.  Should be interesting to see if I can come up with a workaround...

**Comment by embray** [comment] 2015-03-09 17:54
See [here](https://github.com/numpy/numpy/issues/2434#issuecomment-77898051) for an explanation I left on how/why this is affecting Numpy.  I believe this may actually be fixed if using the latest version of setuptools, but I need to confirm this...

**Comment by embray** [comment] 2015-03-09 17:59
Confirmed--the issue with Numpy should be worked around if you have setuptools >= 10.0 (although in practice >= 11.0 since astropy_helpers is broken with setuptools 10.x, as reported in #3576).
