### ISSUE TITLE
Improve frame comparison

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#3182] opened 2014-12-07 10:36 UTC
At the moment, one cannot compare whether frames are equivalent:

```
In [1]: from astropy.coordinates import FK5

In [2]: FK5(equinox='J2000') == FK5(equinox='J2010')
Out[2]: False

In [3]: FK5(equinox='J2000') == FK5(equinox='J2000')
Out[3]: False
```

It would be nice to have a way to check that all frame attributes are the same. Now `==` may be ambiguous because for frames with data this is not as well defined (are we comparing the frame attributes or the data? what if the data is a vector?).

Maybe the solution is to disable straight-off comparisons like the ones above but to instead have a method or function to check if two frames are the same (excluding data)?

cc @eteq @taldcroft

**Comment by adrn** [comment] 2017-09-19 19:49
As @taldcroft mentioned, I think this is a duplicate of #2154, but I think the discussion here is more relevant now, so I'm going to close the other issue. I'm working on this now. It turns out we don't have a way to compare representations, so I need to start there...

**Comment by taldcroft** [comment] 2017-09-21 21:45
Looking at this again, maybe we also want a `coordinates.allclose` function with sensible defaults?  Then equality is strict equality but there is a way to allow `allclose` matching of the data (again require strict equality of frame attributes).  Also `allclose` might make the `representation` of left and right be the same while `==` would not.

:+1: on implementing frame comparison since it is a pre-requisite for a conservative implementation of coordinate setitem.  :smile:  In other words, first thing you do for setting is make sure the left and right side frames are exactly the same, then setting the data from right will be fine (need to clear any caches of course, etc).

**Comment by taldcroft** [comment] 2017-12-21 11:44
I ran into this problem (or a slight variant) again today:
```
In [10]: sc = SkyCoord([1,2], [3,4], unit='deg')
In [11]: sc2 = SkyCoord([1,2], [3,4], unit='deg')
In [12]: sc == sc2
Out[12]: False
```
This really should return a bool array of `True` since the objects are the same down to the bit level.
What about this:
```
In [32]: def equal(sc1, sc2):
    ...:     if not sc1.is_equivalent_frame(sc2):
    ...:         return False
    ...:     if sc1.representation is not sc2.representation:  # Will be representation_type..
    ...:         return False
    ...:     if sc1.shape != sc2.shape:
    ...:         return False  # Maybe raise ValueError corresponding to future numpy behavior
    ...:     eq = np.ones(shape=sc1.shape, dtype=bool)
    ...:     for comp in sc.data.components:
    ...:         eq &= getattr(sc.data, comp) == getattr(sc2.data, comp)
    ...:     return eq
```

**Comment by taldcroft** [comment] 2018-02-07 14:26
In #6888 , I implemented the code from the previous comment as a new function `skycoord_equal` that is used for testing.  Any interest in bringing something like this into coordinates proper?

I have no idea if this works for coordinates with velocities. I do think that a strict equality comparison is a useful and well-defined thing for coordinates, basically the objects are the same at the bit level.  This is different from an `isclose` kind of comparison.   

@eteq @mhvk @adrn

**Comment by mhvk** [comment] 2018-02-07 19:58
I'm in favour of testing for equality checking - as you say, it is well-defined. I do think we need to think a bit about what to return if frames or representations do not match. Here, python and numpy seem to be diverging, sadly (though also understandably), with python never allowing `==` to fail. In particular, if, e.g., the shapes can be broadcast but frames and/or representation types do not match, should one return an array of False, or just False, or raise an error?

**Comment by Juanlu001** [comment] 2018-09-03 09:41
Notice that `is_equivalent_frame` is not always correct, see https://github.com/astropy/astropy/issues/7793.

**Comment by Juanlu001** [comment] 2019-02-10 18:30
To update my previous comment, this still stands but #7793 was fixed.

**Comment by taldcroft** [comment] 2019-10-25 18:19
I (AGAIN) ran into this problem (or a slight variant) 

 ```
In [10]: sc = SkyCoord([1,2], [3,4], unit='deg')
In [11]: sc2 = SkyCoord([1,2], [3,4], unit='deg')
In [12]: sc == sc2
Out[12]: False
```
This really should return a **bool array** of `True` since the objects are the same down to the bit level, not a scalar Python `False`.

Would there be any interest (for 4.0) in issuing a FutureWarning that SkyCoord (or Frame) `__eq__` will be fixed to respect the `shape` of the object?  This idea has been tossed about for at least 5 years now, and the problem of testing for equality at the bit level is not insurmountable (I think??).

**Closed** 2020-05-02 13:35 UTC
Labels: Feature Request, coordinates
