### ISSUE TITLE
TDISPn keywords do not roundtrip to/from Astropy Table object

### ISSUE THREAD

**Issue by SaOgaz** [astropy/astropy#7165] opened 2018-02-06 22:51 UTC
Maybe related to #6806, although I don't even see a warning about it getting put into column attributes, so I'm guessing that isn't happening here. I don't think my file has any of those keywords in the extension header and I'm not touching the primary header.

TDISPn keywords are the only ones getting thrown out.

I'm using `Table.read()` and `fits.table_to_hdu()` to do the round-tripping.

**Comment by saimn** [comment] 2018-02-06 23:45
When creating a column with `io.fits` (`fits.Column(..., disp='.1f')`) TDISP is correctly used. The issue is with the Table to BinTableHDU conversion (`table_to_hdu`) which does not transfer the Table `.format` to the FITS Column. So I think the issue is exactly #6806, unless I miss something ?

**Comment by SaraOgaz** [comment] 2018-02-08 16:50
I actually linked to a different issue then I meant to, heh.

For my test file, the it looks like the TDISP keywords are not getting moved into the table at all.  It should be in the `format` attribute right?

**Comment by SaraOgaz** [comment] 2018-02-08 18:31
Not sure if I tracked this down to the right place, but in master it looks like TDISP is still on the ignore list for a Table.read()

https://github.com/astropy/astropy/blob/master/astropy/io/fits/connect.py#L261
https://github.com/astropy/astropy/blob/master/astropy/io/fits/connect.py#L33

**Comment by saimn** [comment] 2018-02-08 22:09
TDISP is not in the REMOVE_KEYWORDS list so I think it just go in the `.meta` dictionary. So yes, the conversion must be done in both directions, in `read_table_fits` and in `table_to_hdu`.

**Comment by SaraOgaz** [comment] 2018-02-08 23:03
What's the time scale for getting this fixed?  I'm trying to give some of my co-workers a time estimate on when they can do some other work that's waiting on this, so I was curious.

**Comment by taldcroft** [comment] 2018-02-09 12:12
Just a caution in this and #6806 that one needs to be careful about the `TDISP` keyword since according to the FITS standard that can only accept a narrowly-defined set of values:
![image](https://user-images.githubusercontent.com/348089/36026882-f31ade06-0d66-11e8-9476-523783d408ed.png)
I note in the original example from @SaraOgaz that the value of `disp='.1f'` would result in a non-compliant FITS file.

So if supporting `TDISP` through `io.fits` is "official", I assume there needs to be validation of the input.  This is part of the trick related to Table column `.format` attribute, which can take a wide variety of forms.  Thus #6192 chooses to store column `format` exactly using the meta serialization machinery (in `COMMENT` cards) and completely ignore `TDISP`.  That is the only way to ensure perfect round-trip of an arbitrary Table with arbitrary `format` values.

But as I mentioned this is certainly taking an end-run around the available `TDISP` keyword, which can capture a subset of desired formats.  However, something as simple as `.1f` (one digit but no specification of overall length) would appear to be impossible since the standard says it needs to be `Fw.d`, with no option for dropping the `w`.  Maybe I'm reading it wrong...

**Comment by SaraOgaz** [comment] 2018-02-09 18:58
Sorry @taldcroft, I'm not sure which example your referring to? I don't remember ever posting that...

**Comment by SaraOgaz** [comment] 2018-02-09 18:58
Here are some solid example values from the file I'm working with:
DISP3  = 'L4      '           / display format                                 
TDISP4  = 'A21     '           / display format                                 
TDISP5  = 'A21     '           / display format                                 
TDISP6  = 'A8      '           / display format                                 
TDISP7  = 'L4      '           / display format                                 
TDISP8  = 'L4      '           / display format                                 
TDISP9  = 'A12     '           / display format                                 
TDISP10 = 'E20.12  '           / display format                                 
TDISP11 = 'E20.12  '           / display format

**Comment by taldcroft** [comment] 2018-02-09 18:59
@SaraOgaz - sorry, I meant the one from @saimn above.  Your examples are fine, but don't work (directly) for the table column `format`.

**Comment by saimn** [comment] 2018-02-09 22:35
Yeah sorry, I realized later that FITS has its own format, which makes the conversion more complicated. I had a quick look and didn't find a way in Python's stdlib to parse a format string. 
And as you can see with my example, `io.fits` does not verify what is put in TDISP .

**Comment by mhvk** [comment] 2018-02-12 08:29
The fits formats just use the FORTRAN specification. It should not be difficult to convert from them, but, as @taldcroft noted, one cannot have a generic mechanism for converting to them. Still, roundtripping from fits files would be nice.

**Comment by eteq** [comment] 2018-02-12 23:06
I was looking at this and realized I'm confused about the thread here... The actual issue as posted is that the round-tripping doesn't work, right?  Are we all agreed that it *should*, or is @taldcroft  saying it shouldn't for files that are technically non-compliant? 

I'm inclined to say that if something is used a lot "in the wild", it should round-trip (although I don't know whether this is "a lot" or not...), even if it nominally isn't up to spec.  That's been the solution *everywhere* in `votable`, for example...

**Comment by pllim** [comment] 2018-04-24 18:36
I have having problem where I wrote a FITS table using `Table.write()` but failed to read it back in with `Table.read(fits.getdata(...))`. Is this the same issue or should I open a new one? I found this while trying to investigate #7399.

**Comment by saimn** [comment] 2018-05-15 08:00
Fixed by #7226.

**Closed by saimn** 2018-05-15 08:00 UTC
Labels: io.fits
