### ISSUE TITLE
CIRS is not at the ultimate accuracy

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#10356] opened 2020-05-15 23:15 UTC
Copying @mkbrewer's https://github.com/astropy/astropy/issues/10230#issuecomment-629491534:

>It is unfortunate that you only implement geocentric position for your CIRS frame. You use apci() and apio() rather than the more rigorous apco() which builds the observer's topocentric position and velocity (if present) right in. This has two side effects. In going from ICRS to CIRS light deflection doesn't take into account a topocentric observer's position and velocity and in going from CIRS to AltAz the less rigorous simple first-order vector expression for diurnal aberration as mentioned in paragraph 4.7 of the SOFA Astrometry Tools document is used.

It sounds like we could improve things fairly simply since GCRS seems OK:

> On the other hand, your GCRS frame does implement topocentric position rigorously. Therefore, I find it curious that you don't derive your CIRS frame from GCRS. After all, with GCRS you are just one step of applying the CIO based BPN matrix from true topocentric CIRS intermediate (apparent) place. The call to apcs() in this transform properly sets up the ASTROM data structure for rigorously calculating gravitational light deflection, diurnal aberration and diurnal parallax including the observer's position and velocity (including taking the observer's velocity into account in beta - 1). I particularly like the way that diurnal aberration is naturally included in Ab() this way, so that the transformation from topocentric CIRS to AltAz can be done without resorting to the use of astrom->diurab.

**Comment by mkbrewer** [comment] 2020-08-23 22:05
Now that GCRS is pretty much all set, it's time to address the other elephant in the room which are the GCRS to CIRS and CIRS to observed transforms. The problem here is that instead of following the `atco` chain, you chose to use `atci` and `atio` instead. What SOFA fails to mention, is that the later is completely incompatible with solar system bodies where diurnal parallax comes into play (although, if you look closely, the documentation for `atci13()` does say that it is specifically for star data) This is especially true of the Moon, so that is what I've concentrated on here. There, I can't help but notice a rather large (to my standards) error in the returned Alt/Az coordinates. Here is the error between your Alt/Az and mine in the latest data file that I have from you. 
![AzElError](https://user-images.githubusercontent.com/10635444/90988111-3cebe300-e55e-11ea-8bf7-1e9388aa757f.png)
This is in coordinate space and on this date, the Moon reaches lower meridian transit at 13:05 UT. At that time the elevation is -80.5 degrees, so I also plotted the actual offset on the sky which looks better, but is still pretty bad.
![OnSkyAzElError](https://user-images.githubusercontent.com/10635444/90988186-0fec0000-e55f-11ea-928e-3ee1701b090d.png)
I was able to reproduce this exactly (to 20 uas) by altering my program to follow the steps that you use.

1. Transform the topocentric GCRS coordinates back to BCRS..
2.  Drop the EarthLocation and transform to geocentric GCRS.
3. Apply the BPN matrix to transform to geocentric CIRS.
4. Add the EarthLocation back in to transform to topocentric CIRS.
5. Use `apio()` to set up the CIRS to observed transform.
6. Call `atioq()` to transform to Alt/Az.

It turns out that the root of the problem is in the transform to geocentric GCRS. Specifically the geocentric aberration. When observing the Moon, there is a contribution to diurnal aberration from the diurnal parallax. This comes in to the aberration calculated by `ab()` due to the diurnal offsets in the topocentric direction vector from the observer to the Moon. I was able to confirm this by altering the steps that you use. In the transformation to geocentric GCRS, I retained the topocentric BCRS unit vectors, but called `apcg()` instead of `apco()` to tell SOFA that I was using geocentric positions even though I wasn't. This eliminated the velocity based component of the diurnal aberration but retained the position based component. Then comparing the resulting CIRS Ra/Dec to that obtained by using the full topocentric GCRS transform yielded a nice velocity based diurnal aberration. Very sinusoidal with the Declination component dropping to zero at upper and lower meridian transit.
![MKBRADecError](https://user-images.githubusercontent.com/10635444/90989033-82f87500-e565-11ea-8319-61524a74d49d.png)
Then I used `apio()` as before to set up the velocity based diurnal aberration during the transformation to Alt/Az. The resulting Alt/Az positions were in agreement with my normal data (full topocentric transform using `apco()`) to within 15 uas.
On the other hand, the CIRS RA/Dec offsets obtained from following your procedure exactly weren't nearly as pretty.
![AstropyRADecError](https://user-images.githubusercontent.com/10635444/90989316-3d3cac00-e567-11ea-8d33-96690da0526c.png)
There is a phase shift and an offset in the Declination sinusoid due to the missing position based diurnal aberration.

Clearly, the way to solve this problem is to merely apply the BPN matrix directly to yield topocentric CIRS coordinates without any folderol of transforming the GCRS coordinates to geocentric first. Then you can still use `apio13()`, if you'd like, to set up the Alt/Az transformation, but you must be sure to set `astrom['diurab']` to zero before calling `atioq()`. Since this is rather inefficient, it would better to make a modified version of `apio()` dropping the call to `pvtob()` and setting `astrom['diurab']` to zero directly.

**Comment by mkbrewer** [comment] 2020-08-24 12:34
Note that you can also apply the BPN to the `gcrs_frame.obsgeoloc` attribute to get the appropriate `icrs_frame.obsgeoloc` attribute to apply to topocentrc CIRS (topocentric intermediate place). Yes, I know that, as currently implemented, CIRS doesn't have an `obsgeoloc`attribute, but it should. Also note that the true equator true equinox (TETE) frame that I requested can also be realized in the same manner by merely applying the equinox based BPN to either geocentric GCRS (proper place) or topocentric GCRS (local place) to derive geocentric TETE (apparent place) or topocentric TETE (topocentric apparent place)

**Comment by maxnoe** [comment] 2020-10-15 14:54
@mkbrewer could you maybe summarize what the proposed solution is for the CIRS transform graph?

So which changes are required to CIRS (I see the addition of an obsgeoloc?) and which erfa functions should be used in the transform graph?

**Comment by StuartLittlefair** [comment] 2020-10-15 15:15
@maxnoe - it may be worth holding your trigger on this for a few days. I'm about to push an implementation of apparent place coordinates (TETE) which, when finished would make a reasonable starting point for how to implement CIRS with obsgeoloc/vel. 

Most of the methods I use could be ported to the corrections in CIRS quite simply, but the ICRS<->CIRS transforms will need fixing, or indeed removing, since in principle one can rely on ICRS->GCRS->CIRS without the direct transformation.

**Comment by mkbrewer** [comment] 2020-10-15 20:04
I second what @StuartLittlefair has said here. The only difference between CIRS and TETE is the BPN matrix that is used. If topocentric intermediate place inherits its observer location from the GCRS frame, then the observer's geodetic longitude and latitude can easily be extracted for use in conversion to AltAz or HADec.

**Comment by mkbrewer** [comment] 2020-10-15 20:38
But to answer your question, the idea here would be to start with a GCRS frame (either geocentric or topocentric), then call `get_cip()` and `c2ixys()` to build the CIO based BPN matrix for transformation to CIRS.

**Comment by mkbrewer** [comment] 2020-10-15 21:08
On the other hand, just like TETE, one can envision an AltAz or HADec frame with it's unique time and observer location as is currently done. But then the CIRS location would need to be converted to GCRS in order to do the transformation back to ICRS/BCRS to get the source position at the given time and then pass back through GCRS to finally arrive at CIRS  ready for conversion to AltAz or HADec. .

**Comment by mkbrewer** [comment] 2020-10-15 21:48
Seems the long way around. Of course, `apco()` will do that for you. It would only be necessary to extract the GCRS position of the observer that `apco()` constructs to derive the ICRS/BCRS position of the source, then use the resulting `astrom` data structure for conversion to observed coordinates. See `apco13()` for an example of how to do this.

**Comment by StuartLittlefair** [comment] 2020-10-16 18:58
I'm getting somewhere with this now. I've added a topocentric position to CIRS (in GCRS coordinates for consistency with other frames). I think I have the ICRS<->CIRS and GCRS<->CIRS figure out. Just have to try and fix CIRS<->AltAz following @mkbrewer's suggestions

**Comment by StuartLittlefair** [comment] 2020-10-17 11:11
Well, partial success; I have managed to reduce the discrepancies by following the two routes @mkbrewer suggested - either using ```apio13``` and setting ```astrom['diurab']=0```, **or** using ```apco``` to get the ```astrom``` context. However, the discrepancies still show some residual structure for @mkbrewer's moon test case.

![moon_azel](https://user-images.githubusercontent.com/4570807/96335526-2a2eef80-1071-11eb-9694-abc0ddd87e77.png)

Note: I get identical results using the direct ICRS->AltAz transform sketched out in #10887

For some reason I am unable to get a good comparison with Horizons, or SkyField's output. One thing that makes this difficult is that I am not sure I have an up-to-date file of the output from @mkbrewer's script. I'm pretty sure the version I have is out-of-date. Do you think you could share this here? 

I'd like the correct Az and El for the Moon on Apr 6 2017 from an observatory at 22.959748 deg S, 67.787260 deg W and 5186m...

**Comment by mkbrewer** [comment] 2020-10-17 15:47
What version of the output data that I gave you are you using here? If it's `moon_topo_4_6_2017_mkb_v5_ap_polar_motion.csv`, then I'd like to see the Ra/Dec comparison also. Perhaps the best thing to do is for you to post your output so that I can look into the apparent discrepancy.

**Comment by StuartLittlefair** [comment] 2020-10-17 17:17
It’s a lot older than that - the file name is just `moon_topo_4_6_2017_mkb.csv`. If I have a copy of the latest data then I know if the things I am doing are working.

**Comment by mkbrewer** [comment] 2020-10-17 18:01
Here you go. 

![AstropyAzAltFixed](https://user-images.githubusercontent.com/10635444/96349955-f52a9900-1080-11eb-9095-2822c699e83a.png)
[moon_topo_4_6_2017_mkb_ap_v5_10356.txt](https://github.com/astropy/astropy/files/5396220/moon_topo_4_6_2017_mkb_ap_v5_10356.txt)

**Comment by mkbrewer** [comment] 2020-10-17 18:06
I'm pretty convinced that those oscillations are coming from `jpleph`. I see them in both astropy and Skyfield, but not in JPL Horizons. If you want to compare your output to Skyfield, you should set polar motion to zero. As that is what Skyfield uses by default.

**Comment by StuartLittlefair** [comment] 2020-10-17 18:52
Well that looks splendid! Now I only have to work out why this build is failing almost everywhere in our tests... <sigh>

**Comment by mkbrewer** [comment] 2020-10-17 23:01
Oh, I forgot that I was setting the TIO locator to zero rather than calling `sp00()`. At this level, it actually makes a small difference. Here is the revised file.

![AstropyAzAltFixed](https://user-images.githubusercontent.com/10635444/96355003-215b0f80-10ab-11eb-9002-1f2e03a96f1c.png)
[moon_topo_4_6_2017_mkb_ap_v5_10356.txt](https://github.com/astropy/astropy/files/5396831/moon_topo_4_6_2017_mkb_ap_v5_10356.txt)

**Comment by StuartLittlefair** [comment] 2020-10-23 11:45
@mkbrewer perhaps you can help me get to the bottom of the issue that's stopping me from pushing my CIRS fix. As you know, we used to do the CIRS-AltAz transform by calculating geocentric CIRS, adding the EarthLocation back to get topocentric CIRS and then running the CIRS->AltAz transform.

In my branch I use ```erfa.apcs``` to handle transformations into and out of topocentric CIRS directly, but setting the ```astrom[bpn]``` matrix to the celestial-intermediate-matrix. So far so good.

We have a number of tests in astropy where we construct ITRS coordinates just above the Earth's surface and convert to Alt/Az. An example is below:

```python
t = Time('J2010')
obj = EarthLocation(-1*u.deg, 52*u.deg, height=100*u.km)
home = EarthLocation(-1*u.deg, 52*u.deg, height=0*u.km)
aa = obj.get_itrs(t).transform_to(AltAz(obstime=t, location=home))
```

These tests expect altitudes very close to 90 degrees to result. The current master gives ```alt=89.99994516 deg```.

In my branch the altitudes are quite different - e.g the example above gives ```alt=89.63242684 deg```.

The difference is purely in the CIRS position that is fed into the Alt/Az transform - my method gives a value which is 0.3 degrees away from the old method. 

What I can't wrap my head around is why there should be such a large difference - I'm thinking that perhaps it's a numerical accuracy issue caused by the new approach round-tripping through ICRS to get a topocentric CIRS. I'm not missing some genuine reason for the difference am I?

**Comment by mkbrewer** [comment] 2020-10-23 17:05
@StuartLittlefair Since you are observing an object directly overhead, of course the result should be Alt 90, Az 0. There are a few of aspects to this. First the object's location in the ITRS needs to be transformed to CIRS. This involves adding in polar motion and the earth rotation angle as is handled nicely by `intermediate_rotation_transforms.itrs_to_cirs()`. Second, the observer's location `home` must be transformed into the GCRS. As far as I can see, this involves calling `intermediate_rotation_transforms.itrs_to_cirs()` followed by `intermediate_rotation_transforms.cirs_to_girs()`. Unfortunately, I have never been able to confirm that this is what is being done when `EarthLocation.get_gcrs_posvel()` is called. Once these two steps have been taken, you should have a proper CIRS frame with the object's position in the CIRS and the observer's location `obsgeoloc` in the GCRS. Now it's just a matter of transforming `obsgeoloc` back into the CIRS, subtracting this from the object's position in the CIRS to obtain the topocentric intermediate position of the object. Then you need to set up the `astrom` context which involves a call to `erfa.apio()` with the following two steps: 
```
/* Observer's geocentric position and velocity (m, m/s, CIRS). */
   iauPvtob(elong, phi, hm, xp, yp, sp, theta, pv);

/* Magnitude of diurnal aberration vector. */
   astrom->diurab = sqrt(pv[1][0]*pv[1][0]+pv[1][1]*pv[1][1]) / CMPS;
```
replaced by: 
```
   astrom->diurab = 0.0;
```
(Please pardon me for using SOFA code there.) Once this is done, a call to `erfa.atioq()` will back out the local earth rotation angle and polar motion yielding the proper ITRS declination and hour angle to transform to AltAz. 
Please note that all of this assumes an airless model. If refraction is included, then it would need to be backed out before the initial transformation of the object's position in the ITRS to CIRS.

**Comment by mkbrewer** [comment] 2020-10-23 17:25
> Note that you can also apply the BPN to the gcrs_frame.obsgeoloc attribute to get the appropriate cirs_frame.obsgeoloc attribute to apply to topocentrc CIRS (topocentric intermediate place). 

https://github.com/astropy/astropy/issues/10356#issuecomment-679099350. The reason that I suggested using the observer's CIRS location in the CIRS frame rather than the GCRS `obsgeoloc` is that it avoids the necessity of recomputing the GCRS->CIRS BPN matrix as you already have that available during the transform from GCRS to CIRS.

**Comment by mkbrewer** [comment] 2020-10-23 17:35
In the above case, this BPN matrix is actually computed twice. Once in `EarthLocation.get_gcrs_posvel()` to get the observer's `obsgeoloc` in the GCRS and a second time to convert this to the observer's location in the CIRS. This could be obviated by simply creating a function `EarthLocation.get_cirs_pos()`.

**Comment by StuartLittlefair** [comment] 2020-11-04 18:16
OK - so having now convinced myself that astropy is doing the right thing when converting geocentric CIRS to topocentric CIRS I am almost ready to add some tests to my branch and submit a PR. I have one outstanding question for @mkbrewer. I find excellent agreement with your data (`moon_topo_4_6_2017_mkb_ap_v5_10356.txt`), but poor agreement (up to 1" out) with JPL Horizons and Skyfield.

![astropy_vs_jpl_polarmotion](https://user-images.githubusercontent.com/4570807/98152044-02d97e80-1ec9-11eb-88a4-0d635ea5ff39.png)

![astropy_vs_skyfield_polarmotion](https://user-images.githubusercontent.com/4570807/98152059-07059c00-1ec9-11eb-9aea-475666ecd2d7.png)

The agreement gets much better if I turn polar motion off:

![astropy_vs_jpl_nopolarmotion](https://user-images.githubusercontent.com/4570807/98152018-f9e8ad00-1ec8-11eb-996e-41ad5de0d318.png)
![astropy_vs_skyfield_nopolarmotion](https://user-images.githubusercontent.com/4570807/98152051-04a34200-1ec9-11eb-87b5-9dc50ee678f4.png)

Although interestingly there I recover the patterns that I saw compared to an older output from your code (`moon_topo_4_6_2017_mkb_ap.csv`).

Comparing HORIZONS to Skyfield reveals a similar pattern so it seems almost everyone disagrees at this level apart from us!

![horizons_vs_skyf](https://user-images.githubusercontent.com/4570807/98152522-c78b7f80-1ec9-11eb-8017-b79b09b2c45b.png)

I am surprised that HORIZONS seems to ignore polar motion by default, but my question is whether you understand the pattern that remains after I turn polar motion off?

**Comment by mkbrewer** [comment] 2020-11-05 01:41
@StuartLittlefair Sorry to be long in responding. I didn't notice these posts for awhile and then I had issues with my installation of Skyfield that turned out to be due it to no longer being able to download EOP data from the USNO. After upgrading to the latest version, it's working again. If I disable polar motion in my program and Skyfield, I get very good agreement. 

![az_el_mkb_skyfield_no_polar](https://user-images.githubusercontent.com/10635444/98186957-e85dd000-1edd-11eb-89f6-b90e48ab2cc4.png)

Here is the script that I used:

[skyfield_topo_test.py.txt](https://github.com/astropy/astropy/files/5491395/skyfield_topo_test.py.txt)

**Comment by mkbrewer** [comment] 2020-11-05 01:51
Regarding JPL Horizons, that's a whole can of worms there. I have never been able to get good agreement in AltAz with them. They do use polar motion, but the EOPs that they use are significantly different than the IERS published data. You can request the EOPs that they use if you wish. I did that once and I still couldn't get good agreement. This led me to compare my output to Skyfield, but unfortunately, there are rather significant issues that Skyfield has with polar motion. I've been trying to to get Brandon Rhodes to address this since May, so far to little avail. In fact, he recently downgraded the issue I opened to a feature request rather than a bug, so i have no idea when he's going to get around to addressing it.

**Comment by StuartLittlefair** [comment] 2020-11-05 08:57
Thanks @mkbrewer - don't worry about the time it takes you to reply. I'm asleep whilst you are working! Upgrading Skyfield to the latest version made a big difference for me, but I'm not quite as close as you still. 

The output I have from your code is `moon_topo_4_6_2017_mkb_ap_v5_10356.csv`. Is the only difference between the output you compare to Skyfield and the output I have polar motion? In which case I probably haven't disabled it properly in astropy...

![astropy_vs_skyfield_nopolarmotion](https://user-images.githubusercontent.com/4570807/98219325-c21f4b00-1f44-11eb-8e83-46bac8209f2a.png)

Nevertheless we are looking good to go here - I just need to write some tests. This is why I was trying to compare to HORIZONS - it would be good to have an independent third party!

**Comment by mkbrewer** [comment] 2020-11-05 12:18
Yes, I simply set xp and yp to zero when I call `apco()`. 

btw, upgrading Skyfield made a difference for me also. I am no longer seeing the oscillations that were previously present. This is most easily seen in the residual for the distance to the Moon.
![moon_dist_v_1 10](https://user-images.githubusercontent.com/10635444/98239841-98f7be00-1f36-11eb-95af-1dd1fb74ed7b.png)
![moon_dist_v_1 31](https://user-images.githubusercontent.com/10635444/98239856-9e550880-1f36-11eb-9bab-993b3adbf258.png)

**Comment by mkbrewer** [comment] 2020-11-05 19:37
I am curious if you still see that level of discrepancy if you use the code in #10887. There it would be quite easy to disable polar motion by simply setting xp and yp to zero.

**Comment by StuartLittlefair** [comment] 2020-11-05 20:07
No, using that code I get the same as Skyfield to better than 0.6 mas.

**Comment by mkbrewer** [comment] 2020-11-05 21:29
OK. I don't know how you are disabling polar motion in the standard transform. Is there any possibility that you are disabling it in some place, but not others? One that comes to mind is `get_gcrs_posvel()`.

**Comment by StuartLittlefair** [comment] 2020-11-05 21:31
That was my thought as well. I’m not too concerned about chasing it up because I don’t think we’d be interested in turning it on/off.

**Comment by mkbrewer** [comment] 2020-11-05 22:01
Well, If I can ever get Brandon Rhodes to fix polar motion in Skyfield, this won't be an issue anyway. On that, once this is finished, it will be quite helpful as he can compare his results to yours without having to rely on data that I give him.

**Comment by mkbrewer** [comment] 2020-11-14 22:21
@StuartLittlefair I am pleased to announce that polar motion is now fixed in Skyfield. Here are the new residual plots between my program and Skyfield.

![ra_dec_both_polar](https://user-images.githubusercontent.com/10635444/99158106-5011d900-269d-11eb-869d-582eabf4c351.png)
![az_el_both_polar](https://user-images.githubusercontent.com/10635444/99158107-543df680-269d-11eb-8ec4-03ac160f8f8e.png)
This fix should be available at the next release of Skyfield.

**Comment by mhvk** [comment] 2020-11-15 02:03
@mkbrewer - nice! And super that you now have helped to get this right in two packages!

**Closed** 2020-11-19 18:12 UTC
Labels: coordinates, precision
