### ISSUE TITLE
astropy.coordinates.Distance does not work with parallax values in a table Column with units

### ISSUE THREAD

**Issue by pmaxted** [astropy/astropy#15693] opened 2023-12-07 22:20 UTC
### Description

Running astropy.coordinates.Distance on a column of a Table with units provided in the column metadata produces a `AttributeError: 'Column' object has no attribute 'to_value'` error message.

### Expected behavior

Expected behaviour is to return the distance in parsecs corresponding to the parallaxes, as happens if the same data are provided as an astropy.units.quantity.Quantity array.

### How to Reproduce

```python
from astropy.coordinates import Distance
from astropy.table import Table
import astropy.units as u
t = Table(names=['Plx'],units=[u.mas])
t.add_row([1])
t.add_row([2])
t.add_row([3])
Distance(parallax=t['Plx'])

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/var/folders/dl/tc85r2_j2v94kqhby3hvz4n00000gn/T/ipykernel_49653/1669335759.py in <module>
      7 t.add_row([3])
      8 
----> 9 Distance(parallax=t['Plx'])

~/miniconda3/lib/python3.9/site-packages/astropy/coordinates/distances.py in __new__(cls, value, unit, z, cosmology, distmod, parallax, dtype, copy, order, subok, ndmin, allow_negative)
    165             if unit is None:
    166                 unit = u.pc
--> 167             value = parallax.to_value(unit, equivalencies=u.parallax())
    168 
    169             if np.any(parallax < 0):

AttributeError: 'Column' object has no attribute 'to_value'
```

### Versions

astropy 5.3.4

**Comment by neutrinoceros** [comment] 2023-12-08 08:53
@pmaxted To explore the topic of `Table` w/ units VS `QTable`, see https://docs.astropy.org/en/stable/table/mixin_columns.html#quantity-and-qtable

**Comment by taldcroft** [comment] 2023-12-08 10:43
Indeed I think that even the existing `Quantity`-like behavior of `Column` should be deprecated and eventually removed. Basically I would say that only the `quantity` property should remain, meaning remove `.to()` and remove the partial Quantity-like parlor tricks like supporting arithmetic with a `Quantity`.

The example at the end of https://docs.astropy.org/en/stable/table/access_table.html#columns-with-units is particularly troublesome because some things work as expected and some do not. Here is the warning text in our docs:
```
.. warning::

  |Table| columns do *not* always behave the same as |Quantity|. |Table|
  columns act more like regular ``numpy`` arrays unless either explicitly
  converted to a |Quantity| or combined with a |Quantity| using an arithmetic
  operator. For example, the following does not work in the way you would
  expect::

    >>> data = [[30, 90]]
    >>> t = Table(data, names=('angle',))
    >>> t['angle'].unit = 'deg'
    >>> np.sin(t['angle'])  # doctest: +FLOAT_CMP
    <Column name='angle' dtype='float64' unit='deg' length=2>
    -0.988031624093
     0.893996663601

  This is wrong both in that it says the result is in degrees, *and*
  `~numpy.sin` treated the values as radians rather than degrees. If at all in
  doubt that you will get the right result, the safest choice is to either use
  |QTable| or to explicitly convert to |Quantity|::

    >>> np.sin(t['angle'].quantity)  # doctest: +FLOAT_CMP
    <Quantity [0.5, 1. ]>
```

**Comment by mhvk** [comment] 2023-12-08 14:47
I'm fine with making `Column` more different.

But it still seems a bit of a bug to me that a Quantity subclass (Distance) does not correctly recognize a Column with an obvious unit, given that Quantity itself recognizes Column fine.

**Comment by taldcroft** [comment] 2023-12-08 15:41
I agree that `Distance` should work with a `Column` with units, though that would also warrant updating the [API docs](https://docs.astropy.org/en/stable/api/astropy.coordinates.Distance.html#astropy.coordinates.Distance) accordingly.

This points to a need for a `QuantityLike` type as anything that can be coerced to a `Quantity` (ala [ArrayLike](https://numpy.org/devdocs/reference/typing.html#numpy.typing.ArrayLike)).

I admit sometimes being unclear on whether `QuantityLike` should mean that the object implements the `Quantity` protocol and behaves fully like `Quantity`. In this case (similar to `ArrayLike`), it means that `Column` is `QuantityLike` but does not implement the `Quantity` protocol.

**Comment by eerovaher** [comment] 2023-12-08 21:27
`astropy` already defines `quantity-like`, but the current definition does not include `Column` :
https://github.com/astropy/astropy/blob/faa20e537265eb750dcccd18dd2283b01cad2f4f/docs/glossary.rst?plain=1#L27-L33

**Comment by mhvk** [comment] 2023-12-08 23:29
Yes, it is a bit vague, but `Quantity` itself just checks whether something has a unit and acts accordingly, so `Distance` might as well do the same.  I'll need to remind myself of the implementation to see if that's easy...

**Comment by taldcroft** [comment] 2023-12-09 10:45
It looks like the original issue here can be fixed with the usual pattern of coercing the `quantity-like` input to `Quantity`:
```
diff --git a/astropy/coordinates/distances.py b/astropy/coordinates/distances.py
index d53f5f504b..34bcf32cab 100644
--- a/astropy/coordinates/distances.py
+++ b/astropy/coordinates/distances.py
@@ -162,6 +162,7 @@ class Distance(u.SpecificTypeQuantity):
                     unit = u.pc
 
         elif parallax is not None:
+            parallax = u.Quantity(parallax, copy=False)
             if unit is None:
                 unit = u.pc
             value = parallax.to_value(unit, equivalencies=u.parallax())
```
With that the original example produces:
```
 <Distance [1000.        ,  500.        ,  333.33333333] pc>
```
Just to play around I confirmed that `Quantity` is doing the expected thing with:
```
In [2]: class FloatMeters(float):
   ...:     unit = u.m

In [3]: fm = FloatMeters(2.5)

In [4]: u.Quantity(fm)
Out[4]: <Quantity 2.5 m>
```

**Closed** 2023-12-12 17:39 UTC
Labels: table, Bug
