### ISSUE TITLE
Improving error handling in _kraft_burrows_nousek

### ISSUE THREAD

**Issue by bharathr98** [astropy/astropy#13448] opened 2022-07-12 20:17 UTC
### Description

While I was going through the code to play around with the issue #13334, I noticed this raise call https://github.com/astropy/astropy/blob/19cc80471739bcb67b7e8099246b391c355023ee/astropy/stats/funcs.py#L1287-L1297

Although the documentation mentions that SciPy cannot be used for N>100, the error raised does not reflect that. 

Consider the following example. I am a user with only SciPy on my system. I call 
```
poisson_conf_interval(n=int(101), background=3.8, confidence_level=0.95, interval='kraft-burrows-nousek')
```
 Since this is above the N=100 threshold, it skips the `HAS_SCIPY` if statement, and it also skips `HAS_MPMATH` if statement since I do not have mpmath. It then raises an `ImportError('Either scipy or mpmath are required.')` which is super confusing since I have SciPy available. A more reasonable way to deal with this would be to have a separate if statement inside the `HAS_SCIPY` block that raises a `ValueError` when N>100.

**Comment by pllim** [comment] 2022-11-02 15:26
I think this is duplicate of #13334 ?

**Closed by pllim** 2022-11-02 15:26 UTC
Labels: Feature Request, stats
