### ISSUE TITLE
Maybe test SAMP and other networking code with mock sockets?

### ISSUE THREAD

**Issue by embray** [astropy/astropy#2126] opened 2014-02-24 19:02 UTC
A lot of the "random" test failures on Travis of late are mostly, I think, due to interactions with OS sockets over which we don't have full control, and which can lead to unpredictable behavior.

I wonder if it wouldn't be better to just mock the entire socket module for these purposes, using a lightweight Python replacement for sockets without touching real OS level sockets.  For the most part I don't think we require any advanced socket features so this should be reasonably straightforward.

There is one project already called "mocket" which provides this: https://github.com/mocketize/python-mocket, though it doesn't seem to have had much active development in the last year.  It still looks okay though.  There's also a mock_socket.py hanging out in Python itself: http://hg.python.org/cpython/file/718cddfa0292/Lib/test/mock_socket.py

This is not a normally installed module, but it could just be copied verbatim with the proper attribution.  Or, depending on what we determine our actual needs to be, it may be straightforward enough to roll our own.

This isn't something I'd want to put a lot of effort into if it winds up being troublesome. But I think it could really improve the reliability of our tests without implicitly also testing sockets, which really doesn't help us in general.

**Comment by astrofrog** [comment] 2017-06-15 14:17
I'm going to go ahead and close this - even though this could potentially be nice in a general sense, the only failures that occurred were related to the HTTPS/SSL tests, and SSL support has been removed in https://github.com/astropy/astropy/pull/6201. We can always re-open in future if we run into similar issues, but for now the problem is solved.

**Closed by astrofrog** 2017-06-15 14:17 UTC
Labels: Priority-Low, testing, vo.samp
