### ISSUE TITLE
Clarify documentation on how io.fits uses "structural" keywords

### ISSUE THREAD

**Issue by embray** [astropy/astropy#3836] opened 2015-06-10 17:25 UTC
An unfortunate design quirk of FITS is that FITS keywords mix up both metadata, and critical information on how a given FITS file is structured needed to parse the file--in particular keywords that describe the format of the data in an HDU (NAXIS, GCOUNT, TFIELDS, etc.)

An FAQ I get is "I wanted to add another row to my table so I set `header['NAXIS2'] += 1`" or something to that effect.  For better or worse this is _not_ how PyFITS/`astropy.io.fits` works.  The header keywords are used, when reading a file, to determine how the data is formatted _in_ the file.  Once the data is loaded it is no longer tied to any of the header keywords.

At the other end, when writing an HDU, the values that go into those _structural_ keywords are determined entirely by the data array that is attached to the HDU (as well as the HDU type).  Any hand-written values users might assign to those keywords will be overwrittten.  In other words, the structural keywords are a serialization detail that users should almost never manipulate manually except in some rare corner cases.

This point is made in various places throughout the PyFITS docs.  But I think it's important enough to understanding how this library works that it deserves a section right in the introduction explaining this (in more or less the terms I just laid out above).  This is also an actual frequently asked question, so there should be a reference in the FAQ (perhaps just linking back to the docs in the introduction).

**Comment by embray** [comment] 2019-03-06 12:45
This still keeps coming up with users, e.g. in StackOverflow questions. PyFITS really deserves better documentation on how to use it in practical terms.

**Comment by eigenbrot** [comment] 2019-06-03 16:41
This ticket was recently referenced in Slack. The example was:
```
>>> hd = fits.open('MY_DATA.fits')[0]
>>> hd.data.shape
(1, 2048, 2048)
>>> hd.header['NAXIS']
3
# Seems OK so far!
>>> ph = fits.PrimaryHDU()
>>> ph.header['NAXIS']
0
# Yep, that makes sense too
>>> ph.header = hd.header
>>> ph.header['NAXIS']
0
# OK, this seems legit; that required keyword was changed because ph really has no data
>>> hd.header['NAXIS']
0
# WHAAAA?
```
This is technically expected behavior because "assigning to `.header` is not making a copy, meaning that internally `ph` and `hd` use the same header" (@saimn). That said, it certainly surprised me and could probably benefit from explicate documentation.

I'm happy to take this on or help in any way I can.

**Closed** 2020-03-19 20:12 UTC
Labels: Docs, Effort-low, Package-expert, io.fits
