### ISSUE TITLE
DOC: Skycoord example creates big files

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#8792] opened 2019-06-04 12:44 UTC
While looking at the docs build time #7080, I noticed one big file (56Mb) generated by the Skycoord examples:
```
❯ ls -lh coordinates/skycoord-2* plot_directive/coordinates/skycoord-2.*
-rw-r--r-- 1 simon users 5,2M 24 mai   22:59 coordinates/skycoord-2.pdf
-rw-r--r-- 1 simon users  55K 24 mai   22:59 coordinates/skycoord-2.png
-rw-r--r-- 1 simon users 1,6K 24 mai   22:59 coordinates/skycoord-2.py
-rw-r--r-- 1 simon users  56M 24 mai   22:59 coordinates/skycoord-2.svg
-rw-r--r-- 1 simon users 5,2M 24 mai   22:59 plot_directive/coordinates/skycoord-2.pdf
-rw-r--r-- 1 simon users  55K 24 mai   22:57 plot_directive/coordinates/skycoord-2.png
-rw-r--r-- 1 simon users  56M 24 mai   22:58 plot_directive/coordinates/skycoord-2.svg
```
http://docs.astropy.org/en/latest/coordinates/skycoord.html#example-2-plotting-star-positions-in-bulge-and-disk
Which creates this:
![](http://docs.astropy.org/en/latest/_images/skycoord-2.png)

Not sure if this example is really useful ?

**Comment by mhvk** [comment] 2019-06-04 13:42
Wow...

**Comment by adrn** [comment] 2019-06-04 14:58
And that's a terrible example! I think I wrote it...so I'll take responsibility to fix it 😬

**Comment by adrn** [comment] 2019-06-04 15:19
The source of the big file here is actually a change in behavior within matplotlib. Something must have changed around mpl v3.0, because this does not do what I expect it to do - `plot()` with a projection seems to be interpolating points between the plotted points?

With mpl v3.1.0:
```python
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 4))
plt.subplot(111, projection="aitoff")

x = [0, np.pi/4, np.pi/2]
y = [0, np.pi/4, 3*np.pi/8]

plt.scatter(x, y, color='tab:orange')

plt.plot(x, y,
         marker='o', linestyle='none', markersize=2, alpha=0.3)
```
![image](https://user-images.githubusercontent.com/583379/58891445-867eb280-86ba-11e9-89d4-6ea85f792e7c.png)

**Comment by saimn** [comment] 2019-06-04 15:24
Indeed, looking at the old (v1.0) docs the result was different: https://docs.astropy.org/en/older-docs-archive/v1.0/coordinates/skycoord.html
v2.0 already shows the issue (https://docs.astropy.org/en/v2.0.12/coordinates/skycoord.html), so this is not new, maybe something related to the change of default style in matplotlib 2.0 ?

**Comment by pllim** [comment] 2019-06-04 15:50
Looks like the example was written back in #3111 by @hamogu .

**Comment by hamogu** [comment] 2019-06-04 15:55
In addition to making sure that we plot points, not lines, we can probably also reduce the number of stars by a factor of 10.

**Comment by adrn** [comment] 2019-06-04 17:00
It is already supposed to be plotting points, and it isn't many points - there seems to be a change in matplotlib that has changed the behavior. See my minimal example above!

**Comment by pllim** [comment] 2019-06-04 19:39
@adrn , have you reported this upstream to `matplotlib`?

**Comment by bsipocz** [comment] 2019-06-04 22:05
I'm looking into it and it seems to be a regression in mpl between v2.2.3 and v2.2.4. I don't yet have the solution, if something I can fix will open a PR upstream, or in worst case a bug report.

**Comment by bsipocz** [comment] 2019-06-04 23:37
https://github.com/matplotlib/matplotlib/pull/11407 is to blame, and I do have a fix, let's hope it doesn't break something unintended.

**Comment by bsipocz** [comment] 2019-06-08 20:54
Upstream fix has been merged and will be out in the next mpl bugfix release, thus I close this issue now.

**Closed by bsipocz** 2019-06-08 20:54 UTC
Labels: Bug, Docs, Upstream Fix Required, coordinates
