### ISSUE TITLE
astropy 1.0.4, failed test astropy.io.fits.tests.test_connect in ppc64

### ISSUE THREAD

**Issue by sergiopasra** [astropy/astropy#4185] opened 2015-09-23 22:08 UTC
The Fedora package build of astropy 1.0.4 fails in architecture ppc64  (64-bit big-endian PowerPC and Power Architecture). ppc64le (little endian mode) is fine. The faillures are as follows:

```
____________________ TestSingleTable.test_read_from_fileobj
____________________
self = <astropy.io.fits.tests.test_connect.TestSingleTable object at
0x3fffa9fdf210>
tmpdir = local('/tmp/pytest-0/test_read_from_fileobj0')
    def test_read_from_fileobj(self, tmpdir):
        filename = str(tmpdir.join('test_read_from_fileobj.fits'))
        hdu = BinTableHDU(self.data)
        hdu.writeto(filename)
        with open(filename, 'rb') as f:
            t = Table.read(f)
>       assert equal_data(t, self.data)
E       assert equal_data(<Table masked=False length=4>\n  a      b        c
\nint64 string32 float64\n--...�a     2.3\n    2     ���b     4.5\n    3
���c     6.7\n    4     ���d     8.9, array([(1, u'a', 2.3), (2, u'b', 4.5),
(3, u'c', 6.7), (4, u'd', 8.9)], \n      dtype=[('a', '>i8'), ('b', '>U1'),
('c', '>f8')]))
E        +  where array([(1, u'a', 2.3), (2, u'b', 4.5), (3, u'c', 6.7), (4,
u'd', 8.9)], \n      dtype=[('a', '>i8'), ('b', '>U1'), ('c', '>f8')]) =
<astropy.io.fits.tests.test_connect.TestSingleTable object at
0x3fffa9fdf210>.data
astropy/io/fits/tests/test_connect.py:130: AssertionError
```

A quick search suggests that this bug is related with #1849

This is the bug in the Fedora tracker, with more details

https://bugzilla.redhat.com/show_bug.cgi?id=1264912

**Comment by embray** [comment] 2015-09-28 15:04
Thanks for the report.  I'm going to mark this as a duplicate of #1849, but I'll leave it open until resolved (if nothing else since it's more specific than #1849).

**Comment by astrofrog** [comment] 2016-02-12 10:38
@sergiopasra - are you still seeing this issue? I tried running the tests on ppc (not ppc64) and didn't see any failures in test_connect.py: https://github.com/astrofrog/astropy/blob/c71116cb65e0672c8debb9017b26b144d89afd19/powerpc_latest_numpy.log

**Comment by sergiopasra** [comment] 2016-02-15 13:00
@astrofrog It seems to work with astropy 1.1.1

http://ppc.koji.fedoraproject.org/koji/taskinfo?taskID=3061160

**Closed** 2017-01-26 17:56 UTC
Labels: Affects-release, Bug, Duplicate, io.fits, platform-ppc, testing
