### ISSUE TITLE
IERS error when converting to altaz

### ISSUE THREAD

**Issue by elliesch** [astropy/astropy#6910] opened 2017-11-29 16:49 UTC
When writing this code with Python 3.6 and Astropy v2.0.2:
```
from astropy import coordinates as coord
import astropy.units as u
from astropy import time

vega = coord.SkyCoord.from_name('Vega')

loc = coord.EarthLocation(lon=0.1 * u.deg,
                          lat=51.5 * u.deg)

obstime = time.Time(57734.1231, format='mjd')

altaz = coord.AltAz(location=loc, obstime=obstime)

vega_altaz = vega.transform_to(altaz)
```

I get this error:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/Users/elliannaschwab/anaconda/lib/python3.6/site-packages/astropy/io/ascii/core.py in _convert_vals(self, cols)
    956                 try:
--> 957                     converter_func, converter_type = col.converters[0]
    958                     if not issubclass(converter_type, col.type):

IndexError: list index out of range

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-23-5540b2e880c6> in <module>()
     10 altaz = coord.AltAz(location=loc, obstime=time)
     11 
---> 12 vega_altaz = vega.transform_to(altaz)
     13 vega_altaz.alt

/Users/elliannaschwab/anaconda/lib/python3.6/site-packages/astropy/coordinates/sky_coordinate.py in transform_to(self, frame, merge_attributes)
    479         # Do the transformation, returning a coordinate frame of the desired
    480         # final type (not generic).
--> 481         new_coord = trans(self.frame, generic_frame)
    482 
    483         # Finally make the new SkyCoord object from the `new_coord` and

/Users/elliannaschwab/anaconda/lib/python3.6/site-packages/astropy/coordinates/transformations.py in __call__(self, fromcoord, toframe)
   1312 
   1313             curr_toframe = t.tosys(**frattrs)
-> 1314             curr_coord = t(curr_coord, curr_toframe)
   1315 
   1316         # this is safe even in the case where self.transforms is empty, because

/Users/elliannaschwab/anaconda/lib/python3.6/site-packages/astropy/coordinates/transformations.py in __call__(self, fromcoord, toframe)
    912             return reprwithoutdiff.realize_frame(reprwithdiff)
    913         else:
--> 914             return supcall(fromcoord, toframe)
    915 
    916 

/Users/elliannaschwab/anaconda/lib/python3.6/site-packages/astropy/coordinates/builtin_frames/cirs_observed_transforms.py in cirs_to_altaz(cirs_coo, altaz_frame)
     51 
     52     lon, lat, height = altaz_frame.location.to_geodetic('WGS84')
---> 53     xp, yp = get_polar_motion(obstime)
     54 
     55     # first set up the astrometry context for CIRS<->AltAz

/Users/elliannaschwab/anaconda/lib/python3.6/site-packages/astropy/coordinates/builtin_frames/utils.py in get_polar_motion(time)
     41     """
     42     # Get the polar motion from the IERS table
---> 43     xp, yp, status = iers.IERS_Auto.open().pm_xy(time, return_status=True)
     44 
     45     wmsg = None

/Users/elliannaschwab/anaconda/lib/python3.6/site-packages/astropy/utils/iers/iers.py in open(cls)
    586             return cls.iers_table
    587 
--> 588         cls.iers_table = cls.read(file=filename)
    589         cls.iers_table.meta['data_url'] = str(conf.iers_auto_url)
    590 

/Users/elliannaschwab/anaconda/lib/python3.6/site-packages/astropy/utils/iers/iers.py in read(cls, file, readme)
    455         # Read in as a regular Table, including possible masked columns.
    456         # Columns will be filled and converted to Quantity in cls.__init__.
--> 457         iers_a = Table.read(file, format='cds', readme=readme)
    458 
    459         # Combine the A and B data for UT1-UTC and PM columns

/Users/elliannaschwab/anaconda/lib/python3.6/site-packages/astropy/table/table.py in read(cls, *args, **kwargs)
   2519         passed through to the underlying data reader (e.g. `~astropy.io.ascii.read`).
   2520         """
-> 2521         out = io_registry.read(cls, *args, **kwargs)
   2522         # For some readers (e.g., ascii.ecsv), the returned `out` class is not
   2523         # guaranteed to be the same as the desired output `cls`.  If so,

/Users/elliannaschwab/anaconda/lib/python3.6/site-packages/astropy/io/registry.py in read(cls, *args, **kwargs)
    529 
    530         reader = get_reader(format, cls)
--> 531         data = reader(*args, **kwargs)
    532 
    533         if not isinstance(data, cls):

/Users/elliannaschwab/anaconda/lib/python3.6/site-packages/astropy/io/ascii/connect.py in io_read(format, filename, **kwargs)
     37     from .ui import read
     38     format = re.sub(r'^ascii\.', '', format)
---> 39     return read(filename, format=format, **kwargs)
     40 
     41 

/Users/elliannaschwab/anaconda/lib/python3.6/site-packages/astropy/io/ascii/ui.py in read(table, guess, **kwargs)
    351                                              ' with fast (no guessing)'})
    352         else:
--> 353             dat = reader.read(table)
    354             _read_trace.append({'kwargs': new_kwargs,
    355                                 'status': 'Success with specified Reader class '

/Users/elliannaschwab/anaconda/lib/python3.6/site-packages/astropy/io/ascii/cds.py in read(self, table)
    320                     return table
    321         else:
--> 322             return super(Cds, self).read(table)

/Users/elliannaschwab/anaconda/lib/python3.6/site-packages/astropy/io/ascii/core.py in read(self, table)
   1200         if hasattr(self.header, 'table_meta'):
   1201             self.meta['table'].update(self.header.table_meta)
-> 1202         table = self.outputter(cols, self.meta)
   1203         self.cols = self.header.cols
   1204 

/Users/elliannaschwab/anaconda/lib/python3.6/site-packages/astropy/io/ascii/core.py in __call__(self, cols, meta)
    986         # Sets col.data to numpy array and col.type to io.ascii Type class (e.g.
    987         # FloatType) for each col.
--> 988         self._convert_vals(cols)
    989 
    990         # If there are any values that were filled and tagged with a mask bit then this

/Users/elliannaschwab/anaconda/lib/python3.6/site-packages/astropy/io/ascii/core.py in _convert_vals(self, cols)
    971                     last_err = err
    972                 except IndexError:
--> 973                     raise ValueError('Column {} failed to convert: {}'.format(col.name, last_err))
    974 
    975 

ValueError: Column year failed to convert: invalid literal for int() with base 10: '<h'


```

**Comment by ktc312** [comment] 2017-11-29 16:50
Same issue here

**Comment by alecxe** [comment] 2017-11-29 17:23
Not sure, I've turned on VPN and I am able to see the table url page data in the browser, but still getting the 

> ValueError: Column year failed to convert: invalid literal for int() with base 10: '<h'

error. Thanks.

**Comment by bsipocz** [comment] 2017-11-29 17:35
It seems to work fine for me.

**Comment by alecxe** [comment] 2017-11-29 20:14
Ah, @adrn, just debugged a bit what is happening - you are right, the "'http://maia.usno.navy.mil/ser7/finals2000A.all'" contains HTML content which results into `self.lines` [here](https://github.com/astropy/astropy/blob/4783f43892471110272e9caee759612a00d98786/astropy/io/ascii/core.py#L1146)  to obtain this kind of a weird value: `['<html>', '<head>', '<title>Web Page Blocked</title>', ..., '</body>', '</html>', '\x00']` which fails afterwards.

Disregard my previous point about the VPN - `astropy` [cached the webpage](https://github.com/astropy/astropy/blob/4749e9bdd18955a43cce7c08c1cfb23ca3e61fef/astropy/utils/iers/iers.py#L639) in the `/Users/<username>/.astropy/cache/...`.

I guess there needs to be some sort of a contents pre-check after the page is downloaded, or HTTP status code check.

Thanks.

**Comment by aburgasser** [comment] 2018-02-06 00:41
any update on this issue? I still have the same error following the example in the documentation:

import astropy.units as u
from astropy.time import Time
from astropy.coordinates import SkyCoord, EarthLocation
keck = EarthLocation.from_geodetic(lat=19.8283*u.deg, lon=-155.4783*u.deg, height=4160*u.m)
sc = SkyCoord(ra=4.88375*u.deg, dec=35.0436389*u.deg)
barycorr = sc.radial_velocity_correction(obstime=Time('2016-6-4'), location=keck)

output:

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-1-45533580c1c5> in <module>()
      4 keck = EarthLocation.from_geodetic(lat=19.8283*u.deg, lon=-155.4783*u.deg, height=4160*u.m)
      5 sc = SkyCoord(ra=4.88375*u.deg, dec=35.0436389*u.deg)
----> 6 barycorr = sc.radial_velocity_correction(obstime=Time('2016-6-4'), location=keck)

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/coordinates/sky_coordinate.py in radial_velocity_correction(self, kind, obstime, location)
   1374                              "'{}'".format(kind))
   1375 
-> 1376         gcrs_p, gcrs_v = location.get_gcrs_posvel(obstime)
   1377         # transforming to GCRS is not the correct thing to do here, since we don't want to
   1378         # include aberration (or light deflection)? Instead, only apply parallax if necessary

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/coordinates/earth.py in get_gcrs_posvel(self, obstime)
    651         """
    652         # GCRS position
--> 653         gcrs_data = self._get_gcrs(obstime).data
    654         obsgeopos = gcrs_data.without_differentials()
    655         obsgeovel = gcrs_data.differentials['s'].to_cartesian()

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/coordinates/earth.py in _get_gcrs(self, obstime)
    631         zeros = broadcast_to(0. * u.km / u.s, (3,) + itrs.shape, subok=True)
    632         itrs.data.differentials['s'] = CartesianDifferential(zeros)
--> 633         return itrs.transform_to(GCRS(obstime=obstime))
    634 
    635     def get_gcrs_posvel(self, obstime):

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/coordinates/baseframe.py in transform_to(self, new_frame)
    932             msg = 'Cannot transform from {0} to {1}'
    933             raise ConvertError(msg.format(self.__class__, new_frame.__class__))
--> 934         return trans(self, new_frame)
    935 
    936     def is_transformable_to(self, new_frame):

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/coordinates/transformations.py in __call__(self, fromcoord, toframe)
   1312 
   1313             curr_toframe = t.tosys(**frattrs)
-> 1314             curr_coord = t(curr_coord, curr_toframe)
   1315 
   1316         # this is safe even in the case where self.transforms is empty, because

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/coordinates/transformations.py in __call__(self, fromcoord, toframe)
    845 
    846             from_diffless = fromcoord.realize_frame(fromcoord.data.without_differentials())
--> 847             reprwithoutdiff = supcall(from_diffless, toframe)
    848 
    849             # first we use the existing differential to compute an offset due to

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/coordinates/builtin_frames/intermediate_rotation_transforms.py in itrs_to_cirs(itrs_coo, cirs_frame)
     87 def itrs_to_cirs(itrs_coo, cirs_frame):
     88     # compute the pmatrix, and then multiply by its transpose
---> 89     pmat = cirs_to_itrs_mat(itrs_coo.obstime)
     90     newrepr = itrs_coo.cartesian.transform(matrix_transpose(pmat))
     91     cirs = CIRS(newrepr, obstime=itrs_coo.obstime)

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/coordinates/builtin_frames/intermediate_rotation_transforms.py in cirs_to_itrs_mat(time)
     31 def cirs_to_itrs_mat(time):
     32     # compute the polar motion p-matrix
---> 33     xp, yp = get_polar_motion(time)
     34     sp = erfa.sp00(*get_jd12(time, 'tt'))
     35     pmmat = erfa.pom00(xp, yp, sp)

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/coordinates/builtin_frames/utils.py in get_polar_motion(time)
     41     """
     42     # Get the polar motion from the IERS table
---> 43     xp, yp, status = iers.IERS_Auto.open().pm_xy(time, return_status=True)
     44 
     45     wmsg = None

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/utils/iers/iers.py in open(cls)
    581             return cls.iers_table
    582 
--> 583         cls.iers_table = cls.read(file=filename)
    584         cls.iers_table.meta['data_url'] = str(conf.iers_auto_url)
    585 

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/utils/iers/iers.py in read(cls, file, readme)
    450         # Read in as a regular Table, including possible masked columns.
    451         # Columns will be filled and converted to Quantity in cls.__init__.
--> 452         iers_a = Table.read(file, format='cds', readme=readme)
    453 
    454         # Combine the A and B data for UT1-UTC and PM columns

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/table/table.py in read(cls, *args, **kwargs)
   2517         passed through to the underlying data reader (e.g. `~astropy.io.ascii.read`).
   2518         """
-> 2519         out = io_registry.read(cls, *args, **kwargs)
   2520         # For some readers (e.g., ascii.ecsv), the returned `out` class is not
   2521         # guaranteed to be the same as the desired output `cls`.  If so,

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/io/registry.py in read(cls, *args, **kwargs)
    529 
    530         reader = get_reader(format, cls)
--> 531         data = reader(*args, **kwargs)
    532 
    533         if not isinstance(data, cls):

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/io/ascii/connect.py in io_read(format, filename, **kwargs)
     37     from .ui import read
     38     format = re.sub(r'^ascii\.', '', format)
---> 39     return read(filename, format=format, **kwargs)
     40 
     41 

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/io/ascii/ui.py in read(table, guess, **kwargs)
    351                                              ' with fast (no guessing)'})
    352         else:
--> 353             dat = reader.read(table)
    354             _read_trace.append({'kwargs': new_kwargs,
    355                                 'status': 'Success with specified Reader class '

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/io/ascii/cds.py in read(self, table)
    320                     return table
    321         else:
--> 322             return super(Cds, self).read(table)

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/io/ascii/core.py in read(self, table)
   1200         if hasattr(self.header, 'table_meta'):
   1201             self.meta['table'].update(self.header.table_meta)
-> 1202         table = self.outputter(cols, self.meta)
   1203         self.cols = self.header.cols
   1204 

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/io/ascii/core.py in __call__(self, cols, meta)
    986         # Sets col.data to numpy array and col.type to io.ascii Type class (e.g.
    987         # FloatType) for each col.
--> 988         self._convert_vals(cols)
    989 
    990         # If there are any values that were filled and tagged with a mask bit then this

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/io/ascii/core.py in _convert_vals(self, cols)
    971                     last_err = err
    972                 except IndexError:
--> 973                     raise ValueError('Column {} failed to convert: {}'.format(col.name, last_err))
    974 
    975 

ValueError: Column year failed to convert: invalid literal for int() with base 10: '<h'

In [2]: import astropy
In [3]: astropy.__version__
Out[3]: '2.0.3'

**Comment by aburgasser** [comment] 2018-02-06 00:53
also, thought I'd be clever and eliminate the poorly formatted cached webpage and now I'm hosed:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-1-45533580c1c5> in <module>()
      4 keck = EarthLocation.from_geodetic(lat=19.8283*u.deg, lon=-155.4783*u.deg, height=4160*u.m)
      5 sc = SkyCoord(ra=4.88375*u.deg, dec=35.0436389*u.deg)
----> 6 barycorr = sc.radial_velocity_correction(obstime=Time('2016-6-4'), location=keck)

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/coordinates/sky_coordinate.py in radial_velocity_correction(self, kind, obstime, location)
   1374                              "'{}'".format(kind))
   1375 
-> 1376         gcrs_p, gcrs_v = location.get_gcrs_posvel(obstime)
   1377         # transforming to GCRS is not the correct thing to do here, since we don't want to
   1378         # include aberration (or light deflection)? Instead, only apply parallax if necessary

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/coordinates/earth.py in get_gcrs_posvel(self, obstime)
    651         """
    652         # GCRS position
--> 653         gcrs_data = self._get_gcrs(obstime).data
    654         obsgeopos = gcrs_data.without_differentials()
    655         obsgeovel = gcrs_data.differentials['s'].to_cartesian()

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/coordinates/earth.py in _get_gcrs(self, obstime)
    631         zeros = broadcast_to(0. * u.km / u.s, (3,) + itrs.shape, subok=True)
    632         itrs.data.differentials['s'] = CartesianDifferential(zeros)
--> 633         return itrs.transform_to(GCRS(obstime=obstime))
    634 
    635     def get_gcrs_posvel(self, obstime):

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/coordinates/baseframe.py in transform_to(self, new_frame)
    932             msg = 'Cannot transform from {0} to {1}'
    933             raise ConvertError(msg.format(self.__class__, new_frame.__class__))
--> 934         return trans(self, new_frame)
    935 
    936     def is_transformable_to(self, new_frame):

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/coordinates/transformations.py in __call__(self, fromcoord, toframe)
   1312 
   1313             curr_toframe = t.tosys(**frattrs)
-> 1314             curr_coord = t(curr_coord, curr_toframe)
   1315 
   1316         # this is safe even in the case where self.transforms is empty, because

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/coordinates/transformations.py in __call__(self, fromcoord, toframe)
    845 
    846             from_diffless = fromcoord.realize_frame(fromcoord.data.without_differentials())
--> 847             reprwithoutdiff = supcall(from_diffless, toframe)
    848 
    849             # first we use the existing differential to compute an offset due to

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/coordinates/builtin_frames/intermediate_rotation_transforms.py in itrs_to_cirs(itrs_coo, cirs_frame)
     87 def itrs_to_cirs(itrs_coo, cirs_frame):
     88     # compute the pmatrix, and then multiply by its transpose
---> 89     pmat = cirs_to_itrs_mat(itrs_coo.obstime)
     90     newrepr = itrs_coo.cartesian.transform(matrix_transpose(pmat))
     91     cirs = CIRS(newrepr, obstime=itrs_coo.obstime)

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/coordinates/builtin_frames/intermediate_rotation_transforms.py in cirs_to_itrs_mat(time)
     31 def cirs_to_itrs_mat(time):
     32     # compute the polar motion p-matrix
---> 33     xp, yp = get_polar_motion(time)
     34     sp = erfa.sp00(*get_jd12(time, 'tt'))
     35     pmmat = erfa.pom00(xp, yp, sp)

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/coordinates/builtin_frames/utils.py in get_polar_motion(time)
     41     """
     42     # Get the polar motion from the IERS table
---> 43     xp, yp, status = iers.IERS_Auto.open().pm_xy(time, return_status=True)
     44 
     45     wmsg = None

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/utils/iers/iers.py in open(cls)
    581             return cls.iers_table
    582 
--> 583         cls.iers_table = cls.read(file=filename)
    584         cls.iers_table.meta['data_url'] = str(conf.iers_auto_url)
    585 

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/utils/iers/iers.py in read(cls, file, readme)
    450         # Read in as a regular Table, including possible masked columns.
    451         # Columns will be filled and converted to Quantity in cls.__init__.
--> 452         iers_a = Table.read(file, format='cds', readme=readme)
    453 
    454         # Combine the A and B data for UT1-UTC and PM columns

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/table/table.py in read(cls, *args, **kwargs)
   2517         passed through to the underlying data reader (e.g. `~astropy.io.ascii.read`).
   2518         """
-> 2519         out = io_registry.read(cls, *args, **kwargs)
   2520         # For some readers (e.g., ascii.ecsv), the returned `out` class is not
   2521         # guaranteed to be the same as the desired output `cls`.  If so,

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/io/registry.py in read(cls, *args, **kwargs)
    529 
    530         reader = get_reader(format, cls)
--> 531         data = reader(*args, **kwargs)
    532 
    533         if not isinstance(data, cls):

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/io/ascii/connect.py in io_read(format, filename, **kwargs)
     37     from .ui import read
     38     format = re.sub(r'^ascii\.', '', format)
---> 39     return read(filename, format=format, **kwargs)
     40 
     41 

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/io/ascii/ui.py in read(table, guess, **kwargs)
    351                                              ' with fast (no guessing)'})
    352         else:
--> 353             dat = reader.read(table)
    354             _read_trace.append({'kwargs': new_kwargs,
    355                                 'status': 'Success with specified Reader class '

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/io/ascii/cds.py in read(self, table)
    320                     return table
    321         else:
--> 322             return super(Cds, self).read(table)

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/io/ascii/core.py in read(self, table)
   1157 
   1158         # Get a list of the lines (rows) in the table
-> 1159         self.lines = self.inputter.get_lines(table)
   1160 
   1161         # Set self.data.data_lines to a slice of lines contain the data rows

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/io/ascii/core.py in get_lines(self, table)
    294                     ('\n' not in table + '' and '\r' not in table + '')):
    295                 with get_readable_fileobj(table,
--> 296                                           encoding=self.encoding) as fileobj:
    297                     table = fileobj.read()
    298             lines = table.splitlines()

/Users/adam/anaconda3/lib/python3.5/contextlib.py in __enter__(self)
     57     def __enter__(self):
     58         try:
---> 59             return next(self.gen)
     60         except StopIteration:
     61             raise RuntimeError("generator didn't yield") from None

/Users/adam/anaconda3/lib/python3.5/site-packages/astropy/utils/data.py in get_readable_fileobj(name_or_obj, encoding, cache, show_progress, remote_timeout)
    204             fileobj = open(name_or_obj, 'rb')
    205         else:
--> 206             fileobj = io.FileIO(name_or_obj, 'r')
    207         if is_url and not cache:
    208             delete_fds.append(fileobj)

FileNotFoundError: [Errno 2] No such file or directory: '/Users/adam/.astropy/cache/download/py3/20b3e61e52b6c1a14845ddb60d67b3e5'

**Comment by adrn** [comment] 2018-07-15 07:44
Sorry @aburgasser for letting this slip through the cracks. Were you able to resolve this by clearing the cache?

**Comment by juandesant** [comment] 2018-11-05 19:42
I can reproduce this still in astropy 3.0.5 with this code:

    import astropy.units as u
    from astropy.time import Time
    from astropy.coordinates import SkyCoord, EarthLocation
    keck = EarthLocation.from_geodetic(lat=19.8283*u.deg, lon=-155.4783*u.deg, height=4160*u.m)
    sc = SkyCoord(ra=4.88375*u.deg, dec=35.0436389*u.deg)
    barycorr = sc.radial_velocity_correction(obstime=Time('2016-6-4'), location=keck)

**Comment by Thinkpiet** [comment] 2018-12-02 00:42
Upgrading from numpy 1.15.3 to 1.15.4 has solved this for me

**Comment by adrn** [comment] 2018-12-20 15:51
Confirmed: updating from 1.15.3 -> 1.15.4 is the fix for this issue.

**Closed by adrn** 2018-12-20 15:51 UTC
Labels: Bug, coordinates

**Comment by mshemuni** [comment] 2018-12-21 13:12
```
  File "check.py", line 13, in <module>
    barycorr = sc.radial_velocity_correction(obstime=Time('2016-6-4'), location=keck)
  File "/usr/local/lib/python3.6/dist-packages/astropy/coordinates/sky_coordinate.py", line 1564, in radial_velocity_correction
    gcrs_p, gcrs_v = location.get_gcrs_posvel(obstime)
  File "/usr/local/lib/python3.6/dist-packages/astropy/coordinates/earth.py", line 648, in get_gcrs_posvel
    gcrs_data = self.get_gcrs(obstime).data
  File "/usr/local/lib/python3.6/dist-packages/astropy/coordinates/earth.py", line 628, in get_gcrs
    return itrs.transform_to(GCRS(obstime=obstime))
  File "/usr/local/lib/python3.6/dist-packages/astropy/coordinates/baseframe.py", line 1167, in transform_to
    return trans(self, new_frame)
  File "/usr/local/lib/python3.6/dist-packages/astropy/coordinates/transformations.py", line 1377, in __call__
    curr_coord = t(curr_coord, curr_toframe)
  File "/usr/local/lib/python3.6/dist-packages/astropy/coordinates/transformations.py", line 913, in __call__
    reprwithoutdiff = supcall(from_diffless, toframe)
  File "/usr/local/lib/python3.6/dist-packages/astropy/coordinates/builtin_frames/intermediate_rotation_transforms.py", line 87, in itrs_to_cirs
    pmat = cirs_to_itrs_mat(itrs_coo.obstime)
  File "/usr/local/lib/python3.6/dist-packages/astropy/coordinates/builtin_frames/intermediate_rotation_transforms.py", line 31, in cirs_to_itrs_mat
    xp, yp = get_polar_motion(time)
  File "/usr/local/lib/python3.6/dist-packages/astropy/coordinates/builtin_frames/utils.py", line 40, in get_polar_motion
    xp, yp, status = iers.IERS_Auto.open().pm_xy(time, return_status=True)
  File "/usr/local/lib/python3.6/dist-packages/astropy/utils/iers/iers.py", line 642, in open
    cls.iers_table = cls.read(file=filename)
  File "/usr/local/lib/python3.6/dist-packages/astropy/utils/iers/iers.py", line 499, in read
    iers_a = Table.read(file, format='cds', readme=readme)
  File "/usr/local/lib/python3.6/dist-packages/astropy/table/table.py", line 2534, in read
    out = io_registry.read(cls, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/astropy/io/registry.py", line 517, in read
    data = reader(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/astropy/io/ascii/connect.py", line 37, in io_read
    return read(filename, format=format, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/astropy/io/ascii/ui.py", line 385, in read
    dat = reader.read(table)
  File "/usr/local/lib/python3.6/dist-packages/astropy/io/ascii/cds.py", line 319, in read
    return super().read(table)
  File "/usr/local/lib/python3.6/dist-packages/astropy/io/ascii/core.py", line 1189, in read
    table = self.outputter(cols, self.meta)
  File "/usr/local/lib/python3.6/dist-packages/astropy/io/ascii/core.py", line 976, in __call__
    self._convert_vals(cols)
  File "/usr/local/lib/python3.6/dist-packages/astropy/io/ascii/core.py", line 961, in _convert_vals
    raise ValueError('Column {} failed to convert: {}'.format(col.name, last_err))
ValueError: Column year failed to convert: invalid literal for int() with base 10: '<s'
```
My numpy:
```
Name: numpy
Version: 1.15.4
Summary: NumPy: array processing for numbers, strings, records, and objects.
Home-page: http://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /usr/local/lib/python3.6/dist-packages
Requires:
```
My OS:
```
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 19 Tara
Release:	19
Codename:	tara
```

**Comment by pllim** [comment] 2018-12-21 15:53
@mshemuni , are you using the latest development version of Astropy from its `master` branch?

**Comment by pllim** [comment] 2019-01-04 20:56
@mshemuni , any chance you can use `conda` to create a fresh environment and see if the problem goes away? This might be also something incompatible hiding in your installation library...

**Comment by mshemuni** [comment] 2019-01-05 11:36
@pllim I installed Anaconda3 and basically started python3 from Anaconda bin directory and was able to execute the code.

Apparently you were right.Something in my system is not right.
Thank you for your help.

**Comment by aburgasser** [comment] 2019-02-13 06:49
@adrn sorry for not responding earlier, but yes clearing cache fixed the issue, thank you!
