### ISSUE TITLE
SkyCoord.separation is slow due to unneeded frame transform

### ISSUE THREAD

**Issue by dmopalmer** [astropy/astropy#5702] opened 2017-01-14 17:52 UTC
SkyCoord.separation() takes 22 milliseconds, compared to 4.5 milliseconds for Skycoord.position_angle().  This is the timing for two points in the same coordinate system.

The difference in speed is due to the fact that position_angle() checks whether the coordinate systems are the same, while separation() always does a transformation.  Since the most common use-case is to have all of the points be in the same coordinate system, this is extremely wasteful.

The code at 
`sky_coordinate.py:1060:position_angle()` and
`sky_coordinate.py:677:separation()`
should be identical, since they both serve the same function.

(Neither is fast, largely due  #5698 .  separation() calls FRAME_ATTR_NAMES_SET() 22 times causing 2717 getattr() calls).

Other comments:
I don't know why the various methods have their own import statements, e.g. `sky_coordinate.py:392`.  It probably is a minimal speed-up to put them all at the top, but it may be a stylistic convention in this project.

The following are possible enhancements (Should they go in a separate issue?  Do they already exist in some other library?):
I would also like to suggest a single function that returns both separation and posang (because that is something commonly desired). 

Also useful would be a function that takes a separation and posang to produce a new point.  (My particular use is triangulation from the InterPlanetary Network (IPN) that does timing-base localization of gamma ray bursts.  Other uses include drawing field-of-view circles and finding the midpoint between two points.)

**Comment by pllim** [comment] 2017-01-15 00:37
Perhaps solving #5698 (which appears to be a duplicate of #5022) would naturally solve this as well? Would be nice to have some code profiling to identify exactly where the bottleneck is for your use case.

**Comment by mhvk** [comment] 2017-01-15 03:16
@dmopalmer - thanks for the continued investigations! While #5698 would seem the bigger fish in terms of speed-up, I think you're right that `separation` and `position_angle` should share as much code/logic as possible. It also seems it is nice bitesize: one can start by just making the code more similar to the fast path, then try to merge common parts, etc. Indeed, this might well involve making the function that calculates either or both of `separation` and `position_angle`.

I also like the idea of an `offset(separation, position_angle)` method, though I guess it is probably best dealt with as a separate issue.

For now, I'll label this issue as a nice one where someone who wants to contribute to astropy could start; of course, if you're up for it, a PR would be most welcome!

**Comment by mhvk** [comment] 2017-01-15 03:18
Effort-low and Package-novice refer to the simplest part of this issue, of unifying what's good in `separation` and `position_angle`.

**Comment by dmopalmer** [comment] 2017-01-15 06:01
I'm working on it.

Is there some reason why .separation(self, other) takes either a SkyCoord or a BaseCoordinateFrame but position_angle only takes as a SkyCoord?  Is there any problem with harmonizing them?

**Comment by taldcroft** [comment] 2017-01-15 20:32
Since the issue of performance for separation is coming up again, there were similar discussions previously and I argued that we should support a very fast cythonized version that accepts only floats.  I still believe this.  See https://github.com/astropy/astropy/issues/3908#issuecomment-176782129.

**Comment by dmopalmer** [comment] 2017-01-15 20:50
The current implementation of position_angle has a bug due to it not recognizing that coordinate systems with the same frame name but equinoxes are different.  This means that the same-system short circuiting gets a false positive.  I will fix that too.

```
# position_angle has a bug
from astropy.coordinates import SkyCoord,FK5
import astropy.units as u
scJ2k = SkyCoord(10,20,unit=u.deg,frame=FK5,equinox='J2000')
scB50 = SkyCoord(10,20,unit=u.deg,frame=FK5,equinox='B1950')
print("J2K to B1950", scJ2k.separation(scB50),scJ2k.position_angle(scB50))
print("B1950 to J2K", scB50.separation(scJ2k),scB50.position_angle(scJ2k))

assert(scJ2k.position_angle(scB50) != scB50.position_angle(scJ2k))
```
```
J2K to B1950 0d40m35.1916s 0rad
B1950 to J2K 0d40m35.1916s 0rad
```

**Comment by dmopalmer** [comment] 2017-01-16 05:59
I fixed the position_angle bug and harmonized the code, by adding a lazy= argument to  SkyCoord.transform_to().

1) Defaults to lazy=False so it doesn't affect established code that always expects a copy of the object.
2) I don't have a lazy= argument in BaseCoordinateFrame.transform_to(), which would probably be good for API symmetry.
3) Is lazy= the right name for such an argument?

No timing results yet because they will be meaningless until #5703 PR is folded in, and I don't know how to do that reversibly in git without making a mess.  (I will probably end up doing an  [xkcd#1597](https://xkcd.com/1597/) merge anyway eventually, as usual.)

I will be adding 
```
SkyCoord.offset_by(self, sep=, posang=, dra=, ddec=, dlon=, dlat=, inplace=False)
```
where you can specify one pair of offsets.

Questions: 
1) Are those argument names stylistically appropriate for astropy, or should it be `separation=, position_angle=` ?
2) What is the right way to take a scalar SkyCoord and clone it into an array?  Can you point to a good example?

**Comment by mhvk** [comment] 2017-01-21 21:59
@dmopalmer - it may be easier to discuss based on an actual PR, but some answers anyway:
1. Is the `lazy` option meant to just return `self` if no transformation is needed? If so, I think I'd go with a `copy=True` argument (i.e., by default always a copy is returned, if `False`, only when needed, i.e., when a transform needs to be done).
2. I think it would be best to use long names for the parameters, and thus match the methods.
3. I don't understand the cloning aspect -- with the recent changes, `SkyCoord` should broadcast properly.

p.s.  I'd suggest to do the harmonization of `position_angle` and `separation` separately from introducing a new `offset_by` method -- this especially since the former involves a bug fix and can thus be in 1.3.1, while the latter is new and will go in 2.0.

**Comment by dmopalmer** [comment] 2017-01-21 22:31
1.  I would expect a `copy=False` argument to mean 'don't copy; if the frame is different, change the frame and values of the object', i.e. like an `inplace=True` argument.  An alternative is a a separate private member function `_transform_if_necessary_to`

2. Long arguments it is.  (I use ipython or an IDE, so I don't care how many characters a completion-key inserts.)

3. My cloning question is: does `result = SkyCoord(newlon, newlat, frame=self.frame)` capture all relevant information about `self`, such as frame name, equinox, pressure, temperature, and internals I don't know about?  (It doesn't capture, e.g., `self.obstime`, which raises the question of whether it would be expected to.)

**Comment by taldcroft** [comment] 2017-01-21 23:02
:+1: to the suggestion from @mhvk  to put these different changes into different PRs (and also to open PRs even if WIP to make it easier to discuss).

About this suggestion for API:
```
SkyCoord.offset_by(self, sep=, posang=, dra=, ddec=, dlon=, dlat=, inplace=False)
```
I would propose a different idea of allowing for any consistent set of kwargs that will initialize a [Representation object](http://astropy.readthedocs.io/en/latest/coordinates/representations.html).  This makes the API general and future proof.  That might imply adding a new representation based on `sep` and `posang` (at least in a perfect world, though we could fudge this special case if necessary).

**Comment by mhvk** [comment] 2017-01-21 23:11
@dmopalmer - I realized again one thing which influences two aspects of the above discussion, viz., that `SkyCoord` by design are meant to be immutable. Hence, nobody can care whether `transform_to` returns a copy or not and thus no `lazy` or `copy` flag is needed -- you can just change the code to return `self` if the frame transformed to is the same as that of `self`.

For the same reason, we should *not* introduce an `inplace` flag -- instead, we should make initialization so fast that nobody cares (and your other PR really helps for that purpose!).

See also http://docs.astropy.org/en/latest/coordinates/inplace.html

**Comment by dmopalmer** [comment] 2017-01-21 23:59
I will submit separate PRs for the different changes.

Representation Objects for locations in 2 or 3 space don't seem like a good fit for displacements.   @taldcroft  What would you suggest as the arguments to replace separation and position angle?  If you make a special case Representation Object for them, what does that mean in isolation?

My current signature is
```
    def offset_by(self, position_angle=None, separation=None,
                  dra=None, dra_distance=None, ddec=None,
                  dlon=None, dlon_distance=None, dlat=None,
                  inplace=False):
```
where ra and dec are synonymous with lon and lat.  

_distance means distance along that axis, instead of change of coordinate.  (i.e. if dec==60 then dra=1 changes ra from 0 to 1 but only moves the point by cos(60°)=1/2 degree, while dra_distance=1 changes ra from 0 to 2.)  This is another distinction that a Representation Object doesn't seem right for.

This function does not include any radial displacements.  It also does not include cartesian displacements.  Those would be nice.  Are they necessary?  Is it reasonable to just pile on more keyword arguments in a later PR cycle?

@mhvk I didn't know that SkyCoord was supposed to be immutable, but I agree that therefore you don't want an `inplace=` flag (whether you call it that or `copy=`; and you don't want to imply it and have it not work that way).

Even with my other PR initialization is still dog-slow (~1 ms), but it's not dead-dog-slow.  According to profiling, caching _get_representation_info (#2989) would double its speed again, which would make it merely slow.

**Comment by mhvk** [comment] 2017-01-22 00:59
we'll get up to greyhound speed at some point....

**Comment by taldcroft** [comment] 2017-01-22 12:14
@dmopalmer - 

The idea of using a Representation object is that a generalized coordinate offset is simply a new point viewed in the corresponding SkyOffsetFrame.  So here is an example that does most of the implementation of `offset_by` in a few lines of code, taking advantage of all the machinery (input validation, broadcasting, etc) that is already in place:
```
In [15]: c = SkyCoord(90, 45, unit='deg')

In [16]: offset = UnitSphericalRepresentation(lat=1*u.deg, lon=2*u.deg)
In [17]: offset_frame = SkyOffsetFrame(origin=c)
In [18]: c_offset = SkyCoord(offset, frame=offset_frame).transform_to(c.frame)

In [19]: c_offset
Out[19]: 
<SkyCoord (ICRS): (ra, dec, distance) in (deg, deg, )
    ( 92.87745395,  45.96448829,  1.)>
```

In reality it might make better conceptual sense to take any input representation and collapse to a 2d one by `represent_as` a unit spherical representation.

Admittedly there is the question of performance...

This idea does not handle your case of the `dra` and `ddec` args, but since it looks like those are just being arithmetically added to the coordinate `ra` and `dec`, I don't see any need to have that in an `offset_by` method.  Better to just do the addition explicitly since that means someone reading the code will immediately understand what is happening instead of having to refer to an API spec.

**Comment by taldcroft** [comment] 2017-01-22 12:19
Ugh, looks like this doesn't work for a non-scalar input coordinate `c`.  Need to think on this a bit...
```
>>> c_offset = SkyCoord(offset, frame=offset_frame).transform_to(c.frame)
ValueError: attribute origin should be scalar or have shape (), but is has shape (2,) and could not be broadcast.
```

**Comment by dmopalmer** [comment] 2017-01-22 16:09
The main problem with dra, ddec offsets is that it is fundamentally the wrong thing to do--treating spherical coordinates as if they are cartesian--and so it's hard to decide on the right way to do it.

If you are talking sub-degree displacements it is a useful and expedient thing to do, but it is hard to convince a framework intent on doing the right thing to permit it.

**Comment by dmopalmer** [comment] 2017-01-22 17:43
@taldcroft the arguments in `offset = UnitSphericalRepresentation(lat=1*u.deg, lon=2*u.deg)` don't correspond to separation and position_angle.

To use offset frames, you would want a new type of spherical representation with `colatitude` (distance from pole) instead of `latitude`, and a new argument for `SkyOffsetFrame(pole=c)`

**Comment by hamogu** [comment] 2017-01-23 01:41
:+1: to some offset_by(separation, position_angle) either as a method or as an example in the docs if the current framework already allows it similar to what @taldcroft suggested above.
I just has a need for that in a ray-trace simulation and found no easy solution. (I have something that's good enough for my use case  with subarcsec separations right now, but it's not elegant or readable or general.)

**Comment by dmopalmer** [comment] 2017-01-23 06:05
@taldcroft I (incorrectly) thought that my `offset_by(dra,ddec)` was the inverse of `spherical_offset_to()`.

However, looking more closely, it appears that  `spherical_offset_to()` does do the full spherical geometry.

Pull request #5727 contains the progress I've made so far.  (Plus some git-based confusion.)

**Comment by eteq** [comment] 2018-10-28 06:53
#5727 #5723 are in now so I think this is set to be closed.  Can be reopened if there's still some thread I missed though, as this spawned a lot of discussion.  Thanks @dmopalmer !

(Also, @hamogu, note that #5727 may now have the solution to you problem from https://github.com/astropy/astropy/issues/5702#issuecomment-274378485 ... sure, maybe 1.5 yrs after, but better late than never? ⏲  :wink:)

**Closed by eteq** 2018-10-28 06:53 UTC
Labels: Effort-low, Feature Request, Package-novice, Performance, coordinates, good first issue
