### ISSUE TITLE
Centralize `HAS_X` optional dependency flags?

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy#11488] opened 2021-04-06 18:46 UTC
>  I think all the flags for optional dependencies should be centrally managed. I personally put a ``setup_package.py`` file at the top of my code trees to hold all these ``HAS_X`` flags.

_Originally posted by @nstarman in https://github.com/astropy/astropy/pull/11361#discussion_r608047079_

@adrn replied
> ... I agree that we should probably centralize all of the HAS_X flag variables. I know of many instances in astropy, but mostly in test functions. For example: HAS_MATPLOTLIB or HAS_SCIPY.

**Comment by pllim** [comment] 2021-04-06 18:53
Why does it sound familiar. I think this had been suggested before...

**Comment by adrn** [comment] 2021-04-06 18:54
Oh, yea, I just found #4630 :)

**Comment by pllim** [comment] 2021-04-06 18:54
I think this is a duplicate of #4630 . It wasn't possible back then but maybe it is now...

https://github.com/astropy/astropy/issues/4630#issuecomment-627458639

**Closed** 2021-04-06 18:54 UTC
