### ISSUE TITLE
Auto-detect ECSV files

### ISSUE THREAD

**Issue by dkirkby** [astropy/astropy#4596] opened 2016-02-10 16:05 UTC
Currently, the format must always be specified when reading an ECSV file, e.g.

```
table = astropy.table.Table.read('data.ecsv', format='ascii.ecsv')
```

This issue is a suggestion to auto-detect the ECSV format for files with the .ecsv extension.

**Comment by cdeil** [comment] 2016-08-25 13:27
👍

**Comment by nimitbhardwaj** [comment] 2017-09-13 19:39
This is perhaps the duplicate of #6265

**Closed** 2017-10-03 13:23 UTC
Labels: Effort-low, Feature Request, io.ascii, Package-intermediate, table
