### ISSUE TITLE
FITS header keywords aren't updated if the only change is traling white space.

### ISSUE THREAD

**Issue by scfleming** [astropy/astropy#4693] opened 2016-03-14 19:04 UTC
Example, where "f" is the name of a FITS file that contains a header keyword called 'XTENSION' whose current value is "IMAGE":

with fits.open(f, mode="update") as hdulist:
    hdulist[1].header['XTENSION'] = "IMAGE   "
    hdulist.flush()

In this case, the keyword value is still set to "IMAGE" (no white space at the end).

The following DO work however:
with fits.open(f, mode="update") as hdulist:
    hdulist[1].header['XTENSION'] = "   IMAGE"
    hdulist.flush()

Leading white space does not suffer from this, the value is updated to include the leading white space.

with fits.open(f, mode="update") as hdulist:
    hdulist[1].header['XTENSION'] = "googly   "
    hdulist.flush()

Trailing white space is preserved if the string is otherwise different when updating.

with fits.open(f, mode="update") as hdulist:
    hdulist[1].header['XTENSION'] = "googly   "
    hdulist[1].header['XTENSION'] = "IMAGE   "
    hdulist.flush()

Trailing white space is preserved if you first change it to something else, then make the change that includes only white space at the end.

Either this is a bug regarding how astropy determines if the value has actually changed when the only change is trailing whitespace, or this is an unitended consequence of how the methods/objects that are relied on operate.

**Comment by joergdietrich** [comment] 2016-03-16 14:41
This seems to be in accordance with the FITS standard (Sect. 4.2.1):

>  Leading spaces are significant; trailing spaces are not.

**Comment by embray** [comment] 2021-07-08 09:57
I think there is still a bug in that:

> Trailing white space is preserved if you first change it to something else, then make the change that includes only white space at the end.

**Comment by embray** [comment] 2021-07-08 10:03
In any case, if there was a bug I can't reproduce it any longer.

One other bit from the FITS standard worth noting regarding trailing whitespace:

> Earlier versions of this Standard also required that fixed-format
characters strings must be padded with space characters to at
least a length of eight characters so that the closing quote character does not occur before Byte 20. This minimum characterstring length is no longer required, except for the value of the
XTENSION keyword (e.g., 'IMAGE ' and 'TABLE '; see
Sect. 7), which must be padded to a length of eight characters
for backward compatibility with previous usage

`astropy.io.fits` still does this padding for all keywords rather than making a special case for `XTENSION`.  But no one has ever really bothered or complained about that.  I suppose it could be an option if anyone really cared.

**Closed by embray** 2021-07-08 10:03 UTC
Labels: io.fits
