### ISSUE TITLE
Deepcopy of table with object column returns shallow copy

### ISSUE THREAD

**Issue by dlakaplan** [astropy/astropy#13435] opened 2022-07-06 15:12 UTC
### Description
With an astropy `Table` (or `QTable`) containing a column of `dtype=object`, a deepcopy returns a shallow copy of that column (the other columns are OK).

### Expected behavior
Deep copies of all columns

### Actual behavior
Deep copies of columns with `dtype=int`, `float`, etc, but with `object` just returns shallow copy.

### Steps to Reproduce

```python
import copy
from astropy.table import Table
from astropy import units as u
import numpy as np
import astropy


class X:
    def __init__(self, value):
        self.value = value

    def __repr__(self):
        return str(self.value)


a = np.array([1, 4, 5], dtype=np.int32)
b = [2.0, 5.0, 8.5]
c = ["x", "y", "z"]
d = [10, 20, 30] * u.m / u.s
e = [X(1), X(2), X(3)]

t = Table(
    [a, b, c, d, e],
    names=("a", "b", "c", "d", "e"),
    meta={"name": "first table"},
)
t_copy = copy.deepcopy(t)

for cname in t.colnames:
    print(
        f"column '{cname}' in Table: type={t[cname].dtype}, is identical={t[0][cname] is t_copy[0][cname]}"
    )
print(f"For astropy version {astropy.__version__}")
```

For me this returns:
```
column 'a' in Table: type=int32, is identical=False
column 'b' in Table: type=float64, is identical=False
column 'c' in Table: type=<U1, is identical=False
column 'd' in Table: type=float64, is identical=False
column 'e' in Table: type=object, is identical=True
For astropy version 5.1
```

If you add in an explicit deepcopy of those objects:
```python
for i in range(len(t)):
    t_copy[i]["e"] = copy.deepcopy(t[i]["e"])
```
then it works as expected

### System Details
```
>>> import platform; print(platform.platform())
macOS-10.16-x86_64-i386-64bit
>>> import sys; print("Python", sys.version)
Python 3.9.7 (default, Sep 16 2021, 08:50:36) 
[Clang 10.0.0 ]
>>> import numpy; print("Numpy", numpy.__version__)
Numpy 1.21.2
>>> import erfa; print("pyerfa", erfa.__version__)
pyerfa 2.0.0
>>> import astropy; print("astropy", astropy.__version__)
astropy 5.1
>>> import scipy; print("Scipy", scipy.__version__)
Scipy 1.7.1
>>> import matplotlib; print("Matplotlib", matplotlib.__version__)
Matplotlib 3.4.3
```

**Comment by pllim** [comment] 2022-07-06 16:33
Thanks for reporting. Confirmed in 5.2.dev as well.

**Comment by neutrinoceros** [comment] 2024-01-10 13:24
I had a look. First, here's a reduced version of the reproducer in test form:
```python
import copy
from astropy.table import Table
from astropy import units as u
import numpy as np
import pytest


@pytest.mark.parametrize(
    "data",
    [
        np.array([1], dtype=np.int32),
        [2.0],
        ["x"],
        [10] * u.m / u.s,
        [object()],
    ],
)
def test_13435(data):
    t = Table({"a": data})
    t_copy = copy.deepcopy(t)

    col = t["a"]
    col_copy = t_copy["a"]
    assert col_copy is not col
    assert col_copy[0] is not col[0]
```

Upon inspection, I discovered that the root cause is that `np.array(..., copy=True)` doesn't work as you'd expect for simple `object`s:
```python
import numpy as np
a = np.array(object())
b = np.array(a, copy=True)
assert b.item() is not a.item()
```
raises an `AssertionError`. While it should in principle to possible to copy an instance of `object`, I don't know whether that's considered a bug in numpy. I'll need to report upstream.

In the case of my reduced test, we hit https://github.com/astropy/astropy/blob/4e456bc57dded369edb92584ea85ffa597114202/astropy/table/column.py#L560
but there are many other branches that can be hit instead, and in all cases, we delegate to `np.array(..., copy=copy)` to perform the actual copy.

**Comment by neutrinoceros** [comment] 2024-01-10 14:33
reported upstream as https://github.com/numpy/numpy/issues/25562

**Comment by taldcroft** [comment] 2024-01-10 15:28
Thanks for the triage on this @neutrinoceros. I agree with your assessment, and hopefully this will be addressed in numpy. 

Even though we have some history of trying to patch around undesirable numpy behavior (mostly in masked arrays), I think we should leave this as an upstream fix and something we won't fix in astropy. That would imply closing this issue with `wont-fix`. Thoughts @mhvk?

**Comment by rkern** [comment] 2024-01-10 16:24
It's working as designed. `copy=True` was never intended to imply a deepcopy of `dtype=object` arrays, just that you would get a new `ndarray` object with the data copied over, as opposed to `np.asarray()`. In the `dtype=object` case, "the data" is just the pointers to the objects.

`copy.deepcopy(some_object_array)` works to get a deepcopy of a `dtype=object` array.

**Comment by mhvk** [comment] 2024-01-10 16:40
This all makes sense. So, the question then is whether our `Table.__deepcopy__` should be adjusted to, essentially, do `copy.deepcopy` of all the columns. To me, that seems reasonable, given that `deepcopy(array)` does that. That means `__deepcopy__` can no longer rely on `Table(..., copy=True)`, but would need to be something like
```
out = self.__class__(self, copy=False)
for name = out.colnames:
    out[name] = deepcopy(out[name])
return out
```
(Using that metadata is always deep-copied.)

p.s. Removing the `close` and `wont-fix` for now.

**Comment by neutrinoceros** [comment] 2024-01-11 08:13
> So, the question then is whether our Table.__deepcopy__ should be adjusted to, essentially, do copy.deepcopy of all the columns

This sound like the only reasonable approach to me. Thank you for laying out so much insight, I'll get started on implementing it !

**Closed** 2024-03-27 17:14 UTC
Labels: table, Bug, question
