### ISSUE TITLE
Permission systematically denied in import from astropy.io

### ISSUE THREAD

**Issue by mrkite92** [astropy/astropy#5924] opened 2017-03-30 16:21 UTC
Hi astropy gurus,

I work under macOS 10.12.4 and MacPorts Python install with sudo.
Here is a typical scenario, using the astride package installed from pip:
```
from astride import test
test()
```
Then:
```
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-1-42f18d0a8bb9> in <module>()
----> 1 from astride import test
      2 
      3 test()

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astride/__init__.py in <module>()
----> 1 from astride.test.run import test
      2 from astride.detect import Streak
      3 from astride.utils.logger import Logger

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astride/test/run.py in <module>()
      2 from os.path import join
      3 
----> 4 from astride.detect import Streak
      5 from astride.utils.logger import Logger
      6 

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astride/detect.py in <module>()
      5 
      6 from skimage import measure
----> 7 from astropy.io import fits
      8 from astropy.stats import sigma_clipped_stats
      9 from photutils import Background2D, SigmaClip, MedianBackground

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/__init__.py in <module>()
    284     log = _init_log()
    285 
--> 286     _initialize_astropy()
    287 
    288     from .utils.misc import find_api_page

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/__init__.py in _initialize_astropy()
    207 
    208     try:
--> 209         config.configuration.update_default_config(__package__, config_dir)
    210     except config.configuration.ConfigurationDefaultMissingError as e:
    211         wmsg = (e.args[0] + " Cannot install default profile. If you are "

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/config/configuration.pyc in update_default_config(pkg, default_cfg_dir_or_fn, version)
    671     cfgfn = get_config(pkg).filename
    672 
--> 673     with io.open(default_cfgfn, 'rt', encoding='latin-1') as fr:
    674         template_content = fr.read()
    675 

IOError: [Errno 13] Permission denied: '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/astropy.cfg'
```
I got the same from my own scripts.

Cheers,
JB

**Comment by bsipocz** [comment] 2017-03-30 16:29
@mrkite92 - This looks like being a duplicate of #https://github.com/astropy/astropy/issues/5912. Could you please confirm that you're trying to use astropy 1.3.1?

If yes, then the workarounds are the following: 
- downgrade to 1.3 from macports
- try to pip or conda install 1.3.1

1.3.2 will have a fix for this issue

**Comment by cdeil** [comment] 2017-03-30 19:16
@bsipocz - Is there an ETA for Astropy 1.3.2 with a fix for this issue?

If it's not within the next few days, then I would change back to the older, working version in Macports now.

**Comment by bsipocz** [comment] 2017-03-30 19:18
@cdeil - I'm waiting for a green light on a coordinate bugfix (https://github.com/astropy/astropy/pull/5887), once that's given making the release shouldn't take long.

**Comment by bsipocz** [comment] 2017-03-30 20:18
Closing as duplicate.

**Closed by bsipocz** 2017-03-30 20:18 UTC
Labels: Duplicate, installation, Mac OSX

**Comment by cdeil** [comment] 2017-03-31 15:45
For any Macports users, this issue should now be fixed. To update:
```
sudo port selfupdate
sudo port -p upgrade outdated
```
and to check the version number
```
port installed *astropy*
```
