### ISSUE TITLE
Trying to install Astropy

### ISSUE THREAD

**Issue by antiseptic2017** [astropy/astropy#6467] opened 2017-08-22 15:55 UTC
Hi

Trying to test and install Astropy on Ubuintu 16.04 without any success, I have the errors popping up as below.

Thanks

Traceback (most recent call last):
  File "/home/ladyhawk/Desktop/astro.py", line 1, in <module>
    import astropy
  File "/home/ladyhawk/Desktop/astropy.py", line 2, in <module>
    astropy.test(package='io.fits')
AttributeError: module 'astropy' has no attribute 'test'
>>>

**Comment by astrofrog** [comment] 2017-08-22 16:04
The issue is that you have a file called ``astropy.py`` on your desktop, so this takes precedence over the real astropy module. Try removing or renaming the astropy.py file from the desktop then do (in ``astro.py``):

```
import astropy
astropy.test()
```

**Comment by antiseptic2017** [comment] 2017-08-23 11:34
Hi

Thanks, that worked fine.

I am still having huge amounts of problems of just getting a 4 line program
to work, there dose not seem to be any simple examples on the web to
get you on the way, there is one site with examples but dose not include
print function in the examples.

I tried this several different ways, just failures.

Any extra help with this would be much appreciated.

I have written my own local sidereal time program, that works fine just
trying to get the astropy module to read the commands.

from astropy.time import Time

T = t.sidereal_time('mean')

print ('T')

Traceback (most recent call last):
  File "/home/ladyhawk/Desktop/as.py", line 3, in <module>
    T = t.sidereal_time('mean')
NameError: name 't' is not defined

**Comment by astrofrog** [comment] 2017-08-23 12:29
@antiseptic2017 - have you tried some of the examples here?

http://docs.astropy.org/en/stable/time/index.html

In your example you have not defined ``t`` before using it. You might be missing a statement of the form ``t = Time(...)``

**Comment by antiseptic2017** [comment] 2017-08-23 14:48
I have tried those examples but there is no print statement to print the
answer, dose astopy not use print statements, just a litle confused on all
of this.



On Wed, Aug 23, 2017 at 8:29 PM, Thomas Robitaille <notifications@github.com

**Comment by pllim** [comment] 2017-08-23 14:59
> I have tried those examples but there is no print statement to print the answer

Whenever you want to print something in your session, just use `print(...)`.

**Comment by antiseptic2017** [comment] 2017-08-23 15:07
Hi


I looked at the examples there is no output from the examples, or print
statement.


Thanks


Sidereal Time

Apparent or mean sidereal time can be calculated using sidereal_time()
<http://docs.astropy.org/en/stable/api/astropy.time.Time.html#astropy.time.Time.sidereal_time>.
The method returns a Longitude
<http://docs.astropy.org/en/stable/api/astropy.coordinates.Longitude.html#astropy.coordinates.Longitude>
with units of hourangle, which by default is for the longitude
corresponding to the location with which the Time
<http://docs.astropy.org/en/stable/api/astropy.time.Time.html#astropy.time.Time>
object is initialized. Like the scale transformations, ERFA C-library
routines are used under the hood, which support calculations following
different IAU resolutions. Sample usage:
>>>

>>> t = Time('2006-01-15 21:24:37.5', scale='utc', location=('120d', '45d'))>>> t.sidereal_time('mean')  <Longitude 13.089521870640212 hourangle>>>> t.sidereal_time('apparent')  <Longitude 13.089503675087027 hourangle>>>> t.sidereal_time('apparent', 'greenwich')  <Longitude 5.089503675087027 hourangle>>>> t.sidereal_time('apparent', '-90d')  <Longitude 23.08950367508703 hourangle>>>> t.sidereal_time('apparent', '-90d', 'IAU1994')  <Longitude 23.08950365423405 hourangle>

**Comment by pllim** [comment] 2017-08-23 15:10
The example is using an interactive Python session. So the output shown would be similar to what you would see if you print them out instead. You may modify the example code to suit your needs.

**Comment by antiseptic2017** [comment] 2017-08-23 15:25
Traceback (most recent call last):
  File "/home/ladyhawk/Desktop/AS.py", line 4, in <module>
    t.sidereal_time('apparent', 'greenwich')
NameError: name 't' is not defined

**Comment by antiseptic2017** [comment] 2017-08-23 15:25
Traceback (most recent call last):
  File "/home/ladyhawk/Desktop/AS.py", line 4, in <module>
    t.sidereal_time('apparent', 'greenwich')
NameError: name 't' is not defined

**Comment by pllim** [comment] 2017-08-23 15:25
In the example you provided above
```python
t = Time('2006-01-15 21:24:37.5', scale='utc', location=('120d', '45d'))
```

**Comment by mhvk** [comment] 2017-08-25 17:30
closing since the problems seem to have been solved

**Closed by mhvk** 2017-08-25 17:30 UTC
Labels: Close?, Needs-clarification
