### ISSUE TITLE
WCS tick labels not appearing

### ISSUE THREAD

**Issue by REMeyer** [astropy/astropy#8521] opened 2019-03-22 02:33 UTC
I am trying to plot a fits image with equitorial coordinates. The header contains enough information to produce a WCS solution and correctly displays the correct coordinates when moving the cursor over the interactively plotted image. The tick labels however do not appear. I have tried setting many different options to make the labels appear to no avail. Attached is a sample image for testing purposes. 

[M85_combined_cubeImg_1.fits.zip](https://github.com/astropy/astropy/files/2994705/M85_combined_cubeImg_1.fits.zip)

**Comment by pllim** [comment] 2019-03-22 13:19
Hello. Could you please provide snippet to reproduce your problem and the versions used? Also please check the other issues to make sure it is not already reported, as this sounds familiar.

**Comment by astrofrog** [comment] 2019-03-22 17:05
The issue is that the WCS is rotated by almost exactly 90 degrees, so that RA varies on the y axis and Dec on the x axis. Try using the methods described here to show RA/Dec on all axes:

http://docs.astropy.org/en/stable/visualization/wcsaxes/ticks_labels_grid.html#tick-tick-label-and-axis-label-position

for instance:

```python
lon, lat = ax.coords
lon.set_ticks(color='red')
lon.set_ticks_position('lbtr')
lon.set_ticklabel_position('lbtr')
lat.set_ticks(color='blue')
lat.set_ticks_position('lbtr')
lat.set_ticklabel_position('lbtr')
```

**Comment by astrofrog** [comment] 2019-03-22 17:06
This is a reasonably common issue that comes up from time to time, so I think we should add a section to mention this solution.

**Comment by REMeyer** [comment] 2019-03-22 17:36
> The issue is that the WCS is rotated by almost exactly 90 degrees, so that RA varies on the y axis and Dec on the x axis. Try using the methods described here to show RA/Dec on all axes:
> 
> http://docs.astropy.org/en/stable/visualization/wcsaxes/ticks_labels_grid.html#tick-tick-label-and-axis-label-position
> 
> for instance:
> 
> ```python
> lon, lat = ax.coords
> lon.set_ticks(color='red')
> lon.set_ticks_position('lbtr')
> lon.set_ticklabel_position('lbtr')
> lat.set_ticks(color='blue')
> lat.set_ticks_position('lbtr')
> lat.set_ticklabel_position('lbtr')
> ```

This solved the issue. The axis labels now appear.

**Comment by astrofrog** [comment] 2019-03-22 17:41
@REMeyer - great! Ok, so we should keep this issue open as a documentation task. I can try and write this shortly.

**Comment by astrofrog** [comment] 2019-06-18 14:48
I'm going to close this as we also have https://github.com/astropy/astropy/issues/7180

**Closed by astrofrog** 2019-06-18 14:48 UTC
Labels: Docs, visualization.wcsaxes
