### ISSUE TITLE
time.to_datetime() is extremely slow when there is a timezone

### ISSUE THREAD

**Issue by dmopalmer** [astropy/astropy#5607] opened 2016-12-14 17:51 UTC
Timezone support was added to Time.to_datetime recently (#4119).  However, it is extremely slow (~20 milliseconds, 100x slower than without timezone.)  This excess time comes from the constructor of TimezoneInfo().

```
>>> from astropy.time import Time, TimezoneInfo
>>> from pytz import utc
>>> now = Time.now()
>>> %timeit now.to_datetime()
10000 loops, best of 3: 166 µs per loop
>>> %timeit now.to_datetime(timezone=utc)
10 loops, best of 3: 23.2 ms per loop
>>> %timeit TimezoneInfo
10000000 loops, best of 3: 46.6 ns per loop
>>> %timeit TimezoneInfo()
10 loops, best of 3: 25 ms per loop
```

Limiting time conversions to 50/second is a significant performance issue (although there are workarounds.)

EDIT: See also #4124

**Comment by mhvk** [comment] 2016-12-14 19:08
@dmopalmer - I'm trying to reproduce, and I find a ridiculously slow `TimezoneInfo()` also on 1.2.1 (11 ms on my machine), but if I try on current master, it is *much* faster (0.5 ms). I'm quite puzzled by this, since I don't see any obvious code changes, but before I go further, could you check as well?

**Comment by mhvk** [comment] 2016-12-14 20:09
It is also fast on astropy-1.3rc1, so in that sense this is resolved. I think the reason for the speed-up is #5306: it will have made https://github.com/astropy/astropy/blob/master/astropy/units/decorators.py#L129 much faster.

Anyway, if you can confirm that the problem is solved in 1.3rc1, then I think we can close this issue.

**Comment by dmopalmer** [comment] 2016-12-14 22:50
Just grabbing the latest version from github (which is 2.0.dev17573) it is significantly improved (to only 10x slower):
```
In [1]: import astropy

In [2]: astropy.__version__
Out[2]: '2.0.dev17573'

In [3]: from astropy.time import Time, TimezoneInfo

In [4]: from pytz import utc

In [5]: now = Time.now()

In [6]: %timeit now.to_datetime()
10000 loops, best of 3: 140 µs per loop

In [7]: %timeit now.to_datetime(timezone=utc)
1000 loops, best of 3: 1.12 ms per loop
```

So I agree, close.

**Comment by mhvk** [comment] 2016-12-14 23:08
OK, thanks both for reporting and for checking that, thankfully, this has indeed been solved.

**Closed by mhvk** 2016-12-14 23:08 UTC
Labels: Performance, time

**Comment by MSeifert04** [comment] 2016-12-14 23:13
@mhvk You're probably right. It took a while and it's not really doable to profile decorators but it would make sense that the `equivalencies` in `u.quantity_input` were the bottleneck here. It's still quite slow but I think these are because of the `Quantity.to` and `x * u.day == 0` operations in the code.

**Comment by mhvk** [comment] 2016-12-14 23:19
@MSeifert04 - yes, the code is not the fastest. Though, looking at it more, I think it is meant only as a crutch if one doesn't have `pytz` -- @dmopalmer - that may be another way to get a speed-up...

**Comment by MSeifert04** [comment] 2016-12-14 23:30
Yeah, was quite a surprise that it's the comparisons [`dst == 0`](https://github.com/astropy/astropy/blob/82519cff4983c52edb46805dbbb3eaf5a1261964/astropy/time/formats.py#L650) were the bottleneck with _250_ us per operation 😄

**Comment by mhvk** [comment] 2016-12-14 23:58
Yes, that is actually a tricky one, as it finds the units do not match and then goes on to check whether the values involved are all 0. For optimal speed, this particular line should be
```
if tzname is None and utc_offset.value == dst.value == 0:
```
though I don't like the lack of clarify that results (though even just doing `utc_offset == dst == 0.*u.day` helps considerably).

Anyway, time might be better spent trying to optimize `Quantity` itself!
