### ISSUE TITLE
Table.read segfaults on CSV file with missing comma in header

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy#5276] opened 2016-08-29 09:37 UTC
For this `CSV` file with a missing trailing comma in the header line

```
aaa,bbb
1,2,
3,4,
```

I'm getting a segfault from `Table.read`:

```
$ python -c 'from astropy.table import Table; Table.read("test.csv")'
Segmentation fault: 11
```

This is with Python 3.5.2, Numpy 1.11.1 and Astropy 1.2 from Macports on latest Mac OS X.

Here's the crash report:
https://gist.github.com/cdeil/164d4d5ee14b49598e0454873ff0ea04#file-gistfile1-txt-L34

```
1   cparser.cpython-35m-darwin.so   0x0000000111448763 __pyx_pw_7astropy_2io_5ascii_7cparser_7CParser_9read + 1219
```

@mdmueller, @taldcroft or anyone familiar with the astropy.io.ascii cparser: can you reproduce or do you need more info?

**Comment by taldcroft** [comment] 2016-08-29 11:37
@cdeil - I can reproduce this.  You probably know this, but a workaround is to use `fast_reader=False`).

I spent a few minutes playing around with this, but my C skills are basically null.  Clearly what is happening here is that `self->nul_cols` gets set from the header and some structures get allocated based on that:
```
    // Allocate memory for structures used during tokenization
    self->output_cols = (char **) malloc(self->num_cols * sizeof(char *));
    self->col_ptrs = (char **) malloc(self->num_cols * sizeof(char *));
    self->output_len = (int *) malloc(self->num_cols * sizeof(int));
```
If I just hacked the `tokenizer.c` code and allocated `self->num_cols + 1` then your example does not segfault.  If there is someone with experience debugging C code that would be good!

**Comment by pllim** [comment] 2016-08-29 13:58
`gdb` should be able to provide a proper traceback for this case, I think.

**Comment by taldcroft** [comment] 2016-08-29 16:19
Do you need to compile the code with a debug flag?

**Comment by pllim** [comment] 2016-08-29 17:32
@taldcroft , yes, you need the debug flag.

**Comment by cdeil** [comment] 2016-12-01 07:23
IMO Astropy segfaulting for a common and simple use case, reading a CSV file with a little format error makes us look bad. I'm working with colleagues that mostly use C / C++, and one of the big selling points of Python is that Python programs don't segfault, they either just work or end with a traceback.

I don't want to spend time on debugging this C ascii reader code, because I don't understand why it was added in the first place. Is anyone really limited by ascii table reading speed? If yes, can't they  change to a binary format?

My proposal here would be to change the default reader back to the Python one, i.e. make the C reader opt-in for people that need it. Then people like me and most others would never see this issue.

**Comment by cdeil** [comment] 2016-12-01 12:50
It looks like changing the `fast_reader` default from `True` to `False` would be a simple, small change:
https://github.com/astropy/astropy/search?utf8=%E2%9C%93&q=fast_reader

@taldcroft - what do you think about this change? (at least until all known C ascii reader bugs are resolved)

If positive, I could try to make a PR today or tomorrow to get this in for 1.3.

**Comment by taldcroft** [comment] 2016-12-01 13:28
@cdeil - I am provisionally OK with changing the default if we cannot resolve this bug.  Hopefully this should be a relatively straightforward PR.

As for the motivation, like it or not, people do use ASCII formats for large tables and performance can be an issue.  Perhaps opting-in to using the C-reader is acceptable, but it will just be annoying to suddenly have it take a 4 times longer to read tables (by default).

@mdmueller - any chance you could look at this in the next couple days?  :smile:

**Comment by saimn** [comment] 2016-12-01 13:58
Having a quick look to it, now that I know a bit the tokenizer code, it should be easy to fix. I will open a PR later.

**Comment by pllim** [comment] 2016-12-01 16:39
> changing the default

I vaguely remember a long discussion about this in some older PR...

**Comment by cdeil** [comment] 2016-12-01 16:43
There's another issue by @taldcroft with a crash in the fast ascii reader: #5219

I didn't browse the issues, but I think there were other issues.

May I suggest we milestone those 1.3, and then either they are fixed in a day or two,
or we make the change to slower, but non-crashing ascii table reading by defaul?

**Comment by cdeil** [comment] 2016-12-01 16:44
Here's another one that might or might not be the same issue: #4610
In any case, since it ends with segfault, it should be labled "bug" and milestoned 1.3 IMO.

**Comment by taldcroft** [comment] 2016-12-01 17:09
#5219 is a duplicate of this and I've closed it.

**Closed** 2016-12-02 11:32 UTC
Labels: Affects-release, Bug, table
