### ISSUE TITLE
Should the default centering statistic for sigma clipping be mean instead of median?

### ISSUE THREAD

**Issue by larrybradley** [astropy/astropy#7581] opened 2018-06-20 02:33 UTC
This question originally came up in https://github.com/astropy/astropy/pull/7478.

Note that changing the default from median to mean would cause a backwards-incompatible change.  For reference, `scipy.stats.sigmaclip` always uses the mean (it's not a user option).

CC: @astrofrog, @astroferreira

**Comment by pllim** [comment] 2018-06-20 14:03
FWIW I would say the ship has sailed on this one. Consider this: User upgrades Astropy that suddenly uses mean as default, where it used to be median, only to be confused why results changed but only slightly.

And isn't median more resistant to outliers?

**Comment by pllim** [comment] 2018-06-20 14:03
cc @crawfordsm

**Comment by saimn** [comment] 2018-06-20 14:11
I think the median is better here: the goal is to remove outliers, so it needs a robust mean estimator.

For instance IDL's [meanclip](https://idlastro.gsfc.nasa.gov/ftp/pro/math/meanclip.pro) uses the median, and same for [GnuAstro](https://www.gnu.org/software/gnuastro/manual/html_node/Sigma-clipping.html). 

I tried to find why scipy uses the mean, but this was added a long time ago (https://github.com/scipy/scipy/commit/bad9a1b7345aaae2165a0b5a9516c9859075c968) and it didn't change since, and I didn't find justification of using the mean.

**Comment by bsipocz** [comment] 2018-06-20 14:21
I vote for status quo, too, (but being partial, too as I always used median for sigma clipping given its more robustness for the outliers)

**Comment by astroferreira** [comment] 2018-06-20 15:17
I think the median is more common (as stated by @saimn) in the context of astronomy. I guess it is more than just because it is more robust against outliers. The median is generally a better guess than the mean when it comes to background estimation in astronomy.

**Comment by astrofrog** [comment] 2018-06-20 16:15
I guess the reason why this came up originally is because I was thinking that the issue is that the std is computed relative to the mean, not the median, so I was wondering whether that was inconsistent.

**Comment by pllim** [comment] 2018-06-20 17:21
> the issue is that the std is computed relative to the mean

Hmm... Would replacing `std` with MAD make more sense? :thinking:

**Comment by crawfordsm** [comment] 2018-08-31 20:28
Closing -- as the user has the chance to change it and there isn't overwhelming feelings this should change, it seems like maintaining the backward compatibility takes precedent.

**Closed by crawfordsm** 2018-08-31 20:28 UTC
Labels: question, stats
