### ISSUE TITLE
Explanation of Bayesian block warning?

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/astropy#5826] opened 2017-02-17 18:07 UTC
(Related #4927)

    WARNING: p0 does not seem to accurately represent the false positive rate for event data. It is highly recommended that you run random trials on signal-free noise to calibrate ncp_prior to achieve a desired false positive rate. [astropy.stats.bayesian_blocks]

I'm getting this warning when using [astropy.stats.bayesian_blocks()](http://docs.astropy.org/en/stable/api/astropy.stats.bayesian_blocks.html#astropy.stats.bayesian_blocks) on some data. Sadly the [Scargle article](http://adsabs.harvard.edu/abs/2012arXiv1207.5578S) goes over my head. Could someone perhaps explain in more or less layman's terms what this warning means or how to address it?

As I recall the [astroML](http://www.astroml.org/user_guide/density_estimation.html#bayesian-blocks-histograms-the-right-way) implementation of this algorithm did not have such a warning.

cc @jakevdp @robcross

**Comment by jakevdp** [comment] 2017-02-17 18:23
This is to alert you to something that's discussed in the function documentation string: ``p0`` does not appear to be a valid false-positive rate for events-based fitness functions. The false positive rate can be callibrated by running bootstrap trials or trials on data with zero signal. I don't have any example of that around – maybe @robcross does?

**Comment by jakevdp** [comment] 2017-02-17 18:23
More discussion of this issue here: https://github.com/astropy/astropy/pull/4301

**Comment by robcross** [comment] 2017-02-17 18:25
Hi Gabriel. I put this warning in because the `ncp_prior` is used to tune the "sensitivity" of the algorithm detecting an edge. Scargle found a relationship between `ncp_prior` and the false probability `p0` of detecting an edge for a specific case of data with certain statistics.

The bottom line is that if you want `p0` to accurately represent the probability of detecting a false edge, you should tune `ncp_prior` by running trials on data without any signal (just noise).

Let me know if this helps.

(you beat me to it Jake!)

**Comment by Gabriel-p** [comment] 2017-02-17 18:48
Thank you both @jakevdp and @robcross, that's very helpful.

Briefly, I'm using this algorithm to determine the bin edges in a color-magnitude diagram of star clusters, as the one shown below (the dotted lines are the Bayesian block edges found for each dimension separately)

![cmd](https://cloud.githubusercontent.com/assets/6054951/23078691/6b4784f4-f528-11e6-9804-9ef51e7d99d1.png)

The bins in this 2D histogram are then analyzed to remove contamination from field stars.

As my statistical knowledge is rather limited, how would you advice I proceed to properly estimate `ncp_prior` to bypass this warning?

**Comment by bsipocz** [comment] 2017-02-18 01:20
This issue seems to be a duplicate of #4927, so I'm very much inclined to close it. 

For similar "how-to" issues, I think, the [mailing list](https://mail.scipy.org/mailman/listinfo/astropy), or the "Python in astronomy" facebook group is a better platform.

@Gabriel-p - Please do reopen if you think there is a todo item for the code or the docs to address.

**Closed by bsipocz** 2017-02-18 01:20 UTC
Labels: Docs, Duplicate, stats

**Comment by Gabriel-p** [comment] 2017-02-18 02:03
Fair enough @bsipocz. Cheers.
