### ISSUE TITLE
SkyCoord class is Iterable, yet raises exception when trying to iterate scalars.

### ISSUE THREAD

**Issue by dobos** [astropy/astropy#16172] opened 2024-03-06 21:11 UTC
### Description

As of version 5.2.2, `isinstance(SkyCoord(10, 10, unit=u.degree), Iterable)` evaluates to `True` and member functions `__iter__` and `__len__` are present, `hasattr(c, '__len__')` evaluates to `True`. Yet calls to `__iter__` or `__len__` result in an exception when only a single pair of coordinates is wrapped.

### Expected behavior

Either make sure that `__iter__` and `__len__` are not present when `SkyCoord` is just a single pair of coordinates, or implement the iterator over that single value. Throwing an exception from `__len__` or `__iter__` is not how other Python libraries work. Since testing if an object is an instance of Iterable translates to something like `hasattr(c, '__iter__')`, implementing the single-element iterator is easier, or the scalar `SkyCoord` should be monkey-patched somehow by explicitly removing the functions from the object. The issue probably affects all classes that inherit from `ShapedLikeNDArray`.

### How to Reproduce

1. Run the code below with the latest version of astropy installed.

```python
from collections.abc import Iterable
from astropy.coordinates import SkyCoord
import astropy.units as u

cc = SkyCoord(0 * u.deg, 0 * u.deg)
if isinstance(cc, Iterable):
  for c in cc:     # __iter__ will throw an exception
    print(c)
```

### Versions

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import astropy; print("astropy", astropy.__version__)
import numpy; print("Numpy", numpy.__version__)
import erfa; print("pyerfa", erfa.__version__)
try:
    import scipy
    print("Scipy", scipy.__version__)
except ImportError:
    print("Scipy not installed")
try:
    import matplotlib
    print("Matplotlib", matplotlib.__version__)
except ImportError:
    print("Matplotlib not installed")
```
```
Linux-4.18.0-348.20.1.el8_5.x86_64-x86_64-with-glibc2.28
Python 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC 11.3.0]
astropy 5.2.2
Numpy 1.24.4
pyerfa 2.0.0.2
Scipy 1.10.1
Matplotlib 3.7.1
```

EDIT: xref https://github.com/astropy/astropy/issues/5481

**Comment by mhvk** [comment] 2024-03-06 21:50
`SkyCoord` (and `Time` and `Quantity`) share this behaviour with numpy `ndarray`:
```
In [1]: import numpy as np

In [2]: from collections.abc import Iterable

In [3]: a = np.array(0)

In [4]: isinstance(a, Iterable)
Out[4]: True

In [5]: iter(a)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [5], line 1
----> 1 iter(a)

TypeError: iteration over a 0-d array
```

This is an unfortunate consequence of python's ideas of what makes something iterable not being a good match to arrays, where one really wants to distinguish shape `()` from shape `(1,)`.

Anyway, regardless of what one thinks about the logic, astropy will have to continue to follow numpy in this regard, so I'll mark this issue as `close?` and `upstream fix required`.

p.s. Internally, we use `utils.isiterable` to test whether or not something can be iterated (which does a simple `try/except` around `iter()`).

**Comment by neutrinoceros** [comment] 2024-03-07 07:31
Kinda related, see https://github.com/numpy/numpy/issues/19833 for a precedent.

**Comment by eerovaher** [comment] 2024-03-07 14:38
This is an exact duplicate of #13172

**Comment by mhvk** [comment] 2024-03-07 15:12
Well, at least we independently give the same feedback and advice!

**Closed** 2024-03-15 05:58 UTC
Labels: Upstream Fix Required, Bug, coordinates, Close?, Duplicate, closed-by-bot
