### ISSUE TITLE
Affiliated package developer docs out of date? (references to missing template-package files)

### ISSUE THREAD

**Issue by perwin** [astropy/astropy#6546] opened 2017-09-13 13:07 UTC
The current version of the "Starting a new package" section in `docs/development/affiliated-packages.rst` has lots of references to copying files from the previously installed template package (e.g., `cp ../template/MANIFEST.in .` and numerous other examples).

However, the current version of the package template https://github.com/astropy/package-template doesn't have most of the referenced files. Specifically, it's missing:

- template/MANIFEST.in
- template/ah_bootstrap.py
- template/ez_setup.py
- template/setup.cfg
- template/setup.py

- template/packagename/ and everything under it
- template/docs/_templates
- template/docs/make.bat

**Comment by bsipocz** [comment] 2017-09-13 13:20
This is something on our radar, and is a duplicate of several other issues.

Until the docs gets sorted out, I suggest to use the docs directly from the package-template to set up a new package [0]. The infrastructure has been changed recently to use a cookiecutter to set up a package skeleton. 

The rendered version of the cookiecutter based package-template can be found in the ``rendered`` branch [1] while the "legacy" version this document is written about to is in the ``master`` branch [2]. Being legacy, the latter hasn't been updated in a while, and thus is expected to be not working with the latest version of some of the packages.

[0] - https://github.com/astropy/package-template

[1] - https://github.com/astropy/package-template/tree/rendered
[2] - https://github.com/astropy/package-template/tree/master

**Comment by perwin** [comment] 2017-09-13 18:16
Thanks; I'll take a look and see whether those are comprehensible (I'll admit that I initially have no idea what "a cookiecutter" is, but I can probably figure some of it out from context.

Could I suggest that updating the `docs/development/affiliated-packages.rst` page with a brief note about its currently being out-of-date might be helpful, given that it's one of the only publicly advertised links describing how to get started with Astopy affiliated packages?

(I did do a quick search to see if there were any issues relating to that page, but only found one from 2015 that wasn't really related.)

**Comment by bsipocz** [comment] 2017-09-13 18:47
Yes, we're planning to update that document next week, during a sprint.

**Comment by saimn** [comment] 2021-04-12 16:25
Closing since the documentation is now in the package-template: https://docs.astropy.org/projects/package-template/en/latest/

**Closed by saimn** 2021-04-12 16:25 UTC
Labels: Docs, Duplicate
