### ISSUE TITLE
Quantity converts interger array to float array with copy=False and thus copies

### ISSUE THREAD

**Issue by maxnoe** [astropy/astropy#10079] opened 2020-03-27 16:16 UTC
### Expected behavior

Creating a Quantity from another array with copy=False should keep data type and not copy the data.

### Actual behavior

Creating a quantity from an integer array with `copy=False` converts the input data to float
and thus copies.

### Steps to Reproduce
```python
import numpy as np
import astropy.units as u
a = np.zeros(10, dtype=int)
q = u.Quantity(a, copy=False)
print(q.dtype, np.shares_memory(q, a))
```
gives:
```
float64 False
```

**Comment by pllim** [comment] 2020-03-27 16:35
Maybe a workaround for now is to explicitly cast dtype?
```python
>>> import numpy as np 
>>> import astropy.units as u                                                                   
>>> a = np.zeros(10, dtype=int)                                                                 
>>> q = u.Quantity(a, copy=False, dtype=int)                                                    
>>> print(q.dtype, np.shares_memory(q, a))                                                      
int64 True
```

`Quantity`  has always cast int to float, AFAIK. To change that now would break some code downstream.

**Comment by mhvk** [comment] 2020-03-28 14:27
Hmm, that's somewhat tricky, and reading the docstring, the current behaviour is probably closest to how it is described: that there is an implicit dtype of `float` (or complex as needed). But your explicit example does not feel quite right.

Before going ahead and consider changing, though, we should think about implications. For instance, I can quite easily see a user doing something like `np.arange(10) << u.s` (mostly because I do that all the time myself!) - here, the `<<` implies `copy=False` (and that is in fact how it is implemented), but is it really a good idea to let the integers go through?  Almost certainly not what was intended...

One possible solution might be to go ahead and make `copy=False` not change the dtype, but have an additional possibility (e.g., `copy=None`??) for the case where we do want to copy if the dtype is not float/complex already.  Obviously, with that, there is a risk that it would break current (slightly poorly written) code, possibly giving quite hard to debug errors.

Of course, yet another alternative is just to make the current behaviour more explicit in the docstring, and just give the work-around that @pllim suggested (or to have a new flag for copy, say `copy='never'`).

Right now, my tendency would be to go for trying to document better, as I think one generally really should not use integers with units, and hence it is OK to make getting integer quantities a bit trickier if that avoids risks elsewhere. What do you think?

**Comment by MaxNoe** [comment] 2020-03-28 15:01
> Almost certainly not what was intended...

I tend to disagree. Everyone *should* be aware that `np.arange` as dtype integer by default. It has an dtype argument. 

I think that astropy non-copy / inplace operations should never mutate the dtype of something by default. I can see how this might implicate breakage though.

I would expect:
```
>>> a = np.arange(10) << u.s
>>> a.dtype
int
>>> b = np.arange(10, dtype=float) << u.s
float
```

**Comment by MaxNoe** [comment] 2020-03-28 15:07
@mhvk What woul you say to this example, where someone's trying to be explicit, but at the wrong part of the code:

```
np.arange(10, dtype=int) << u.s
```

**Comment by mhvk** [comment] 2020-03-28 17:57
@MaxNoe - I'm generally a fan of assuming users know what they are doing, but will admit that I very often forget the `.`, i.e., I do `np.arange(10)` instead of `np.arange(10.)`...

It seems to me the question in the end boils down to weighing the risks of users shooting themselves in the foot (especially since we would be changing behaviour) against the benefits of more easily supporting integer quantities. To me, the latter generally seem very unnatural, so I guess the first question is what use cases do require it? (In terms of actual physical quantities, I can only think of spin, but even there one would want half-integers!)

**Comment by MaxNoe** [comment] 2020-03-28 18:04
I agree. I was stubling over this while implementing a schema checker for fits files and sometimes, people split times in an integer part in seconds and a float part for the fractional seconds in fits.

**Comment by mhvk** [comment] 2020-03-28 18:55
Yes, that makes sense. I've sometimes wondered whether in `TimeDelta` we should have kept the option for the integer part to be something else than days. 

Practically, for `<<` to still convert to `float`, we'd need to introduce a new possible value for the `copy` argument. Within astropy, we can obviously change to use that new value, but I would remain worried about code outside astropy, which might implicitly rely on the current behaviour.

**Comment by pllim** [comment] 2020-03-29 23:47
I, for one, have code that relies on the implicit int to float conversion, so I am 👎 on changing the behavior now. I think that ship has sailed.

**Comment by dstansby** [comment] 2021-01-26 14:53
> To me, the latter generally seem very unnatural, so I guess the first question is what use cases do require it? (In terms of actual physical quantities, I can only think of spin, but even there one would want half-integers!)

I stumbled across the (to me) very surprising behavior of silently casting integers to floats in `Quantity`, in particular `type(u.Quantity(int(1), 'pixel').value)` isn't an integer! The use case I have is using `u.pix` - pixels are almost always integers.

Perhaps a good first step would be adding a prominent warning to the docstring that this happens.

**Comment by mhvk** [comment] 2021-01-26 16:12
@dstansby - People differ: for me, pixel units would almost always be float, since they would be centroids of something measured in a CCD image (say, of arc lines), which would then used to convert to real coordinates using a WCS.

But more generally, does it actually matter that internally it is not an integer? The only use I can think of is for indices, but why should quantities be usable as indices?

Anyway, I'm all for trying to document this better (though less sure a warning is appropriate - but let's discuss that in #11273)

**Comment by dstansby** [comment] 2021-01-26 16:17
I'm not saying pixel indices shouldn't be floating point, but that I shouldn't be forced into floats if I don't want to be. I do appreciate the arguments for forcing floats though, and can't come up with any compelling real word use cases for integer Quantities other than "casting to float feels wrong" 😆

Thanks for the quick feedback on the PR, I'll try and improve it, but otherwise I'm personally happy with the improving docs and closing this as wontfix.

**Comment by mhvk** [comment] 2021-01-26 16:22
OK, sounds good! (And yes appreciated that "casting to float feels wrong"...  the deviation from `np.array` behaviour was not done lightly, it is a bit like division, where if one is used to think in terms of int/float, it all works fine, but new users were forced to learn by painful experience to put `1.` instead of `1` in their code...)

**Comment by mhvk** [comment] 2021-04-12 18:14
Since we improved the docs in #11273, closing this.

**Closed by mhvk** 2021-04-12 18:14 UTC
Labels: units
