### ISSUE TITLE
SkyCoord is very slow with pandas dataframe

### ISSUE THREAD

**Issue by Gabriel-p** [astropy/astropy#13272] opened 2022-05-25 13:14 UTC
### Description
Defining a `SkyCoord`  object using a `pandas` dataframe is hundreds of times slower than simply using a `numpy` array

### Expected behavior
Same performance

### Steps to Reproduce
```python

import numpy as np
import astropy.units as u
from astropy.coordinates import SkyCoord
import pandas as pd
import time as t

N = 100000
ra = np.random.uniform(1, 200, N)
de = np.random.uniform(-70, 70, N)

df = pd.DataFrame()
df['ra'], df['dec'] = ra, de

# Very slow
s = t.time()
gc = SkyCoord(ra=df['ra'] * u.degree, dec=df['dec'] * u.degree)
print(t.time() - s)

# Not slow
s = t.time()
gc = SkyCoord(ra=df['ra'].values * u.degree, dec=df['dec'].values * u.degree)
print(t.time() - s)
```

### System Details

Linux-5.5.0-050500-generic-x86_64-with-glibc2.17
Python 3.8.12 (default, Oct 12 2021, 13:49:34) 
[GCC 7.5.0]
Numpy 1.21.2
pyerfa 2.0.0
astropy 5.0
Scipy 1.7.3
Matplotlib 3.5.0

**Comment by eerovaher** [comment] 2022-05-25 13:58
The underlying issue is described in more detail in #11247, and it has nothing to do with `SkyCoord`.

A second solution would be to use `<<` instead of `*` because `pandas` does not think it can do that so `astropy` gets the chance of creating a `Quantity`.

**Comment by taldcroft** [comment] 2022-05-25 14:05
It is worth noting another pathway which give the correct answer (i.e. not a bug) but is indeed very slow:
```
In [59]: s = Series(np.linspace(1, 2, 100000))

In [60]: %time SkyCoord(ra=s, dec=s, unit='deg,deg')
CPU times: user 2.62 s, sys: 15 ms, total: 2.63 s
Wall time: 2.63 s
```
I suspect that under the hood there is a `*` to apply the unit instead of `<<`. If so changing to `<<` might fix this remaining performance problem.

**Comment by Gabriel-p** [comment] 2022-05-25 14:38
I don't understand the `wont-fix` tag. If `SkyCoord` is not meant to work with a `pandas` dataframe then an error or at least a warning should be raised, right?

**Comment by Gabriel-p** [comment] 2022-05-25 14:45
I get the decision of not allowing that input, but then the call to `SkyCoord` should either fail or at least warn the user about the issue. Currently there is no indication that this is a bad input and `SkyCoord` _appears_ to be working properly, just very very slow.

**Comment by taldcroft** [comment] 2022-05-25 14:53
@Gabriel-p - pandas `Series` is not listed in the documentation as an allowed input to `SkyCoord`: https://docs.astropy.org/en/stable/coordinates/skycoord.html#initialization-syntax. 

We do try to make the code robust in the case of unexpected inputs, but this can be a bit of whack-a-mole and there is a question of resources to address this one case. PR's certainly welcome if anyone has the time.

For pandas Series this is a wee bit tricky because it is mostly working (which actually I don't understand).

**Comment by Gabriel-p** [comment] 2022-05-25 17:06
@taldcroft I understand what you mean but I can almost guarantee there are currently lots of people out there using `pandas` Series as input, and simply assuming that `astropy` is slow.

Would a warning be a reasonable compromise?

**Comment by taldcroft** [comment] 2022-05-26 10:47
I removed the Close? and wont-fix labels. This is something that is worth addressing albeit at moderate priority.

**Comment by Gabriel-p** [comment] 2022-05-26 12:34
I can try to create a PR with a warning although it could take me some time to understand the inner workings of the `SkyCoord` class. Before I attempt that though, is there some kind of consensus on adding such a warning?

**Comment by pllim** [comment] 2022-05-26 12:39
Re: add warning -- Since this is about performance, the warning has to be somewhere that won't add to the performance problem. And if you pass in Series in RA and Series in Dec, you should still only see the warning once. And if this PR happens in the next few months, maybe v5.2 is reasonable.

**Comment by MridulS** [comment] 2024-01-16 13:15
The pandas example above now returns an error and the user won't really be able to trip up on this slow code path.

```
UnitTypeError: Angle instances require units equivalent to 'rad', but no unit was given.
```

Let's close this issue?

Tested with:
pandas 2.1.4
astropy 6.1dev

**Comment by mhvk** [comment] 2024-01-16 15:00
@MridulS - thanks! The error will not be super helpful, but I think it is good enough to close this; as is, this issue is not very actionable.

**Closed as completed by mhvk** 2024-01-16 15:00 UTC
Labels: coordinates, Performance, wont-fix
