### ISSUE TITLE
What was the motivation for astropy.{units,constants,uncertainties}, when there are pint and uncertainties?

### ISSUE THREAD

**Issue by doronbehar** [astropy/astropy#15440] opened 2023-10-05 09:53 UTC
### What is the problem this feature will solve?

After years of using [pint](https://pint.readthedocs.io/en/stable/) and [uncertainties](https://uncertainties-python-package.readthedocs.io/en/latest/), I wanted to try out astropy's `constants`, `units` and `uncertainties` modules as an alternative. I wanted to get rid of [pint](https://pint.readthedocs.io/en/stable/) and [uncertainties](https://uncertainties-python-package.readthedocs.io/en/latest/), because I felt they are a bit abandoned / unmaintained.

After very basic testings, the experience with astropy's `units` and `constants` was satisfying, like with pint. However I was disappointed by the possibilities suggested by the `uncertainties` module, and worth mentioning is https://github.com/astropy/astropy/issues/13902 .

### Describe the desired outcome

Personally, I wish that the very high quality developers in this organization would have contributed to the above python packages, and would have improved the compatibility experience of [pint](https://pint.readthedocs.io/en/stable/) and [uncertainties](https://uncertainties-python-package.readthedocs.io/en/latest/) with numpy and even with astropy if needed - instead of attempting to develop it all in house.

In general, my primary impression of astropy is that it is monorepo sort-of, with a lot of separate modules that perhaps don't necessarily need to be developed together? I'm not sure, I'm just inviting you to a discussion :)

**Comment by mhvk** [comment] 2023-10-05 11:56
@doronbehar - for `uncertainty`, the problem is that `uncertainties` is essentially made for scalars only (and array is just an array of uncertainties objects). I actually have a now-closed PR (#3715) that made a proper array-aware version, but never finished it. One problem is easy to explain: assume I have a CCD image with errors and subtract the mean (i.e., `b = a - a.mean()`). Now *every* pixel in `b` is covariant with every pixel in `a`, i.e., the covariance matrix becomes huge if `a` is a decent-sized images. So, somehow one has to be able to tell for which cases to drop the matrix. 

More technically, correctly dealing with numpy broadcasting in creating the covariance matrices proved quite challenging.

Anyway, suggestions for how to approach this are quite welcome.

p.s. For units, astropy derived from pynbody, which I think predates pint. There is definitely a case for having just one units package for everybody, but that takes effort, especially in mutually agreeing which parts of which package are "best".

**Comment by pllim** [comment] 2023-10-05 13:38
For units and constants, please discuss here:

* https://github.com/astropy/astropy/issues/13460

**Comment by pllim** [comment] 2023-10-05 13:43
I do not see this issue really going anywhere and mhvk already gave an explanation above, with linked issue(s).

Re: monorepo -- Astropy Project tries to find the balance between "monorepo" and having to juggle many packages that depend on each other. We ran into problems of circular dependency a couple of times and also get complains of someone just wants to read FITS file but get all these other stuff. There is no single solution that would make everyone happy. Currently, we aim to have `astropy` (this repo) contain what we consider "core" functionalities and the farm out the rest to Coordinated and Affiliated. See https://www.astropy.org/affiliated/ for more info.

Therefore I am closing this issue. Discussion is better to be had in one of the other more social outlets. See https://www.astropy.org/help.html

However, if you have actionable items (other than making us maintain `pint` or `uncertainties`, which is out of scope), feel free to open new issues for each of them if there are no existing issues already. Thank you.

**Closed by pllim** 2023-10-05 13:43 UTC
Labels: units, constants, question, uncertainty

**Comment by doronbehar** [comment] 2023-10-05 13:59
Thank you all for your comments :) I wasn't sure whether it'd be appropriate for the issue tracker or the forum, and indeed this is not actionable :+1. Thanks again!

**Comment by mhvk** [comment] 2023-10-05 15:03
No worries, @doronbehar. For `uncertainty`, any ideas what best behaviour should be are definitely welcome; I wish `uncertainties` helped us out of the box! For units, the issue @pllim linked to is a good one.
