### ISSUE TITLE
Add persistence of Table indices

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy#6925] opened 2017-12-04 12:21 UTC
Table indices would be more useful if they could be stored to a disk file.  The mixin column serialization machinery could be extended to handle this special case.

**Comment by ananyashreyjain** [comment] 2018-01-12 14:24
@taldcroft do you want store the information that index is created (and the columns for which the index is created)  on the disk file and then creating index again when reading the file or do you want to store a table showing index(something like output you get using  `Table.indices(['column'])` )on file?

**Comment by ananyashreyjain** [comment] 2018-01-19 06:22
@taldcroft  just a reminder to reply.

**Comment by taldcroft** [comment] 2018-01-19 11:27
@ananyashreyjain - it should be storing the actual index or indices so that they don't need to be recomputed.

**Comment by pllim** [comment] 2024-08-27 17:21
Closed as duplicate of https://github.com/astropy/astropy/issues/16836 as @saimn suggested.

**Closed** 2024-08-27 17:21 UTC
Labels: table, Package-intermediate, Effort-medium, Duplicate, Enhancement
