### ISSUE TITLE
BUG: failure duing v4.0rc1 wheel build

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy#9628] opened 2019-11-19 03:28 UTC
Failure during building 3.6 wheels, relating to IERS/leapseconds/possibly caching. There is a slight change that the wheel needs a patch, but I suspect it's rather something here:

https://travis-ci.org/MacPython/astropy-wheels/jobs/613813972#L1387

```
______________ TestDefaultAutoOpen.test_system_file_never_expired ______________

self = <astropy.utils.iers.tests.test_leap_second.TestDefaultAutoOpen object at 0x7fb671301198>

tmpdir = local('/tmp/pytest-of-root/pytest-0/test_system_file_never_expired0')

    @pytest.mark.skipif(not os.path.isfile(SYSTEM_FILE),

                        reason=f'system does not have {SYSTEM_FILE}')

    def test_system_file_never_expired(self, tmpdir):

        self.remove_auto_open_files('erfa')

        with iers.conf.set_temp('system_leap_second_file', SYSTEM_FILE):

            ls = iers.LeapSeconds.open()

            assert ls.expires > self.good_enough

            assert ls.meta['data_url'] in (iers.IERS_LEAP_SECOND_FILE,

                                           SYSTEM_FILE)

    

            # Also check with a "built-in" file that is expired

            fake_file = make_fake_file('28 June 2017', tmpdir)

            iers.LeapSeconds._auto_open_files[0] = fake_file

            ls2 = iers.LeapSeconds.open()

            assert ls2.expires > Time.now()

>           assert ls2.meta['data_url'] == SYSTEM_FILE

E           AssertionError: assert 'https://hpie...ap_Second.dat' == '/usr/share/z...-seconds.list'

E             - https://hpiers.obspm.fr/iers/bul/bulc/Leap_Second.dat

E             + /usr/share/zoneinfo/leap-seconds.list

/venv/lib/python3.6/site-packages/astropy/utils/iers/tests/test_leap_second.py:241: AssertionError

```

**Comment by astrofrog** [comment] 2019-11-19 11:28
Duplicate of https://github.com/astropy/astropy/issues/9497

**Closed by astrofrog** 2019-11-19 11:28 UTC
Labels: Affects-dev, Bug, time, utils, utils.iers
