### ISSUE TITLE
Cannot fit to compound model

### ISSUE THREAD

**Issue by gkanarek** [astropy/astropy#5467] opened 2016-11-08 00:57 UTC
I'm not sure if #3783 is the same - but you can't currently fit a CompoundModel:

```python
from astropy.modeling import fitting
from astropy.modeling.polynomial import Polynomial2D
import numpy as np

x, y = np.mgrid[:100,:100]
z = x**2 - x*y + y
model = Polynomial2D(2) + Polynomial2D(2)
fitter = fitting.LinearLSQFitter()

print(fitter(model, x, y, z))
```
This leads to:
```Python traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "{my-python-path}/site-packages/astropy/modeling/fitting.py", line 287, in __call__
    lhs = model_copy.fit_deriv(x, y, *model_copy.parameters)
TypeError: 'NoneType' object is not callable
```

**Comment by pllim** [comment] 2016-11-08 15:23
What version of Astropy are you using?

**Comment by gkanarek** [comment] 2016-11-08 15:24
This is 1.2.1

**Comment by gkanarek** [comment] 2016-11-08 15:26
Also, let me say that it's not just Polynomial2D - I wasn't able to get any 2D compound models to work. Didn't try 1D models.

**Comment by pllim** [comment] 2016-11-08 15:30
Okay, I see the same traceback in the dev version as well.

**Comment by pllim** [comment] 2016-11-09 14:56
#3098 somehow implies that fitting should be possible in compound models. Perhaps this could be a bug.

**Comment by gkanarek** [comment] 2016-11-09 16:03
Agreed. [This](http://docs.astropy.org/en/stable/modeling/compound-models.html#compound-models-with-model-instances) is pretty explicit about it.

I think the problem is that the CompoundModel constructors don't do anything with the underlying classes' fit_deriv - which makes sense, since it's probably non-trivial to come up with a general implementation to handle it (if one exists). So what happens with other types of user-defined models that don't have a fit_deriv?

**Comment by nden** [comment] 2016-11-09 16:12
I haven't had time to look at this yet but it sounds like a bug. 1D compound models can be fit.
I suspect you would be able to run your example using one of the iterative fitters.

**Comment by pllim** [comment] 2016-11-09 16:13
The weird thing is the fitting example for Gaussian compound models work fine. See http://docs.astropy.org/en/latest/modeling/index.html#compound-models (scroll down just a bit). I can run it on latest dev.

**Comment by pllim** [comment] 2016-11-09 16:21
Update: Works with this particular fitter:
```python
>>> m_fit = fitter(model, x, y, z)
WARNING: Model is linear in parameters; consider using linear fitting methods. [astropy.modeling.fitting]
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 0.000823040489615
            Iterations: 13
            Function evaluations: 229
            Gradient evaluations: 13
```

**Comment by mirca** [comment] 2016-11-09 16:38
Maybe the bug is in the `LinearLSQFitter`?
With `LevMarLSQFitter` it works just fine.

**Comment by pllim** [comment] 2016-11-09 16:39
Yes, I agree. Looking at the codes, there is no handling of `if model_copy.fit_deriv is None`.

**Comment by embray** [comment] 2021-07-08 11:31
This is a duplicate of the more recent (but more developed) issue #6038.  There have also been some band-aids to this issue including documentation updates and better error handling.

**Closed by embray** 2021-07-08 11:31 UTC
Labels: Bug, Duplicate, modeling
