### ISSUE TITLE
Deprecate blackbody functions in analytic_functions

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#6160] opened 2017-06-06 13:21 UTC
*https://github.com/astropy/astropy/pull/4855 is not merged yet, but this is a reminder to work on this issue after merging*

In https://github.com/astropy/astropy/pull/4855, I added a fittable 1D blackbody model, but this doesn't replace the functions in astropy.analytic_functions. We should make the radiance functions in astropy.analytic_functions into models that support units.

Note that the Blackbody1D model includes 'vertical' scaling which is useful for most fitting applications. However, the functions in analytic_functions are just to compute the plain Planck function which doesn't include scaling, so these should be separate (probably non-fittable) models.

We should also then add a documentation page about the various blackbody models.

Milestoning as 2.0 as at least the deprecation should be in place for 2.0.

**Comment by pllim** [comment] 2017-06-06 14:29
This is a duplicate of #5780.

**Closed by pllim** 2017-06-06 14:29 UTC
Labels: analytic_functions, Feature Request, modeling
