### ISSUE TITLE
Version 4.0.2 fails to build with pip3 due to missing dependency cython

### ISSUE THREAD

**Issue by basvandertol** [astropy/astropy#10834] opened 2020-10-12 13:53 UTC
Starting from a bare ubuntu image
`docker run -it ubuntu:18.04 /bin/bash`

Trying to install astropy in docker with pip3
`root@77dc6379e544:/# apt-get update`
`root@77dc6379e544:/# apt-get -y install python3-pip`
`pip3 install astropy`

This fails with `error: [Errno 2] Could not find C/C++ file astropy/table/_np_utils.(c/cpp) for Cython file astropy/table/_np_utils.pyx when building extension astropy.table._np_utils. Cython must be installed to build from a git checkout.: 'astropy/table/_np_utils.c'`

Installing cython
`pip3 install cython`

resolves the issue
`pip3 install astropy` => success

Proposed resolution: astropy should list cython as a dependency.

**Comment by astrojuanlu** [comment] 2020-10-12 14:05
A quick way to workaround this is to tell pip to use only wheels:

```
# pip3 install astropy --only-binary :all:  
Collecting astropy
  Downloading https://files.pythonhosted.org/packages/da/c2/07b8244febf380f8fe43d87ab906bfff70221ba095df3fe85cf89957c63d/astropy-4.0.1.post1-cp36-cp36m-manylinux1_x86_64.whl (6.5MB)
    100% |################################| 6.5MB 210kB/s 
Collecting numpy>=1.16 (from astropy)
  Downloading https://files.pythonhosted.org/packages/b8/e5/a64ef44a85397ba3c377f6be9c02f3cb3e18023f8c89850dd319e7945521/numpy-1.19.2-cp36-cp36m-manylinux1_x86_64.whl (13.4MB)
    100% |################################| 13.4MB 94kB/s 
Installing collected packages: numpy, astropy
Successfully installed astropy-4.0.1.post1 numpy-1.19.2
```

`python3-pip` brings pip 9.0.1, which is somewhat old, and doesn't support `--prefer-binary`. But most importantly, it does not understand the build requirements that are alread in `pyproject.toml`:

https://github.com/astropy/astropy/blob/v4.0.2/pyproject.toml#L10

However, doing the right thing (i.e. creating a virtual environment, upgrading pip, and using it to install Astropy without `sudo` permissions) solves the problem:

```
# apt-get -y install python3-venv
# python3 -m venv /tmp/venv
# source /tmp/venv/bin/activate
# python -m pip install -U pip setuptools
# pip3 install astropy  # Correctly installs manylinux2010 wheel
# pip3 uninstall -y astropy
# pip3 install astropy --no-binary :all:  # Correctly installs Cython and other dependencies to build from source
```

I am not sure there is anything the Astropy project can do for pip 9.0.1 users.

**Comment by basvandertol** [comment] 2020-10-12 14:12
Thanks! That was fast, and very helpful.

**Comment by Cadair** [comment] 2020-10-12 14:18
This is a real regression in the build system changes for 4.0.2. :(

**Comment by Cadair** [comment] 2020-10-12 14:19
@astrofrog sadness.

**Comment by Cadair** [comment] 2020-10-12 14:23
That being said, while this is a change in build system for 4.0.2 it might actually be a conscious one now I think about it, because of the addition of a pyproject.toml file, maybe @astrojuanlu was right. and there is nothing to be done here.

**Comment by astrofrog** [comment] 2020-10-12 14:26
I will investigate - is the issue that pip is too old to pick up pyproject.toml? 🤔

**Comment by Cadair** [comment] 2020-10-12 14:27
I think so, pip 9 is real old now.

**Comment by astrofrog** [comment] 2020-10-12 14:28
Ah yes I see that above - I will have a think about whether we can avoid this, but the issue will happen with 4.1 too.

**Comment by astrofrog** [comment] 2020-10-12 14:30
I think I know how to fix it

**Comment by Cadair** [comment] 2020-10-12 14:34
Do we really need to keep support for pip 9, especially on 4.1?

**Comment by astrofrog** [comment] 2020-10-12 14:44
@Cadair - I'm not suggesting fixing it on 4.1 to be clear, I'm just interested in fixing it on LTS which I think is a one-line fix.

**Comment by astrofrog** [comment] 2020-10-12 14:56
See https://github.com/astropy/astropy/pull/10837 for a possible fix.

**Comment by bsipocz** [comment] 2020-10-23 21:13
This has been fixed now, please reopen if you run into the same issue with a more recent version.

**Closed by bsipocz** 2020-10-23 21:13 UTC
Labels: Bug, installation
