### ISSUE TITLE
[4.1RC2] Astropy module may return the wrong version

### ISSUE THREAD

**Issue by olebole** [astropy/astropy#10760] opened 2020-09-23 07:32 UTC
### Description

When I have a `PKG-INFO` file in the current working dir, astropy shows the version number from this file instead of its hown one. This is something what I observed while packaging the new "photutils" version, where the wrong path is taken during pytest.

### Expected behavior

Astropy should show its own version number under all circumstances

### Actual behavior

The version number is wrong if a `PKG-INFO` file is present.

### Steps to Reproduce

Shell script:
```shell
$ python3 -c "import astropy; print(astropy.__version__)"
4.1-rc2
$ echo Version: 1.2.3 > PKG-INFO
$ python3 -c "import astropy; print(astropy.__version__)"
1.2.3
```

### System Details

Linux-5.8.0-1-amd64-x86_64-with-glibc2.29
Python 3.8.5 (default, Aug  2 2020, 15:09:07) 
Numpy 1.19.1
astropy 1.2.3   :grin: :grin: :grin:
Scipy 1.5.2
Matplotlib 3.3.2

I didn't observe this with 4.0.1.post1.

**Comment by Cadair** [comment] 2020-09-23 10:20
I think this is by design. I am a little confused as to why this is a problem?

**Comment by Cadair** [comment] 2020-09-23 10:24
Actually, do you have `setuptools_scm` installed in the environment where you are running into this?

**Comment by olebole** [comment] 2020-09-23 10:34
When you use astropy, you can't be sure what is in the current directory, and a basic functionality like returning the version should be independent of it.
Simple use case (this is mainly where I observed it): One develops a package that depends on astropy and pytest-astropy-header, and starts pytest from the package root (which contains a `PKG-INFO`). Then, pytest-astropy-header does the following: https://github.com/astropy/pytest-astropy-header/blob/f109f5c400f9d0e169693d575b735505fa5b130c/pytest_astropy_header/display.py#L42-L56

```python
    if astropy_version == 'unknown':  # assume developer version
        ASTROPY_LT_30 = ASTROPY_LT_40 = False
    else:
        ASTROPY_LT_30 = LooseVersion(astropy_version) < '3.0'
        ASTROPY_LT_40 = LooseVersion(astropy_version) < '4.0'


    # If using a version of astropy that has the display plugin, we make sure that
    # we use those variables for listing the packages, in case we choose to let
    # that plugin handle things below (which we do if that plugin is active).
    if ASTROPY_LT_30:
        from astropy.tests.pytest_plugins import (PYTEST_HEADER_MODULES,
                                                  TESTED_VERSIONS)
    elif ASTROPY_LT_40:
        from astropy.tests.plugins.display import (PYTEST_HEADER_MODULES,
                                                   TESTED_VERSIONS)
```

Since `astropy.__version__` now returns the version of the package one is working on and not the astropy version, the wrong import statement is executed here (in my case the `ASTROPY_LT_30`), which fails.
The same probably also happens when you execute `setup.py` of the local package; this is usually done from the root directory of your package. If this contains somwhere a dependency on the astropy version, it will fail.

setuptools-scm is installed, but this is not a requirement to run the installed version of astropy, it is only required for the installation, right?

**Comment by Cadair** [comment] 2020-09-23 11:01
Ah I somehow missed the "current working directory" thing. 

This is really strange this behaviour has to be coming from the call to `setuptools_scm.get_version` which was added to correctly detect git versions when doing dev installs. It wouldn't happen if `setuptools_scm` wasn't installed (expected in a normal user install).

> The same probably also happens when you execute setup.py of the local package; this is usually done from the root directory of your package.

Why are you executing `setup.py` files :wink: 

> setuptools-scm is installed, but this is not a requirement to run the installed version of astropy, it is only required for the installation, right?

It's only required to install from a git checkout, a generated tarball shouldn't need it (although now I think about it we probably install it as a PEP 517 build dep anyway).

I am half tempted to chalk this up as a `setuptools_scm` bug, but I guess we should do some investigating on it first. I tried to dig though the scm source to work out where it does this, but it's all entrypoints and deep callback hell.

**Comment by olebole** [comment] 2020-09-23 11:09
Is there a reason for the `setuptools_scm` code here at all? The generated code in `astropy/version.py` is
```python
try:
    from setuptools_scm import get_version
    version = get_version(root='..', relative_to=__file__)
except Exception:
    version = '4.1rc2'
else:
    del get_version  # clean up namespace
```
and this code fragment sounds to me like "calling for trouble": The version number may depend on whether `setuptools_scm` is actually installed or not. I would rather assume that the version number should be a fixed string in a given installed package. This was however probably generated by `setuptools_scm` itself during the astropy installation, right?

**Comment by pllim** [comment] 2020-09-23 12:32
That code is from a template that @astrofrog added in #9726 . Maybe he can explain.

**Comment by pllim** [comment] 2020-09-23 12:33
I think this should be fixed before final 4.1 release, if possible.

**Comment by olebole** [comment] 2020-09-23 12:37
I would need this fixed for Debian, since it breaks the build time tests of reverse dependencies. Working around this by patching the version dependent lines in [`pytest-astropy-header`](https://github.com/astropy/pytest-astropy-header/blob/f109f5c400f9d0e169693d575b735505fa5b130c/pytest_astropy_header/display.py#L42-L56) sounds a bit hacky.

**Comment by pllim** [comment] 2020-09-23 12:45
Okay, thanks for the info. I noted in the [RC wiki](https://github.com/astropy/astropy/wiki/astropy-v4.1-release-candidate-(RC)-Testing) that this is a blocker.

**Comment by Cadair** [comment] 2020-09-23 12:46
The setuptools_scm code is there to allow for dev version strings to be correct (i.e. update when you do things in the git repo).

**Comment by Cadair** [comment] 2020-09-23 12:50
@olebole just to check I understand this error is occuring when you are building another package, which has a build time dep on `setuptools_scm` and astropy is installed normally from a deb package?

**Comment by olebole** [comment] 2020-09-23 12:54
Yes, this is my problem. Many astropy related packages (like photutils) use `setuptools_scm` as well.

**Comment by Cadair** [comment] 2020-09-23 12:56
If you are installing just from tarballs, I think you can safely drop the `setuptools_scm` requirement, I am reasonably sure it's not needed to run `setup.py install` from the unpacked tarball (it is needed to make the tarball). I just tested this with a tarball of 4.1rc2.

**Comment by Cadair** [comment] 2020-09-23 12:56
(We should still investigate the actual bug, but maybe that's a good fix in the mean time)

**Comment by Cadair** [comment] 2020-09-23 13:02
Going to ping @embray on this given comments in https://github.com/pypa/setuptools_scm/issues/143 and https://github.com/pypa/setuptools_scm/issues/273

**Comment by saimn** [comment] 2020-09-23 13:03
I don't understand why you would have a PKG-INFO file in your current working directory. This file is not like a random file, it contains the metadata and is generated by `setup.py sdist`, so arguably if it's present then it should be used. But normally this file is present only in sdist archives, and in `.egg-info` directories.

**Comment by Cadair** [comment] 2020-09-23 13:04
I am assuming @olebole has a PKG-INFO in their current directory because the debian build system is building (photutils) in an unpacked tarball of photutils.

**Comment by Cadair** [comment] 2020-09-23 13:12
It looks like the only option we have from the astropy side here is to change / improve / remove the call to setuptools_scm in `version.py`. I think what we are trying to achieve by doing that (accurate versions with editable installs) is not supported by setuptools & setuptools_scm at the moment, even though it is a useful feature.

I think we can either add a couple of checks [along these lines](https://github.com/pypa/setuptools_scm/issues/273#issuecomment-519812675) or [like @embray suggested here](https://github.com/pypa/setuptools_scm/issues/143#issuecomment-672878863) or some combination of the two to make this more robust.

**Comment by embray** [comment] 2020-09-27 14:20
I don't doubt that it's a real issue, but I wasn't able to reproduce it with @olebole's instructions.  Simply creating a PKG-INFO file in my current directory did not change the version reported by setuptools_scm.

**Comment by embray** [comment] 2020-09-27 14:32
Nevermind, I was able to reproduce iff
1) astropy is installed in non-editable mode
2) my current working directory is not in the astropy source repo
3) setuptools_scm is installed (obviously needed for it to invoke this automatic behavior)

**Comment by embray** [comment] 2020-09-27 14:47
I think as @Cadair suggested, my suggested pattern [here](https://github.com/pypa/setuptools_scm/issues/143#issuecomment-672878863) would work, as it would ensure that `setuptools_scm` is only ever invoked from the source checkout of astropy--when astropy is installed from a wheel a different `version.py` (or separate file like `_version.py`) whose presence ensures that `setuptools_scm` is never invoked.

**Comment by embray** [comment] 2020-09-27 15:01
Hmm, for some reason I recalled that setuptools_scm only writes the "version" file when building a wheel, but it seems it also does it even when running `pip install -e .` which would make it counter to what we want here.

I also noticed that `astropy/version.py` is checked into the repo despite being a generated file?

**Comment by embray** [comment] 2020-09-27 15:38
I think I have a solution--working on it now.

**Comment by embray** [comment] 2020-09-27 15:43
How are we managing backports these days?  Should this issue be backported to a bugfix release?

[These docs](https://docs.astropy.org/en/latest/development/workflow/maintainer_workflow.html#using-milestones-and-labels) which I wrote in 8f1b111e still exist, but appear to be outdated: It doesn't seem there are `backport-*` labels anymore.

**Comment by embray** [comment] 2020-09-27 15:59
Hrm :/  Well my idea works for creating sdist tarballs, but not for wheels.  My idea was to have a file only included in the repository but that isn't installed.  It works when building sdists, but it appears that MANIFEST.in is totally ignored when building wheels (and hence when running `pip install .` or `pip wheel`): https://github.com/pypa/setuptools/issues/511

**Comment by embray** [comment] 2020-09-27 16:12
A workaround was to move the files I don't want installed into a package, and then exclude that package from the set of installed packages.  It's actually not terrible, as it creates a place to put code that we might want to use in development but that shouldn't be installed.

**Comment by eteq** [comment] 2020-10-06 17:43
@embray 

> How are we managing backports these days? Should this issue be backported to a bugfix release?

There's a script in https://github.com/astropy/astropy-procedures that searches for backports based on the milestone set in github, and produces a list of cherry-picks to be done.  Then you cherry-pick merge commits onto the vZ.Y.x branch appropriate for Z.Y.  Of course in practice that sometimes requires manual conflict resolution some of the time, in which case if it's easy it can be done directly in the maintenance branch, and if it's not easy we sometimes ask the original PR author (or other knowledgeable person) to do a PR against the maintenance branch.

Does that clear that up?

**Comment by eteq** [comment] 2020-10-06 20:29
(Also, I agree this is a blocker for 4.1!)

**Comment by embray** [comment] 2020-10-07 18:37
Makes sense. I'll have a look at it.  I'm still not entire clear how the script determines what fixes should be backported.

**Closed** 2020-10-10 09:23 UTC
Labels: :fire:, Bug, installation

**Comment by eteq** [comment] 2020-10-12 15:26
@olebole - #10774 should have fixed this, but can you confirm this is now resolved for you in the same environment you did rc2 testing? (if it's working now I think we're set to release!)

**Comment by olebole** [comment] 2020-10-13 08:29
@eteq I can confirm (locally tested) that this is fixed.

**Comment by olebole** [comment] 2020-10-13 08:31
But when uploading, I see a number of test failures not observed before, which I need to figure out. Before releasing, could you give me a day?

**Comment by olebole** [comment] 2020-10-13 12:13
OK, disregard. The problems was mainly #10675 where I accidently overwrote the patch to skip it, and a minor problem with `test_wcsapi_extension()`. The latter needs some investigation, but is for sure not problematic.
