### ISSUE TITLE
Performance regression in mask creation from table column

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#2986] opened 2014-09-26 14:28 UTC
Thanks to the awesomeness that is `asv`, I noticed a performance regression when doing things like 

``` python
table['a'] > 0.6
```

The time in the benchmark in https://github.com/astropy/astropy-benchmarks/pull/10 went from 10 to almost 200µm, so a factor of 20 more. This is due to https://github.com/astropy/astropy/pull/2963

Now maybe this is an acceptable performance penalty, but I just wanted to report it since it's a pretty big jump!

cc @mhvk @mdboom @taldcroft

**Comment by embray** [comment] 2021-07-06 09:39
The performance regression originally reported in this issue was fixed a long time ago according to the performance report: https://www.astropy.org/astropy-benchmarks/#table.TimeMaskedTable.time_column_make_bool_mask

It since regressed a little bit again but not so dramatically (and now we lack up-to-date benchmarks to compare to more recently...)

So this issue can probably be closed as OBE.

**Closed** 2021-07-06 10:14 UTC
Labels: Close?, Performance, table
